### ISSUE TITLE
一键脚本到CF申请通配符证书选择否会直接跳出脚本

### ISSUE THREAD

**Issue by Newbie-L** [mack-a/v2ray-agent#1001]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
使用一键脚本安装的过程中，选择1.安装——选择1.Xray-core——输入二级域名——输入默认端口——使用DNS API申请证书——使用默认（cloudflare）Token申请——到是否进行API申请通配符证书时选择否，会直接跳出脚本
## 2.安装失败的log或者截图
![IMG_4314](https://github.com/mack-a/v2ray-agent/assets/18143348/05276fb1-6f80-4e41-a623-726a8d58be10)
## 3.系统版本
Ubuntu 22.04.4 LTS
## 4.脚本版本
v3.2.37
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```  
- 协议(VLESS+TLS_Vision+TCP)
```
无
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
1.全部安装
```

**Comment by mack-a** [comment]
目前不支持非通配符dns api申请证书，后续可能会增加此步骤。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.10
