### ISSUE TITLE
Hysteria2设置端口跳跃后连不上了

### ISSUE THREAD

**Issue by x64bugreport** [mack-a/v2ray-agent#1002]
## 1.问题描述
Hysteria2设置端口跳跃后连不上了，删除端口跳跃后恢复
设置顺序4 3 1 端口范围35000-36000
## 3.系统版本
debian11
## 4.脚本版本
v3.2.37
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
xray-core + sing-box

- 协议
VLESS+TLS_Vision+TCP
Hysteria2

- 安装方式（1.全部安装、2.任意组合安装）
2
先组合安装的xray内核的VLESS+TLS_Vision+TCP 然后在第一级菜单4安装的Hysteria，设置端口跳跃后客户端就连不上了，删除端口跳跃，使用单端口就可以正常连通。

**Comment by mack-a** [comment]
debian44 是什么系统版本

**Comment by x64bugreport** [comment]
sorry 键盘按11 按跑偏了

**Comment by x64bugreport** [comment]
> debian44 是什么系统版本

sorry 键盘按11 按跑偏了

**Comment by mack-a** [comment]
客户端用的哪一个？
