### ISSUE TITLE
clashmeta for android 拉取不到配置

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#1003]
## 1.问题描述
v2ray-agent 脚本升级到最新版，部署了hysteria2端口跳跃后，clashmeta for android客户端，可以更新，但代理没有任何节点信息。
## 2.安装失败的log或者截图
![fd83acf7797c89f73599b1bcb95c1b5](https://github.com/mack-a/v2ray-agent/assets/43665641/bf69a275-7655-4b79-ac15-1ba3c2d9d9fb)

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v3.2.27
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
sing-box
```  
- 协议(VLESS+TLS_Vision+TCP)
```
Hysteria2 VLESS+Reality+Vision VLESS+Reality+gRPC Tuic
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```

**Comment by mack-a** [comment]
看看你使用的clashmeta for android是否支持端口跳跃。

**Comment by bettswang** [comment]
看着像不支持。。。我去那边问问看吧，因为用的都是clashmeta的内核，我windows上 使用的clashverge是正常拉取的。

**Comment by bettswang** [comment]
我直接在配置中，增加port的关键字，让客户端可以正常拉去配置，但是这样我不知道端口跳跃是否生效就是了。
