### ISSUE TITLE
大佬，sing-box内核能增加单独支持VLESS+TLS+WS安装支持吗？

### ISSUE THREAD

**Issue by x64bugreport** [mack-a/v2ray-agent#1004]
其实我就是想问问，能不能只开sing-box一个内核，兼容下VLESS+TLS+WS，这样就不用在同时跑xray内核了(主要是VPS配置辣鸡。。。)。搞来搞去，发现Hysteria2、Tuic 、VLESS+TLS_Vision+TCP、VLESS+TLS+WS表现好一些，
![1](https://github.com/mack-a/v2ray-agent/assets/34920463/4b543314-e3b1-4d79-b8ec-c876be1bb2bd)
sing-box内核选项下木有VLESS+TLS+WS。

PS:一些闲言碎语不看也罢。
我对各类协议原理上认知基本都是从大佬博客上看来的，其实我已经好久没折腾过了，之前用的还是大佬上次停更2.7.3的版本，直到最近vps的nigix莫名其妙启动不了，加上系统也是很老的centos索性直接重装debian11了，然后去大佬博客发现原来又多了一堆协议玩法，然后开始重新搭，测试下来发现：
1.VLESS+Reality+uTLS+Vision这种模式(用的自己的域名)，时好时坏，经常就会断一下，开启后用speedapp测试，经常测不完就断了。
2.带gRPC的也是经常会断一下，过一会又好了。
反倒是Hysteria2 Tuic 和以前一直用的VLESS+TLS+WS表现良好VLESS+TLS_Vision+TCP也还可以，遂想问问能不能就开sing-box内核，不启动xray内核将VLESS+TLS+WS也安排上。这样我就能在我的穷逼VPS上省点资源了。感谢大佬写的一键脚本，拯救我这种小白。

**Comment by mack-a** [comment]
可以

**Comment by x64bugreport** [comment]
> 可以

感谢大佬 希望大佬有时间安排下 感谢！！！

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.39
