### ISSUE TITLE
sing-box 订阅无法在google play中下载，一直是等待中的状态，随后googleapis.com域名报错

### ISSUE THREAD

**Issue by lzy1960** [mack-a/v2ray-agent#1005]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述

- 脚本可以正常安装
- sing-box 订阅无法在google play中下载，一直是等待中的状态，随后googleapis.com域名报错
- 客户端为安卓 sing-box
- 确定是订阅的问题，因为用其他的订阅转换工具是可以正常下载的

![b0e6b37e3ca4363eab78ff9701c5f2b](https://github.com/mack-a/v2ray-agent/assets/40552111/c202995e-1169-465d-b6de-28c752d7eb28)

## 2.安装失败的log或者截图

![aed6f24b645e2e861dd4a4dd75f68e1](https://github.com/mack-a/v2ray-agent/assets/40552111/bdb2ff13-dc4a-4fc6-a814-7c51fc433904)

## 3.系统版本

Debian GNU/Linux 11 (bullseye)

## 4.脚本版本

3.2.39

## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
sing-box
```  
- 协议(VLESS+TLS_Vision+TCP)
```
tuic (应该与协议无关)
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
0,6,7,8,9,10
```

**Comment by mack-a** [comment]
同一个节点吗？用其他订阅转换的可以下载，用脚本提供的订阅无法下载吗？

**Comment by lzy1960** [comment]
> 同一个节点吗？用其他订阅转换的可以下载，用脚本提供的订阅无法下载吗？

是的，这两个问题都是。

我分别测试了两个不同的节点，都是这个现象。

**Comment by lzy1960** [comment]
又测试了一下，貌似与这个http proxy开关有关，打开后能下载，关闭不行，具体配置还不清楚

PS：脚本生成的订阅链接没有此开关

![7a299dbd6c76960c36f09ea6b91163f](https://github.com/mack-a/v2ray-agent/assets/40552111/832bc489-6d86-439a-8800-1ce875695870)

**Comment by mack-a** [comment]
删除节点后提供下转换后的配置

**Comment by lzy1960** [comment]
> 删除节点后提供下转换后的配置

[其他转换的订阅.txt](https://github.com/mack-a/v2ray-agent/files/14929666/default.txt)
[脚本生成的订阅.txt](https://github.com/mack-a/v2ray-agent/files/14929668/default.txt)

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.40 建议等待半小时后重新拉取订阅，GitHub文件有缓存

**Comment by lzy1960** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.40 建议等待半小时后重新拉取订阅，GitHub文件有缓存

感谢大佬，订阅配置更新了，但打开http_proxy开关后，无法访问任何网络了😖（包括百度）
