### ISSUE TITLE
Hysteria 版本升级

### ISSUE THREAD

**Issue by mongoliabao555** [mack-a/v2ray-agent#1009]
**详细描述建议的内容**
安装Xray核心后选择Hysteria2 管理安装 Hysteria2后找不到升级选项，管理界面只有添加跳跃端口。使用官方的bash <(curl -fsSL https://get.hy2.sh/)好象是搭建新的Hysteria2.

**Comment by mack-a** [comment]
脚本采用singbox内核实现hy2，升级singbox内核即可。
