### ISSUE TITLE
openwrt中间使用openclash代理用不了

### ISSUE THREAD

**Issue by liufangpu** [mack-a/v2ray-agent#1012]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
按照脚本方式运行起来，widnows电脑的v2ray客户端可以用，但是导入openwrt里的openclash却用不了
```

## 2.安装失败的log或者截图
```
请填写
```

## 3.系统版本
```
openwrt openclashv0.46.003-beta
```

## 4.脚本版本
```
最新版
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
1
```  
- 协议(VLESS+TLS_Vision+TCP)
```
trajon及所有协议
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
openwrt  openclash v0.46.003-beta
```

**Comment by mack-a** [comment]
v2rayNG已经1.8.19，你的版本太老了。
openclash了解不多但应该是也是版本问题。
