### ISSUE TITLE
安装Xray-core出现死循环的 “选择错误”

### ISSUE THREAD

**Issue by BLCheung** [mack-a/v2ray-agent#1013]
## 1.问题描述
执行任意组合安装 ➡️ VLESS+TLS_Vision+TCP[推荐] 出现死循环的 “选择错误”

## 2.安装失败的log或者截图
![WechatIMG893](https://pic.superbed.cc/item/66216edbf989f2fb97595d87.png)

## 3.系统版本
CentOS 7.9.2009 x86_64(Py3.7.9)

## 4.脚本版本
v3.2.41

## 5.服务端安装的内核、协议、安装方式
核心 xray-core

- 安装方式（1.全部安装、2.任意组合安装）
任意组合安

- 协议(VLESS+TLS_Vision+TCP)
VLESS+TLS_Vision+TCP[推荐]

## 6.客户端版本
无

**Comment by BLCheung** [comment]
经测试，无论我选择Xray-core下的哪种协议 都会出现“选择错误”，而sing-box则不会

**Comment by mack-a** [comment]
卸载脚本后重新安装尝试
