### ISSUE TITLE
本脚本不支持此系统，请将下方日志反馈给开发者

### ISSUE THREAD

**Issue by vvstar1982** [mack-a/v2ray-agent#1014]
**详细描述建议的内容**
本脚本不支持此系统，请将下方日志反馈给开发者
 
Ubuntu 22.04.2 LTS 
 \l 
Linux version 6.3.2-bbrplus (admin@sidamd64) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Sun May 14 23:02:58 CST 2023

**Comment by mack-a** [comment]
建议dd纯净系统后重新尝试

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/1015
