### ISSUE TITLE
3.2.42脚本提示不支持Ubuntu

### ISSUE THREAD

**Issue by lavyr** [mack-a/v2ray-agent#1015]
问题描述：
升级到脚本版本3.2.42后执行vasma提示如下：

# vasma                                                                                          [18:25:47]

本脚本不支持此系统，请将下方日志反馈给开发者
 
Ubuntu 22.04.4 LTS 
 \l 
Linux version 6.8.6 (root@b4d3a0465c6e) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Mon Apr 15 08:19:16 CST 2024 

服务环境：
Ubuntu 22.04.4 LTS（apt命令更新到最新）
已安装协议Hysteria2、VLESS+Reality+Vision、Tuic
原版bbr内核6.8.6，加速算法bbr-fq
其他：系统配置优化脚本

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.43
