### ISSUE TITLE
分流卸载后无法还原规则，出现sing-box无法启动

### ISSUE THREAD

**Issue by love768952693** [mack-a/v2ray-agent#1016]
复现：
第一步：
添加IPV6分流，添加一个关键词：google，启动成功。

第二步
卸载分流，启动报错。

不管是卸载，刚更新了 v3.2.42 脚步，问题依旧，卸载还原时，不会还原ipv6出站，导致无法启动。

错误信息
`FATAL[0000] create service: outbound not found for rule[0]: IPv6_out
﻿`

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.43

**Comment by love768952693** [comment]
大佬，添加分流规则后又出问题了，采用的是IPV4 warp分流。
脚本版本是：当前版本：v3.3.31 
`FATAL[0000] create service: initialize outbound[1]: `detour` is not supported in direct context
`
