### ISSUE TITLE
Clash Link Not Working With Clash for Windows

### ISSUE THREAD

**Issue by byeno16** [mack-a/v2ray-agent#1019]
Hello,
I get an error when I try to add the subscription link for clash to Clash For Windows.

![image](https://github.com/mack-a/v2ray-agent/assets/40113392/9778cebd-5299-4fd7-8de3-afba7b885d1e)

**Comment by mack-a** [comment]
clash for windows已不在乎为，建议使用 https://github.com/clash-verge-rev/clash-verge-rev

**Comment by mack-a** [comment]
clash for windows已不再维护，建议使用 https://github.com/clash-verge-rev/clash-verge-rev
