### ISSUE TITLE
对singbox增加"全球代理"和"全局代理"规则

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#1021]
**详细描述建议的内容**
希望singbox可以像clashmeta一样，下发配置文件内，可以对全球代理进行节点选择，并包含"手动选择"和"自动选择"。 同时也希望singbox的global全局代理，是否也可以进行节点的选择。当前singbox的配置规则，对于不包含在规则tag内的流量，都是通过手动设置的节点进行代理。

**Comment by mack-a** [comment]
不是很理解，有示例吗

**Comment by bettswang** [comment]
例如，对于clashmeta的客户端中他的规则有如下的""
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/c78dc9f0-b5f1-489f-860f-53cf624de23a)
当我在浏览器访问境外网站后，他将会使用这个规则进行匹配，在这个规则下他可以选择"手动节点"或者"自动节点"进行代理

对于singbox的规则，没有这个规则，当我在浏览器访问一些普通的境外ip网站，它将只会使用手动节点进行进行代理。如果这个手动指定的节点异常后，将会无法访问。

**Comment by bettswang** [comment]
全局代理(global)也是一样，clashmeta是可以制定自动和手动节点。而对于singbox只有手动节点代理生效

**Comment by mack-a** [comment]
你可以提个PR。

**Comment by mack-a** [comment]
@bettswang 有研究好吗

**Comment by bettswang** [comment]
> @bettswang 有研究好吗

我不太会写代码，我有空找个别人的模板来参照修改下
