### ISSUE TITLE
证书申请方式中dns api希望能够支持更多的api

### ISSUE THREAD

**Issue by hzy132** [mack-a/v2ray-agent#1023]
目前脚本dns api申请证书只支持CloudFlare方式，希望可以在脚本中加入acme.sh的dns api申请方式，acme.sh支持数十种解析商，我看脚本中本来就用了acme.sh，只是用的http方式。

我的域名解析方不在CloudFlare，只能再用acme.sh设置申请证书，稍微麻烦了一点点。

**Comment by mack-a** [comment]
说一下你需要什么dns api

**Comment by mack-a** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh

v3.2.46 使用此版本看看是否正常申请aliyun通配符证书。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.46
