### ISSUE TITLE
部署 sing-box 默认配置，google cloud 时常反馈 存在 ddos 攻击

### ISSUE THREAD

**Issue by iamdennisme** [mack-a/v2ray-agent#1029]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 在google cloud 上部署singbox（协议不限），运行一段时间，会收到 ddos 告警文件
```
请填写
```

## 2.安装失败的log或者截图
```
请填写
```

## 3.系统版本
```
ubuntu 24.02
```

## 4.脚本版本
```
master 
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
siing-box
```
- 安装方式（1.全部安装、2.任意组合安装）
```
全部安装
```  
- 协议(VLESS+TLS_Vision+TCP)
```
请填写
```  
## 6.客户端版本
```
# sing -box 1.8
请填写
```

**Comment by mack-a** [comment]
Google Cloud部署任何协议跑流量都会提示挖矿或者攻击（很早以前就这样）。

**Comment by iamdennisme** [comment]
> Google Cloud部署任何协议跑流量都会提示挖矿或者攻击（很早以前就这样）。

我换成 xray ，暂时看起来是稳定的，同样的服务器，我和朋友，他部署xray，看起来半年都是没有同步的，但是我基本每个月都会被警告一次，我再观察下 xray
