### ISSUE TITLE
无法使用BT

### ISSUE THREAD

**Issue by sky2021hash** [mack-a/v2ray-agent#103]
作者好，我发现trojan可以下载Bt，但xray的不行，如何更改？能否把默认屏蔽BT改为用户自行决定？

**Comment by mack-a** [comment]
> 作者好，我发现trojan可以下载Bt，但xray的不行，如何更改？能否把默认屏蔽BT改为用户自行决定？

现在没有开嗅探，脚本里面的屏蔽BT是有问题的。过段时间会去掉屏蔽bt这个功能。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.17 BT删了
