### ISSUE TITLE
socks5_inbound_route.json 未生成，socks5允许入站ip未生效

### ISSUE THREAD

**Issue by MFYDev** [mack-a/v2ray-agent#1032]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚

参考 #919 ,设置入站，然后添加允许ip，之后所有设置均成功，但是此文件socks5_inbound_route.json无法生成，测试允许所有ip入站

## 2.安装失败的log或者截图
```bash
 /etc/v2ray-agent/sing-box/conf/config 
 root@SG  ls
01_direct_outbound.json  20_socks5_inbounds.json
```

## 3.系统版本
```
Ubuntu 22.04 LTS
```

## 4.脚本版本
```
v3.2.51
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
both
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```  
- 协议(VLESS+TLS_Vision+TCP)
```
vless+reality+vision
任意组合安装0，1，7
```  
## 6.客户端版本
```
shadowrocket
```

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.52 试一下这个版本

**Comment by MFYDev** [comment]
更新最新版之后问题解决，非常感谢！
