### ISSUE TITLE
How to use with Caddy

### ISSUE THREAD

**Issue by mfat** [mack-a/v2ray-agent#1033]
Hi 
I don't want xray to take over port 443. I have caddy running on 443. 
How can i forward from caddy to xray for xray.mydomain.com?
Thanks much

**Comment by mack-a** [comment]
The script does not support this installation method

**Comment by mfat** [comment]
@mack-a Thanks. I understand. But how can i change the port for xray? Which file should i edit?

**Comment by mack-a** [comment]
/etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json

**Comment by mfat** [comment]
Thanks a million @mack-a
