### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by mfat** [mack-a/v2ray-agent#1035]
I have installed the script and it's working fine. So I have no issue with v2ray agent.

But I have another subdomin  (jellyfin.mydomain.com) that I need to reverse proxy to a local port. How can I make xray forward traffic for that subdomain to local port 6000?

I tried adding this under "fallbacks" in  02_VLESS_TCP_inbounds.json but it didn't work.
```
{ 
            "domain": "jellyfin.mydomain.com",
            "dest": 6000,
            "xver": 1
          }
```

**Comment by mack-a** [comment]
https://www.v2ray-agent.com/archives/1715588176000
