### ISSUE TITLE
设置Socks5全局转发后可以查看全局转发的配置

### ISSUE THREAD

**Issue by wsnsnsns** [mack-a/v2ray-agent#1037]
目前的效果:
------------------------------------
1.安装Socks5出站 
2.设置Socks5全局转发 
3.查看分流规则 
4.添加分流规则 
请选择:3
已安装 sing-box socks5全局出站分流 
--------------------------------------
希望在这里,增加一个->5.查看Socks5全局转发配置
显示之前的全局转发的配置
目前可以通过文件查看:cat /etc/v2ray-agent/xray/conf/socks5_outbound.json

**Comment by wsnsnsns** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/43594614/9588c6f7-a349-4759-b550-665204401c97)
如上图~~~

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.1
