### ISSUE TITLE
订阅端口修改和上次使用的端口复用的建议

### ISSUE THREAD

**Issue by wsnsnsns** [mack-a/v2ray-agent#1038]
![image](https://github.com/mack-a/v2ray-agent/assets/43594614/564c1dcf-c3f2-40cb-bd5c-64330abe50ed)
7->2,这里在第一次安装的时候,选的是随机端口,
所以想修改一下端口,建议加个->6.修改订阅端口
另外一个建议是,重新安装之后,能够复用上一次使用的端口;

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/1041
