### ISSUE TITLE
设置Socks5全局转发后进行卸载,脚本功能失效

### ISSUE THREAD

**Issue by jin-gubang** [mack-a/v2ray-agent#1040]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
第一步:11.分流工具->4.Socks5分流【替换任意门分流】->1.Socks5出站->2.设置Socks5全局转发->设置完成后,全局转发功能正常使用;
过了一段时间,想卸载全局转发功能,进行了如下操作:
第二步:11.分流工具->4.Socks5分流【替换任意门分流】->3.卸载 ->卸载完成后,协议全都不可用;
尝试了查看日志:
第三步:16.core管理->9.查看日志->1.打开access日志->2.监听access日志->3.监听error日志->都没有日志
尝试重装:
第四步:2.任意组合安装 ->安装完成后->协议全部恢复
```
## 2.安装失败的log或者截图
```
无log
```
## 3.系统版本
```
Ubuntu 20.04.6 LTS
```

## 4.脚本版本
```
v3.2.54
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```  
- 协议(VLESS+TLS_Vision+TCP)
```
VLESS+TCP[TLS_Vision] VLESS+Reality+Vision VLESS+Reality+gRPC
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
windows-v2rayN V6.43
```

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.1
