### ISSUE TITLE
在[重新安装]这个部分,希望带上一些上次的选择,作为默认值

### ISSUE THREAD

**Issue by jin-gubang** [mack-a/v2ray-agent#1041]
在出现各种各样的问题的时候,需要重新安装,如果带一些默认值,会方便很多;
下面是我个人的选择,可以参考:
2.任意组合安装
功能 1/1 : 选择核心安装 
1.Xray-core 
2.sing-box 
请选择:1**[默认值:上一次选择的]**
进度  2/12 : 初始化Nginx申请证书配置 
读取到上次安装记录，是否使用上次安装时的域名 ？[y/n]:y**[默认值:y]**
进度  3/12 : 申请TLS证书
 ---> 如未过期或者自定义证书请选择[n]
是否重新安装？[y/n]:n**[默认值:n]**
进度 6/12 : 添加伪装站点 
检测到安装伪装站点，是否需要重新安装[y/n]:n**[默认值:n]**
进度  7/12 : 安装Xray 
 ---> Xray-core版本:1.8.11 
是否更新、升级？[y/n]:n**[默认值:n]**
进度 9/12 : 初始化Xray配置 
读取到上次用户配置，是否使用上次安装的配置 ？[y/n]:y**[默认值:y]**
配置VLESS+Reality
读取到上次安装记录，是否使用上次安装时的端口 ？[y/n]:y**[默认值:y]**
是否使用 xxxxxxx.xxxxxx.com 此域名作为Reality目标域名 ？[y/n]:n**[默认值:n]**
配置客户端可用的serverNames
 #注意事项 
Reality目标可用域名列表：https://www.v2ray-agent.com/archives/1689439383686#heading-3
录入示例:addons.mozilla.org:443
请输入目标域名，[回车]随机域名，默认端口443:lol.secure.dyn.riotcdn.net**[默认值:上次已经使用过的域名和端口]**
 ---> 客户端可用域名: lol.secure.dyn.riotcdn.net:443
生成Reality key
读取到上次安装记录，是否使用上次安装时的PublicKey/PrivateKey ？[y/n]:y**[默认值:y]**
进度 12/12 : 账号

**Comment by mack-a** [comment]
可以。

**Comment by mack-a** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh 

已更新到dev分支
