### ISSUE TITLE
输入API Token后显示不支持此域名申请通配符证书

### ISSUE THREAD

**Issue by Kratos0902** [mack-a/v2ray-agent#1042]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
安装脚本时，输入API Token后显示
---> 不支持此域名申请通配符证书，建议使用此格式[xx.xx.xx]
```

## 2.安装失败的log或者截图
```
进度  3/12 : 初始化Nginx申请证书配置 
请输入要配置的域名 例: www.v2ray-agent.com ---> 
域名:abcxyz.com
请输入端口[默认: 443]，可自定义端口[回车使用默认] 
端口:
 ---> 端口: 443 
 ---> 域名IP校验通过 
 ---> Nginx启动成功 
 ---> Nginx关闭成功 
 ---> 检测到443端口已开放 
 ---> 检查域名ip中 
 ---> 检查当前域名IP正确 
 ---> Xray关闭成功 
进度  4/12 : 申请TLS证书
是否使用DNS API申请证书[支持NAT]？[y/n]:y
============================================================== 
1.cloudflare[默认] 
2.aliyun 
============================================================== 
请选择[回车]使用默认:1
 CF_Token参考配置教程：https://www.v2ray-agent.com/archives/1701160377972
请输入API Token:xxXXxx0XxXxxXx0XXXXxxxxxxxxXX-xxXXxxxXXx
 ---> 不支持此域名申请通配符证书，建议使用此格式[xx.xx.xx] 
```

## 3.系统版本
```
ubuntu 20.04
```

## 4.脚本版本
```
v3.2.54
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
1
```

**Comment by mack-a** [comment]
通配符证书建议使用 *.*.*的格式。比如 a.b.com
