### ISSUE TITLE
安装无故自动退出

### ISSUE THREAD

**Issue by Jas0n0ss** [mack-a/v2ray-agent#1043]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
如截图

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/88020021/ae407013-69a1-4241-ba0d-6d2b03c8afc9)

## 3.系统版本
```
root@xHK:/mnt# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
root@xHK:/mnt#```

## 4.脚本版本
```
v3.2.54
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```  
- 协议(VLESS+TLS_Vision+TCP)
```
VLESS+TLS_Vision+TCP
```

**Comment by mack-a** [comment]
未复现此问题
