### ISSUE TITLE
There is an error with the vless_grpc protocol when customizing the ServiceName.

### ISSUE THREAD

**Issue by AlanNeverStopWin** [mack-a/v2ray-agent#1044]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
``I found that when I customize the ServiceName for "vless_grpc," it automatically adds "grpc" at the end. However, the generated configuration URL does not show "grpc," while it is present in the config. If using a non-subscription method, this causes "vless_grpc" to be unusable after customizing the ServiceName. I'm not sure if you have already addressed this issue, as it was a problem I discovered earlier.`
请填写
``I found that when I customize the ServiceName for "vless_grpc," it automatically adds "grpc" at the end. However, the generated configuration URL does not show "grpc," while it is present in the config. If using a non-subscription method, this causes "vless_grpc" to be unusable after customizing the ServiceName. I'm not sure if you have already addressed this issue, as it was a problem I discovered earlier.`

## 2.安装失败的log或者截图
```
请填写
```

## 3.系统版本
```
请填写
```

## 4.脚本版本
```
请填写
```

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
``xray-core`
请填写
``xray-core`
- 安装方式（1.全部安装、2.任意组合安装）
``2`
请填写
``2`  
- 协议(VLESS+TLS_Vision+TCP)
``VLESS+TLS_Vision+GRCP`
请填写
`VLESS+TLS_Vision+GRCP``  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请填写
```

**Comment by mack-a** [comment]
未复现此问题，详述安装步骤。
