### ISSUE TITLE
别再推荐 cloudsilk 了，付了款不激活，也没有售后

### ISSUE THREAD

**Issue by akakoori** [mack-a/v2ray-agent#1045]
之前逾期了，从邮件连接进去付了续费款之后一直没有激活服务
售后没人理，发售前邮件也没人理，估计已经跑路了

![image](https://github.com/mack-a/v2ray-agent/assets/15867066/1854faf6-b2b6-489a-9609-1a293f81c9be)
![image](https://github.com/mack-a/v2ray-agent/assets/15867066/5759f1fc-281f-4283-87e9-beaed0d693f0)

**Comment by mack-a** [comment]
联系TG: @baisiyun @bestidc

**Comment by akakoori** [comment]
大哥，我现在梯子挂了，怎么上TG？我能上TG我会在这里？

**Comment by akakoori** [comment]
这售后可以的，售后成本远超购买成本

**Comment by mack-a** [comment]
https://cloudsilk.io/announcements/1 

2.1    工单回复时效24小时内, 24小时内未回复将给予一定的补偿

**Comment by akakoori** [comment]
> https://cloudsilk.io/announcements/1
> 
> 2.1 工单回复时效24小时内, 24小时内未回复将给予一定的补偿

23年提过一个工单，整整4天后才回复，没有补偿

**Comment by akakoori** [comment]
TG 上联系了，已读不回

> 联系TG: @baisiyun @bestidc

**Comment by akakoori** [comment]
总算回复了，说7个工作日内原路退款，只能说找渠道主还是有用的，大家自己判断要不要用这家吧
