### ISSUE TITLE
sing box内核升级失败重复出现

### ISSUE THREAD

**Issue by anon1984encn** [mack-a/v2ray-agent#1046]
## 1.问题描述
不管是通过脚本第16项升级sing box内核还是重新安装，都出现无法获取最新release版本的问题

## 2.安装失败的log或者截图
![Xnip2024-05-30_11-21-58](https://github.com/mack-a/v2ray-agent/assets/100828799/07fa7055-65e7-4150-8345-9e14a0fb4e99)

## 3.系统版本
```
请填写
```

## 4.脚本版本
已升级到最新

## 5.服务端安装的内核、协议、安装方式
sing-box

- 安装方式（1.全部安装、2.任意组合安装）
2

**Comment by mack-a** [comment]
机器请求GitHub API失败，共用IP会出现，建议手动下载替换内核，或者等一段时间后再尝试。

**Comment by snugduahn** [comment]
我的也是提示安装失败，从昨天开始出现的。

**Comment by mack-a** [comment]
> 我的也是提示安装失败，从昨天开始出现的。

IP是否为共用IP（比如NAT）。
