### ISSUE TITLE
socks5分流出站不会安装singbox内核，导致无法生效

### ISSUE THREAD

**Issue by MFYDev** [mack-a/v2ray-agent#1047]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚

1. 升级更新最新脚本
2. 重新安装xray在两台机器上
3. 之前版本的已经比较奇怪，只要是全局socks转发， 出站入站会忽略xray自动安装sing-box，全部流量走sing-box，然后入栈机器也就是解锁机器想添加额外的dns解锁也不再可能，是否都用xray不用sing-box？
4. 目前的最新版本出站机器安装全局转发根本不会安装singbox内核，即使规则存在也不生效，手动安装singbox也存在配置上的问题导致两个机器之间无法建立通信

## 2.安装失败的log或者截图
```
请填写
```

## 3.系统版本
```
请填写
```
ubuntu 24.04

## 4.脚本版本
```
请填写
```
3.2.55

## 5.服务端安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2
0,1,7
```  
- 协议(VLESS+TLS_Vision+TCP)
```
请填写
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请填写
```

**Comment by MFYDev** [comment]
经过多次测试，发现出站机器正常安装出站不会安装和启用singbox内核，在这个版本上突然出现的

**Comment by mack-a** [comment]
1.出站对于不同的内核产生的配置文件不一样，如果同时安装了xray和sing-box则会有两个出站配置（xray、sing-box）
2.入站统一采用sing-box，如果想要配置dns解锁需要在入站机器的sing-box下配置。

**Comment by mack-a** [comment]
针对你说的dns解锁问题，如果入站机安装xray并设置socks5分流。这时候dns解锁不会对socks5分流生效。
如果入站机安装sing-box，并设置dns解锁和socks5分流。这时候会生效。
