### ISSUE TITLE
Hysteria2 fails to run after the installation of xray, they can't co-exist?

### ISSUE THREAD

**Issue by tlsalex** [mack-a/v2ray-agent#1048]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
Install Hysteria2 with the script, after the installation, I was able to see the configuration for Hysteria2 TLS.
Then install VLESS+Reality+uTLS+Vision, after the installation, I was able to see the configuration for Vless,
At this moment, I found the status for is  sing-box.service inactive

root@racknerd-xx:~/temp# systemctl status sing-box.service
○ sing-box.service
     Loaded: loaded (/etc/systemd/system/sing-box.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2024-06-03 01:57:55 UTC; 11min ago
   Main PID: 13418 (code=exited, status=0/SUCCESS)
        CPU: 74ms

It also failed to restart 

root@racknerd-xx:~# systemctl restart sing-box.service
root@racknerd-xx:~# systemctl status sing-box.service
● sing-box.service
     Loaded: loaded (/etc/systemd/system/sing-box.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-06-03 03:30:38 UTC; 9s ago
    Process: 18749 ExecStart=/etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json (code=exited, status=1/FAILURE)
   Main PID: 18749 (code=exited, status=1/FAILURE)


```

## 2.安装失败的log或者截图
```
![co-exist](https://github.com/mack-a/v2ray-agent/assets/36788337/1966b98c-14a9-478a-ad81-d0e0a8035d23)

```

## 3.系统版本
```
root@racknerd-xx:~# cat /etc/issue
Ubuntu 22.04.1 LTS \n \l

root@racknerd-xx:~# uname -r
5.15.0-46-generic
```

## 4.脚本版本
```
v3.3.1
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
1.xray-core and 2.sing-box
```
- 安装方式任意组合安装
```
请填写
```  
- 协议( Hysteria2 and VLESS+TLS_Vision+TCP
```
可以用数字代替，比如0.VLESS+TLS_Vision+TCP-->0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18

V2rayN 6.45
```

**Comment by tlsalex** [comment]
root@racknerd-xx:~# systemctl cat sing-box.service
# /etc/systemd/system/sing-box.service
[Unit]
After=network.target nss-lookup.target

[Service]
User=root
WorkingDirectory=/root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
ExecStart=/etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json
ExecReload=/bin/kill -HUP
Restart=on-failure
RestartSec=10
LimitNPROC=512
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
root@racknerd-c43ff44:~# ll  /etc/v2ray-agent/sing-box/conf/
total 12
drwxr-xr-x 3 root root 4096 Jun  3 02:00 ./
drwxr-xr-x 3 root root 4096 Jun  3 01:37 ../
drwxr-xr-x 2 root root 4096 Jun  3 02:00 config/
root@racknerd-xx:~#

The configure config.json doesn't exist any more.

**Comment by mack-a** [comment]
如果用xray-core作为主要内核，先用脚本安装所需协议。安装后再使用 4.Hysteria2管理 安装hy2.
