### ISSUE TITLE
查看账号时候ws的路径错误

### ISSUE THREAD

**Issue by DdVwl6Fj3a** [mack-a/v2ray-agent#105]
**1.描述出现的问题**

```
配置vless+ws+cdn，输入的字符串末尾字母为“v”的时候，查看账户时候显示的ws的路径会漏掉“v”，导致配置客户端出现无法连接服务端的问题
比如：自定义路径“aowv”，vless配置文件里面的路径是“/aowvws”，但是查看账户的时候显示的是“/aowws”

可能是脚本处理的时候正则有问题～

```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> centos7
- 否

**6.脚本版本**

- v2.3.17

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- vless

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.20 已修复

**Comment by DdVwl6Fj3a** [comment]
@mack-a 大佬我这个是重复提了吗？

**Comment by mack-a** [comment]
你提了我才修的
