### ISSUE TITLE
Trojan 和低版本trojan客户端 软路由不兼容

### ISSUE THREAD

**Issue by watsonlamson** [mack-a/v2ray-agent#1050]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
参考示例：vasma->2->2->0,7,9,10，选择后一路回车，安装完毕后选择7->1 查看账号 **VLESS gRPC TLS [仅CDN推荐]**不展示等。
```
Trojan 和低版本trojan客户端 软路由不兼容，手机 shadowrocket可以运行TROJAN， 路由器不能运行。 低版本V2RAY也不能运行，
之前一直用你的脚本，现在路由器没法运行TROJAN。只能用其他脚本

## 2.安装失败的log或者截图
```
请在这里填写
```

## 3.系统版本
```
请在这里填写
```

## 4.脚本版本
```
请在这里填写
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
请在这里填写
```
- 安装方式（1.全部安装、2.任意组合安装）
```
请填写
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
可以用数字代替，比如0.VLESS+TLS_Vision+TCP-->0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请在这里填写
```

**Comment by mack-a** [comment]
提供下低版本软路由的trojan日志。

**Comment by watsonlamson** [comment]
请问大神有没之前版本脚本下载？

之前旧脚本可以用TLS XLS，后来只能TROJAN，现在TROJAN也不行了

我用的是PANDORA软路由

 

发件人: ***@***.*** ***@***.***> 代表 mack-a
发送时间: 2024年6月11日 14:54
收件人: mack-a/v2ray-agent ***@***.***>
抄送: watsonlamson ***@***.***>; Author ***@***.***>
主题: Re: [mack-a/v2ray-agent] Trojan 和低版本trojan客户端 软路由不兼容 (Issue #1050)

 

提供下低版本软路由的trojan日志。

**Comment by mack-a** [comment]
trojan已经很长时间没更新，你可以尝试下用xray-core的trojan。

**Comment by watsonlamson** [comment]
请教大神，有没资源发我

我都研究了很久，网上找的TROJAN 安装脚本运行安装失败，安装完重启直接22端口不能用，可能是太久没维护

WULABING 223BOY也脚本也不好用，失败，就是你的脚本最流畅。

 

xray-core的trojan 脚本可以发我吗？

Xray /v2ray 脚本可以发我吗？

 

非常感谢！

 

发件人: ***@***.*** ***@***.***> 代表 mack-a
发送时间: 2024年6月11日 16:51
收件人: mack-a/v2ray-agent ***@***.***>
抄送: watsonlamson ***@***.***>; Author ***@***.***>
主题: Re: [mack-a/v2ray-agent] Trojan 和低版本trojan客户端 软路由不兼容 (Issue #1050)

 

trojan已经很长时间没更新，你可以尝试下用xray-core的trojan。
