### ISSUE TITLE
节点经常性断流

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#1051]
## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
1. 客户端使用clashverge v1.6.5 
2. 客户端长时间运行时，经常会节点断流，然后需要在客户端上更新下订阅下(或者重启下应用)。断流节点就会恢复
3. 断流的节点不固定
4. 故障的时候，其他客户端环境(例如，另一台电脑，或者手机)是正常的。
5. 每个clashverge客户端(同配置，同版本)都会出现, 手机端的clashforandroid好像没有，没注意到。
```

## 2.安装失败的log或者截图
![log](https://github.com/mack-a/v2ray-agent/assets/43665641/cd4136b1-46f1-4e2b-b77d-efa470c4cfea)

![微信截图_20240612100200](https://github.com/mack-a/v2ray-agent/assets/43665641/0790a3b4-f825-40b5-b2f6-a6ce0a621128)

## 3.系统版本
ubuntu20.04

## 4.脚本版本
```
v3.3.2
```

## 5.服务端安装的内核、协议、安装方式
- 核心 2.singbox
```
请在这里填写
```
-2.任意组合安装
```
请填写
```  
0,6,9
```

## 6.客户端版本
```
clash verge v1.6.5  内核时clashmeta 或者 alpha ，两者都会出现这个问题
```

**Comment by bettswang** [comment]
针对此问题，我也对clashverge的那边提问过，那边有解释过可能是服务端这边dns解析设置的问题。
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/3f297168-a2aa-454d-9c63-0fbe64fd998f)

这个是不是改成IP会更直接点好？

**Comment by bettswang** [comment]
应该是被运营商QOS或者限流了。我想请问下，端口条约是否可以解决这个问题呢？

**Comment by mack-a** [comment]
端口跳跃可以缓解但是无法根本解决问题。

**Comment by bettswang** [comment]
tuic协议可以增加下端口跳跃功能吗？

**Comment by mack-a** [comment]
可以，提一个新issue。
