### ISSUE TITLE
安装sing-box后无法删除用户

### ISSUE THREAD

**Issue by qq290598268** [mack-a/v2ray-agent#1052]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
安装sing-box后无法删除用户，7管理---5.删除用户  删除后还在
```

## 2.安装失败的log或者截图
```
请在这里填写
```

## 3.系统版本
```
Ubuntu 20.04
```

## 4.脚本版本
```
请在这里填写
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
2.sing-box
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请在这里填写
```

**Comment by mack-a** [comment]
最新版未复现。建议更新到最新版重新尝试。
