### ISSUE TITLE
oracle vps 证书申请失败

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#1056]
## 1.问题描述
```
完全卸载后，且删除~/.acme.sh。然后重新部署最新版本脚本，在申请证书时失败。oracle vps网络完全放开，80端口可以访问。也使用新域名进行申请。都是失败。
```

## 2.安装失败的log或者截图

![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/f384159a-545d-4c96-9afb-06cbfdc20a92)

![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/99a3c6c1-3c53-4ac8-a79b-a5e07375a5b0)

![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/1c8ef3f3-79b5-4f1e-bf39-1a678d49a47d)

## 3.系统版本
```
ubuntu20.04
```

## 4.脚本版本
```
v3.3.3
```

## 5.服务端安装的内核、协议、安装方式
- 核心
```
sing-box
```
- 安装方式
```
任意组合安装
```  
- 协议
```
0，6，9
```

**Comment by mack-a** [comment]
使用什么申请方式。api还是普通申请。

**Comment by bettswang** [comment]
普通tls

**Comment by mack-a** [comment]
甲骨文有自己的防火墙，有没有允许访问。

**Comment by bettswang** [comment]
防火墙打开的，全部允许。看我traceroute截图，端口可以打通的

**Comment by mack-a** [comment]
通过 @mack_a_bot 机器人把机器的IP、密码、域名私聊给我。

**Comment by mack-a** [comment]
通过调试可能因为 letsencrypt对于top支持的不够好，使用zerossl可以申请成功。
letsencrypt申请不成功可以使用zerossl。
