### ISSUE TITLE
`域名IP校验通过 ` 之后脚本自动退出

### ISSUE THREAD

**Issue by CharlesCCC** [mack-a/v2ray-agent#1057]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
vasma->1->1-> 回车 
```
请输入端口[默认: 443]，可自定义端口[回车使用默认] 
端口:

 ---> 端口: 443 
 ---> 域名IP校验通过 
```

脚本就自动退出,没有任何提示/错误. 

## 2.安装失败的log或者截图
<img width="373" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/7534809/b5061bc1-c44b-4ec7-9631-e186f6ed0554">

## 3.系统版本

AWS Lightsail 
```
Debian 6.1.0-21-cloud-amd64
```

## 4.脚本版本
```
最新版本
https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
1
```
- 安装方式（1.全部安装、2.任意组合安装）
```
1
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
N/A (还没到这一步) 
```  
## 6.客户端版本
```
N/A (还没到这一步) 
```

**Comment by mack-a** [comment]
卸载脚本后重新安装脚本。
