### ISSUE TITLE
证书申请失败，DNS解析式没有问题的

### ISSUE THREAD

**Issue by qwazx** [mack-a/v2ray-agent#1059]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
在申请证书的环节失败，试过不同地区的服务器都卡在了证书申请的步骤上，下面的log是在之前安装成功的服务器上测试的，但这次安装还是失败了

## 2.安装失败的log或者截图
cat: /root/.acme.sh/XXX_ecc/fullchain.cer: No such file or directory
[Fri 28 Jun 2024 11:37:49 PM EDT] Pending, The CA is processing your order, please just wait. (7/30)
[Fri 28 Jun 2024 11:37:52 PM EDT] Pending, The CA is processing your order, please just wait. (8/30)
[Fri 28 Jun 2024 11:37:54 PM EDT] Pending, The CA is processing your order, please just wait. (9/30)
[Fri 28 Jun 2024 11:37:57 PM EDT] Pending, The CA is processing your order, please just wait. (10/30)
[Fri 28 Jun 2024 11:37:59 PM EDT] Pending, The CA is processing your order, please just wait. (11/30)
[Fri 28 Jun 2024 11:38:01 PM EDT] Pending, The CA is processing your order, please just wait. (12/30)
[Fri 28 Jun 2024 11:38:04 PM EDT] Pending, The CA is processing your order, please just wait. (13/30)
[Fri 28 Jun 2024 11:38:06 PM EDT] Invalid status, XXX:Verify error detail:DNS problem: server failure at resolver looking up A for XXX; DNS problem: server failure at resolver looking up AAAA for XXX
[Fri 28 Jun 2024 11:38:06 PM EDT] Please add '--debug' or '--log' to check more details.
[Fri 28 Jun 2024 11:38:06 PM EDT] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

cat: /root/.acme.sh/XXX_ecc/fullchain.cer: No such file or directory
[Fri 28 Jun 2024 11:39:55 PM EDT] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri 28 Jun 2024 11:39:55 PM EDT] Standalone mode.
[Fri 28 Jun 2024 11:39:55 PM EDT] Single domain='XXX'
[Fri 28 Jun 2024 11:39:56 PM EDT] Getting webroot for domain='XXX'
[Fri 28 Jun 2024 11:39:56 PM EDT] Verifying: XXX
[Fri 28 Jun 2024 11:39:56 PM EDT] Standalone mode server
[Fri 28 Jun 2024 11:39:58 PM EDT] Pending, The CA is processing your order, please just wait. (1/30)
[Fri 28 Jun 2024 11:40:00 PM EDT] Invalid status, XXX:Verify error detail:DNS problem: looking up A for XXX: DNSSEC: DNSKEY Missing; DNS problem: looking up AAAA for XXX: DNSSEC: DNSKEY Missing
[Fri 28 Jun 2024 11:40:00 PM EDT] Please add '--debug' or '--log' to check more details.
[Fri 28 Jun 2024 11:40:00 PM EDT] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

## 3.系统版本
Debian 11 x86_64  

## 4.脚本版本
v3.3.4

## 5.服务端安装的内核、协议、安装方式
1.xray-core
1.全部安装

**Comment by mack-a** [comment]
top域名用zerossl申请。

**Comment by qwazx** [comment]
> top域名用zerossl申请。

之前用默认的没问题，现在得用第二个了是吗

**Comment by qwazx** [comment]
> top域名用zerossl申请。

可以了，十分感谢🙏

**Comment by mack-a** [comment]
https://letsencrypt.status.io/

**Comment by qwazx** [comment]
> https://letsencrypt.status.io/

感谢，我还以为又是我自己操作失误了，就没想到是他们的问题
