### ISSUE TITLE
脚本生成的新用户使用vmess协议无法连接

### ISSUE THREAD

**Issue by ccav6123** [mack-a/v2ray-agent#106]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
脚本安装时生成的默认用户使用vmess协议没有问题，但是生成的新用户，使用vmess协议时，无法连接。
操作系统win10         v2rayN4.12版本使用xray1.3
```
# 这是v2rayN的部分日志信息
read response header > EOF
2021/02/25 22:59:10 127.0.0.1:56119 accepted //nav.smartscreen.microsoft.com:443 [http -> proxy]
2021/02/25 22:59:10 [Warning] [2431840981] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2021/02/25 22:59:10 [Warning] [4211967550] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

-已经试过，问题必现

**4.直接安装失败的错误内容或者截图**

-安装没有报错，默认生成的用户使用任何协议都连接正常。新生成的用户使用vmess协议无法连接。

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- debian10 X64

**6.脚本版本**

- v2.3.20

**7.安装类型**

- 全部安装

**8.安装的核心版本**

- Xray-core 1.3

**9.出现问题的协议类型**

- vmess

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 相同

**Comment by mack-a** [comment]
配置服务端配置文件脱敏发一下，只发那个vmess得即可

**Comment by ccav6123** [comment]
{
  "inbounds": [
    {
      "port": 31298,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "tag": "VMessTCP",
      "settings": {
        "clients": [
          {
            "id": "xxx",
            "alterId": 1,
            "email": "xxx"
          },
          {
            "id": "xxx",
            "flow": "xtls-rprx-direct",
            "email": "xxx"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "acceptProxyProtocol": true,
          "header": {
            "type": "http",
            "request": {
              "path": [
                "/eufotcp"
              ]
            }
          }
        }
      }
    }
  ]
}

>

**Comment by mack-a** [comment]
稍后会修复

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.21 已修复
