### ISSUE TITLE
sing-box分流规则支持增量添加  怎么使用

### ISSUE THREAD

**Issue by jimmy-yao** [mack-a/v2ray-agent#1060]
如题，[sing-box分流规则支持增量添加](https://github.com/mack-a/v2ray-agent/commit/22111dbfdce7af13917716b3c3d26731c1add241)
具体怎么使用
谢谢

**Comment by mack-a** [comment]
你设置下分流就明白了。

**Comment by jimmy-yao** [comment]
是选项11的分流工具吗，还是重新安装的时候可以配置分流规则，另外我已经安装好了，想在安装好的基础上增加分流规则该怎么处理。谢谢。

**Comment by mack-a** [comment]
更新到最新脚本，添加规则即可。无需重新安装。

**Comment by jimmy-yao** [comment]
好的，谢谢。
