### ISSUE TITLE
Xray最新Splithttp支持。

### ISSUE THREAD

**Issue by doggie1989** [mack-a/v2ray-agent#1061]
Xray最新Splithttp支持。

[Xray-core v1.8.16](https://github.com/XTLS/Xray-core/releases/tag/v1.8.16) [Latest](https://github.com/XTLS/Xray-core/releases/latest)
SplitHTTP 传输方式 https://github.com/XTLS/Xray-core/pull/3412 https://github.com/XTLS/Xray-core/pull/3462 https://github.com/XTLS/Xray-core/discussions/716 @mmmray @RPRX @Fangliding
实现进一步的流量混淆有两种刚好相反的方式：多路复用 与 拆分连接，虽然现在只是逻辑拆分而没有实际拆分

SplitHTTP 使用 HTTP GET 长连接传输下行流量，使用多个 HTTP POST 请求传输上行流量，可以通过不支持 WebSocket、gRPC 的 CDN，实现与 Meek 相同的目标，但 SplitHTTP 是从零开始设计的全新传输方式，并非基于 Meek 修改而来，且 SplitHTTP 比 Meek 更简单、效率更高，详见文档 [英文（原生文档）](https://xtls.github.io/en/config/transports/splithttp.html) [中文（内容略有不同）](https://xtls.github.io/config/transports/splithttp.html)

此外，SplitHTTP 没有 WebSocket 的 ALPN 问题，这是一大优势，未来还会支持 HTTP/3

**Comment by RaySibay** [comment]
手搓了一个，实测下载飞快，基本跑满链路，上传速度受限于协议本身较慢，目前没有被gfw针对的迹象。

很适合套cdn用。

**Comment by doggie1989** [comment]
> 手搓了一个，实测下载飞快，基本跑满链路，上传速度受限于协议本身较慢，目前没有被gfw针对的迹象。
> 
> 很适合套cdn用。

你测试过什么cdn，我测试的cdn好像不能通过。。

**Comment by RaySibay** [comment]
> > 手搓了一个，实测下载飞快，基本跑满链路，上传速度受限于协议本身较慢，目前没有被gfw针对的迹象。
> > 很适合套cdn用。
> 
> 你测试过什么cdn，我测试的cdn好像不能通过。。

cloudflare+电信，别家暂时还懒得测。

**Comment by doggie1989** [comment]
> > > 手搓了一个，实测下载飞快，基本跑满链路，上传速度受限于协议本身较慢，目前没有被gfw针对的迹象。
> > > 很适合套cdn用。
> > 
> > 
> > 你测试过什么cdn，我测试的cdn好像不能通过。。
> 
> cloudflare+电信，别家暂时还懒得测。

确实，不需要开什么websocket也通的，不需要这些协议了。

**Comment by 1yasa** [comment]
+1，cdn现在有时候也被电信限流，vision反而是正常的，说明vless cdn传输行为异常。

splitHTTP能提示识别难度（需要多段合并识别，成本高了）

**Comment by mack-a** [comment]
目前客户端软件还未兼容，服务端Splithttp还在继续更新。后续稳定后会增加此内容。

**Comment by 1yasa** [comment]
> 目前客户端软件还未兼容，服务端Splithttp还在继续更新。后续稳定后会增加此内容。

🫡了解

**Comment by hedsbj** [comment]
感谢大牛们不断的在探索新途径。发现服务端和客户端的path 设置就算不一样，也能成功连接

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.15

**Comment by fredericky123** [comment]
有什么客户端 推荐吗

**Comment by mack-a** [comment]
> 有什么客户端 推荐吗

Xray-core核心的客户端都可以。

**Comment by mack-a** [comment]
> 我这样的配置 写在clash里不对，请问哪里需要修改呢 ![image](https://private-user-images.githubusercontent.com/13982749/365159103-1beda9ad-60cb-4445-90cc-deb71ce637c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzkzMDksIm5iZiI6MTcyNTYzOTAwOSwicGF0aCI6Ii8xMzk4Mjc0OS8zNjUxNTkxMDMtMWJlZGE5YWQtNjBjYi00NDQ1LTkwY2MtZGViNzFjZTYzN2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE2MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YWE3MTM4Mzc2ZGJhZjA4NGY0NzVkYjczZTA4MjA3NWIxNzJmN2Y0MzUwNzE0NzY4N2E4YzViZTBiZjc2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMB38yt9ymBQxcUF0WVucYKyKsuPmCLBeqTNrFe6xIk)

clashmeta不支持SplitHTTP

**Comment by siren202101** [comment]
> > 有什么客户端 推荐吗
> 
> Xray-core核心的客户端都可以。
A大，为什么我用V2rayN最新版有这个协议的，但是使用优选IP就不通了？
不是说支持CDN吗？
