### ISSUE TITLE
执行到最后的时候出现这种错误不知道为什么？

### ISSUE THREAD

**Issue by hanshoukai** [mack-a/v2ray-agent#1065]
**详细描述建议的内容**
生成Reality key

 privateKey:wG0GeGw7SD4hyDCpFsXw5COEa1Mmqpi1gUVlcv-jJGU

 publicKey:NsgeSgEtFiO0ofcXtlOnSffZ_o1ybiAISqUUqlABNm4
 ---> sing-box关闭成功
 ---> Xray关闭成功
Xray启动失败
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈

**Comment by Thomas-Cannon** [comment]
我也是

**Comment by mack-a** [comment]
都安装了什么协议。
