### ISSUE TITLE
最近tuic无法连接吗？烦请大佬帮助诊断，非常感谢！

### ISSUE THREAD

**Issue by xiuyuanxm** [mack-a/v2ray-agent#1068]
## 1.问题描述
使用其他方式都可以，就最后的tuic不行，v2rayn V6.49，手机端nekobox也不行，本来两者都可以。
![image](https://github.com/user-attachments/assets/b1f4f5e3-4a03-4234-b51f-855739d2c488)

## 2.安装失败的log或者截图
v2rayn日志显示：
+0800 2024-07-16 15:23:48 ERROR router: fetch rule-set geosite-category-ads-all: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs": open connection: timeout: no recent network activity

## 3.系统版本
win 11，android 13

## 4.脚本版本
`最新版本 v3.3.9

## 5.服务端安装的内核、协议、安装方式
2.sing-box
任意组合安装
0，7，8，9
## 6.客户端版本
v2rayn V6.49

**Comment by mack-a** [comment]
打开服务端的日志并访问看看是否有报错日志。

**Comment by xiuyuanxm** [comment]
![image](https://github.com/user-attachments/assets/1c5f3c8d-ba35-4066-9a62-94a6a938c376)
qing'we请问在哪里打开呢?

**Comment by mack-a** [comment]
vasma->16->找到相应核心

**Comment by xiuyuanxm** [comment]
+0800 2024-07-16 15:54:21 INFO [3613982261 0ms] outbound/direct: outbound connection to content-autofill.googleapis.com:443
+0800 2024-07-16 15:54:21 DEBUG [3613982261 0ms] dns: lookup domain content-autofill.googleapis.com
+0800 2024-07-16 15:54:21 DEBUG [3613982261 2ms] dns: lookup succeed for content-autofill.googleapis.com: 142.250.217.138 142.250.72.138 142.250.189.10 172.217.12.138 172.217.14.74 142.250.68.42 142.250.72.170 142.250.188.234 172.217.14.106 142.250.72.234 142.250.68.10 142.250.68.74 142.250.176.10 142.251.40.42
+0800 2024-07-16 15:54:21 DEBUG [2001437600 1.36s] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56193: download: raw-read tcp 97.65.199.200:17562->140.82.116.4:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56193: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [15498664 7.84s] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56126: download: raw-read tcp 97.65.199.200:51728->91.108.56.105:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56126: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [1481271564 1.66s] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56186: download: raw-read tcp 97.65.199.200:17560->140.82.116.4:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56186: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [1429275578 1.36s] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56191: download: raw-read tcp 97.65.199.200:17564->140.82.116.4:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56191: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [2990102569 8.24s] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56108: download: raw-read tcp 97.65.199.200:37872->140.82.114.25:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56108: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [2798112649 226ms] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56209: download: raw-read tcp 97.65.199.200:6678->142.250.217.138:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56209: read: connection reset by peer
+0800 2024-07-16 15:54:21 DEBUG [2428819658 337ms] inbound/vless[VLESSTCP]: connection closed: process connection from 183.250.151.88:56205: download: raw-read tcp 97.65.199.200:30728->185.199.108.133:443: use of closed network connection | upload: read tcp 97.65.199.200:443->183.250.151.88:56205: read: connection reset by peer
谢谢大佬，IP做了一些处理

**Comment by mack-a** [comment]
要用tuic节点访问

**Comment by xiuyuanxm** [comment]
奇怪，我用了tuic节点访问了，日志并没有增加，google也确实就打不开了。。
2024/07/16 16:03:07 系统代理设置改变 - ForcedChange
+0800 2024-07-16 16:03:11 ERROR router: fetch rule-set geosite-cn: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs": open connection: timeout: no recent network activity
+0800 2024-07-16 16:03:16 ERROR router: fetch rule-set geosite-category-ads-all: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs": open connection: timeout: no recent network activity
2024/07/16 16:03:17 当前服务的真连接延迟: -1 ms
+0800 2024-07-16 16:03:21 ERROR router: fetch rule-set geosite-geolocation-cn: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs": open connection: timeout: no recent network activity
+0800 2024-07-16 16:03:26 ERROR router: fetch rule-set geosite-geolocation-!cn: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs": open connection: timeout: no recent network activity
+0800 2024-07-16 16:03:31 ERROR router: fetch rule-set geoip-cn: Get "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/srs/cn.srs": open connection: timeout: no recent network activity
配置成功

**Comment by xiuyuanxm** [comment]
没有日志，防火墙也打开端口了，原来也是可以了，请问大佬，可能还有什么其他可能吗，已经重装tuic了，还是一样

**Comment by mack-a** [comment]
换成手机客户端试一下。

**Comment by xiuyuanxm** [comment]
试了nekobox 1.3.1版本，服务器端还是没有tuic日志，突然不能用的。。
![image](https://github.com/user-attachments/assets/bad3c768-aad5-4ca6-b94e-27cd64a0da49)

**Comment by xiuyuanxm** [comment]
![image](https://github.com/user-attachments/assets/738a3969-fea6-4c9f-933b-3ca2747ada68)
但是其他几个服务也是这样的

**Comment by mack-a** [comment]
参考这个 https://t.me/v2rayAgentChannel/1729

**Comment by xiuyuanxm** [comment]
已经解决，谢谢大佬！
