### ISSUE TITLE
只是放开443端口连接不上呢，必须全部放开才行，用的其他端口是动态的吗，还是说几个固定的能不能修改，怎么确定都用哪些？

### ISSUE THREAD

**Issue by 3039561909** [mack-a/v2ray-agent#1069]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
参考示例：vasma->2->2->0,7,9,10，选择后一路回车，安装完毕后选择7->1 查看账号 **VLESS gRPC TLS [仅CDN推荐]**不展示等。
```

## 2.安装失败的log或者截图
```
请在这里填写
```

## 3.系统版本
```
请在这里填写
```

## 4.脚本版本
```
请在这里填写
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
请在这里填写
```
- 安装方式（1.全部安装、2.任意组合安装）
```
请填写
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
可以用数字代替，比如0.VLESS+TLS_Vision+TCP-->0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请在这里填写
```

**Comment by mack-a** [comment]
脚本只会自动开启需要的端口。
