### ISSUE TITLE
生成的订阅的分组规则可以自定义吗

### ISSUE THREAD

**Issue by jimmy-yao** [mack-a/v2ray-agent#1071]
生成的订阅的分组规则可以自定义吗，目前生成的分组规则AI分组只有openai和bing的分组规则，想添加Claude.ai的规则该怎么处理，谢谢。

**Comment by mack-a** [comment]
https://wiki.metacubex.one/config/rule-providers/content/#classical 需要自己增加规则。

**Comment by jimmy-yao** [comment]
谢谢回复
可能我没有说清楚，这个安装的时候生成sing-box和clash订阅，是调用的哪个订阅地址URL，
现在用脚本生成的订阅，生成的分组规则AI分组只有openai和bing的分组规则，怎么讲新的规则添加到订阅中呢。

**Comment by jimmy-yao** [comment]
![image](https://github.com/user-attachments/assets/a23d3d2b-ccf2-4a5c-ab9d-36690b2dd3ac)
如图所示，我想通过脚本生成订阅的时候，自带Claude.AI的规则

**Comment by mack-a** [comment]
可以等待后续更新

**Comment by jimmy-yao** [comment]
好的，谢谢。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.11 更新到v3.3.11后重新查看订阅。

**Comment by jimmy-yao** [comment]
这速度，大爱。

**Comment by jimmy-yao** [comment]
有个问题，重新查看订阅，或者重新生成订阅，只有clashMeta订阅生成了Claude的规则组，singbox订阅没有生成。

**Comment by mack-a** [comment]
没找到相应的ruleSet规则，建议手动修改本地配置。
