### ISSUE TITLE
sing_box vmess+httpupgrade, 配置导入v2N不通，Log提示：v2ray-http-upgrade: unexpected status: 521

### ISSUE THREAD

**Issue by KGB333** [mack-a/v2ray-agent#1075]
## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
使用vasma->1->2（sing_box）搭建完成后，使用账号里vmess+httpupgrade配置导入v2rayN不通，无法正常使用，求助A大~
```

## 2.安装失败的log或者截图

截图：
![1721807630699](https://github.com/user-attachments/assets/c0784d59-e92a-4c7c-9c20-a9884540e44f)

## 3.系统版本
```
PC Win11, VPS Debian 12x64
```

## 4.脚本版本
```
3.3.12
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
2
```
- 安装方式（1.全部安装、2.任意组合安装）
```
1
```  

## 6.客户端版本
```
v2rayN V6.52
```

配置截图：
![1721807412584](https://github.com/user-attachments/assets/ce635d34-b3df-4883-9ac3-e1a31ee82ec0)

**Comment by mack-a** [comment]
https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-521-web-server-is-down

检查一下服务端的服务是否正常启动。

**Comment by KGB333** [comment]
> https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-521-web-server-is-down
> 
> 检查一下服务端的服务是否正常启动。

我这边看服务端sing-box是在运行中的，其他协议也没有问题，唯独VmessHttpupgrade无法使用，然后看了一眼服务端配置文件我发现httpupgrade监听的端口是31306，我当时设置的是2053，vasma>7>1查看也是显示2053，不知道跟这个有没有关系（但我尝试改成2053保存后重启sing-box，客户端还是报521）

**Comment by mack-a** [comment]
30306是正常的，看一下nginx是否正常启动。

**Comment by KGB333** [comment]
vasma>8显示该功能只支持xray-core, 灭克大佬有啥建议么> 30306是正常的，看一下nginx是否正常启动。

**Comment by KGB333** [comment]
> 30306是正常的，看一下nginx是否正常启动。

vasma>8 显示此功能只支持xray-core内核，灭克大佬有啥建议么

**Comment by mack-a** [comment]
singbox不支持伪装站点。 @KGB333

**Comment by KGB333** [comment]
> singbox不支持伪装站点。 @KGB333

刚用nginx命令后能看到nginx在进程中，现在连接的话显示如下
![1721878552881](https://github.com/user-attachments/assets/195a0847-9341-4637-b2a8-d6d15e0bad3d)

**Comment by mack-a** [comment]
换个客户端试一下。用订阅拉取，不要用手动填写。

**Comment by KGB333** [comment]
> 换个客户端试一下。用订阅拉取，不要用手动填写。

现在用v2NG能用了，我现在怀疑是N的问题，我再试一下等下给你反馈，感谢灭克

**Comment by KGB333** [comment]
已测试，总结就是：
nginx刚开始应该是没启动，然后v2N和v2NG都是能用的，但不同的是v2NG path可以加ed，v2N 如果path 加 ed 是不能通的，应该是v2N的问题。

**Comment by KGB333** [comment]
现在使用倒是没问题，就是log一直报这种ERROR：
![1721960100162](https://github.com/user-attachments/assets/edb605b6-b016-418e-bd06-16c99c179967)
