### ISSUE TITLE
vps 被自动安装了Mikutap

### ISSUE THREAD

**Issue by UncleUncleWang** [mack-a/v2ray-agent#1079]
完全干净的 vps，没有装过其他脚本，为啥会挂上了Mikutap

**Comment by mack-a** [comment]
使用xray-core安装后会自动随机一个伪装站点。你可以选择使用sing-box，sing-box没有默认的伪装站点。
伪装站点列表 https://github.com/mack-a/v2ray-agent/tree/master/fodder/blog/unable 。
