### ISSUE TITLE
更新脚本命令无法更新到最新版本

### ISSUE THREAD

**Issue by lfxx** [mack-a/v2ray-agent#108]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 更新脚本命令无法更新最新脚本，我选择11选项想把脚本更新到最新2.3.21版本，却显示最新还是2.3.20
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- ubuntu18.04

**6.脚本版本**

- 2.3.20

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by mack-a** [comment]
稍等 我查看一下

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.22 此版本已修复

先用下面的命令更新下

wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by lfxx** [comment]
> [`v2.3.22` (release)](https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.22) 此版本已修复
> 
> 先用下面的命令更新下
> 
> wget -P /root -N --no-check-certificate "[`master`/install.sh (raw)](https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh)" && chmod 700 /root/install.sh && /root/install.sh

root@cool-baud-3:~# wget -P /root -N --no-check-certificate "master/install.sh (raw)" && chmod 700 /root/install.sh && /root/install.sh
--2021-03-01 02:19:10--  http://master/install.sh%20(raw)
Resolving master (master)... failed: Name or service not known.
wget: unable to resolve host address ‘master’
报错了

**Comment by mack-a** [comment]
> > [`v2.3.22` (release)](https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.22) 此版本已修复
> > 先用下面的命令更新下
> > wget -P /root -N --no-check-certificate "[`master`/install.sh (raw)](https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh)" && chmod 700 /root/install.sh && /root/install.sh
> 
> root@cool-baud-3:~# wget -P /root -N --no-check-certificate "master/install.sh (raw)" && chmod 700 /root/install.sh && /root/install.sh
> --2021-03-01 02:19:10-- http://master/install.sh%20(raw)
> Resolving master (master)... failed: Name or service not known.
> wget: unable to resolve host address ‘master’
> 报错了

请复制完整
