### ISSUE TITLE
安装提示Nginx启动失败的问题

### ISSUE THREAD

**Issue by CHKZL** [mack-a/v2ray-agent#1081]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
使用搬瓦工的机器，使用官方镜像（ubuntu2004-2404 3个版本都试过）
未进行其他操作，直接进行安装，安装到最后提示Nginx重启失败。
尝试过根据提示手动安装Nginx和卸载Nginx后再重装Nginx，错误依旧
```

## 2.安装失败的log或者截图
```
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本 
```

## 3.系统版本
```
ubuntu20.04_64
```

## 4.脚本版本
```
v3.3.13 
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
全部安装
```

**Comment by mack-a** [comment]
未复现，tg私聊 @mack_a_bot
