### ISSUE TITLE
tuic无法连接

### ISSUE THREAD

**Issue by superabbite1** [mack-a/v2ray-agent#1082]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 按照教程（https://www.v2ray-agent.com/archives/1687167522196）安装了tuic V5 ，但是发现无法访问，所有网页都打不开，这是什么问题呢
```
## 2.安装失败的log或者截图
```
![QQ截图20240814232216](https://github.com/user-attachments/assets/2f68dad3-8369-4f74-857a-b2dd9d6ae2b6)
![QQ截图20240814232225](https://github.com/user-attachments/assets/635b889f-60c5-4708-a0be-e5b829e135fc)
```

## 3.系统版本
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

```

## 4.脚本版本
```
github最新版本
```

## 5.服务端安装的内核、协议、安装方式
- 
```核心（1.xray-core）
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```  
vasma->1/2->输入域名一路回车
安装Tuic
vasma->6.Tuic管理
```  
## 6.客户端版本
```
v2rayN v6.29

```

**Comment by mack-a** [comment]
更换客户端试一下。

**Comment by superabbite1** [comment]
换了最新的6.55可以了
