### ISSUE TITLE
全新安装-无法更新核心

### ISSUE THREAD

**Issue by wsj911** [mack-a/v2ray-agent#1085]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
2->1->7.之后在“安装xray”出错。提示“核心下载失败，请重新尝试安装，是否重新尝试？[y/n]”。
按y后，继续出现，再按y,问题依旧

参考示例：vasma->2->2->0,7,9,10，选择后一路回车，安装完毕后选择7->1 查看账号 **VLESS gRPC TLS [仅CDN推荐]**不展示等。
```

## 2.安装失败的log或者截图
```

```

## 3.系统版本
```centos 7.0
```

## 4.脚本版本
```v3.3.13
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```2, 任意组合安装 
```  
![1724677350880](https://github.com/user-attachments/assets/fb48a988-a1bd-4d3f-9090-7449921748c1)

- 协议(0.VLESS+TLS_Vision+TCP)
```
7.VLESS+Reality+uTLS+Vision[推荐] 
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请在这里填写
```

**Comment by wsj911** [comment]
补充一个图
![1724677814885](https://github.com/user-attachments/assets/2c452ffe-405c-4f46-9d6a-132d8a6a973c)

**Comment by mack-a** [comment]
系统未安装jq功能，可以tg 私聊 @mack_a_bot。
