### ISSUE TITLE
CloudFlare DNS 申请证书一直卡住不动

### ISSUE THREAD

**Issue by x8-phoenix** [mack-a/v2ray-agent#1086]
通过CloudFlare DNS API申请证书一直卡住不动，CloudFlare 的DNS 记录申请之后也有添加TXT记录值
![image](https://github.com/user-attachments/assets/eea0d0e0-6ce9-4a9d-87b8-9a631afd1409)

![image](https://github.com/user-attachments/assets/bfbcbc38-f793-4ce9-896d-e643af1b264e)

**Comment by mack-a** [comment]
超时后有没有报错

**Comment by x8-phoenix** [comment]
> 超时后有没有报错

没有任何提示，就卡在那里了，等了20多分钟也没有反应

**Comment by mack-a** [comment]
> > 超时后有没有报错
> 
> 没有任何提示，就卡在那里了，等了20多分钟也没有反应

用的什么域名后缀

**Comment by mack-a** [comment]
目前未复现，可以将服务器私聊给机器人。 @mack_a_bot

**Comment by x8-phoenix** [comment]
> > > 超时后有没有报错
> > 
> > 
> > 没有任何提示，就卡在那里了，等了20多分钟也没有反应
> 
> 用的什么域名后缀

.xyz的域名
