### ISSUE TITLE
最新v3.3.14 版本reality不能正常连接

### ISSUE THREAD

**Issue by e70123456** [mack-a/v2ray-agent#1087]
VLESS reality_vision、VLESS reality_gRPC，使用opwrt、Xray内核v2rayN客户端均不能正常连接，同时连接VLESS_TCP/TLS_Vision正常。
如开发者有测速过v3.3.14 版本reality正常，请忽略该问题，并关闭。

**Comment by mack-a** [comment]
更换reality域名重新尝试。
