### ISSUE TITLE
ubuntu下部分协议失效

### ISSUE THREAD

**Issue by HysterLc** [mack-a/v2ray-agent#1091]
## 1.问题描述
[- 尽可能的将复现步骤描述清楚
```
在安卓和windows都可以正常使用，在ubuntu中只有vless_grpc可以用， tls_vision/reality_vision/reality_grpc全部都可以ping通

连接tls_vision/reality_vision/reality_grpc $\rightarrow$ 测试ping成功 $\rightarrow$ 打开网页 $\rightarrow$ 报错
```]

## 2.安装失败的log或者截图
```
客户端日志
 2024/10/08 15:09:42.205 [W] [asm_amd64.s:1695]  ObservatoryProducer: did not connect: context deadline exceeded 2024/10/08 15:09:42.206 [I] [io.go:431]  127.0.0.1:42530 accepted tcp:127.0.0.1:0 [api-out] 2024/10/08 15:09:42.754 [I] [io.go:431]  V2Ray 5.19.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.23.1 linux/amd64) 2024/10/08 15:09:42.754 [I] [io.go:431]  A unified platform for anti-censorship. 2024/10/08 15:09:43.454 [I] [io.go:431]  127.0.0.1:50574 accepted tcp:127.0.0.1:0 [api-out] 2024/10/08 15:09:44.415 [I] [io.go:431]  10.211.89.93:53052 accepted tcp:40.79.197.34:443 [proxy]

网页端
Hmmm… can't reach this page
It looks like github.com closed the connection
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_CLOSED
```

## 3.系统版本
```
ubuntu22.03
```

## 4.脚本版本
```
3.3.1
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
1.xray-core
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```  
- 已安装协议: VLESS+TCP[TLS_Vision] VLESS+gRPC[TLS] VLESS+Reality+Vision VLESS+Reality+gRPC 
```
可以用数字代替，比如0.VLESS+TLS_Vision+TCP-->0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18

v2rayA 2.2.5.8
```

**Comment by mack-a** [comment]
更换客户端以及内核试一下。

**Comment by HysterLc** [comment]
> 更换客户端以及内核试一下。

尝试了更新内核，重新安装脚本都没解决。
客户端尝试了Qv2ray,clash都只有reality_grpc可以用。
最后换sing-box开启TUN模式解决了，可能跟linux系统有关？
