### ISSUE TITLE
能否支持两个hy2节点的vps之间的端口转发？

### ISSUE THREAD

**Issue by li12138** [mack-a/v2ray-agent#1093]
**详细描述建议的内容**
我是有两个vps，都用hy2协议，想保护我的落地ip不被墙。
两个hy2都开启了端口跳跃，这两个vps之间还能用端口转发吗？

**Comment by mack-a** [comment]
落地的hy2选择用固定端口。或者在落地机器端口跳跃中选择一个端口做为固定端口。
但是脚本不支持端口->端口转发，只有针对域名或者全局的分流，例如socks5。
