### ISSUE TITLE
Socks5出站功能 出現問題

### ISSUE THREAD

**Issue by hojo-yukinoshita** [mack-a/v2ray-agent#1094]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
参考示例：vasma->2->2->0,7,9,10，选择后一路回车，安装完毕后选择7->1 查看账号 **VLESS gRPC TLS [仅CDN推荐]**不展示等。
```

vasma -- 1 -- X-Ray -- 一路正常安裝輸入自有域名以及正常自定義UUID，一路回車後 ，確認能在v2rayN v5.39正常使用該節點後，進入11【分流工具】設置socks5全局分流。設置的socks5代理是由NPS客戶端 
（https://github.com/ehang-io/nps）

發出的，能在v2rayN等客戶端上正常使用的socks5代理，有完整的地址和帳號密碼驗證.

結果設置完socks5出站之後，所有的流量都無法被正常導向這個正常運作的socks5代理，而是顯示所有http或https請求都是tcp:127.0.0.1:443，即不能正常訪問任何內容。卸載socks5出站之後，立刻完全恢復正常... 但我確實非常需要配置這個socks5出站，所以十萬火急希望知道為何出現這種問題及如何解決。再三叩首多謝！

## 2.安装失败的log或者截图

已安装 xray-core socks5全局出站分流 

出站分流配置： 
{
  "address": "正常可用的地址",
  "port": 正常可用的端口,
  "users": [
    {
      "user": "正常可用的用戶名",
      "pass": "正常可用的密鑰"
    }
  ]
} 

而socks5全局轉發的出站配置完成之後，xray-core服務日誌如下：

2024/10/16 00:43:13 from 我的客戶端家庭IP地址:57496 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:18 from 我的客戶端家庭IP地址:57507 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:18 from 我的客戶端家庭IP地址:57517 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:18 from 我的客戶端家庭IP地址:57516 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:18 from 我的客戶端家庭IP地址:57515 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:23 from 我的客戶端家庭IP地址:57535 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:23 from 我的客戶端家庭IP地址:57534 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:23 from 我的客戶端家庭IP地址:57533 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
2024/10/16 00:43:23 from 我的客戶端家庭IP地址:57544 accepted tcp:127.0.0.1:443 [dokodemo-door-newPort-8019 >> socks5_outbound]
顯然是異常的

## 3.系统版本
```
客戶端：Windows 10 LTSC 1809
服務端：Debian 12
```

## 4.脚本版本
```
v3.3.19```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
XRay-Core
```
- 安装方式（1.全部安装、2.任意组合安装）
全部安裝

```  
## 6.客户端版本
```
v2rayN 5.39
Brave Browser v1.70.126
Proxy SwitchyOmega

**Comment by mack-a** [comment]
設置的socks5代理是由NPS客戶端發出的，能在v2rayN等客戶端上正常使用的socks5代理，有完整的地址和帳號密碼驗證.

这句话的意思是socks5的入站是由nps提供吗？

**Comment by hojo-yukinoshita** [comment]
> 設置的socks5代理是由NPS客戶端發出的，能在v2rayN等客戶端上正常使用的socks5代理，有完整的地址和帳號密碼驗證.
> 
> 这句话的意思是socks5的入站是由nps提供吗？

對不起我可能用語不是特別精準，請多多包涵！但我用到的就是"https://ehang-io.github.io/nps/#/example?id=socks5%e4%bb%a3%e7%90%86" 中提到的這個socks5代理 在我自己的一台機器上運行的。[socks5代理](https://ehang-io.github.io/nps/#/example?id=socks5%e4%bb%a3%e7%90%86)
适用范围： 在外网环境下如同使用vpn一样访问内网设备或者资源

假设场景： 想将公网服务器1.1.1.1的8003端口作为socks5代理，达到访问内网任意设备或者资源的效果

使用步骤

在刚才创建的客户端隧道管理中添加一条socks5代理，填写监听的端口（8003），保存。
在外网环境的本机配置socks5代理(例如使用proxifier进行全局代理)，ip为公网服务器ip（1.1.1.1），端口为填写的监听端口(8003)，即可畅享内网了
注意 经过socks5代理，当收到socks5数据包时socket已经是accept状态。表现是扫描端口全open，建立连接后短时间关闭。若想同内网表现一致，建议远程连接一台设备。

**Comment by mack-a** [comment]
使用分流工具选择socks5分流，输入IP、用户、密码即可（这里是你的nps提供）。

**Comment by hojo-yukinoshita** [comment]
> 使用分流工具选择socks5分流，输入IP、用户、密码即可（这里是你的nps提供）。

對對，我就是完全按這樣做了，然後遇到了我issue裡描述的問題，所以才開這個issue的。還懇請您再看看我最初寫的內容～ 再次感謝！

**Comment by mack-a** [comment]
能贴一下nps的日志吗？

**Comment by hojo-yukinoshita** [comment]
> 能贴一下nps的日志吗？

抱歉NPS這邊我設置了log_level=0所以沒有日誌  但如果您認為有必要的話我會重新配置一遍然後給你發NPS的日誌

**Comment by mack-a** [comment]
看一下是否正常访问倒nps

**Comment by hojo-yukinoshita** [comment]
> 看一下是否正常访问倒nps

我剛剛專門購買了一個Colocrossing的IPv4 VPS來復現整個測試過程，結果發現完全沒有任何問題，socks5出站設置成功並完美可用。socks5出站設置後出現問題的兩台VPS則都是NAT(natvps.uk)和IPv6-only VPS （Scaleway Stardust）。因此初步懷疑是這兩台機器上與一般正常擁有獨立IPv4的VPS有所不同的DNS解析設置 與 您腳本中的socks5出站設置產生了不知怎麼樣的衝突
