### ISSUE TITLE
伪装站绑定多个域名咋设置呢

### ISSUE THREAD

**Issue by sundys** [mack-a/v2ray-agent#1097]
**详细描述建议的内容**
域名在nginx添加，域名证书没找到在哪里指定，大佬能指点一下在哪里修改吗

**Comment by mack-a** [comment]
/etc/v2ray-agent/tls

**Comment by siren202101** [comment]
> 证书位置 /etc/v2ray-agent/tls nginx配置文件位置 /etc/nginx/conf.d/ https需要配置几行代码，具体的问下AI。

A大，能否添加一个功能，让脚本可以申请其它域名的证书并且自动更新证书
自从有了AI彻底抛弃宝塔了，但自己去申请证书又不知道设置后会不会冲突导致脚本的自动更新失败
所以希望大佬在脚本添加一个申请其它域名证书并且自动更新证书的功能，最好是支持申请通配符

**Comment by ARC-XX** [comment]
> 证书位置 /etc/v2ray-agent/tls nginx配置文件位置 /etc/nginx/conf.d/ https需要配置几行代码，具体的问下AI。

可是大佬，目前版本的443端口似乎被xray占用了，具体的链路好像是 
[client]
   └─> [xray]
         ├─> [proxy]
         └─> [nginx]

```json
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "tag": "VLESSTCP",
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.2",
          "certificates": [
            {
              "certificateFile": "/etc/v2ray-agent/tls/********.crt",
              "keyFile": "/etc/v2ray-agent/tls/*********.key",
              "ocspStapling": 3600
            }
          ]
        }
      }
    }
  ]
}
```
