### ISSUE TITLE
关于hysteria自签名证书的问题

### ISSUE THREAD

**Issue by ax003** [mack-a/v2ray-agent#1099]
hysteria2已经支持自签名证书
但目前脚本选择singbox安装hysteria的时候，还是会提示缺少证书，需要安装其他带tls的协议
希望后续版本能修正

**详细描述建议的内容**

**Comment by mack-a** [comment]
https://www.v2ray-agent.com/archives/1679931532764#%E4%BA%94%E3%80%81%E8%AF%81%E4%B9%A6%E7%9B%B8%E5%85%B3%E5%86%85%E5%AE%B9
