### ISSUE TITLE
本脚本不支持此系统，请将下方日志反馈给开发者

### ISSUE THREAD

**Issue by svnfox** [mack-a/v2ray-agent#1100]
本脚本不支持此系统，请将下方日志反馈给开发者
 
\S
 on an \m 
Linux version 6.6.34-9.oc9.x86_64 (mockbuild@builder1.x86.opencloudos.tech) (gcc (Tencent Compiler 12.3.1.1) 12.3.1 20230912 (OpenCloudOS 12.3.1.1-1), GNU ld (GNU Binutils) 2.41) #1 SMP PREEMPT_DYNAMIC Wed Jun 19 19:35:45 CST 2024

**Comment by mack-a** [comment]
目前仅支持 Debian、Ubuntu、Centos、Alpine。
