### ISSUE TITLE
更新证书失败

### ISSUE THREAD

**Issue by superabbite1** [mack-a/v2ray-agent#1102]
证书到期后，更新证书报错了

进度  1/1 : 更新证书 
 ---> 证书检查日期:2024-11-15 13:37:54 
 ---> 证书生成日期:2024-08-14 10:55:43 
 ---> 证书生成天数:93 
 ---> 证书剩余天数:已过期 
 ---> 证书过期前最后一天自动更新，如更新失败请手动更新 
 ---> 重新生成证书 
 ---> Nginx关闭成功 
 ---> Xray关闭成功 
[Fri 15 Nov 2024 01:37:55 PM UTC] ===Starting cron===
[Fri 15 Nov 2024 01:37:56 PM UTC] Renewing: '*.马赛克.top'
[Fri 15 Nov 2024 01:37:56 PM UTC] Renewing using Le_API=https://acme-v02.api.letsencrypt.org/directory
[Fri 15 Nov 2024 01:37:56 PM UTC] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri 15 Nov 2024 01:37:56 PM UTC] Single domain='*.马赛克.top'
[Fri 15 Nov 2024 01:37:57 PM UTC] Getting webroot for domain='*.马赛克.top'
[Fri 15 Nov 2024 01:37:58 PM UTC] Adding TXT value: RqX4kD8yEPO-qtNicc7Tl8xJDFv98QDpF马赛克 domain: _acme-challenge.马赛克.top
[Fri 15 Nov 2024 01:37:58 PM UTC] invalid domain
[Fri 15 Nov 2024 01:37:58 PM UTC] Error adding TXT record to domain: _acme-challenge.马赛克.top
[Fri 15 Nov 2024 01:37:58 PM UTC] Please add '--debug' or '--log' to see more information.
[Fri 15 Nov 2024 01:37:58 PM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri 15 Nov 2024 01:37:59 PM UTC] Error renewing *.马赛克.top_ecc.
[Fri 15 Nov 2024 01:37:59 PM UTC] ===End cron===
[Fri 15 Nov 2024 01:37:59 PM UTC] The domain '马赛克.top' is not a cert name. You must use the cert name to specify the cert to install.
[Fri 15 Nov 2024 01:37:59 PM UTC] Cannot find path: '/root/.acme.sh/马赛克.top_ecc'
 ---> Xray关闭成功 
 ---> Xray启动成功

**Comment by myworksfun** [comment]
> [Fri 15 Nov 2024 01:37:58 PM UTC] Adding TXT value: RqX4kD8yEPO-qtNicc7Tl8xJDFv98QDpF马赛克 domain: _acme-challenge.马赛克.top
> [Fri 15 Nov 2024 01:37:58 PM UTC] invalid domain
> [Fri 15 Nov 2024 01:37:58 PM UTC] Error adding TXT record to domain: _acme-challenge.马赛克.top

**Refer to the error message above, which may help solve your issue.**😄

**Comment by mack-a** [comment]
重新安装试一下。 @superabbite1
