### ISSUE TITLE
无法切换到系统代理模式

### ISSUE THREAD

**Issue by oupeng** [mack-a/v2ray-agent#1103]
**详细描述建议的内容**
Mac App Store版本的sing-box客户端
服务器核心为sing-box
协议为VLESS_Reality_Vision
脚本更新到最新版本后（3.3.20）默认为tun模式
无论怎么修改配置文件，都无法使用系统代理模式
是否可以增加一个切换tun模式或系统代理模式的功能？

实在抱歉小白一枚
YouTube、chatgpt、博客各种教程跟着学，改好配置文件后，直接无法翻墙，日志也没有报错

用GUI for sing-box默认倒是可以系统代理，但在Mac平台不太好用，把生成的配置文件导入到官方客户端，还是不行

实在没办法了才到这儿求教！请理解一下

**Comment by mack-a** [comment]
Mac平台建议使用clash-verge-rev。
