### ISSUE TITLE
设置302跳转，重启系统后失效

### ISSUE THREAD

**Issue by gxhunter1982** [mack-a/v2ray-agent#1106]
## 1.问题描述
设置302跳转，重启后失效。
1，设置时会提示失败，302跳转无效。但此时不重启，设置其他选项，让xray内核关闭重启后，302跳转就有效的。但重启系统后还是失效
2，有时设置是提示成功（好像是重新安装完节点后，第一时间设置302才会提示成功），但重启系统后还是失效

## 2.安装失败的log或者截图

![1202](https://github.com/user-attachments/assets/f4c32094-7f4a-47b7-af8e-c06dea05cae5)

## 3.系统版本
```
debian 12
x86
```

## 4.脚本版本
```
3.3.21
```

## 5.服务端安装的内核、协议、安装方式
- 核心
- 1.xray-core

- 安装方式
- 1.全部安装

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.22 用一下此版本，如还有问题描述详细的的复现步骤。

**Comment by gxhunter1982** [comment]
新版应该是OK的

测试了好几遍中，发生过一次最开始那种红字提示的“302重定向错误”，我执行了两遍删除命令后，再添加就暂时没再出现这个错误了。

但现在我碰到了其他情况

我在测试服务器重启后，在本地测试跳转有没有生效时，发现不同游览器不同模式在差不多同一个时间，有时会有不同的结果，有些还是原网页，有些就跳转了。测的很崩溃。有些F5半天还是本来的，有时过一会F5就跳转生效了，但有时过一会再手动输入原网址，进去的还是本来的网页，没有跳转。
我测的是我手里的两个不同服务器不同域名，分别用我的笔记本和台式机分别测试。

![屏幕截图 2024-12-03 192719](https://github.com/user-attachments/assets/47391f2f-76de-4c2a-9e5c-83cbe8065aa7)
Y是跳转生效，N是无效。

测了太多遍，真的不知道是服务端，还是我本地，还是墙的问题。

原本的问题，应该是修正了，先关闭吧
