### ISSUE TITLE
没有速度

### ISSUE THREAD

**Issue by geek2024811** [mack-a/v2ray-agent#1108]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
```
用的是.sing-box 无域名版Reality。2-2-7 回车回车，测速一点速度都没有
```

## 2.安装失败的log或者截图
```
![image](https://github.com/user-attachments/assets/f3df3545-df0b-4308-b6b4-ce38b11f203e)
```

## 3.系统版本
```
Debian12
```

## 4.脚本版本
```
wget -P /root -N --no-check-certificate https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh && chmod 700 /root/install.sh && /root/install.sh
```

## 5.服务端安装的内核、协议、安装方式
- 核心（1.xray-core、2.sing-box）
```
请在这里填写
```sing-box
- 安装方式（1.全部安装、2.任意组合安装）
```2
请填写
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
可以用数字代替，比如0.VLESS+TLS_Vision+TCP-->0
```  
## 6.客户端版本
```
# 比如v2rayNG 1.18
请在这里填写
```

**Comment by mack-a** [comment]
安装其它协议试一下。
