### ISSUE TITLE
大佬我在用脚本更新Xray-core 1.3.1时有错误

### ISSUE THREAD

**Issue by jhx80kg** [mack-a/v2ray-agent#111]
之前脚本安装的是1.3.0，一切顺利正常，今天打开脚本，先更新脚本，一切正常
当我更新xray-core的时候 有这样的提示：
/usr/sbin/vasma: line 3184: 成账号: command not found

/usr/sbin/vasma: line 3187: syntax error near unexpected token `else'
/usr/sbin/vasma: line 3187: `   else'

麻烦大佬帮忙看一下是哪里的问题

**Comment by mack-a** [comment]
> 之前脚本安装的是1.3.0，一切顺利正常，今天打开脚本，先更新脚本，一切正常
> 当我更新xray-core的时候 有这样的提示：
> /usr/sbin/vasma: line 3184: 成账号: command not found
> 
> /usr/sbin/vasma: line 3187: syntax error near unexpected token `else' /usr/sbin/vasma: line 3187: ` else'
> 
> 麻烦大佬帮忙看一下是哪里的问题

啥版本的shell

**Comment by jhx80kg** [comment]
SercureCRT 8.7.2

**Comment by jhx80kg** [comment]
putty 0.74也是一样的错误

**Comment by jhx80kg** [comment]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by mack-a** [comment]
100%复现吗
