### ISSUE TITLE
二次设置socks分流后，分流设置失效

### ISSUE THREAD

**Issue by S6venA** [mack-a/v2ray-agent#1110]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
- 尽可能的将复现步骤描述清楚
核心：sing-box
搭建协议：vmess+ws+cdn、vless+reality、hy2、tuic

第一次设置socks全局分流成功，后续换了一个socks5地址后，设置不起作用，在ipinfo中查询都是本机地址，查看核心日志也没有想过出站数据

![iShot_2024-12-04_09 43 27](https://github.com/user-attachments/assets/3100cfa9-b136-44fb-a212-7da4452f3cf1)
## 2.安装失败的log或者截图
出站变成了直接出站
![iShot_2024-12-04_09 47 40](https://github.com/user-attachments/assets/9dfe036d-a979-4c18-af9f-e21153f8692e)
## 3.系统版本
```
debian11
```

## 4.脚本版本
```
v3.3.22
```

## 5.服务端安装的内核、协议、安装方式
- 核心
```
2.sing-box
```
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```  
- 协议(0.VLESS+TLS_Vision+TCP)
```
3,6,7,9
```  
## 6.客户端版本
```
shadowrocket
```

**Comment by mack-a** [comment]
未复现，是否进行了其他操作？

**Comment by S6venA** [comment]
> 未复现，是否进行了其他操作？

没有任何其他操作

**Comment by caixiaomao** [comment]
相同的问题

**Comment by mack-a** [comment]
> 相同的问题

提供一下复现步骤。

**Comment by S6venA** [comment]
1. 添加一个全局socks5分流
2. 删除全局socks5分流
3. 增加一个新的socks5分流
使用sing-box内核

**Comment by S6venA** [comment]
> > 相同的问题
> 
> 提供一下复现步骤。


    添加一个全局socks5分流
    删除全局socks5分流
    增加一个新的socks5分流
    使用sing-box内核

**Comment by caixiaomao** [comment]
> > 相同的问题
> 
> 提供一下复现步骤。

添加socks5分流
卸载socks5分流
添加全局socks5分流
内核：sing-box

**Comment by caixiaomao** [comment]
重装复现了下，确实会出现失效，步骤：
1. 安装全局socks5 出站
2. 卸载 全局socks5 出站
3. 再次安装 全局socks5 出站
4. 失效

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.25
