### ISSUE TITLE
重新安装Reality协议，会导致Reality配置dest字段缺失端口信息。

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#1112]
## 1.问题描述
在Reality正常可用的情况下，重新安装该协议，会导致Reality协议失效。
操作：
vasma->5->一路y下去。

定位发现是07_VLESS_vision_reality_inbounds.json里
dest字段缺失了端口信息。

## 4.脚本版本
v3.3.22

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.23
