### ISSUE TITLE
Xray核心,套用CDN后订阅链接失效

### ISSUE THREAD

**Issue by ddtpower3** [mack-a/v2ray-agent#1113]
为了套用CDN,监听端口设为443,订阅端口只能设定为其他值. 套用CDN后,订阅链接不能被CDN节点转发,从而失效. 能否将订阅链接置于伪装站点的访问路径中. 老版本似乎没有这个问题.

**Comment by mack-a** [comment]
https://www.v2ray-agent.com/archives/1684858575649#%E4%BA%8C%E3%80%81%E8%84%9A%E6%9C%AC%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B

订阅可以采用 2053,2083,2087,2096,8443这些端口，同样可以过CDN。
