### ISSUE TITLE
请求新功能：增加一个支持Full Cone（UOT）的Vless+TLS+WS安装选项。

### ISSUE THREAD

**Issue by Accademia** [mack-a/v2ray-agent#1115]
目前的所有一键安装脚本，都没有支持Fullcone（UOT）的Vless+TLS+WS （Sing-Box）。希望能增加这个。非常感谢。

照着开发日志的，散装安装教程，实在看不懂。

我看了用贵项目生成的配置，貌似服务器端，并没有这样的字段。

      "udp": {
        "enabled": true,
        "fullcone": true
      }

客户端也米有这样的字段。

    udp: true
    packet-encoding: xudp

而且手动修改字段 重启服务后，UOT依旧不生效。所以，需要脚本原生支持UOT。非常感谢@mack-a

**Comment by mack-a** [comment]
https://www.youtube.com/watch?v=GQg5JIQIjgk 参考这个。

**Comment by Accademia** [comment]
> https://www.youtube.com/watch?v=GQg5JIQIjgk 参考这个。

大佬，我发帖之前，这个视频翻过三遍。但是还是不得要领。按照视频所说，只要吧1024-65535 UDP端口开放就可以在Vless+TLS+WS+Sing-box服务端实现FullCone支持。但问题是。使用贵脚本的VPS，压根没有装防火墙，我命令行也检测过了，没有端口被阻挡。但问题是，还是UOT失败。所以我怀疑，是不是脚本本身制作出来的Vless+TLS+WS+Sing-box，就没有FullCone支持？

**Comment by mack-a** [comment]
你可以试试xray内核。
