### ISSUE TITLE
被墙的vps使用了 Vmess+Ws+Tls  套用domain08.qiu4.ml无法访问国内网站

### ISSUE THREAD

**Issue by csvf** [mack-a/v2ray-agent#112]
一键 安装的 稳定-v2.2.24 
使用  Vmess+Ws+Tls 协议 由于ip被墙了 使用大佬提供的 domain08.qiu4.ml 地址 ，vps救活了  外网正常访问。
但是国内的网站打不开，求解 如何操作？

**Comment by mack-a** [comment]
看一下你本地的路由规则或者pac

**Comment by csvf** [comment]
> 看一下你本地的路由规则或者pac，检查一下

找到原因了。客户端设置的问题， 改为pac 自动配置系统代理模式；预定义规则设置绕过局域网和xx地址就可以了。感谢。
