### ISSUE TITLE
安装配置nginx报错，域名解析出来的内容不是IP 

### ISSUE THREAD

**Issue by sad-castle** [mack-a/v2ray-agent#113]
**1.描述出现的问题**

-安装配置nginx报错，域名解析出错，域名解析出来的结果与预期不符

**2.是否直接安装失败**

- 是

**3.是否重新build系统后尝试**

- 是

**4.直接安装失败的错误内容或者截图**
输入域名后 解析出来的应该是IP 才对吧,但是内容是框里这个
**-请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:hg1.******.top

 ---> 配置Nginx 

检查IP是否设置为当前VPS 
 ---> 检查ipv4中 

当前域名的IP为 [64 bytes from 193.122.120.*: icmp_seq=0 ttl=63 time=1.230 ms]，是否正确[y/n]？n

 ---> 1.检查Cloudflare DNS解析是否正常 
 ---> 2.检查Cloudflare DNS云朵是否为灰色**

**5.系统版本【例：Centos8】**
ubuntu 18.04.5

**6.脚本版本**

- 2.3.27

**7.安装类型**

- 全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
手动ping一下域名

**Comment by sad-castle** [comment]
> 手动ping一下域名

root@hg1:~# ping hg1.*.top
PING hg1.sadcastle.top (193.122.120.155): 56 data bytes
64 bytes from 193.122.120.*: icmp_seq=0 ttl=63 time=1.355 ms
64 bytes from 193.122.120.*: icmp_seq=1 ttl=63 time=0.670 ms

^C--- hg1.*.top ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.283/0.607/1.355/0.397 ms

手动ping 内容是这样的

**Comment by mack-a** [comment]
> > 手动ping一下域名
> 
> root@hg1:~# ping hg1._.top PING hg1._.top (193.122.120._): 56 data bytes 64 bytes from 193.122.120._: icmp_seq=0 ttl=63 time=1.355 ms
> 64 bytes from 193.122.120.*: icmp_seq=1 ttl=63 time=0.670 ms
> 
> ^C--- hg1.*.top ping statistics ---
> 5 packets transmitted, 5 packets received, 0% packet loss
> round-trip min/avg/max/stddev = 0.283/0.607/1.355/0.397 ms
> 
> 手动ping 内容是这样的
> 
> ping -c 1 -W 1000 ${hg1.sadcastle.top} | sed '2{s/[^(]_(//;s/)._//;q;}' | sed -n '$p'
> 感觉像这一行没有提取对

你这是啥机器

**Comment by sad-castle** [comment]
oracle 韩国的机器。系统ubuntu。18.04.5
我也很好奇。我oracle日本的机器就没问题
mack-a <notifications@github.com>于2021年3月8日 周一13:48写道：

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.28 已修复
