### ISSUE TITLE
Cloudflare 优化方案中的疑惑；

### ISSUE THREAD

**Issue by goodluckwxl** [mack-a/v2ray-agent#114]
脚本中的更换cdn节点，与我在 Cloudflare 解析地址填入智能DNS解析的IP是否是一样的效果？根据您在原理解析文章中，脚本中没有关闭选项，我手动更换成自己主机ip是否 为关闭呢？cnd解析中，你已说明用户可以通过客户端自定义cdn，但该如果理解   Cloudflare 中address     和 脚本中更改cdn节点，    用户客户端修改cdn   这3者的关系呢？
另外反馈一个bug，手动设置cnd中，输入一个错误的域名，导致 脚本 cdn显示异常.

```
# 
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 否

**6.脚本版本**

- 

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 否

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
> 脚本中的更换cdn节点，与我在 Cloudflare 解析地址填入智能DNS解析的IP是否是一样的效果？根据您在原理解析文章中，脚本中没有关闭选项，我手动更换成自己主机ip是否 为关闭呢？cnd解析中，你已说明用户可以通过客户端自定义cdn，但该如果理解 Cloudflare 中address 和 脚本中更改cdn节点， 用户客户端修改cdn 这3者的关系呢？
> 另外反馈一个bug，手动设置cnd中，输入一个错误的域名，导致 脚本 cdn显示异常.
> 
> ```
> # 
> ```
> 
> **2.是否直接安装失败**
> 
> * 否
> 
> **3.是否重新build系统后尝试**
> 
> * 否
> 
> **4.直接安装失败的错误内容或者截图**
> 
> 
> **5.系统版本【例：Centos8】**
> 
> > 最新版本脚本不支持Centos6
> > 是否更换Debian系统后再次安装
> 
> * 否
> 
> **6.脚本版本**
> 
> 
> **7.安装类型**
> 
> * 个性化安装/全部安装
> 
> **8.安装的核心版本**
> 
> * Xray-core【version】
> 
> **9.出现问题的协议类型**
> 
> 
> **10.尝试重装后是否100%复现**
> 
> * 否
> 
> **11.是否仔细检查客户端与服务端的配置是否相同**
> 
> * 否

- 1.脚本中的设置智能解析ip唯一影响到的地方是查看账号的地方，别的地方没有任何影响。
- 2.根据回答的第一点也就不存在是否关闭dns智能解析的这个东西
- 3.客户端想设置啥就设置啥，和服务端设置什么CDN节点没有任何关系
- 4.不能设置成错的，设置成错的就会影响账号查看的内容
- 5.与你在客户端手动输入CDN的ip功能一样，但是脚本中提供的不是一个单独ip而是一个CNAME解析，区分不同的运营商包含多个ip。
- 6.如果你想账号查看的时候显示自己的域名，则自定义的时候输入自己的域名即可。
