### ISSUE TITLE
域名与IP地址正确，但是总是报错nginx无法正常访问服务器

### ISSUE THREAD

**Issue by blueveryday** [mack-a/v2ray-agent#115]
安装的时候，配置nginx，检查ipv4，询问ip是否正确，yes，然后报错：
`检查Nginx是否正常访问
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->
`

**Comment by NaiHeKK** [comment]
> 检查Nginx是否正常访问 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->
请问你解决了吗

**Comment by blueveryday** [comment]
同样的问题，不晓得如何解决。
