### ISSUE TITLE
Debian10安装到ngnix提示没有此命令。

### ISSUE THREAD

**Issue by RayoungC** [mack-a/v2ray-agent#116]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 否

**6.脚本版本**

- 

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 否

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
手动更新库或者自己安装nginx后重新执行脚本即可

**Comment by malikshi** [comment]
@mack-a why not using Nginx latest build by adding sourcelist? Isn't much better?
