### ISSUE TITLE
谷歌云提示涉嫌挖矿，把个例给封了，大佬求解

### ISSUE THREAD

**Issue by luoyouyu520** [mack-a/v2ray-agent#117]
如题，我相信大佬是不会干这种事情的，但是这个问题可能是流量异常被检查到了，那应该怎么去解决呢？

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/111267357-caac2e80-8666-11eb-9d03-7bb0c84879a3.png)

这个问题应该去问GCP
