### ISSUE TITLE
xray启动失败

### ISSUE THREAD

**Issue by jiahanbryant** [mack-a/v2ray-agent#119]
```
进度  14/17 : 添加定时维护证书 
 ---> 添加定时维护证书成功 
 ---> Xray关闭成功 
xray启动失败 
执行 [ps -ef|grep xray] 查看日志 
```
安装时总在这里失败，运行：
```
root@london:~# ps -ef | grep xray
root      1871  1111  0 13:32 pts/0    00:00:00 grep --color=auto xray
```
```
root@london:~# systemctl status xray.service
● xray.service - Xray - A unified platform for anti-censorship
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-03-21 13:29:15 UTC; 4min 49s ago
  Process: 1826 ExecStart=/etc/v2ray-agent/xray/xray run -confdir /etc/v2ray-agent/xray/conf (code=exited, status=255)
 Main PID: 1826 (code=exited, status=255)

Mar 21 13:29:15 london systemd[1]: xray.service: Main process exited, code=exited, status=255/n/a
Mar 21 13:29:15 london systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 21 13:29:15 london systemd[1]: xray.service: Service hold-off time over, scheduling restart.
Mar 21 13:29:15 london systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Mar 21 13:29:15 london systemd[1]: Stopped Xray - A unified platform for anti-censorship.
Mar 21 13:29:15 london systemd[1]: xray.service: Start request repeated too quickly.
Mar 21 13:29:15 london systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 21 13:29:15 london systemd[1]: Failed to start Xray - A unified platform for anti-censorship.
```

**Comment by mack-a** [comment]
/etc/v2ray-agent/xray/xray run -confdir /etc/v2ray-agent/xray/conf 执行这个 然后把日志发一下

**Comment by cqxx** [comment]
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
A unified platform for anti-censorship.
2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json

**Comment by mack-a** [comment]
> Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> A unified platform for anti-censorship.
> 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json

没报错 应该是启动起来了 但是你和上面的是一个人吗

**Comment by cqxx** [comment]
> > Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > A unified platform for anti-censorship.
> > 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> > xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> 
> 没报错 应该是启动起来了 但是你和上面的是一个人吗

不是一个人，我也是安装的时候，一直在这里报错

**Comment by mack-a** [comment]
> > > Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > > A unified platform for anti-censorship.
> > > 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> > > xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> > 
> > 
> > 没报错 应该是启动起来了 但是你和上面的是一个人吗
> 
> 不是一个人，我也是安装的时候，一直在这里报错

开机自启动不成功 ？ 尝试下安装所有协议

**Comment by cqxx** [comment]
> > > > Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > > > A unified platform for anti-censorship.
> > > > 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> > > > xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> > > 
> > > 
> > > 没报错 应该是启动起来了 但是你和上面的是一个人吗
> > 
> > 
> > 不是一个人，我也是安装的时候，一直在这里报错
> 
> 开机自启动不成功 ？ 尝试下安装所有协议

好的，我安装时输入的2，开始输入1，错误报得更早

**Comment by mack-a** [comment]
> > > > > Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > > > > A unified platform for anti-censorship.
> > > > > 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> > > > > xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> > > > 
> > > > 
> > > > 没报错 应该是启动起来了 但是你和上面的是一个人吗
> > > 
> > > 
> > > 不是一个人，我也是安装的时候，一直在这里报错
> > 
> > 
> > 开机自启动不成功 ？ 尝试下安装所有协议
> 
> 好的，我安装时输入的2，开始输入1，错误报得更早

说一下你的系统版本以及vps厂商是哪一家 刚才试了下个性化安装 然后xray->VLESS WS GCP安装成功，我是用的Debian10

**Comment by cqxx** [comment]
========================个性化安装============================ 
VLESS前置，默认安装0，如果只需要安装0，则只选择0即可 
0.VLESS+TLS/XTLS+TCP 
1.VLESS+TLS+WS[CDN] 
2.VMess+TLS+TCP 
3.VMess+TLS+WS[CDN] 
4.Trojan、Trojan+WS[CDN] 
请选择[多选]，[例如:123]:0
Xray的0-4我都试了，都是卡在这里。v2ray 也是在这里卡住了，我是在oracle cloud的 系统是ubuntu 20

**Comment by cqxx** [comment]
> > > > > > Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > > > > > A unified platform for anti-censorship.
> > > > > > 2021/03/21 13:52:03 Using confdir from arg: /etc/v2ray-agent/xray/conf
> > > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> > > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> > > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> > > > > > xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag: VLESSWS
> > > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> > > > > > 2021/03/21 13:52:03 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> > > > > 
> > > > > 
> > > > > 没报错 应该是启动起来了 但是你和上面的是一个人吗
> > > > 
> > > > 
> > > > 不是一个人，我也是安装的时候，一直在这里报错
> > > 
> > > 
> > > 开机自启动不成功 ？ 尝试下安装所有协议
> > 
> > 
> > 好的，我安装时输入的2，开始输入1，错误报得更早
> 
> 说一下你的系统版本以及vps厂商是哪一家 刚才试了下个性化安装 然后xray->VLESS WS GCP安装成功，我是用的Debian10

可能是oracle的哪里配置有问题，我自己买的个，用您的一键安装都成功了的

**Comment by mack-a** [comment]
> ========================个性化安装============================
> VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
> 0.VLESS+TLS/XTLS+TCP
> 1.VLESS+TLS+WS[CDN]
> 2.VMess+TLS+TCP
> 3.VMess+TLS+WS[CDN]
> 4.Trojan、Trojan+WS[CDN]
> 请选择[多选]，[例如:123]:0
> Xray的0-4我都试了，都是卡在这里。v2ray 也是在这里卡住了，我是在oracle cloud的 系统是ubuntu 20

自己dd个系统 用Debian10试试

**Comment by cqxx** [comment]
> > ========================个性化安装============================
> > VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
> > 0.VLESS+TLS/XTLS+TCP
> > 1.VLESS+TLS+WS[CDN]
> > 2.VMess+TLS+TCP
> > 3.VMess+TLS+WS[CDN]
> > 4.Trojan、Trojan+WS[CDN]
> > 请选择[多选]，[例如:123]:0
> > Xray的0-4我都试了，都是卡在这里。v2ray 也是在这里卡住了，我是在oracle cloud的 系统是ubuntu 20
> 
> 自己dd个系统 用Debian10试试

CentOS这个也是卡这里了，oracle没提供Debian。。

**Comment by mack-a** [comment]
> > > ========================个性化安装============================
> > > VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
> > > 0.VLESS+TLS/XTLS+TCP
> > > 1.VLESS+TLS+WS[CDN]
> > > 2.VMess+TLS+TCP
> > > 3.VMess+TLS+WS[CDN]
> > > 4.Trojan、Trojan+WS[CDN]
> > > 请选择[多选]，[例如:123]:0
> > > Xray的0-4我都试了，都是卡在这里。v2ray 也是在这里卡住了，我是在oracle cloud的 系统是ubuntu 20
> > 
> > 
> > 自己dd个系统 用Debian10试试
> 
> CentOS这个也是卡这里了，oracle没提供Debian。。

手动DD系统

**Comment by cqxx** [comment]
> > > > ========================个性化安装============================
> > > > VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
> > > > 0.VLESS+TLS/XTLS+TCP
> > > > 1.VLESS+TLS+WS[CDN]
> > > > 2.VMess+TLS+TCP
> > > > 3.VMess+TLS+WS[CDN]
> > > > 4.Trojan、Trojan+WS[CDN]
> > > > 请选择[多选]，[例如:123]:0
> > > > Xray的0-4我都试了，都是卡在这里。v2ray 也是在这里卡住了，我是在oracle cloud的 系统是ubuntu 20
> > > 
> > > 
> > > 自己dd个系统 用Debian10试试
> > 
> > 
> > CentOS这个也是卡这里了，oracle没提供Debian。。
> 
> 手动DD系统

换了下Ubuntu-20.04-Minimal-2021.02.16-0，这个安装成功了

**Comment by jiahanbryant** [comment]
> /etc/v2ray-agent/xray/xray run -confdir /etc/v2ray-agent/xray/conf 执行这个 然后把日志发一下

```
root@london:~# /etc/v2ray-agent/xray/xray run -confdir /etc/v2ray-agent/xray/conf
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
A unified platform for anti-censorship.
2021/03/21 15:44:38 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/03/21 15:44:38 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/03/21 15:44:38 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2021/03/21 15:44:38 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/03/21 15:44:38 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 443 > transport/internet: failed to listen on address: 0.0.0.0:443 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:443 > listen tcp 0.0.0.0:443: bind: address already in use
```
hmmm，看起来短款有被占用。。
