### ISSUE TITLE
无法更新证书

### ISSUE THREAD

**Issue by khalitt** [mack-a/v2ray-agent#122]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
无法更新证书，导致无法使用。
使用trojan 始终提示 ssl handshake failed with xxxx(域名): certificate verify failed
伪装站也无法访问

```
# 
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

- 

![Snipaste_2021-03-25_14-48-21](https://user-images.githubusercontent.com/20548808/112458222-8b34bf00-8d97-11eb-9dc4-d9832ffad05b.png)

![Snipaste_2021-03-25_14-48-42](https://user-images.githubusercontent.com/20548808/112458343-a7386080-8d97-11eb-9a61-0f7c2472e2cb.png)

![Snipaste_2021-03-25_18-27-30](https://user-images.githubusercontent.com/20548808/112458481-cdf69700-8d97-11eb-9fe0-1ca2bff2ed0d.png)

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

Debian 10

- 否

**6.脚本版本**
2.4.7
- 

**7.安装类型**

- 个性化安装/全部安装
全部安装

**8.安装的核心版本**

- Xray-core【1.4.0】

**9.出现问题的协议类型**

- Trojan VLESS

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by mack-a** [comment]
重新安装
