### ISSUE TITLE
望增加对gRPC传输方式的支持

### ISSUE THREAD

**Issue by yubo780429** [mack-a/v2ray-agent#124]
XRAY 1.4.0版本添加了对gRPC的支持，希望能够跟进。

**Comment by mack-a** [comment]
如果以后小火箭支持就会加这个功能。

**Comment by mack-a** [comment]
据我所知小火煎不会支持gRPC，所以如果没有iOS端支持的话，以后此功能应该不会集成到脚本里面。想用此协议的需要手动搭建。
