### ISSUE TITLE
 TLS安装失败，请检查acme日志

### ISSUE THREAD

**Issue by zing555** [mack-a/v2ray-agent#127]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```TLS安装失败，请检查acme日志
# 
```

**2.是否直接安装失败**

- 是

**3.是否重新build系统后尝试**

- 是

**4.直接安装失败的错误内容或者截图**
![屏幕截图 2021-04-01 215356](https://user-images.githubusercontent.com/71015856/113305279-70cd8900-9335-11eb-83bb-6cdb8c3b1ff4.png)

-TLS安装失败，请检查acme日志

**5.系统版本【例：Centos8】** centos7
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 否

**6.脚本版本**

- Stable-v2.2.24

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 4.Trojan、Trojan+WS[CDN] 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by mack-a** [comment]
建议使用debian系统
