### ISSUE TITLE
服务端v2ray的配置文件在哪个路径下？不在/etc/v2ray下的json呢？

### ISSUE THREAD

**Issue by coyhom** [mack-a/v2ray-agent#128]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
脚本安装倒是安成功了，客户端死活翻不过去。。。
看网上说是那个alertId为0的问题。。
但是怎么死活找不到/v2ray/config.json...默认不是放在/etc/下面的吗。。
怎么跟别的脚本安装位置不同？？？

```
# 
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

centos7

**6.脚本版本**

- Stable-v2.1.27

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- v2ray【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 否

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
同级conf目录
