### ISSUE TITLE
纯净debian8 64下安装失败

### ISSUE THREAD

**Issue by ywyha** [mack-a/v2ray-agent#129]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 系统是DD萌咖的debian8 64纯净版本，然后安装xray内核脚本提示失败，大佬能不能修复一下自动化完成 ---> 配置Nginx 
touch: cannot touch ‘/etc/nginx/conf.d/alone.conf’: No such file or directory
/root/install.sh: line 519: /etc/nginx/conf.d/alone.conf: No such file or directory
/root/install.sh: line 735: nginx: command not found
 ---> Nginx启动失败，请检查日志 

```

**2.是否直接安装失败**

- 是

**3.是否重新build系统后尝试**

- 是

**4.直接安装失败的错误内容或者截图**

- ---> 配置Nginx 
touch: cannot touch ‘/etc/nginx/conf.d/alone.conf’: No such file or directory
/root/install.sh: line 519: /etc/nginx/conf.d/alone.conf: No such file or directory
/root/install.sh: line 735: nginx: command not found
 ---> Nginx启动失败，请检查日志 

**5.系统版本【debian9 64】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 是

**6.脚本版本**

- 最新版

**7.安装类型**

- 全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
用Debian10试试

**Comment by ywyha** [comment]
> 用Debian10试试，不建议使用低版本的系统。

大佬，其实主要是我也想要debian9 和10，主要是硬盘空间不充裕~~~……

**Comment by mack-a** [comment]
试试换ubuntu或者尝试手动安装nginx，上面应该是nginx安装失败或者有自编译的nginx版本，如果有用别的脚本搭建，最好是dd下

**Comment by ywyha** [comment]
> 试试换ubuntu或者尝试手动安装nginx，上面应该是nginx安装失败或者有自编译的nginx版本，如果有用别的脚本搭建，最好是dd下

大佬，主要是一台机器的硬盘比较小，空间不充裕才想使用debian8的，安装环境是重新使用萌咖的DD脚本安装的纯净debian8的环境下安装的，没有安装过其他东西。debian9和ubuntu环境下安装倒是正常，就是占用硬盘空间大了些。如果debian8能一键正常安装脚本就好了。

**Comment by mack-a** [comment]
> > 试试换ubuntu或者尝试手动安装nginx，上面应该是nginx安装失败或者有自编译的nginx版本，如果有用别的脚本搭建，最好是dd下
> 
> 大佬，主要是一台机器的硬盘比较小，空间不充裕才想使用debian8的，安装环境是重新使用萌咖的DD脚本安装的纯净debian8的环境下安装的，没有安装过其他东西。debian9和ubuntu环境下安装倒是正常，就是占用硬盘空间大了些。如果debian8能一键正常安装脚本就好了。

https://github.com/mack-a/v2ray-agent/blob/master/documents/how_to_use.md#4debian8%E5%90%AF%E5%8A%A8nginx%E5%A4%B1%E8%B4%A5 试试这个解决方案

**Comment by mack-a** [comment]
可能是nginx版本太低了

**Comment by ywyha** [comment]
> 可能是nginx版本太低了

感谢大佬，安装成功了，谢谢提供这么好用的脚本，赞~~谢谢
