### ISSUE TITLE
IOS使用小飞机无法解析二维码 Trojan-Go(WS+TLS) Shadowrocket 

### ISSUE THREAD

**Issue by adeng-wc** [mack-a/v2ray-agent#132]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
安装完成后，ios 小飞机（小飞机版本是 2.1.81）无法解析二维码中的内容。 mac 端使用 Qvray 可以正常使用。
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 否
使用 Debian GNU/Linux 10 系统
**6.脚本版本**
脚本版本 v2.4.10 
- 

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】
1.4.2 

**9.出现问题的协议类型**
 Trojan WS TLS 
- 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by mack-a** [comment]
> > 请仔细填写每一项，并回复自己详细的错误信息
> 
> * 不符合的issue会被直接关闭
> 
> **1.描述出现的问题**
> 
> ```
> 安装完成后，ios 小飞机（小飞机版本是 2.1.81）无法解析二维码中的内容。 mac 端使用 Qvray 可以正常使用。
> ```
> 
> **2.是否直接安装失败**
> 
> * 否
> 
> **3.是否重新build系统后尝试**
> 
> * 否
> 
> **4.直接安装失败的错误内容或者截图**
> 
> 
> **5.系统版本【例：Centos8】**
> 
> > 最新版本脚本不支持Centos6
> > 是否更换Debian系统后再次安装
> 
> * 否
>   使用 Debian GNU/Linux 10 系统
>   **6.脚本版本**
>   脚本版本 v2.4.10
> 
> **7.安装类型**
> 
> * 个性化安装/全部安装
> 
> **8.安装的核心版本**
> 
> * Xray-core【version】
>   1.4.2
> 
> ## **9.出现问题的协议类型**
> Trojan WS TLS
> **10.尝试重装后是否100%复现**
> 
> * 是
> 
> **11.是否仔细检查客户端与服务端的配置是否相同**
> 
> * 否

我刚用2.1.82试了下 是可以连接的

**Comment by adeng-wc** [comment]
> > > 请仔细填写每一项，并回复自己详细的错误信息
> > 
> > 
> > 
> > * 不符合的issue会被直接关闭
> > 
> > **1.描述出现的问题**
> > ```
> > 安装完成后，ios 小飞机（小飞机版本是 2.1.81）无法解析二维码中的内容。 mac 端使用 Qvray 可以正常使用。
> > ```
> > 
> > 
> > **2.是否直接安装失败**
> > 
> > * 否
> > 
> > **3.是否重新build系统后尝试**
> > 
> > * 否
> > 
> > **4.直接安装失败的错误内容或者截图**
> > **5.系统版本【例：Centos8】**
> > > 最新版本脚本不支持Centos6
> > > 是否更换Debian系统后再次安装
> > 
> > 
> > 
> > * 否
> >   使用 Debian GNU/Linux 10 系统
> >   **6.脚本版本**
> >   脚本版本 v2.4.10
> > 
> > **7.安装类型**
> > 
> > * 个性化安装/全部安装
> > 
> > **8.安装的核心版本**
> > 
> > * Xray-core【version】
> >   1.4.2
> > 
> > ## **9.出现问题的协议类型**
> > Trojan WS TLS
> > **10.尝试重装后是否100%复现**
> > 
> > * 是
> > 
> > **11.是否仔细检查客户端与服务端的配置是否相同**
> > 
> > * 否
> 
> 我刚用2.1.82试了下 是可以连接的

APPstore 上最近的野菜 2.1.81 ，哪里来的 2.1.82 ？

**Comment by mack-a** [comment]
> > > > 请仔细填写每一项，并回复自己详细的错误信息
> > > 
> > > 
> > > 
> > > * 不符合的issue会被直接关闭
> > > 
> > > **1.描述出现的问题**
> > > ```
> > > 安装完成后，ios 小飞机（小飞机版本是 2.1.81）无法解析二维码中的内容。 mac 端使用 Qvray 可以正常使用。
> > > ```
> > > 
> > > 
> > > **2.是否直接安装失败**
> > > 
> > > * 否
> > > 
> > > **3.是否重新build系统后尝试**
> > > 
> > > * 否
> > > 
> > > **4.直接安装失败的错误内容或者截图**
> > > **5.系统版本【例：Centos8】**
> > > > 最新版本脚本不支持Centos6
> > > > 是否更换Debian系统后再次安装
> > > 
> > > 
> > > 
> > > * 否
> > >   使用 Debian GNU/Linux 10 系统
> > >   **6.脚本版本**
> > >   脚本版本 v2.4.10
> > > 
> > > **7.安装类型**
> > > 
> > > * 个性化安装/全部安装
> > > 
> > > **8.安装的核心版本**
> > > 
> > > * Xray-core【version】
> > >   1.4.2
> > > 
> > > ## **9.出现问题的协议类型**
> > > Trojan WS TLS
> > > **10.尝试重装后是否100%复现**
> > > 
> > > * 是
> > > 
> > > **11.是否仔细检查客户端与服务端的配置是否相同**
> > > 
> > > * 否
> > 
> > 
> > 我刚用2.1.82试了下 是可以连接的
> 
> APPstore 上最近的野菜 2.1.81 ，哪里来的 2.1.82 ？

内测版
