### ISSUE TITLE
io: 

### ISSUE THREAD

**Issue by MeLeo92** [mack-a/v2ray-agent#133]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
#  openwrt上和Mac上的clash x可以正常使用，手机端连接后报错io:read/write on closed pipe
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 是

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【Debian 10 x86_64  】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 是

**6.脚本版本**

- 2.4.11

**7.安装类型**

- 全部安装

**8.安装的核心版本**

- Xray-core【1.4.2】

**9.出现问题的协议类型**

- 所有协议

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by mack-a** [comment]
客户端问题需要去客户端反馈
