### ISSUE TITLE
EUSERV无法访问服务器

### ISSUE THREAD

**Issue by sunnynctu** [mack-a/v2ray-agent#134]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
检查IP是否设置为当前VPS 
 ---> 检查ipv4中 
jq: error (at <stdin>:0): Cannot iterate over null (null)
 ---> 检查ipv6中 

当前域名的IP为 [2a02:180:*:1::****]，是否正确[y/n]？y

 ---> IP确认完成 

检查Nginx是否正常访问 
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确---> 
# 
```

**2.是否直接安装失败**

- 是

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

-

**5.系统版本【例：Centos8】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- Ubuntu 20.04

**6.脚本版本**

- 2.4.11

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- 三种都尝试了，都不行

**9.出现问题的协议类型**

- 都有问题

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**Comment by sunnynctu** [comment]
一直卡在这里，那个域名我建立的网站都能正常打开，这里一直提示“无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确”

**Comment by mack-a** [comment]
贴一下dns解析的图

**Comment by sunnynctu** [comment]
> 贴一下dns解析的图

感谢大佬回复。
我重装了系统，这次没有安装宝塔，没有建立测速网站，就成功了
之前可能是443端口被其他应用占用了

**Comment by sunnynctu** [comment]
> 贴一下dns解析的图

另外想请教一下，我的域名是mov.**.**，所以想把伪装站重定向到某个视频站，这个应该怎么做呢？
我用托管dns的cloudflare设置了301重定向，打开还是那个dashboard网站
