### ISSUE TITLE
dns解锁分流问题

### ISSUE THREAD

**Issue by bcfead** [mack-a/v2ray-agent#135]
**详细描述建议的内容**
你好，是所有流量都转到解锁后的dns吗？

**Comment by mack-a** [comment]
"geosite:netflix",
					"geosite:bahamut",
					"geosite:hulu",
					"geosite:hbo",
					"geosite:disney",
					"geosite:bbc",
					"geosite:4chan",
					"geosite:fox",
					"geosite:abema",
					"geosite:dmm",
					"geosite:niconico",
					"geosite:pixiv",
					"geosite:bilibili",
					"geosite:viu"
