### ISSUE TITLE
是否可以增加youtube premium的流媒体解锁功能？

### ISSUE THREAD

**Issue by ddnsoft** [mack-a/v2ray-agent#139]
**详细描述建议的内容**
近期很多VPS被谷歌标记到国内，导致youtube premium无法正常使用，请问大佬能否增加youtube premium的流媒体解锁功能（类似Netflix的任意门）？谢谢

**Comment by mack-a** [comment]
> **详细描述建议的内容**
> 近期很多VPS被谷歌标记到国内，导致youtube premium无法正常使用，请问大佬能否增加youtube premium的流媒体解锁功能（类似Netflix的任意门）？谢谢

设置Netflix 任意门解锁 然后改一下09那个配置文件即可。这个功能应该不会添加

**Comment by mack-a** [comment]
> **详细描述建议的内容**
> 近期很多VPS被谷歌标记到国内，导致youtube premium无法正常使用，请问大佬能否增加youtube premium的流媒体解锁功能（类似Netflix的任意门）？谢谢

你可以选择ipv6分流
