### ISSUE TITLE
能否在脚本里添加一个面版安装项和v2-UI集成？

### ISSUE THREAD

**Issue by galaxyskyknight** [mack-a/v2ray-agent#140]
如题，v2-UI项目如下，因不清楚v2-UI的xray安装路径和本项目的路径及fallbacks等参数设置是否一致，但挺希望有个面板能看站点各项目参数的，同时又比较习惯了这个项目的使用，所以恳请作者看能否研究一下？
https://github.com/sprov065/v2-ui

**Comment by mack-a** [comment]
以后可能会加
