### ISSUE TITLE
config

### ISSUE THREAD

**Issue by eroxs** [mack-a/v2ray-agent#141]
how can i edit vmess config ? 
i need change UUID and Alterid after i run script

**Comment by eroxs** [comment]
!!!!!
what ?

**Comment by eroxs** [comment]
i edit vmess json in /etc/v2ray-agent/xray/conf but dont know How can I apply the changes?

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/blob/master/documents/how_to_use.md#3%E6%B7%BB%E5%8A%A0%E7%94%A8%E6%88%B7

**Comment by eroxs** [comment]
This is for camouflage the site
I mean Jason and alterid files and so on

**Comment by mack-a** [comment]
添加一个新用户，再把以前得删除掉就可

**Comment by eroxs** [comment]
This does not change the path and arterid ...

**Comment by eroxs** [comment]
want edit alterid to 64 and delete vws in patch for example

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/115146067-87b5f000-a044-11eb-9e21-4811732e981e.png)
![image](https://user-images.githubusercontent.com/57424792/115146085-98666600-a044-11eb-860c-f1823d146564.png)
改这两个地方

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/115146203-090d8280-a045-11eb-88d9-893e5e45c355.png)
![image](https://user-images.githubusercontent.com/57424792/115146238-23476080-a045-11eb-8c50-20aad46050ed.png)
改这三个地方，path要一样

**Comment by eroxs** [comment]
@mack-a  What command should be executed after the change?
