### ISSUE TITLE
添加域名总是失败是怎么回事

### ISSUE THREAD

**Issue by AvBaike** [mack-a/v2ray-agent#144]
**详细描述建议的内容**

进度  3/17 : 初始化Nginx申请证书配置

请输入要配置的域名 例：www.v2ray-agent.com --->
域名:new.马赛克.com

 ---> 配置Nginx

检查IP是否设置为当前VPS
 ---> 检查ipv4中

当前域名的IP为 [168.138.xxx.xxx]，是否正确[y/n]？y

 ---> IP确认完成

检查Nginx是否正常访问
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->

**Comment by mack-a** [comment]
README注意事项阅读一下

**Comment by AvBaike** [comment]
> README注意事项阅读一下

感谢老大的回复，我用的oracle VPS，看您的readme里说oracle有一个额外的防火墙需要手动关闭，我已经关闭了还是提示这个问题，我在搬瓦工 GCP上安装都没有问题。

**Comment by AvBaike** [comment]
问题找到了，防火墙没关干净。

感谢mack为大家做出的贡献，辛苦了。

**Comment by lomaidve** [comment]
> 问题找到了，防火墙没关干净。
> 
> 感谢mack为大家做出的贡献，辛苦了。

我也遇到同样的问题，能具体说说怎么关么？ 
有4个防火墙的入站规则，分别是 2个ICMP 一个TCP 和一个所有协议。请问如何关闭这些协议。

**Comment by blueveryday** [comment]
> 
> 
> 问题找到了，防火墙没关干净。
> 
> 感谢mack为大家做出的贡献，辛苦了。

兄弟，怎么关闭，能不能说说。

**Comment by bbcvn** [comment]
你好？mack-a
我问一下
进度 3/17 : 初始化Nginx申请证书配置

请输入要配置的域名 例：www.v2ray-agent.com --->
域名:new.马赛克.com

---> 配置Nginx

检查IP是否设置为当前VPS
---> 检查ipv4中

当前域名的IP为 [168.138.xxx.xxx]，是否正确[y/n]？y

---> IP确认完成

检查Nginx是否正常访问
---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->
这个问题怎么解决，我已经全部关闭了。还是不行。能详细的教一下吗?第一次接触这个，谢谢

**Comment by mack-a** [comment]
> 你好？mack-a
> 我问一下
> 进度 3/17 : 初始化Nginx申请证书配置
> 
> 请输入要配置的域名 例：www.v2ray-agent.com --->
> 域名:new.马赛克.com
> 
> ---> 配置Nginx
> 
> 检查IP是否设置为当前VPS
> ---> 检查ipv4中
> 
> 当前域名的IP为 [168.138.xxx.xxx]，是否正确[y/n]？y
> 
> ---> IP确认完成
> 
> 检查Nginx是否正常访问
> ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->
> 这个问题怎么解决，我已经全部关闭了。还是不行。能详细的教一下吗?第一次接触这个，谢谢

Oracle吗 如果是Oracle记得自己开防火墙（额外的防火墙）如果不是Oracle建议直接DD debian10 后重新尝试
