### ISSUE TITLE
为什么vless+tls+ws和vless+tls+grpc只能存在一个呢

### ISSUE THREAD

**Issue by lfxx** [mack-a/v2ray-agent#146]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 安装vless+tls+grpc后，vless+tls+ws会消失
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

- 无

**5.系统版本【例：Centos8】**
- ubuntu20.04

**6.脚本版本**

- 2.4.17

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【1.4.2】

**9.出现问题的协议类型**

- vless+tls+grpc

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by mack-a** [comment]
有空看一下

**Comment by mack-a** [comment]
> > 请仔细填写每一项，并回复自己详细的错误信息
> 
> * 不符合的issue会被直接关闭
> 
> **1.描述出现的问题**
> 
> ```
> # 安装vless+tls+grpc后，vless+tls+ws会消失
> ```
> 
> **2.是否直接安装失败**
> 
> * 否
> 
> **3.是否重新build系统后尝试**
> 
> * 否
> 
> **4.直接安装失败的错误内容或者截图**
> 
> * 无
> 
> **5.系统版本【例：Centos8】**
> 
> * ubuntu20.04
> 
> **6.脚本版本**
> 
> * 2.4.17
> 
> **7.安装类型**
> 
> * 个性化安装
> 
> **8.安装的核心版本**
> 
> * Xray-core【1.4.2】
> 
> **9.出现问题的协议类型**
> 
> * vless+tls+grpc
> 
> **10.尝试重装后是否100%复现**
> 
> * 是
> 
> **11.是否仔细检查客户端与服务端的配置是否相同**
> 
> * 是

# 安装vless+tls+grpc后，vless+tls+ws会消失
这个有具体的复现步骤没

**Comment by lfxx** [comment]
可以先装ws，然后再安装grpc，然后使用查看账号功能，这时候就只会有grpc，ws就没了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mack-a ***@***.***&gt;
发送时间: 2021年5月1日 16:21
收件人: mack-a/v2ray-agent ***@***.***&gt;
抄送: 高峰 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[mack-a/v2ray-agent] 为什么vless+tls+ws和vless+tls+grpc只能存在一个呢 (#146)





   
请仔细填写每一项，并回复自己详细的错误信息
   
不符合的issue会被直接关闭 
 
1.描述出现的问题
 # 安装vless+tls+grpc后，vless+tls+ws会消失  
2.是否直接安装失败
  
否 
 
3.是否重新build系统后尝试
  
否 
 
4.直接安装失败的错误内容或者截图
  
无 
 
5.系统版本【例：Centos8】
  
ubuntu20.04 
 
6.脚本版本
  
2.4.17 
 
7.安装类型
  
个性化安装 
 
8.安装的核心版本
  
Xray-core【1.4.2】 
 
9.出现问题的协议类型
  
vless+tls+grpc 
 
10.尝试重装后是否100%复现
  
是 
 
11.是否仔细检查客户端与服务端的配置是否相同
  
是 
  
安装vless+tls+grpc后，vless+tls+ws会消失
 
这个有具体的复现步骤没

**Comment by mack-a** [comment]
> 可以先装ws，然后再安装grpc，然后使用查看账号功能，这时候就只会有grpc，ws就没了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: mack-a ***@***.***&gt; 发送时间: 2021年5月1日 16:21 收件人: mack-a/v2ray-agent ***@***.***&gt; 抄送: 高峰 ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[mack-a/v2ray-agent] 为什么vless+tls+ws和vless+tls+grpc只能存在一个呢 (#146) 请仔细填写每一项，并回复自己详细的错误信息 不符合的issue会被直接关闭 1.描述出现的问题 # 安装vless+tls+grpc后，vless+tls+ws会消失 2.是否直接安装失败 否 3.是否重新build系统后尝试 否 4.直接安装失败的错误内容或者截图 无 5.系统版本【例：Centos8】 ubuntu20.04 6.脚本版本 2.4.17 7.安装类型 个性化安装 8.安装的核心版本 Xray-core【1.4.2】 9.出现问题的协议类型 vless+tls+grpc 10.尝试重装后是否100%复现 是 11.是否仔细检查客户端与服务端的配置是否相同 是 安装vless+tls+grpc后，vless+tls+ws会消失 这个有具体的复现步骤没 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

任意组合安装的时候安装两个？还是一个个安装

**Comment by mack-a** [comment]
我这暂未复现
