### ISSUE TITLE
v2ray-core版本更新太快

### ISSUE THREAD

**Issue by starcrafti** [mack-a/v2ray-agent#15]
xtls要求服务端和客户端的版本一致，但是服务端的版本更新的太快了，现在已经是4.31.0，而能v2rayN和路由器上的依然是4.30，所以就上不了。

**Comment by mack-a** [comment]
> xtls要求服务端和客户端的版本一致，但是服务端的版本更新的太快了，现在已经是4.31.0，而能v2rayN和路由器上的依然是4.30，所以就上不了。

这两天会出一个回退版本的功能，最迟后天，最快明天。也可以手动替换，文件在/etc/v2ray-agent/v2ray下面，替换掉v2ray即可。

**Comment by rprx** [comment]
这两个版本的 XTLS 可以互相连接，origin 和 direct 不能互相连接

**Comment by mack-a** [comment]
> xtls要求服务端和客户端的版本一致，但是服务端的版本更新的太快了，现在已经是4.31.0，而能v2rayN和路由器上的依然是4.30，所以就上不了。

https://github.com/mack-a/v2ray-agent/releases/tag/v2.0.13 已添加版本回退

**Comment by starcrafti** [comment]
> > xtls要求服务端和客户端的版本一致，但是服务端的版本更新的太快了，现在已经是4.31.0，而能v2rayN和路由器上的依然是4.30，所以就上不了。
> 
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.0.13 已添加版本回退

谢谢！
