### ISSUE TITLE
grpc+tls+cdn不能上网

### ISSUE THREAD

**Issue by lfxx** [mack-a/v2ray-agent#150]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```按照脚本配置好后，使用v2rayN配置好账号信息后无法上网，使用ws方法却可以正常上
# 
```

**2.是否直接安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.直接安装失败的错误内容或者截图**

```
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > transport/internet/grpc/encoding: failed to fetch hunk from gRPC tunnel > rpc error: code = PermissionDenied desc = Forbidden: HTTP status code 403; transport: missing content-type field
```

**5.系统版本【ubuntu20.04】**
> 最新版本脚本不支持Centos6
> 是否更换Debian系统后再次安装

- 否

**6.脚本版本**

- 2.4.23

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【1.4.2】

**9.出现问题的协议类型**

- grpc+tls+cdn

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**Comment by lfxx** [comment]
貌似是因为挂了cf的原因

**Comment by mack-a** [comment]
试试直连

**Comment by lfxx** [comment]
> 试试直连

直连可以的，ws和xtls方式都可以上网，就是grpc不行

**Comment by mack-a** [comment]
> > 试试直连
> 
> 直连可以的，ws和xtls方式都可以上网，就是grpc不行

直连gRPC也不行吗

**Comment by mack-a** [comment]
看看服务端的error日志

**Comment by lfxx** [comment]
> 看看服务端的error日志

服务端没有error日志，怎么直连grpc,只有一个grpc+tls+cdn的选项

**Comment by lfxx** [comment]
开启cf的grpc选项后，脚本卸载重装下可以了，谢谢大佬==

**Comment by mack-a** [comment]
> > 看看服务端的error日志
> 
> 服务端没有error日志，怎么直连grpc,只有一个grpc+tls+cdn的选项

自选ip就是CDN，按照脚本默认都是直连的

**Comment by lfxx** [comment]
> > > 看看服务端的error日志
> > 
> > 
> > 服务端没有error日志，怎么直连grpc,只有一个grpc+tls+cdn的选项
> 
> 自选ip是CDN，按照脚本默认都是直连的

大佬可以在readme中写一下需要在cloudflare的network选项中打开grpc才能正常使用grpc协议，避免后来人踩坑

**Comment by mack-a** [comment]
> > > > 看看服务端的error日志
> > > 
> > > 
> > > 服务端没有error日志，怎么直连grpc,只有一个grpc+tls+cdn的选项
> > 
> > 
> > 自选ip是CDN，按照脚本默认都是直连的
> 
> 大佬可以在readme中写一下需要在cloudflare的network选项中打开grpc才能正常使用grpc协议，避免后来人踩坑

谢谢提醒

**Comment by wsnsnsns** [comment]
> > > > 看看服务端的error日志
> > > 
> > > 
> > > 服务端没有error日志，怎么直连grpc,只有一个grpc+tls+cdn的选项
> > 
> > 
> > 自选ip是CDN，按照脚本默认都是直连的
> 
> 大佬可以在readme中写一下需要在cloudflare的network选项中打开grpc才能正常使用grpc协议，避免后来人踩坑

疑问:grpc必须是443端口么?还是别的自定义端口也可以呢?
