### ISSUE TITLE
acme.sh一直安装失败

### ISSUE THREAD

**Issue by jimi098** [mack-a/v2ray-agent#155]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

- acme.sh 安装失败

**2.是否安装失败**

- 是

**3.是否重新build系统后尝试**

- 使用的甲骨文云实例。。。小白不知道啥叫build系统，是重新删了实例再建吗

**4.安装失败的错误内容或者截图**

-
![image](https://user-images.githubusercontent.com/84094719/118018083-ea6f8280-b389-11eb-8a3a-8f46bb4ed799.png)

**5.系统版本【例：Debian10】**

- Ubuntu 20.04.2 

- 是否更换Debian10系统后再次安装

- 否

**6.脚本版本**

-v2.43.23

**7.安装类型**

- 脚本一键安装=。=

**8.安装的核心版本**

- Xray-core

**9.出现问题的协议类型**

-  没到协议那一步

**10.尝试重装后是否100%复现**

- 是，重装了很多次

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否，甲骨文云那个算客户端哪个算服务端=。=

**12.是否将客户端升级最新进行尝试**

- FinalShell 3.83算客户端吗，好像是最新版本

**Comment by mack-a** [comment]
甲骨文有自己得防火墙，需要自己关一下
