### ISSUE TITLE
ws路径中自动添加部分有特殊字符，openclash似乎不能准确识别和应用

### ISSUE THREAD

**Issue by laulay2033** [mack-a/v2ray-agent#156]
**详细描述建议的内容**
我指定了：/abcd321
脚本在VMess WS的路径变为 /abcd321vws?ed=2048，本人R2S openwrt 上的Openclash不能正确添加该节点。其他参数应该可以排除产生错误。SSR+可以正确添加该节点。

不用WS的，路径 /abcd321tcp，openclash和ssr+都可以正确添加。

**Comment by mack-a** [comment]
?ed=2048时xray的 ws 0-RTT，与v2ray的0-RTT不兼容，如果想用ws需手动删除?ed=2048
