### ISSUE TITLE
证书未能自动更新

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#157]
证书未能自动更新，昨晚就连接出问题了没怎么在意今天发现还是连接不了就上vps重装到证书那一步提示过期了。
vps系统是centos-7.8-BBR

![2021-05-16_094550](https://user-images.githubusercontent.com/9279217/118382879-2cb7ee80-b62c-11eb-84c8-2b05ebab2d0f.jpg)

**Comment by mack-a** [comment]
脚本版本呐 老版本的会有证书更新的问题

**Comment by smdx** [comment]
> 脚本版本呐 老版本的会有证书更新的问题

用的是v2.4.23版本啊

**Comment by mack-a** [comment]
> > 脚本版本呐 老版本的会有证书更新的问题
> 
> 用的是v2.4.23版本啊

不是按你当前使用的版本，是按照安装tls的版本

**Comment by smdx** [comment]
哦，这样啊。要怎么更新tls呢？

**Comment by mack-a** [comment]
> 哦，这样啊。要怎么更新tls呢？

crontab -l 然后再把打印的内容发一下

**Comment by smdx** [comment]
# crontab -l
30 1 * * * /bin/bash /etc/v2ray-agent/install.sh RenewTLS

**Comment by mack-a** [comment]
> # crontab -l
> 30 1 * * * /bin/bash /etc/v2ray-agent/install.sh RenewTLS

看着没问题呀 等我的证书到期我试试

**Comment by smdx** [comment]
好的，麻烦了。
