### ISSUE TITLE
如何在v2rayN Qv2ray及clash使用grpc

### ISSUE THREAD

**Issue by firstwaterer** [mack-a/v2ray-agent#158]
我有一个问题，用的是v2rayN,linux上用qv2ray 和 clash
但是我不会填写如下信息
![image](https://user-images.githubusercontent.com/75522951/119251852-69ab5480-bbdb-11eb-9179-63f48c372533.png)
可不可以在wiki添加

**Comment by mack-a** [comment]
win用qv2ray就好了呀

**Comment by firstwaterer** [comment]
好的，谢谢帮助

在 2021年5月23日星期日，mack-a ***@***.***> 写道：
