### ISSUE TITLE
脚本系统检测有问题

### ISSUE THREAD

**Issue by cncherisher** [mack-a/v2ray-agent#16]
VPS是openvz虚拟化，系统是debian8

脚本日志：
root@vm1601722352:~# ./install.sh
./install.sh: line 1707: rpm: command not found
（菜单省略）
请选择:1

进度  1/17 : 创建文件夹 

进度  2/17 : 安装工具 
 ---> 检查安装jq、nginx epel源、yum-utils 
./install.sh: line 76: rpm: command not found
 ---> 检查、安装更新【新机器会很慢，耐心等待】 
./install.sh: line 124: yum: command not found
 ---> 安装unzip 
./install.sh: line 139: yum: command not found
 ---> 安装socat 
./install.sh: line 145: yum: command not found
 ---> 安装crontabs 
./install.sh: line 161: yum: command not found
 ---> 安装binutils 
 ---> 安装nginx 
./install.sh: line 178: yum: command not found
 ---> 安装sudo 
./install.sh: line 184: yum: command not found
 ---> 安装acme.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  201k  100  201k    0     0  2463k      0 --:--:-- --:--:-- --:--:-- 2487k
[Sat Oct 10 00:21:37 EDT 2020] It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
[Sat Oct 10 00:21:37 EDT 2020] We need to set cron job to renew the certs automatically.
[Sat Oct 10 00:21:37 EDT 2020] Otherwise, your certs will not be able to be renewed automatically.
[Sat Oct 10 00:21:37 EDT 2020] Please add '--force' and try install again to go without crontab.
[Sat Oct 10 00:21:37 EDT 2020] ./acme.sh --install --force
[Sat Oct 10 00:21:37 EDT 2020] Pre-check failed, can not install.

进度  3/17 : 初始化Nginx申请证书配置 
请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:^C

root@vm1601722352:~# uname -romi
2.6.32-042stab145.3 x86_64 unknown GNU/Linux

root@vm1601722352:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

**Comment by mack-a** [comment]
下午我改一下

**Comment by mack-a** [comment]
> VPS是openvz虚拟化，系统是debian8
> 
> 脚本日志：
> root@vm1601722352:~# ./install.sh
> ./install.sh: line 1707: rpm: command not found
> （菜单省略）
> 请选择:1
> 
> 进度 1/17 : 创建文件夹
> 
> 进度 2/17 : 安装工具
> ---> 检查安装jq、nginx epel源、yum-utils
> ./install.sh: line 76: rpm: command not found
> ---> 检查、安装更新【新机器会很慢，耐心等待】
> ./install.sh: line 124: yum: command not found
> ---> 安装unzip
> ./install.sh: line 139: yum: command not found
> ---> 安装socat
> ./install.sh: line 145: yum: command not found
> ---> 安装crontabs
> ./install.sh: line 161: yum: command not found
> ---> 安装binutils
> ---> 安装nginx
> ./install.sh: line 178: yum: command not found
> ---> 安装sudo
> ./install.sh: line 184: yum: command not found
> ---> 安装acme.sh
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 201k 100 201k 0 0 2463k 0 --:--:-- --:--:-- --:--:-- 2487k
> [Sat Oct 10 00:21:37 EDT 2020] It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
> [Sat Oct 10 00:21:37 EDT 2020] We need to set cron job to renew the certs automatically.
> [Sat Oct 10 00:21:37 EDT 2020] Otherwise, your certs will not be able to be renewed automatically.
> [Sat Oct 10 00:21:37 EDT 2020] Please add '--force' and try install again to go without crontab.
> [Sat Oct 10 00:21:37 EDT 2020] ./acme.sh --install --force
> [Sat Oct 10 00:21:37 EDT 2020] Pre-check failed, can not install.
> 
> 进度 3/17 : 初始化Nginx申请证书配置
> 请输入要配置的域名 例：blog.v2ray-agent.com --->
> 域名:^C
> 
> root@vm1601722352:~# uname -romi
> 2.6.32-042stab145.3 x86_64 unknown GNU/Linux
> 
> root@vm1601722352:~# lsb_release -a
> No LSB modules are available.
> Distributor ID: Debian
> Description: Debian GNU/Linux 8.6 (jessie)
> Release: 8.6
> Codename: jessie

可否方便 用一下vps

**Comment by cncherisher** [comment]
已经加你telegram的群了

**Comment by cncherisher** [comment]
最新版问题已解决
