### ISSUE TITLE
请求出一个可以一键卸载的功能

### ISSUE THREAD

**Issue by 3858809** [mack-a/v2ray-agent#164]
**详细描述建议的内容**
有时候使用久了 会不能用了，不能用的问题可能会有很多，在排除了ip被墙的可能性，想要重装一下xary，对于小白很不友好，卸载不干净会导致，重装各种问题，要是脚本提供一键卸载干净，用户就可以自己，卸载自己重装，如果可以实现这种功能那真是太棒了

**Comment by mack-a** [comment]
脚本支持

**Comment by 3858809** [comment]
> 剧本支持
感谢大佬的回复
对不起 我仔细阅读了一下。你的说明文档里面确实提到了支持 
我对重新安装存在疑惑，脚本中的第一项功能和第二项功能 
1.安装
2.任意组合安装
以上两个如果安装过第二次在安装脚本会自动重装是吗？  
因为我在早些时候。使用第一项功能重置出现了些问题，也许是我自己的问题但是我想确认一下我的用法是否正确。

另外如果单纯卸载是不是使用
15.卸载脚本
