### ISSUE TITLE
允许IPv6分流规则与任意门解锁规则共存

### ISSUE THREAD

**Issue by MFYDev** [mack-a/v2ray-agent#165]
建议二者能够共存，这样能够适用于更多场景

**Comment by mack-a** [comment]
是的 目前只能二选一

**Comment by MFYDev** [comment]
不知道能否使这两个共存，因为有些vps既需要ipv6解锁YouTube premium，又需要任意门解锁其他区（非ipv6对应区）的Netflix

比如香港被google识别为中国的节点，就是需要warp解锁YouTube，然后还需要解锁Netflix新加坡区

建议使这两个能共存

**Comment by mack-a** [comment]
改一下title吧 这不是bug

**Comment by MFYDev** [comment]
好的，非常感谢，已更改

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.1 可以升级此版本后再次尝试
