### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by zhouguangyou1994** [mack-a/v2ray-agent#166]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
请选择：1
 ---> 当前Xray-core版本:1.4.2 
当前版本与最新版相同，是否重新安装？[y/n]:y
 ---> Xray关闭成功 
 ---> Xray-core版本:v1.4.2 
Xray-linux-64.zip                                            100%[===========================================================================================================================================>]   8.21M  40.4MB/s    in 0.2s    
 ---> Xray关闭成功 
 ---> Xray启动成功 
/usr/sbin/vasma: line 3792: unexpected EOF while looking for matching `"'
/usr/sbin/vasma: line 3843: syntax error: unexpected end of file

```

**2.是否安装失败**

- 否

**3.是否重新build系统后尝试**

- 否

**4.安装失败的错误内容或者截图**

-

**5.系统版本【例：Debian10】**

- 最新版本脚本不支持Centos6

- 是否更换Debian10系统后再次安装

```
否
```

**6.脚本版本**

-

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 否

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**12.是否将客户端升级最新进行尝试**

- 否

**Comment by mack-a** [comment]
这是已经装完了 直接再次运行 查看账号 应该可以用
