### ISSUE TITLE
请问一下v2ray中conf中的逻辑是什么样的?

### ISSUE THREAD

**Issue by TianqiSu** [mack-a/v2ray-agent#168]
你好, 目前我需要修改vmess下ws+tls的outbound, 并加上routing字段, 应该如何处理?

分开修改05_VMess_WS_inbounds.json和10_ipv4_outbounds.json, 还是直接在05_VMess_WS_inbounds.json中增加outbounds和routing?

我希望的是单独对vmess+ws+tls此协议进行修改, 保持其他协议不变.

**Comment by phlinhng** [comment]
+ 完整回答：
https://www.v2fly.org/config/multiple_config.html
+ 短回答：
分开修改05_VMess_WS_inbounds.json和10_ipv4_outbounds.json

**Comment by TianqiSu** [comment]
OK 那么再请问下 routing是在05还是10修改呢? 我需要配一个geoip走IPV6

**Comment by phlinhng** [comment]
> OK 那么再请问下 routing是在05还是10修改呢? 我需要配一个geoip走IPV6

改 10，注意顺序，越上面优先级越高。

**Comment by TianqiSu** [comment]
收到 非常感谢解答

**Comment by phlinhng** [comment]
> 收到 非常感谢解答

抱歉 typo 了， routing 要改 09 才对。
