### ISSUE TITLE
能不能出一个宝塔面板共存版？

### ISSUE THREAD

**Issue by lukemin** [mack-a/v2ray-agent#17]
能不能出一个宝塔面板共存版？服务器上已经安装了宝塔面板，并且有网站正在运行。

**Comment by mack-a** [comment]
> 能不能出一个宝塔面板共存版？服务器上已经安装了宝塔面板，并且有网站正在运行。

宝塔是用的什么做的反向代理，Nginx吗

**Comment by lukemin** [comment]
我现在用的233boy的脚本，v2ray的端口用的5001，vmess+tls协议，宝塔 Nginx 反代的，域名的ssl也是通过宝塔设置 ，cf 自选IP加速。我现在想试验一下Trojan go，但是能搜到的脚本都是要安装Nginx。

**Comment by mack-a** [comment]
> 我现在用的233boy的脚本，v2ray的端口用的5001，vmess+tls协议，宝塔 Nginx 反代的，域名的ssl也是通过宝塔设置 ，cf 自选IP加速。我现在想试验一下Trojan go，但是能搜到的脚本都是要安装Nginx。

这里估计得需要手动装一下trojan-go  然后给他不同的端口

**Comment by lukemin** [comment]
只要是不会安装设置，所以才找到你的脚本的

**Comment by mack-a** [comment]
> 只要是不会安装设置，所以才找到你的脚本的

先建议看一下文档，配置不复杂。按照目前脚本的架构是没有办法兼容你那个个性化需求。
https://p4gefau1t.github.io/trojan-go/basic/full-config/
