### ISSUE TITLE
疑似Bug反馈

### ISSUE THREAD

**Issue by leeskyler-top** [mack-a/v2ray-agent#170]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

-OracleCloud aarch64 机子 Oracle Linux 7.9（理论上属于Red Hat发行版本）
安装时出现Nginx无法访问
在运行Nginx出现98错误（端口已占用，在kill 占用80的进程nginx本身再service nginx restart仍然相同报错）
**2.是否安装失败**

- 是
**3.是否重新build系统后尝试**

- 是

**4.安装失败的错误内容或者截图**

-Nginx无法访问，请检查安全组，DNS解析

**5.系统版本【例：Debian10】**

- 最新版本脚本不支持Centos6

- 是否更换Debian10系统后再次安装

```
否
```
Oracle Linux 7.9 
OracleCloud ARM 无法安装其他版本的发行版Linux。
**6.脚本版本**

-Latest Version

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- V2Ray-Core

*9.出现问题的协议类型**

- 0

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**12.是否将客户端升级最新进行尝试**

- 否

**Comment by mack-a** [comment]
有相同错误的可以在此条下面留言，目前我测试得还没复现。可以私聊我你复现的机器。如果机器使用其他脚本安装过，可能会出现端口占用service 无法启动得情况。
