### ISSUE TITLE
TLS failed

### ISSUE THREAD

**Issue by sadistrz** [mack-a/v2ray-agent#173]
*******.net:Verify error:Fetching http://*******.net/.well-known/acme-challenge/Q6CNw0lHpOv-bxE6Lo7_G5Qitl5tZjVKc_7gmA0ybjY: Timeout during connect (likely firewall problem)
[Sat Jun  5 01:34:49 EDT 2021] Please add '--debug' or '--log' to check more details.
[Sat Jun  5 01:34:49 EDT 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/*******.net_ecc/fullchain.cer: No such file or directory
 ---> TLS安装失败，请检查acme日志 
[root@ggcus-39045-wdrtuwpf ~]# sudo systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Thanks for your help, my big god.

**Comment by mack-a** [comment]
建议直接dd系统后重新尝试
