### ISSUE TITLE
希望能够兼容一下宝塔

### ISSUE THREAD

**Issue by sunnynctu** [mack-a/v2ray-agent#174]
**详细描述建议的内容**
一台VPS只用来科学富强似乎有点浪费，还可以部署很多服务。但是对于依赖一键脚本的小白们来说，用默认的nginx自己写配置文件部署一个白板网站已经相当困难，更不要说设置伪静态、反代、重定向、申请SSL证书、自动备份、计划任务等进阶操作了，宝塔面板的图形操作界面大大简化了操作难度。
因此希望大佬可以考虑兼容一下宝塔，下面是宝塔的安装步骤、主要命令和配置文件目录
https://www.bt.cn/btcode.html

**Comment by sunnynctu** [comment]
宝塔的nginx安装目录、配置文件、网站配置文件、站点目录等均与默认的有所差异，但仅仅是目录的区别，本质并无不同。

**Comment by sunnynctu** [comment]
目前脚本和宝塔的的冲突在于，80/443端口已经被宝塔的nginx服务接管，脚本新建的nginx服务无法使用443端口。能不能检测是否已经存在nginx环境，如果存在直接调用，不在默认目录安装第二套nginx？

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/98
