### ISSUE TITLE
成功安装脚本后会把系统crontab内容覆盖

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#175]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# RT 所述，成功安装脚本后会把系统crontab内容覆盖，使得其他定时服务失效。
```

**2.是否安装失败**

- 否

**3.是否重新build系统后尝试**

- 是

**4.安装失败的错误内容或者截图**

-

**5.系统版本【例：Debian10】**

- 最新版本脚本不支持Centos6

- 是否更换Debian10系统后再次安装

```
是
```

**6.脚本版本**

-

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**12.是否将客户端升级最新进行尝试**

- 是

**Comment by mack-a** [comment]
脚本我记得做过兼容，你用的哪个版本的脚本

**Comment by AndersonGhost** [comment]
最新的版本啊

**Comment by ChellyL** [comment]
我也出现了这个问题，不过我是卸载重装后出现的，不清楚是卸载问题还是安装问题

**Comment by mack-a** [comment]
有空我测试一下，最近比较忙

**Comment by AndersonGhost** [comment]
经过测试，100%必现，每次安装完，需要手动把之前的crontab恢复一下

**Comment by mack-a** [comment]
> 经过测试，100%必现，每次安装完，需要手动把之前的crontab恢复一下

感谢测试 有空我改一下

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.4.40
