### ISSUE TITLE
搬瓦工debian10 出现 acme安装失败

### ISSUE THREAD

**Issue by Masterbaiter** [mack-a/v2ray-agent#176]
**1.描述出现的问题**

脚本安装时出现 
sh: 2: Syntax error: newline unexpected   acme安装失败

**2.是否安装失败**

- 是

**3.是否重新build系统后尝试**

- 是

**4.安装失败的错误内容或者截图**

功能 1/1 : 选择核心安装

==============================================================
1.Xray-core
2.v2ray-core
3.v2ray-core[XTLS]
==============================================================
请选择：1
安装工具

进度  2/17 : 安装工具
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】
 ---> 安装curl
 ---> 安装unzip
 ---> 安装socat
 ---> 安装jq
 ---> 安装binutils
 ---> 安装qrencode
 ---> 安装nginx
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
 ---> 安装semanage
 ---> 安装acme.sh
sh: 2: Syntax error: newline unexpected
  acme安装失败--->
错误排查：
  1.获取Github文件失败，请等待Gitub恢复后尝试，恢复进度可查看 [https://www.githubstatus.com/]
  2.acme.sh脚本出现bug，可查看[https://github.com/acmesh-official/acme.sh] issues

![Screenshot 2021-06-07 004929](https://user-images.githubusercontent.com/16754468/120933762-22ba7480-c72e-11eb-9d5c-785e8cb950f4.jpg)

**5.系统版本【例：Debian10】**

- Debian10

**6.脚本版本**

-最新版本 ，Stable-v2.2.24， Stable-v2.1.27 都有同样问题

**7.安装类型**

- 个性化安装/全部安装 都有同样问题

**8.安装的核心版本**

- Xray-core

**9.出现问题的协议类型**

- 还未到安装协议

**10.尝试重装后是否100%复现**

- 是

**Comment by mack-a** [comment]
现在还有这种问题吗

**Comment by Masterbaiter** [comment]
> 现在还有这种问题吗

还有

**Comment by mack-a** [comment]
现在还有问题吗

**Comment by lengge86** [comment]
搬瓦工Ubuntu也还有这个问题

**Comment by mack-a** [comment]
> 搬瓦工Ubuntu也还有这个问题

现在吗

**Comment by mack-a** [comment]
> 搬瓦工Ubuntu也还有这个问题

cat /etc/v2ray-agent/tls/acme.log 执行下这条语句

**Comment by Masterbaiter** [comment]
> > 搬瓦工Ubuntu也还有这个问题
> 
> cat /etc/v2ray-agent/tls/acme.log 执行下这条语句

我这边问题消失了，安装成功。
