### ISSUE TITLE
trojan协议无法使用

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#177]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
使用最新版（39）脚本更新/重装时，如果选择了gRPC协议，可以完成安装，但节点的trojan协议实际上无法使用
```

**2.是否安装失败**

- 否

**3.是否重新build系统后尝试**

- 是

**4.安装失败的错误内容或者截图**

- 安装成功，查看账号后将链接导入V2RayN测试时，如果测试真延迟，则trojan协议的会提示“基础连接已经关闭: 发送时发生错误。”（gPRC似乎也会出现该问题，反正Trojan一定会有该问题）

**5.系统版本【例：Debian10】**

- 最新版本脚本不支持Centos6

- 是否更换Debian10系统后再次安装

```
Centos7 。否。
但我测试了五台vps，尝试过卸载脚本重装及系统重装
```

**6.脚本版本**

-2.4.39

**7.安装类型**

- 个性化安装/全部安装
- 全部安装，任意模式安装均尝试过，
- 部分机器我已经只装了VLESS+TCP+xtls-rprx-direct和trojan协议，尝试任意组合安装gRPC后，显示成功但原有trojan会失效。删除脚本后尝试全部安装，或者删除脚本后尝试三者组合安装，依然显示trojan“基础连接已经关闭: 发送时发生错误。”

**8.安装的核心版本**

- Xray-core【version】
- 都是最新版

**9.出现问题的协议类型**

- trojan、gRPC

**10.尝试重装后是否100%复现**

- 是。测试重装很多次，最后的解决办法是，删除脚本，检测端口占用后，任意组合安装只安装Xray核心的VLESS+TCP+xtls-rprx-direct和trojan协议【40】，但我使用前几个脚本（好像是2.4.23）选择全部安装时，没有出现该问题，所有协议都可使用

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**12.是否将客户端升级最新进行尝试**

- 是，V2rayN也更新了，还尝试了clash

**Comment by mack-a** [comment]
有两种解决方案
1.使用qv2ray、小火箭作为客户端
2.使用不带gRPC的脚本安装
据我所知，现在v2rayN对于trojan和gRPC只能二选一。

**Comment by ChellyL** [comment]
我用2.4.23版本的时候，所有vps都使用了全部安装，当时的gPRC协议和Trojan协议似乎可以共用，升级脚本重新安装后则Trojan失效，不仅是v2rayN无法使用，clash也无法链接。感觉两者有点冲突……

**Comment by mack-a** [comment]
> 我用2.4.23版本的时候，所有vps都使用了全部安装，当时的gPRC协议和Trojan协议似乎可以共用，升级脚本重新安装后则Trojan失效，不仅是v2rayN无法使用，clash也无法链接。感觉两者有点冲突……

等v2rayN适配 或者 更换客户端 qv2ray

**Comment by ChellyL** [comment]
嗯，其实我日常是主用clash的，v2rayN拿来管理链接，主要是反馈一下同时安装gPRC和trojan似乎会导致trojan失效

**Comment by mack-a** [comment]
> 嗯，其实我日常是主用clash的，v2rayN拿来管理链接，主要是反馈一下同时安装gPRC和trojan似乎会导致trojan失效

目前大概只能等v2rayN或者xray更新才能解决这个问题

**Comment by ChellyL** [comment]
我好像知道这个问题出现的原因了，大概和ipv6以及V2rayN的真延迟测试地址有关。
当时，我在重装之前，用其他的脚本给只有ipv4地址的小鸡套了warp的ipv6，设置给google网站ipv6分流，大概我自己还乱设置了一些其他的玩意儿（比如开启ipv6之类的），trojan似乎不支持warp套的ipv6地址（至少clash上用是如此），V2rayN测试真延迟时的测试地址为google.com，会被分流到ipv6访问，所以测试时就会显示trojan协议的连接出错。
今天也出现了类似的情况，vless协议测真延迟失败显示基础访问关闭，trojan可以正常使用，但可以访问除我设置分流之外的其他被屏蔽的网站（eg.推特），最后发现与warp套用的ipv6地址以及脚本对ipv6的设置有关。
感觉和ipv6相关的设置还是用在自带ipv6的小鸡上不容易出错

**Comment by mack-a** [comment]
> 我好像知道这个问题出现的原因了，大概和ipv6以及V2rayN的真延迟测试地址有关。
> 
> 当时，我在重装之前，用其他的脚本给只有ipv4地址的小鸡套了warp的ipv6，设置给google网站ipv6分流，大概我自己还乱设置了一些其他的玩意儿（比如开启ipv6之类的），trojan似乎不支持warp套的ipv6地址（至少clash上用是如此），V2rayN测试真延迟时的测试地址为google.com，会被分流到ipv6访问，所以测试时就会显示trojan协议的连接出错。
> 
> 今天也出现了类似的情况，vless协议测真延迟失败显示基础访问关闭，trojan可以正常使用，但可以访问除我设置分流之外的其他被屏蔽的网站（eg.推特），最后发现与warp套用的ipv6地址以及脚本对ipv6的设置有关。
> 
> 感觉和ipv6相关的设置还是用在自带ipv6的小鸡上不容易出错

把服务端VLESS的h1.1 h2换一下顺序，trojan就可正常使用

**Comment by ChellyL** [comment]
嗯嗯，几天前的问题因为我还不知道是因为ipv6的缘故，所以通过换系统和不安装gRPC协议解决了。
今天的问题，依然是ipv6分流导致的问题：
1.我跑去warp脚本看了下issue，大概是因为那个脚本没有做开机自启，所以我重启机器后warp失效，
2.我套用warp后设置了google的ipv6分流，
3.正好v2rayN的真延迟使用了google.com做测试，
这一连串加起来导致我测试vless真延迟失效。但实际没有分流的网站依然可以正常访问，当时trojan协议我没有测试，估计如果测试了也会一样报连接错误。
因此我认为前几天的报错也单纯是因为ipv6重启失效导致的……
这也解决了我前几天虽然v2rayN真延迟测试报错但clash依旧正常使用的迷惑，clash不支持warp套用的ipv6，所以warp失效与否没有影响到clash的使用
不知道我表述清楚没有，我这边的问题和大佬的脚本没啥关系，纯粹是我自己设置出的错~非常感谢大佬的耐心解答~
