### ISSUE TITLE
能否添加一个指定落地机的选项，解锁Netflix功能的超集

### ISSUE THREAD

**Issue by la0wei** [mack-a/v2ray-agent#179]
流量全部由vpsA转发到vpsB，vpsB做为出口，而不仅仅是Netflix

**Comment by mack-a** [comment]
https://t.me/v2rayagentshare/396

**Comment by la0wei** [comment]
分享一个配置，下面的内容为 @mack-a 脚本安装完成后，我替换/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json后的完全内容，访问ip测试网站已经是ss服务器的。替换内容前请备份原文件。具体路径视自己安装组合。作用是将v2ray的出口流量转到ss服务器，从而使自己的出口ip为SS服务器。

并未测试email、ota、level参数是否必须项。

{
    "outbounds": [
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "email":"10000@qq.com",
                        "address": "6.7.8.9",
                        "port": 1234,
                        "method": "chacha20-ietf-poly1305",
                        "password": "45tiyfgoh458y",
                        "ota": false,
                        "level": 0
                    }
                            ]
                        }
        }
                 ]
}

**Comment by wooleo** [comment]
因为我圣荷西cn2 gia线路vps一用warp就断流，所以我的Netflix线路是从另一台vps跳转的，这个需求也可以用gia 拉绕程的新加坡vps

调试的时候记得命令行启动，可以方便定位配置的语法错误
配置修改如下：
 "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "tag": "BWG",
      "protocol": "vless",
      "settings": {
        "vnext": [{
          "address": "xx.xx.com",
          "port": 443,
          "users": [{
            "id": "xxxxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxx",
            "encryption": "none",
            "level": 0
          }]
        }]
      },
      "streamSettings": {
                "network": "tcp",
                "security": "tls"
                }
      }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "BWG",
        "domain": ["geosite:netflix"]
      }
    ]
  }

**Comment by mack-a** [comment]
该需求暂停
