### ISSUE TITLE
vps断开连接

### ISSUE THREAD

**Issue by shinzi0427** [mack-a/v2ray-agent#18]
使用这个脚本安装还没结束 vps就断开连接了 ，不知道是不是小鸡 硬件太差了

**Comment by mack-a** [comment]
> 使用这个脚本安装还没结束 vps就断开连接了 ，不知道是不是小鸡 硬件太差了

用的finalshell吗

**Comment by shinzi0427** [comment]
是finalshell，原来是这个软件的问题啊，我试试xshell，谢谢
