### ISSUE TITLE
ipv6分流设置后xray启动失败

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#180]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 设置ipv6分流后，按提示输入多个分流网址后，提示xray启动失败。但只输入google则可成功启动
```

**2.是否安装失败**

-  是

**3.是否重新build系统后尝试**

- 否

**4.安装失败的错误内容或者截图**

- 
![Snipaste_2021-06-09_20-23-16](https://user-images.githubusercontent.com/38887991/121354383-6a751200-c961-11eb-8921-fb52d361fbd4.png)

**5.系统版本【例：Debian10】**

- 最新版本脚本不支持Centos6

- 是否更换Debian10系统后再次安装

```
Centos7
```

**6.脚本版本**

- 2.4.39

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【最新】

**9.出现问题的协议类型**

- ipv6分流

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**12.是否将客户端升级最新进行尝试**

- 是

**Comment by mack-a** [comment]
有空我测试一下

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/121452651-61705900-c9d2-11eb-9353-6182924bee20.png)

Debian10没复现

**Comment by mack-a** [comment]
我这目前没复现，如再次复现再打开个此issue

**Comment by ChellyL** [comment]
感谢回复，今天换了个系统，确实没问题了，看来还是Debian更合适点
