### ISSUE TITLE
gRPC使用问题

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#181]
**1.描述出现的问题**

如何正确使用gRPC？cloudflare已允许grpc，当云朵颜色为橙色，在安装脚本解析域名时，会出现域名和自己不匹配的情形，继续完成安装后，代理无法访问，所以正确的使用方式什么？

**2.是否安装失败**

- 否

**3.是否重新build系统后尝试**

- 是

**4.安装失败的错误内容或者截图**

-能安装成功，代理失效

**5.系统版本【例：Debian10】**

Debian10

**6.脚本版本**

-2.4.42

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

- Xray-core【1.4.2】

**9.出现问题的协议类型**

- gRPC

**10.尝试重装后是否100%复现**

- 是

**11.是否仔细检查客户端与服务端的配置是否相同**

- 是

**12.是否将客户端升级最新进行尝试**

- 是

**Comment by mack-a** [comment]
address 中的域名改成自己的域名

**Comment by fredericky123** [comment]
> address 中的域名改成自己的域名 再试试

安装时是自定义域名

**Comment by mack-a** [comment]
> > address 中的域名改成自己的域名 再试试
> 
> 安装时是自定义域名，我没说说清楚，是自定义域名和解析出来的ip不对应

开了小云朵安装就显示的不一样

**Comment by fredericky123** [comment]
我刚关了云朵，进行配置，配置完再打开云朵，发现连不上服务器，类似的操作设置ws tls cdn就没问题

**Comment by mack-a** [comment]
> 我刚关了云朵，进行配置，配置完再打开云朵，发现连不上服务器，类似的操作设置ws tls cdn就没问题

因为你刚才开了小云朵，所以除了ws gRPC都无法使用，关闭小云朵后都可以使用。
因为刚关了小云朵需要等dns生效

**Comment by fredericky123** [comment]
> > 我刚关了云朵，进行配置，配置完再打开云朵，发现连不上服务器，类似的操作设置ws tls cdn就没问题
> 
> 因为你刚才开了小云朵，所以除了ws gRPC都无法使用，关闭小云朵后都可以使用。
> 因为刚关了小云朵需要等dns生效

刚不是一会儿，是很久之前了，抱歉。
我的操作流程是关了小云朵，同时配置ws和grpc，配置好后，再开启小云朵，想要加个cdn，此时ws可以访问，grpc连不上。
确认不是dns解析的原因。

**Comment by mack-a** [comment]
> > > 我刚关了云朵，进行配置，配置完再打开云朵，发现连不上服务器，类似的操作设置ws tls cdn就没问题
> > 
> > 
> > 因为你刚才开了小云朵，所以除了ws gRPC都无法使用，关闭小云朵后都可以使用。
> > 因为刚关了小云朵需要等dns生效
> 
> 刚不是一会儿，是很久之前了，抱歉。
> 我的操作流程是关了小云朵，同时配置ws和grpc，配置好后，再开启小云朵，想要加个cdn，此时ws可以访问，grpc连不上。
> 确认不是dns解析的原因。

gRPC使用小火煎或者qv2ray(action版本)

**Comment by fredericky123** [comment]
> > > > 我刚关了云朵，进行配置，配置完再打开云朵，发现连不上服务器，类似的操作设置ws tls cdn就没问题
> > > 
> > > 
> > > 因为你刚才开了小云朵，所以除了ws gRPC都无法使用，关闭小云朵后都可以使用。
> > > 因为刚关了小云朵需要等dns生效
> > 
> > 
> > 刚不是一会儿，是很久之前了，抱歉。
> > 我的操作流程是关了小云朵，同时配置ws和grpc，配置好后，再开启小云朵，想要加个cdn，此时ws可以访问，grpc连不上。
> > 确认不是dns解析的原因。
> 
> gRPC使用小火煎或者qv2ray(action版本)

用的是最新版action qv2ray

**Comment by mack-a** [comment]
我没遇到过你说的情况 ，我的qv2ray action目前好用

**Comment by mack-a** [comment]
小火煎 qv2ray我可，其余的客户端没用过，你可以打开服务端日志看一下

**Comment by mack-a** [comment]
https://www.jamesdailylife.com/xray-grpc

可以看看这个

**Comment by fredericky123** [comment]
> https://www.jamesdailylife.com/xray-grpc
> 
> 可以看看这个

太神奇了，根据这个教程的提示我都注意到了，没什么问题。
qv2ray的日志里也不报错，一片绿，可是就是连不上谷歌，太神奇了，切换成ws+cdn就没问题

**Comment by mack-a** [comment]
> > https://www.jamesdailylife.com/xray-grpc
> > 可以看看这个
> 
> 太神奇了，根据这个教程的提示我都注意到了，没什么问题。
> qv2ray的日志里也不报错，一片绿，可是就是连不上谷歌，太神奇了，切换成ws+cdn就没问题

这个时候就需要看看服务端日志

**Comment by fredericky123** [comment]
> > > https://www.jamesdailylife.com/xray-grpc
> > > 可以看看这个
> > 
> > 
> > 太神奇了，根据这个教程的提示我都注意到了，没什么问题。
> > qv2ray的日志里也不报错，一片绿，可是就是连不上谷歌，太神奇了，切换成ws+cdn就没问题
> 
> 这个时候就需要看看服务端日志

服务端日志我没导出来，😌
我先不用grpc了吧
请问 话说mux有最佳值吗，多少比较好
