### ISSUE TITLE
申请TLS证书 fail

### ISSUE THREAD

**Issue by happy201807** [mack-a/v2ray-agent#183]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
申请TLS证书 fail

```

**2.是否安装失败**

- 是

**3.是否重新build系统后尝试**

- 否 Oracle没这功能

**4.安装失败的错误内容或者截图**

-进度  3/17 : 申请TLS证书

 ---> 安装TLS证书
[Sun 13 Jun 2021 10:37:14 AM UTC] Please add '--debug' or '--log' to check more details.
[Sun 13 Jun 2021 10:37:14 AM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/domain.ml_ecc/domain.ml.key: No such file or directory
cat: /etc/v2ray-agent/tls/domain.ml.crt: No such file or directory
 ---> TLS安装失败，请检查acme日志
 

**5.系统版本【例：Debian10】**

- Ubuntu20

- 是否更换Debian10系统后再次安装

```
否
```

**6.脚本版本**

-Latest Version

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

- Xray-core【version】

**9.出现问题的协议类型**

- 5 vless+grpc

**10.尝试重装后是否100%复现**

- 否

**11.是否仔细检查客户端与服务端的配置是否相同**

- 否

**12.是否将客户端升级最新进行尝试**

- 否

**Comment by mack-a** [comment]
DD debain10重新安装

**Comment by mack-a** [comment]
可以使用 v2.4.43 再试试

**Comment by blueboyggh** [comment]
> 可以使用 v2.4.43 再试试

2.4.43依旧有这个问题，跟我用GCP有关系吗？我记得3个月之前我用GCP是可以成功的

**Comment by mack-a** [comment]
> > 可以使用 v2.4.43 再试试
> 
> 
> 
> 2.4.43依旧有这个问题，跟我用GCP有关系吗？我记得3个月之前我用GCP是可以成功的

卸载掉脚本或者重新弄个镜像 重新弄

**Comment by PanHsin** [comment]
关于证书的申请问题，或是官方脚本acme.sh的原因。

当前acme.sh 默认CA是ZeroSSL的。
之前的CA是letsencrypt。


当用 curl https://get.acme.sh | sh  申请时会有相关提示：

[Sun 13 Jun 2021 03:39:36 PM UTC] Using CA: https://acme.zerossl.com/v2/DV90
[Sun 13 Jun 2021 03:39:36 PM UTC] Standalone mode.
[Sun 13 Jun 2021 03:39:37 PM UTC] Create account key ok.
[Sun 13 Jun 2021 03:39:37 PM UTC] No EAB credentials found for ZeroSSL, let's get one
[Sun 13 Jun 2021 03:39:37 PM UTC] **acme.sh is using ZeroSSL as default CA now.**
[Sun 13 Jun 2021 03:39:37 PM UTC] Please update your account with an email address first.
[Sun 13 Jun 2021 03:39:37 PM UTC] acme.sh --register-account -m my@example.com
[Sun 13 Jun 2021 03:39:37 PM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA

用 ZeroSSL申请证书，失败了。

临时的解决方式是 把默认的CA 切换为 letsencrypt 

curl https://get.acme.sh | sh

   **~/.acme.sh/acme.sh  --set-default-ca  --server  letsencrypt**    ←添加这一句，把CA 切换为letsencrypt

**Comment by mack-a** [comment]
最新已经修了

**Comment by happy201807** [comment]
已解决。
