### ISSUE TITLE
脚本中的trojan协议 兼容性问题

### ISSUE THREAD

**Issue by PanHsin** [mack-a/v2ray-agent#184]
> 请仔细填写每一项，并回复自己详细的错误信息

脚本中trojan/  trojan-go协议来自trojan-go核心。

trojan-go核心兼容Trojan(TLS)  、Trojan-Go(WS+TLS)。

qv2ray 或 igniter-go,，使用了trojan-go核心，连接Trojan(TLS)/ Trojan-Go(WS+TLS)正常。

- 不符合的issue会被直接关闭
------------------------------------------------------------------------------------------------------
**1.描述出现的问题**

但，部分客户端连接**trojan协议**时 出现兼容性问题。

比如安卓的v2rayNG （v1.6.4，和版本无关吧 ）   / igniter 最新版 0.10.3-beta / sagernet 等

如windows的 v2rayN （4.14  关闭MUX）

当使用这些客户端 连接 脚本所给trojan链接（有手动修正，确保配置无误）时，但链接出错。

v2rayNG 和v2rayN  提示：

**malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"**

igniter / sagernet   日志不明显，但无法连接。

**8.安装的核心版本**

- Xray-core【version】
Xray-core  1.4.2
**9.出现问题的协议类型**

trojan tls

**11.是否仔细检查客户端与服务端的配置是否相同**

-是

**12.是否将客户端升级最新进行尝试**

- 否
---------------------------------------------------------------------------------------------------------------------------

问题的原因可能是   https://github.com/XTLS/Xray-core/issues/235

当前配置是：
当使用xray核心时，
脚本 的trojan/trojan-go配置是回落到trojan-go.
并不回落到xray实现的trojan。

xray /（原版trojan？）客户端 不兼容 trojan-go服务端 

**既可选了xray，可以考虑用 xray实现的trojan协议，以解决这个trojan链接在那些客户端不能用的问题，扩大兼容性**。

即配置 回落到xray实现的trojan。

至于trojan-go协议，可以单独使用trojan-go核心。

**Comment by mack-a** [comment]
如果只使用trojan或者不使用gRPC的话，可以直接使用无gRPC的stable_v2.4.16，目前gRPC和trojan只能二选一。
你说的这个问题j大概率是因为服务端alpn的问题，可以调整alpn h2和http1.1的顺序再测试

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/198 目前可以参考这个

**Comment by mack-a** [comment]
已修改 推荐 v2.5.10
