### ISSUE TITLE
TLS安装失败

### ISSUE THREAD

**Issue by seva324** [mack-a/v2ray-agent#185]
[Sun 13 Jun 2021 11:31:36 PM UTC] Please add '--debug' or '--log' to check more details.
[Sun 13 Jun 2021 11:31:36 PM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/worijbface.site_ecc/worijbface.site.key: No such file or directory
cat: /etc/v2ray-agent/tls/worijbface.site.crt: No such file or directory
 ---> TLS安装失败，请检查acme日志 
请问是什么原因呢

**Comment by mack-a** [comment]
卸载脚本后用最新的脚本安装

**Comment by seva324** [comment]
你好 我已经使用最新的脚本了和新部署的系统了，还是出现这个问题

**Comment by seva324** [comment]
> 卸载脚本后用最新的脚本安装

同样的脚本我在别的vps服务器上没有问题，是不是环境设置的问题？

**Comment by seva324** [comment]
换成了Debian10系统，重设了cloudfare， 没有以上问题了

**Comment by luoyouyu520** [comment]
> 依次了Debian10系统，重设了cloudfare， 没有以上问题了

兄弟，你是怎么解决的？
