### ISSUE TITLE
使用“14.查看日志”之后一旦关闭access日志，xray停止运行后，无法自动重启。

### ISSUE THREAD

**Issue by waitandsoon** [mack-a/v2ray-agent#186]
如题。
使用“14.查看日志”之后，一旦关闭access日志，xray-core停止运行后，无法自动重启。
需要手工重启。

**Comment by mack-a** [comment]
他没显示启动成功吗

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/122004847-80faed80-cde7-11eb-8e88-ecfb7cab5591.png) 我这没有复现
