### ISSUE TITLE
安装配置完成，能用但是报错

### ISSUE THREAD

**Issue by doegeenon** [mack-a/v2ray-agent#19]
不太清楚为什么一直报这个错误，但能通
使用的是xtls direct

[Warning] [2001959080] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF

v2rayN 3.26
v2ray-core 4.31.0

**Comment by doegeenon** [comment]
Warning后的数字还有其他的，但后面的内容都一样

**Comment by mack-a** [comment]
> 不太清楚为什么一直报这个错误，但能通
> 使用的是xtls direct
> 
> [Warning] [2001959080] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
> 
> v2rayN 3.26
> v2ray-core 4.31.0
https://github.com/v2ray/v2ray-core/issues/2665#issuecomment-669234017 看一下作者的回答
一般如果不影响使用，我一般都会忽略。

**Comment by doegeenon** [comment]
好的，感谢

**Comment by doegeenon** [comment]
哥，再次请教一下那个证书和密钥装哪去了，我想找那个证书路径和密钥路径，但我翻遍了VPS都没找到，也可能是我操作问题没找到，只能请教一下作者大神了🙏@mack-a @一下不知道关闭的您能不能看到，感谢

**Comment by mack-a** [comment]
> 哥，再次请教一下那个证书和密钥装哪去了，我想找那个证书路径和密钥路径，但我翻遍了VPS都没找到，也可能是我操作问题没找到，只能请教一下作者大神了🙏@mack-a @一下不知道关闭的您能不能看到，感谢

/etc/v2ray-agent/有一个叫tls的目录
