### ISSUE TITLE
可以正常的使用，但是网站本身无法查看，会报错

### ISSUE THREAD

**Issue by qwazx** [mack-a/v2ray-agent#190]
**1.描述出现的问题**
可以正常的使用，但是网站本身无法查看，会报错

我这边会提示
The webpage is not available
Remote host HTTP/2 protocol error: -902

尝试了三种系统，Centos、Debian、Ubuntu结果都一样，不知道怎么回事。都是演示网站无法显示

**2.是否安装失败**
否

**3.是否重新build系统后尝试**
是

**4.安装失败的错误内容或者截图**
无

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
Debian10

**6.安装的脚本版本**
当前版本：v2.5.3 

**7.安装类型**
全部安装

**8.安装的核心版本**
当前Xray-core版本:1.4.2 

**9.出现问题的协议类型**
无

**10.尝试重装后是否100%复现**
是

**11.是否更换客户端后再次尝试**
无关

**12.是否将客户端升级最新进行尝试**
是

**13.是否卸载脚本&DD系统后重新用最新脚本安装**
是

**Comment by mack-a** [comment]
正在修

**Comment by qwazx** [comment]
> 正在修
> 
> It’s being repaired

辛苦大佬了

**Comment by mack-a** [comment]
着急得话 可以先用dev 分支 那个修了

**Comment by qwazx** [comment]
> 着急得话 可以先用dev 分支 那个修了

好的。就是月初建了一个没问题，这两天建了两个都有问题，我还以为我哪里弄错了(/▽＼)

**Comment by mack-a** [comment]
最新版已修复

**Comment by qwazx** [comment]
> 最新版已修复

辛苦大佬，我去试试＼(￣▽￣)／

**Comment by Xia-Jingye** [comment]
> 最新版已修复

貌似还是不行，依旧报HTTP/2 protocol error，导致gRPC无法使用。

**Comment by mack-a** [comment]
> > 最新版已修复
> 
> 貌似还是不行，依旧报HTTP/2 protocol error，导致gRPC无法使用。

又修了
