### ISSUE TITLE
疑问【4.如果既想要使用TCP+TLS又想要使用WS+TLS，则不需要开启云朵】

### ISSUE THREAD

**Issue by AaronWing** [mack-a/v2ray-agent#192]
不开启云朵，伪站访问不了，规则还能生效吗？
【当address为智能DNS解析的IP时，流量则会通过Cloudflare回源机制】，这里的只能dns解析是指什么？domain08.mqcjuc.ml吗？

**Comment by mack-a** [comment]
> 不开启云朵，伪站访问不了，规则还能生效吗？
> 【当address为智能DNS解析的IP时，流量则会通过Cloudflare回源机制】，这里的只能dns解析是指什么？domain08.mqcjuc.ml吗？

不开启云朵伪站也是可以正常打开的，如果你想要使用cloudflare进行流量转发则需要吧address设置为你自选的CDNip或者用我提供的

**Comment by AaronWing** [comment]
但现在关掉云朵后，我的伪站访问不到：
![image](https://user-images.githubusercontent.com/22290329/122922482-41f40b80-d396-11eb-9ff1-88560106492c.png)
另外还有个问题，麻烦请教下，改 clash 配置时，{name: xxx, server: xxx, port: 443, type: vmess, uuid: xxx alterId: 1, cipher: auto, tls: true, network: ws, ws-path: /xxx, ws-headers: {Host: xxx}}，server 和 ws-headers host 该怎么配？

**Comment by mack-a** [comment]
> 但现在关掉云朵后，我的伪站访问不到：
> ![image](https://user-images.githubusercontent.com/22290329/122922482-41f40b80-d396-11eb-9ff1-88560106492c.png)
> 另外还有个问题，麻烦请教下，改 clash 配置时，{name: xxx, server: xxx, port: 443, type: vmess, uuid: xxx alterId: 1, cipher: auto, tls: true, network: ws, ws-path: /xxx, ws-headers: {Host: xxx}}，server 和 ws-headers host 该怎么配？

这个问题用最新脚本重新安装就可解决
