### ISSUE TITLE
Debian 10 在安裝nginx時發生錯誤

### ISSUE THREAD

**Issue by fiadigifrank** [mack-a/v2ray-agent#193]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# nginx 啟動失敗。有試著使用wulabing的腳本。安裝nginx是正常
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 是。已全新安裝一新的debian10，一樣出現此問題
```

**4.安装失败的错误内容或者截图**

```
# 在選擇xray-core後，安裝nginx時出現「Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx」

下一步輸入自已的域名後

就出現
 ---> 配置Nginx 
/usr/bin/vasma: line 873: nginx: command not found
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是。全新debian
```

**6.安装的脚本版本**

```
#2.5.5
```

**7.安装类型**

#全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# 全部
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
![iShot2021-06-22 19 30 42](https://user-images.githubusercontent.com/26327498/122917576-c2177280-d390-11eb-8bcf-7c36c103c3d3.jpg)

```

**Comment by mack-a** [comment]
尝试把语言环境改成英文试试

**Comment by LitCcc** [comment]
更新到最新版脚本后重新安装一样出现了
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx，不过之前已经安装过nginx所以配置域名时没有报错


尝试卸载脚本重新安装后解决了

**Comment by fiadigifrank** [comment]
> 尝试把语言环境改成英文试试

嘗試中

**Comment by fiadigifrank** [comment]
> 尝试把语言环境改成英文试试
一樣

**Comment by mack-a** [comment]
> > 尝试把语言环境改成英文试试
> > 一樣

方便通过tg把vps 私聊给我吗
