### ISSUE TITLE
你打错字了

### ISSUE THREAD

**Issue by cloudwindy** [mack-a/v2ray-agent#194]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
xray出现错误的时候会提示“xray启动失败 执行 [ps -ef|grep xray] 查看日志”
我觉得你打错了，应该是 journalctl -ef | grep xray
```
**顺便吐嘈一句，你的这个模板通用性太差，非常不适合我提的这个issue，结果不按模板提交还要直接关闭，不知道怎么想的**

**2.是否安装失败**

```
# 无关
```

**3.是否重新build系统后尝试**

```
# 无关
```

**4.安装失败的错误内容或者截图**

```
# 没有
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
与系统无关
```

**6.安装的脚本版本**

```
# 与版本无关
```

**7.安装类型**

- 与安装类型无关

**8.安装的核心版本**

```
# 无关
```

**9.出现问题的协议类型**

```
# 无关
```

**10.尝试重装后是否100%复现**

```
# 是的
```

**11.是否更换客户端后再次尝试**

```
# 没有
```

**12.是否将客户端升级最新进行尝试**

```
# 没有
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 没有
```

**Comment by mack-a** [comment]
有空会优化下
