### ISSUE TITLE
关掉云朵后，伪站访问不到

### ISSUE THREAD

**Issue by AaronWing** [mack-a/v2ray-agent#196]
如图：
![image](https://user-images.githubusercontent.com/22290329/122930749-d4001200-d39e-11eb-926b-1fbfaa240f3d.png)
另外还有个问题，麻烦请教下，改 clash 配置时，{name: xxx, server: xxx, port: 443, type: vmess, uuid: xxx alterId: 1, cipher: auto, tls: true, network: ws, ws-path: /xxx, ws-headers: {Host: xxx}}，server 和 ws-headers host 该怎么配？

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/192#issuecomment-865994216
