### ISSUE TITLE
安装成功后服务不生效

### ISSUE THREAD

**Issue by finale1230** [mack-a/v2ray-agent#197]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 安装成功，伪装站能正常打开，但服务不生效，pc的v2rayN和手机的小火箭均无法连接
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# 无
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是，搬瓦工的Debian10
```

**6.安装的脚本版本**

```
#2.5.5
```

**7.安装类型**

- 个性化安装VLESS+WS+TLS

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# 全部已安装协议 VLESS+TCP[TLS/XTLS] VLESS+WS[TLS] VMess+TCP[TLS] VMess+WS[TLS] Trojan+TCP/WS[TLS]VLESS+gRPC[TLS]

```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
所有协议都不生效吗

**Comment by mack-a** [comment]
最新版修了

**Comment by finale1230** [comment]
> 最新版修了

用了2.5.6的新脚本卸载重装还是会有同样的问题

**Comment by mack-a** [comment]
> > 最新版修了
> 
> 用了2.5.6的新脚本卸载重装还是会有同样的问题

换客户端试一下

**Comment by mack-a** [comment]
我用新机器重新安装后，用小火煎正常使用，伪站订阅都没有问题
