### ISSUE TITLE
Xray内核下出现ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by bltzraven** [mack-a/v2ray-agent#198]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
使用最新脚本选择Xray内核完成安装后，使用V2rayN并尝试过Trojan-Go+WS，trojan以及VLESS+gRPC+TLS进行访问，Chrome均显示ERR_SSL_PROTOCOL_ERROR。手机上使用Shadowrocket则无问题

另外一台机器选择V2ray内核，则不出现以上问题
```
# 
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是
```

**6.安装的脚本版本**

```
# 2.5.9
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]

``` 

**9.出现问题的协议类型**

```
# Trojan-Go+WS Trojan以及VLESS+gRPC+TLS
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
> > 请仔细填写每一项，并回复自己详细的错误信息
> 
> * 不符合的issue会被直接关闭
> 
> **1.描述出现的问题**
> 使用最新脚本选择Xray内核完成安装后，使用V2rayN并尝试过Trojan-Go+WS，trojan以及VLESS+gRPC+TLS进行访问，Chrome均显示ERR_SSL_PROTOCOL_ERROR。手机上使用Shadowrocket则无问题
> 
> 另外一台机器选择V2ray内核，则不出现以上问题
> 
> ```
> # 
> ```
> 
> **2.是否安装失败**
> 
> ```
> # 否
> ```
> 
> **3.是否重新build系统后尝试**
> 
> ```
> # 是
> ```
> 
> **4.安装失败的错误内容或者截图**
> 
> ```
> # 
> ```
> 
> **5.系统版本【例：Debian10】**
> 
> > 最新版本脚本不支持Centos6，同时不建议使用centos
> 
> * 是否更换Debian10系统后再次安装
> 
> ```
> 是
> ```
> 
> **6.安装的脚本版本**
> 
> ```
> # 2.5.9
> ```
> 
> **7.安装类型**
> 
> * 全部安装
> 
> **8.安装的核心版本**
> 
> ```
> # xray-core[1.4.2]
> ```
> 
> **9.出现问题的协议类型**
> 
> ```
> # Trojan-Go+WS Trojan以及VLESS+gRPC+TLS
> ```
> 
> **10.尝试重装后是否100%复现**
> 
> ```
> # 是
> ```
> 
> **11.是否更换客户端后再次尝试**
> 
> ```
> # 是
> ```
> 
> **12.是否将客户端升级最新进行尝试**
> 
> ```
> # 是
> ```
> 
> **13.是否卸载脚本&DD系统后重新用最新脚本安装**
> 
> ```
> # 是
> ```

换客户端或者用老版本的脚本

**Comment by mack-a** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev_remove_trojan-go/install.sh" && chmod 700 /root/install.sh && /root/install.sh

可以试试这个，Beta版本

**Comment by bltzraven** [comment]
旧版v2.4.16实测没有问题了。 我卸载掉用beta版试试。谢谢大佬。

**Comment by mack-a** [comment]
又更新了 v2.5.10-dev_remove_trojan-go

**Comment by bltzraven** [comment]
v2.5.10-dev_remove_trojan-go， 这个测试ok xray内核下可用。按照命名以及实际安装生成是拿掉了trojan吧。 那后续就静待大佬更新了

**Comment by mack-a** [comment]
> v2.5.10-dev_remove_trojan-go， 这个测试ok xray内核下可用。按照命名以及实际安装生成是拿掉了trojan吧。 那后续就静待大佬更新了

拿掉了trojan是啥意思

**Comment by bltzraven** [comment]
啊嘞？因为最终生成的连接以及安装过程中，没有看到trojan的安装。以为是故意的，请问是要自选安装吗？

**Comment by mack-a** [comment]
全部安装的时候现在不再提起trojan相关内容 ，个性化安装 需要自己选择

**Comment by bltzraven** [comment]
好的 谢谢。
