### ISSUE TITLE
fallback vless to trojan-gfw

### ISSUE THREAD

**Issue by malikshi** [mack-a/v2ray-agent#199]
>==============================================================
作者：mack-a
当前版本：v2.5.10-dev_remove_trojan-go_1
Github：https://github.com/mack-a/v2ray-agent
描述：八合一共存脚本
==============================================================
VMess+TLS+TCP(http+tls)，将在未来几个版本脚本中移除
此版本正在将trojan-go(trojan)替换为Xray-core(trojan)
==============================================================
1.安装
2.任意组合安装
-------------------------工具管理-----------------------------
3.账号管理
4.更换伪装站
5.更新证书
6.更换CDN节点
7.IPv6分流
8.WARP分流
9.流媒体工具
10.添加新端口
-------------------------版本管理-----------------------------
11.core管理
12.更新脚本
13.安装BBR、DD脚本
-------------------------脚本管理-----------------------------
14.查看日志
15.卸载脚本
==============================================================
快捷方式创建成功，可执行[vasma]重新打开脚本
请选择:
1
==============================================================
1.Xray-core
2.v2ray-core
==============================================================
请选择：
1
请输入要配置的域名 例：www.v2ray-agent.com --->
域名:
mydomainsssss.com
当前域名的IP为 [103.227.252.153]，是否正确[y/n]？
y
请输入自定义路径[例: alone]，不需要斜杠，[回车]随机路径
路径:
iptun
如对Cloudflare自选ip不了解，请选择[n]

 移动:104.16.123.96
 联通:hostmonit.com
 电信:www.digitalocean.com
----------------------------
是否使用？[y/n]:
y
是否自定义UUID ？[y/n]:
n

all installation then testing out work fine for all services. anyway is it possible the fallback in vless to trojan(xray) changes to trojan-gfw(original). i want to using trojan panel.
my assumtion
**02_VLESS_TCP_inbounds.json**
`{"dest":31296,"xver":1}`
**remove 04_trojan_TCP_inbounds.json**
then add trojan-gfw panel with port 31296.
yet again, how warp offload works?
NB: i not interested using trojan-go, after you answered the issue #198 i want to try your script again
thanks you for your hard work for this repo

**Comment by malikshi** [comment]
An updates issues.
Via android v2rayng the trojan xray
>06-26 02:20:59.861 D/com.v2ray.ang(18207): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

Using anXray that XTLS forked from sagernet work well.
I will try other service vless/vmess.

**Comment by malikshi** [comment]
Updates issues
I'm testing all services, here the result

>Testing using v2rayNG v 1.6.13 and anXray 0.1-rc02
Trojan TLS  error on v2rayng, work on anxray
VMess+TCP+TLS error on both apps
VLESS+gRPC+TLS work on both apps
VMess+WS+TLS work on both apps
VLESS+WS+TLS work on both apps
VLESS+TCP+TLS/xtls-rprx-splice work on both apps
VLESS+TCP+TLS/xtls-rprx-direct work on both apps

**Comment by mack-a** [comment]
尝试用beta版本，在readme

**Comment by malikshi** [comment]
> Try to use the beta version, in the readme

Yes i am using the beta version v2.5.10-dev_remove_trojan-go_1.
It's error in VMess+TCP+TLS in v2rayng or anxray apk. I found some issues to regarding trojan(xray) it's work in anxray but not working in v2rayng.
Here the log from v2rayNG running trojan(xray)
>06-26 02:20:59.861 D/com.v2ray.ang(18207): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01

**Comment by malikshi** [comment]
@mack-a i found something if the client apps doesn't provide alpn setting, the trojan(xray) not gonna work
Apk anxray provided that setting which is make it work. But v2rayNG not work
![Uploading IMG_20210626_132112.jpg…]()

**Comment by mack-a** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/stable_v2.4.16/install.sh" && chmod 700 /root/install.sh && /root/install.sh   
尝试使用此版本，脚本中trojan不是trojan-gfw，是trojan-go 或者 xray

**Comment by mack-a** [comment]
> trojan-gfw(

不会更改为trojan-gfw实现的trojan，以后会更改为xray/v2ray实现的trojan。我认为只是核心不同应该不会影响到你使用panel。

**Comment by mack-a** [comment]
> > Try to use the beta version, in the readme
> 
> Yes i am using the beta version v2.5.10-dev_remove_trojan-go_1.
> Sorry didn't read `VMess+TLS+TCP(http+tls), will be removed in the next few versions of the script` in note script, so vmess tls+tcp not working because you're removing them? If true, why the json file vmess+tls+tcp not removed from config it's make me confused.
> I found some issues to regarding trojan(xray) it's work in anxray but not working in v2rayng.
> Here the log from v2rayNG running trojan(xray)
> 
> > 06-26 02:20:59.861 D/com.v2ray.ang(18207): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01

手里目前没有安卓设备，等段时间我找一台安卓设备进行测试。完全兼容的版本会在master的下一个版本进行发布

**Comment by malikshi** [comment]
Thank you very much for the follow up the issues. I tried in trojan-gfw client in windows it's seem can't connect properly too.

**Comment by mack-a** [comment]
下个版本我会尽量兼容所有的客户端，尽情期待

**Comment by malikshi** [comment]
@mack-a seeing you committed new update I will wait for the updated version 👍

**Comment by mack-a** [comment]
推荐 anXray、qv2ray、Shadowrocket

**Comment by malikshi** [comment]
yes no need to use script trojan-go(trojan)->Xray-core(trojan)【Beta】? 
after you merge so isn't fine to use latest version?

**Comment by mack-a** [comment]
使用master[Latest Version]

**Comment by malikshi** [comment]
@mack-a thank you, let me try the script.

**Comment by malikshi** [comment]
@mack-a I tested all account and work very good, but need to adjust because you don't include `sni=mydomainsss.com` in links **VLESS_gRPC**, **vmess_ws**, and **VLESS_WS** hope you add `SNI` in links.
note: tested on V2rayNG and an Xray no issues found. but need `SNI` in those links account I mentioned

**Comment by mack-a** [comment]
> @mack-a I tested all account and work very good, but need to adjust because you don't include `sni=mydomainsss.com` in links **VLESS_gRPC**, **vmess_ws**, and **VLESS_WS** hope you add `SNI` in links for the next patch/update
> note: tested on V2rayNG and an Xray no issues found. but need `SNI` in those links account I mentioned

https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.11

**Comment by malikshi** [comment]
Thank you for an updates. I will try it in tomorrow, because my current vps has reached max reinstall os for this month.

**Comment by malikshi** [comment]
I tested the latest script from the master branch it's work so far so good no issues found. and I came to the conclusion I tried to implement the config from your repo to work along with the trojan panel but only with `WebSocket` a.k.a `ws` in streamsetting network that will work along with the trojan panel. anyway thank you very much for all the updates
