### ISSUE TITLE
6.22日之后的install脚本有问题

### ISSUE THREAD

**Issue by chocolateu** [mack-a/v2ray-agent#200]
我正好22号和24号装了两次，装的都是xray vless和trojan 分别在手机小火箭和mac上用
22号都正常
24号的 生成的配置在小火箭上 vless和trojan都能用 但是mac客户端上就是连不上trojan
我验证了下 用22号 9f40b8fd209d67dc0019af0e30cad40802db39bb 这个commit的脚本就是正常的

**Comment by mack-a** [comment]
可以尝试用beta版本，在readme

**Comment by mack-a** [comment]
> 我正好22号和24号装了两次，装的都是xray vless和trojan 分别在手机小火箭和mac上用
> 22号都正常
> 24号的 生成的配置在小火箭上 vless和trojan都能用 但是mac客户端上就是连不上trojan
> 我验证了下 用22号 [9f40b8f](https://github.com/mack-a/v2ray-agent/commit/9f40b8fd209d67dc0019af0e30cad40802db39bb) 这个commit的脚本就是正常的

mac的话 可以尝试使用action版本的qv2ray

**Comment by chocolateu** [comment]
> > 我正好22号和24号装了两次，装的都是xray vless和trojan 分别在手机小火箭和mac上用
> > 22号都正常
> > 24号的 生成的配置在小火箭上 vless和trojan都能用 但是mac客户端上就是连不上trojan
> > 我验证了下 用22号 [9f40b8f](https://github.com/mack-a/v2ray-agent/commit/9f40b8fd209d67dc0019af0e30cad40802db39bb) 这个commit的脚本就是正常的
> 
> mac的话 可以尝试使用action版本的qv2ray

什么是action版本的。。。

**Comment by mack-a** [comment]
https://github.com/Qv2ray/Qv2ray/actions

**Comment by mack-a** [comment]
推荐 v2.5.10
