### ISSUE TITLE
TLS安装失败，请检查acme日志 

### ISSUE THREAD

**Issue by zshleon** [mack-a/v2ray-agent#201]
尝试了最新的脚本，全新DD的系统，还是有这个错误：

[Sat 26 Jun 2021 07:17:26 AM EDT] Please add '--debug' or '--log' to check more details.
[Sat 26 Jun 2021 07:17:26 AM EDT] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat 26 Jun 2021 07:15:09 AM EDT] Please update your account with an email address first.
[Sat 26 Jun 2021 07:15:09 AM EDT] acme.sh --register-account -m my@example.com
[Sat 26 Jun 2021 07:15:09 AM EDT] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Sat 26 Jun 2021 07:17:26 AM EDT] Using CA: https://acme.zerossl.com/v2/DV90
[Sat 26 Jun 2021 07:17:26 AM EDT] Standalone mode.
[Sat 26 Jun 2021 07:17:26 AM EDT] No EAB credentials found for ZeroSSL, let's get one
[Sat 26 Jun 2021 07:17:26 AM EDT] acme.sh is using ZeroSSL as default CA now.
[Sat 26 Jun 2021 07:17:26 AM EDT] Please update your account with an email address first.
[Sat 26 Jun 2021 07:17:26 AM EDT] acme.sh --register-account -m my@example.com
[Sat 26 Jun 2021 07:17:26 AM EDT] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
 ---> TLS安装失败，请检查acme日志

**Comment by mack-a** [comment]
最新的脚本什么版本？

**Comment by zshleon** [comment]
作者：mack-a 
当前版本：v2.5.9 
Github：https://github.com/mack-a/v2ray-agent 
描述：八合一共存脚本

**Comment by mack-a** [comment]
德鸡吗

**Comment by zshleon** [comment]
> 德鸡吗

机子是阿里云，国内的轻量版

**Comment by mack-a** [comment]
用stable试试

**Comment by zshleon** [comment]
> 用stable试试

几个脚本都是过了，一样的error

**Comment by mack-a** [comment]
dd的神马系统版本呐

**Comment by zshleon** [comment]
就是这个脚本里面推荐的Debian 10

**Comment by mack-a** [comment]
没其他的错误了吗

**Comment by zshleon** [comment]
> 没其他的错误了吗

没有，一直是这个错误

**Comment by mack-a** [comment]
acme.sh --register-account -m my@example.com 执行下这个 再安装

**Comment by zshleon** [comment]
试了一下你的方法，再安装的时候到这个

 ---> 配置Nginx 
touch: cannot touch '/etc/nginx/conf.d/alone.conf': No such file or directory
/usr/sbin/vasma: line 637: /etc/nginx/conf.d/alone.conf: No such file or directory
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本

**Comment by mack-a** [comment]
把vps 默认dns改成1. 1. 1. 1

**Comment by zshleon** [comment]
> 把vps dns改成1. 1. 1. 1，并放在首位

用命令行吗？不太会操作...

**Comment by zshleon** [comment]
是不是因为我装了其他的一键脚本，我再重装下系统试试

**Comment by mack-a** [comment]
经群友测试，刚安装的debain10(脚本中的dd)没有发现以上问题

**Comment by mack-a** [comment]
现在还有问题没

**Comment by zshleon** [comment]
没问题了，重新d了一下，放开了阿里云所有的防火墙端口，就可以了

**Comment by junior-stack** [comment]
问一下我在服务器那头打好了Xray以后，我复制VLESS的协议链接到V2RayN, 测试速度能达到3.5M, 但为什么我就是打不开google?

**Comment by Grefer** [comment]
遇到相同问题，80和443端口都开着，但就是获取TSL证书失败，更换DNS后成功！

**Comment by zach666** [comment]
我也遇到相同问题，搞了好久！！！原来是DSN解析没有设置好。需要遇到相同问题的查一下DNS解析。

**Comment by zhaozhuque** [comment]
> acme.sh --register-account -m [my@example.com](mailto:my@example.com)
请问一下我施阿里云的dns解析，是否需要修改
