### ISSUE TITLE
account managemant

### ISSUE THREAD

**Issue by tslim181** [mack-a/v2ray-agent#202]
how do i can manage my v2ray? please help me . i'm newbie

**Comment by malikshi** [comment]
they're offered account management but only add and delete account, cmmiw

**Comment by tslim181** [comment]
> they're offered account management but only add and delete account, cmmiw

v2rayn?

**Comment by malikshi** [comment]
> > they're offered account management but only add and delete account, cmmiw
> 
> v2rayn?

yes. never try the feature manage account but it seems good enough for personal use, for commercial you need to use other script

**Comment by mack-a** [comment]
推荐 v2.5.10
