### ISSUE TITLE
腾讯云香港轻量安装求助

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#203]
腾讯云香港轻量安装求助，在输入域名那一步提示
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->
已经在后台设置放行tcp、udp、1-65535端口了的。系统原来是centos换了Debian也是这样，请问这要怎么解决啊？谢谢
![2021-06-27_145256](https://user-images.githubusercontent.com/9279217/123535650-b2fd3f80-d757-11eb-97d8-41b396130a53.jpg)

**Comment by mack-a** [comment]
改一下 清凉云的默认dns为1.1.1.1

**Comment by smdx** [comment]
谢谢，安装成功了。

**Comment by smdx** [comment]
> 改一下 清凉云的默认dns为1.1.1.1

作者你好，清凉云使用求助。有些网站用清凉云无法打开，另外的服务器就正常传输协议什么的都是相同的。请问要怎么解决啊？谢谢

`2021/06/28 10:03:16 [Info] [2023274167] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:16 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:17 [Info] [2023274167] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2021/06/28 10:03:17 [Info] [2023274167] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:17 [Info] [2023274167] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:17 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:17 [Info] [2023274167] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:qua.sislook.com:443 > common/ret                                              ry: [dial tcp 154.84.6.33:443: connect: connection timed out dial tcp 154.84.6.33:443: operation was canceled] > common/retry: all retry attempts failed
2021/06/28 10:03:22 [Info] [954088450] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:22 [Info] [954088450] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:22 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:29 [Info] [954088450] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:29 [Info] [954088450] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:29 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:35 [Info] [924278222] proxy/vless/inbound: firstLen = 373
2021/06/28 10:03:35 [Info] [924278222] proxy/vless/inbound: received request for tcp:qua.sislook.com:443
2021/06/28 10:03:35 [Info] [924278222] app/dispatcher: default route for tcp:qua.sislook.com:443
2021/06/28 10:03:35 [Info] [924278222] proxy/freedom: opening connection to tcp:qua.sislook.com:443
2021/06/28 10:03:35 [Info] [924278222] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:35 [Info] [924278222] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:35 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:36 [Info] [954088450] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:36 [Info] [954088450] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:36 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:37 [Info] [954088450] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2021/06/28 10:03:37 [Info] [954088450] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:37 [Info] [954088450] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:37 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:37 [Info] [954088450] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:qua.sislook.com:443 > common/retry: [dial tcp 154.84.6.33:443: connect: connection timed out dial tcp 154.84.6.33:443: operation was canceled] > common/retry: all retry attempts failed
2021/06/28 10:03:42 [Info] [924278222] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:42 [Info] [924278222] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:42 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:49 [Info] [924278222] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:49 [Info] [924278222] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:49 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:56 [Info] [924278222] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:56 [Info] [924278222] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:56 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:57 [Info] [924278222] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2021/06/28 10:03:57 [Info] [924278222] proxy/freedom: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:57 [Info] [924278222] transport/internet/tcp: dialing TCP to tcp:154.84.6.33:443
2021/06/28 10:03:57 [Debug] transport/internet: dialing to tcp:154.84.6.33:443
2021/06/28 10:03:57 [Info] [924278222] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:qua.sislook.com:443 > common/retry: [dial tcp 154.84.6.33:443: connect: connection timed out dial tcp 154.84.6.33:443: operation was canceled] > common/retry: all retry attempts failed
2021/06/28 10:04:24 [Info] [707801113] proxy/vless/inbound: firstLen = 647
2021/06/28 10:04:24 [Info] [707801113] proxy/vless/inbound: received request for tcp:www.google.com.hk:443
2021/06/28 10:04:24 [Info] [707801113] app/dispatcher: default route for tcp:www.google.com.hk:443
2021/06/28 10:04:24 [Info] [707801113] proxy/freedom: opening connection to tcp:www.google.com.hk:443
2021/06/28 10:04:24 [Info] [707801113] proxy/freedom: dialing to tcp:172.217.31.227:443
2021/06/28 10:04:24 [Info] [707801113] transport/internet/tcp: dialing TCP to tcp:172.217.31.227:443
2021/06/28 10:04:24 [Debug] transport/internet: dialing to tcp:172.217.31.227:443
2021/06/28 10:04:25 [Info] [2969964696] proxy/vless/inbound: firstLen = 681
2021/06/28 10:04:25 [Info] [2969964696] proxy/vless/inbound: received request for tcp:oauthaccountmanager.googleapis.com:443
2021/06/28 10:04:25 [Info] [2969964696] app/dispatcher: default route for tcp:oauthaccountmanager.googleapis.com:443
2021/06/28 10:04:25 [Info] [2969964696] proxy/freedom: opening connection to tcp:oauthaccountmanager.googleapis.com:443
2021/06/28 10:04:25 [Info] [2969964696] proxy/freedom: dialing to tcp:142.250.199.74:443
2021/06/28 10:04:25 [Info] [2969964696] transport/internet/tcp: dialing TCP to tcp:142.250.199.74:443
2021/06/28 10:04:25 [Debug] transport/internet: dialing to tcp:142.250.199.74:443
2021/06/28 10:04:25 [Info] [814740844] proxy/vless/inbound: firstLen = 645
2021/06/28 10:04:25 [Info] [814740844] proxy/vless/inbound: received request for tcp:id.google.com.hk:443
2021/06/28 10:04:25 [Info] [814740844] app/dispatcher: default route for tcp:id.google.com.hk:443
2021/06/28 10:04:25 [Info] [814740844] proxy/freedom: opening connection to tcp:id.google.com.hk:443
2021/06/28 10:04:25 [Info] [814740844] proxy/freedom: dialing to tcp:142.250.204.67:443
2021/06/28 10:04:25 [Info] [814740844] transport/internet/tcp: dialing TCP to tcp:142.250.204.67:443
2021/06/28 10:04:25 [Debug] transport/internet: dialing to tcp:142.250.204.67:443
2021/06/28 10:04:29 [Info] [4075674918] proxy/vless/inbound: firstLen = 568
2021/06/28 10:04:29 [Info] [4075674918] proxy/vless/inbound: received request for tcp:github.com:443
2021/06/28 10:04:29 [Info] [4075674918] app/dispatcher: default route for tcp:github.com:443
2021/06/28 10:04:29 [Info] [4075674918] proxy/freedom: opening connection to tcp:github.com:443
2021/06/28 10:04:29 [Info] [4075674918] proxy/freedom: dialing to tcp:52.74.223.119:443
2021/06/28 10:04:29 [Info] [4075674918] transport/internet/tcp: dialing TCP to tcp:52.74.223.119:443
2021/06/28 10:04:29 [Debug] transport/internet: dialing to tcp:52.74.223.119:443
2021/06/28 10:04:30 [Info] [776442804] proxy/vless/inbound: firstLen = 587
2021/06/28 10:04:30 [Info] [776442804] proxy/vless/inbound: received request for tcp:github.githubassets.com:443
2021/06/28 10:04:30 [Info] [776442804] app/dispatcher: default route for tcp:github.githubassets.com:443
2021/06/28 10:04:30 [Info] [776442804] proxy/freedom: opening connection to tcp:github.githubassets.com:443
2021/06/28 10:04:30 [Info] [776442804] proxy/freedom: dialing to tcp:185.199.110.154:443
2021/06/28 10:04:30 [Info] [776442804] transport/internet/tcp: dialing TCP to tcp:185.199.110.154:443
2021/06/28 10:04:30 [Debug] transport/internet: dialing to tcp:185.199.110.154:443
2021/06/28 10:04:31 [Info] [3264993163] proxy/vless/inbound: firstLen = 599
2021/06/28 10:04:31 [Info] [3264993163] proxy/vless/inbound: received request for tcp:avatars.githubusercontent.com:443
2021/06/28 10:04:31 [Info] [3264993163] app/dispatcher: default route for tcp:avatars.githubusercontent.com:443
2021/06/28 10:04:31 [Info] [3264993163] proxy/freedom: opening connection to tcp:avatars.githubusercontent.com:443
2021/06/28 10:04:31 [Info] [3264993163] proxy/freedom: dialing to tcp:185.199.110.133:443
2021/06/28 10:04:31 [Info] [3264993163] transport/internet/tcp: dialing TCP to tcp:185.199.110.133:443
2021/06/28 10:04:31 [Debug] transport/internet: dialing to tcp:185.199.110.133:443
2021/06/28 10:04:31 [Info] [2667430312] proxy/vless/inbound: firstLen = 675
2021/06/28 10:04:31 [Info] [2667430312] proxy/vless/inbound: received request for tcp:content-autofill.googleapis.com:443
2021/06/28 10:04:31 [Info] [2667430312] app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/06/28 10:04:31 [Info] [2667430312] proxy/freedom: opening connection to tcp:content-autofill.googleapis.com:443
2021/06/28 10:04:31 [Info] [2667430312] proxy/freedom: dialing to tcp:142.250.66.106:443
2021/06/28 10:04:31 [Info] [2667430312] transport/internet/tcp: dialing TCP to tcp:142.250.66.106:443
2021/06/28 10:04:31 [Debug] transport/internet: dialing to tcp:142.250.66.106:443
2021/06/28 10:04:31 [Info] [861293586] proxy/vless/inbound: firstLen = 574
2021/06/28 10:04:31 [Info] [861293586] proxy/vless/inbound: received request for tcp:alive.github.com:443
2021/06/28 10:04:31 [Info] [861293586] app/dispatcher: default route for tcp:alive.github.com:443
2021/06/28 10:04:31 [Info] [861293586] proxy/freedom: opening connection to tcp:alive.github.com:443
2021/06/28 10:04:31 [Info] [861293586] proxy/freedom: dialing to tcp:140.82.114.26:443
2021/06/28 10:04:31 [Info] [861293586] transport/internet/tcp: dialing TCP to tcp:140.82.114.26:443
2021/06/28 10:04:31 [Debug] transport/internet: dialing to tcp:140.82.114.26:443
2021/06/28 10:04:37 [Info] [1217522189] proxy/vless/inbound: firstLen = 591
2021/06/28 10:04:37 [Info] [1217522189] proxy/vless/inbound: received request for tcp:raw.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [1217522189] app/dispatcher: default route for tcp:raw.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [1217522189] proxy/freedom: opening connection to tcp:raw.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [1217522189] proxy/freedom: dialing to tcp:185.199.110.133:443
2021/06/28 10:04:37 [Info] [1217522189] transport/internet/tcp: dialing TCP to tcp:185.199.110.133:443
2021/06/28 10:04:37 [Debug] transport/internet: dialing to tcp:185.199.110.133:443
2021/06/28 10:04:37 [Info] [3092688926] proxy/vless/inbound: firstLen = 588
2021/06/28 10:04:37 [Info] [3092688926] proxy/vless/inbound: received request for tcp:avatars0.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [3092688926] app/dispatcher: default route for tcp:avatars0.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [3092688926] proxy/freedom: opening connection to tcp:avatars0.githubusercontent.com:443
2021/06/28 10:04:37 [Info] [3092688926] proxy/freedom: dialing to tcp:185.199.109.133:443
2021/06/28 10:04:37 [Info] [3092688926] transport/internet/tcp: dialing TCP to tcp:185.199.109.133:443
2021/06/28 10:04:37 [Debug] transport/internet: dialing to tcp:185.199.109.133:443
2021/06/28 10:05:40 [Info] [23697277] proxy/vless/inbound: firstLen = 643
2021/06/28 10:05:40 [Info] [23697277] proxy/vless/inbound: received request for tcp:mail.google.com:443
2021/06/28 10:05:40 [Info] [23697277] app/dispatcher: default route for tcp:mail.google.com:443
2021/06/28 10:05:40 [Info] [23697277] proxy/freedom: opening connection to tcp:mail.google.com:443
2021/06/28 10:05:40 [Info] [23697277] proxy/freedom: dialing to tcp:142.250.204.101:443
2021/06/28 10:05:40 [Info] [23697277] transport/internet/tcp: dialing TCP to tcp:142.250.204.101:443
2021/06/28 10:05:40 [Debug] transport/internet: dialing to tcp:142.250.204.101:443
2021/06/28 10:05:48 [Info] [861293586] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/06/28 10:06:01 [Info] [1856731909] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/06/28 10:06:01 [Info] [1856731909] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer response payload > io: read/write on closed pipe
2021/06/28 10:06:02 [Info] [1397766909] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2021/06/28 10:06:02 [Info] [1397766909] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/06/28 10:06:28 [Info] [2968047278] proxy/vless/inbound: firstLen = 0
2021/06/28 10:06:28 [Info] [2968047278] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2021/06/28 10:06:28 [Info] [2968047278] proxy/vless/inbound: realName =
2021/06/28 10:06:28 [Info] [2968047278] proxy/vless/inbound: realAlpn =
2021/06/28 10:06:28 [Info] [2968047278] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [301]
2021/06/28 10:07:01 [Info] [4075674918] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/06/28 10:07:01 [Info] [4075674918] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
`
