### ISSUE TITLE
TLS安装失败请检查ACME日志

### ISSUE THREAD

**Issue by johnan0528** [mack-a/v2ray-agent#206]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
安装TLS证书的时候出现问题

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

![image](https://user-images.githubusercontent.com/66048352/123738951-6a20c480-d8d8-11eb-80b3-50f757fe13e8.png)

**5.系统版本Debian10
- 是否更换Debian10系统后再次安装
否
**6.安装的脚本版本**
Latest version 
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**7.安装类型**

Xray 默认安装

**Comment by mack-a** [comment]
防火墙关一下

**Comment by YefengYue** [comment]
关闭防火墙：ufw disable
或开放80和443端口 ：ufw allow 80
                                    ufw allow 443
