### ISSUE TITLE
grpc在v2rayng上无法工作

### ISSUE THREAD

**Issue by ajdgsu** [mack-a/v2ray-agent#207]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 在使用v2rayng(安卓)时，grpc无法工作
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version (xray报错)
"PRI * HTTP/2.0" 400 157 "-" "-" "-" (nginx报错)
```

**5.系统版本【Ubuntu 20.04】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#Latest Version
```

**7.安装类型**

- 个性化安装(05)

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是(当前版本为v1.6.13 lib v23, xray-core v1.4.2)
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
目前这个版本的v2rayNG与脚本不兼容，请更换AnXray使用
