### ISSUE TITLE
大佬看一下进行到15/17之后就提示错误日志

### ISSUE THREAD

**Issue by shuyeee** [mack-a/v2ray-agent#209]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
进行到15/17之后就提示错误日志

请手动执行【/etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf】，查看错误日志 
root@shuyee_vps:~# /etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf
V2Ray 4.41.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
A unified platform for anti-censorship.
2021/07/01 17:18:32 Using confdir from arg: /etc/v2ray-agent/v2ray/conf
v2ctl> [ /etc/v2ray-agent/v2ray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
v2ctl> [ /etc/v2ray-agent/v2ray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
v2ctl> [ /etc/v2ray-agent/v2ray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
v2ctl> [ /etc/v2ray-agent/v2ray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/00_log.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/02_VLESS_TCP_inbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/03_VLESS_WS_inbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/04_trojan_TCP_inbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/05_VMess_WS_inbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/06_VLESS_gRPC_inbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/10_ipv4_outbounds.json
2021/07/01 17:18:32 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/11_dns.json

```

**2.是否安装失败**
是


**3.是否重新build系统后尝试**

build系统是什么...我是小白55

**4.安装失败的错误内容或者截图**
![image](https://user-images.githubusercontent.com/66329206/124101520-04783800-da92-11eb-8fba-ff02c984e446.png)

```

**5.系统版本【例：Debian10】
Ubuntu 18.04 x64
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

否
```

**6.安装的脚本版本**
v2.5.13 
#
```

**7.安装类型**

-全部安装

**8.安装的核心版本**
 v2ray-core版本:v4.41.0
```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**
还没选协议就提示错误日志了

```

**10.尝试重装后是否100%复现**
是的
```

```

**11.是否更换客户端后再次尝试**
哪个客户端 shell客户端吗
```
# 否
```

**12.是否将客户端升级最新进行尝试**

哪个客户端
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**
直接选的重新安装 没有卸
```
# 否
```

**Comment by mack-a** [comment]
用xray试试
