### ISSUE TITLE
wget: command not found [这里需要自己手动安装下wget]

### ISSUE THREAD

**Issue by shuishou4184** [mack-a/v2ray-agent#21]
我是小白，谁能告诉我怎么手动安装wget呢

**Comment by mack-a** [comment]
> 我是小白，谁能告诉我怎么手动安装wget呢

啥系统

**Comment by mack-a** [comment]
- centos
```
yum install wget -y
```
- Debian&Ubuntu
```
apt install wget -y
or
apt-get install wget -y
```

**Comment by shuishou4184** [comment]
> * centos
> 
> ```
> yum install wget -y
> ```
> 
> * Debian&Ubuntu
> 
> ```
> apt install wget -y
> or
> apt-get install wget -y
> ```

感谢，按照你的方法搞定 Debian系统，非常感谢
