### ISSUE TITLE
VPS重启后核心不会自己启动，手动启动不能成功，debian10系统，xray和v2ray均如此

### ISSUE THREAD

**Issue by hunterleekm** [mack-a/v2ray-agent#210]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# VPS重启后核心就不会自己启动，手动启动也不能成功，重启VPS执行vasma后，核心行显示未运行，执行11.核心管理里的所有项目均不能重启核心，只能执行1.重新安装才能成功启动核心（不改变任何参数的话客户端可接着用），百试不爽，xray和v2ray都一样，这是什么问题？

```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#2.5.13
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray和v2ray都一样
```

**9.出现问题的协议类型**

```
# 所有
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 与客户端无关，v2rayN，Qv2ray，Clash，Clash.net
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
我这没复现，可能是特例。你可以检查下 xray或者v2ray的service是否enable成功

**Comment by MFYDev** [comment]
今天同样遇到了这个问题，所有使用最新版脚本安装，重启vps后全部都无法启动，必须手动启动才可以

**Comment by mack-a** [comment]
> 今天同样遇到了这个问题，所有使用最新版脚本安装，重启vps后全部都无法启动，必须手动启动才可以

检查下service 的状态

**Comment by MFYDev** [comment]
重启vps后，如果不进行任何操作手动启动xray是无法启动的，还是需要把之前的trojan-go结束了才能手动启动成功，所以确认为trojan-go的问题，之前您回复过我使用stable版本卸载trojan-go，可是stable版本里并没有卸载trojan-go的选项，只有重新安装的选项，latest version重新安装也没有彻底卸载trojan-go的选项。

这就形成了悖论，如果使用过以前老版本安装过的，必须手动卸载才能卸干净。

**Comment by mack-a** [comment]
systemctl stop trojan-go
systemctl disable trojan-go


明天我写到release里面
