### ISSUE TITLE
用ipv6分流访问google scholar

### ISSUE THREAD

**Issue by chengwei21** [mack-a/v2ray-agent#211]
我建好之后还是无法访问谷歌学术，我谷歌了一下说是谷歌学术把我的ip给封了，如果用ipv6进行访问就可以，所以我想问问如何用这里的ipv6分流技术来访问谷歌学术呢

**Comment by mack-a** [comment]
脚本里面有ipv6分流

**Comment by chengwei21** [comment]
我用ipv6添加google-scholar域名后，还是无法访问谷歌学术
![屏幕截图 2021-07-04 084753](https://user-images.githubusercontent.com/53066412/124369987-948dcb80-dca4-11eb-96da-c6d2d8cb29b1.png)
![屏幕截图 2021-07-04 084730](https://user-images.githubusercontent.com/53066412/124369989-96f02580-dca4-11eb-85e5-85787872608a.png)

**Comment by mack-a** [comment]
> 我用ipv6添加google-scholar域名后，还是无法访问谷歌学术
> 
> ![屏幕截图 2021-07-04 084753](https://user-images.githubusercontent.com/53066412/124369987-948dcb80-dca4-11eb-96da-c6d2d8cb29b1.png)
> 
> ![屏幕截图 2021-07-04 084730](https://user-images.githubusercontent.com/53066412/124369989-96f02580-dca4-11eb-85e5-85787872608a.png)
> 
> 

你自己 ip的问题 需要自己找能解锁的

**Comment by chengwei21** [comment]
好的，谢谢了
