### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by chenqiuhe** [mack-a/v2ray-agent#212]
今天更新了脚本，重新安装时变成以下安装不了了，

9.WARP分流
10.流媒体工具
11.添加新端口
熊
-版本管理
12.core管理
13.更新脚本
14.安装BBR、DD脚本
-脚本管理
15.查看日志
16.卸载脚本
请选择:11 
功能 1/1 :选择核心安装
1.Xray-core
2.v2ray
请选择：1 
安装工具
进度
2 2/17 ：安装工具
检查、安装更新【新机器会很慢，如长时间无反
安装binutils 
安装1sb-release
安装semanage 
进度 3/17 ：初始化Nginx申请证书配置
请输入要配置的域名例：www.v2ray-agent.com ---
域名:www.chenqiuhe.ga
配置Nginx
nginx: [emerg] open()"/etc/nginx/modules-enabled
/50-mod-http-auth-pam.conf" failed (2: No such fi
le or directory) in /etc/nginx/nginx.conf:4
Nginx启动失败
请手动尝试安装nginx后，再次执行脚本
root@hk:~#·

**Comment by mack-a** [comment]
删除nginx后重新安装

**Comment by mack-a** [comment]
或者直接dd新系统进行安装

**Comment by mack-a** [comment]
或者直接dd新系统进行安装

**Comment by mack-a** [comment]
或者直接dd新系统进行安装

**Comment by chenqiuhe** [comment]
> 删除nginx后重新安装

怎么样操作丫？

**Comment by mack-a** [comment]
直接dd  debian10重新弄 dd脚本 脚本里面有

**Comment by ulifuqiang** [comment]
我也是这个情况 Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 5.13.1 x86_64)

**Comment by mack-a** [comment]
> 我也是这个情况 Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 5.13.1 x86_64)

dd系统重新执行下就ok
