### ISSUE TITLE
VLESS+TLS+gRPC失败，其他6个协议组合正常

### ISSUE THREAD

**Issue by ForestSketch** [mack-a/v2ray-agent#213]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# VLESS+grpc+tlc无法使用，全部七个协议组合其他六个都可以用，除了这一个。虽然不影响上网，但是想了解下这个组合为何失败？初步判断不是grpc的问题，因为trogan+grac正常使用，而其他vless也正常使用，就很奇怪。
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否，全新创建的vps，全新的域名，就是担心出现tls、ame失败
```

**4.安装失败的错误内容或者截图**

```
# 没有失败，应该是顺利安装完成
```

**5.系统版本【例：Ubuntu20】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 重新安装最新版本ubuntu还是不行

```
否
```

**6.安装的脚本版本**

```
#大佬推荐的最新版本脚本
```

**7.安装类型**

-全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
https://t.me/v2rayagentshare/438

https://t.me/v2rayagentshare/420

**Comment by 1-1-2** [comment]
确实，猜测是 nginx 中没有配置TLS证书。有空测试

>https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC
