### ISSUE TITLE
主机重启后warp分流不生效，卸载warp后也无法重新安装

### ISSUE THREAD

**Issue by cn-404-not-found** [mack-a/v2ray-agent#217]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
#主机重启后warp分流不生效，重启前一切正常，在debian和ubuntu都试过
另外卸载warp后也无法重新安装，即使整个脚本卸载也无法安装，卸载warp后，进入脚本选择9，第二个菜单仍然是卸载warp分流而不是安装warp分流

**2.是否安装失败**
#否

**3.是否重新build系统后尝试**
#否

**4.安装失败的错误内容或者截图** 
#无

**5.系统版本
#Debian10和Ubuntu20.04

**Comment by mack-a** [comment]
有空我看一下，可能自启任务没启动

**Comment by cn-404-not-found** [comment]
> 有空我看一下，可能自启任务没启动

有手工启动的命令吗？

**Comment by mack-a** [comment]
疑似cloudflare-warp官方客户端bug，现已移除
