### ISSUE TITLE
更好的自动化

### ISSUE THREAD

**Issue by fggggsn** [mack-a/v2ray-agent#218]
**详细描述建议的内容**
对于仅有ipv4的vps，能否在安装脚本时自动配置WARP 添加 IPv6以解锁全部Netflix以及谷歌人机验证?

**Comment by mack-a** [comment]
这样做issues会经常有人问【为什么我的自己加ipv6，脚本作者是不是加料了 balabla的一些问题】

**Comment by mack-a** [comment]
> **详细描述建议的内容**
> 对于仅有ipv4的vps，能否在安装脚本时自动配置WARP 添加 IPv6以解锁全部Netflix以及谷歌人机验证?

脚本内的warp已经移除了

**Comment by mack-a** [comment]
还有一个问题，不是所有的vps都有人机验证，只有那几天比较滥用的机房才会出这个
