### ISSUE TITLE
IP查询失败，请检查域名解析是否正确，是否重试[y/n]？

### ISSUE THREAD

**Issue by fzts** [mack-a/v2ray-agent#219]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# IP查询失败，请检查域名解析是否正确，是否重试[y/n]？
使用的hostiger土耳其的vps，使用cloudflare DNS，我自己的电脑可以ping通域名，VPS上也可以ping通，但是脚本死活检测不到IP。尝试使用2.4.x版本，但是脚本下载失败
![image](https://user-images.githubusercontent.com/28336310/125888412-14fb8ad6-9004-44e7-97da-ce325185cf66.png)
先感谢大佬
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
![image](https://user-images.githubusercontent.com/28336310/125887830-c2aa36be-c6ba-4f36-87c6-5913ccfc0a7a.png)

```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
操作系统模板 | Debian GNU/Linux 10 (64-bit)
- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#当前版本：v2.5.17
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
尝试修改下dns呐

**Comment by mack-a** [comment]
手动安装jq之后再尝试，缺少jq包

**Comment by fzts** [comment]
谢谢大佬
