### ISSUE TITLE
V2Ray启动失败

### ISSUE THREAD

**Issue by chenwangnec** [mack-a/v2ray-agent#22]
请手动执行【/etc/v2ray-agent/v2ray/v2ray -config /etc/v2ray-agent/v2ray/config.json】,查看错误日志

**Comment by mack-a** [comment]
> 请手动执行【/etc/v2ray-agent/v2ray/v2ray -config /etc/v2ray-agent/v2ray/config.json】,查看错误日志 

pls -ef|grep v2ray 查看返回信息 
你之前装过v2ray吗

**Comment by chenwangnec** [comment]
好的 我试一下

**Comment by chenwangnec** [comment]
还是无法启动,VPS上原来运行正常了 后来发现v2ray 无法启动，在用最新的脚本安装 和全卸载，在安装还是无法启动
root@vm194277:~# ps -ef|grep v2ray
root       44932       1  0 13:55 ?        00:00:00 /etc/v2ray-agent/trojan/trojan-go -config /etc/v2ray-agent/trojan/config.json
root       45133   44005  0 14:03 pts/0    00:00:00 grep --color=auto v2ray
root@vm194277:~#

**Comment by mack-a** [comment]
> 还是无法启动,VPS上原来运行正常了 后来发现v2ray 无法启动，在用最新的脚本安装 和全卸载，在安装还是无法启动
> root@vm194277:~# ps -ef|grep v2ray root 44932 1 0 13:55 ? 00:00:00 /etc/v2ray-agent/trojan/trojan-go -config /etc/v2ray-agent/trojan/config.json root 45133 44005 0 14:03 pts/0 00:00:00 grep --color=auto v2ray root@vm194277:~#

现在用最新的再试一下 然后到哪一个步骤无法通过贴个错误信息

**Comment by chenwangnec** [comment]
============================================================== 
作者：mack-a 
当前版本：v2.0.26 
Github：https://github.com/mack-a/v2ray-agent 
描述：七合一共存脚本 
============================================================== 
1.安装 
2.任意组合安装 
-------------------------工具管理----------------------------- 
3.查看账号 
4.自动排错 
5.更新证书 [fail] 
6.更换CDN节点 
7.重置uuid 
-------------------------版本管理----------------------------- 
8.V2Ray版本管理 
9.升级Trojan-Go 
10.升级脚本 
11.安装BBR 
-------------------------脚本管理----------------------------- 
12.查看日志 
13.卸载脚本 
============================================================== 
快捷方式创建成功，可执行[vasma]重新打开脚本 
请选择:1

进度  1/17 : 创建文件夹 

进度  2/17 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，耐心等待】 

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 ---> 安装binutils 

进度  3/17 : 初始化Nginx申请证书配置 
请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:msk.tajk.cf
 ---> 配置Nginx 
 ---> 检查Nginx是否正常访问 
 ---> Nginx配置成功 

进度  4/17 : 申请TLS证书 
 ---> 检测到证书 
是否重新生成？[y/n]:y

进度  4/17 : 申请TLS证书 
 ---> 安装TLS证书 
 ---> TLS生成成功 

进度  5/17 : 配置Nginx 

进度  6/17 : 生成随机路径 
请输入自定义路径[例: alone]，不需要斜杠，[回车]随机路径 
路径:msktajkcfblog
path：msktajkcfblog 

进度  7/17 : 安装V2Ray 
 ---> v2ray-core版本:4.31.1 
是否重新安装？[y/n]:y

进度  7/17 : 安装V2Ray 
 ---> v2ray-core版本:v4.31.1 

进度  8/17 : 配置V2Ray开机自启 
 ---> 配置V2Ray开机自启成功 

进度  9/17 : 安装Trojan-Go 
 ---> Trojan-Go版本:v0.8.2 
是否重新安装？[y/n]:y

进度  9/17 : 安装Trojan-Go 
 ---> Trojan-Go版本:v0.8.2 

进度  10/17 : 配置Trojan开机自启 
 ---> 配置Trojan开机自启成功 

进度 11/17 : 添加DNS智能解析 
 移动:104.19.41.56 
 联通:104.16.160.136 
 电信:104.17.78.198 
是否使用？[y/n]:y

进度 12/17 : 初始化Trojan配置 

进度 13/17 : 初始化V2Ray配置 

进度  14/17 : 添加定时维护证书 
 ---> 添加定时维护证书成功 

进度 15/17 : 添加伪装博客 
 ---> 添加伪装博客成功 
 ---> V2Ray关闭成功 
V2Ray启动失败 
ps -ef|grep v2ray,查看日志 
root@vm194277:~#

**Comment by chenwangnec** [comment]
V2Ray启动失败 
ps -ef|grep v2ray,查看日志 
root@vm194277:~# ps -ef|grep v2ray
root       49182   48229  0 14:13 pts/0    00:00:00 grep --color=auto v2ray
root@vm194277:~#

**Comment by chenwangnec** [comment]
最新脚本 是当前版本：v2.0.26

**Comment by mack-a** [comment]
> 最新脚本 是当前版本：v2.0.26

可否借vps一用 我上去看一眼 是为啥

**Comment by mack-a** [comment]
> # ==============================================================
> 作者：mack-a
> 当前版本：v2.0.26
> Github：https://github.com/mack-a/v2ray-agent
> 描述：七合一共存脚本
> # 1.安装
> 2.任意组合安装
> -------------------------工具管理-----------------------------
> 3.查看账号
> 4.自动排错
> 5.更新证书 [fail]
> 6.更换CDN节点
> 7.重置uuid
> -------------------------版本管理-----------------------------
> 8.V2Ray版本管理
> 9.升级Trojan-Go
> 10.升级脚本
> 11.安装BBR
> -------------------------脚本管理-----------------------------
> 12.查看日志
> 13.卸载脚本
> 快捷方式创建成功，可执行[vasma]重新打开脚本
> 请选择:1
> 
> 进度 1/17 : 创建文件夹
> 
> 进度 2/17 : 安装工具
> ---> 检查、安装更新【新机器会很慢，耐心等待】
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> ---> 安装binutils
> 
> 进度 3/17 : 初始化Nginx申请证书配置
> 请输入要配置的域名 例：blog.v2ray-agent.com --->
> 域名:msk.tajk.cf
> ---> 配置Nginx
> ---> 检查Nginx是否正常访问
> ---> Nginx配置成功
> 
> 进度 4/17 : 申请TLS证书
> ---> 检测到证书
> 是否重新生成？[y/n]:y
> 
> 进度 4/17 : 申请TLS证书
> ---> 安装TLS证书
> ---> TLS生成成功
> 
> 进度 5/17 : 配置Nginx
> 
> 进度 6/17 : 生成随机路径
> 请输入自定义路径[例: alone]，不需要斜杠，[回车]随机路径
> 路径:msktajkcfblog
> path：msktajkcfblog
> 
> 进度 7/17 : 安装V2Ray
> ---> v2ray-core版本:4.31.1
> 是否重新安装？[y/n]:y
> 
> 进度 7/17 : 安装V2Ray
> ---> v2ray-core版本:v4.31.1
> 
> 进度 8/17 : 配置V2Ray开机自启
> ---> 配置V2Ray开机自启成功
> 
> 进度 9/17 : 安装Trojan-Go
> ---> Trojan-Go版本:v0.8.2
> 是否重新安装？[y/n]:y
> 
> 进度 9/17 : 安装Trojan-Go
> ---> Trojan-Go版本:v0.8.2
> 
> 进度 10/17 : 配置Trojan开机自启
> ---> 配置Trojan开机自启成功
> 
> 进度 11/17 : 添加DNS智能解析
> 移动:104.19.41.56
> 联通:104.16.160.136
> 电信:104.17.78.198
> 是否使用？[y/n]:y
> 
> 进度 12/17 : 初始化Trojan配置
> 
> 进度 13/17 : 初始化V2Ray配置
> 
> 进度 14/17 : 添加定时维护证书
> ---> 添加定时维护证书成功
> 
> 进度 15/17 : 添加伪装博客
> ---> 添加伪装博客成功
> ---> V2Ray关闭成功
> V2Ray启动失败
> ps -ef|grep v2ray,查看日志
> root@vm194277:~#

这个地方如果有证书 重新安装的时候 不要选择y 选择n 每个ip和域名在一定时间内 证书是有数量限制的

**Comment by chenwangnec** [comment]
好的

**Comment by chenwangnec** [comment]
45.136.245.88
Login: root
Password: 1nN0U4W3KzT9Iv9

**Comment by mack-a** [comment]
> 好的

我已经收到密码账号了 我先把那条敏感信息删除掉

**Comment by chenwangnec** [comment]
好的 ，麻烦了 mack-a大神

**Comment by mack-a** [comment]
> 好的 ，麻烦了 mack-a大神

ss可以关掉吗

**Comment by mack-a** [comment]
> 好的 ，麻烦了 mack-a大神

好了 等会你自己改一下vps的密码和重新执行下脚本 重新安装一次
 tls如果提示是否重新安装的时候 要选择n
问题是里面有一个进程一直创建service 导致安装不成功

**Comment by chenwangnec** [comment]
好的，麻烦了 mack-a大神

**Comment by Happiness-in-Danger** [comment]
@mack-a 我也是这个问题 ,重新卸载,安装也试过了,还是不行
![图片](https://user-images.githubusercontent.com/45912561/124913128-56d0d000-e021-11eb-845c-2a367f16de33.png)

**Comment by mack-a** [comment]
> @mack-a 我也是这个问题 ,重新卸载,安装也试过了,还是不行
> 
> ![图片](https://user-images.githubusercontent.com/45912561/124913128-56d0d000-e021-11eb-845c-2a367f16de33.png)
> 
> 

需要先用别人脚本安装的停掉，或者直接重装系统

**Comment by A-script** [comment]
检测到安装伪装站点，是否需要重新安装[y/n]:n
 ---> V2Ray关闭成功 
V2Ray启动失败 
请手动执行【/etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf】，查看错误日志 
root@v1:~# ps -ef|grep v2ray
root        6839    1077  0 17:51 pts/0    00:00:00 grep v2ray
