### ISSUE TITLE
现在已经有TLS证书，如何安装程序？

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#222]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
现已有TLS证书，按照该链接操作步骤：https://github.com/mack-a/v2ray-agent/blob/master/documents/install_tls.md， 安装失败。
 
 请问：在现已有证书的前提下，如何正确安装程序？

```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是
```

**6.安装的脚本版本**

```
 最新
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
脚本readme里面有，只要copy到指定目录脚本会自动识别

**Comment by AndersonGhost** [comment]
我就是按照readme的教程来安装的：
1.首先，按照教程，将证书拷贝到相应的文件夹内并改名。
2.安装一键脚本。
3.acme.sh提示安装失败。

**Comment by mack-a** [comment]
> 我就是按照readme的教程来安装的：
> 1.首先，按照教程，将证书拷贝到相应的文件夹内并改名。
> 2.安装一键脚本。
> 3.提示安装失败，显示如下：
> 
> 检查Nginx是否正常访问
> ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->

你这还没到证书那步呢

**Comment by AndersonGhost** [comment]
证书安装通过了啊   失败后  重新再安装一遍  就是这个提示了

**Comment by mack-a** [comment]
> 证书安装通过了啊 失败后 重新再安装一遍 就是这个提示了

重新安装也没到证书那一步呀，这不是刚输入完域名然后给的提示吗

**Comment by AndersonGhost** [comment]
是啊   是的   那现在是什么问题呢

**Comment by mack-a** [comment]
> 是啊 是的 那现在是什么问题呢

按照那个提示检查下，云朵、dns、防护墙什么的

**Comment by mack-a** [comment]
现在可以了吗

**Comment by AndersonGhost** [comment]
谢谢大佬，已成功！
