### ISSUE TITLE
2.5.19版本的grpc 客户端无论使用Qv2ray还是V2rayN都无法连接   退回2.5.10版本后grpc都可以使用

### ISSUE THREAD

**Issue by wzl0904** [mack-a/v2ray-agent#224]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
2.5.19版本grpc 客户端无论使用Qv2ray还是V2rayN都无法连接   退回2.5.10版本后grpc都可以使用
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```
Debian10

**6.安装的脚本版本**
2.5.19
```
#
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
是
```

**11.是否更换客户端后再次尝试**

```
是
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
是
```

**Comment by mack-a** [comment]
gRPC兼容性比较差，选择能用的脚本版本即可
