### ISSUE TITLE
生成的vmess链接clash for Windows 和clash for andriod都无法识别

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#229]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 如题，用这个脚本生成的vmess链接cfw和cfa都无法正常识别，会显示time out，用别的脚本生成的就可以
# 怀疑是ws path的中的“?ed=2048”部分包含了特殊符号“？”和“=”导致的
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是
```

**6.安装的脚本版本**

```
# 最新版 。从我开始用这脚本开始一直是这样
```

**7.安装类型**

- 个性化安装
**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VMESS+WS+TLS
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是，使用Clash.NET就可以正常读取
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
手动删除。?ed=2048。这个参数仅支持xray
