### ISSUE TITLE
希望卸载脚本时支持卸载Nginx

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#230]
**详细描述建议的内容**
如题，目前的卸载方式会保留Nginx，可能会导致卸载后无法使用其他同样的脚本安装v2ray等协议

希望能在卸载时增加“卸载Nginx（及配置）”的功能

**Comment by mack-a** [comment]
nginx没卸载，脚本生成的配置删除了。
如果卸载的时候卸载nginx会导致个人化的nginx配置删除
