### ISSUE TITLE
安装失败，错误信息如下，请参考

### ISSUE THREAD

**Issue by TerryHoCQ** [mack-a/v2ray-agent#232]
进度  7/17 : 安装Xray 
 ---> Xray-core版本: 
unzip:  cannot find or open /etc/v2ray-agent/xray/Xray-linux-64.zip, /etc/v2ray-agent/xray/Xray-linux-64.zip.zip or /etc/v2ray-agent/xray/Xray-linux-64.zip.ZIP.
chmod: cannot access ‘/etc/v2ray-agent/xray/xray’: No such file or directory

**Comment by mack-a** [comment]
现在还有吗 应该是核心下载失败了

**Comment by malikshi** [comment]
add argument to check wheter file is available after downloaded if it doesn't sucess then repeat once more to download it. for some reason vps from different ISP has bad connection to github in certain time, my speed download like 2-10Kb/s to github at 7-11 pm

**Comment by TerryHoCQ** [comment]
我手动下载文件传到安装目录解决的。目前很多vps访问github很不稳定
