### ISSUE TITLE
部署时ningx一定要80端口？

### ISSUE THREAD

**Issue by ramocky** [mack-a/v2ray-agent#233]
部署时ningx一定要80端口？

**Comment by mack-a** [comment]
脚本里面必须80，可以安装完自己改

**Comment by ramocky** [comment]
> 脚本里面必须80，可以安装完自己改

改alone.conf？还是default.conf

**Comment by mack-a** [comment]
> > 脚本里面必须80，可以安装完自己改
> 
> 
> 
> 改alone.conf？还是default.conf

第一个

**Comment by ramocky** [comment]
> > > 脚本里面必须80，可以安装完自己改
> > 
> > 
> > 改alone.conf？还是default.conf
> 
> 第一个

打扰了 我对ngnix 真不熟 然后要怎么指定这个配置启动？ nginx -c /etc/nginx/conf.d/alone.conf 提示  "server" directive is not allowed here in /etc/nginx/conf.d/alone.conf:1

**Comment by ramocky** [comment]
> > > 脚本里面必须80，可以安装完自己改
> > 
> > 
> > 改alone.conf？还是default.conf
> 
> 第一个
大佬大佬 方便回复吗

**Comment by ramocky** [comment]
> 脚本里面必须80，可以安装完自己改

大佬大佬方便回复吗
