### ISSUE TITLE
关于Trojan-gRPC-TLS

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [mack-a/v2ray-agent#235]
请问本脚本安装的Trojan-gRPC-TLS在openwrt有什么客户端支持连接？

**Comment by mack-a** [comment]
可以去相应的TG群里问一下

**Comment by mack-a** [comment]
![telegram-cloud-photo-size-5-6073170717203082698-y](https://user-images.githubusercontent.com/57424792/127990559-a3316b0c-5af2-4eaf-8842-ca96a3781030.jpg)
