### ISSUE TITLE
大佬你好，我也是想安装你的脚本之后，再安装宝塔面板+wordpress来搭建自己的博客，但是存在冲突

### ISSUE THREAD

**Issue by chengwei21** [mack-a/v2ray-agent#238]
大佬，我的安装过程如下
我的VPS是centos 7系统，我首先到宝塔官网（https://www.bt.cn/download/linux.html）找到centos安装的命令
yum install -y wget && wget -O install.sh http://download.bt.cn/install/install_6.0.sh && sh install.sh
安装完成后会出现宝塔面板的登陆网址，用户名和密码
![Inkedinstall-bt5_LI](https://user-images.githubusercontent.com/53066412/128619125-2499fc0f-acf3-4da6-a7ea-28ed332e5c10.jpg)
然后在浏览器输入相应的网址，就会出现登陆界面
![屏幕截图 2021-08-08 105038](https://user-images.githubusercontent.com/53066412/128619153-91b9c1c2-77b8-407a-a326-ee7245ebd122.png)
输入用户名和密码登陆进去之后，他会提示你安装LNMP
![v2-8f9d79517de6af4cc08edd8efcf3b87e_r](https://user-images.githubusercontent.com/53066412/128619174-4cd6d39f-4035-4c49-90d1-a492cdd8231c.jpg)
我选择的是LNMP的编译安装，安装的时间有点久，安装完成后选择添加站点，输入域名，并且创建FTP和数据库
![Inked屏幕截图 2021-08-08 100607_LI](https://user-images.githubusercontent.com/53066412/128619192-67e1510e-9de5-45fb-aa91-585a7f27e949.jpg)
然后选择文件，进入到网站的根目录，上传从wordpress官网（https://wordpress.org/）下载的压缩包，解压之后将wordpress文件夹里面的东西复制到网站根目录下
![1](https://user-images.githubusercontent.com/53066412/128619223-70637255-2bbf-421c-866e-4c236ddbac36.png)
![屏幕截图 2021-08-08 101134](https://user-images.githubusercontent.com/53066412/128619226-2ca8871d-099d-4f5d-8c39-23225eb66b4b.png)
然后点击站点，为站点生成ssl证书
![屏幕截图 2021-08-08 101309](https://user-images.githubusercontent.com/53066412/128619235-77d9c16e-fa5f-44d2-80bb-39dee80909cf.png)
![屏幕截图 2021-08-08 101404](https://user-images.githubusercontent.com/53066412/128619237-23a46ccd-f689-495a-a09b-304b2f67e0fa.png)
然后我关闭了服务器的防火墙，然后访问创建的域名，就进入到了wordpress安装页面
![屏幕截图 2021-08-08 102325](https://user-images.githubusercontent.com/53066412/128619250-456d7959-a147-4edc-b40d-00a0b46cc666.png)
宝塔+wordpress就差不多安装完了，然后我想安装大佬你的这个脚本，在安装的过程中，在检查Nginx是否正常访问的时候出现了问题
![屏幕截图 2021-08-08 103356](https://user-images.githubusercontent.com/53066412/128619284-5ae59977-5027-4f27-9b3f-f7c95b5bc677.png)
然后我也试过先安装大佬你的脚本，再安装宝塔面板，但是这样安装过后我修改不了网页上的内容，就是更改网站根目录下的文件后，网页上永远都只显示一个内容。我也在网上搜了一下，有的说可能是建的博客会占用80和443端口，所以导致不可以，我也在大佬你的其他issue里面看到了相关内容，但是不知道该怎样解决，所以非常希望大佬能够帮我这个小白解决一下这个冲突问题(*￣︶￣)

**Comment by mack-a** [comment]
感谢反馈，有时候我兼容下

**Comment by chengwei21** [comment]
麻烦大佬了o( ❛ᴗ❛ )o

**Comment by Happiness-in-Danger** [comment]
不是端口冲突,问题出在Nginx,网站用这个服务,脚本也用.即使走不同端口也是一样.

**Comment by chengwei21** [comment]
那就是说更改端口也不能解决这个冲突了，那要如何才能让脚本和宝塔能共用这个Nginx呀

**Comment by Happiness-in-Danger** [comment]
共用不了,疑似是进程问题.除非不用宝塔建站,手动建站,可能就能公用,宝塔不支持导入已搭建好的环境.

遇见只为远方 ***@***.***> 于2021年8月16日周一 下午10:10写道：

**Comment by ChellyL** [comment]
用另一个脚步可以兼容，但v2ray不能走443端口，我以前试过

**Comment by Happiness-in-Danger** [comment]
这个脚本是可以修改端口的。其他的我不清楚

ChellyL ***@***.***> 于 2021年8月25日周三 09:47写道：

**Comment by chengwei21** [comment]
> 用另一个脚本可以兼容，但v2ray不能走443端口，我以前试过
用哪个脚本兼容的呀?能不能分享一下😁😁

**Comment by chengwei21** [comment]
> 用另一个脚本可以兼容，但v2ray不能走443端口，我以前试过

用的是哪个脚本呀，能不能分享一下😁😁

**Comment by ChellyL** [comment]
> 
> 
> > 用另一个脚本可以兼容，但v2ray不能走443端口，我以前试过
> 
> 用的是哪个脚本呀，能不能分享一下😁😁

这个，你注意看下它选项容易给绕晕 https://github.com/jinwyp/one_click_script

**Comment by mack-a** [comment]
已移动到 https://github.com/mack-a/v2ray-agent/issues/76

**Comment by mack-a** [comment]
开始兼容

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.39 已更新beta1版本
