### ISSUE TITLE
域名ip检测无法通过，是否能更换检测方式

### ISSUE THREAD

**Issue by xuxianhe** [mack-a/v2ray-agent#239]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 域名解析无法通过，翻看脚本发现采用cloudflare-dns.com检测域名解析，而cloudflare-dns.com无法访问，造成无法继续安装。
域名解析用ping命令检查正常
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 

========================个性化安装============================
VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
0.VLESS+TLS/XTLS+TCP
1.VLESS+TLS+WS[CDN]
2.Trojan+TLS+gRPC[CDN]
3.VMess+TLS+WS[CDN]
4.Trojan
5.VLESS+TLS+gRPC[CDN]
请选择[多选]，[例如:123]:0
--------------------------------------------------------------
安装工具

进度  1/17 : 安装工具
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】
 ---> 安装binutils
 ---> 安装lsb-release
 ---> 安装semanage

进度  2/17 : 初始化Nginx申请证书配置

请输入要配置的域名 例：www.v2ray-agent.com --->
域名: *****

 ---> 配置Nginx

检查IP是否设置为当前VPS
 ---> 检查ipv4中
 ---> 检查ipv6中
IP查询失败，请检查域名解析是否正确，是否重试[y/n]？y
 ---> 检查ipv4中
 ---> 检查ipv6中
IP查询失败，请检查域名解析是否正确，是否重试[y/n]？n
root@iZbp11a1q9jzu92rik8jqvZ:~#
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
# ubuntu20.04
```

**6.安装的脚本版本**

```
# wget 方式获取的最新脚本
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# 0.VLESS+TLS/XTLS+TCP
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by xuxianhe** [comment]
后续：更换为 ping、ping6方式通过

**Comment by mack-a** [comment]
为什么无法访问

**Comment by xuxianhe** [comment]
> 为什么无法访问

各种情况都有可能啊，一个服务而已，怎么能靠这一个服务来检测域名解析呢

**Comment by xuxianhe** [comment]
建议将脚本中采用cloudflare-dns.com检测域名解析的部分，更换为ping、ping6方式

**Comment by mack-a** [comment]
> 建议将脚本中采用cloudflare-dns.com检测域名解析的部分，更换为ping、ping6方式

建议您那边排除下为啥不支持 cloudflare-dns.com

**Comment by xuxianhe** [comment]
> > 建议将脚本中采用cloudflare-dns.com检测域名解析的部分，更换为ping、ping6方式
> 
> 建议排除下为啥不支持 cloudflare-dns.com

我们无法去分析一个第三方服务为何无法访问，第三方服务出问题都是不可控的
有更可靠的方式为什么不用呢？
我只是给您建议，是否采用在您。

至于 cloudflare-dns.com 为啥不可用，真不是我能排除的，也没必要，我只是想正常使用脚本而已

**Comment by mack-a** [comment]
> > > 建议将脚本中采用cloudflare-dns.com检测域名解析的部分，更换为ping、ping6方式
> > 
> > 
> > 建议排除下为啥不支持 cloudflare-dns.com
> 
> 我们无法去分析一个第三方服务为何无法访问，第三方服务出问题都是不可控的
> 有更可靠的方式为什么不用呢？
> 我只是给您建议，是否采用在您。
> 
> 至于 cloudflare-dns.com 为啥不可用，真不是我能排除的，也没必要，我只是想正常使用脚本而已

下次不能用的时候 建议更换下脚本或者找到此脚本还在用ping工具的版本
