### ISSUE TITLE
填写域名后报错， 但是用其他脚本完美。

### ISSUE THREAD

**Issue by youcaiwang** [mack-a/v2ray-agent#24]

**Comment by mack-a** [comment]
请检查dns解析记录并在vps进行ping 检查域名的ip

**Comment by JoseStone5** [comment]
我这边也是同样的问题，trojan域名填进去一直不行

**Comment by mack-a** [comment]
> 我这边也是同样的问题，trojan域名填进去一直不行

是连接不上 还是安装不了哇 可以更新下脚本试试

**Comment by mack-a** [comment]
现在还有问题吗  @youcaiwang @JoseStone5

**Comment by mack-a** [comment]
Issues已关闭，如果有问题请重新打开。
