### ISSUE TITLE
TLS安装失败

### ISSUE THREAD

**Issue by xiaoxiaofeihh** [mack-a/v2ray-agent#243]
TLS安装失败，请检查acme日志 
![捕获](https://user-images.githubusercontent.com/83327561/129034211-54f5ba28-087a-46fe-8a1c-f8051c45f892.PNG)
![捕获1](https://user-images.githubusercontent.com/83327561/129034290-bfee152d-9a8f-4542-8d1c-9895a6aebbf6.PNG)
获取域名出现这种情况

**Comment by mack-a** [comment]
只有ipv6吗

**Comment by gogopotato** [comment]
看下是不是443端口没打开？ 有可能默认运营商是关闭的

**Comment by lynnF7ZcfS** [comment]
应该是 EUserv 的免费 IPv6 小鸡，试了下遇到了同样的问题。
log：https://paste.ubuntu.com/p/pyNm69T7gw/

acme.sh log 如下：
https://paste.ubuntu.com/p/vrhWKHxbwH/
看A大能不能帮到他...

**Comment by lynnF7ZcfS** [comment]
bash /root/.acme.sh/acme.sh --issue -d yourdomain.com --debug --standalone --keylength ec-256 --listen-v6

将yourdomain.com替换为你的域名，即可手动申请 ssl 证书

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.22 已修复

**Comment by lfxx** [comment]
> 1. use LE CA with acme.sh by using:--set-default-ca --server letsencrypt
> 2. bash /root/.acme.sh/acme.sh --issue -d yourdomain.com --debug --standalone --keylength ec-256 --listen-v6
>    （ 将yourdomain.com替换为你的域名，即可手动申请 ssl 证书 ）
> 3. 参考 [https://github.com/mack-a/v2ray-agent/blob/master/documents/install_tls.md](https://github.com/mack-a/v2ray-agent/blob/master/documents/install_tls.md?rgh-link-date=2021-08-12T03%3A20%3A18Z) 添加证书
> 4. Re-run vasma

大佬，这小鸡我也申请了个免费版叫vServer VS2-free v2.1，为啥审批这么慢。。
四天了还没通过
