### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by jtshushu** [mack-a/v2ray-agent#244]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#
```

进度  4/13 : 申请TLS证书
 
 ---> 安装TLS证书 
[Fri Aug 13 11:41:45 UTC 2021] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: abc.popcoypop.site: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Fri Aug 13 11:41:45 UTC 2021] Please add '--debug' or '--log' to check more details.
[Fri Aug 13 11:41:45 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Aug 13 11:38:13 UTC 2021] Single domain='abc.popcoypop.site'
[Fri Aug 13 11:38:13 UTC 2021] Getting domain auth token for each domain
[Fri Aug 13 11:38:15 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Aug 13 11:38:15 UTC 2021] Standalone mode.
[Fri Aug 13 11:38:15 UTC 2021] Single domain='abc.popcoypop.site'
[Fri Aug 13 11:38:15 UTC 2021] Getting domain auth token for each domain
[Fri Aug 13 11:41:44 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Aug 13 11:41:44 UTC 2021] Standalone mode.
[Fri Aug 13 11:41:44 UTC 2021] Single domain='abc.popcoypop.site'
[Fri Aug 13 11:41:44 UTC 2021] Getting domain auth token for each domain
 ---> TLS安装失败，检查防火墙中 
 ---> 重新尝试安装TLS证书 

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
too many certificates (5) already issued for this exact set of domains in the last 168 hours: abc.popcoypop.site: see https://letsencrypt.org/docs/rate-limits/",

too many了 换个子域名再试
