### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by malikshi** [mack-a/v2ray-agent#245]
Ubuntu 20.04

请选择:1

功能 1/1 : 选择核心安装

==============================================================
1.Xray-core
2.v2ray-core
==============================================================
请选择：1
安装工具

进度  2/13 : 安装工具
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】
 ---> 安装unzip
 ---> 安装socat
 ---> 安装binutils
 ---> 安装qrencode
 ---> 安装lsb-release
 ---> 安装nginx
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
 ---> 安装semanage
 ---> 安装acme.sh

进度  3/13 : 初始化Nginx申请证书配置

请输入要配置的域名 例：www.v2ray-agent.com --->
域名:mydomain.com

 ---> 检查域名ip中
 ---> 当前域名ip为：[139.99.105.185]

进度  4/13 : 申请TLS证书

 ---> 安装TLS证书
2021/08/13 23:07:05 socat[6143] E write(5, 0x5616c527cc70, 328): Broken pipe
2021/08/13 23:07:05 socat[6147] E write(5, 0x5616c527cc70, 327): Broken pipe
2021/08/13 23:07:05 socat[6139] E write(5, 0x5616c527cc70, 406): Broken pipe
2021/08/13 23:07:05 socat[6155] E write(5, 0x5616c527cc70, 328): Broken pipe
2021/08/13 23:07:05 socat[6156] E write(5, 0x5616c527cc70, 328): Broken pipe
2021/08/13 23:07:05 socat[6151] E write(5, 0x5616c527cc70, 403): Broken pipe
2021/08/13 23:07:05 socat[6163] E write(5, 0x5616c527cc70, 328): Broken pipe
2021/08/13 23:07:06 socat[6201] E write(5, 0x5616c527cc70, 329): Broken pipe
2021/08/13 23:07:06 socat[6205] E write(5, 0x5616c527cc70, 329): Broken pipe
2021/08/13 23:07:06 socat[6209] E write(5, 0x5616c527cc70, 204): Broken pipe
2021/08/13 23:07:06 socat[6217] E write(5, 0x5616c527cc70, 218): Broken pipe
2021/08/13 23:07:07 socat[6229] E write(5, 0x5616c527cc70, 226): Broken pipe
2021/08/13 23:07:07 socat[6283] E write(5, 0x5616c527cc70, 82): Broken pipe
2021/08/13 23:07:07 socat[6225] E write(5, 0x5616c527cc70, 226): Broken pipe
2021/08/13 23:07:07 socat[6287] E write(5, 0x5616c527cc70, 82): Broken pipe
2021/08/13 23:07:07 socat[6221] E write(5, 0x5616c527cc70, 201): Broken pipe
2021/08/13 23:07:07 socat[6279] E write(5, 0x5616c527cc70, 82): Broken pipe

**Comment by mack-a** [comment]
重新弄个系统再试试，或者把socat卸载重装

**Comment by malikshi** [comment]
Any plan to use certbot or acme with dns-cloudflare api? I didn't have issues when using dns cf api

**Comment by mack-a** [comment]
> Any plan to use certbot or acme with dns-cloudflare api? I didn't have issues when using dns cf api.
> 
> Since almost all services in your script using cloudflare cdn isn't worth to add dns api?

目前没考虑，那个步骤有些麻烦，也不是所有人都有cloudflare

**Comment by malikshi** [comment]
Okay then.
Socat problem doesn't affect script to get certs. I'm close the issues
