### ISSUE TITLE
添加doh的支持

### ISSUE THREAD

**Issue by ylx2016** [mack-a/v2ray-agent#246]
DNS-over-HTTPS需求
生成的路径建议随机生成或者默认 逻辑参考之前的生成规则 留空则随机生成路径 填入的话则不生成
此处路径和FQ路径分开
再深入可以配合AdGuard home去广告

**Comment by ylx2016** [comment]
默认公开路径为/dns-query

**Comment by mack-a** [comment]
已移动到https://github.com/mack-a/v2ray-agent/issues/76
