### ISSUE TITLE
重装脚本后核心无法启动

### ISSUE THREAD

**Issue by jh3274** [mack-a/v2ray-agent#247]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```重新安装服务后，核心无法启动
# 
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**
xray启动失败 
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 
root@instance20210527161417:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/arm64)
A unified platform for anti-censorship.
2021/08/19 09:25:30 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/08/19 09:25:30 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 31296 > transport/internet: failed to listen on address: 127.0.0.1:31296 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:31296 > listen tcp 127.0.0.1:31296: bind: address already in use

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
ubuntu20
- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#2.5.27
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
手动停止下trojan-go 或者直接重新安装个系统重新安装
