### ISSUE TITLE
域名无法获取ip

### ISSUE THREAD

**Issue by Neomanbeta** [mack-a/v2ray-agent#250]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
脚本第三部输入我VPS的域名以后，提示获取不到IP，从而导致失败。但是这个域名解析是正常到140.238.0.217的。
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
进度  3/13 : 初始化Nginx申请证书配置 

请输入要配置的域名 例：www.v2ray-agent.com ---> 
域名:oc1.neoman.cf

 ---> 检查域名ip中 

 ---> 未检测到当前域名的ip 
 ---> 请检查域名是否书写正确 
 ---> 请检查域名dns解析是否正确 
 ---> 如解析正确，请等待dns生效，预计三分钟内生效 
 ---> 如以上设置都正确，请重新安装纯净系统后再次尝试 
 ---> 检测返回值异常 
 ---> 请检查防火墙是否关闭
 
是否通过脚本关闭防火墙？[y/n]:

```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
用的是Debian11，所以没有重装Debian10去试。
```

**6.安装的脚本版本**

```
Latest
```

**7.安装类型**

-全部安装

**8.安装的核心版本**

```
# xray-core
```

**9.出现问题的协议类型**

```
# 没到这步就已经失败
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
检查下nginx，最好手动安装下试试

**Comment by Neomanbeta** [comment]
卸载nginx并清除所有残留以后再重装就能通过了，关闭issue。

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/130358179-dedf58db-8daf-4dee-8409-4fe8d1905bec.png)

**Comment by ChellyL** [comment]
我有出现了同样的情况，完整卸载nginx依然会出现此问题，估计只能重装解决。但我用了另外一个脚本，只要完全卸载nginx就能安装成功……为啥会这样啊

**Comment by mack-a** [comment]
> 我有出现了同样的情况，完整卸载nginx依然会出现此问题，估计只能重装解决。但我用了另外一个脚本，只要完全卸载nginx就能安装成功……为啥会这样啊

错误的返回值贴一下，就是那几行字 未找到ip那几个

**Comment by ChellyL** [comment]
> ---> 检查域名ip中 
> 
>  ---> 未检测到当前域名的ip 
>  ---> 请检查域名是否书写正确 
>  ---> 请检查域名dns解析是否正确 
>  ---> 如解析正确，请等待dns生效，预计三分钟内生效 
>  ---> 如以上设置都正确，请重新安装纯净系统后再次尝试 
>  ---> 请检查防火墙是否关闭
>  
> 是否通过脚本关闭防火墙？[y/n]:

和楼主的提示一样吧。我是之前安装成功过，然后想通过“任意组合安装”换下内核，就提示此错误。最后是完全卸载nginx后换了个脚本才安装成功的

**Comment by mack-a** [comment]
>  > ---> 检查域名ip中 
> 
> > 
> 
> >  ---> 未检测到当前域名的ip 
> 
> >  ---> 请检查域名是否书写正确 
> 
> >  ---> 请检查域名dns解析是否正确 
> 
> >  ---> 如解析正确，请等待dns生效，预计三分钟内生效 
> 
> >  ---> 如以上设置都正确，请重新安装纯净系统后再次尝试 
> 
> >  ---> 请检查防火墙是否关闭
> 
> >  
> 
> > 是否通过脚本关闭防火墙？[y/n]:
> 
> 
> 
> 和楼主的提示一样吧。我是之前安装成功过，然后想通过“任意组合安装”换下内核，就提示此错误。最后是完全卸载nginx后换了个脚本才安装成功的

仔细看 是不一样的

**Comment by mack-a** [comment]
建议如果下次出现这种情况可以把机器tg私聊给我

**Comment by ChellyL** [comment]
好的，主要是我那个机器跑了别的程序，不想重装，不然我就重装顺便升级debian11了
