### ISSUE TITLE
能否加入AdGuardHome解决dns污染问题

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#251]
https://github.com/AdguardTeam/AdGuardHome
脚本可否同时加入adguardahome以自建dns解决dns污染问题
感谢！

**Comment by mack-a** [comment]
国外也有dns污染吗

**Comment by fredericky123** [comment]
是这样，我不知道对adguardhome的理解是否正确：
我是在国内，但是自己的域名被个别运营商污染了，只有切换dns才可解析，所以想着在国外服务器上自建一个dns解析，以解决污染问题

**Comment by mack-a** [comment]
> 是这样，我不知道对adguardhome的理解是否正确：
> 
> 我是在国内，但是自己的域名被个别运营商污染了，只有切换dns才可解析，所以想着在国外服务器上自建一个dns解析，以解决污染问题

这个需要你在本地做就好 访问国内网站和vps没关系

**Comment by mack-a** [comment]
本地的话可以用114

**Comment by fredericky123** [comment]
我在网关那里改成114确实能生效，可是在qv2ray里设置成114，并勾选直连使用v2ray dns和dns拦截，依然无法访问域名，不知为何

**Comment by fredericky123** [comment]
另外不是考虑到adguard功能强大，可以找最快的解析，想着能不能把功能加进来，要是长期使用114，就不会被污染吗，全部使用114会不会有些解析变慢了，想同时用好几个dns

**Comment by mack-a** [comment]
这是你本地的问题呀，和vps没关系也就和脚本没关系

**Comment by mack-a** [comment]
国内域名直连，流量不走代理 dns解析是你本地完成的

**Comment by fredericky123** [comment]
好的吧 看来只能想办法手动更换本地dns解析地址了
感谢感谢
