### ISSUE TITLE
xray核心无法启动

### ISSUE THREAD

**Issue by jh3274** [mack-a/v2ray-agent#258]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```xray核心无法启动# 
```

**2.是否安装失败**
否
```
# 否
```

**3.是否重新build系统后尝试**
否
```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 否
```

**5.系统版本ubuntu20
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#最新
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
#全部
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**
 否

日志

root@instance-20210826-0711:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/arm64)
A unified platform for anti-censorship.
2021/09/02 22:02:54 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/09/02 22:02:54 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json

**Comment by mack-a** [comment]
没有别的日志了吗 没看到错误信息

**Comment by jh3274** [comment]
没有  卸载后 在top里面看到xray进程  kill以后 重新安装依旧无法打开
日志
2021/09/02 22:20:23 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/09/02 22:20:23 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
2021/09/02 22:20:43 195.146.37.241:64640 rejected  proxy/trojan: not trojan protocol

**Comment by jh3274** [comment]
另外一台同样问题的机器的日志
5.重启Xray-core 
============================================================== 
请选择：5
 ---> Xray关闭成功 
xray启动失败 
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 
root@debian:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/arm64)
A unified platform for anti-censorship.
2021/09/02 22:23:29 Using confdir from arg: /etc/v2ray-agent/xray/conf
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2021/09/02 22:23:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json

**Comment by mack-a** [comment]
systemctl stop trojan-go
systemctl disable trojan-go

**Comment by jh3274** [comment]
、
2台机器返回分别为
root@debian:~# systemctl stop trojan-go
Failed to stop trojan-go.service: Unit trojan-go.service not loaded.
root@debian:~# 
root@debian:~# systemctl disable trojan-go
Failed to disable unit: Unit file trojan-go.service does not exist.
root@debian:~# 
root@debian:~# 
root@instance-20210826-0711:~# systemctl stop trojan-go
Failed to stop trojan-go.service: Unit trojan-go.service not loaded.
root@instance-20210826-0711:~# systemctl disable trojan-go
Failed to disable unit: Unit file trojan-go.service does not exist.
root@instance-20210826-0711:~# 
root@instance-20210826-0711:~#

**Comment by jh3274** [comment]
安装stable版本
日志为
root      416595  401228  0 22:38 pts/0    00:00:00 grep --color=auto xray

**Comment by jh3274** [comment]
还有个问题是 xray核心启动失败 为什么trojan也无法使用。。。。。。

**Comment by mack-a** [comment]
用最新的脚本安装，不要用stable 那个版本我已经删掉了，实在不行重做系统重新安装。

**Comment by jh3274** [comment]
就是新脚本运行不动xray核心所以想换老脚本试试。。。现在看来只能重装系统解决了。。建议大佬以后可以考虑把脚本放到docker里面 搞个一键docker脚本 这样出问题清理起来比较方便
