### ISSUE TITLE
甲骨文云安装失败

### ISSUE THREAD

**Issue by cnm105** [mack-a/v2ray-agent#262]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

v2.5.32版本甲骨文云安装失败（域名解析正常）
# 

**2.是否安装失败**

是
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

---> 未检测到当前域名的ip 
 ---> 请检查域名是否书写正确 
 ---> 请检查域名dns解析是否正确 
 ---> 如解析正确，请等待dns生效，预计三分钟内生效 
 ---> 如以上设置都正确，请重新安装纯净系统后再次尝试 
 ---> 请检查防火墙是否关闭

# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
unbuntu
- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
甲骨文需要手动关闭防火墙
