### ISSUE TITLE
希望能改善一下自动申请证书功能

### ISSUE THREAD

**Issue by GitHub66666666** [mack-a/v2ray-agent#263]
**详细描述建议的内容**
好几次证书过期了，脚本申请一次失败就不再申请了，需要自己再手动申请，太不符合大佬您做这个脚本的价值观了。希望在证书过期前，添加多几次（间隔一段时间）自动申请的次数，实在失败了再提示手动吧。谢谢大佬！

**Comment by mack-a** [comment]
如果是早期版本，需要重新安装，如果是近期版本可以查看日志排查问题。
