### ISSUE TITLE
vless,ws,tls, cdn 无法连接上网。疑配置文件有误。（V2ray-agent 2.5.33 Xray 1.4.3 ） 

### ISSUE THREAD

**Issue by wangyubow** [mack-a/v2ray-agent#267]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 
# VLESS+WS[TLS] 无法上网。
# 但VLESS+TCP[TLS/XTLS] ，  VLESS+gRPC[TLS]上网正常。
# 疑似配置参数有误。

# 2021/09/16 18:24:24 [Warning] [50498786] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxxx.xxx/ws): 403 Forbidden > websocket: bad handshake

```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 没有安装错误。
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
# 客户端：Qv2ray 2.7.0：7000
# 客户端OS: ubuntu 20.04
# 服务器OS： ubuntu server 20.04
# 客户端Xray: Xray 1.4.3 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
```

**6.安装的脚本版本**

```
# V2ray-agent 2.5.33

```

**7.安装类型**

- 个性化安装
```
# 核心：Xray-core[运行中] 
# 已安装协议：VLESS+TCP[TLS/XTLS] VLESS+WS[TLS] VLESS+gRPC[TLS] 
```

**8.安装的核心版本**

```
# 服务器：当前Xray-core版本:1.4.3 
# 客户端：Xray 1.4.3 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
```

**9.出现问题的协议类型**

```
# VLESS+WS[TLS] 无法上网。
# ________________________________________________
# 但VLESS+TCP[TLS/XTLS] ，  VLESS+gRPC[TLS]上网正常。
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否

```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
# 客户端，Qv2ray-v2.7.0-linux-x64已经是最新版本。
```

**Comment by mack-a** [comment]
作者：mack-a
当前版本：v2.5.33
Github：https://github.com/mack-a/v2ray-agent
描述：八合一共存脚本
核心：Xray-core[运行中]
已安装协议：VLESS+TCP[TLS/XTLS] VLESS+WS[TLS] VLESS+gRPC[TLS]

Qv2ray
版本：2.7.0-pre2:6220

同时试了小火箭也没复现

**Comment by wangyubow** [comment]
今天重新运行script,  配置了012345。 VLESS+WS[TLS] 成功了。

QV2ray2.7.0:7000  ubuntu 20.04.
_________________________________
当前版本：v2.5.33 
Github：https://github.com/mack-a/v2ray-agent 
描述：八合一共存脚本
核心：Xray-core[运行中] 
已安装协议：VLESS+TCP[TLS/XTLS] VLESS+WS[TLS] Trojan+gRPC[TLS] VMess+WS[TLS] Trojan+TCP[TLS] VLESS+gRPC[TLS]

**Comment by wangyubow** [comment]
@mack-a
