### ISSUE TITLE
新版本脚本在申请证书那一步一直重复

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#268]
作者你好,在申请证书那一步一直不断重复.
脚本版本：v2.5.34
搬瓦工vps/Centos 7 x64

![2021-09-18_083948](https://user-images.githubusercontent.com/9279217/133866205-5b3e3c91-9e3c-4ea3-b131-165f6fef2d52.jpg)

**Comment by mack-a** [comment]
把机器通过tg私聊给我，我昨天也在找这个问题，我这还没复现。或者更新到最新的脚本再试试

**Comment by smdx** [comment]
哎..早上换Debian系统重新安装解决了，一直未能下定决心换系统这次出问题想了想还是重建算了。

**Comment by mack-a** [comment]
这次出这个问题的时候记得tg私聊我
