### ISSUE TITLE
最新脚本导致套CF不能正常工作

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#269]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
使用最新脚本（v2.5.36）安装后，使用套CF的方法无法正常工作。
例如，将Vless + ws 的一个配置中的ip地址改成icook.tw（或者其他cloudflare地址），导致无法链接，不能正常代理。
而使用v2.4.28等老版本时，上述操作可以正常代理。
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
是
```

**6.安装的脚本版本**

```
#
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.4]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
小火箭全部安装没发现问题
