### ISSUE TITLE
证书自动签发有点问题，一直无法正常运行。

### ISSUE THREAD

**Issue by anniextra** [mack-a/v2ray-agent#270]
今天是证书过期日，然后显性的网站已经无法连接，证书报错了。
但是用代码脚本的6选项，依然显示证书有效。

既然都是几个月验证一次，建议不要最后一天更新，可以提前三天更新好了。
另外，在文档里面没有看到单独的更新证书的脚本，

我最后是选择重新安装，然后一路继承原有配置，只有在生成证书那里，选择重新生成，才得以解决的。
按理说，我直接选择6，是不是也应该给出一个强制更新的选项，而不是直接自动验证完就退出。

**Comment by mack-a** [comment]
把你vps通过tg私聊给我

**Comment by mack-a** [comment]
如果不是最新版本的脚本会出现定时任务证书的问题

**Comment by mack-a** [comment]
可以将这个log贴一下，/etc/v2ray-agent/crontab_tls.log

**Comment by mack-a** [comment]
> 我也遇到同样问题 今天发现证书过期了。
> 
> 我升级到最新脚本，尝试重新安装，报nginx 启动失败。
> 
> ```bash
> 
> `nginx: [emerg] open() "/etc/nginx/modules-enabled/50-mod-http-image-filter.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:4
> 
> `
> 
> ```
> 
> 系统是ubuntu20.4 应该挺新的

这个是nginx版本太老导致的，需要手动卸载nginx再用脚本安装
