### ISSUE TITLE
2.5.36版的VLESS_WS和VMESS_WS的path输出错误

### ISSUE THREAD

**Issue by gxhunter1982** [mack-a/v2ray-agent#271]
**1.描述出现的问题**

```
vless的ws模式一直连不上，后来查看配置文件，发现配置文件里的patch和最后显示的设置不同。
安装时随机路径设置的是testws（再次尝试时改用xrayws时复现）

vless_ws的配置文件里，patch是testwsws
而最后显示输出的是testws?ed=2048
“?ed=2048”是xray的0rtt设置。这个我知道，忽略掉这点，区别就是

配置文件里是testwsws
而显示输出和链接是testws

vmess的错误类似
配置文件里是testwsvws
而显示输出和链接是testvws



试验了几次，发现只要随机路径最后带ws的，都能触发此问题
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
否
```

**4.安装失败的错误内容或者截图**

```
无
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

Centos8

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
2.5.36
```

**7.安装类型**

全部安装

**8.安装的核心版本**

```
xray-core[1.4.5]
```

**9.出现问题的协议类型**

```
VLESS_WS
VMESS_WS
```

**10.尝试重装后是否100%复现**

```
只要随机路径末尾是ws，问题就能复现。

```

**11.是否更换客户端后再次尝试**

```
否
```

**12.是否将客户端升级最新进行尝试**

```
否，已是最新版。
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
卸载脚本后重装过，一样如此。
系统没有DD过。
```

**Comment by mack-a** [comment]
不是bug，脚本就是这样，建议随机path

**Comment by gxhunter1982** [comment]
问题是，如果随机时最后的字母碰巧是ws，也会触发这个问题。

**Comment by mack-a** [comment]
> 问题是，如果随机时最后的字母碰巧是ws，也会触发这个问题。

那你手动输入不要出现ws
