### ISSUE TITLE
failed to process outbound traffic

### ISSUE THREAD

**Issue by simplysexyboy** [mack-a/v2ray-agent#272]
你好

我在用你的Script 安装ubuntu 20.04服务器。经常可以用 但是有时候我连到 ads.tiktok.com 直接断网出这个问题

2021/09/30 22:57:01 [Warning] [3859358714] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [dial tcp 173.82.134.79:443: i/o timeout !dial tcp IPADDRESS:443: operation was canceled dial tcp: operation was canceled] > common/retry: all retry attempts failed

然后v2ray自己再连一次可以上那个网站了 你知道什么原因吗？

谢谢

![12](https://user-images.githubusercontent.com/74426831/135481109-993f4bb9-ccc3-4c20-ae5f-ebe236f46824.png)
![133](https://user-images.githubusercontent.com/74426831/135481114-5c7eee73-8924-46da-b650-e16f39bb4ae0.png)
![15](https://user-images.githubusercontent.com/74426831/135481116-fb1988e2-d9f5-45ee-82a9-0b10f1bf3521.png)
![16](https://user-images.githubusercontent.com/74426831/135481119-3c5062da-d103-4152-90a9-131fe7682a40.png)
![123123](https://user-images.githubusercontent.com/74426831/135481123-007ca7af-2586-4b0f-a2d8-457d077c3225.png)

**Comment by mack-a** [comment]
断流了

**Comment by simplysexyboy** [comment]
怎么解决呀？

**Comment by simplysexyboy** [comment]
我换了端口还是一样的问题 ,sa那天都没解决！

2021/10/01 21:24:44 [Warning] [4107543874] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp xxx:9999: operation was canceled dial tcp: operation was canceled] > common/retry: all retry attempts failed
