### ISSUE TITLE
arm64安装warp失败

### ISSUE THREAD

**Issue by ly012** [mack-a/v2ray-agent#274]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

arm64安装warp失败

**2.是否安装失败**
是

**3.是否重新build系统后尝试**

是

**4.安装失败的错误内容或者截图**

WARP未安装，是否安装 ？[y/n]:y
 ---> 安装WARP 
 ---> 安装WARP失败 

**5.系统版本【例：Debian10】**

Ubuntu 20.04

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**
v2.5.36

**7.安装类型**

WARP分流

**8.安装的核心版本**

**9.出现问题的协议类型**

**10.尝试重装后是否100%复现**

**11.是否更换客户端后再次尝试**

**12.是否将客户端升级最新进行尝试**

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

**Comment by mack-a** [comment]
手里没没ARM机器没办法测试
