### ISSUE TITLE
因Let‘s Encrypt根证书9月30号过期，而导致所有机器无法上网

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#275]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
如果所述，因Let‘s Encrypt根证书9月30号过期，而导致所有机器无法上网。该问题如何快速解决？
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
删除acme重新执行脚本即可

**Comment by mack-a** [comment]
rm -rf ~/.acme

**Comment by AndersonGhost** [comment]
如果这样，那不是所有的机器都得重装一遍呀，V2rayN里面所有的配置都得删除了o(╯□╰)o

**Comment by AndersonGhost** [comment]
好像有一种快速解决的办法：将V2rayN之前的“跳过证书验证”从false 改成 ture 就可以全部正常代理了
