### ISSUE TITLE
卡在检查IP是否设置为当前VPS

### ISSUE THREAD

**Issue by kobehuanghai** [mack-a/v2ray-agent#28]
用的azure，安装进程卡在检查IP是否设置为当前VPS

**Comment by mack-a** [comment]
> 用的azure，安装进程卡在检查IP是否设置为当前VPS

打开可ping

**Comment by kobehuanghai** [comment]
> > 用的azure，安装进程卡在检查IP是否设置为当前VPS
> 
> 打开可ping

收到，感谢
