### ISSUE TITLE
求助nginx高手，大大脚本生成的alone.conf里，怎么添加auth_basic，实现用户名密码登录啊？

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#280]
**详细描述建议的内容**
我以前都习惯在nginx里添加auth_basic，来实现用户名密码登录我的网页
```
auth_basic "Please input password";
auth_basic_user_file /etc/nginx/conf.d/passwd; 
```
但用了大大的脚本，我在alone.conf里添加auth_basic，实现不了原来的效果了。。。
大大是用`return 301 https:`来实现https访问的，这个auth_basic我不知道怎么加了。。。
请问可以实现吗？求助！

**Comment by mack-a** [comment]
加到下面得端口上面应该是3开头的，你可以都加上试试

**Comment by Se7enMuting** [comment]
哦，可以了。
我本来加到`listen 127.0.0.1:3**** http2;`后面没有效果，没看到下面还有个3开头的，现在加到最下面那个3开头的就可以了，感谢
