### ISSUE TITLE
trojan ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#281]
**1.描述出现的问题**
trojan协议出现 ERR_SSL_PROTOCOL_ERROR
是哪里的配置有问题吗
**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**
![image](https://user-images.githubusercontent.com/13982749/138022272-aa5da39d-a41c-46cd-a942-0621b62f55ba.png)

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
ubuntu
- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
2.5.36
```

**7.安装类型**

全部安装

**8.安装的核心版本**

```
# xray-core[1.4.5]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by fredericky123** [comment]
有些网站比如谷歌能打开，时而又打不开

**Comment by fredericky123** [comment]
是改了某个配置后能打开，然鹅我不记得修改的啥能打开谷歌了，打开谷歌的同时，gitHub却打不开，同一个服务器v2ray正常

**Comment by mack-a** [comment]
上面有测试方案呀，先换客户端排除节点问题

**Comment by mack-a** [comment]
> haoba，换了客户端trojan还是不通，看来真是节点，放弃了

你这个看着像 是服务端alpn的问题，你改过吗
