### ISSUE TITLE
能否支持vmess+grpc?

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#282]
**详细描述建议的内容**
clash是少有的支持grpc的客户端，可惜不支持vless，不过clash支持vmess+grpc,本脚本能否也支持vmess+grpc？

**Comment by mack-a** [comment]
理论上是可以的

**Comment by fredericky123** [comment]
请问你常用的客户端有哪些，尤其是支持grpc的？感谢分享~我可以帮助测试VMess+gRPC
如果大佬想尝鲜clash的话，测试应该也很方便
