### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by fys666** [mack-a/v2ray-agent#291]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

**```> 

我本地是有ipv6的（笔记本手机热点）
伪装站也有了，ipv4也能访问伪装站了，就是脚本生成的链接用不了，比如 VMess WS TLS CDN 。给了一个 ---> 通用vmess(VMess+WS+TLS)链接 。我就是用不了，防火墙也关了，我是纯IPV6的服务器（euserv），不知道咋办了，我就想用它做个T子，麻烦了**
# 
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
是
```

**4.安装失败的错误内容或者截图**

```
![QQ截图20211104225749](https://user-images.githubusercontent.com/55824187/140338319-efe3de3c-5af1-4e8c-8f84-fb6aa2ed79bc.png)

```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

Centos7


- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#最新的
```

**7.安装类型**

全部安装

**8.安装的核心版本**

```
# v2ray-core最新的
```

**9.出现问题的协议类型**

```
# VMess WS TLS CDN 
```

**10.尝试重装后是否100%复现**

```
是
```

**11.是否更换客户端后再次尝试**

```
是
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

 否
```

**Comment by mack-a** [comment]
本地没ipv6没办法测试ipv6的问题，建议开云朵使用ipv4
