### ISSUE TITLE
添加新端口后，如何使新端口生效

### ISSUE THREAD

**Issue by vllv** [mack-a/v2ray-agent#292]
由于脚本默认端口443 被封，利用脚本内11.添加新端口  添加了一个新端口 10887(02_dokodemodoor_inbounds_10887.json)
不过利用tcp ping工具，发现该端口，并没有生效，纯IP 可以ping 通
请问还需要做什么操作，才能让新端口生效。

**Comment by mack-a** [comment]
添加玩立即失效的
