### ISSUE TITLE
脚本不支持系统

### ISSUE THREAD

**Issue by dario-github** [mack-a/v2ray-agent#294]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 本脚本不支持此系统，请将下方日志反馈给开发者
 
Ubuntu 16.04.7 LTS 
 \l 
Linux version 4.15.0-142-generic (buildd@lgw01-amd64-039) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 系统版本不适配，未安装
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
# https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# None
```

**9.出现问题的协议类型**

```
# None
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
这个版本 脚本不支持，请升级高版本系统
