### ISSUE TITLE
发现很久了。。。splice的节点备注一直是VLESS_XTLS/TLS-direct_TCP 

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#295]
强迫症每次都要手动把direct改成splice，以为会修，发现一直没修
所以强伯症的我来发个issue试试。。。

**Comment by mack-a** [comment]
截个图看一下

**Comment by Se7enMuting** [comment]
![image](https://user-images.githubusercontent.com/889925/140648599-cc11684b-adfd-4a23-bf94-c07093fc5db0.png)

**Comment by mack-a** [comment]
修了
