### ISSUE TITLE
版本v2.5.38在centos 7下 第一次安装nginx 无法正常启动

### ISSUE THREAD

**Issue by JeffesJiang** [mack-a/v2ray-agent#297]
![image](https://user-images.githubusercontent.com/43066752/141045312-acbaded9-e9cc-44f3-afd3-c24ce06284f7.png)
提示31032端口无法绑定

**Comment by JeffesJiang** [comment]
nginx服务无法正产刚启动导致订阅服务无法正常运行

**Comment by JeffesJiang** [comment]
伪装站点也无法访问

**Comment by 2ndMessiah** [comment]
selinux

**Comment by JeffesJiang** [comment]
> selinux

重新安装就好了，只不过我测试了只要没有使用过脚本的机子，第一次安装都有问题，在此使用脚本重新安装就可以使用了。

**Comment by mack-a** [comment]
换debian试试

**Comment by JeffesJiang** [comment]
> 换debian试试

测试了vultr的debian11 没有问题
