### ISSUE TITLE
提示TLS安装失败是什么情况？

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#30]
进度  4/17 : 申请TLS证书
 ---> 安装TLS证书
[Fri Nov 13 07:21:32 EST 2020] 我的域名:Verify error:Fetching http://我的域名/.well-known/acme-challenge/sM7R-jOC2LuuBM-aeGNbrS2LkkmoX6l6cCs97iyU6fQ: Error getting validation d                                                   ata
[Fri Nov 13 07:21:32 EST 2020] Please add '--debug' or '--log' to check more details.
[Fri Nov 13 07:21:32 EST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/我的域名_ecc/fullchain.cer: No such file or directory
 ---> TLS安装失败，请检查acme日志

刚申请的域名，在vps已经能ping通了

**Comment by mack-a** [comment]
检查一下防火墙和80端口是是否开放

**Comment by mack-a** [comment]
> 进度  4/17 : 申请TLS证书
> 
>  ---> 安装TLS证书
> 
> [Fri Nov 13 07:21:32 EST 2020] 我的域名:Verify error:Fetching http://我的域名/.well-known/acme-challenge/sM7R-jOC2LuuBM-aeGNbrS2LkkmoX6l6cCs97iyU6fQ: Error getting validation d                                                   ata
> 
> [Fri Nov 13 07:21:32 EST 2020] Please add '--debug' or '--log' to check more details.
> 
> [Fri Nov 13 07:21:32 EST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
> 
> cat: /root/.acme.sh/我的域名_ecc/fullchain.cer: No such file or directory
> 
>  ---> TLS安装失败，请检查acme日志
> 
> 
> 
> 刚申请的域名，在vps已经能ping通了
> 
> 

检查一下防火墙和80 443端口是是否开放

**Comment by smdx** [comment]
> > 进度  4/17 : 申请TLS证书
> > ---> 安装TLS证书
> > [Fri Nov 13 07:21:32 EST 2020] 我的域名:Verify error:Fetching [http://我的域名/.well-known/acme-challenge/sM7R-jOC2LuuBM-aeGNbrS2LkkmoX6l6cCs97iyU6fQ](http://%E6%88%91%E7%9A%84%E5%9F%9F%E5%90%8D/.well-known/acme-challenge/sM7R-jOC2LuuBM-aeGNbrS2LkkmoX6l6cCs97iyU6fQ): Error getting validation d                                                   ata
> > [Fri Nov 13 07:21:32 EST 2020] Please add '--debug' or '--log' to check more details.
> > [Fri Nov 13 07:21:32 EST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
> > cat: /root/.acme.sh/我的域名_ecc/fullchain.cer: No such file or directory
> > ---> TLS安装失败，请检查acme日志
> > 刚申请的域名，在vps已经能ping通了
> 
> 检查一下防火墙和80 443端口是是否开放

感谢，防火墙开放80 443后成功了
