### ISSUE TITLE
甲骨文arm Ubuntu20机安装的trojan不可用

### ISSUE THREAD

**Issue by Jacobax** [mack-a/v2ray-agent#302]
**1.描述出现的问题**
其它协议正常，两个trojan连不上，当前最新脚本版本
之前也是用这个脚本（不同版本）使用正常，重新安装失败，卸载脚本且重启后重新安装脚本，安装过程一切正常
![IMG_20211123_180338.jpg](https://user-images.githubusercontent.com/23228895/143005893-07e5286d-0ac4-4d84-8d7e-bb7bf5eac9bb.jpg)
![IMG_20211123_180249.jpg](https://user-images.githubusercontent.com/23228895/143005925-4cd5ca78-8c0f-4245-b03d-1d677357bab1.jpg)

**Comment by mack-a** [comment]
换个客户端试试，还有不是所有的协议都能在不更改alpn的情况下正常使用

**Comment by Jacobax** [comment]
> 换个客户端试试，还有不是所有的协议都能在不更改alpn的情况下正常使用

试了在v2rayng上可以连通，在推荐的anxray和原sagernet连不上

**Comment by mack-a** [comment]
> > 换个客户端试试，还有不是所有的协议都能在不更改alpn的情况下正常使用
> 
> 试了在v2rayng上可以连通，在推荐的anxray和原sagernet连不上

已删除推荐选项
