### ISSUE TITLE
无法检测域名的ip

### ISSUE THREAD

**Issue by Happiness-in-Danger** [mack-a/v2ray-agent#305]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的
![EA27140E-079B-4648-A940-2231500D2A73](https://user-images.githubusercontent.com/45912561/143561845-d8f938ab-7e35-4ff4-9d8c-d538e203f623.png)

```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**

Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否
```

**6.安装的脚本版本**

```
#
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 否
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否

我已经改成root去运行了但是还是不行，域名已经和ip绑定了，ping通的

**Comment by mack-a** [comment]
按照提示挨个检查

**Comment by Happiness-in-Danger** [comment]
80和443都放行了，解析也是对的，但是就是不行 @mack-a

**Comment by mack-a** [comment]
重新dd个系统，保证纯净

**Comment by Happiness-in-Danger** [comment]
> 重新dd个系统，保证纯净

解决了，控制台里面没有放行端口。我一直在主机里面操作
