### ISSUE TITLE
关于宝塔安装脚本启用TLS的疑问

### ISSUE THREAD

**Issue by Plus-xu** [mack-a/v2ray-agent#313]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

宝塔安装本脚本后在<<脚本功能介绍>>Nginx配置文件目录`/etc/nginx/conf.d/alone.conf`中未找到此配置文件，文件管理器中搜索后，在`/www/server/panel/vhost/nginx/alone.conf`查找到，但文件中只有grpc回落端口的设置，没有443端口设置，并且在端口监听部分也没有开启ssl的设置。我在`/etc/v2ray-agent/xray`文件夹中查找相关设置json，也没有看到有关启用ssl的代码。在宝塔面板安装的默认nginx设置中，并没有对于443和80端口的相关默认设置。如果没有开启ssl，那么我们在使用代理软件用设置好的grpc+tls协议传输过程中，是不是没有启用tls加密呢？如果没有，应该如何设置ssl开启tls呢？谢谢~

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 否
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否，CentOS 7.9.2009
```

**6.安装的脚本版本**

```
#最新版v2.5.41
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.5.0]
```

**9.出现问题的协议类型**

```
# Trojan+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 否
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by mack-a** [comment]
脚本中的协议可以使用代表tls正常，443端口是由xray处理，其余的都是回落
