### ISSUE TITLE
小白被 `?ed=2048` 这个 path 后缀坑了一把。。。

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#315]
重装系统，把原先的 UUID 和 path 值记录下来，想新装的V2沿用原先的参数（客户端比较多，懒得一个个改了），记录值来自脚本的帐号管理的输出，path 是 `abcd?ed=2048`，以为这都是随机数。。。结果自然是悲剧，查了半天才发现有0-RTT这回事。
问题是 path 手动输入 `abcd?ed=2048`，但是脚本最后账号输出的还是：`abcd?ed=2048`，而不是：`abcd?ed=2048?vws?ed=2048`，这算不算小 bug？因为一直没注意（忘记）path后缀的事情，这里看到我输入和输出是一样的，自然觉得 path 没问题。。。
建议：
在手动输入 path 时加个提示，不要输入 URI 保留字（`!#$&'()*+,/:;=?@[]`），如果能做个检查提示输入错误最好了。。。

**Comment by mack-a** [comment]
脚本查看账号都写了
