### ISSUE TITLE
无法使用cloudflare自选ip

### ISSUE THREAD

**Issue by la0wei** [mack-a/v2ray-agent#316]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 客户端中的服务器地址使用自选ip无法连接。使用VLESS WS TLS CDN 直连可以使用 
```

**2.是否安装失败**
```
#否
```
**3.是否重新build系统后尝试**
```
#是
```
**4.安装失败的错误内容或者截图**
```
#无
```
**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
debian11 64bit
- 是否更换Debian10系统后再次安装
```
#否
```
**6.安装的脚本版本**

```
#当前版本：v2.5.41
```

**7.安装类型**
```
#全部安装
```
**8.安装的核心版本**

```
#xray-core[1.4.5] (服务器)，  v2rayN 4.25 xray-core[1.4.5] (windows客户端)
```

**9.出现问题的协议类型**

```
# VLESS WS TLS CDN
```

**10.尝试重装后是否100%复现**

```
 #是
```

**11.是否更换客户端后再次尝试**

```
#是
```

**12.是否将客户端升级最新进行尝试**

```
#是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
#否
```
cf配置：打开websocket，ssl为严格，关闭云朵。ping域名直接得到服务器ip

v2rayN客户端，日志中ip地址为cf自选ip
2021/12/07 15:50:27 [Warning] core: Xray 1.4.5 started
2021/12/07 15:50:33 tcp:127.0.0.1:1864 accepted tcp:www.youtube.com:443 [socks -> proxy]
2021/12/07 15:50:33 [Warning] [1349905333] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.41.56/alonews):  > remote error: tls: handshake failure
2021/12/07 15:50:44 tcp:127.0.0.1:1871 accepted tcp:www.youtube.com:443 [socks -> proxy]
2021/12/07 15:50:44 [Warning] [2131156918] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.41.56/alonews):  > remote error: tls: handshake failure

主机端日志：
2021/12/06 23:50:30 [Info] [4121780624] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > websocket: close 1006 (abnormal closure): unexpected EOF
2021/12/06 23:50:30 [Info] [4121780624] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/12/06 23:50:30 [Info] [3286422524] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp 服务器ip:443->117.136.66.127:6523: read: connection reset by peer
2021/12/06 23:50:30 [Info] [3286422524] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 服务器ip:443->117.136.66.127:6523: write: broken pipe
2021/12/06 23:50:30 [Info] [3822676917] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > websocket: close 1006 (abnormal closure): unexpected EOF

以前不需要特殊设置，只要在v2rayN中将服务器地址替换为自选ip即可，但是这个新装的xray无法实现。由于原可以使用的服务器已注销，无法比较。

**Comment by la0wei** [comment]
![可用直连配置](https://user-images.githubusercontent.com/3761308/144992187-eaf0aa7b-690e-418b-a3d6-dc01eb25c39f.png)

**Comment by AndersonGhost** [comment]
大佬，目前这个问题解决了吗？如何解决的？

**Comment by la0wei** [comment]
> 大佬，目前这个问题解决了吗？如何解决的？

和脚本应该没有关系，我申请了另一个cloudflare帐号，添加了新域名，基本没有修改东西，直接就成功了。可能以前在cloudflare修改了什么东西，但是没有找出来具体修改的项目。

**Comment by AndersonGhost** [comment]
> > 大佬，目前这个问题解决了吗？如何解决的？
> 
> 和脚本应该没有关系，我申请了另一个cloudflare帐号，添加了新域名，基本没有修改东西，直接就成功了。可能以前在cloudflare修改了什么东西，但是没有找出来具体修改的项目。

我的情况跟您一样：以前不需要特殊设置，只要在v2rayN中将服务器地址替换为自选ip即可，并且在安装Xray的时候没有进行任何CF的设置，安装完成后替换服务器地址为自选ip可以正常进行上网，现在不能这样操作了。

**Comment by WinRec** [comment]
首先要确定自选ip是可用的, 有很多cf的ip是被屏蔽的. 用cloudflareST找一些可用的ip多试试.

原先能用, 一段时间后不能用, 多半是ip被屏蔽. cf的ip会不停被屏蔽, 需要时不时换一下ip.
