### ISSUE TITLE
微软云使用网络跳越(hijk)的脚本可以正常安装

### ISSUE THREAD

**Issue by Mochongli** [mack-a/v2ray-agent#318]
先用hijk安装再使用v2ray-agent脚本提示解析IP错误
先使用v2ray-agent 443端口开放失败

**Comment by Mochongli** [comment]
[https://github.com/Mochongli/-/blob/main/26.jpg?raw=true](url)
[https://github.com/Mochongli/-/blob/main/27.jpg?raw=true](url)

**Comment by mack-a** [comment]
没有微软云无法排查
