### ISSUE TITLE
ipv6 only vps安装脚本后 ping命令默认强制优先ipv4,且无法通过gai.conf修改优先级

### ISSUE THREAD

**Issue by NinjaUmbra** [mack-a/v2ray-agent#322]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
ipv6 only vps安装脚本后 ping命令默认强制ipv4, 卸载脚本后,仍然出现这个情况,导致机子无法正常使用
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
是
```

**4.安装失败的错误内容或者截图**

```
无
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
Debian11
```

**6.安装的脚本版本**

```
2.5.45
```

**7.安装类型**

```
个性化安装
```

**8.安装的核心版本**

```
xray-core[1.5.2]
```

**9.出现问题的协议类型**

```
VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
是
```

**11.是否更换客户端后再次尝试**

```
是
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
否
```

**Comment by NinjaUmbra** [comment]
主要表现为 卸载脚本后 ping命令无法正常ping ipv6 还是一直ping ipv4 如果进一步卸载warp ipv6 vps就会报错 ping: unknown host
预期行为为 ping命令既可以ping v4 也可以v6 且可以通过gai.conf修改优先级

**Comment by mack-a** [comment]
脚本不会更改ping，脚本中也没用到ping，如有问题请更换其他脚本

**Comment by mack-a** [comment]
有空修
