### ISSUE TITLE
Latest Version脚本任意组合安装后，VLESS+XTLS+TCP和VLESS+TLS+WS无法使用。

### ISSUE THREAD

**Issue by LeiD215** [mack-a/v2ray-agent#324]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 任意组合安装，Xray-core，0135，全程没有错误提示。0.VLESS+TLS/XTLS+TCP和1.VLESS+TLS+WS[CDN]生成的连接无法使用。可以正常连接后，但是无法打开谷歌。3.VMess+TLS+WS[CDN]和5.VLESS+TLS+gRPC[CDN]生成的连接可以正常使用。
```

**2.是否安装失败**

```
# 否
```

**3.是否重新build系统后尝试**

```
# 重装系统后尝试依然失败。
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
#使用的系统就是Debian10
```

**6.安装的脚本版本**

```
#Latest Version
```

**7.安装类型**

- 个性化安装

**8.安装的核心版本**

```
# xray-core[1.5.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS/XTLS+TCP、VLESS+TLS+WS
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# WIN10系统，一直使用Qv2ray，出现错误后使用v2rayN，错误一样。
```

**12.是否将客户端升级最新进行尝试**

```
# v2rayN尝试升级最新版，错误一样。
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```

**Comment by mack-a** [comment]
云朵关掉，仔细看脚本README
