### ISSUE TITLE
升级v2ray内核或选择安装v2内核时会提示「V2Ray启动失败」

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#327]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
如题，选择内核管理→升级内核，升级v2内核后会提示重启失败；重新安装时选择v2内核也同样报错
```

**2.是否安装失败**

```
是
```

**3.是否重新build系统后尝试**

```
是，换了台没安装过v2的机器安装同样
```

**4.安装失败的错误内容或者截图**

![图片](https://user-images.githubusercontent.com/38887991/147929654-c1fed268-93f5-4287-880f-ae2113a6579a.png)

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
使用的Debian11
```

**6.安装的脚本版本**

```
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
v2ray 5.0.1
```

**9.出现问题的协议类型**

```
vmess+ws
```

**10.尝试重装后是否100%复现**

```
是
```

**11.是否更换客户端后再次尝试**

```
# 否
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
是
```

不知道是不是和“自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。”  (https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6)  有关，
我改用xray可正常启动

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.47
