### ISSUE TITLE
大佬，我用V2RAYn连接以后，报错日志出现这个，请问怎么解决呢？谢谢大佬

### ISSUE THREAD

**Issue by luoyouyu520** [mack-a/v2ray-agent#328]
**详细描述建议的内容**
2022/01/05 18:24:20 [Warning] [1110637063] github.com/xtls/xray-core/v1/app/proxyman/outbound: failed to process outbound traffic > github.com/xtls/xray-core/v1/proxy/vless/outbound: failed to find an available destination > github.com/xtls/xray-core/v1/common/retry: [dial tcp: operation was canceled] > github.com/xtls/xray-core/v1/common/retry: all retry attempts failed

**Comment by mack-a** [comment]
如不影响使用可忽略
