### ISSUE TITLE
无法删除端口

### ISSUE THREAD

**Issue by ArickV3** [mack-a/v2ray-agent#329]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
无法删除端口

**2.是否安装失败**

否

**3.是否重新build系统后尝试**

是

**4.安装失败的错误内容或者截图**

删除端口时提示如下
请输入要删除的端口编号：1
rm: cannot remove '/etc/v2ray-agent/v2ray/conf//02_dokodemodoor_inbounds_2033.json'$'\n''02_dokodemodoor_inbounds_2005.json'$'\n''02_dokodemodoor_inbounds_2002.json'$'\n''02_dokodemodoor_inbounds_1566.json'$'\n''02_dokodemodoor_inbounds_2758.json': No such file or directory

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装
Debian10
更换过Centos7

**6.安装的脚本版本**

版本：v2.5.46 

**7.安装类型**

全部安装

**8.安装的核心版本**

核心：v2ray-core[运行中] 
```

**9.出现问题的协议类型**

```
已安装协议：VLESS+TCP[TLS] VLESS+WS[TLS] VMess+WS[TLS] Trojan+TCP[TLS] VLESS+gRPC[TLS] 
```

**10.尝试重装后是否100%复现**

```
有几率出现，比如开10个端口，可能会有1-2个无法删除
```

**11.是否更换客户端后再次尝试**

```
是
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
是
```

**Comment by mack-a** [comment]
此问题没复现
