### ISSUE TITLE
关于底层传输安全的选择问题

### ISSUE THREAD

**Issue by kimuxer** [mack-a/v2ray-agent#331]
大佬你好，感谢你的脚本
安装过程没有问题
选择的是vless+xtls-rprx-direct
使用自动生成的分享链接导入v2rayN
底层传输安全默认是xtls，但是无法打开网页，切换到tls就没问题
我没有修改过任何一个配置文件
我也不知道这是BUG还是只能选择tls，或者是哪里还需要设置一下，求大佬解惑
系统是debian 11

**Comment by mack-a** [comment]
用xray
