### ISSUE TITLE
Nginx重新开机后无法启动

### ISSUE THREAD

**Issue by TonyLCH** [mack-a/v2ray-agent#335]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
重新开机后无法启动nginx,使用apt remove nginx命令删除nginx后再使用脚本安装nginx也无法启动导致重装xray失败需要重装系统才能启动nginx,一旦重新开机就关掉nginx无法启动
vps:euserv纯ipv6
系统:Debian11
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
是
```

**4.安装失败的错误内容或者截图**

```
# 
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
否, 使用的是Debian11
```

**6.安装的脚本版本**

```
最新版
```

**7.安装类型**

- 个性化安装/全部安装

**8.安装的核心版本**

```
# xray-core[1.5.2]
```

**9.出现问题的协议类型**

```
# VLESS+ws+tls
```

**10.尝试重装后是否100%复现**

```
是,每次重新开机后也会出现这个问题
```

**11.是否更换客户端后再次尝试**

```
是
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 否
```

**Comment by TonyLCH** [comment]
已经试过apt-get安装nginx但无法在这个脚本使用

**Comment by mack-a** [comment]
没有euserv机器，使用vultr Debian11测试正常，请手动检查开机自启程序是否启动

**Comment by TonyLCH** [comment]
请问怎样检查？

**Comment by TonyLCH** [comment]
> 没有euserv机器，使用vultr Debian11测试正常，请手动检查开机自启程序是否启动
请问怎样检查？

**Comment by TonyLCH** [comment]
> 没有euserv机器，使用vultr Debian11测试正常，请手动检查开机自启程序是否启动

请问怎样检查？
