### ISSUE TITLE
大佬安装你的脚本提示要手动安装gninx

### ISSUE THREAD

**Issue by dgfrwx** [mack-a/v2ray-agent#336]
Vultr centos7
![Screenshot_2022_0124_154602](https://user-images.githubusercontent.com/30223562/150742024-006b6535-dd1e-4ed1-8736-62e7ab8593d1.png)
怎么办？

**Comment by dgfrwx** [comment]
网上ngninx教程好多,不知道怎么装装哪个？

**Comment by dgfrwx** [comment]
我装的是你的v2.5.48八合一脚本

**Comment by mack-a** [comment]
- 执行这个或者使用Without SELinux
```
setenforce 0 
```
