### ISSUE TITLE
甲骨文arm机器安装warp失败

### ISSUE THREAD

**Issue by flhs0606** [mack-a/v2ray-agent#337]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

甲骨文arm机器安装warp失败

**2.是否安装失败**

是

**3.是否重新build系统后尝试**

否

**4.安装失败的错误内容或者截图**

 ---> 安装WARP
 ---> 安装WARP失败

**5.系统版本【例：Debian10】**
Ubuntu 20.04

- 是否更换Debian10系统后再次安装

否

**6.安装的脚本版本**

2.5.48

**7.安装类型**

全部安装

**8.安装的核心版本**

xray-core[1.5.2]

**9.出现问题的协议类型**

无关联

**10.尝试重装后是否100%复现**

是

**11.是否更换客户端后再次尝试**

否

**12.是否将客户端升级最新进行尝试**

否

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

否

**Comment by mack-a** [comment]
错误信息呢

**Comment by flhs0606** [comment]
![image](https://user-images.githubusercontent.com/53371423/150946220-6b07375a-a2f4-4b5a-a383-0e066798066c.png)

**Comment by flhs0606** [comment]
> 错误信息呢

就一个失败，无其他有用信息

**Comment by mack-a** [comment]
手头没oracle机器，这样话，建议更换其他安装warp的脚本，然后用脚本中的ipv6分流即可

**Comment by Saxon-Sun** [comment]
> 手头没oracle ARM机器，这样话，建议更换其他安装warp的脚本，然后用脚本中的ipv6分流即可
麻烦给个tg，群里不知道哪个是您的tg 我有错误信息 用issues回复解决太慢了
