### ISSUE TITLE
甲骨文云纯ipv6安装xray core失败。

### ISSUE THREAD

**Issue by iamjimmycheng** [mack-a/v2ray-agent#338]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# 使用脚本安装的时候，进度到了6/13安装xray-core的时候等了很久，最后提示失败。
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

```
# 进度  6/13 : 安装Xray 
 ---> Xray-core版本:v1.5.2 
unzip:  cannot find or open /etc/v2ray-agent/xray/Xray-linux-arm64-v8a.zip, /etc/v2ray-agent/xray/Xray-linux-arm64-v8a.zip.zip or /etc/v2ray-agent/xray/Xray-linux-arm64-v8a.zip.ZIP.
chmod: cannot access '/etc/v2ray-agent/xray/xray': No such file or directory

```

**5.系统版本【例：Debian10】**

```
版本为：ubuntu 20.04
```

**6.安装的脚本版本**

```
#当前版本：v2.5.48 
```

**7.安装类型**

# 全部安装

**8.安装的核心版本**

```
# xray-core[1.5.2]
```

**9.出现问题的协议类型**

```
# xray-core核心安装失败
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是
```

**12.是否将客户端升级最新进行尝试**

```
# 是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 有尝试卸载脚本重装，故障依旧；没有DD
```

**Comment by mack-a** [comment]
重新执行，核心下载失败了

**Comment by iamjimmycheng** [comment]
重新执行过几次了，还是一样；

再换另一台甲骨文VPS，问题也是一样；

更换安装v2ray-core核心，问题也一样；

是IPV6的问题吗？我前天安装IPV4是正常的。

**Comment by mack-a** [comment]
甲骨文有纯ipv6的机器吗

**Comment by iamjimmycheng** [comment]
![image](https://user-images.githubusercontent.com/56783248/151502251-018a7384-73c9-4274-bc2d-a2fbdf44d5e3.png)

有的

**Comment by mack-a** [comment]
试试ipv4
