### ISSUE TITLE
【8.IPv6分流---2.卸载IPv6分流】操作后，并不删除 09_routing.json 内的域名，会影响下次再启动 IPv6分流的规则

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#339]
当前版本：v2.5.48   用Xray

发现用 【8.IPv6分流---2.卸载IPv6分流】 后， 09_routing.json 文件并没有改动（只是变更了 10_ipv4_outbounds.json 文件），导致下次再启动 IPv6分流后，会导致之前添加域名又会生效。
比如我先 IPv6分流添加域名 youtube，再卸载IPv6分流（意思我不再需要 youtube 域名的IPv6分流了），然后再添加域名 netflix 的 IPv6分流，那么上次的 youtube 也同时起效了，09_routing.json 文件会变成如下：

```
{
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:youtube"
        ],
        "outboundTag": "IPv6-out"
      },
      {
        "type": "field",
        "domain": [
          "geosite:netflix"
        ],
        "outboundTag": "IPv6-out"
      }
    ]
  }
}
```
或者我只是经常开关同一个域名的 IPv6分流，因为只能通过添加域名的方式启动，就会导致 09_routing.json 文件内会有一长串重复的规则残留。

**Comment by mack-a** [comment]
最新脚本重新安装试试

**Comment by Se7enMuting** [comment]
升级到 v2.5.49 好像没有区别啊
xray 原先是用脚本配置的 IPv6分流 netflix的，然后用脚本关闭IPv6分流，再用脚本添加 netflix的 IPv6分流，09_routing.json 里面还是会出现2份同样的 netflix 分流 rules，如下：
```
{
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:netflix"
        ],
        "outboundTag": "IPv6-out"
      },
      {
        "type": "field",
        "domain": [
          "geosite:netflix"
        ],
        "outboundTag": "IPv6-out"
      }
    ]
  }
}
```
而且如果在输入 IPv6分流域名的时候，直接打回车，就会出错了，xray 无法再启动，要进 conf 手动改配置。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.50
