### ISSUE TITLE
vmess地址转换成clash格式后无法链接

### ISSUE THREAD

**Issue by blue2018** [mack-a/v2ray-agent#34]
脚本生成的vmess格式地址，通过“https://subcon.dlj.tf/，这个网页转换成clash格式后无法连接，用别的脚本生成的vmess链接转换后都没问题的，麻烦修正一下，谢谢

**Comment by mack-a** [comment]
> 脚本生成的vmess格式地址，我用“[https://subcon.dlj.tf/”这个网页转换成clash格式后无法连接，用别的脚本生成的vmess链接转换后都没问题的，麻烦修正一下，谢谢](https://subcon.dlj.tf/%E2%80%9D%E8%BF%99%E4%B8%AA%E7%BD%91%E9%A1%B5%E8%BD%AC%E6%8D%A2%E6%88%90clash%E6%A0%BC%E5%BC%8F%E5%90%8E%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5%EF%BC%8C%E7%94%A8%E5%88%AB%E7%9A%84%E8%84%9A%E6%9C%AC%E7%94%9F%E6%88%90%E7%9A%84vmess%E9%93%BE%E6%8E%A5%E8%BD%AC%E6%8D%A2%E5%90%8E%E9%83%BD%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%8C%E9%BA%BB%E7%83%A6%E4%BF%AE%E6%AD%A3%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%B0%A2%E8%B0%A2)

手中无Clash

**Comment by blue2018** [comment]
> 手中无Clash无法进行测试，规则是按照v2rayN、小火箭。可以问问转换链接的作者。看看是否兼容了v2rayN、小火煎

之前我也是从v2rayN导出链接再进行转换也是可以的喔，不过用的不是你的脚本...

**Comment by mack-a** [comment]
> > 手中无Clash无法进行测试，规则是按照v2rayN、小火箭。可以问问转换链接的作者。看看是否兼容了v2rayN、小火煎
> 
> 
> 
> 之前我也是从v2rayN导出链接再进行转换也是可以的喔，不过用的不是你的脚本...

可以换一下他的脚本

**Comment by blue2018** [comment]
这是我一直在用的脚本，可以参考下喔
https://github.com/phlinhng/v2ray-tcp-tls-web

**Comment by phlinhng** [comment]
> 这是我一直在用的脚本，可以参考下喔
> https://github.com/phlinhng/v2ray-tcp-tls-web

好的

**Comment by blue2018** [comment]
哈哈，把另一位大神也吸引过来了←_←，有时间的话考虑更新下支持Xray呗
