### ISSUE TITLE
  ---> Nginx启动失败   ---> 请手动尝试安装nginx后，再次执行脚本 

### ISSUE THREAD

**Issue by JACKUSR2089** [mack-a/v2ray-agent#341]
系统是oracle的  [CentOS-8-2021.12.03-0]

脚本当前版本：v2.5.50 

报错是
**详细描述建议的内容**
touch: cannot touch '/etc/nginx/conf.d/alone.conf': No such file or directory
/root/install.sh: line 763: /etc/nginx/conf.d/alone.conf: No such file or directory
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本

**Comment by mack-a** [comment]
看README
