### ISSUE TITLE
2.5.50无法获取V2ray内核升级目标版本号

### ISSUE THREAD

**Issue by WoadZS** [mack-a/v2ray-agent#343]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
```
通过 `vasma` 菜单 `15` 无法获取 v2ray-core 最新版本号
```

**2.是否安装失败**

```
否
```

**3.是否重新build系统后尝试**

```
否
```

**4.安装失败的错误内容或者截图**

```
![错误截图](https://user-images.githubusercontent.com/18167899/152912013-7f9585b6-71b7-496c-8c9c-edca44ac58b3.png)

```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos

- 是否更换Debian10系统后再次安装

```
Debian 11.2.0-12 和 Ubuntu 20.04 两台VPS均必现
```

**6.安装的脚本版本**

```
2.5.50
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# V2ray-core[4.44.0]
```

**9.出现问题的协议类型**

```
协议正常使用
```

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.51
