### ISSUE TITLE
euserv安装tls失败

### ISSUE THREAD

**Issue by 6s6t** [mack-a/v2ray-agent#345]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**

```
# euserv安装tls失败
```

**2.是否安装失败**

```
# 是
```

**3.是否重新build系统后尝试**

```
# 是
```

**4.安装失败的错误内容或者截图**

![IMG_20220209_130032](https://user-images.githubusercontent.com/98389120/153125262-56af5578-2a7c-4a21-924b-1b6f137f54db.jpg)

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
Debian10
- 是否更换Debian10系统后再次安装

```
Debian10
```

**6.安装的脚本版本**

```
最新
```

**7.安装类型**

- 全部安装

**8.安装的核心版本**

```
# xray-core[1.4.2]
```

**9.出现问题的协议类型**

```
# VLESS+TLS+gRPC
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
# 是
```

**12.是否将客户端升级最新进行尝试**

```
# 书
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
# 是
```
# 其他 绑域名的时候IP是
![IMG_20220209_130449](https://user-images.githubusercontent.com/98389120/153125517-afbfa3e4-82da-410f-bd03-f465951073b8.jpg)

**Comment by mack-a** [comment]
80端口被占用 先手动关闭后再尝试使用脚本

**Comment by freesd** [comment]
大佬 ，我用八合一脚本在甲骨文VPS一键默认搭建的节点，唯独这个apkmirror.com这个网站访问不了，提示Error 1020，但是同样的脚本在GCP上搭建的没有问题，有解决方法吗？

**Comment by mack-a** [comment]
>  大佬 ，我用八合一脚本在甲骨文VPS一键默认搭建的节点，唯独这个apkmirror.com这个网站访问不了，提示Error 1020，但是同样的脚本在GCP上搭建的没有问题，有解决方法吗？

vps ip问题，换ip解决
