### ISSUE TITLE
增加ZeroSSL证书申请支持

### ISSUE THREAD

**Issue by amigo-via-circuito** [mack-a/v2ray-agent#347]
是否能增加一个在申请证书时选择证书颁发机构的选项，比如可以选Let's Encrypt或ZeroSSL的证书，并且可以选择证书类型是ECC证书还是RSA证书，目前遇到一个问题是在路由器上的科学上网插件似乎只支持ZeroSSL证书，如果服务端是Let's Encrypt证书的话就必须跳过证书验证。另外如果ZeroSSL的ECC的证书的话也会引起特定路由器的CPU满负载问题[https://github.com/XTLS/Xray-core/discussions/562](https://github.com/XTLS/Xray-core/discussions/562)
感谢大佬！

**Comment by mack-a** [comment]
什么路由器插件

**Comment by windfrom** [comment]
[https://github.com/cary-sas/v2ray_bin/issues/18](https://github.com/cary-sas/v2ray_bin/issues/18)
因为路由器只能用到较旧的梅林380 X7.9.1固件为止，fancyss_arm科学上网插件的版本停留在4.2.2，不支持新的vless协议 xray-core等，所以用了这个插件[https://github.com/cary-sas/v2ray_bin](https://github.com/cary-sas/v2ray_bin)
