### ISSUE TITLE
建议允许用户自己指定证书和保留原Nginx设定

### ISSUE THREAD

**Issue by lzy0702** [mack-a/v2ray-agent#349]
**详细描述建议的内容**
每次运行脚本都会把原本的Nginx设定弄没，导致服务器上同时存在的其它网站和服务不正常。额外生成的证书还会造成服务器其它服务的SSL异常。

**Comment by mack-a** [comment]
1.脚本本身支持自定义证书
2.脚本nginx不会卸载也不会删除用户自己的配置，只会删除脚本自建的nginx文件
