### ISSUE TITLE
某些vps安装后ws模式无法使用

### ISSUE THREAD

**Issue by jasonding121205** [mack-a/v2ray-agent#351]
> 请仔细填写每一项，并回复自己详细的错误信息

- 不符合的issue会被直接关闭

**1.描述出现的问题**
在甲骨文、racknerd、virmach机器上安装后带ws模式均无法使用，例如导入VLESS+WS[TLS]或VMess+WS[TLS]节点后，客户端输出unexpected EOF，vps端打开监听日志输出rejected  proxy/trojan: not trojan protocol。奇怪的是euserv的ipv6小鸡倒是可以正常使用。

**2.是否安装失败**
否

**3.是否重新build系统后尝试**
是
**4.安装失败的错误内容或者截图**
安装成功
```

**5.系统版本【例：Debian10】**
>最新版本脚本不支持Centos6，同时不建议使用centos
DEBIAN10
- 是否更换Debian10系统后再次安装

```
重新DD debian10后依然无法使用ws节点
```

**6.安装的脚本版本**
2.5.52

**7.安装类型**

- 选项1全部安装

**8.安装的核心版本**

```
xray-core[1.5.3]
```

**9.出现问题的协议类型**

```
VLESS+WS[TLS]/VMess+WS[TLS]/Trojan+TCP[TLS]
```

**10.尝试重装后是否100%复现**

```
# 是
```

**11.是否更换客户端后再次尝试**

```
是，导入passwall亦无法使用
```

**12.是否将客户端升级最新进行尝试**

```
是
```

**13.是否卸载脚本&DD系统后重新用最新脚本安装**

```
是
```
![image](https://user-images.githubusercontent.com/9958478/154017561-678a641c-0a1b-47c0-89d9-0c634e38f3bb.png)

![image](https://user-images.githubusercontent.com/9958478/154017902-fd678e62-6b27-40bb-9ebb-7ae9ed89cc1e.png)

**Comment by mack-a** [comment]
用vultr测试了下，客户端选用qv2ray和shadowrocket均未发现此问题，是否方便提供出现问题的vps。

**Comment by jasonding121205** [comment]
感谢大佬回复，请问要如何提供呢？

**Comment by mack-a** [comment]
> 感谢大佬回复，请问要如何提供呢？

可以通过加tg群 然后问一下就可
