### ISSUE TITLE
TLS报错，提示@example.com禁止

### ISSUE THREAD

**Issue by vongoethe** [mack-a/v2ray-agent#352]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
安装过程中，生成证书时候，TLS报错

**2.安装失败的错误内容或者截图**
`进度  3/17 : 申请TLS证书
 
 ---> 安装TLS证书 
[Sat Feb 19 05:24:30 UTC 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Sat Feb 19 05:24:30 UTC 2022] Please add '--debug' or '--log' to check more details.
[Sat Feb 19 05:24:30 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat Feb 19 05:18:10 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:18:10 UTC 2022] Standalone mode.
[Sat Feb 19 05:18:10 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:18:13 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:18:13 UTC 2022] Standalone mode.
[Sat Feb 19 05:18:14 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:28 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:28 UTC 2022] Standalone mode.
[Sat Feb 19 05:24:28 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
 ---> TLS安装失败，正在检查80、443端口是否开放 
 ---> 重新尝试安装TLS证书 

进度  3/17 : 申请TLS证书
 
 ---> 安装TLS证书 
[Sat Feb 19 05:24:33 UTC 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Sat Feb 19 05:24:33 UTC 2022] Please add '--debug' or '--log' to check more details.
[Sat Feb 19 05:24:33 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat Feb 19 05:18:10 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:18:13 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:18:13 UTC 2022] Standalone mode.
[Sat Feb 19 05:18:14 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:28 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:28 UTC 2022] Standalone mode.
[Sat Feb 19 05:24:28 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:31 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 19 05:24:31 UTC 2022] Standalone mode.
[Sat Feb 19 05:24:31 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
 ---> TLS安装失败，请检查acme日志 
`
**3.系统版本**
甲骨文ubuntu 20.04

**4.脚本版本**
v2.5.52

**5.核心类型及版本**
5.11.0-1028-oracle

**Comment by KaneLeung** [comment]
我也出现这个情况，现在卸载后重新安装试试
