### ISSUE TITLE
建议优化默认的SSL申请邮箱

### ISSUE THREAD

**Issue by a2841905265** [mack-a/v2ray-agent#354]
请输入要配置的域名 例：www.v2ray-agent.com --->
域名:ip.eu.plwd.xyz

 ---> 检查域名ip中
 ---> 当前域名ip为：[2a02:180:6:1::4ebc]

进度  4/13 : 申请TLS证书

 ---> 安装TLS证书
[Sun Feb 20 13:55:09 CST 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Sun Feb 20 13:55:09 CST 2022] Please add '--debug' or '--log' to check more details.
[Sun Feb 20 13:55:09 CST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Feb 20 13:51:31 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:51:31 CST 2022] Standalone mode.
[Sun Feb 20 13:51:33 CST 2022] Create account key ok.
[Sun Feb 20 13:51:34 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:51:38 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:51:38 CST 2022] Standalone mode.
[Sun Feb 20 13:51:39 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:06 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:06 CST 2022] Standalone mode.
[Sun Feb 20 13:55:07 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
 ---> TLS安装失败，正在检查80、443端口是否开放
 ---> 重新尝试安装TLS证书

进度  4/13 : 申请TLS证书

 ---> 安装TLS证书
[Sun Feb 20 13:55:14 CST 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Sun Feb 20 13:55:14 CST 2022] Please add '--debug' or '--log' to check more details.
[Sun Feb 20 13:55:14 CST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Feb 20 13:51:34 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:51:38 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:51:38 CST 2022] Standalone mode.
[Sun Feb 20 13:51:39 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:06 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:06 CST 2022] Standalone mode.
[Sun Feb 20 13:55:07 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:11 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Feb 20 13:55:11 CST 2022] Standalone mode.
[Sun Feb 20 13:55:12 CST 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
 ---> TLS安装失败，请检查acme日志
root@ip:~#

**Comment by mack-a** [comment]
无复现，请手动卸载脚本后重新安装
