### ISSUE TITLE
更新最新内核后无法启动内核

### ISSUE THREAD

**Issue by TTTTTiT** [mack-a/v2ray-agent#355]
更新1.5.4的xray内核的时候无法正常启动内核，尝试启动多次无果，遂降级回1.5.3版本，结果还是无法启动。下面是日志。
Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
A unified platform for anti-censorship.
2022/02/20 14:54:20 Using confdir from arg: /etc/v2ray-agent/xray/conf
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/11_dns.json > infra/conf/serial: failed to read config file at line 5 char 29 > invalid character '\x1b' in string literal

**Comment by TTTTTiT** [comment]
无奈只能重装，重装的时候到第二步安装工具的时候就卡住了，等了很久也不见动静，多次取消重试都没有好转。最后卸载脚本重新安装脚本，还是在第二步卡住了。

**Comment by mack-a** [comment]
建议更换debian系统

**Comment by mack-a** [comment]
> 更新1.5.4的xray内核的时候无法正常启动内核，尝试启动多次无果，遂降级回1.5.3版本，结果还是无法启动。下面是日志。
> 
> Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
> 
> A unified platform for anti-censorship.
> 
> 2022/02/20 14:54:20 Using confdir from arg: /etc/v2ray-agent/xray/conf
> 
> xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
> 
> xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
> 
> xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
> 
> xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
> 
> xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
> 
> 2022/02/20 14:54:20 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
> 
> Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/11_dns.json > infra/conf/serial: failed to read config file at line 5 char 29 > invalid character '\x1b' in string literal

看报错信息，明确指出哪一行配置有问题
