### ISSUE TITLE
伪装站点网页无法访问

### ISSUE THREAD

**Issue by huoshenlaile** [mack-a/v2ray-agent#356]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- xray 核心 安装时选2 trojan grpc , 伪装站点网页无法访问

**2.安装失败的错误内容或者截图**
- 
- 
![image](https://user-images.githubusercontent.com/48918740/155069700-034d07b4-daad-47f4-9281-c783416dca27.png)

**3.系统版本**
- ubuntu 20.04 LTS

**4.脚本版本**
- v2.5.52

**5.核心类型及版本**
- Xray 1.5.3

**Comment by mack-a** [comment]
清除缓存试一下

**Comment by huoshenlaile** [comment]
> 清除缓存试一下

清楚了，并且尝试在Chrome无痕模式里打开也没有用
