### ISSUE TITLE
English Install Script still at 2.5.28

### ISSUE THREAD

**Issue by demib72** [mack-a/v2ray-agent#358]
Hello, I just thought I would point out that the install script you have for English (massive thank you) is still at 2.5.28. When you go to update it, it simply installs the updated Chinese version. Provided there aren't too many differences in language (I have noticed some additions), I can try to translate those as I copy and paste from the existing install_en.

**Comment by mack-a** [comment]
please pull requests

**Comment by wertyty** [comment]
不支持免费域名吗

**Comment by mack-a** [comment]
> 不支持免费域名吗

支持

**Comment by wertyty** [comment]
为啥我的域名已经在Cloudflare解析成功了，配置域名还是提示未检测到当前域名的ip

**Comment by mack-a** [comment]
> 为啥我的域名已经在Cloudflare解析成功了，配置域名还是提示未检测到当前域名的ip

查看提示 挨个检查

**Comment by wertyty** [comment]
好的，谢谢
