### ISSUE TITLE
建议增加TFO（TCP fastopen）开启功能

### ISSUE THREAD

**Issue by 40560208t** [mack-a/v2ray-agent#361]
**详细描述建议的内容**
尝试在服务器端修改/etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json，添加"tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": true,
        "fast_open_qlen": 20
    },
但是重启后TFO无法打开，用SS-trust搭建的可以打开。

**Comment by mack-a** [comment]
特征明显
