### ISSUE TITLE
目前添加端口后 xr或者v2 会自动停止运行。

### ISSUE THREAD

**Issue by meliissy** [mack-a/v2ray-agent#362]
**详细描述建议的内容**
1

**Comment by mack-a** [comment]
反馈一下错误日志

**Comment by meliissy** [comment]
root@5287848548hax:~# /etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2022/03/09 12:01:56 Using confdir from arg: /etc/v2ray-agent/v2ray/conf
v2ctl> [ /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_2053.json ] appended inbound with tag:  dokodemo-door-newPort-2053
v2ctl> [ /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_2083.json ] appended inbound with tag:  dokodemo-door-newPort-2083
v2ctl> [ /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_80.json ] appended inbound with tag:  dokodemo-door-newPort-80
v2ctl> [ /etc/v2ray-agent/v2ray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
v2ctl> [ /etc/v2ray-agent/v2ray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
v2ctl> [ /etc/v2ray-agent/v2ray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
v2ctl> [ /etc/v2ray-agent/v2ray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
v2ctl> [ /etc/v2ray-agent/v2ray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/00_log.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/02_VLESS_TCP_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_2053.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_2083.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/02_dokodemodoor_inbounds_80.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/03_VLESS_WS_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/04_trojan_TCP_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/04_trojan_gRPC_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/05_VMess_WS_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/06_VLESS_gRPC_inbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/10_ipv4_outbounds.json
2022/03/09 12:01:56 [Info] main/jsonem: Reading config: /etc/v2ray-agent/v2ray/conf/11_dns.json
Failed to start app/proxyman/inbound: failed to listen TCP on 80 > transport/internet: failed to listen on address: 0.0.0.0:80 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:80 > listen tcp 0.0.0.0:80: bind: address already in use
root@5287848548hax:~#

**Comment by meliissy** [comment]
这个日志是重启之后 停止运行。 我尝试重新升级。提示这个。

**Comment by mack-a** [comment]
端口不能加80 80已被nginx占用，请更换其他端口
