### ISSUE TITLE
ipv6分流

### ISSUE THREAD

**Issue by shifrank1989** [mack-a/v2ray-agent#363]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
-xray运行正常后，使用vasma运行脚本，使用ipv6分流，输入youtube后报错

**2.安装失败的错误内容或者截图**
- 
<img width="1440" alt="截屏2022-03-09 下午11 22 46" src="https://user-images.githubusercontent.com/13214736/157475428-efcb186f-e24e-4468-bb9b-7066bb4c161d.png">

**3.系统版本**
- CentOS Linux release 7.9.2009 (Core)

**4.脚本版本**
- v2.5.52 

**5.核心类型及版本**
- Xray-core

**Comment by mack-a** [comment]
暂未复现，请确认是否是输入文本的编码问题
