### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Determined-face** [mack-a/v2ray-agent#365]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 启动失败

**2.安装失败的错误内容或者截图**
![RNYO3U5BF5HQT`3E6 G)FLQ](https://user-images.githubusercontent.com/49339706/158631677-9e514a37-a498-420c-a516-57dde3fefff4.png)

**3.系统版本**
- 最新

**4.脚本版本**
- 最新

**5.核心类型及版本**
- xray

**Comment by mack-a** [comment]
按照提示，反馈详细的错误日志
