### ISSUE TITLE
ubuntu 16无法使用

### ISSUE THREAD

**Issue by woshiekao** [mack-a/v2ray-agent#366]
**详细描述建议的内容**
本脚本不支持此系统，请将下方日志反馈给开发者
 
Ubuntu 16.04.6 LTS 
 \l 
Linux version 5.5.10-050510-generic (kernel@sita) (gcc version 9.2.1 20200203 (Ubuntu 9.2.1-28ubuntu1)) #202003180732 SMP Wed Mar 18 07:35:23 UTC 2020

**Comment by mack-a** [comment]
![Uploading image.png…]()

**Comment by mack-a** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/57424792/158934588-983a0b46-fb97-42a6-913c-aba5218f993e.png">
