### ISSUE TITLE
关于英文版的提问

### ISSUE THREAD

**Issue by Armin-0401** [mack-a/v2ray-agent#369]
因爲想把脚本推薦給朋友用，考慮到朋友的中文不好，我就去看了下英文版，英文版脚本仍停留在 v2.5.28
然後在[ **Furtue**](https://github.com/mack-a/v2ray-agent/issues/76) 这个issue里，看到`脚本中英文切换`這項是打勾的

- [x] 脚本中英文切换

請問這項是額外添加的新功能嗎？還是就是指 install_en.sh ？

**Comment by mack-a** [comment]
对 一个额外的翻译版本
