### ISSUE TITLE
添加或删除用户后会遇到脚本未运行的情况

### ISSUE THREAD

**Issue by sinian-liu** [mack-a/v2ray-agent#374]
**1.问题描述**
- 多次添加用户后会出现Xray启动失败情况，重启等一系列操作都无法解决，必须重装系统再重新安装本脚本才可以解决问题，删除用户也偶尔同样遇到此问题

**2.安装失败的错误内容或者截图**
- root@localhost:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】
Xray 1.5.4 (Xray, Penetrates Everything.) Custom (go1.17.7 linux/amd64)
A unified platform for anti-censorship.
2022/04/04 01:19:19 Using config from STDIN
2022/04/04 01:19:19 [Info] infra/conf/serial: Reading config: stdin:

Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLES S_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.j son /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/ll_dns.json] > infra/conf/serial: failed to decod e config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json > infra/conf/serial: failed to read config file > EOF 

**3.系统版本**
- Debian 9 64位

**4.脚本版本**
- v2.5.57

**5.核心类型及版本**
- Xray-core版本:v1.5.4
- 
<img width="895" alt="wenti" src="https://user-images.githubusercontent.com/86273555/161477348-b7c4345b-2a2c-4ecd-9a63-667397cbc714.png">

**Comment by sinian-liu** [comment]
![133](https://user-images.githubusercontent.com/86273555/161480810-6023d35c-1c19-4bd5-901f-c1c6ead4d86f.jpg)

**Comment by mack-a** [comment]
> ![133](https://user-images.githubusercontent.com/86273555/161480810-6023d35c-1c19-4bd5-901f-c1c6ead4d86f.jpg)

email不可重名
