### ISSUE TITLE
client for linux

### ISSUE THREAD

**Issue by wonderful27x** [mack-a/v2ray-agent#375]
**详细描述建议的内容**
期望拥有linux的客户端

**Comment by mack-a** [comment]
这是服务端的脚本，需求提错地方了

**Comment by wonderful27x** [comment]
你好，请问在linux端怎么连接服务啊，在[手动自建](https://github.com/mack-a/v2ray-agent/blob/master/documents/Cloudflare_Full.md)中有android、ios、windows、mac的客户端，就是没找到linux的，希望能解答下，谢谢！
