### ISSUE TITLE
请求内置下内网穿透代理NPS功能

### ISSUE THREAD

**Issue by VFengChen** [mack-a/v2ray-agent#376]
**详细描述建议的内容**
大佬,我想要在同一台VPS中同时安装你的脚步+内网穿透NPS(https://github.com/ehang-io/nps)
但是NPS也是占用80和443端口的,不能启动,不知大佬你的脚本是否可以直接内置内网穿透代理功能或者兼容设置方法?

**Comment by mack-a** [comment]
只要内网vps有公网ip（映射）和80 443两个端口就可

**Comment by VFengChen** [comment]
我的意思是能不能同时安装NPS,想要实现直接域名访问不带端口号.

**Comment by mack-a** [comment]
目前不会加
