### ISSUE TITLE
多域名情况下，建议一键添加增加的域名，

### ISSUE THREAD

**Issue by mmmmzpl** [mack-a/v2ray-agent#377]
多域名情况下，建议一键添加增加的域名，
我有一个服务器，服务器可以增加多个IP，
那么我用不同的域名解析不同的IP，而实际是还在一个服务器上
那么，就像独立安装单个域名一样，
增加一个域名就自动增加一个新的，
能 理解吗，可以解决吗？

**Comment by mack-a** [comment]
不支持

**Comment by mmmmzpl** [comment]
可以改一改吗，就当每个域名绑一定虚似服务器，每个虚似服务器给他绑一个固定IP，然后环境只用安装一次，这种思路可能可行

**Comment by mmmmzpl** [comment]
说错了，
就当每一个域名绑定一个虚似服务器，每一个虚似服务器给他绑定固定IP，然后环境只用安装一次，这种思路就可以改

**Comment by mack-a** [comment]
个性化需求请自行修改
