### ISSUE TITLE
任意门解锁有问题

### ISSUE THREAD

**Issue by mrright-cyber** [mack-a/v2ray-agent#379]
**【结论放开头】：通过反复的更改VPS2inbound以及相关VPS1路由，并通过ip.sb进行验证，返回的仍为VPS1的IP，因此此解锁尚待进一步确定有效性。**
（1）VPS1（不能看Netflix、Disney+）outbounds:
    {
      "tag": "streamingMedia-80",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "VPS2IP:22387"
      }
    },
    {
      "tag": "streamingMedia-443",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "VPS2IP:22388"
      }
    }
{
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "port": 80,
        "domain": [
          "ip.sb",
          "geosite:disney"
        ],
        "outboundTag": "streamingMedia-80"
      },
      {
        "type": "field",
        "port": 443,
        "domain": [
          "ip.sb",
          "geosite:disney"
        ],
        "outboundTag": "streamingMedia-443"
      }
    ]
  }
}

（2）VPS2（可观看NF\D+）的inbound：
{
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 22387,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0",
        "port": 80,
        "network": "tcp",
        "followRedirect": false
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http"
        ]
      },
      "tag": "streamingMedia-80"
    },
    {
      "listen": "0.0.0.0",
      "port": 22388,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0",
        "port": 443,
        "network": "tcp",
        "followRedirect": false
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "tls"
        ]
      },
      "tag": "streamingMedia-443"
    }
  ]
}
            {
              "routing": {
                "rules": [
                  {
                     "source": [
                    	"VPS1 IP"
                    ],
                    "type": "field",
                    "inboundTag": [
                      "streamingMedia-80",
                      "streamingMedia-443"
                    ],
                    "outboundTag": "direct"
                  },
                  {
                    "domains": [
                    	"geosite:disney"
                    ],
                    "type": "field",
                    "inboundTag": [
                      "streamingMedia-80",
                      "streamingMedia-443"
                    ],
                    "outboundTag": "blackhole-out"
                  }
                ]
              }
            }
**结论：通过反复的更改VPS2inbound以及相关VPS1路由，并通过ip.sb进行验证，返回的仍为VPS1的IP，因此此解锁尚待进一步确定有效性。**

**Comment by mack-a** [comment]
使用脚本中的任意门落地机解锁流媒体 测试未发现此问题，并通过上述描述测试ip.sb IP显示为解锁机ip
