### ISSUE TITLE
执行卸载脚本后nginx有残留

### ISSUE THREAD

**Issue by wsa01378** [mack-a/v2ray-agent#38]
uninstall reboot后 80端口被nginx占用

**Comment by mack-a** [comment]
> uninstall reboot后 80端口被nginx占用

卸载脚本后不会删除nginx，因为nginx服务不一定是脚本安装的。只会删除当时生成的文件。如果这里手动卸载了还占用，可能是卸载方法有误。可以排查是否真的是nginx占用端口，亦或者自己删除service 重启就可以了。
