### ISSUE TITLE
nginx无法安装

### ISSUE THREAD

**Issue by ByboyCn** [mack-a/v2ray-agent#381]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 请在此处填写
无法安装nginx
**2.安装失败的错误内容或者截图**
- 请在此处填写
![image](https://user-images.githubusercontent.com/17998816/163553114-5a142857-a555-48b5-baf3-4b4082cadae4.png)

**3.系统版本**
- 请在此处填写
centos7
**4.脚本版本**
- 请在此处填写
2.5.58
**5.核心类型及版本**
- 请在此处填写

**Comment by mack-a** [comment]
手动安装一下nginx或者更换debian ubuntu
