### ISSUE TITLE
大佬我想提一个意见 关于流媒体解锁任意门和DNS解锁

### ISSUE THREAD

**Issue by yl1677866238** [mack-a/v2ray-agent#384]
流媒体解锁任意门 是否可以接收多个同地区的解锁的小鸡
比如说 我有一台连接国内良好的VPS 需要同时解锁台湾动画疯和新加坡网飞还需要解锁DAZN 我就需要同时入站3台 
第二点就是DNS解锁
我自己有很多个DNS解锁 我希望可以添加多个不同DNS解锁给不同的流媒体
谢谢大佬

**Comment by mack-a** [comment]
这些倒是都可以实现，等有空的

**Comment by yl1677866238** [comment]
感谢大佬回复

**Comment by yl1677866238** [comment]
这边出站的话  也想请大佬 可以添加多个出站

**Comment by mack-a** [comment]
> 流媒体解锁任意门 是否可以接收多个同地区的解锁的小鸡 比如说 我有一台连接国内良好的VPS 需要同时解锁台湾动画疯和新加坡网飞还需要解锁DAZN 我就需要同时入站3台 第二点就是DNS解锁 我自己有很多个DNS解锁 我希望可以添加多个不同DNS解锁给不同的流媒体 谢谢大佬

入站可以多台吧，现在出站不可以

**Comment by yl1677866238** [comment]
> > 流媒体解锁任意门 是否可以接收多个同地区的解锁的小鸡 比如说 我有一台连接国内良好的VPS 需要同时解锁台湾动画疯和新加坡网飞还需要解锁DAZN 我就需要同时入站3台 第二点就是DNS解锁 我自己有很多个DNS解锁 我希望可以添加多个不同DNS解锁给不同的流媒体 谢谢大佬
> 
> 入站可以多台吧，现在出站不可以

是的大佬 我脑子坏的了

**Comment by Saxon-Sun** [comment]
@mack-a 任意门入站能否增加自定义协议设置，有些解锁平台提供的是vmess或者是vless协议进行解锁（套娃），我现在都是通过手动修改配置实现的 能否增加自定义这个功能

**Comment by mack-a** [comment]
> @mack-a 任意门入站能否增加自定义协议设置，有些解锁平台提供的是vmess或者是vless协议进行解锁（套娃），我现在都是通过手动修改配置实现的 能否增加自定义这个功能

你想说的是任意门出站吧 然后解锁方提供VMess和VLESS

这个需求用的人太少，只能手动实现

**Comment by Saxon-Sun** [comment]
> > @mack-a 任意门入站能否增加自定义协议设置，有些解锁平台提供的是vmess或者是vless协议进行解锁（套娃），我现在都是通过手动修改配置实现的 能否增加自定义这个功能
> 
> 你想说的是任意门出站吧 然后解锁方提供VMess和VLESS
> 
> 这个需求用的人太少，只能手动实现

对对 出站 手动实现太麻烦了😡  得有空自己提交pr了

**Comment by mack-a** [comment]
> > > @mack-a 任意门入站能否增加自定义协议设置，有些解锁平台提供的是vmess或者是vless协议进行解锁（套娃），我现在都是通过手动修改配置实现的 能否增加自定义这个功能
> > 
> > 
> > 你想说的是任意门出站吧 然后解锁方提供VMess和VLESS
> > 这个需求用的人太少，只能手动实现
> 
> 对对 出站 手动实现太麻烦了😡 得有空自己提交pr了

不麻烦呀，改一下09改一下10出站就OK了

**Comment by Saxon-Sun** [comment]
> 

对 09路由和10出站改了就好了 就是手动修改起来 还是没自动方便感觉 🙄

**Comment by MaoMichael** [comment]
> 流媒体解锁任意门 是否可以接收多个同地区的解锁的小鸡 比如说 我有一台连接国内良好的VPS 需要同时解锁台湾动画疯和新加坡网飞还需要解锁DAZN 我就需要同时入站3台 第二点就是DNS解锁 我自己有很多个DNS解锁 我希望可以添加多个不同DNS解锁给不同的流媒体 谢谢大佬

多建几个VMESS+WS的分流TAG就可以了。

**Comment by jaysonyip** [comment]
大佬什么时候有增加sing-box DNS流媒体解锁的计划，不想用xray了
