### ISSUE TITLE
请求支持新协议

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#387]
网上有关hysteria的测试发现效果很炸裂，大佬能否兼容该协议实现一键安装
https://github.com/HyNetwork/hysteria

**Comment by mack-a** [comment]
目前不会添加

**Comment by lfxx** [comment]
> 网上有关hysteria的测试发现效果很炸裂，大佬能否兼容该协议实现一键安装 [HyNetwork/hysteria](https://github.com/HyNetwork/hysteria)

好东西
