### ISSUE TITLE
Trojan无法连接

### ISSUE THREAD

**Issue by Fangliding** [mack-a/v2ray-agent#388]
**1.问题描述**
- 下发的Trojan订阅由于配置问题无法连接

**2.安装失败的错误内容或者截图**
I/v2ray-core: app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to read address and port > remote error: tls: no application protocol

**3.系统版本**
-安卓10

**4.脚本版本**
最新

**5.核心类型及版本**
sagernet 0.8 beta2(fly 5.0.9)

锅已经找到了 下发的Trojan中包含应用层协议协商http1.1
这是错误的写法 正确的写法是
http/1.1
或者直接留空 也可以连

**Comment by mack-a** [comment]
最新版已修改
