### ISSUE TITLE
请求大佬增加支持树莓派的CPU架构

### ISSUE THREAD

**Issue by yauhf** [mack-a/v2ray-agent#389]
我记得之前的版本是支持树莓派3B的CPU的，但是现在安装的时候会提示不支持CPU架构。
请求大佬增加支持树莓派的CPU架构，请问这个可以实现吗？
树莓派3B的CPU是BCM2837，4B的是BCM2711
谢谢大佬

**Comment by mack-a** [comment]
没支持过这个CPU

**Comment by mack-a** [comment]
你可以看看对应的是哪一个

https://github.com/XTLS/Xray-core/releases/tag/v1.5.5

**Comment by yauhf** [comment]
> 你可以看看对应的是哪一个
> 
> 
> 
> https://github.com/XTLS/Xray-core/releases/tag/v1.5.5

应该是对应这个的Xray-linux-arm64-v8a

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/164959667-2883308b-acf7-4801-ae4d-0c8b57674783.png)
这个有的

**Comment by mack-a** [comment]
可以执行一下 uname 看看显示啥

**Comment by yauhf** [comment]
只显示linux

**Comment by mack-a** [comment]
uname -m 这个呢

**Comment by yauhf** [comment]
显示armv7l
抱歉原来不是armv8

**Comment by mack-a** [comment]
等我发一下v7a的需要配合测试，手头没有树莓派

**Comment by mack-a** [comment]
> 显示armv7l 抱歉原来不是armv8

返回的是armv7 还是 armv7l

**Comment by mack-a** [comment]
你来TG 群 https://t.me/technologyshare

**Comment by yauhf** [comment]
armv7l

**Comment by mack-a** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/57424792/164960600-745d7a8f-53c1-463a-878d-bf5ceac2e234.png">
可以手动测试下这个核心 是否可用
