### ISSUE TITLE
vless+xtls连接比trojan慢3-5秒左右

### ISSUE THREAD

**Issue by urnuts** [mack-a/v2ray-agent#39]
用您的脚本xray,选了0,1,4协议: vless+xtls, vless+ws, trojan-go
在第一次访问google和y2b时，Trojan可以立即连接上，vless+xtls, vless+ws则会有3-5秒的明显延迟；

尝试过启用/关闭脚本带的dns,结果一样
客户端是v2rayN 3.28+ xray 1.0

**Comment by mack-a** [comment]
> 用您的脚本xray,选了0,1,4协议: vless+xtls, vless+ws, trojan-go
> 
> 在第一次访问google和y2b时，Trojan可以立即连接上，vless+xtls, vless+ws则会有3-5秒的明显延迟；
> 
> 
> 
> 尝试过启用/关闭脚本带的dns,结果一样
> 
> 客户端是v2rayN 3.28+ xray 1.0
> 
> 

Trojan是基于trojan-go的，非Xray-core
