### ISSUE TITLE
任意门落地机解锁流媒体，Trojan方式不成功

### ISSUE THREAD

**Issue by cmazfuture** [mack-a/v2ray-agent#391]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
-任意门落地机解锁流媒体， 测试奈飞，Trojan方式上网无法使用落地的IP解锁奈飞。VLESS和Vmess方式正常使用落地的IP解锁奈飞

**3.系统版本**
- debian11

**4.脚本版本**
- v2.5.63 

**5.核心类型及版本**
- Xray-core1.5.4

**Comment by mack-a** [comment]
未复现此问题
