### ISSUE TITLE
三个小建议

### ISSUE THREAD

**Issue by PeterPan0106** [mack-a/v2ray-agent#392]
1.关于订阅，服务器配置改变之后订阅似乎不会发生变化。例如接口从443换到其他接口之后订阅同步过来的依然是旧配置，而即便我选择1重新安装之后配置依然还是旧配置。不确定是bug还是我操作的问题。
2.脚本安装时无法选择端口，有时候端口被墙就不太方便，得安装完之后再加端口，叠加上1就会有些不方便。
3.重装系统之后，按照V2ray+Vmess+TLS的时候，如果按照前一个服务器正常再跑的配置重新设置，就是手动输入UUID和path，脚本能正常跑完并且没有任何报错。但是客户端连接时会报错404，端口IP和域名都排查过没问题。只能用新配置，这个可能是个bug，就是手动输入这两个信息时出现问题。

**Comment by mack-a** [comment]
1.第一个必须查看才会更改，脚本有说明
2.第二个不方便修改，已放弃
3.path随机一般是没有问题，如果和回落path重合会出现问题，还需要优化
