### ISSUE TITLE
gRPC传输协议下serviceName配置错误

### ISSUE THREAD

**Issue by wty9206** [mack-a/v2ray-agent#396]
更新脚本后，gRPC传输协议下，serviceName无论如何自定义或随机生成，最终返回结果均为"grpc"，且无法用生成的配置成功连接。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.66 用这个版本试一下呐

**Comment by wty9206** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.66 用这个版本试一下呐

谢谢作者的回复，试了2.5.66和2.5.67，都有同样的问题，gRPC模式serviceName=grpc，以前都是八个字母的。并且客户端无法连接（同一个服务器用其他协议都可以连接，再未更新脚本之前gRPC模式也可以连接，并且serviceName随机生成一直为八个字母，例如zdoygrpc）。

**Comment by wty9206** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.68 试试这个版本

可以啦，谢谢大神

**Comment by fredericky123** [comment]
> 更新脚本后，gRPC传输协议下，serviceName无论如何自定义或随机生成，最终返回结果均为"grpc"，且无法用生成的配置成功连接。

请问你grpc用的什么客户端，我这里一直想尝试grpc协议，却始终未成功，求教经验

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.69

**Comment by fredericky123** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.69

谢谢，选择trojan grpc是不是需要对alpn进行额外设置？
换言之，vmess+ws和trojan grpc不改任何配置能在服务器同时实现么，这样可以同时使用两种协议

**Comment by fredericky123** [comment]
clash的trojan grpc配置里没有uuid，不过w我发现生成的账号信息里却有，不知该如何配置
![image](https://user-images.githubusercontent.com/13982749/166883766-0e9f213b-56f8-4e37-be27-cf8d8527eacd.png)

**Comment by fredericky123** [comment]
目前服务端首选h2,客户端配置
<img width="341" alt="image" src="https://user-images.githubusercontent.com/13982749/166886050-a6f9d484-7efa-4710-8366-92b15f07808c.png">
总是出现这个问题：
![image](https://user-images.githubusercontent.com/13982749/166886078-9aeb58e0-3f10-4e13-aefc-41db92869f43.png)

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.70

**Comment by fredericky123** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.70

可否明示配置哪里出了问题？
以及更新为2570依然出现err ssl protocol error问题

**Comment by mack-a** [comment]
> > https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.70
> 
> 可否明示配置哪里出了问题？ 以及更新为2570依然出现err ssl protocol error问题

serviceName出现问题，建议账号什么的重新弄一下，仅测试了v2rayNG不保证其余客户端可用
