### ISSUE TITLE
无法启动，手动执行无异常，

### ISSUE THREAD

**Issue by dotaxl** [mack-a/v2ray-agent#397]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 请在此处填写
 ---> Xray关闭成功 
Xray启动失败 
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 
[root@cvm-3j8uhys28a225 nginx]# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
2022/05/04 10:10:05 Using confdir from arg: /etc/v2ray-agent/xray/conf
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2022/05/04 10:10:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json

**2.安装失败的错误内容或者截图**
- 请在此处填写
![image](https://user-images.githubusercontent.com/15247913/166615347-91a36e50-9f27-45fb-8de4-b336fde0c809.png)

**3.系统版本**
- 请在此处填写

**4.脚本版本**
- 请在此处填写
 2.5.68
**5.核心类型及版本**
- 请在此处填写
- 1.Xray-core

**Comment by dotaxl** [comment]
感觉启动成功了，好像是关闭没成功 
执行这个命令ps -ef|grep xray
[root@cvm-3j8uhys28a225 nginx]# ps -ef|grep xray
root       880     1  0 May03 ?        00:00:00 /usr/local/bin/xray run -config /usr/local/etc/xray/config.json
root     13283 30131  0 10:27 pts/0    00:00:00 grep --color=auto xray
我杀掉进程再试试

**Comment by dotaxl** [comment]
![image](https://user-images.githubusercontent.com/15247913/166616217-e814d38f-3c40-4137-ace8-51d3b40690dd.png)

**Comment by mack-a** [comment]
请先卸载其他脚本安装的内容，或者dd新系统安装
