### ISSUE TITLE
请问：在vps上删除改脚本的命令是什么？

### ISSUE THREAD

**Issue by myworksfun** [mack-a/v2ray-agent#4]
脚本问题太多，什么明明正确的域名解析和配置OK的防火墙，各种报错，不折腾了；比较糟糕的脚本

**Comment by myworksfun** [comment]
reset centos，done！

**Comment by mack-a** [comment]
> 脚本问题太多，什么明明正确的域名解析和配置OK的防火墙，各种报错，不折腾了；比较糟糕的脚本

暴躁老哥，有问题可以提呀  也可以私聊我帮助你解决问题。

**Comment by mack-a** [comment]
> 脚本问题太多，什么明明正确的域名解析和配置OK的防火墙，各种报错，不折腾了；比较糟糕的脚本

Sorry 给你带来不好的体验 ，之前这个项目没开Watch，看不到issues的提醒，后续我会继续完善脚本。
