### ISSUE TITLE
关于几个service启动顺序

### ISSUE THREAD

**Issue by monsterzzzz** [mack-a/v2ray-agent#40]
选择安装的是0,4，发现在某些VPS上，trojan-go启动时nginx还没启动，trojan-go就会启动失败，手动systemctl restart trojan-go才会启动成功，这种情况一般发生在系统重启后。在trojan-go.service里面的After=加上nginx.service就可以了，不知道有没有更好的解决办法

**Comment by mack-a** [comment]
> 选择安装的是0,4，发现在某些VPS上，trojan-go启动时nginx还没启动，trojan-go就会启动失败，手动systemctl restart trojan-go才会启动成功，这种情况一般发生在系统重启后。在trojan-go.service里面的After=加上nginx.service就可以了，不知道有没有更好的解决办法

谢谢反馈，有空我改一下

**Comment by mack-a** [comment]
> 选择安装的是0,4，发现在某些VPS上，trojan-go启动时nginx还没启动，trojan-go就会启动失败，手动systemctl restart trojan-go才会启动成功，这种情况一般发生在系统重启后。在trojan-go.service里面的After=加上nginx.service就可以了，不知道有没有更好的解决办法

https://github.com/mack-a/v2ray-agent/releases/tag/v2.1.24 已更新，trojan-go忽略http的服务
