### ISSUE TITLE
Oracle ARM  ubuntu问题

### ISSUE THREAD

**Issue by wangjiale1125** [mack-a/v2ray-agent#401]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 请在此处填写
环境：Oracle ARM ubuntu，手机V2rayNG连接节点vps就断网，整个机器无法ping通，无法ssh连接，断开连接几分钟之后就恢复正常

**2.安装失败的错误内容或者截图**
- 请在此处填写

**3.系统版本**
- 请在此处填写
Ubuntu20.04
**4.脚本版本**
- 请在此处填写
最新
**5.核心类型及版本**
- 请在此处填写
最新

**Comment by wangjiale1125** [comment]
2022/05/14 05:22:22 [Info] [2184641680] proxy/vless/inbound: realName = XXXXX
2022/05/14 05:22:22 [Info] [2184641680] proxy/vless/inbound: realAlpn = http/1.1
2022/05/14 05:22:22 [Info] [2184641680] proxy/vless/inbound: realPath = /okrxws
2022/05/14 05:22:22 [Info] [1772639544] proxy/vless/inbound: firstLen = 195
2022/05/14 05:22:22 [Info] [1772639544] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version

**Comment by mack-a** [comment]
找到问题了？
