### ISSUE TITLE
脚本与其他应用如何兼容？部署在nginx上的其他应用403，菜鸟懵圈中

### ISSUE THREAD

**Issue by clggwater** [mack-a/v2ray-agent#402]
做过如下尝试

纯净的Ubuntu系统，直接用脚本v2ray，安装完后代理正常，此时安装其他的应用，打开nginx配置这些应用，这些应用listen 80或者其他端口可以打开，但是listen 443，ssl，全部403 forbidden，查询之后说是权限问题，nginx conf里面直接改成user root，然后重启nginx，查看nginx进程发现nginx进程并未用户为root。后来直接把v2ray核心停掉了，然后nginx关闭，把nginx conf里面的user改成了root，重新安装v2ray，user改成了root，但是其他应用站点打开依然403 forbidden，是否和v2ray代理占用443端口有关？

全新的nginx配置文件，我只加了如下部分和修改了user root；
![image](https://user-images.githubusercontent.com/23073985/168414243-5426a397-9c7a-4f77-a3fe-c89ed1c48b21.png)
这部分是放在nginx根目录的nginx.conf里的，也尝试过放在conf.d里面新建一个配置文件，依然是403，我总感觉是个很简单的问题，但是我已经搞懵了。这部分我加的nginx配置里的证书是cloudflare下载的，而v2ray的证书是脚本生成的，是否有影响？

脚本自带的伪装站点稳得不行，一直都是能打开。

**Comment by mack-a** [comment]
Nginx已经被v2ray使用，请使用其他端口，或者修改默认的v2ray端口为其他端口

**Comment by clggwater** [comment]
> 443已经被v2ray使用，nginx请使用其他端口，或者修改默认的v2ray端口为其他端口

端口管理那里只有添加和删除，如何设置默认的v2ray端口为其他端口，修改v2ray配置文件夹内的配置文件吗？(如果是这个文件夹内应该修改哪个文件？)还是说修改nginx的alone.conf，感谢你的回复，不知道为啥没邮件通知，才看到。

一般来说，443端口配合二级域名，可以复用443端口的，这是v2ray的机制导致的无法复用吗？

**Comment by mack-a** [comment]
修改下v2ray 的配置文件，路径readme有

**Comment by stfei** [comment]
对v2ray不熟悉，但安装好看来这个脚本nginx是被放在v2ray后面的的。有没有能让nginx承载流量再反向到v2r里面的方法，这样nginx就比较方便来配置域名和端口。
