### ISSUE TITLE
acme.sh安装失败

### ISSUE THREAD

**Issue by fanofpal** [mack-a/v2ray-agent#404]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
-  安装acme.sh 失败

**2.安装失败的错误内容或者截图**
-  ---> 安装acme.sh 
  acme安装失败---> 
sh: 2: Syntax error: newline unexpected
错误排查: 
  1.获取Github文件失败，请等待Github恢复后尝试，恢复进度可查看 [https://www.githubstatus.com/] 
  2.acme.sh脚本出现bug，可查看[https://github.com/acmesh-official/acme.sh] issues 

**3.系统版本**
- Ubuntu18.04, Debian 9.4, Debian 10

**4.脚本版本**
- 2.5.70

**5.核心类型及版本**
- 4.15.0-22-generic
<img width="673" alt="截屏2022-05-20 下午6 56 14" src="https://user-images.githubusercontent.com/19284371/169513846-7bfc6d94-fa03-456f-a2d3-acbbf00e751d.png">

**Comment by mack-a** [comment]
curl -s https://get.acme.sh | sh -s  


执行一下看看
