### ISSUE TITLE
无法安装Xray -Core 

### ISSUE THREAD

**Issue by ouzc12358** [mack-a/v2ray-agent#407]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 启动脚本后，选择xray后退出脚本运行

**2.安装失败的错误内容或者截图**
- ![IMG_20220521_222610.jpg](https://user-images.githubusercontent.com/7533211/169656058-7f45cee0-a98e-499d-9a7e-19f19e8f557a.jpg)

**3.系统版本**
- CentOS 10.0

**4.脚本版本**
-v.2.5.70

**5.核心类型及版本**
- Xray-Core

**Comment by mack-a** [comment]
重新执行下试试，或者换一个shell
