### ISSUE TITLE
挂掉的很快

### ISSUE THREAD

**Issue by ouzc12358** [mack-a/v2ray-agent#408]
刚装好测试速度都没问题，很好用，但是仅过了30分钟就上不去了，更换网络也不行。
感觉很像以前未加密被ban的情况那时候我用vmess，但是其他几个服务器都运行正常，用的vless vmess 动态端口。

然后查了IP也没有问题，速度依然正常，域名正常，ping全绿。。。。

刚开始用这个脚本，这个问题有啥建议？

**Comment by mack-a** [comment]
通过 【 ping.pe 】 检查ip和端口是否出现异常，如端口被阻断可以通过添加端口解决【vasma->11】，如IP被阻断可使用CDN
