### ISSUE TITLE
在甲骨文云上安装失败，有如下提示：

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#41]
在甲骨文云上，使用centos、Ubuntu安装该脚本，均安装失败，均有如下提示信息。注：域名、dns均已正常解析，防火墙也开放了所有端口。

提示信息：
检查Nginx是否正常访问 
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析 以及防火墙设置是否正确--->

**Comment by AndersonGhost** [comment]
使用wulabing的V2Ray_ws-tls_bash_onekey一键脚本可以完美安装。

**Comment by mack-a** [comment]
> 在甲骨文云上，使用centos、Ubuntu安装该脚本，均安装失败，均有如下提示信息。注：域名、dns均已正常解析，防火墙也开放了所有端口。
> 
> 提示信息：
> 检查Nginx是否正常访问
> ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析 以及防火墙设置是否正确--->

有没有具体的报错

**Comment by AndersonGhost** [comment]
就是在提示输入vps 绑定域名的时候，正确输入了域名后，然后就弹出：

IP解析正确
检查Nginx是否正常访问
---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析 以及防火墙设置是否正确--->

然后就退出安装了。

**Comment by mack-a** [comment]
> 在甲骨文云上，使用centos、Ubuntu安装该脚本，均安装失败，均有如下提示信息。注：域名、dns均已正常解析，防火墙也开放了所有端口。
> 
> 提示信息：
> 检查Nginx是否正常访问
> ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析 以及防火墙设置是否正确--->

之前有人反馈过 也是甲骨文 他说他把网页上的防火墙关掉就可以了。可以参考一下。

**Comment by AndersonGhost** [comment]
谢谢大佬，根据您的提示，已经成功搭建！感谢！！！
