### ISSUE TITLE
Failed to enable unit: Unit file nginx.service does not exist.

### ISSUE THREAD

**Issue by rockszq** [mack-a/v2ray-agent#413]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- debian 10运行脚本报错

**2.安装失败的错误内容或者截图**
- Failed to enable unit: Unit file nginx.service does not exist.

**3.系统版本**
- 请在此处填写

**4.脚本版本**
- 请在此处填写

**5.核心类型及版本**
- 请在此处填写

**Comment by XstepAhead** [comment]
> > 请仔细填写每一项，并回复自己详细的错误信息
> 
> **1.问题描述**
> 
> * debian 10运行脚本报错
> 
> **2.安装失败的错误内容或者截图**
> 
> * Failed to enable unit: Unit file nginx.service does not exist.
> 
> **3.系统版本**
> 
> * 请在此处填写
> 
> **4.脚本版本**
> 
> * 请在此处填写
> 
> **5.核心类型及版本**
> 
> * 请在此处填写

nano /lib/systemd/system/nginx.service

put this
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target

save it
and then systemctl daemon-reload

**Comment by mack-a** [comment]
可以先退回上一个版本使用 新版本兼容性有问题

**Comment by mack-a** [comment]
版本已回退
