### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by rodericliu** [mack-a/v2ray-agent#416]
本人用该脚本在阿里云搭建了环境给公司内部使用，单人测试时没有任何问题，但是开放给公司内部后，出现访问中断，经查日志，发现xray那边报 too many open files. 系统默认的文件描述符不够，通过修改xray的systemd脚本，添加了NOFILE的数量，解决了该问题。

22022/06/20 11:48:38 [Warning] [4272866466] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31297 > common/retry: [dial tcp 127.0.0.1:31297: socket: too many open files] > common/retry: all retry attempts failed

希望可以在systemd启动脚本里添加上

_LimitNOFILE=65536
LimitNPROC=65536_

**Comment by mack-a** [comment]
只修改了xray的service吗

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.71

已修复
