### ISSUE TITLE
ubuntu22.04，nginx启动失败

### ISSUE THREAD

**Issue by FianW** [mack-a/v2ray-agent#419]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
使用服务器Atlantic云服务器，系统为ubuntu22.04LTS，x64，输入伪装域名后提示nginx启动失败。
已尝试卸载并手动安装nginx，尝试重置系统，问题依旧。

**2.安装失败的错误内容或者截图**

![IMG_0201](https://user-images.githubusercontent.com/58384236/177051930-db12df13-bdee-4004-a186-2047191c3eb2.jpeg)

**3.系统版本**
ubuntu 22.04LTS，x64

**4.脚本版本**
latest

**5.核心类型及版本**
全新安装xray-core

**Comment by FianW** [comment]
另外我在aws上安装一切正常，不知道是不是这个服务器的问题…

**Comment by FianW** [comment]
****

**Comment by mack-a** [comment]
手动启动下nginx看下错误日志

**Comment by FianW** [comment]
问题已解决。
手动启动nginx报错如下：
nginx: [emerg] could not build server_names_hash, you should increase server_nam
es_hash_bucket_size: 32

查看配置文件发现默认的etc/nginx/nginx.conf文件http字段中的server_nam
es_hash_bucket_size项不知道为什么被注释了…
删除注释符，并把默认值改成64或以上，然后就能顺利安装脚本了
