### ISSUE TITLE
大佬，出BUG了

### ISSUE THREAD

**Issue by ywyha** [mack-a/v2ray-agent#42]
全新环净安装
进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空---> 

进度  /17 : 初始化Nginx申请证书配置 
  域名不可为空--->

**Comment by mack-a** [comment]
更新26版本

**Comment by mack-a** [comment]
> 全新环净安装
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->
> 
> 进度 /17 : 初始化Nginx申请证书配置
> 域名不可为空--->

更新下2.1.26

**Comment by ywyha** [comment]
@mack-a 正常了，谢谢大佬
