### ISSUE TITLE
纯IPV6小鸡安装后无法使用

### ISSUE THREAD

**Issue by 16620671339** [mack-a/v2ray-agent#424]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 新安装的debian 11系统。nat64后正装安装好八合一脚本后。输入vasma显示xray正常。但导出来的链接无法使用代理。

**2.安装失败的错误内容或者截图**
- 安装正常。当前版本:v2.5.72 
Github:https://github.com/mack-a/v2ray-agent 
描述:八合一共存脚本
核心: Xray-core[运行中] 
已安装协议: VLESS+TCP[TLS/XTLS] Trojan+TCP[TLS] 

**3.系统版本**
- Linux 814323405hax.localdomain 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**4.脚本版本**
- 2.5.72

**5.核心类型及版本**
- xray 1.5.5

**Comment by mack-a** [comment]
添加nat64后进行尝试，可以多添加几个
