### ISSUE TITLE
希望新增自定义端口功能

### ISSUE THREAD

**Issue by Jacky-Bruse** [mack-a/v2ray-agent#425]
发生过好几次443端口被墙的事，每次还要进入配置文件进行修改，希望新增自定义端口功能，谢谢

**Comment by Jacky-Bruse** [comment]
> 发生过好几次443端口被墙的事，每次还要进入配置文件进行修改，希望新增自定义端口功能，谢谢

有这个功能，不好意思

**Comment by xclidongbo** [comment]
有吗？我怎么没找到？

**Comment by ikkyusan123** [comment]
> 发生过好几次443端口被墙的事，每次还要进入配置文件进行修改，希望新增自定义端口功能，谢谢

修改端口改哪个配置文件呀？是这个吗？文件路径：/etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json，我从443改成其他的端口，上不了网。
