### ISSUE TITLE
无法通过 CDN（Cloudflare）连接到服务器

### ISSUE THREAD

**Issue by FlandiaYingman** [mack-a/v2ray-agent#427]
目前已：
1. 通过脚本安装 V2Ray
2. 修改 CDN 节点为 www.cloudflare.com
3. 将 DNS 解析添加到 Cloudflare 中
4. 将 Cloudflare 的“云朵”设置为灰色（DNS Only)
5. 将 Cloudflare 的 SSL/TLS 选项设置为 Full
6. 开启 Cloudflare 的 Grpc 支持的选项
7. 刷新了脚本中的订阅，并将其导入到客户端中

结果为：
```
remote error: tls: handshake failure] > common/retry: all retry attempts failed
# 或
Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed
# 或
x509: certificate has expired or is not yet valid
```

请问是否哪里设置错误？或是遗漏了某些步骤？

补充：传输协议为 TCP（即直连服务器地址/域名的）时一切正常

**Comment by FlandiaYingman** [comment]
Close as solved

**Comment by noahge** [comment]
遇到了同样的问题，请教下是怎么解决的？

**Comment by FlandiaYingman** [comment]
@noahge 记不清楚细节了。关键在于 Cloudflare 的 TLS 不支持多级域名。即 Cloudflare 仅支持形如 `a.b.com` 而不是 `a.b.c.com` 的 TLS 证书申请。所以域名解析的时候别加太多层级就行了
