### ISSUE TITLE
移动端能正常使用，PC端异常

### ISSUE THREAD

**Issue by Cullwen** [mack-a/v2ray-agent#428]
ios，ipad的能正常翻墙
今天PC端的v2rayN突然报错，无法正常使用
v2rayN：
[Warning] [3475279779] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://cullwenvps1.tk/biipvws):  > x509: certificate has expired or is not yet valid:  transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://cullwenvps1.tk/biipvws):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed
脚本日志：
2022/08/04 08:30:55 [Warning] [2611171918] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:30:55 [Warning] [605858961] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:30:56 [Warning] [961856278] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:30:57 [Warning] [2934059049] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:30:58 [Warning] [2774771650] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:30:59 [Warning] [1947238566] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:31:00 [Warning] [1863192575] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:36:38 [Warning] [710474158] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:36:39 [Warning] [4265944899] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts failed
2022/08/04 08:36:41 [Warning] [2354786879] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:31300 > common/retry: [dial tcp 127.0.0.1:31300: connect: connection refused] > common/retry: all retry attempts fail

**Comment by mack-a** [comment]
检查下证书
