### ISSUE TITLE
订阅链接在一段时间后莫名无法使用

### ISSUE THREAD

**Issue by wjjzzdlzd** [mack-a/v2ray-agent#429]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 订阅链接在一段时间后莫名无法使用，确定非域名，IP问题。并且我的vps只运行这个脚本，其他程序均为出厂设置

**2.安装失败的错误内容或者截图**
- 该网页无法正常运作xxx.xxx.top 未发送任何数据。
ERR_EMPTY_RESPONSE

**3.系统版本**
- debian11
- Ubuntu 20.04.3 LTS

**4.脚本版本**
- v2.5.72

**5.核心类型及版本**
- xray1.55

**Comment by wjjzzdlzd** [comment]
重新安装后会解决问题，但是不知为何过段时间又会发生这种故障

**Comment by mack-a** [comment]
当订阅不可用时，节点是否可用

**Comment by wjjzzdlzd** [comment]
节点可用，不过某些情况下，trojan无法连接，其他协议正常。
触发原因不明，10台机器，出问题的大概有4台。
目前能肯定的是，在刚刚安装完毕时，是什么问题都没有的，而在长时间使用后会出现这个问题。但是也并不是每台机器都会出现故障。

**Comment by wjjzzdlzd** [comment]
今早重装后，暂时一切正常

**Comment by mack-a** [comment]
如果还出现此问题，按照节点->ping->端口检查，可使用 ping.pe

**Comment by mack-a** [comment]
如还遇到此问题，请重新打开此issues
