### ISSUE TITLE
升级Core有错误提示

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#43]
你好，升级Core有错误提示，升级后梯子正常。
![2020-12-12_102942](https://user-images.githubusercontent.com/9279217/101970419-3a281180-3c65-11eb-8c1e-af35e2d1ab72.jpg)

**Comment by mack-a** [comment]
> 你好，升级Core有错误提示，升级后梯子正常。
> 
> ![2020-12-12_102942](https://user-images.githubusercontent.com/9279217/101970419-3a281180-3c65-11eb-8c1e-af35e2d1ab72.jpg)
> 
> 

下次执行就会回复正常。

**Comment by smdx** [comment]
好的，感谢解答。
