### ISSUE TITLE
安装时直接失败，无法解析地址

### ISSUE THREAD

**Issue by Sousukes** [mack-a/v2ray-agent#431]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 无法解析此地址：raw.githubusercontent.com

**2.安装失败的错误内容或者截图**
- --2022-08-10 23:04:54--  https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’

**3.系统版本**
- Debian 10 64 Bit

**4.脚本版本**
- v2.5.72

**5.核心类型及版本**
- 无

**Comment by mack-a** [comment]
请更换dns尝试，如果ipv6请设置NAT64
