### ISSUE TITLE
不能检测到输入域名的IP

### ISSUE THREAD

**Issue by cnsnet** [mack-a/v2ray-agent#432]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 安装过程中输入域名后, 检测不到输入域名的IP

**2.安装失败的错误内容或者截图**
- 
![image](https://user-images.githubusercontent.com/1931457/185527547-bf9a8d2c-4f51-4726-a6be-6cec8215dcf3.png)

**3.系统版本**
- 搬瓦工Ubuntu 20.04

**4.脚本版本**
- 7天前的那个版本

**5.核心类型及版本**
- 不知道, 不知道怎么看

**Comment by mack-a** [comment]
按照提示处理，处理不成功建议dd系统
