### ISSUE TITLE
任意门落地机解锁流媒体不成功

### ISSUE THREAD

**Issue by binhe-cpu** [mack-a/v2ray-agent#433]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
任意门落地机解锁流媒体不成功

**2.安装失败的错误内容或者截图**
![image](https://user-images.githubusercontent.com/61576528/185529086-47b61ec7-aba7-4f08-90e3-7a980c2da16c.png)

**3.系统版本**

**4.脚本版本**
v2.5.73

**Comment by mack-a** [comment]
建议dd系统重新尝试
