### ISSUE TITLE
遇到相同问题，80和443端口都开着，但就是获取TSL证书失败，更换DNS后成功！

### ISSUE THREAD

**Issue by 18236176689** [mack-a/v2ray-agent#434]
遇到相同问题，80和443端口都开着，但就是获取TSL证书失败，更换DNS后成功！

_Originally posted by @Grefer in https://github.com/mack-a/v2ray-agent/issues/201#issuecomment-1126677044_

请问怎么换DNS

**Comment by mack-a** [comment]
建议Google一下
