### ISSUE TITLE
请教 搭建完成之后连不上网

### ISSUE THREAD

**Issue by githubvpn007** [mack-a/v2ray-agent#435]
> 我搭建的是 vless + XTLS  始终上不了网
![image](https://user-images.githubusercontent.com/86774805/186313684-2d8d5933-bf4b-4e8b-a65d-6b6a3579da78.png)

**1.问题描述**
我搭建的是 vless + XTLS  始终上不了网。
1. 我尝试切换了端口也不行，
2. 我确认域名解析没有问题，并且能ping 通。
3. 我尝试了linux 系统 Debian10 和centOS7  都尝试了，结果都一样不行
4. 我也尝试了 x-ui一键安装脚本。也是不行。 不知道我的是什么问题。请大神指教，已经自己折腾几天了
![image](https://user-images.githubusercontent.com/86774805/186316552-e438bf2b-202f-4d87-a014-1581d2240f99.png)
![image](https://user-images.githubusercontent.com/86774805/186316716-06409100-3c83-45a0-aa24-ae894842bffd.png)

**2.安装失败的错误内容或者截图**
这个是真连接测试的输出日志
![image](https://user-images.githubusercontent.com/86774805/186315650-5a58d420-06f2-41c7-b5b4-3d4722807e56.png)

**3.系统版本**
linux 系统是 Debian10 和centOS7  都尝试了，结果都一样。

**4.脚本版本**
v2.5.73

**5.核心类型及版本**
xray-core

**Comment by githubvpn007** [comment]
补充 我的客户端是v2rayN v5.31
![image](https://user-images.githubusercontent.com/86774805/186319302-66abe141-a11f-4f54-998e-2832730f219e.png)

**Comment by githubvpn007** [comment]
希望能有大神指教以下

**Comment by mack-a** [comment]
ping.pe检查下ip 是否被阻断
