### ISSUE TITLE
请问能否多入口配置多出口

### ISSUE THREAD

**Issue by wxjer** [mack-a/v2ray-agent#436]
因为服务器有多个ip，想问问怎么修改配置可以让多端口路由到不同的出口ip。

**Comment by wxjer** [comment]
看了xray的conf下面没有找到routing的配置

**Comment by mack-a** [comment]
修改节点的address地址为你的vps ip地址即可

**Comment by wxjer** [comment]
我自己创建一个routing.json 就行吧，名字需要带上序号么？我看其他json 用了01 02 10 这种序号命名。
