### ISSUE TITLE
Node Subscription with Traffic Forwarding (流量转发) Links

### ISSUE THREAD

**Issue by xenstar** [mack-a/v2ray-agent#437]
**详细描述建议的内容**

Hello. Recently I installed your script to deploy a vless + xtls protocol. It's working very smoothly. I also generate a subscription link through which I can easily import the servers in passwall (openwrt). But the problem that I am facing is, I am now using Traffic Forwarding Service "流量转发" and they generate different domain name and port for each tunnel. So this I have to manually change in the protocol settings and also it hard to keep track. 

e.g Landing Server is xyz.com:20050
Port Forwarding Server: blahblah.com:50050

Can you find a solution, where we can input these traffic forwarding links and port number, and it can update the traffic forwarding links in the subscription links automatically?  https://xyz.com/s/xyz.com_d74e1257444824ba1f66648c202f7c63

It can generate two Link:
1) With Direct Server Link (Which is currently there)
2) With Port Forwarding Link (Which you have to code it)

So in this way, if I am using the subscriptions link on multiple devices, it will be updated automatically. Doing it manually is confusing and time-consuming, and I often make mistakes. 

E.g In Subscription Link, there are 7 protocol settings listed. Port Forwarding Company: I added 5 More different tunnel configurations. So total is 7 x 5 = 35 Different configuration.

The logic and idea is pretty simple, it will not be hard for you to develop something like this. But in this way, we can also easily check which combination is giving the best and fastest result.

**Comment by xenstar** [comment]
How we can apply the Logic?

20: Traffic Forwarding Rules. (After we type 20), it will take to next step.

Type Traffic Forwarding / Tunnel Name: Guangzhou Mobile - HGC - Singapore gzmob-hgc-sg (Just example) Press enter

Type Port Number: 10077 (Port number that we setup in 咸蛋 panel)

Subscription Link - https://xyz.com/s/gzmob-hgc-sg_d74e1257444824ba1f66648c202f7c63

So in this way, we can add multiple combinations.

**Comment by mack-a** [comment]
Does not support

**Comment by xenstar** [comment]
I know doesn't support. But you can add in the future.
