### ISSUE TITLE
连封两个IP

### ISSUE THREAD

**Issue by iwyang** [mack-a/v2ray-agent#438]
昨天晚上突然发现代理用不了，ping了之后才发现IP被封了，于是就在搬瓦工后台申请换了一个ip。刚刚用新IP搭建了代理，没想到没用一会儿又被封了，这是什么情况呀，以前从来没有遇到过。

**Comment by mack-a** [comment]
bwh的ip是重灾区每当敏感节日都会这样

**Comment by iwyang** [comment]
> bwh的ip是重灾区每当敏感节日都会这样

那选择哪一种安装类型相对安全一些，选择VLESS+TCP+xtls-rprx-direct秒封。
