### ISSUE TITLE
安装证书时失败，有如下提示：

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#44]
........

检查Nginx是否正常访问 

 ---> Nginx配置成功 

进度  4/17 : 申请TLS证书 
 ---> 检测到错误证书，需重新生成，重新生成中 

进度  4/17 : 申请TLS证书 
 ---> 安装TLS证书 
[Wed Dec 16 16:15:44 UTC 2020] xxx.xxx.xxx:Verify error:During secondary validation: DNS problem: networking error looking up A for xxx.xxx.xxx
[Wed Dec 16 16:15:44 UTC 2020] Please add '--debug' or '--log' to check more details.
[Wed Dec 16 16:15:44 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/xxx.xxx.xxx_ecc/fullchain.cer: No such file or directory
 ---> TLS安装失败，请检查acme日志

**Comment by mack-a** [comment]
看日志 是dns的A记录有问题。

**Comment by mack-a** [comment]
> ........
> 
> 
> 
> 检查Nginx是否正常访问 
> 
> 
> 
>  ---> Nginx配置成功 
> 
> 
> 
> 进度  4/17 : 申请TLS证书 
> 
>  ---> 检测到错误证书，需重新生成，重新生成中 
> 
> 
> 
> 进度  4/17 : 申请TLS证书 
> 
>  ---> 安装TLS证书 
> 
> [Wed Dec 16 16:15:44 UTC 2020] xxx.xxx.xxx:Verify error:During secondary validation: DNS problem: networking error looking up A for xxx.xxx.xxx
> 
> [Wed Dec 16 16:15:44 UTC 2020] Please add '--debug' or '--log' to check more details.
> 
> [Wed Dec 16 16:15:44 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
> 
> cat: /root/.acme.sh/xxx.xxx.xxx_ecc/fullchain.cer: No such file or directory
> 
>  ---> TLS安装失败，请检查acme日志 
> 
> 
> 
> 

看日志 是dns的A记录有问题。

**Comment by mack-a** [comment]
看看A记录解析对吗

**Comment by AndersonGhost** [comment]
昨晚使用在线ping工具测试时，解析是正确的。
今天还是昨天的安装步骤，又顺利安装好了。
可能是等待了一晚上，解析完全正确了吧。
感谢大佬！
