### ISSUE TITLE
 jq: command not found

### ISSUE THREAD

**Issue by simplysexyboy** [mack-a/v2ray-agent#440]
进度  6/13 : 安装Xray
/root/install.sh: line 1315: jq: command not found
 ---> Xray-core版本:
unzip:  cannot find or open /etc/v2ray-agent/xray/Xray-linux-64.zip, /etc/v2ray-agent/xray/Xray-linux-64.zip.zip or /etc/v2ray-agent/xray/Xray-linux-64.zip.ZIP.
chmod: cannot access '/etc/v2ray-agent/xray/xray': No such file or directory

can not install the xray script because of the jq ?

**Comment by mack-a** [comment]
Try again after jq is installed
