### ISSUE TITLE
v2ray not work after upgrade to 5.10

### ISSUE THREAD

**Issue by BOBINIUNIU** [mack-a/v2ray-agent#441]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- v2ray can not start

**2.安装失败的错误内容或者截图**
- v2ray V5 does not appear to support the -confdir command anymore

**3.系统版本**
- Debian 11

**4.脚本版本**
- 2.5.74

**5.核心类型及版本**
- v2ray 5.10

**Comment by XDorz** [comment]
我也遇到这个问题了，可以先用v2ray内核稳定版4.32应应急，在选择内核那块输入3



功能 1/1 : 选择核心安装 

============================================================== 
1.Xray-core 
2.v2ray-core 
============================================================== 
请输入：3

**Comment by mack-a** [comment]
最新版已屏蔽v5
