### ISSUE TITLE
Can you upload english version of the latest please

### ISSUE THREAD

**Issue by achira22** [mack-a/v2ray-agent#442]

**Comment by xenstar** [comment]
Yes, english version codes are not updated.

**Comment by achira22** [comment]
Why, how tf i am gonna understand this

**Comment by LonelyJupiter** [comment]
> Why, how tf i am gonna understand this

why tf wouldn't u learn Chinese or try google translate at least smh

**Comment by cursedwraith** [comment]
> Why, how tf i am gonna understand this

u wont get anywhere with this kind of attitude. im english speaking person as well i just use google translate.

**Comment by xenstar** [comment]
> Why, how tf i am gonna understand this

As everyone suggested, you need to fix your attitude buddy. Also here is a tutorial for setting up Mack-A script in English - https://xenstar.xyz/proxy-series-part-2/

**Comment by xkjdox** [comment]
your attitude shows your character

**Comment by amebrahimi** [comment]
Use https://www.deepl.com/translator for translation.
It's superb

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/blob/master/documents/en/README_EN.md
