### ISSUE TITLE
[Feature Request] 请问能否增加生成clash订阅的功能？

### ISSUE THREAD

**Issue by zxkmm** [mack-a/v2ray-agent#443]
您好，请问能否增加生成clash订阅的功能？
ref. https://github.com/tindy2013/subconverter
感激不尽！

**Comment by mack-a** [comment]
目前不会考虑

**Comment by ajmz** [comment]
> 目前不会考虑

用最新的脚本生成链接，转换工具转为clash配置文件，clash.meta就是无法翻墙，非vision脚本也不行，不知什么原因。
还是希望agent能增加转为clash链接和订阅功能，谢谢。
