### ISSUE TITLE
Can't install the script in Nat Server

### ISSUE THREAD

**Issue by xenstar** [mack-a/v2ray-agent#444]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- So after I run the script, on step 3 the script will check whether port 443/80 is open or not, but in NAT servers, providers usually give us 20-30 different port for using. But according to your script logic, if port 443/80 is blocked, it can't go to next step. 

**2.安装失败的错误内容或者截图**
- ![image](https://user-images.githubusercontent.com/55502651/189332735-8db9461a-c6f8-43dc-8b75-8e5d42303385.png)

**3.系统版本**
- Debian 11

**4.脚本版本**
- v2.5.75

**5.核心类型及版本**
- Xray - Latest Core

**6 Solution**

In step 3, allow us to skip the 444/80 port check, for advanced users or allow us to select a port number, so the script can check accordingly with the port number given by the NAT provider.

**Comment by mack-a** [comment]
Not Supported
