### ISSUE TITLE
请求支持Cloudflare DNS认证获取证书

### ISSUE THREAD

**Issue by sjtuross** [mack-a/v2ray-agent#449]
**详细描述建议的内容**

避免依赖80和443端口

**Comment by THERentropy** [comment]
实际上你完全可以把你的证书重命名为网站名字，后缀不变，放到服务端/etc/v2ray-agent/tls目录下，这样子脚本就自动检测到你拥有的证书了不会重复获取

**Comment by mack-a** [comment]
下个版本支持，dev已经支持可以尝试使用

**Comment by sjtuross** [comment]
感谢大佬
