### ISSUE TITLE
重构版本

### ISSUE THREAD

**Issue by mack-a** [mack-a/v2ray-agent#45]
- [x] 1.去掉origin
- [x] 2.多文件配置文件
- [x] 3.ipv6的人机验证
- [x] 4.兼容ipv6 
- [x] 5.添加多用户配置
- [ ] 6.自定义安装时选择trojan-go，只安装trojan-go不再安装回落【可能放到下一个版本，也可能不写】
- [x] 7.自定义email地址

**Comment by wgedu** [comment]
期待新的版本！

**Comment by ywyha** [comment]
感谢大佬，挺需要IPV6的，有时候访问一些网站需要IPV6才能打开，而且是国外的IPV6才能打开……比如北邮人……大佬加油

**Comment by mack-a** [comment]
目前已基本完成，关掉此issue
