### ISSUE TITLE
Xray gRPC安装报错

### ISSUE THREAD

**Issue by jasonpeng02** [mack-a/v2ray-agent#450]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
-一键脚本安装提示报错

**2.安装失败的错误内容或者截图**
- <img width="931" alt="image" src="https://user-images.githubusercontent.com/107748782/190885894-31180145-d3e4-4f5e-805a-555ad8be4c15.png">

**3.系统版本**
- Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**4.脚本版本**
-wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**5.核心类型及版本**
Linux debian 5.10.0-10-arm64 #1 SMP Debian 5.10.84-1 (2021-12-08) aarch64

**Comment by mack-a** [comment]
使用脚本中的core功能重新启动内核就ok
