### ISSUE TITLE
安装好后 vmess 的连接不上，监听access日志提示 invalid user: VMessAEAD is enforced 

### ISSUE THREAD

**Issue by frankygang** [mack-a/v2ray-agent#451]
2022/09/18 22:52:02 36.67.25.194:64855 rejected  proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable xray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.

**Comment by mack-a** [comment]
更换客户端
