### ISSUE TITLE
搭建之后 连接出现：基础连接已经关闭：发送时发生错误

### ISSUE THREAD

**Issue by githubvpn007** [mack-a/v2ray-agent#454]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 客户端连接出现：基础连接已经关闭：发送时发生错误

**2.安装失败的错误内容或者截图**
![微信截图_20220928123011](https://user-images.githubusercontent.com/86774805/192688105-0751ee7d-9a54-46b9-8e49-eb03992ab492.png)

**3.系统版本**
- Debian 10 x64 (buster)

**4.脚本版本**
- v2.5.78

**5.核心类型及版本**
- xray 1.6

**Comment by mack-a** [comment]
请查看vps日志
