### ISSUE TITLE
aws 服务器安装失败 出现以下错误 请问是什么原因

### ISSUE THREAD

**Issue by XIXUANHAO** [mack-a/v2ray-agent#459]
- 
- 本脚本不支持此系统，请将下方日志反馈给开发者
 
\S
 on an \m 
Linux version 5.10.135-122.509.amzn2.x86_64 (mockbuild@ip-10-0-43-203) (gcc10-gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-21.amzn2.0.1) #1 SMP Thu Aug 11 22:41:16 UTC 2022

**Comment by XIXUANHAO** [comment]
第一次尝试了 debian11镜像也是报这个错误

然后第二次尝试了aws的Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type镜像 也是这个错误

都是x86的版本

**Comment by mack-a** [comment]
dd debian11试一下呢

**Comment by XIXUANHAO** [comment]
奇怪 好像是我点错了
