### ISSUE TITLE
Ubuntu 18.04.4 LTS 配置Nginx 失败 已经是root用户

### ISSUE THREAD

**Issue by silveryxx** [mack-a/v2ray-agent#46]
---> 配置Nginx 
touch: cannot touch '/etc/nginx/conf.d/alone.conf': No such file or directory
/root/install.sh: line 499: /etc/nginx/conf.d/alone.conf: No such file or directory
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
 ---> Nginx启动失败，请检查日志

**Comment by mack-a** [comment]
> ---> 配置Nginx
> touch: cannot touch '/etc/nginx/conf.d/alone.conf': No such file or directory
> /root/install.sh: line 499: /etc/nginx/conf.d/alone.conf: No such file or directory
> nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
> ---> Nginx启动失败，请检查日志

如果不是纯净系统，建议重新build一个系统然后再试

**Comment by silveryxx** [comment]
重建系统后OK了

**Comment by xman55555** [comment]
大佬,如何重建系统啊?

**Comment by 02015678** [comment]
`sudo apt-get remove --purge nginx`
