### ISSUE TITLE
安装成功，但是客户端连接总是失败提示context deadline exceeded

### ISSUE THREAD

**Issue by Angel0726** [mack-a/v2ray-agent#464]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 请在此处填写
脚本安装并且运行成功，没有失败。但是客户端总是无法连接，而且伪装网站也无法打开。不知道如何进行检查与排错
扫描了端口443端口扫描不到  80端口正常开启。这个正常吗？
<img width="946" alt="image" src="https://user-images.githubusercontent.com/32816780/195997737-cf576e0d-773d-480f-aec2-1d12dc62f04f.png">

**2.安装失败的错误内容或者截图**
- 请在此处填写
安装过程中没有任何错误

**3.系统版本**
- 请在此处填写
Debian10

**4.脚本版本**
- 请在此处填写
v2.5.78 

**5.核心类型及版本**
- 请在此处填写
v2ray、xray均存在此问题

**Comment by mack-a** [comment]
如果是VMess检查下时间，同时ping.pe检查端口，建议不要用443。

**Comment by Angel0726** [comment]
> 如果是VMess检查下时间，同时ping.pe检查端口，建议不要用443。

明白，我有几个1、使用的是vless

**Comment by mack-a** [comment]
1.VLESS和时间没关系
2.你这是国内已经屏蔽443端口
3.是用添加端口，建议高位端口。

最近一直再封禁端口，即使开了新端口也不一定100%保证不被继续封禁

**Comment by Angel0726** [comment]
> 1.VLESS和时间没关系 2.你这是国内已经屏蔽443端口 3.是用添加端口，建议高位端口。
> 
> 最近一直再封禁端口，即使开了新端口也不一定100%保证不被继续封禁

我也注意到在封锁端口了。我想问一下目前有什么解决办法吗？我注意到了https://github.com/mack-a/v2ray-agent/issues/456和https://github.com/net4people/bbs/issues/129发现大家众说纷云，也没有一个好的解决办法，使用utls吗？还是。。。套cdn太慢了

**Comment by mack-a** [comment]
目前没有好的解决方案

**Comment by Angel0726** [comment]
> 目前没有好的解决方案

添加端口如何添加？我使用主页面中的添加方法，添加之后不知道在哪里可以找到账户的二维码，不知道如何添加账户
