### ISSUE TITLE
这个项目有后门

### ISSUE THREAD

**Issue by liunian321** [mack-a/v2ray-agent#465]
**详细描述建议的内容**
服务器已经被黑,网卡被删.来源IP是美国新泽西.暂且不清楚有几层跳板.这个项目的代码还没有时间查看.新服务器只装了这个非官方的东西,基本可以确定有后门.

**Comment by mack-a** [comment]
有意思

**Comment by qingmuhy** [comment]
我也有一台服务器也是这样的，啥都没装就被黑了，系统是ubuntu的，除了Linux内核其他都是Ubuntu的软件包，都被人拿去发垃圾邮件了，基本可以确定ubuntu官方留后门了，建议慎用Ubuntu！

**Comment by lumaster** [comment]
新装机子先改端口＋fail2ban

**Comment by KyonCN** [comment]
您时间这么宝贵，代码就别看了，先去医院看下脑科比较重要

**Comment by JesseLuoab** [comment]
用了mack-a的脚本2年多，至少在4个不同的vps上部署过，没遇到过什么问题。感谢作者的分享。
