### ISSUE TITLE
SS白名单模式 防火墙未安装，请手动安装

### ISSUE THREAD

**Issue by watchingfun** [mack-a/v2ray-agent#466]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- SS白名单模式 防火墙未安装，请手动安装 （还有就是可否不安装v2ray只安装ss啊） 

**2.安装失败的错误内容或者截图**
- 
![uTools_1665968723216](https://user-images.githubusercontent.com/22067924/196068833-aec43b4e-3187-4ab7-95f6-70e0c58e2452.png)

**3.系统版本**
- Debian 11

**4.脚本版本**
- shadowsocks 动态IP白名单模式【Beta】

**5.核心类型及版本**
- shadowsocks 动态IP白名单模式【Beta】

是否和该处判断有关
![uTools_1665968867762](https://user-images.githubusercontent.com/22067924/196069004-e40e1c86-7707-4596-bebe-240dcbbf318e.png)

**Comment by mack-a** [comment]
如果有条件可以自己fork改一下，目前这个版本维护成本较高，应该不会继续维护

**Comment by watchingfun** [comment]
> 如果有条件可以自己fork改一下，目前这个版本维护成本较高，应该不会继续维护

大佬不好意思再打扰下，防火墙问题我换成firewalld搞定了，window上用v2rayN配置后能使用，但是Android上我找不到能用的客户端，是因为v2ray-plugin的ws不支持path选项吗，我看其官网没写，如果我要去掉path该如何修改啊

**Comment by mack-a** [comment]
> > 如果有条件可以自己fork改一下，目前这个版本维护成本较高，应该不会继续维护
> 
> 大佬不好意思再打扰下，防火墙问题我换成firewalld搞定了，window上用v2rayN配置后能使用，但是Android上我找不到能用的客户端，是因为v2ray-plugin的ws不支持path选项吗，我看其官网没写，如果我要去掉path该如何修改啊

安卓的我不是很清楚 帮不到你
