### ISSUE TITLE
如果不乐意别人加TG群，麻烦把简介里的链接删掉

### ISSUE THREAD

**Issue by takoa1573** [mack-a/v2ray-agent#467]
加了群，还想着看看项目有没有新进展。进去2分钟直接被拉黑踢了，一脸懵逼……我寻思链接不是你放在项目简介里的么……

**Comment by takoa1573** [comment]
> 你的tg名字是什么，我查一下是怎么被踢的

Takoa

**Comment by mack-a** [comment]
你是被机器人踢了，答题超时封禁
