### ISSUE TITLE
老哥，你看看这个人对443端口被封的解决方法可行嘛？

### ISSUE THREAD

**Issue by ElementBridge** [mack-a/v2ray-agent#472]
**详细描述建议的内容**
老哥，你看看这个人对443端口被封的解决方法可行嘛？
https://zgao.top/trojan-443%e7%ab%af%e5%8f%a3%e8%a2%ab%e5%b0%81%e7%9a%84%e7%ae%80%e5%8d%95%e8%a7%a3%e5%86%b3%e6%80%9d%e8%b7%af/#more-3665

**Comment by mack-a** [comment]
不解决根本问题，可以尝试下 Hysteria。
