### ISSUE TITLE
伪装站打开显示error 521，重定向302设置失败

### ISSUE THREAD

**Issue by suyeonku** [mack-a/v2ray-agent#480]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 用脚本配置好协议后，能够正常富强，但是打开伪装网址显示error 521，防火墙关掉或者放行端口仍然显示error 521，重装之后也是如此.伪装站更换别的模板还是error 521 ，重定向302输入示例网址显示设置失败

**2.安装失败的错误内容或者截图**
-The web server is not returning a connection. As a result, the web page is not displaying.

**3.系统版本**
- ubuntu 20.04

**4.脚本版本**
- v2.6.5

**5.核心类型及版本**
- xray-core 1.6.1

**Comment by mack-a** [comment]
把cdn关掉试试

**Comment by suyeonku** [comment]
http可以访问到伪装站点，https还是显示Error code 521，302重定向仍然无法设置

**Comment by mack-a** [comment]
截图
