### ISSUE TITLE
请教，安装到证书那一步出问题了

### ISSUE THREAD

**Issue by JduenznnxjSj** [mack-a/v2ray-agent#482]
---> 安装TLS证书 

============================================================== 
1.letsencrypt[默认] 
2.zerossl 
3.buypass[不支持DNS申请] 
============================================================== 
请选择[回车]使用默认:

 ---> 请手动添加DNS TXT记录 
 --->  name：_acme-challenge 
 --->  value：jgTB8_imZNSoqPf2CQJd-nSJA4CU9rCplJKktCQ182U 
 ---> 添加完成后等请等待1-2分钟 

是否添加完成[y/n]:y
 ---> 验证失败，请等待1-2分钟后重新尝试 
[root@vultr ~]#

**Comment by JduenznnxjSj** [comment]
@mack-a 可以帮忙看看嘛

**Comment by mack-a** [comment]
如果不会使用dns申请证书，建议不要自定义端口

**Comment by JduenznnxjSj** [comment]
我是选了默认的，但是我443端口被墙了

**Comment by JduenznnxjSj** [comment]
@mack-a 我的端口已经被墙了呢...

**Comment by JduenznnxjSj** [comment]
@mack-a 通了，谢谢大神。请问怎么打赏

**Comment by JduenznnxjSj** [comment]
这个订阅的shadowsock适用嘛
