### ISSUE TITLE
脚本安装成功，伪装网站也能打开，使用V2RAY N 链接上，无网。

### ISSUE THREAD

**Issue by henhuo** [mack-a/v2ray-agent#485]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 脚本安装成功，伪装网站也能打开，使用V2RAY N 链接上，无网。 买的是菲律宾IP，但伪装出来的成了香港的。手机客户端V2ray N链接失败。

**2.安装失败的错误内容或者截图**
![微信图片_20221108171442](https://user-images.githubusercontent.com/117635922/200524161-1f34e702-0fdc-4aae-9ce2-a6d4826fcd1c.jpg)

- 100  214k  100  214k    0     0   210k      0  0:00:01  0:00:01 --:--:--  210k
[Tue Nov  8 16:05:53 HKT 2022] Installing from online archive.
[Tue Nov  8 16:05:53 HKT 2022] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue Nov  8 16:05:55 HKT 2022] Extracting master.tar.gz
[Tue Nov  8 16:05:55 HKT 2022] Installing to /root/.acme.sh
[Tue Nov  8 16:05:55 HKT 2022] Installed to /root/.acme.sh/acme.sh
[Tue Nov  8 16:05:55 HKT 2022] Installing alias to '/root/.bashrc'
[Tue Nov  8 16:05:55 HKT 2022] OK, Close and reopen your terminal to start using acme.sh
[Tue Nov  8 16:05:55 HKT 2022] Installing cron job
no crontab for root
no crontab for root
[Tue Nov  8 16:05:55 HKT 2022] Good, bash is found, so change the shebang to use bash as preferred.
[Tue Nov  8 16:0

9 HKT 2022] OK
[Tue Nov  8 16:05:59 HKT 2022] Install success!
[Tue Nov  8 16:05:33 HKT 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Tue Nov  8 16:05:33 HKT 2022] Standalone mode.
[Tue Nov  8 16:05:33 HKT 2022] Create account key ok.
[Tue Nov  8 16:05:33 HKT 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Tue Nov  8 16:05:35 HKT 2022] Registered
[Tue Nov  8 16:05:35 HKT 2022] ACCOUNT_THUMBPRINT='aoHctNCARnFoLLnruQtV5zDhF-Gtc2YObniALYZkjMI'
[Tue Nov  8 16:05:35 HKT 2022] Creating domain key
[Tue Nov  8 16:05:35 HKT 2022] The domain key is here: /root/.acme.sh/u.xraymh.asia_ecc/u.xraymh.asia.key
[Tue Nov  8 16:05:35 HKT 2022] Single domain='u.xraymh.asia'
[Tue Nov  8 16:05:35 HKT 2022] Getting domain auth token for each domain
[Tue Nov  8 16:05:38 HKT 2022] Getting webroot for domain='u.xraymh.asia'
[Tue Nov  8 16:05:38 HKT 2022] Verifying: u.xraymh.asia
[Tue Nov  8 16:05:38 HKT 2022] Standalone mode server
[Tue Nov  8 16:05:40 HKT 2022] Pending, The CA is processing your order, please just wait. (1/30)
[Tue Nov  8 16:05:43 HKT 2022] Success
[Tue Nov  8 16:05:43 HKT 2022] Verify finished, start to sign.
[Tue Nov  8 16:05:43 HKT 2022] Lets finalize the order.
[Tue Nov  8 16:05:43 HKT 2022] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/814154637/142054200767'
[Tue Nov  8 16:05:45 HKT 2022] Downloading cert.
[Tue Nov  8 16:05:45 HKT 2022] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0492421f8babb313f178eb41411d4193952a'
[Tue Nov  8 16:05:46 HKT 2022] Cert success.
-----BEGIN CERTIFICATE-----
MIIEVTCCAz2gAwIBAgISBJJCH4ursxPxeOtBQR1Bk5UqMA0GCSqGSIb3DQEBCwUA
、、、、、
-----END CERTIFICATE-----
[Tue Nov  8 16:05:46 HKT 2022] Your cert is in: /root/.acme.sh/u.xraymh.asia_ecc/u.xraymh.asia.cer
[Tue Nov  8 16:05:46 HKT 2022] Your cert key is in: /root/.acme.sh/u.xraymh.asia_ecc/u.xraymh.asia.key
[Tue Nov  8 16:05:46 HKT 2022] The intermediate CA cert is in: /root/.acme.sh/u.xraymh.asia_ecc/ca.cer
[Tue Nov  8 16:05:46 HKT 2022] And the full chain certs is there: /root/.acme.sh/u.xraymh.asia_ecc/fullchain.cer

[**3.系统版本**]()
- Debian11

**4.脚本版本**
- Xray-core版本:v1.6.1

**5.核心类型及版本**
当前版本:v2.6.6 

有的VPS，一次安装成功。能正常安装。 有的VPS安装后，就出现上面这种情况。

求大神告知，如何解决。

**Comment by mack-a** [comment]
检查443端口是否被阻断，如果阻断可使用添加端口功能

**Comment by henhuo** [comment]
> 检查 443 端口是否可以使用，方便使用

![微信图片_20221108185516](https://user-images.githubusercontent.com/117635922/200546665-6611f0ea-7cd0-452d-b47d-f2205ee86462.png)
443端口检测可用。

**Comment by Luck-Love** [comment]
请问一下 你的问题解决了吗？ 我的也无法使用。
