### ISSUE TITLE
希望支持xtls-rprx-vision流控

### ISSUE THREAD

**Issue by sdshdv** [mack-a/v2ray-agent#489]
https://github.com/XTLS/Xray-core/pull/1235

希望支持xray1.6.3版本更新的全新流控方案

**Comment by mack-a** [comment]
目前手头还没有可用的客户端，等有可用的客户端 的时候会更新

**Comment by haomuch** [comment]
> 目前手头还没有可用的客户端，等有可用的客户端 的时候会更新

不会吧，v2rayN和v2rayNG都已经支持vision流控了呀

**Comment by haomuch** [comment]
现有的xtls流控即使增加utls指纹也根本无法防止被封端口，亟需mack大佬更新vision流控来拯救我们啊~

**Comment by mack-a** [comment]
> > 目前手头还没有可用的客户端，等有可用的客户端 的时候会更新
> 
> 不会吧，v2rayN和v2rayNG都已经支持vision流控了呀

我只用Clash和小火煎这两个更新就会跟进

**Comment by sjtuross** [comment]
passwall也支持了
