### ISSUE TITLE
最新版本hysteria上下行宽带带宽设置问题

### ISSUE THREAD

**Issue by usaxyh** [mack-a/v2ray-agent#490]
目前的脚本有问题，比如我家宽带下行300mbps，上行45mbps，脚本执行完毕后服务端config可见如下：
 "up_mbps": 45,
  "down_mbps": 300,
但实际测速最高也只有45mbps。服务端带宽设置上行应该对应客户端下行，服务端下行对应客户端上行。
脚本带宽设置应和客户端带宽设置相反。

请修改脚本

**Comment by mack-a** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/57424792/201020675-ac3fd34d-41f7-4f44-867d-a36c535970f6.png">

**Comment by mack-a** [comment]
你可以试下一下手动删除服务端的up和down再测试一下  /etc/v2ray-agent/hysteria/conf/config.json 配置文件的地址

**Comment by usaxyh** [comment]
> 你可以试下一下手动删除服务端的up和down再测试一下 /etc/v2ray-agent/hysteria/conf/config.json 配置文件的地址

是的，我现在手动修改过已经正常了。谢谢

**Comment by mack-a** [comment]
> > 你可以试下一下手动删除服务端的up和down再测试一下 /etc/v2ray-agent/hysteria/conf/config.json 配置文件的地址
> 
> 是的，我现在手动修改过已经正常了。谢谢

删除之后就正常了吗

**Comment by usaxyh** [comment]
> > > 你可以试下一下手动删除服务端的up和down再测试一下 /etc/v2ray-agent/hysteria/conf/config.json 配置文件的地址
> > 
> > 
> > 是的，我现在手动修改过已经正常了。谢谢
> 
> 删除之后就正常了吗
删除之后正常了。在服务端设置把up和down反过来写也可以正常工作，如下：
  "up_mbps":300,
  "down_mbps": 45,
  "alpn": "h3",
  "recv_window_conn": 15728640,
  "recv_window_client": 67108864,
  "max_conn_client": 4096,
  "disable_mtu_discovery": true,
  "resolve_preference": "46",
  "resolver": "https://8.8.8.8:443/dns-query"
目前的脚本：
本地带宽上行对应服务端config up_mbps
本地带宽下行对应服务端config down_mbps

应修改为如下比较合理：
本地带宽上行对应服务端下行（"down_mbps": 45,）
本地带宽下行对应服务端上行（"up_mbps":300,）

**Comment by mack-a** [comment]
最新版已移除这个服务端的配置
