### ISSUE TITLE
使用ZeroSSL申请证书之后。无法使用vasma的更新证书选项查看和续期。

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#493]
**1.问题描述**
测试使用ZeroSSL申请证书之后。无法使用vasma的更新证书选项查看和续期。
会提示 “未安装”。

ps. 询问“是否使用DNS申请证书[y/n]:” 选择的是n

**2.脚本版本**
v2.6.12

**Comment by mack-a** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/57424792/202336472-7591a2c7-4263-4e9f-96be-c413756f7c19.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/57424792/202336577-2899b075-e7f6-4ecf-95b2-4b4dbec83e0c.png">

安装2.zerossl没有复现你说的问题，建议卸载后用最新脚本重新安装
