### ISSUE TITLE
euserv纯IPV6机器无法安装acme.sh

### ISSUE THREAD

**Issue by necoic** [mack-a/v2ray-agent#494]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
euserv纯IPV6机器无法安装acme.sh

echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" >> /etc/resolv.conf 命令失效

**2.安装失败的错误内容或者截图**
进度  1/17 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】 
 ---> 安装binutils 
 ---> 安装lsb-release 
 ---> 安装semanage 
 ---> 安装acme.sh 
  acme安装失败---> 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  214k  100  214k    0     0  3897k      0 --:--:-- --:--:-- --:--:-- 3969k
[Tue 15 Nov 2022 02:40:21 AM CST] Installing from online archive.
[Tue 15 Nov 2022 02:40:21 AM CST] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue 15 Nov 2022 02:40:21 AM CST] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Tue 15 Nov 2022 02:40:21 AM CST] Download error.
Install error
中国大陆用户请参考:
https://github.com/acmesh-official/acme.sh/wiki/Install-in-China
错误排查: 
  1.获取Github文件失败，请等待Github恢复后尝试，恢复进度可查看 [https://www.githubstatus.com/] 
  2.acme.sh脚本出现bug，可查看[https://github.com/acmesh-official/acme.sh] issues 
  3.如纯IPv6机器，请设置NAT64,可执行下方命令 
  echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" >> /etc/resolv.conf 

**3.系统版本**
Debian 10/11

**4.脚本版本**
v2.6.12 

**5.核心类型及版本**
Xray

**Comment by mack-a** [comment]
nat64设置了吗

**Comment by necoic** [comment]
设置了 并没有效果

mack-a ***@***.***> 于 2022年11月15日周二 上午10:14写道：
