### ISSUE TITLE
无法自动创建 /tmp/v2ray

### ISSUE THREAD

**Issue by shanyouli** [mack-a/v2ray-agent#5]
当服务器重启并删除了 /tmp/v2ray 文件夹， v2ray 服务启动会因为无法发现 /tmp/v2ray/v2ray_access_ws_tls.log 而失败，具体日志如下：
```
main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /tmp/v2ray/v2ray_access_ws_tls.log: no such file or directory
```
建议将日志文件放在 /var/v2ray或者v2ray服务启动时，检查一下 `/tmp/v2ray` 是否创建。

**Comment by mack-a** [comment]
感谢反馈

shanyouli <notifications@github.com>于2020年7月22日 周三13:08写道：

**Comment by mack-a** [comment]
> 当服务器重启并删除了 /tmp/v2ray 文件夹， v2ray 服务启动会因为无法发现 /tmp/v2ray/v2ray_access_ws_tls.log 而失败，具体日志如下：
> 
> ```
> main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /tmp/v2ray/v2ray_access_ws_tls.log: no such file or directory
> ```
> 
> 建议将日志文件放在 /var/v2ray或者v2ray服务启动时，检查一下 `/tmp/v2ray` 是否创建。

已修复
