### ISSUE TITLE
升级2.2.2后无法检测到core

### ISSUE THREAD

**Issue by Protamandua** [mack-a/v2ray-agent#50]
2.2.1升级脚本到2.2.2后，点击选项9升级xray：

请选择:9

 ---> 没有检测到安装目录，请执行脚本安装内容

查看日志，提示同上。
查看账号，仅显示trojan信息。

查看/etc/v2ray-agent/xray目录存在，v2ray目录存在
可以正常连接

**Comment by mack-a** [comment]
需要重新安装
