### ISSUE TITLE
未检测到当前域名的ip cf已经解析ip

### ISSUE THREAD

**Issue by zudaz** [mack-a/v2ray-agent#500]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 未检测到当前域名的ip cf已经解析ip

**2.安装失败的错误内容或者截图**
- 
![image](https://user-images.githubusercontent.com/115730635/202913764-66b40e52-d0f5-4551-85d6-5875d2c0ebeb.png)

**3.系统版本**
- debian 10
**4.脚本版本**
- v2.6.13 

**5.核心类型及版本**
- Xray-core

**Comment by mack-a** [comment]
1.图中检查项依次检查
2.dd系统后重新安装
