### ISSUE TITLE
卡在安装Xray不动了

### ISSUE THREAD

**Issue by zycboss** [mack-a/v2ray-agent#507]
**1.问题描述**
之前使用一切正常
今天想更新一下Xray-core到1.6.5版，结果更新的时候卡在下载v1.6.5，卡了十几分钟没动，我就ctrl+C结束了
重新vasma打开，发现xray没了，core管理显示未安装
于是重走流程安装，但是现在进度一直卡在安装Xray，无法继续了
尝试重启，
systemctl stop xray
systemctl disable xray
再次安装依然卡在安装Xray这一步
确定网络连接是正常的

**2.安装失败的错误内容或者截图**

进度  8/17 : 安装Xray
 ---> Xray-core版本:v1.6.1

**3.系统版本**
Ubuntu 18 LTS 

**4.脚本版本**
2.6.13

**5.核心类型及版本**
6.0.7-x64v2-rt14-xanmod1

**Comment by mack-a** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/57424792/204239139-2161cf60-ae71-4e60-afc6-1503a46804f1.png">
未发现问题，建议排查下vps的网络（如dns）

**Comment by zycboss** [comment]
找到原因了，/etc/resolv.conf里面不知道为什么ipv4的DNS全没了，只剩ipv6的了，估计是下载的时候ipv6 DNS解析不到github的地址卡住了，加上ipv4的DNS就好了

不过新问题又出现了……卸载之前是用grpc的，现在重新装了以后grpc突然用不了了……ws和tcp正常，我去研究下为啥
