### ISSUE TITLE
BUG汇总

### ISSUE THREAD

**Issue by mack-a** [mack-a/v2ray-agent#51]

**Comment by mack-a** [comment]
- Ubuntu update、upgrade 使用错误
- 自定义路径只截取前四个字符
- 证书过期重新安装后还是过期证书

**Comment by KyonCN** [comment]
1. debian 8下 ping 命令参数 -4 错误
2. ubuntu18.04 v2ray核心管理 日志查看 打开一闪而过就退回主页

**Comment by mack-a** [comment]
> 1. debian 8下 ping 命令参数 -4 错误
> 2. ubuntu18.04 v2ray核心管理 日志查看 打开一闪而过就退回主页
> 3. 安装生成的tcp xtls 通用json无法使用

详细描述一下第三个错误，内核版本 安装类型等等

**Comment by mack-a** [comment]
> 1. debian 8下 ping 命令参数 -4 错误
> 2. ubuntu18.04 v2ray核心管理 日志查看 打开一闪而过就退回主页
> 3. 安装生成的tcp xtls 通用json无法使用

第二个的查看日志因为是查看日志所以展示完就会退回主页。
第二个的V2ray的核心管理现在已经更名为core核心管理，不确定是不是那个版本有问题。还是说是安装v2ray然后使用核心管理会这样，可以详细描述下

**Comment by ArthurXL2G** [comment]
ipv6人机验证，选择后没有反应

**Comment by mack-a** [comment]
> ipv6人机验证，选择后没有反应

系统版本

**Comment by ArthurXL2G** [comment]
> > ipv6人机验证，选择后没有反应
> 
> 系统版本

Linux version 5.10.0 (root@osboxes) (gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1 SMP Mon Dec 14 07:04:47 UTC 2020
 另外升级了BBR内核：
 当前内核为：5.10.0
 当前状态: 已安装 BBR 加速内核 , BBR启动成功
 当前拥塞控制算法为: bbr 当前队列算法为: fq

**Comment by ArthurXL2G** [comment]
![done](https://user-images.githubusercontent.com/62242396/102851566-2778be00-4457-11eb-8afd-ab2e5697c93d.jpg)
已解决，HE申请的IPV6没有配置正常，感谢： ）

**Comment by KyonCN** [comment]
以下都是基于xray-core1.1.4 和最新版v2-agent centos7.3 5.6.15

>  名为core核心管理，不确定是不是那

  我去测试了一下 核心管理的bug是因为将脚本升级为最新版后再去升级core导致的，完全卸载后重装就没问题了
> 详细描述一下第三个错误，内核版本 安装类型等等

 生成的json qv2ray 下无法导入 不过这可能是qv2ray的问题 因为貌似手动编辑流控为splice都启动不了

**Comment by mack-a** [comment]
> 以下都是基于xray-core1.1.4 和最新版v2-agent centos7.3 5.6.15
> 
> > 名为core核心管理，不确定是不是那
> 
> 我去测试了一下 核心管理的bug是因为将脚本升级为最新版后再去升级core导致的，完全卸载后重装就没问题了
> 
> > 详细描述一下第三个错误，内核版本 安装类型等等
> 
> 生成的json qv2ray 下无法导入 不过这可能是qv2ray的问题 因为貌似手动编辑流控为splice都启动不了

那就现在是木有问题了

**Comment by danerlt** [comment]
![image](https://user-images.githubusercontent.com/14197717/102950391-81d05800-4505-11eb-8be2-bcf7b81c793a.png)
安装会失败

**Comment by danerlt** [comment]
![image](https://user-images.githubusercontent.com/14197717/102950641-fc997300-4505-11eb-8f85-65d1f5bc46ca.png)
应该是启动xray的时候报错了

**Comment by mack-a** [comment]
> ![image](https://user-images.githubusercontent.com/14197717/102950641-fc997300-4505-11eb-8f85-65d1f5bc46ca.png)
> 应该是启动xray的时候报错了

我脚本里面的service不是这样的呀，应该反馈错地方了

**Comment by mack-a** [comment]
> ![image](https://user-images.githubusercontent.com/14197717/102950391-81d05800-4505-11eb-8be2-bcf7b81c793a.png)
> 安装会失败

这个应该是用别的脚本安装过，需要删除以前的或者直接重新build系统。

**Comment by danerlt** [comment]
@mack-a 是的,我把之前安装的卸载调就可以重新安装了

**Comment by fredericky123** [comment]
> ![done](https://user-images.githubusercontent.com/62242396/102851566-2778be00-4457-11eb-8afd-ab2e5697c93d.jpg)
> 已解决，HE申请的IPV6没有配置正常，感谢： ）

请问你是怎么配置的，HE配置可以实现谷歌云分配ipv6地址，然后通过这个脚本解决人机访问是吗？

**Comment by ArthurXL2G** [comment]
> > ![done](https://user-images.githubusercontent.com/62242396/102851566-2778be00-4457-11eb-8afd-ab2e5697c93d.jpg)
> > 已解决，HE申请的IPV6没有配置正常，感谢： ）
> 
> 请问你是怎么配置的，HE配置可以实现谷歌云分配ipv6地址，然后通过这个脚本解决人机访问是吗？

我谷歌云不需要人机验证，没使用此功能，HE申请是为了给本身不提供IPV6的VPS的解决办法

**Comment by sdc9088** [comment]
![QQ截图20201229140236](https://user-images.githubusercontent.com/26533528/103262020-97022680-49de-11eb-969e-1098140b5d85.png)

debian9,debian10 都会出现如图的问题。

**Comment by sdc9088** [comment]
![20201229140236](https://user-images.githubusercontent.com/26533528/103262501-13e1d000-49e0-11eb-931d-d716074c8e72.jpg)

在dedebian9.13he debian10中安装都会出现上面的问题。

**Comment by mack-a** [comment]
> ![20201229140236](https://user-images.githubusercontent.com/26533528/103262501-13e1d000-49e0-11eb-931d-d716074c8e72.jpg)
> 
> 在dedebian9.13he debian10中安装都会出现上面的问题。

看脚本的提示，现实该系统安装过nginx，请先卸载掉自编译的nginx或者重新build再安装

**Comment by PerseSniper** [comment]
大佬们，使用trojan 的安装方式， 我手机端使用V2rayNG 导入trojan格式地址，无法访问  失败:net/http: http/1.x transport connection broken： malformed http  response

**Comment by mack-a** [comment]
> 大佬们，使用trojan 的安装方式， 我手机端使用V2rayNG 导入trojan格式地址，无法访问 失败:net/http: http/1.x transport connection broken： malformed http response

尝试手动输入

**Comment by PerseSniper** [comment]
> > 大佬们，使用trojan的安装方式，我手机端使用V2rayNG导入trojan格式地址，无法访问失败：net / http：http / 1.x传输连接断开：格式错误的http响应
> 
> 尝试手动输入

一样的是这个错误。我感觉是 v2rayng软件原因。我下了好多支持 trojan 感觉是集体雪崩了啊

**Comment by PerseSniper** [comment]
> > 大佬们，使用trojan 的安装方式， 我手机端使用V2rayNG 导入trojan格式地址，无法访问 失败:net/http: http/1.x transport connection broken： malformed http response
> 
> 尝试手动输入

大佬你安卓端用的什么软件

**Comment by mack-a** [comment]
> > > 大佬们，使用trojan 的安装方式， 我手机端使用V2rayNG 导入trojan格式地址，无法访问 失败:net/http: http/1.x transport connection broken： malformed http response
> > 
> > 
> > 尝试手动输入
> 
> 大佬你安卓端用的什么软件

我用iOS

**Comment by PerseSniper** [comment]
> > > > 大佬们，使用trojan 的安装方式， 我手机端使用V2rayNG 导入trojan格式地址，无法访问 失败:net/http: http/1.x transport connection broken： malformed http response
> > > 
> > > 
> > > 尝试手动输入
> > 
> > 
> > 大佬你安卓端用的什么软件
> 
> 我用iOS

我测试ios 是没问题的。好吧。谢谢大佬。

**Comment by PerseSniper** [comment]
大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动  把 path地址填上去

**Comment by mack-a** [comment]
> 大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动 把 path地址填上去

客户端用的啥

**Comment by PerseSniper** [comment]
> > 大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动 把 path地址填上去
> 
> 客户端用的啥

安卓 V2rayNg

**Comment by PerseSniper** [comment]
![image](https://user-images.githubusercontent.com/47959291/103399755-606bff00-4af7-11eb-96fc-cb50ce397aad.png)
![image](https://user-images.githubusercontent.com/47959291/103399772-6eba1b00-4af7-11eb-92c1-c8d9874e0f25.png)

**Comment by mack-a** [comment]
path好长，如果手动输入短一些看看能展示出来不

**Comment by PerseSniper** [comment]
> path好长，如果手动输入短一些看看能展示出来不

好

**Comment by PerseSniper** [comment]
![image](https://user-images.githubusercontent.com/47959291/103399976-4a127300-4af8-11eb-9273-76b42b47f04d.png)
![image](https://user-images.githubusercontent.com/47959291/103399987-54347180-4af8-11eb-9a19-ebbe779818ef.png)
一样的出不来

**Comment by mack-a** [comment]
> 大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动 把 path地址填上去

安装方式和内核版本说一下

**Comment by PerseSniper** [comment]
安装方式:VMess+TLS+WS[CDN] 
内核版本:Linux 4.9.0-14-amd64 x86_64
系统: Debian 9 X64
脚本版本：v2.2.13

**Comment by PerseSniper** [comment]
> > 大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动 把 path地址填上去
> 
> 我刚试了下 我这是可以的 ，安装方式、内核版本、脚本版本说一下
大佬你测试的 系统版本 告诉我。我去装你测试的系统版本

**Comment by mack-a** [comment]
> 安装方式:VMess+TLS+WS[CDN]
> 内核版本:Linux 4.9.0-14-amd64 x86_64
> 系统: Debian 9 X64
> 脚本版本：v2.2.13

啥厂商的，或者使用自动生成的试一下勒

**Comment by PerseSniper** [comment]
vultr

**Comment by mack-a** [comment]
> vultr

我用Debian10试了下，木有问题，试试Debian10勒

**Comment by mack-a** [comment]
> 大佬我来提bug了，我测试了VMess+TLS+WS[CDN] 协议的安装。 生成的的协议链接 和二维码中 path 路径 [在使用的过程中我自己自定义的路径]没填上去。 客户端扫描了二维码 或者导入了链接地址 需要手动 把 path地址填上去

https://github.com/mack-a/v2ray-agent/releases/tag/v2.2.16
已修改

**Comment by dreamyear2000hk** [comment]
大佬, 请问在安装时出现" 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确"这个是什么原因呢?

**Comment by mack-a** [comment]
> 大佬, 请问在安装时出现" 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确"这个是什么原因呢?

一般都是防火墙问题，还有些是只关闭vps防火墙不可以，还需要再关闭面板的。建议使用纯净系统搭建。

**Comment by dreamyear2000hk** [comment]
> > 大佬, 请问在安装时出现" 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确"这个是什么原因呢?
> 
> 一般都是防火墙问题，还有些是只关闭vps防火墙不可以，还需要再关闭面板的。建议使用纯净系统搭建。

大佬, 因为这台是实体机, 因为在机器前有一台实体防火墙, 请问题我要在防火墙打开什么端口才可以呢?

**Comment by mack-a** [comment]
> > > 大佬, 请问在安装时出现" 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确"这个是什么原因呢?
> 
> > 
> 
> > 一般都是防火墙问题，还有些是只关闭vps防火墙不可以，还需要再关闭面板的。建议使用纯净系统搭建。
> 
> 
> 
> 大佬, 因为这台是实体机在机器前有一台实体防火墙, 请问题我要在防火墙打开什么端口才可以呢?

443 80

**Comment by r6c** [comment]
```bash
============================================================== 
作者：mack-a 
当前版本：v2.2.16 
Github：https://github.com/mack-a/v2ray-agent 
描述：七合一共存脚本 
============================================================== 
1.安装 
2.任意组合安装 
-------------------------工具管理----------------------------- 
3.查看账号 
4.更换伪装站 
5.更新证书 
6.更换CDN节点 
7.多用户管理 
8.ipv6人机验证 
-------------------------版本管理----------------------------- 
9.core版本管理 
10.升级Trojan-Go 
11.升级脚本 
12.安装BBR 
-------------------------脚本管理----------------------------- 
13.查看日志 
14.卸载脚本 
============================================================== 
请选择:9
进度  1/1 : Xray版本管理 
============================================================== 
1.升级 
2.回退 
============================================================== 
请选择：1
 ---> 当前Xray-core版本:1.1.4 
最新版本为：v1.2.0，是否更新？[y/n]：y
 ---> Xray-core版本:v1.2.0 
Xray-linux-64.zip            100%[=============================================>]   8.34M  4.89MB/s    in 1.7s    
 ---> Xray关闭成功 
 ---> Xray启动成功 
/usr/bin/vasma: line 3087: ystem/trojan-go.service: No such file or directory
/usr/bin/vasma: line 3088: syntax error near unexpected token `fi'
/usr/bin/vasma: line 3088: `        fi'
```

**Comment by mack-a** [comment]
> ```shell
> ============================================================== 
> 作者：mack-a 
> 当前版本：v2.2.16 
> Github：https://github.com/mack-a/v2ray-agent 
> 描述：七合一共存脚本 
> ============================================================== 
> 1.安装 
> 2.任意组合安装 
> -------------------------工具管理----------------------------- 
> 3.查看账号 
> 4.更换伪装站 
> 5.更新证书 
> 6.更换CDN节点 
> 7.多用户管理 
> 8.ipv6人机验证 
> -------------------------版本管理----------------------------- 
> 9.core版本管理 
> 10.升级Trojan-Go 
> 11.升级脚本 
> 12.安装BBR 
> -------------------------脚本管理----------------------------- 
> 13.查看日志 
> 14.卸载脚本 
> ============================================================== 
> 请选择:9
> 进度  1/1 : Xray版本管理 
> ============================================================== 
> 1.升级 
> 2.回退 
> ============================================================== 
> 请选择：1
>  ---> 当前Xray-core版本:1.1.4 
> 最新版本为：v1.2.0，是否更新？[y/n]：y
>  ---> Xray-core版本:v1.2.0 
> Xray-linux-64.zip            100%[=============================================>]   8.34M  4.89MB/s    in 1.7s    
>  ---> Xray关闭成功 
>  ---> Xray启动成功 
> /usr/bin/vasma: line 3087: ystem/trojan-go.service: No such file or directory
> /usr/bin/vasma: line 3088: syntax error near unexpected token `fi'
> /usr/bin/vasma: line 3088: `        fi'
> ```

出这个报错可以正常使用吗

**Comment by r6c** [comment]
> > ```shell
> > ============================================================== 
> > 作者：mack-a 
> > 当前版本：v2.2.16 
> > Github：https://github.com/mack-a/v2ray-agent 
> > 描述：七合一共存脚本 
> > ============================================================== 
> > 1.安装 
> > 2.任意组合安装 
> > -------------------------工具管理----------------------------- 
> > 3.查看账号 
> > 4.更换伪装站 
> > 5.更新证书 
> > 6.更换CDN节点 
> > 7.多用户管理 
> > 8.ipv6人机验证 
> > -------------------------版本管理----------------------------- 
> > 9.core版本管理 
> > 10.升级Trojan-Go 
> > 11.升级脚本 
> > 12.安装BBR 
> > -------------------------脚本管理----------------------------- 
> > 13.查看日志 
> > 14.卸载脚本 
> > ============================================================== 
> > 请选择:9
> > 进度  1/1 : Xray版本管理 
> > ============================================================== 
> > 1.升级 
> > 2.回退 
> > ============================================================== 
> > 请选择：1
> >  ---> 当前Xray-core版本:1.1.4 
> > 最新版本为：v1.2.0，是否更新？[y/n]：y
> >  ---> Xray-core版本:v1.2.0 
> > Xray-linux-64.zip            100%[=============================================>]   8.34M  4.89MB/s    in 1.7s    
> >  ---> Xray关闭成功 
> >  ---> Xray启动成功 
> > /usr/bin/vasma: line 3087: ystem/trojan-go.service: No such file or directory
> > /usr/bin/vasma: line 3088: syntax error near unexpected token `fi'
> > /usr/bin/vasma: line 3088: `        fi'
> > ```
> 
> 出这个报错后，可以正常使用吗

xray启动正常
