### ISSUE TITLE
大佬，现在脚本还兼容宝塔面板吗？我测试了一下，好像不行了哦

### ISSUE THREAD

**Issue by lovelygfj** [mack-a/v2ray-agent#513]

**Comment by mack-a** [comment]
等抽空搞一下

**Comment by lovelygfj** [comment]
今天折腾了一天，搞出来了共存，但脚本无法继续重装，记录一下：
1. 全新的Debian 11 VPS
2. 安装最新的脚本
3. 不卸载脚本，直接安装宝塔面板
4. 使用官网 https://www.bt.cn/new/download.html 在线安装
5. 安装的时候选择LMNP环境，不选Nginx；PHP admin
6. 等在线安装完宝塔面板以后，V2ray-agent依然可以正常运行。

唯一的问题是，重新安装的时候无法继续，
会卡在检查本机IP，循环打开80和443端口。
请大佬抽空帮忙看看。

**Comment by jjjyyyllll** [comment]
宝塔已经安装LMNP的环境 要卸载掉 Nginx PHP admin才可以用吗？

**Comment by Dem-K** [comment]
好了希望能弄个教程

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.7.9
