### ISSUE TITLE
xtls-rprx-vision无法正常工作

### ISSUE THREAD

**Issue by shell12345** [mack-a/v2ray-agent#514]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
xtls-rprx-vision无法正常工作，
所有客户端流控xtls-rprx-vision都无法工作，手机v2rayNG，桌面v2rayN，路由器与linux xray with json。
ws全部正常。
**3.系统版本**
服务器 ubuntu 22.04.1
**4.脚本版本**
最新[v2.6.15](https://github.com/mack-a/v2ray-agent/releases/tag/v2.6.15)
**5.核心类型及版本**
xray 1.7.2

另外请支持批量添加端口段如1000-1050，以应对频繁的端口封禁。1000,1001这种逗号太麻烦了，而且不稳定，经常出错。
谢谢@mack-a

**Comment by mack-a** [comment]
[v2rayNG 1.7.34](https://github.com/2dust/v2rayNG/releases/tag/1.7.34) 未发现问题

**Comment by shell12345** [comment]
@mack-a 是不是因为未采用默认端口的原因？443被封，我采用的其他端口，
v2rayNG
https://github.com/2dust/v2rayNG/releases/tag/1.7.34 显示EOF
服务器客服端xray都是1.7.2

**Comment by shell12345** [comment]
卸载脚本，重装脚本以后问题解决
