### ISSUE TITLE
全新安装，在 Xray 部分出现错误

### ISSUE THREAD

**Issue by mybdye** [mack-a/v2ray-agent#516]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 全新安装，在 Xray 部分出现错误

**2.安装失败的错误内容或者截图**
- <img width="1332" alt="image" src="https://user-images.githubusercontent.com/21116709/212459396-88638a1a-5b27-465f-8568-4ef80d88b4c1.png">

**3.系统版本**
- debian 11

**4.脚本版本**
- v2.6.16

**5.核心类型及版本**
- Xray-core

**Comment by mack-a** [comment]
卸载后重新安装

**Comment by mybdye** [comment]
> 卸载后重新安装

可以了

**Comment by oacao** [comment]
> > 卸载后重新安装
> 
> 可以了

我也同样的问题，请问怎么搞的，重装也没用啊
