### ISSUE TITLE
在v2.6.18中，安装Hysteria提示“Hysteria启动失败”

### ISSUE THREAD

**Issue by AirTed** [mack-a/v2ray-agent#517]
### 问题描述
环境描述：

> 系统版本：Centos 7
> 核心：Xray-core
> v2ray-agent版本：v2.6.18

在安装Hysteria时提示如下：

> 进度  3/5 : 配置Hysteria开机自启 
 ---> 配置Hysteria开机自启成功 
 ---> Hysteria关闭成功 
Hysteria启动失败 
请手动执行【/etc/v2ray-agent/hysteria/hysteria --log-level debug -c /etc/v2ray-agent/hysteria/conf/config.json server】，查看错误日志

错误日志如下：
> 2023-01-16T02:36:51+08:00 [FATA] [cert:/etc/v2ray-agent/tls/.crt] [key:/etc/v2ray-agent/tls/.key] [error:open /etc/v2ray-agent/tls/.crt: no such file or directory] Failed to load the certificate

经过调试并调试后，发现是**无法正确获取到currentHost**，导致无法找到相应配置文件.json

### 解决方案
个人的解决方案如下：
在install.sh的第481行中把
**tlsSettings**
改为
**xtlsSettings**

https://github.com/mack-a/v2ray-agent/blob/a81bdcc4017ba8635a0d9823fc21947131d6a2ee/install.sh#L481

修改后的第481行如下：
```shell
currentHost=$(jq -r .inbounds[0].streamSettings.xtlsSettings.certificates[0].certificateFile ${configPath}${frontingType}.json | awk -F '[t][l][s][/]' '{print $2}' | awk -F '[.][c][r][t]' '{print $1}')
```

### 修改后的影响

- 使用Hysteria管理功能，正常进行安装Hysteria以及运行Hysteria
- 使用查看账号功能，正常输出的订阅链接中host、sni、peer

> 个人注：
抱歉啊，第一次在Github上提交issues不太懂规则，如果提交的issues某些错误请指正，谢谢。^_^

**Comment by mack-a** [comment]
完全卸载后重新安装
