### ISSUE TITLE
安装最新脚本，无法上网

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#52]
最近登录Google，时不时就提示我进行人机验证（几个安装该脚本的机器都是这种提示），故而升级脚本。
然而，升级完脚本，并重新安装后，机器就不能上网了（几个机器都是这种现象）。安装过程一路顺利。

有如下提示：

2020/12/21 14:25:46 127.0.0.1:3414 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy2484] 
2020/12/21 14:25:51 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://XXX.XXX.XXX/gxzd): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/12/21 14:25:51 [Warning] [704766260] v2ray.com/core/proxy/http: failed to read response from speedtest-sgp1.digitalocean.com > unexpected EOF

**Comment by AndersonGhost** [comment]
之前的现象是：只要用Google搜索就会跳转到人机验证的界面。

**Comment by mack-a** [comment]
> 最近登录Google，时不时就提示我进行人机验证（几个安装该脚本的机器都是这种提示），故而升级脚本。
> 然而，升级完脚本，并重新安装后，机器就不能上网了（几个机器都是这种现象）。安装过程一路顺利。
> 
> 有如下提示：
> 
> 2020/12/21 14:25:46 127.0.0.1:3414 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy2484]
> 2020/12/21 14:25:51 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://XXX.XXX.XXX/gxzd): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> 2020/12/21 14:25:51 [Warning] [704766260] v2ray.com/core/proxy/http: failed to read response from speedtest-sgp1.digitalocean.com > unexpected EOF

path可能不对 或者uuid可能不对 再检查下

**Comment by AndersonGhost** [comment]
我就是复制生成的VMess WS TLS CDN 链接呀

**Comment by mack-a** [comment]
> 我就是复制生成的VMess WS TLS CDN 链接呀

那是自定义path了吗

**Comment by AndersonGhost** [comment]
自动生成的path 啊

刚才有重新安装了一遍，有下面的提示：

---------------------------- 
是否使用？[y/n]:n

进度 12/17 : 初始化V2Ray配置 

读取到上次安装记录，是否使用上次安装时的UUID ？[y/n]:n

 ---> uuid读取错误，重新生成 

进度 13/17 : 初始化Trojan配置 

进度  14/17 : 添加定时维护证书

**Comment by mack-a** [comment]
> 自动生成的path 啊
> 
> 刚才又重新安装了一遍，有下面的提示：
> 
> 是否使用？[y/n]:n
> 
> 进度 12/17 : 初始化V2Ray配置
> 
> 读取到上次安装记录，是否使用上次安装时的UUID ？[y/n]:n
> 
> ---> uuid读取错误，重新生成
> 
> 进度 13/17 : 初始化Trojan配置
> 
> 进度 14/17 : 添加定时维护证书

用的VMess+WS+CDN对不

**Comment by AndersonGhost** [comment]
V2ray呀

**Comment by mack-a** [comment]
> V2ray呀

核心+版本:
协议类型:

对着这个写上

**Comment by AndersonGhost** [comment]
v2ray-core    v2.2.3
VMess+WS+CDN

**Comment by AndersonGhost** [comment]
大佬，您好！根据您的提示，我找到问题原因了：我之前自定义了path，后来出错了后，我又自动生成了path。
刚才把全部都卸载了后重新安装，然后自动生成path，然后就可以连上了。

**Comment by AndersonGhost** [comment]
大佬，现在还有一个问题：为什么连上之后，每次Google都需要进行人机验证呢？

**Comment by AndersonGhost** [comment]
> > 我就是复制生成的VMess WS TLS CDN 链接呀
> 
> 是自定义path么
> 
> 如果是自定义path，path那个地就只显示4位，那个问题还没改

大佬，您好！  现在还有一个问题：为什么连上之后，每次Google都需要进行人机验证呢？

**Comment by mack-a** [comment]
> > > 我就是复制生成的VMess WS TLS CDN 链接呀
> > 
> > 
> > 是自定义path么
> > 如果是自定义path，path那个地就只显示4位，那个问题还没改
> 
> 大佬，您好！ 现在还有一个问题：为什么连上之后，每次Google都需要进行人机验证呢？

人机验证和你vps的ip有关，和脚本关系不大
