### ISSUE TITLE
VLESS+TLS/XTLS+TCP

### ISSUE THREAD

**Issue by lfxx** [mack-a/v2ray-agent#53]
**详细描述建议的内容**
大佬您好，想知道上述搭配是否可以搭配CDN，若不能，ip被封是不是就不能用了。我目前使用的VMESS+WS+CDN方案，好像无法再搭建VLESS+TLS/XTLS+TCP组合

**Comment by mack-a** [comment]
都支持，自由组合

**Comment by lfxx** [comment]
> 都支持，自由组合

在您的脚本中只有VLESS+TLS/XTLS+TCP，VLESS+TLS+WS[CDN]两种搭配方式，并没有VLESS+TLS/XTLS+TCP+CDN的搭配方式，不太会自己捣鼓。。

**Comment by lfxx** [comment]
> 都支持，自由组合

VLESS+TLS/XTLS+TCP+CDN方式的话，是不是申请完证书后，再把云朵设置成橙色就行。但是这样的话后期证书续期应该会出问题吧

**Comment by mack-a** [comment]
> > 都支持，自由组合
> 
> 
> 
> VLESS+TLS/XTLS+TCP+CDN方式的话，是不是申请完证书后，再把云朵设置成橙色就行。但是这样的话后期证书续期应该会出问题吧

只有支持ws的才支持CAN，你说的这个不支持。

**Comment by mack-a** [comment]
> > 都支持，自由组合
> 
> 
> 
> VLESS+TLS/XTLS+TCP+CDN方式的话，是不是申请完证书后，再把云朵设置成橙色就行。但是这样的话后期证书续期应该会出问题吧

只有支持ws的才支持CDN，你说的这个不支持。

**Comment by mack-a** [comment]
> **详细描述建议的内容**
> 
> 大佬您好，想知道上述搭配是否可以搭配CDN，若不能，ip被封是不是就不能用了。我目前使用的VMESS+WS+CDN方案，好像无法再搭建VLESS+TLS/XTLS+TCP组合

可以，需要云朵置灰，并使用自选ip或者使用脚本里面的。可以查看项目主页，cloudflare相关的优化教程。

**Comment by lfxx** [comment]
> > **详细描述建议的内容**
> > 
> > 大佬您好，想知道上述搭配是否可以搭配CDN，若不能，ip被封是不是就不能用了。我目前使用的VMESS+WS+CDN方案，好像无法再搭建VLESS+TLS/XTLS+TCP组合
> 
> 可以，需要云朵置灰，并使用自选ip或者使用脚本里面的。可以查看项目主页，cloudflare相关的优化教程。

我现在挂着VMESS+WS+CDN方案，再配置VLESS+TLS/XTLS+TCP时，提示address already in use，应该是80端口被我的caddy占用了，我是不是应该把caddy换成ngnix，然后两个方案共用ngnix呢，非常感谢大佬指点

**Comment by moudong168** [comment]
云朵置灰关了CDN,用VLESS TCP XTLS ,想问,没有CDN的保护,会不会将我的小鸡鸡暴露在外而被封杀?
