### ISSUE TITLE
Problem in node name

### ISSUE THREAD

**Issue by MH140000** [mack-a/v2ray-agent#530]
Hello. After installing this script, the nodes are not named correctly. For example
#yourDomain_uuid_VLESS_TCP/XTLS
If it can be as follows (like other scripts):
#userEmail_VLESS_TCP/XTLS

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.6.25

**Comment by MH140000** [comment]
There is no way to apply the changes by going to the user list without having to reinstall?

**Comment by mack-a** [comment]
> There is no way to apply the changes by going to the user list without having to reinstall

可以新添加一个用户来自定义名称然后把之前的删掉

**Comment by MH140000** [comment]
I re-created the user account but the problem is not solved and the uuid is written after the user's email. Please delete that too.
