### ISSUE TITLE
Change the domain without having to reinstall the script and delete all users

### ISSUE THREAD

**Issue by MH140000** [mack-a/v2ray-agent#531]
Hello. Unfortunately, in my country, if users visit the internal site, the subdomain goes to the firewall blacklist and it no longer works for xray. Please add an option to the script so that we can change the subdomain without deleting users and without having to reinstall. Thank you very much

**Comment by mack-a** [comment]
读取到上次安装的用户选择y即可 但是需要重新执行脚本安装

**Comment by MH140000** [comment]
Well, the problem is that all uuids are deleted.
