### ISSUE TITLE
warp问题

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#532]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
设置好warp，可是使用hysteria协议时，warp分流未生效，而同一服务器使用vmess协议则会被正常分流
另外，能否增加选项 查看warp分流地址和ipv6分流地址
core 脚本均为最新版本

**Comment by mack-a** [comment]
1.hysteria目前所有的分流都没实现
2.分流地址可以添加

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/76

**Comment by fredericky123** [comment]
hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上
hysteria建议1000个以上端口，一个个手动输入端口不太现实了

**Comment by mack-a** [comment]
> hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了

个人使用没有那么多的端口需求，商业使用请使用面板

**Comment by fredericky123** [comment]
> > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> 
> 个人使用没有那么多的端口需求，商业使用请使用面板

纯个人使用，是看hysteria配置的介绍时，官方建议1000个

**Comment by mack-a** [comment]
> > > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> > 
> > 
> > 个人使用没有那么多的端口需求，商业使用请使用面板
> 
> 纯个人使用，是看hysteria配置的介绍时，~官方~隔壁hihy建议1000个

目前没有xray-core/v2ray-core与hysteria分开添加端口的想法，建议使用官方脚本。两个脚本之间不冲突

**Comment by fredericky123** [comment]
> > > > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> > > 
> > > 
> > > 个人使用没有那么多的端口需求，商业使用请使用面板
> > 
> > 
> > 纯个人使用，是看hysteria配置的介绍时，~官方~隔壁hihy建议1000个
> 
> 目前没有xray-core/v2ray-core与hysteria分开添加端口的想法，建议使用官方脚本。两个脚本之间不冲突

那个脚本暂不支持warp分流，warp分流国内流量等是刚需，因此期待mack佬的脚本一统天下

**Comment by mack-a** [comment]
> > > > > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> > > > 
> > > > 
> > > > 个人使用没有那么多的端口需求，商业使用请使用面板
> > > 
> > > 
> > > 纯个人使用，是看hysteria配置的介绍时，~官方~隔壁hihy建议1000个
> > 
> > 
> > 目前没有xray-core/v2ray-core与hysteria分开添加端口的想法，建议使用官方脚本。两个脚本之间不冲突
> 
> 那个脚本暂不支持warp分流，warp分流国内流量等是刚需，因此期待mack佬的脚本一统天下

最近在计划hysteria分流至xray-core/v2ray-core

**Comment by fredericky123** [comment]
期待!

**Comment by love768952693** [comment]
> > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> 
> 个人使用没有那么多的端口需求，商业使用请使用面板

希望大佬考虑下 跳跃多端口，某些地区，长期看视频，很容易被限速，跳跃多端口可以有效解决运营商限速问题。

**Comment by fredericky123** [comment]
@mack-a 重新安装时能否默认保留之前的warp和ipv6分流设置（增加问题询问是否保留之前的分流配置也行），现在重装还需要重新配置
hysteria和xray能否支持不同的域名，hys不支持cdn而xray支持，想用不同的域名解析到同一服务器，一个用hys协议，一个嵌套cdn，多重策略能增加服务器的可达性
感谢

**Comment by styxiik** [comment]
> > > hysteria的端口跳跃是否能一并支持？能够以“1000-2000”的格式批量增加端口，并显示在分享的链接上 hysteria建议1000个以上端口，一个个手动输入端口不太现实了
> > 
> > 
> > 个人使用没有那么多的端口需求，商业使用请使用面板
> 
> 纯个人使用，是看hysteria配置的介绍时，~官方~隔壁hihy建议1000个

这么牛逼怎么不去用隔壁脚本
