### ISSUE TITLE
端口增加无效

### ISSUE THREAD

**Issue by yoyosbg** [mack-a/v2ray-agent#533]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**

A 安装后增加端口无效，只能是443
B 安装时指定非443端口， ngixn 启动失败

**2.安装失败的错误内容或者截图**
读取到上次安装时的端口，是否使用上次安装时的端口？[y/n]:n

请输入端口[默认: 443]，如自定义端口，只允许使用DNS申请证书[回车使用默认]
端口:10099
 ---> Xray关闭成功
 ---> Nginx启动失败
 ---> 请手动尝试安装nginx后，再次执行脚本

**3.系统版本**
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 6.0.9
      Architecture: x86-64

**4.脚本版本**
2.6.25

**5.核心类型及版本**
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 6.0.9
      Architecture: x86-64

**Comment by mack-a** [comment]
换debian ubuntu试一下

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/216864065-f1db297d-3ecf-42b2-ae05-75ddcb6e4c16.png)
<img width="824" alt="image" src="https://user-images.githubusercontent.com/57424792/216864139-03b62651-0d5b-42de-a168-0dda3e130d2e.png">

使用debian11，未复现问题。不建议使用centos，请尝试更换debian、ubuntu再尝试安装
