### ISSUE TITLE
传输协议GRPC和TCP报错

### ISSUE THREAD

**Issue by buzzhd** [mack-a/v2ray-agent#541]
![image](https://user-images.githubusercontent.com/85145033/218286562-0177964c-c0f8-42db-84a4-31f55465b03b.png)

**Comment by mack-a** [comment]
如果用了cloudflare建议仔细读一下readme

**Comment by buzzhd** [comment]
在CF里开启了Grpc还是不行

**Comment by mack-a** [comment]
gRPC如果不可用建议换几个客户端测试，或者直接放弃就好
