### ISSUE TITLE
Warp分流问题

### ISSUE THREAD

**Issue by Augus2008** [mack-a/v2ray-agent#542]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- Warp分流添加分流域名后X-ray提示启动失败，重新安装和更新xraycore后也没有解决，最后把warp分流卸载后X-ray就能正常启动

**2.安装失败的错误内容或者截图**
- 请在此处填写
![image](https://user-images.githubusercontent.com/116232372/218312994-043edcb4-81b7-46ca-9526-678b475f6167.jpeg)![image](https://user-images.githubusercontent.com/116232372/218312999-8d8fdfdb-347d-44cd-a603-eb7b0ea7e9ef.jpeg)
**3.系统版本**
- 请在此处填写

**4.脚本版本**
- 脚本版本已更新最新

**5.核心类型及版本**
- 请在此处填写

**Comment by mack-a** [comment]
启动的错误日志贴一下，可能是你域名写的有问题。仔细看下文档
