### ISSUE TITLE
通用格式恢复原本方式

### ISSUE THREAD

**Issue by izsiyy** [mack-a/v2ray-agent#543]
**详细描述建议的内容**
原本Trojan vless通用格式中是带有域名的，这样直接复制通用格式vless://   trojan://就可以粘贴到软件中，如v2rayn，现在通用格式中不带域名，复制后无法粘贴到软件中，有点麻烦。能不能恢复呢？

**Comment by mack-a** [comment]
截个图看看你说的问题

**Comment by izsiyy** [comment]
![image](https://user-images.githubusercontent.com/87903717/218512200-e590d005-9a71-486b-b41b-b8450d5f9c13.png)
像这种  应该sni=后面会有域名。。格式化明文后面应该也会有域名的，现在没了，导致直接复制了通用格式没办法直接导入到软件内

**Comment by mack-a** [comment]
我用最新的脚本安装之后sni安装之后是存在的，建议卸载脚本后重新安装
