### ISSUE TITLE
手动修改grpc协议里的serviceName后无法连接

### ISSUE THREAD

**Issue by finvv** [mack-a/v2ray-agent#544]
生成展示账号了，能正常使用，但是想改serviceName的字段，改了自定义字段后无法科学，重启了xray也一样
![屏幕截图 2023-02-14 151316](https://user-images.githubusercontent.com/103872493/218665711-12372084-0e1e-4018-bb05-9eb31cd16ff4.png)
修改了/etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json的
![屏幕截图 2023-02-14 151355](https://user-images.githubusercontent.com/103872493/218665715-d69c6fc0-93fa-4fbc-a853-1e74177414d3.png)
记得以前老版本可以改

**Comment by mack-a** [comment]
你如果要改serviceName，需要把nginx的也要改一下才可以

**Comment by finvv** [comment]
![屏幕截图 2023-02-15 102127](https://user-images.githubusercontent.com/103872493/218910965-9c2f20cf-bb0e-4b80-95e4-4eae156bcb86.png)
改了/etc/nginx/conf.d/alone.conf的字段还是不行，请教还需改哪里呢？

**Comment by finvv** [comment]
![屏幕截图 2023-02-16 150742](https://user-images.githubusercontent.com/103872493/219292984-896a9405-323e-4420-9c07-203a035ee6b2.png)
只能用随机路径才能正常科学，在这里输入手动路径后也不行
@mack-a

**Comment by mack-a** [comment]
> ![屏幕截图 2023-02-16 150742](https://user-images.githubusercontent.com/103872493/219292984-896a9405-323e-4420-9c07-203a035ee6b2.png) 只能用随机路径才能正常科学，在这里输入手动路径后也不行 @mack-a

更新下新版本试试
