### ISSUE TITLE
这个项目的XRAY的进站和出站规则怎么改呢？

### ISSUE THREAD

**Issue by Michael-EDU** [mack-a/v2ray-agent#546]
本想用这个方法https://mailberry.com.cn/2023/02/cf-solve-it-completely-error-code-1020-by-warp/    ,来解锁chatGPT的，但出站规则和路由不知道怎么配置

**Comment by dzp1018** [comment]
您的邮件我已收到!     感谢您的来信，我会及时处理并回复。

**Comment by mack-a** [comment]
> 本想用这个方法https://mailberry.com.cn/2023/02/cf-solve-it-completely-error-code-1020-by-warp/ ,来解锁chatGPT的，但出站规则和路由不知道怎么配置

脚本支持warp直接用就可以了
