### ISSUE TITLE
请求协助-未检测到当前域名的ip，错误日志nginx 302 Found

### ISSUE THREAD

**Issue by fanshu93** [mack-a/v2ray-agent#548]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 美国VPS，debian11，卡在3/13 : 初始化Nginx申请证书配置 ，输入域名，未检测到当前域名的ip ，下面付报错图片，nginx,302 Found；系统重新安装，执行脚本也这个报错。nginx日志没有明显报错，请问大神排查方向。

**2.安装失败的错误内容或者截图**
- ![image](https://user-images.githubusercontent.com/15394258/219235996-8c15595a-3b68-43a9-8997-9b43fc66e6a2.png)
![image](https://user-images.githubusercontent.com/15394258/219246939-503bfa72-0198-47ba-848b-7752a32aea5b.png)
![image](https://user-images.githubusercontent.com/15394258/219238756-8dddf9ce-f93e-446d-89f5-e0698d8899f9.png)

**3.系统版本**
- debian 11.0

**4.脚本版本**
- v2.7.1

**5.核心类型及版本**
- Xray-core

**Comment by mack-a** [comment]
dd一个debian11试试

**Comment by fanshu93** [comment]
> dd一个 debian11试试

dd什么意思？debian11是全新安装的。而且在两台VPS(新安装系统)都试了，同样问题。

**Comment by mack-a** [comment]
> > dd一个 debian11试试
> 
> dd什么意思？debian11是全新安装的。而且在两台VPS(新安装系统)都试了，同样问题。

把云朵关掉试一下

**Comment by fanshu93** [comment]
> > > dd一个 debian11试试
> > 
> > 
> > dd什么意思？debian11是全新安装的。而且在两台VPS(新安装系统)都试了，同样问题。
> 
> 把云朵关掉试一下



> > > dd一个 debian11试试
> > 
> > 
> > dd什么意思？debian11是全新安装的。而且在两台VPS(新安装系统)都试了，同样问题。
> 
> 把云朵关掉试一下

好的 我试一下

**Comment by mack-a** [comment]
还有问题吗

**Comment by fanshu93** [comment]
> 还有问题吗
关闭云朵，重装系统debian 11，还是获取不到IP。域名是有配置DNS解析的，ip为VPS地址。在VPS上ping 域名，也是正确获取到地址。是否为BUG？以前用过大佬你的作品，IP解析一直正常的。
![image](https://user-images.githubusercontent.com/15394258/219287794-377c29bf-ea3c-4f37-a030-8821411c2fe9.png)
![image](https://user-images.githubusercontent.com/15394258/219288378-89476066-26e5-4403-9c7a-87ed1bbe70b4.png)

**Comment by minwoo0210** [comment]
以前用他家设置也有过同样情况，换了mack-a的设置后就可以了。不知道是什么原因造成的呢，求知+1。

**Comment by mack-a** [comment]
> 以前用他家设置也有过同样情况，换了mack-a大神的设置后就可以了。不知道是什么原因造成的呢，求知+1。

记不太清楚了

**Comment by mack-a** [comment]
> > 还有问题吗
> > 关闭云朵，重装系统debian 11，还是获取不到IP。域名是有配置DNS解析的，ip为VPS地址。在VPS上ping 域名，也是正确获取到地址。是否为BUG？以前用过大佬你的作品，IP解析一直正常的。
> > ![image](https://user-images.githubusercontent.com/15394258/219287794-377c29bf-ea3c-4f37-a030-8821411c2fe9.png)
> > ![image](https://user-images.githubusercontent.com/15394258/219288378-89476066-26e5-4403-9c7a-87ed1bbe70b4.png)

tg群找管理员我给你看看

**Comment by fanshu93** [comment]
> > 还有问题吗
> > 关闭云朵，重装系统debian 11，还是获取不到IP。域名是有配置DNS解析的，ip为VPS地址。在VPS上ping 域名，也是正确获取到地址。是否为BUG？以前用过大佬你的作品，IP解析一直正常的。
> > ![image](https://user-images.githubusercontent.com/15394258/219287794-377c29bf-ea3c-4f37-a030-8821411c2fe9.png)
> > ![image](https://user-images.githubusercontent.com/15394258/219288378-89476066-26e5-4403-9c7a-87ed1bbe70b4.png)

补充：debina 10，也是提示检测不到ip

**Comment by mack-a** [comment]
> > > 还有问题吗
> > > 关闭云朵，重装系统debian 11，还是获取不到IP。域名是有配置DNS解析的，ip为VPS地址。在VPS上ping 域名，也是正确获取到地址。是否为BUG？以前用过大佬你的作品，IP解析一直正常的。
> > > ![image](https://user-images.githubusercontent.com/15394258/219287794-377c29bf-ea3c-4f37-a030-8821411c2fe9.png)
> > > ![image](https://user-images.githubusercontent.com/15394258/219288378-89476066-26e5-4403-9c7a-87ed1bbe70b4.png)
> 
> 补充：debina 10，也是提示检测不到ip

tg私聊  @mackaff

**Comment by fanshu93** [comment]
已解决，乌龙！原因：服务器前段时间被墙，换了IP，域名DNS配置的IP没检查，还是以前的IP，错误IP导致的，已成功使用脚本，给大佬点赞！
![image](https://user-images.githubusercontent.com/15394258/219521570-cde7ee0b-da7c-441e-9954-e32ab2b3e159.png)
