### ISSUE TITLE
人机代理配置成功，可以访问有图比，不能访问google.com

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#55]
>下方留下相关的描述即可

**1.描述出现的问题**
人机代理配置成功，可以访问有图比，不能访问google.com

**2.是否直接安装失败**
- 否

**3.直接安装失败的错误内容或者截图**
- 此项没有可忽略

**4.系统版本【例：Centos8】**
>下列系统版本需自己补全
- DEBAIN

**5.脚本版本**
- 2.2.6

**6.安装类型**
- 安装
- 个性化安装

**7.安装的核心版本**
>version位置需自己替换
- Xray-core【version】
- v2ray-core【version】
- v2ray-core[XTLS]

**8.出现问题的协议类型**
- VLESS+XTLS
- VLESS+TLS+WS
- VMess+TLS+WS
- VMess+TLS+TCP
- Trojan
- Trojan-go+ws

**9.尝试重装后是否100%复现**
- 是

**10.是否仔细检查客户端与服务端的配置是否相同**
- 是

**Comment by fredericky123** [comment]
是不是客户端需要做什么额外配置

**Comment by mack-a** [comment]
> 是不是客户端需要做什么额外配置

完全没有反应吗 你是不是在vps ping6 www.google.com 返回的啥

**Comment by mack-a** [comment]
> 是不是客户端需要做什么额外配置

客户端不需要改任何东西

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/102987100-d0551500-454c-11eb-92dd-487325509cba.png)

**Comment by mack-a** [comment]
> ![image](https://user-images.githubusercontent.com/13982749/102987100-d0551500-454c-11eb-92dd-487325509cba.png)
> 
> 

HE 可能没配置成功

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/102988500-f4195a80-454e-11eb-8f69-e07253797b1e.png)
链接重点这一步好像确实没有完成
