### ISSUE TITLE
移动端手机连接WIFI可以使用，移动数据无法使用，请问是否有什么要配置的吗？

### ISSUE THREAD

**Issue by baofm** [mack-a/v2ray-agent#550]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 默认端口443无法使用，使用自定义端口10099，PC端可以使用，移动端连接Wifi可以使用，但是使用手机移动数据无法使用错误提示
失败：io:read/write on closed pipe

**2.安装失败的错误内容或者截图**
- 请在此处填写

**3.系统版本**
- Debian 11

**4.脚本版本**
- v2.7.2 

**5.核心类型及版本**
- Xray-core v1.7.5

**Comment by mack-a** [comment]
本地网络问题，和脚本无关
