### ISSUE TITLE
申请 DNS 证书，dnsTLSDomain生成规则只保留了最后两位

### ISSUE THREAD

**Issue by mymolasses** [mack-a/v2ray-agent#553]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 申请 DNS 证书，dnsTLSDomain生成规则只保留了最后两位

**2.安装失败的错误内容或者截图**
<img width="556" alt="image" src="https://user-images.githubusercontent.com/123858204/220061788-364338c1-5725-4f10-a27c-f45998bae190.png">

**3.系统版本**
- ubuntu22

**4.脚本版本**
- 2.7.2

readAcmeTLS() {
    if [[ -n "${currentHost}" ]]; then
        dnsTLSDomain=$(echo "${currentHost}" | awk -F "[.]" '{print $(NF-1)"."$NF}')

# 初始化Nginx申请证书配置
initTLSNginxConfig() {
    handleNginx stop
    echoContent skyBlue "\n进度  $1/${totalProgress} : 初始化Nginx申请证书配置"
    if [[ -n "${currentHost}" ]]; then
        echo
        read -r -p "读取到上次安装记录，是否使用上次安装时的域名 ？[y/n]:" historyDomainStatus
        if [[ "${historyDomainStatus}" == "y" ]]; then
            domain=${currentHost}
            echoContent yellow "\n ---> 域名: ${domain}"
        else
            echo
            echoContent yellow "请输入要配置的域名 例: www.v2ray-agent.com --->"
            read -r -p "域名:" domain
        fi
    else
        echo
        echoContent yellow "请输入要配置的域名 例: www.v2ray-agent.com --->"
        read -r -p "域名:" domain
    fi

    if [[ -z ${domain} ]]; then
        echoContent red "  域名不可为空--->"
        initTLSNginxConfig 3
    else
        dnsTLSDomain=$(echo "${domain}" | awk -F "[.]" '{print $(NF-1)"."$NF}')

两处dnsTLSDomain生成规则只取了输入域名的最后两位，若类似 xxxx.eu.org这类域名就取了 eu.org，这样就读不到配置的 txt 记录了

**Comment by mack-a** [comment]
脚本不支持*.*.*.com*这样的 仅支持*.*.com*

**Comment by mymolasses** [comment]
dnsTLSDomain=$(echo "${currentHost}")

我手动把所有dnsTLSDomain赋值的位置都改成了currentHost，输入的时候只输入， xxx.eu.org，可正常使用，生成*.xxx.eu.org的证书了

有类似需求的可以手动改下
