### ISSUE TITLE
删除黑名单后核心启动失败

### ISSUE THREAD

**Issue by gungnirayu** [mack-a/v2ray-agent#554]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 黑名单添加cn，后删除黑名单，导致xray启动失败

**2.安装失败的错误内容或者截图**
进度  1/1 : 域名黑名单

==============================================================
1.查看已屏蔽域名
2.添加域名
3.删除黑名单
==============================================================
请选择:3
/root/install.sh: line 4465: "1" - 1: syntax error: operand expected (error token is ""1" - 1")
 ---> 域名黑名单删除成功
 ---> Xray关闭成功
Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志

错误日志：

[root@vless ~]# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)
A unified platform for anti-censorship.
2023/02/22 17:10:37 Using confdir from arg: /etc/v2ray-agent/xray/conf
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/09_routing.json > infra/conf/serial: failed to read config file > EOF

**3.系统版本**
- centos7.0

**4.脚本版本**
- 2.7.2

**5.核心类型及版本**
- Xray 1.7.5

**Comment by mack-a** [comment]
重新安装一下，或者手动打开/etc/v2ray-agent/xray/conf/09_routing.json 这个文件里面可能有乱码的内容。如果有乱码的内容，把其中乱码的内容修改一下就可以正常启动了

**Comment by gungnirayu** [comment]
这文件删除黑名单之后就空了
