### ISSUE TITLE
大佬又是我，2.7.3安装失败……

### ISSUE THREAD

**Issue by gungnirayu** [mack-a/v2ray-agent#555]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 用最新的2.7.3脚本安装失败

**2.安装失败的错误内容或者截图**
- ========================个性化安装============================
VLESS前置，默认安装0，如果只需要安装0，则只选择0即可
0.VLESS+TLS/XTLS+TCP
1.VLESS+TLS+WS[CDN]
2.Trojan+TLS+gRPC[CDN]
3.VMess+TLS+WS[CDN]
4.Trojan+TLS
5.VLESS+TLS+gRPC[CDN]
请选择[多选]，[例如:123]:0
--------------------------------------------------------------

进度  1/17 : 安装工具
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】
 ---> 安装curl
 ---> 安装unzip
 ---> 安装socat
 ---> 安装jq
 ---> 安装binutils
 ---> 安装qrencode
 ---> 安装lsb-release
 ---> 安装lsof
 ---> 安装dig
 ---> 安装nginx
sudo: unable to resolve host Vless: Name or service not known
mv: cannot stat '/tmp/nginx_signing.key': No such file or directory
Failed to enable unit: Unit file nginx.service does not exist.
 ---> 安装semanage
 ---> 安装acme.sh
/root/install.sh: line 749: curl: command not found
  acme安装失败--->
错误排查:
  1.获取Github文件失败，请等待Github恢复后尝试，恢复进度可查看 [https://www.githubstatus.com/]
  2.acme.sh脚本出现bug，可查看[https://github.com/acmesh-official/acme.sh] issues
  3.如纯IPv6机器，请设置NAT64,可执行下方命令
  echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" >> /etc/resolv.conf

**3.系统版本**
- Debian10

**4.脚本版本**
- 2.7.3

**5.核心类型及版本**
- 还未涉及到

**Comment by mack-a** [comment]
是自己改好了不，可能是系统有一些问题

**Comment by gungnirayu** [comment]
> 是自己改好了不，可能是系统有一些问题

是的，不好意思，后来发现是我那个vps重装以后opkg有问题，修复一下就好了
