### ISSUE TITLE
类型为 Hysteria 时无法联网

### ISSUE THREAD

**Issue by bylucky** [mack-a/v2ray-agent#556]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 请教大神，刚刚安装，使用【VLESS+TCP+xtls-rprx-vision】时正常联网，可类型为 Hysteria 时无法使用，
- 错误提示：(connect: connection refused] TCP error)

**2.安装失败的错误内容或者截图**
- 无

**3.系统版本**
- Debian 10.2.1-6

**4.脚本版本**
- 2.7.3

**5.核心类型及版本**
- Hysteria版本:v1.3.3 ， Xray-core版本:1.7.5

**Comment by mack-a** [comment]
1.打开xray和hy的日志，贴一下调试日志
2.写在hy后重新安装再尝试

**Comment by bylucky** [comment]
刚才试了下可以正常使用了，可能是服务器IP的问题。感谢您回复。
