### ISSUE TITLE
无法正常更新geoip

### ISSUE THREAD

**Issue by xiechangan123** [mack-a/v2ray-agent#557]
如题，只能正常更新geosite，而geoip无法正常更新，麻烦修正下
复现：重新安装xray core1.75之后接着更新geo，用winscp进入v2ray-agent文件夹下的xray文件夹内，可以看到geoip时间没变化，而geosite时间已经变为最新了。。。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.7.5
