### ISSUE TITLE
机器安装失败

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#56]
>下方留下相关的描述即可

**1.描述出现的问题**

安装时失败，有以下提示：

进度 15/17 : 添加伪装站点 

检测到安装伪装站点，是否需要重新安装[y/n]：y
 ---> 添加伪装站点成功 
 ---> V2Ray关闭成功 
 ---> V2Ray启动成功 
nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/alone.conf:11
 ---> Nginx启动失败，请检查日志

**2.是否直接安装失败**
- 是

**3.直接安装失败的错误内容或者截图**
- 此项没有可忽略

**4.系统版本【例：Debian 8】**
>下列系统版本需自己补全
- Debian 8

**5.脚本版本**
- 

**6.安装类型**
- 安装
- 个性化安装

**7.安装的核心版本**
>version位置需自己替换
- Xray-core【version】
- v2ray-core【4.33】
- v2ray-core[XTLS]

**8.出现问题的协议类型**
- VLESS+XTLS
- VLESS+TLS+WS
- VMess+TLS+WS
- VMess+TLS+TCP
- Trojan
- Trojan-go+ws

**9.尝试重装后是否100%复现**
- 是

**10.是否仔细检查客户端与服务端的配置是否相同**
- 是
- 否

**Comment by AndersonGhost** [comment]
打开报错日志为：
root@KK:~# vim /etc/nginx/conf.d/alone.conf
    server {
        listen 80;
        server_name XXX.XXX;
        return 301 https://XXX.XXX;
    }
    server {
        listen 31300;
        server_name XXX.XXX;
        root /usr/share/nginx/html;
        location / {
            add_header Strict-Transport-Security "max-age=63072000" always;
        }
#       location ~ /.well-known {allow all;}
#       location /test {return 200 'fjkvymb6len';}
    }

**Comment by mack-a** [comment]
> 打开报错日志为：
> root@KK:~# vim /etc/nginx/conf.d/alone.conf
> server {
> listen 80;
> server_name XXX.XXX;
> return 301 https://XXX.XXX;
> }
> server {
> listen 31300;
> server_name XXX.XXX;
> root /usr/share/nginx/html;
> location / {
> add_header Strict-Transport-Security "max-age=63072000" always;
> }
> 
> # location ~ /.well-known {allow all;}
> # location /test {return 200 'fjkvymb6len';}
> ```
> }
> ```

看一下nginx的版本

**Comment by AndersonGhost** [comment]
root@KK:~# nginx -v
nginx version: nginx/1.6.2

**Comment by AndersonGhost** [comment]
root@KK:~# nginx -v
nginx version: nginx/1.6.2

**Comment by mack-a** [comment]
> 打开报错日志为：
> root@KK:~# vim /etc/nginx/conf.d/alone.conf
> server {
> listen 80;
> server_name XXX.XXX;
> return 301 XXX.XXX;
> }
> server {
> listen 31300;
> server_name XXX.XXX;
> root /usr/share/nginx/html;
> location / {
> add_header Strict-Transport-Security "max-age=63072000" always;
> }
> # location ~ /.well-known {allow all;}
> # location /test {return 200 'fjkvymb6len';}
> }
把这个里面的63072000改成下面这个数字然后重启ngixn试试
31536000

**Comment by AndersonGhost** [comment]
现在还没有安装完成啊   重启之后怎么操作呢

**Comment by AndersonGhost** [comment]
重启之后，我把生成的链接导入v2rayN中，好像可以代理上网了，但是伪装网站不能代开。

**Comment by mack-a** [comment]
> 现在还没有安装完成啊 重启之后怎么操作呢

重启nginx

**Comment by AndersonGhost** [comment]
> > 现在还没有安装完成啊 重启之后怎么操作呢
> 
> 启动或者重启nginx

嗯，我就这样操作的。可以带来上网了。但是伪装网站还是不能打开。

**Comment by mack-a** [comment]
> > > 现在还没有安装完成啊 重启之后怎么操作呢
> > 
> > 
> > 启动或者重启nginx
> 
> 嗯，我就这样操作的。可以代理上网了。但是伪装网站还是不能打开。

b

> > > 现在还没有安装完成啊 重启之后怎么操作呢
> > 
> > 
> > 启动或者重启nginx
> 
> 嗯，我就这样操作的。可以代理上网了。但是伪装网站还是不能打开。

报错信息呢

**Comment by AndersonGhost** [comment]
无法访问此网站 XXX.XXX 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by mack-a** [comment]
> 无法访问此网站 XXX.XXX 拒绝了我们的连接请求。
> 请试试以下办法：
> 
> 检查网络连接
> 检查代理服务器和防火墙
> ERR_CONNECTION_REFUSED

nginx的报错信息

**Comment by AndersonGhost** [comment]
> > 无法访问此网站 XXX.XXX 拒绝了我们的连接请求。
> > 请试试以下办法：
> > 检查网络连接
> > 检查代理服务器和防火墙
> > ERR_CONNECTION_REFUSED
> 
> nginx的报错信息

如何查看报错信息啊？脚本安装失败后，我就没有进行再次安装了

**Comment by mack-a** [comment]
> > > 无法访问此网站 XXX.XXX 拒绝了我们的连接请求。
> > > 请试试以下办法：
> > > 检查网络连接
> > > 检查代理服务器和防火墙
> > > ERR_CONNECTION_REFUSED
> > 
> > 
> > nginx的报错信息
> 
> 如何查看报错信息啊？脚本安装失败后，我就没有进行再次安装了

你这是哪一个厂的vps，源好老

**Comment by AndersonGhost** [comment]
是呀，使用了伯力的机器   现在使用Debian 9的系统，安装正常了
