### ISSUE TITLE
请问可否增加流量限制功能

### ISSUE THREAD

**Issue by sdshdv** [mack-a/v2ray-agent#561]
是否能增加流量限制功能，如每月1TB后断网，然后每月1号自动恢复

**Comment by mack-a** [comment]
不会

**Comment by w9315273** [comment]
连个流量查询都没有 今天忽然跑了2TB流量 都不知道是哪个用户跑的

**Comment by yzx1208** [comment]
无限流量VPS了解下。

**Comment by mack-a** [comment]
> 连个流量查询都没有 今天忽然跑了2TB流量 都不知道是哪个用户跑的

你可以用一个有流量控制的
