### ISSUE TITLE
更新geo文件后会出现误拦截

### ISSUE THREAD

**Issue by mx4994** [mack-a/v2ray-agent#564]
**1.问题描述**
在脚本里面开启禁CN，使用默认的geo文件，一切正常，但是我更新geo文件之后，会拦截gstatic相关的域名，但是我看了geosite文件CN里面是没有gstatic相关域名的。

**2.安装失败的错误内容或者截图**
![image](https://user-images.githubusercontent.com/52325833/223066322-6ff645a2-7f37-411f-bfde-9be821e15aa1.png)

**3.系统版本**
Debian11  5.10.0-21-cloud-amd64

**4.脚本版本**
- 2.7.7

**5.核心类型及版本**
- XRAY 1.75
- hysteria 1.3.3

hysteria和xray里面的协议都是一样的被拦截。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.7.8
