### ISSUE TITLE
安装时指定的非443端口无效

### ISSUE THREAD

**Issue by dario-github** [mack-a/v2ray-agent#565]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
安装时已指定554端口，但v2rayN无法连接，查看nginx错误日志发现仍然在请求443端口

**2.安装失败的错误内容或者截图**
v2ray节点延迟及测速
<img width="779" alt="image" src="https://user-images.githubusercontent.com/40749119/223582786-a6a521dc-e6e5-4e00-bfe5-66c68f3b39cb.png">
Nginx错误日志及监听日志
```
k.ml"
2023/03/07 23:55:00 [error] 2278479#2278479: *131 open() "/etc/nginx/html/adowvws" failed (2: No such file or directory), client: 172.70.211.60, server: _, request: "GET /adowvws HTTP/1.1", host: "proxy.dariolink.ml"
2023/03/07 23:55:00 [error] 2278479#2278479: *132 open() "/etc/nginx/html/adowvws" failed (2: No such file or directory), client: 172.69.34.20, server: _, request: "GET /adowvws HTTP/1.1", host: "proxy.dariolink.ml"

162.158.166.63 - - [07/Mar/2023:23:59:38 +0000] "GET /adowvws HTTP/1.1" 404 153 "-" "Go-http-client/1.1" "60.186.155.148"
172.69.134.97 - - [07/Mar/2023:23:59:38 +0000] "GET /adowvws HTTP/1.1" 404 153 "-" "Go-http-client/1.1" "60.186.155.148"
```
通过脚本指定的端口
<img width="113" alt="image" src="https://user-images.githubusercontent.com/40749119/223583274-f2317f51-9d95-4acf-83f7-40de68382781.png">
nginx配置
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/ssl/wx.dariolink.ml.pem;
        ssl_certificate_key /etc/nginx/ssl/wx.dariolink.ml.key;

        location /wx {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

```

**3.系统版本**
Linux vultr.guest 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**4.脚本版本**
2.7.7

**5.核心类型及版本**
1.7.5
<img width="185" alt="image" src="https://user-images.githubusercontent.com/40749119/223583550-016190f9-1d10-4296-925c-479815f50be5.png">

**Comment by dario-github** [comment]
xray确实在监听554端口
<img width="573" alt="image" src="https://user-images.githubusercontent.com/40749119/223584524-ee7eced1-df3e-4ac7-8dcd-092ca1109214.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/40749119/223584839-23fd68ed-f05d-417a-947e-75648f13bb04.png">

但不知道为什么v2rayN联不通，以及nginx的错误日志是哪里发起的请求

**Comment by gnuhpc** [comment]
![image](https://user-images.githubusercontent.com/11542289/231652586-2af8bd7c-0109-4cee-8e9f-e472b0fe7d18.png)

**Comment by gnuhpc** [comment]
OS全新安装，选择了8888，v2ray全套安装，端口出来是没有的，OS重装两遍了，疑似有bug。

**Comment by gnuhpc** [comment]
v2ray-agent-2.7.2 没问题，亲你看看你在更新REALITY的几次commit是不是有bug，感谢
