### ISSUE TITLE
DMIT Hongkong Lite 回程已经不是三网CMI了

### ISSUE THREAD

**Issue by zazi0001** [mack-a/v2ray-agent#569]
**详细描述建议的内容**
![image](https://user-images.githubusercontent.com/28730221/224212281-a26c8d14-879d-4c6d-b31a-d9db830192f1.png)
![image](https://user-images.githubusercontent.com/28730221/224212611-b46e296d-6450-47fe-8efb-6bc03bd33d27.png)
![image](https://user-images.githubusercontent.com/28730221/224212661-1a5e45c7-efbf-445c-b1cc-d796dde16b41.png)
只有移动能用

**Comment by mack-a** [comment]
感谢反馈，已修改
