### ISSUE TITLE
ipv6 无法安装

### ISSUE THREAD

**Issue by zyaowei** [mack-a/v2ray-agent#57]
>下方留下相关的描述即可

**1.描述出现的问题**
```
ipv6 无法安装
不识别ip，信息如下。
```

**2.是否直接安装失败**
- 是

**3.直接安装失败的错误内容或者截图**
- ---> 安装binutils
---> 安装ping6

进度 2/17 : 初始化Nginx申请证书配置

请输入要配置的域名 例：blog.v2ray-agent.com --->
域名:aa.suibianba02.cf

---> 配置Nginx

检查IP是否设置为当前VPS
ping: unknown host
IP查询失败，是否重试[y/n]？y
ping: unknown host
IP查询失败，是否重试[y/n]？y
ping: unknown host
IP查询失败，是否重试[y/n]？n

**4.系统版本【例：Centos8】**
- debian10

**5.脚本版本**
- 12月24日时间点最新版

**6.安装类型**
- 个性化安装/全部安装

**7.安装的核心版本**
- v2ray-core【version】

**8.出现问题的协议类型**
- ws cdn

**9.尝试重装后是否100%复现**
- 是

**10.是否仔细检查客户端与服务端的配置是否相同**
- 是

**Comment by mack-a** [comment]
目前ipv6还不支持，请关注后续版本

**Comment by mack-a** [comment]
明天发新版

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.2.7 请使用新版本

**Comment by zyaowei** [comment]
非常感谢。
