### ISSUE TITLE
更换网站 访问域名404

### ISSUE THREAD

**Issue by yumaoss** [mack-a/v2ray-agent#570]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
更换网站后 访问域名404，/usr/share/nginx下只有html2.zip

**2.安装失败的错误内容或者截图**
请选择:2
html2.zip                         100%[==========================================================>]   2.52M  --.-KB/s    in 0.1s    
unzip:  cannot find or open /usr/share/nginx/html/2.zip, /usr/share/nginx/html/2.zip.zip or /usr/share/nginx/html/2.zip.ZIP.
 ---> 更换伪站成功 

**3.系统版本**
Debian 11

**4.脚本版本**
最新

**5.核心类型及版本**
xray 默认

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.7.13
