### ISSUE TITLE
请问脚本能否新增支持reality

### ISSUE THREAD

**Issue by tunlong** [mack-a/v2ray-agent#571]
**详细描述建议的内容**
最近v2rayN也更新了reality支持，而且最近阻断的很厉，能否请大大更新reality，谢谢!!

**Comment by mack-a** [comment]
会

**Comment by chancat87** [comment]
啥时候支持reality呀。pass都更新了

**Comment by AgathonLi** [comment]
@mack-a 请问大佬会不会增加REALITY H2呀？想试试但目前好像没一键部署支持。
看到RPRX：[REALITY 不能过免费 CDN，故 gRPC 与 H2 区别不大，由于 gRPC 是 over H2，直接用 H2 相对省一点点。](https://github.com/XTLS/Xray-core/discussions/1719)

**Comment by mack-a** [comment]
> @mack-a 请问大佬会不会增加REALITY H2呀？想试试但目前好像没一键部署支持。 看到RPRX：[REALITY 不能过免费 CDN，故 gRPC 与 H2 区别不大，由于 gRPC 是 over H2，直接用 H2 相对省一点点。](https://github.com/XTLS/Xray-core/discussions/1719)

目前还不打算支持
