### ISSUE TITLE
脚本域名解析问题

### ISSUE THREAD

**Issue by freakojc** [mack-a/v2ray-agent#573]
---> 检查域名ip中 
 ---> Nginx关闭成功 

 ---> 未检测到当前域名的ip

dns已设置记录 nslookup命令可以解析域名成功 同时已设置networks指定域名和ip

但是
curl: (7) Failed connect to xxx.xxx.com:80; Connection refused
脚本无法执行继续

**Comment by mack-a** [comment]
1.按照提示挨个检查
2.检查云朵状态
3.dd纯净系统重新安装
