### ISSUE TITLE
请教：VLESS+TCP+TLS_Vision中【security】的值应该为tls还是xtls？

### ISSUE THREAD

**Issue by bylucky** [mack-a/v2ray-agent#574]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- vasma命令添加账号后，VLESS+TCP+TLS_Vision 无法连网，把客户端配置文件中的 [安全] 的值: tls 改为 XTLS后可正常连网，
- 请教： security 应该为 tls 还是XTLS？
- 

**2.安装失败的错误内容或者截图**
- 自动生成的配置信息如下：
- 格式化明文(VLESS+TCP+TLS_Vision)
协议类型:VLESS，地址:XXX.com，端口:443，用户ID:XXXX-bc27-45f9-XXX-XXX，安全:tls，传输方式:tcp，flow:xtls-rprx-vision，账户名:default

**3.系统版本**
- debian

**4.脚本版本**
- 2.7.13

**5.核心类型及版本**
- XRAY 最新

**Comment by mack-a** [comment]
是tls，以后没有xtls这个选项，建议更新你的客户端

**Comment by bylucky** [comment]
感谢回答
