### ISSUE TITLE
已安装过ngxin无法运行脚本

### ISSUE THREAD

**Issue by byteslaves** [mack-a/v2ray-agent#58]
我的vps已经挂了博客网站的，使用脚本安装失败，报错如下：
请选择:1

功能 1/1 : 选择核心安装 

============================================================== 
1.Xray-core 
2.v2ray-core 
3.v2ray-core[XTLS] 
============================================================== 
请选择：3

进度  2/17 : 安装工具 
 ---> 检查安装jq、nginx epel源、yum-utils 
 ---> 检查、安装更新【新机器会很慢，耐心等待】 

Transaction check error:
  file /etc/my.cnf from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-config-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/Index.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/armscii8.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/ascii.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp1250.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp1251.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp1256.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp1257.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp850.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp852.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/cp866.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/dec8.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/geostd8.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/greek.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/hebrew.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/hp8.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/keybcs2.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/koi8r.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/koi8u.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/latin1.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/latin2.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/latin5.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/latin7.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/macce.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/macroman.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/charsets/swe7.xml from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-common-5.7.23-1.el7.x86_64
  file /usr/share/mysql/czech/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/danish/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/dutch/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/english/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/estonian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/french/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/german/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/greek/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/hungarian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/italian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/japanese/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/korean/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/norwegian-ny/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/norwegian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/polish/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/portuguese/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/romanian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/russian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/serbian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/slovak/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/spanish/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/swedish/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64
  file /usr/share/mysql/ukrainian/errmsg.sys from install of mariadb-libs-1:5.5.68-1.el7.x86_64 conflicts with file from package appnode-mysql57-errmsg-5.7.23-1.el7.x86_64

Error Summary
-------------

 ---> 安装binutils 

进度  3/17 : 初始化Nginx申请证书配置 

请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:store.**.io
 ---> 配置Nginx 

检查IP是否设置为当前VPS 
 ---> 检查ipv4中 

当前域名的IP为 [******]，是否正确[y/n]？y

 ---> IP确认完成 

检查Nginx是否正常访问 
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->

**Comment by mack-a** [comment]
建议使用纯净系统。

**Comment by byteslaves** [comment]
> 建议使用纯净系统。

那和你的脚本无缘了，只能手动搭了，建议考虑一下兼容已安装ngxin

**Comment by mack-a** [comment]
> > 建议使用纯净系统。
> 
> 那和你的脚本无缘了，只能手动搭了，建议考虑一下兼容已安装ngxin

是有兼容已安装过的nginx，如果你自己安装的内容占用了端口 ，脚本是无法进行搭建的。这和兼容没有关系。

**Comment by mack-a** [comment]
> > 建议使用纯净系统。
> 
> 那和你的脚本无缘了，只能手动搭了，建议考虑一下兼容已安装ngxin

个性化需求建议使用docker或者就像你说的手动搭建。

**Comment by mack-a** [comment]
其实可以先用脚本安装完成后，在手动修改nginx的进行反代到个人站点。

**Comment by kilvn** [comment]
> 个性化需求建议使用docker或者就像你说的手动搭建。

如何使用docker搭建
