### ISSUE TITLE
xshell 中 退格和方向键无效

### ISSUE THREAD

**Issue by pencilqaq** [mack-a/v2ray-agent#580]
**1.问题描述**
xshell 中 退格和方向键无效

**2.安装失败的错误内容或者截图**
![QQ截图20230316182354](https://user-images.githubusercontent.com/36183335/225588378-da898b56-4469-4499-881b-fecc97dcca94.png)

**3.系统版本**
- ubuntu lts 22.04

**4.脚本版本**
- v2.7.13

**5.核心类型及版本**

**Comment by mack-a** [comment]
xshell改个配置就好，Google一下
