### ISSUE TITLE
安装【 VLESS+TLS+WS[CDN]】后安卓v2rayNG链接测试显示tls handshake timeout

### ISSUE THREAD

**Issue by FantaXI** [mack-a/v2ray-agent#581]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
按照流程安装了 VLESS+TLS+WS[CDN] ，端口是443,中途未出现报错信息，安装完成后复制生成的链接到安卓v2rayNG中连接，显示tls handshake timeout。手动按照参数新增链接，结果一致。
访问伪装域名网页正常访问。
**2.安装失败的错误内容或者截图**
<img width="323" alt="1679141544523" src="https://user-images.githubusercontent.com/44300551/226105272-283530ba-895d-4e1e-b38b-b8a940ec8443.png">

**3.系统版本**
安卓v2rayNG版本：1.8.0
**4.脚本版本**
脚本版本：v2.7.13 

**5.核心类型及版本**

**Comment by FantaXI** [comment]
![image](https://user-images.githubusercontent.com/44300551/226105621-00da9811-c5b7-473e-a001-c502212076eb.png)
xray版本应该是这个吧：Xray 1.7.5

**Comment by mack-a** [comment]
检查端口是否被阻断

**Comment by FantaXI** [comment]
![image](https://user-images.githubusercontent.com/44300551/226106202-8c75f8d9-ff00-45b4-849f-a9fd2fef6510.png)
因为这个ip是被墙的，所以国内无法连通。国外ip:443能正常访问，请问您说的检查阻断是如何检查，我不太明白

**Comment by mack-a** [comment]
如果IP被强了 只能套CDN。可以配合优选IP进行使用

**Comment by hs1608038** [comment]
@mack-a 怎么弄

**Comment by hs1608038** [comment]
@mack-a 弄好了,但是想问个问题,这样对速度有影响吗?
