### ISSUE TITLE
域名无法获取ip 

### ISSUE THREAD

**Issue by luchen7** [mack-a/v2ray-agent#585]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
iplc 共享机  无法安装

**2.安装失败的错误内容或者截图**
- 请在此处填写

**3.系统版本**
- 请在此处填写

**4.脚本版本**
- 请在此处填写

**5.核心类型及版本**
- 请在此处填写

**Comment by mack-a** [comment]
NAT需要 用自定义端口

**Comment by luchen7** [comment]
比如我入口是A深圳  出口是B香港  那么我要给我域名的A记录设定到哪里

**Comment by luchen7** [comment]
我在TG 上给你留言了

**Comment by luchen7** [comment]
运营商只给我10个A端端口

**Comment by luchen7** [comment]
可以付费指点吗？

**Comment by mack-a** [comment]
如果是个转发 只需要在落地机脚本搭建即可 IPLC的话 建议直接用更简单的方式（裸连）

**Comment by luchen7** [comment]
我是一台机器有两个IP的那种   不是nat转发  一个深圳IP  一个香港IP

**Comment by luchen7** [comment]
看下你的TG   给我你的捐赠地址

**Comment by mack-a** [comment]
你这种的我没玩过
