### ISSUE TITLE
warp分流后启动xray出错。

### ISSUE THREAD

**Issue by freeisok** [mack-a/v2ray-agent#587]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 我想使用脚本的warp分流功能，实现解锁chatgpt，按照脚本提示，按照warp，添加了2个域名：openai,ai，域名添加成功，但是xray启动失败。

**2.安装失败的错误内容或者截图**
<img width="987" alt="image" src="https://user-images.githubusercontent.com/123152339/229109387-3295c89c-130b-4af3-8b83-b3bbc720aef5.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/123152339/229109487-29d5ff14-db68-45ae-96a2-21c70a042c1b.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/123152339/229109546-56d000f6-ad12-4641-8d5e-4029f83556ca.png">

**3.系统版本**
- debian 11

**4.脚本版本**
- v2.7.13

**5.核心类型及版本**
- xray-core 1.7.5

**Comment by mack-a** [comment]
只填写openai 即可

**Comment by freeisok** [comment]
谢谢大佬，只填写openai确实可以了。

**Comment by kir0618** [comment]
![AB6C7152-A64E-4F4D-8964-2CBEB56CF640](https://user-images.githubusercontent.com/1255282/234976109-ad734246-a602-4416-ba71-f6ee878a815e.jpeg)

只填写 openai 一样报错了。

2.8.12 版本，Linux vultr 6.2.0-19-generic #19-Ubuntu SMP PREEMPT_DYNAMIC Sat Mar 25 10:22:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
