### ISSUE TITLE
Reality里的dest如果修改为其他网站，脚本搭建的伪站和订阅服务，都无法使用了。

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#591]
Reality里的dest如果修改为其他网站，脚本搭建的伪站和订阅服务，都无法使用了。
但dest指向其他网站，是Reality的重要特性之一。
这个很难说是bug。感觉有点难解决。

**Comment by mack-a** [comment]
建议使用 5 直接安装reality

**Comment by yoohooyoo** [comment]
大佬，如果希望同时安装Reality（dest写其他网站）和VLESS+TLS+WS两个协议，并能够使用订阅服务，是不是不太可能实现？

**Comment by mack-a** [comment]
可以实现

**Comment by mack-a** [comment]
> 大佬，如果希望同时安装Reality（dest写其他网站）和VLESS+TLS+WS两个协议，并能够使用订阅服务，是不是不太可能实现？

我重新理解了一下 如果仅仅安装 VLESS ws+reality不行 必须得 VLESS tls_vsion +reality+VLESS ws

**Comment by yoohooyoo** [comment]
> > 大佬，如果希望同时安装Reality（dest写其他网站）和VLESS+TLS+WS两个协议，并能够使用订阅服务，是不是不太可能实现？
> 
> 我重新理解了一下 如果仅仅安装 VLESS ws+reality不行 必须得 VLESS tls_vsion +reality+VLESS ws

明白。现在是不是已经可以了？
我测试一下去。

**Comment by yoohooyoo** [comment]
> > > 大佬，如果希望同时安装Reality（dest写其他网站）和VLESS+TLS+WS两个协议，并能够使用订阅服务，是不是不太可能实现？
> > 
> > 
> > 我重新理解了一下 如果仅仅安装 VLESS ws+reality不行 必须得 VLESS tls_vsion +reality+VLESS ws
> 
> 明白。现在是不是已经可以了？ 我测试一下去。

测试了下，目前的版本还不可以。
