### ISSUE TITLE
centos7的wget不支持 --show-progress参数

### ISSUE THREAD

**Issue by liqunfeifei** [mack-a/v2ray-agent#592]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 运行脚本出现wget错误

**2.安装失败的错误内容或者截图**
```
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

进度  6/13 : 配置Xray开机自启
```

**3.系统版本**
- CentOS Linux release 7.9.2009 (Core)

**4.脚本版本**
- 202304062208

**5.核心类型及版本**
- 请在此处填写

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.1
