### ISSUE TITLE
支持输入已有证书路径

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#595]
呃在用[歇斯底里](https://github.com/emptysuns/Hi_Hysteria)脚本的时候发现它有个选项：
> 开始配置:
请选择证书申请方式:
1、使用ACME申请(推荐,需打开tcp 80/443)
2、使用本地证书文件
3、自签证书
输入序号:

选项2 使用本地证书，可以输入已有证书路径，输入后就不必再申请，
很多脚本都要用到证书，这样就可以共用一个，

**Comment by mack-a** [comment]
脚本为了兼容性不可使用 自选证书
