### ISSUE TITLE
vultr debain11 脚本安装xray,多次重启机器和脚本一直卡在"生成证书中"

### ISSUE THREAD

**Issue by mypoint-01** [mack-a/v2ray-agent#596]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
脚本安装xray,多次重启机器和脚本一直卡在"生成证书中"

**2.安装失败的错误内容或者截图**
![image](https://user-images.githubusercontent.com/21329216/230698914-2b71074d-7667-4f42-823e-5597a654e17a.png)

**3.系统版本**
-vultr debain11 

**4.脚本版本**
最新

**5.核心类型及版本**
最新

**Comment by mack-a** [comment]
尝试使用下面的命令手动申请，如果还失败请贴一下日志

sudo "$HOME/.acme.sh/acme.sh" --issue -d www.example.com --standalone -k ec-256 --server letsencrypt

替换 www.example.com

**Comment by mack-a** [comment]
请测试后重新打开此issues
