### ISSUE TITLE
自测速脚本不支持debian吗？

### ISSUE THREAD

**Issue by lukemin** [mack-a/v2ray-agent#6]
自测速脚本不支持debian吗？求支持centos等其他的操作系统。
bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)

**Comment by mack-a** [comment]
> 自测速脚本不支持debian吗？求支持centos等其他的操作系统。
> bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)

目前仅支持ubuntu+Macos，debian 今天我有空兼容下。

**Comment by lukemin** [comment]
谢谢

**Comment by mack-a** [comment]
今天可能更新不了了 等明天 一定更新

**Comment by mack-a** [comment]
> 自测速脚本不支持debian吗？求支持centos等其他的操作系统。
> bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)

已兼容Debian

**Comment by lukemin** [comment]
> > 自测速脚本不支持debian吗？求支持centos等其他的操作系统。
> > bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)
> 
> 已兼容Debian

谢谢,可以把CentOS也一起加上吧？

**Comment by mack-a** [comment]
> > > 自测速脚本不支持debian吗？求支持centos等其他的操作系统。
> > > bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)
> > 
> > 
> > 已兼容Debian
> 
> 谢谢,可以把CentOS也一起加上吧？

已兼容

**Comment by mack-a** [comment]
> > > 自测速脚本不支持debian吗？求支持centos等其他的操作系统。
> > > bash <(curl -L -s https://raw.githubusercontent.com/mack-a/v2ray-agent/master/find_best_cdn_ip.sh)
> > 
> > 
> > 已兼容Debian
> 
> 谢谢,可以把CentOS也一起加上吧？

有其余需求的话，下次可以提issues。这个我就先关掉了😂
