### ISSUE TITLE
ngnix

### ISSUE THREAD

**Issue by jiujiu1** [mack-a/v2ray-agent#60]
最后一步ngnix启动失败。以前安装的2.1.7版本可以用，换Debian8系统后，安装最新版本。ngnix启动失败。。

**Comment by mack-a** [comment]
可以更换debian10解决这个问题

**Comment by jiujiu1** [comment]
![阿里旺旺图片20201227112756](https://user-images.githubusercontent.com/17944972/103163261-d857d200-4836-11eb-951b-c8436dc500c2.jpg)
![阿里旺旺图片20201227113022](https://user-images.githubusercontent.com/17944972/103163268-f9b8be00-4836-11eb-9d9b-2fc6707812eb.jpg)
![阿里旺旺图片20201227113038](https://user-images.githubusercontent.com/17944972/103163269-fb828180-4836-11eb-94f4-3bee9920c245.jpg)


小鸡 只有这几个系统

**Comment by mack-a** [comment]
> ![阿里旺旺图片20201227112756](https://user-images.githubusercontent.com/17944972/103163261-d857d200-4836-11eb-951b-c8436dc500c2.jpg)
> ![阿里旺旺图片20201227113022](https://user-images.githubusercontent.com/17944972/103163268-f9b8be00-4836-11eb-9d9b-2fc6707812eb.jpg)
> ![阿里旺旺图片20201227113038](https://user-images.githubusercontent.com/17944972/103163269-fb828180-4836-11eb-94f4-3bee9920c245.jpg)
> 
> 小鸡 只有这几个系统

你这个好像是用别的脚本安装过的样子

**Comment by mack-a** [comment]
可以用ubuntu试试

**Comment by mack-a** [comment]
> 最后一步ngnix启动失败。以前安装的2.1.7版本可以用，换Debian8系统后，安装最新版本。ngnix启动失败。。

这个问题我有空兼容下

**Comment by luboyan-hub** [comment]
求指导， Ubuntu 18.04.5 ，Nginx是否需要自己单独安装，如果不需要的话，我这是哪里出了问题，域名用cloudflare解析了，VPS的安全策略也都全部开放了，和我域名是.xyz有关系吗
<a href="https://sm.ms/image/7KYQnSzAoTPNcdC" target="_blank"><img src="https://i.loli.net/2020/12/27/7KYQnSzAoTPNcdC.png" ></a>


> 可以用ubuntu试试

**Comment by mack-a** [comment]
> 求指导， Ubuntu 18.04.5 ，Nginx是否需要自己单独安装，如果不需要的话，我这是哪里出了问题，域名用cloudflare解析了，VPS的安全策略也都全部开放了，和我域名是.xyz有关系吗
> 
> <a href="https://sm.ms/image/7KYQnSzAoTPNcdC" target="_blank"><img src="https://i.loli.net/2020/12/27/7KYQnSzAoTPNcdC.png" ></a>
> 
> 
> 
> 
> 
> > 可以用ubuntu试试
> 
> 
> 
> 

这个大概率是防火墙的问题

**Comment by jiujiu1** [comment]
安装BBR推荐的，重启之后就失去连接，ping不通，断链了，。是怎么回事？128MB内寸。vps限制安装BBR？

**Comment by mack-a** [comment]
> 安装BBR推荐的，重启之后就失去连接，ping不通，断链了，。是怎么回事？128MB内寸。vps限制安装BBR？

你的VPS是OVZ架构的吗，这种情况建议重做系统。

**Comment by mack-a** [comment]
已修改

**Comment by jiujiu1** [comment]
> > 安装BBR推荐的，重启之后就失去连接，ping不通，断链了，。是怎么回事？128MB内寸。vps限制安装BBR？
> 
> 你的VPS是OVZ架构的吗，这种情况建议重做系统。

![阿里旺旺图片20201229114612](https://user-images.githubusercontent.com/17944972/103257283-90b67f00-49cb-11eb-8d75-289a892245e7.jpg)
试了好几次了，一安装BBR就断链，ping不痛，只有这个debian8系统才可以用稳定，半年前都可以。，其他系统总断网代理，bbr都不能装。

**Comment by mack-a** [comment]
> > > 安装BBR推荐的，重启之后就失去连接，ping不通，断链了，。是怎么回事？128MB内寸。vps限制安装BBR？
> > 
> > 
> > 你的VPS是OVZ架构的吗，这种情况建议重做系统。
> 
> ![阿里旺旺图片20201229114612](https://user-images.githubusercontent.com/17944972/103257283-90b67f00-49cb-11eb-8d75-289a892245e7.jpg)
> 试了好几次了，一安装BBR就断链，ping不痛，只有这个debian8系统才可以用稳定，半年前都可以。，其他系统总断网代理，bbr都不能装。

ovz我记得搞不了 bbr

**Comment by jiujiu1** [comment]
> > > 安装BBR推荐的，重启之后就失去连接，ping不通，断链了，。是怎么回事？128MB内寸。vps限制安装BBR？
> > 
> > 
> > 你的VPS是OVZ架构的吗，这种情况建议重做系统。
> 
> ![阿里旺旺图片20201229114612](https://user-images.githubusercontent.com/17944972/103257283-90b67f00-49cb-11eb-8d75-289a892245e7.jpg)
> 试了好几次了，一安装BBR就断链，ping不痛，只有这个debian8系统才可以用稳定，半年前都可以。，其他系统总断网代理，bbr都不能装。

虚拟化类型：kvm
