### ISSUE TITLE
请仔细按照模版看填写，否则一律关闭issue

### ISSUE THREAD

**Issue by zhang-xxx** [mack-a/v2ray-agent#607]
## 1.问题描述
无法检测80端口开放
## 2.安装失败的log或者截图
![image](https://user-images.githubusercontent.com/29112596/231628602-feaabd35-6cbe-4000-96a3-045f7870aa92.png)
## 3.系统版本
CentOS 7.9.2009
## 4.脚本版本
v2.8.2

**Comment by mack-a** [comment]
[显示80端口未开放的可以优先 请求场外援助  IP 密码 私聊给 @mackaff](https://t.me/v2rayAgentChannel/1121)

**Comment by LMX58** [comment]
可能是你打开了CF的代理，要关掉才能正常安装
