### ISSUE TITLE
generate certificate with txt record

### ISSUE THREAD

**Issue by imanktch** [mack-a/v2ray-agent#609]
Hello
Please put the method of getting the certificate by inserting the txt record again.
When the certificate is issued as a stand-alone, we are limited in using the subdomain.
In the current method, we can only use one subdomain and it causes the subdomain to be blocked faster. If the issued certificate is in the form of *.domain.com , it gives us the possibility to give a subdomain to configuration.

**Comment by imanktch** [comment]
For more explanation, if the certificate is for the entire domain, I can consider a separate subdomain for each person and prevent the filtering system from paying attention to a specific subdomain.

**Comment by mack-a** [comment]
下个版本会支持
