### ISSUE TITLE
Debian 9下提示TLS安装失败

### ISSUE THREAD

**Issue by shanzicunren** [mack-a/v2ray-agent#61]
Debian 9下提示TLS安装失败

进度  3/17 : 申请TLS证书 
 ---> 安装TLS证书 
[Sun Dec 27 07:08:46 UTC 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: lz.shanzicunren.ga: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Sun Dec 27 07:08:46 UTC 2020] Please add '--debug' or '--log' to check more details.
[Sun Dec 27 07:08:46 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/lz.shanzicunren.ga_ecc/fullchain.cer: No such file or directory
 ---> TLS安装失败，请检查acme日志

**Comment by mack-a** [comment]
域名或者服务器钱发了太多次证书
