### ISSUE TITLE
可以增加 安装hysteria和reality时端口随机 的功能吗

### ISSUE THREAD

**Issue by ChellyL** [mack-a/v2ray-agent#612]
如题，
安装hysteria和reality时，端口要手动输入，可以增加回车随机端口功能吗
以及，如何直接选择安装hysteria，如果没有先安装其他协议，会提示
>“由于环境依赖，如安装hysteria，请先安装Xray/V2ray”

那为啥不直接增加询问是否安装xray-core呢，这样可以只用hysteria协议

**Comment by mack-a** [comment]
> 如题， 安装hysteria和reality时，端口要手动输入，可以增加回车随机端口功能吗 以及，如何直接选择安装hysteria，如果没有先安装其他协议，会提示
> 
> > “由于环境依赖，如安装hysteria，请先安装Xray/V2ray”
> 
> 那为啥不直接增加询问是否安装xray-core呢，这样可以只用hysteria协议

随机端口可以考虑，单独安装hy不太行
