### ISSUE TITLE
建议增加伪装网站选项

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#615]
建议除了伪装网站，增加“直接跳转到指定目标网站”和“403报错”选项。
在Reality协议部署后，这个功能可能帮助达到更好的伪装效果。

**Comment by mack-a** [comment]
> 建议除了伪装网站，增加“直接跳转到指定目标网站”和“403报错”选项。 在Reality协议部署后，这个功能可能帮助达到更好的伪装效果。

Reality不是又dest吗 普通的协议也有303跳转

**Comment by mack-a** [comment]
> Reality不是有dest吗 普通的协议也有303跳转

Reality不是有dest吗 普通的协议也有302跳转
