### ISSUE TITLE
ARM64,UBUNTU下安装WARP分流失败

### ISSUE THREAD

**Issue by flysn0w** [mack-a/v2ray-agent#617]
>不按照模版提交，一律关闭
## 1.问题描述
VPS为甲骨文云ARM64,UBUNTU下安装WARP分流失败
## 2.安装失败的log或者截图
 ---> 安装WARP
 ---> 安装WARP失败
## 3.系统版本
Ubuntu 22.10 (GNU/Linux 6.2.11-060211-generic aarch64)
## 4.脚本版本
2.8.7

**Comment by mack-a** [comment]
目前手头没有这个架构的服务器，有的时候再调试下。

**Comment by flysn0w** [comment]
新版shell采用wgcf来安装warp分流后,测试已可在aarch64下正常安装使用
