### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Saya47** [mack-a/v2ray-agent#618]
**详细描述建议的内容**

Hello! I'm using the new REALITY feature of XRAY.
My problem is the previous methods I was using, with v2ray, they also enabled IPV6 connectivity, but with this new config, I don't have IPV6 connectivity, is it possible to have that? My VPS does have IPV6, how should I modify the config to enable it?
Thanks for all the hard work! Appreciate it.

**Comment by mack-a** [comment]
如果本地没有IPv6，vps有IPv6，而你又想用IPv6，可以选择套一下cloudflare。
