### ISSUE TITLE
warp安装失败

### ISSUE THREAD

**Issue by hetmly** [mack-a/v2ray-agent#619]
>不按照模版提交，一律关闭
## 1.问题描述
warp安装失败，这是什么原因，在哪里看日志
## 2.安装失败的log或者截图

![image](https://user-images.githubusercontent.com/50097999/233448120-971f21e9-6ce2-402c-8c21-f0598b505b4a.png)

## 3.系统版本
ubuntu 20.04
## 4.脚本版本
2.8.7

**Comment by mack-a** [comment]
ARM以后会处理，还有别人已经提过issues了

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.9
