### ISSUE TITLE
大佬，自定义安装可不可以只安装trajon-go

### ISSUE THREAD

**Issue by ywyha** [mack-a/v2ray-agent#62]
**详细描述建议的内容**
有的小内存机器不需要同时安装两个，但是现在貌似自定义选项安装trajon-go依然会把vless装上。

**Comment by mack-a** [comment]
所有的组合都是基于VLESS的回落，目前不可以只单独安装一个

**Comment by ywyha** [comment]
> 所有的组合都是基于VLESS的回落，目前不可以只单独安装一个

大佬是不是24小时在线啊，每次问题都是秒回，O(∩_∩)O，明白了，谢谢大佬。

**Comment by mack-a** [comment]
其实可以改成单独只安装trojan-go，代码逻辑还需要重新规划

**Comment by ywyha** [comment]
> 其实可以改成单独只安装trojan-go，代码逻辑还需要重新规划

以后如果能单独安装自然而然是最好，还有现在的脚本不知道支不支持debian8安装trajon-go，我之前试过debian8，记得好像卡在nginx那里，然后我这两天脚本说明有关于debian8安装的问题，我以为可以安装了，然后我尝试用全新的系统环境安装依然卡在nginx那里报错，无法继续安装，还有大佬就是IPV6避验证问题，我头几天尝试了用那个大佬最后叫我安装的那个版本安装，依然是全新环净，我使用xray+vless+tls+ws的方式依然无法成功避开验证，@@折腾了好几遍依然不行，系统是全新DD的debian9环境，不过最新的脚本我没有尝试。

**Comment by mack-a** [comment]
> > 其实可以改成单独只安装trojan-go，代码逻辑还需要重新规划
> 
> 
> 
> 以后如果能单独安装自然而然是最好，还有现在的脚本不知道支不支持debian8安装trajon-go，我之前试过debian8，记得好像卡在nginx那里，然后我这两天脚本说明有关于debian8安装的问题，我以为可以安装了，然后我尝试用全新的系统环境安装依然卡在nginx那里报错，无法继续安装，还有大佬就是IPV6避验证问题，我头几天尝试了用那个大佬最后叫我安装的那个版本安装，依然是全新环净，我使用xray+vless+tls+ws的方式依然无法成功避开验证，@@折腾了好几遍依然不行，系统是全新DD的debian9环境，不过最新的脚本我没有尝试。

vps自带ipv6大概率还是需要Google 验证，建议使用HE

**Comment by mack-a** [comment]
> > 其实可以改成单独只安装trojan-go，代码逻辑还需要重新规划
> 
> 
> 
> 以后如果能单独安装自然而然是最好，还有现在的脚本不知道支不支持debian8安装trajon-go，我之前试过debian8，记得好像卡在nginx那里，然后我这两天脚本说明有关于debian8安装的问题，我以为可以安装了，然后我尝试用全新的系统环境安装依然卡在nginx那里报错，无法继续安装，还有大佬就是IPV6避验证问题，我头几天尝试了用那个大佬最后叫我安装的那个版本安装，依然是全新环净，我使用xray+vless+tls+ws的方式依然无法成功避开验证，@@折腾了好几遍依然不行，系统是全新DD的debian9环境，不过最新的脚本我没有尝试。

Debian8报错问题，可以用最新的脚本尝试，记得要用纯净版，由于我手里面没有debian8无法测试改的那个逻辑对不对。

**Comment by ywyha** [comment]
> > > 其实可以改成单独只安装trojan-go，代码逻辑还需要重新规划
> > 
> > 
> > 以后如果能单独安装自然而然是最好，还有现在的脚本不知道支不支持debian8安装trajon-go，我之前试过debian8，记得好像卡在nginx那里，然后我这两天脚本说明有关于debian8安装的问题，我以为可以安装了，然后我尝试用全新的系统环境安装依然卡在nginx那里报错，无法继续安装，还有大佬就是IPV6避验证问题，我头几天尝试了用那个大佬最后叫我安装的那个版本安装，依然是全新环净，我使用xray+vless+tls+ws的方式依然无法成功避开验证，@@折腾了好几遍依然不行，系统是全新DD的debian9环境，不过最新的脚本我没有尝试。
> 
> Debian8报错问题，可以用最新的脚本尝试，记得要用纯净版，由于我手里面没有debian8无法测试改的那个逻辑对不对。报错得话记得贴一下详细的错误信息

大佬 ,最新的脚本debian8安装成功，不报错了。我回家再试试IPV6防污染
