### ISSUE TITLE
2.8.9 新版wgcf的安装有点问题

### ISSUE THREAD

**Issue by szhangcn** [mack-a/v2ray-agent#621]
>不按照模版提交，一律关闭

## 2.安装失败的log或者截图
# 注意事项

# 免责声明：采用Xray-core官方文章中推荐的wgcf进行申请账号，需要依赖第三方开源项目

是否同意安装？[y/n]:y

 ---> wgcf版本:v2.2.16
wgcf_2.2.16_linux_amd64                    100%[=======================================================================================>]   8.59M  --.-KB/s    in 0.1s
mv: cannot stat '/root/wgcf-account.toml': No such file or directory
mv: cannot stat '/root/wgcf-profile.conf': No such file or directory

**Comment by mack-a** [comment]
重新执行下试试

**Comment by szhangcn** [comment]
![无标题](https://user-images.githubusercontent.com/4902402/233604952-57ad1910-f8a1-404d-aa86-7fc34eecb5ad.png)

**Comment by szhangcn** [comment]
重新执行还是一样的。第一次有下载的过程，重新执行就是少了一个下载

**Comment by mack-a** [comment]
卸载分流后再重新安装

**Comment by szhangcn** [comment]
已经试过了，卸载后再试还是一样。手工执行命令反馈申请太多次被ban了

xxxx:/etc/v2ray-agent/warp# ./wgcf register --accept-tos
2023/04/21 18:04:38 Using config file: wgcf-account.toml
2023/04/21 18:04:38 429 Too Many Requests

**Comment by mack-a** [comment]
有空我看看

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.10 试一下这个
