### ISSUE TITLE
wgcf problem

### ISSUE THREAD

**Issue by MH140000** [mack-a/v2ray-agent#622]
>不按照模版提交，一律关闭
## 1.问题描述
When I select option 3 in the warp section, wgcf is not deleted and can not install again.
## 3.系统版本
ubuntu 20
## 4.脚本版本
2.8.10

**Comment by mack-a** [comment]
如果安装过不会重新安装，可以选择卸载后重新安装

**Comment by MH140000** [comment]
It cannot be removed using option 3.
