### ISSUE TITLE
 VLESS reality_gRPC  & VLESS reality_vision 

### ISSUE THREAD

**Issue by isaac574** [mack-a/v2ray-agent#623]
>不按照模版提交，一律关闭
## 1.问题描述
以上二个协议在V2RAYNG可以用，但在V2RAYN运行出错。
## 3.系统版本
V2RAYNG--安桌12.0    V2RAYN--WIN7
以上2个APP均是最新版本的，内核均为XRAY的最新版本。

## 4.脚本版本
V2RAY AGENT 最新版本

***还有以上2个新的协议速度很是一般，比VLESS WS协议要慢很多。

**Comment by mack-a** [comment]
如果有一个客户端可用，与脚本关系不大。
