### ISSUE TITLE
wgcf换回warp-cli了吗，官方生成的IP访问openai会429 

### ISSUE THREAD

**Issue by qy8502** [mack-a/v2ray-agent#625]
昨天刚刚愉快的使用了一天，今天新部署的VPS发现没有了wgcf。
看看代码好像是回滚了吧。
设置分流warp后，访问openai会429 Too many requests in 1 hour. Try again later.

**Comment by mack-a** [comment]
回滚了 不是很稳定 经常有时候用不了
