### ISSUE TITLE
v2ray内核自定义端口失败

### ISSUE THREAD

**Issue by LesterLian** [mack-a/v2ray-agent#627]
>不按照模版提交，一律关闭
## 1.问题描述
安装v2ray内核，自定义9443端口之后，v2ray和nginx抢443端口导致安装失败。查看`/etc/v2ray-agent/v2ray/conf/02_VLESS_TCP_inbounds.json`，确认端口是443而不是9443。手动修改端口到9443之后，所有查看账号和查看订阅里的url都缺少端口。
## 2.安装失败的log或者截图
```
进度  3/13 : 初始化Nginx申请证书配置

请输入要配置的域名 例: www.v2ray-agent.com --->
域名:******

 ---> Nginx启动成功
 ---> 检测到80端口已开放

请输入端口[默认: 443]，可自定义端口[回车使用默认]
端口:9443

 ---> 端口: 9443
 ---> Nginx关闭成功
 ---> Nginx启动成功
 ---> V2Ray关闭成功

 ---> 检查域名ip中
 ---> Nginx关闭成功
 ---> 当前域名ip为:[******]

进度 11/13 : 添加伪装站点
 ---> 添加伪装站点成功
 ---> Nginx关闭成功
 ---> V2Ray关闭成功
 ---> V2Ray启动成功
 ---> Nginx启动失败
 ---> 请手动尝试安装nginx后，再次执行脚本
```
## 3.系统版本
Ubuntu 20.04.5 LTS
## 4.脚本版本
v2.8.9
## 建议
https://github.com/mack-a/v2ray-agent/blob/6f3a69e75f286bcb55b6e25af63e9d2655845cf3/install.sh#L555-L559
这段代码在以前的版本里是在判断内核coreInstallType外面的，不太确定安装的时候是怎么回事，但查看账号端口读不出来应该是这个导致的。

**Comment by mack-a** [comment]
v2ray目前没有新特性，建议使用xray。v2ray的问题有空会修复
