### ISSUE TITLE
大佬不知是否可以绑定多域名？

### ISSUE THREAD

**Issue by wertgftth** [mack-a/v2ray-agent#63]
大佬这个项目不知是否可以绑定多域名？ 求指教

**Comment by mack-a** [comment]
> 大佬这个项目不知是否可以绑定多域名？ 求指教

不可以多域名

**Comment by mack-a** [comment]
> 大佬这个项目不知是否可以绑定多域名？ 求指教

可以了解一下SNI分流

**Comment by wertgftth** [comment]
SNI分流不知有没有相关的资料？求指教。谢谢。

**Comment by mack-a** [comment]
> SNI分流不知有没有相关的资料？求指教。谢谢。

可以后续关注Xray-core的更新，未来可能加
