### ISSUE TITLE
建议：自主选择IPv6/Ipv4优先 & Reality 域名有效性检测

### ISSUE THREAD

**Issue by Marionic0723** [mack-a/v2ray-agent#632]
**详细描述建议的内容**
我发现，使用这个脚本，服务器可能是v6优先，但是客户端无一例外，默认都先走v4，只有v4连不上才走v6，而XUI一键搭建的，就是v4连入v6出去，

所以在安装时增加一个优先级选项就更好了，现在设置v6优先需要手动改 /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json.

   "outbounds":[
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":**"UseIPv4"**
            },
            "tag":"IPv4-out"
加粗这里改成v6，就会默认走v6了。

---

域名有效性检测参考这位大佬的fork ： https://github.com/Suysker/xray-agent/blob/master/install.sh

**Comment by yzx1208** [comment]
这里其实可以增加一个选项，例如4in4out，4in6out，6in4out，6in6out。用户自己设定。或者增加一个大类，比如命名增强功能或者个性选择之类的，nice！
