### ISSUE TITLE
定时更新证书脚本错误？

### ISSUE THREAD

**Issue by lovelygfj** [mack-a/v2ray-agent#633]
>不按照模版提交，一律关闭
## 1.问题描述
看不到定时更新证书的脚本的Log
运行vasma-20-4的时候，报错：
cannot open '/etc/v2ray-agent/crontab_tls.log' for reading: No such file or directory

## 3.系统版本
Debian 10

## 4.脚本版本
2.8.9

**Comment by lovelygfj** [comment]
刚刚装完的系统，不知道是否还没运行到定时更新脚本

**Comment by mack-a** [comment]
应该是吧 有空看看
