### ISSUE TITLE
需求提交

### ISSUE THREAD

**Issue by mack-a** [mack-a/v2ray-agent#635]
此条下可以进行反馈需求，确认可以加的会加到。https://github.com/mack-a/v2ray-agent/issues/76 ，截止5/4

**Comment by mack-a** [comment]
> 能否加入naive协议的支持

这个大概率是不会

**Comment by liuhongyue** [comment]
1、能否增加选项，选择出栈的时候是ipv4优先还是ipv6优先；

2、ipv6分流我在不同的机器上设置完后，xray启动报错，望修复。

**Comment by mack-a** [comment]
> 1、能否增加选项，选择出栈的时候是ipv4优先还是ipv6优先；
> 
> 2、ipv6分流我在不同的机器上设置完后，xray启动报错，望修复。

第一条有啥意义嘞

**Comment by liuhongyue** [comment]
现在gpt封ipv4比较厉害，但是ipv6还能用，所以希望增加此项目

**Comment by EricMzky** [comment]
老板，我觉得我们一键脚本可以增加一个逻辑：回退上一步选项，比如我错误的选择了“3”，进入到第三步，然后有一个Back的选择，重新选择正确的“4”，然后进行下一步安装；这个逻辑是不是要大改了；

**Comment by EricMzky** [comment]
然后，是否可以增加一个信息show，显示出当前所有安装的core或者其他相关工具的版本信息；

**Comment by mack-a** [comment]
> 现在gpt封ipv4比较厉害，但是ipv6还能用，所以希望增加此项目，我在我的甲骨文上测试过，走warp的ipv4就不能正常登录，但是走ipv6就可以

直接IPv6分流就好，这个问题有空我排查下

**Comment by mack-a** [comment]
> 然后，是否可以增加一个信息show，显示出当前所有安装的core或者其他相关工具的版本信息；

有显示core，但是工具版本号好像没啥意义

**Comment by mack-a** [comment]
> 老板，我觉得我们一键脚本可以增加一个逻辑：回退上一步选项，比如我错误的选择了“3”，进入到第三步，然后有一个Back的选择，重新选择正确的“4”，然后进行下一步安装；这个逻辑是不是要大改了；

这个不会搞了

**Comment by liuhongyue** [comment]
> > 现在gpt封ipv4比较厉害，但是ipv6还能用，所以希望增加此项目，我在我的甲骨文上测试过，走warp的ipv4就不能正常登录，但是走ipv6就可以
> 
> 
> 
> 直接IPv6分流就好，这个问题有空我排查下

谢谢大佬

**Comment by flysn0w** [comment]
建议把wgcf早点加回去,warp官方客户端不支持arm64,但是wgcf可以在arm64上用,或者做个可选,和官方客户端二选一安装

**Comment by JackiMa** [comment]
大佬您好！请问怎么设置IPv6分流呢？我按照脚本里的操作，配置ipv6分流后，xray启动报错。之前我以为是自己弄错了，于是重新开了个VPS，发现仍然报错。报错信息如下：

Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志
[root@JOR ~]# Xray启动失败
-bash: Xray启动失败: command not found
[root@JOR ~]# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)
A unified platform for anti-censorship.
2023/04/27 06:18:12 Using confdir from arg: /etc/v2ray-agent/xray/conf
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json > infra/conf/serial: failed to read config file at line 4 char 19 > invalid character ',' looking for beginning of value

赞美大佬！

**Comment by mack-a** [comment]
> 建议把wgcf早点加回去,warp官方客户端不支持arm64,但是wgcf可以在arm64上用,或者做个可选,和官方客户端二选一安装

早就加进去了但是我又删掉了 没什么用

**Comment by mack-a** [comment]
> 大佬您好！请问怎么设置IPv6分流呢？我按照脚本里的操作，配置ipv6分流后，xray启动报错。之前我以为是自己弄错了，于是重新开了个VPS，发现仍然报错。报错信息如下：
> 
> Xray启动失败 请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 [root@JOR ~]# Xray启动失败 -bash: Xray启动失败: command not found [root@JOR ~]# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64) A unified platform for anti-censorship. 2023/04/27 06:18:12 Using confdir from arg: /etc/v2ray-agent/xray/conf Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json > infra/conf/serial: failed to read config file at line 4 char 19 > invalid character ',' looking for beginning of value
> 
> 赞美大佬！

vps 私聊给 tg @mackaff 我刚试了下没复现呀

**Comment by liuhongyue** [comment]
> > 大佬您好！请问怎么设置IPv6分流呢？我按照脚本里的操作，配置ipv6分流后，xray启动报错。之前我以为是自己弄错了，于是重新开了个VPS，发现仍然报错。报错信息如下：
> 
> > 
> 
> > Xray启动失败 请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 [root@JOR ~]# Xray启动失败 -bash: Xray启动失败: command not found [root@JOR ~]# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64) A unified platform for anti-censorship. 2023/04/27 06:18:12 Using confdir from arg: /etc/v2ray-agent/xray/conf Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json > infra/conf/serial: failed to read config file at line 4 char 19 > invalid character ',' looking for beginning of value
> 
> > 
> 
> > 赞美大佬！
> 
> 
> 
> vps 私聊给 tg @mackaff 我刚试了下没复现呀

我分流的时候也是同样的报错

**Comment by mack-a** [comment]
> 

https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.12 修复

**Comment by JackiMa** [comment]
赞美大佬！

**Comment by kittyzero520** [comment]
我不用ipv6也提示失败了
进度 10/13 : 添加定时维护证书 

 ---> 添加定时维护证书成功 

进度 11/13 : 添加伪装站点 
 ---> 添加伪装站点成功 
 ---> Nginx关闭成功 
 ---> Xray关闭成功 
 ---> Xray启动成功 
 ---> Nginx启动成功 

进度 12/13 : 验证服务启动状态 
 ---> 服务启动失败，请检查终端是否有日志打印

**Comment by mack-a** [comment]
> 我不用ipv6也提示失败了 进度 10/13 : 添加定时维护证书
> 
> ---> 添加定时维护证书成功
> 
> 进度 11/13 : 添加伪装站点 ---> 添加伪装站点成功 ---> Nginx关闭成功 ---> Xray关闭成功 ---> Xray启动成功 ---> Nginx启动成功
> 
> 进度 12/13 : 验证服务启动状态 ---> 服务启动失败，请检查终端是否有日志打印

你这个应该是延迟超时了，用脚本中的core管理启动下内核应该就可以了

**Comment by liuhongyue** [comment]
> > 
> 
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.12 修复

非常感谢，今天用了一下，全是绿色，没有报错

**Comment by liouxunhuan8** [comment]
Xray启动失败 
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志 
root@mjj:~# ^C
root@mjj:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)
A unified platform for anti-censorship.
2023/04/29 21:49:19 Using confdir from arg: /etc/v2ray-agent/xray/conf
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/01_netflix_inbounds.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json ] appended inbound with tag:  VLESSTCP
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json ] appended inbound with tag:  VLESSReality
xctl> [ /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json ] appended inbound with tag:  VLESSRealityGRPC
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/09_routing.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
2023/04/29 21:49:19 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/12_policy.json
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/01_netflix_inbounds.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:1 > infra/conf: failed to load geosite: 1 > infra/conf: list not found in geosite.dat: 1


不知道什么缘故

**Comment by hetmly** [comment]
希望可以增加流量控制功能，或者是可以设置一个最高值，达到设置的这个流量就关闭xary或者阻止连接啥的，因为部分服务器超流量的价格太贵了，例如aws啥的

**Comment by liouxunhuan8** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cengzhijie3** [comment]
你好，我用euserv搭建时显示v2ray配置有问题，无法下载你的xray文件
<img width="1002" alt="截圖 2023-05-01 下午7 11 50" src="https://user-images.githubusercontent.com/89333400/235575337-8dfa103b-3505-4319-879c-6730b5d826bb.png">
<img width="1002" alt="截圖 2023-05-01 下午7 12 14" src="https://user-images.githubusercontent.com/89333400/235575358-edc428a1-7c9b-437a-a2a2-7bd3c2b5496e.png">
