### ISSUE TITLE
安装后部分网页ERR

### ISSUE THREAD

**Issue by EricMzky** [mack-a/v2ray-agent#636]
## 1.问题描述
1. 安装VLESS+TLS_Vision+TCP[推荐]后；
2. 浏览油管没问题
3. 登陆VPS SSH出现问题，无法连接
4. 登陆搬瓦工后台网页出现ERR
5. 小火箭延迟测试方法选择TCP 没问题，选择Connect出现超时；
<img width="766" alt="image" src="https://user-images.githubusercontent.com/37823382/234538688-34ac50b0-fa1b-4c40-8bee-7cc05fa78702.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/37823382/234538727-98e085d2-5e4c-49fc-8c35-df02c4f4967a.png">

## 2.安装失败的log或者截图
<img width="733" alt="image" src="https://user-images.githubusercontent.com/37823382/234538190-0e359771-c6cb-4735-a245-7fdc2ebe75a5.png">

## 3.系统版本
debain 11
## 4.脚本版本
最新

**Comment by EricMzky** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/37823382/234539126-188b4395-7898-48d7-87a6-c9233a613698.png">

**Comment by mack-a** [comment]
ping.pe检查下端口和ip

**Comment by EricMzky** [comment]
> ping.pe检查下端口和ip

老板，IP和端口检查过，IP为VPS IP，端口配置为14799（非默认443）

**Comment by mack-a** [comment]
![image](https://user-images.githubusercontent.com/57424792/234575121-7f2fc81d-a343-4d53-977f-e7d337d8a09d.png)
我才发现你这个是不兼容的。小火煎只兼容到 1.7.5 超过这个版本就没法用了

https://www.v2ray-agent.com/archives/1680104902581#heading-9

iOS端可以尝试下，wingsx 或者 V2Box

**Comment by EricMzky** [comment]
大佬，我发现开了bless + XTSL 这个，Tele连接不上啥情况。。。。有方法解答吗谢谢大佬啊

**Comment by EricMzky** [comment]
自身降级：bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --version 1.7.5
agent降级：1.7.5
已验证 可用
