### ISSUE TITLE
先安装了宝塔面包，再使用八合一脚本后报错

### ISSUE THREAD

**Issue by ccinoo** [mack-a/v2ray-agent#637]
>不按照模版提交，一律关闭
## 1.问题描述
先安装了宝塔面包，再使用八合一脚本后报错。请问如下报错，如何解决？谢谢
## 2.安装失败的log或者截图
` /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64) A unified platform for anti-censorship. 2023/04/25 20:41:40 Using confdir from arg: /etc/v2ray-agent/xray/conf Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json > infra/conf/serial: failed to read config file at line 4 char 19 > invalid character ',' looking for beginning of value`

/etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json文件内容：
` { "inbounds":[ { "port": 443, "protocol": "vless", "tag":"VLESSTCP", "settings": { "clients":[ { "id": "8cf3d280-cec******3cf4e5", "flow": "xtls-rprx-vision", "email": "8***80-VLESS_TCP/TLS_Vision", "add": "" } ], "decryption": "none", "fallbacks": [ {"dest":31300,"xver":0},{"alpn":"h2","dest":31302,"xver":0} ] }, "streamSettings": { "network": "tcp", "security": "tls", "tlsSettings": { "minVersion": "1.2", "alpn": [ "http/1.1", "h2" ], "certificates": [ { "certificateFile": "/etc/v2ray-agent/tls/***.***.***.crt", "keyFile": "/etc/v2ray-agent/tls/***.***.***.key", "ocspStapling": 3600, "usage":"encipherment" } ] } } } ]`
## 3.系统版本
`CentOS Linux release 7.9.2009 (Core)`
## 4.脚本版本
`前版本：v2.8.11 `

**Comment by mack-a** [comment]
已经在todolist里面了

**Comment by ccinoo** [comment]
非常感谢，期待早日解决。
`# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)
A unified platform for anti-censorship.
2023/04/27 19:55:55 Using confdir from arg: /etc/v2ray-agent/xray/conf
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json > infra/conf/serial: failed to read config file at line 4 char 19 > invalid character ',' looking for beginning of value`

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.16 已修复
