### ISSUE TITLE
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory

### ISSUE THREAD

**Issue by MH140000** [mack-a/v2ray-agent#638]
>不按照模版提交，一律关闭
## 1.问题描述
When I install the script and then change a reality using option 5 and then 1, this error is shown and all other configurations except reality are deleted.

 ---> Xray启动成功
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory

进度 8/13 : 账号
============================= VLESS reality_vision  ==============================

## 2.安装失败的log或者截图

 ---> Xray启动成功
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory

进度 8/13 : 账号
============================= VLESS reality_vision  ==============================

## 3.系统版本
ubuntu 20
## 4.脚本版本
latest

**Comment by mack-a** [comment]
执行**21**卸载后重新尝试安装

**Comment by MH140000** [comment]
I did this several times, but after selecting 5 and then 1, the same error is displayed again
