### ISSUE TITLE
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory

### ISSUE THREAD

**Issue by MH140000** [mack-a/v2ray-agent#639]
>不按照模版提交，一律关闭
## 1.问题描述
I created this issue before, but you responded by deleting it and then installing it. close it Unfortunately, I uninstalled and reinstalled the script several times. In the last version of the script, after installation by option 1 and then 1, if you choose option 5 to manage reality and go through the steps to the end, the following message will be displayed before generating vless related to reality:
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: No such file or directory
Please check it out.
## 3.系统版本
ubuntu 20
## 4.脚本版本
latest

**Comment by mack-a** [comment]
具体得复现步骤是什么

**Comment by MH140000** [comment]
Install using option 1 then 1 for xray, after install, manage reality using option 5 and then 1, and change domain and server name

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.8.13
