### ISSUE TITLE
可否自定义博客安装

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#64]
**详细描述建议的内容**
如题所述，可否提供自定义博客安装功能，提供更多的博客模板。根据自己的需求，自定义安装博客。

**Comment by mack-a** [comment]
自定义反代地址吗

**Comment by AndersonGhost** [comment]
就是您上面写的“伪装站点”啊   您目前好像就只有4种   可否根据自己的需求，自定义安装博客（伪装站点）呢。

**Comment by mack-a** [comment]
> 就是您上面写的“伪装站点”啊，您目前好像就只有4种。 可否根据自己的需求，自定义安装博客（伪装站点）呢？

可以，需要手动 将你的文件放到 /usr/share/nginx/html 这个目录下面
