### ISSUE TITLE
按照最新版本脚本重装后，提示No such file or directory

### ISSUE THREAD

**Issue by freeisok** [mack-a/v2ray-agent#640]
>不按照模版提交，一律关闭
## 1.问题描述

之前是7合1脚本装的，前几天发现vps上不了。于是采用最新8合1脚本重装，安装过程是根据官网的“一图教程”来的，很顺利，但是按照最后一步显示的账号相关信息里面有个提示，类似下面这样（通过账号查询得到的，安装完成后提示前面部分似乎有点区别）

/usr/bin/vasma: line 3447: /etc/v2ray-agent/subscribe_local/default/welovefree.tk_VLESS_XTLS/TLS: No such file or directory
/usr/bin/vasma: line 3450: /etc/v2ray-agent/subscribe_local/clashMeta/welovefree.tk_VLESS_XTLS/TLS: No such file or directory

然后上次提交issue没反应，一直提交不了，所以截图保存了，直接贴在下面。

## 2.安装失败的log或者截图

<img width="718" alt="image" src="https://user-images.githubusercontent.com/123152339/235332507-ac5f6654-82df-415b-85b0-d06140be1d08.png">

## 3.系统版本

debian 11 

## 4.脚本版本

v2.8.10

**Comment by freeisok** [comment]
又搞了一遍，按照官网这个教程：https://www.v2ray-agent.com/archives/1680104902581，搭建最新的Vision和Reality防止VPS端口封禁。然后按照教程里面配置客户端的步骤，vasma->6.账号管理->2.查看订阅，直接显示下面截图错误信息。

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/123152339/235333455-13531b7d-b1c7-46a6-9595-36822ec8374d.png">

**Comment by mack-a** [comment]
大版本升级都不兼容之前的东西。由于你是从老版本升级上来的 现在需要执行 21进行卸载后重新安装
