### ISSUE TITLE
重新安装TLS安装失败，No such file or directory。

### ISSUE THREAD

**Issue by gaxdel** [mack-a/v2ray-agent#641]
>不按照模版提交，一律关闭
## 1.问题描述
重新安装在tls安装步骤时错误 The domain '*.xxxx.com' is not a cert name. You must use the cert name to specify the cert to install.
尝试卸载脚本重装脚本之后再安装，tail: cannot open '/etc/v2ray-agent/tls/acme.log' for reading: No such file or directory。TLS安装失败。
## 2.安装失败的log或者截图
1.The domain '*.xxxx.com' is not a cert name. You must use the cert name to specify the cert to install.

2.tail: cannot open '/etc/v2ray-agent/tls/acme.log' for reading: No such file or directory
 ---> TLS安装失败，请检查acme日志

## 3.系统版本
Debian 11
## 4.脚本版本
2.8.12

**Comment by mack-a** [comment]
现在脚本不支持通配符证书

**Comment by gaxdel** [comment]
卸载脚本重装，换了个域名，tls成功安装了。不知道之前是什么原因。
