### ISSUE TITLE
malformed HTTP status code "JL\x870=\x8a\xa4Ɣ\xaf\x00\x02:\x00kHTTP/1.1"

### ISSUE THREAD

**Issue by kastnerka** [mack-a/v2ray-agent#642]
## 1.问题描述
VLESS+TCP+TLS_Vision 协议全新安装

## 2.安装失败的log或者截图
测速提示 [Warning] proxy/http: failed to read response from cachefly.cachefly.net > malformed HTTP status code "JL\x870=\x8a\xa4Ɣ\xaf\x00\x02:\x00kHTTP/1.1"

## 3.系统版本
Ubuntu 18.04

## 4.脚本版本
v2.8.12

**Comment by mack-a** [comment]
检查下端口或者IP是否正常使用
