### ISSUE TITLE
2.65 版本升级到 2.8.13 后，证书更新显示：未安装

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#646]
>不按照模版提交，一律关闭
- 使用21卸载后重新尝试
- 如果是旧版本升级到新版本的建议使用21卸载后重新安装

## 1.问题描述
2.6.5 版本升级到 2.8.13 后，再执行6.证书更新，显示：未安装
## 2.安装失败的log或者截图
1. 先在2.65版本下执行：证书更新，正常。
![image](https://user-images.githubusercontent.com/889925/236269405-9e0063a1-3b05-4981-8841-870bd2893d26.png)
2. 选 16 升级 到 2.8.13
![image](https://user-images.githubusercontent.com/889925/236269853-5e8bca21-2dda-4384-8c6f-f54fe0e644eb.png)
3. 再次执行8.证书更新，显示：未安装
![image](https://user-images.githubusercontent.com/889925/236270075-3330d3ae-181c-4868-8a11-9b60227117da.png)

## 4.脚本版本
2.65-> 2.8.13 

是不是 acme 的路径变了啊？大大，我不想重新安装，有没有什么方便的解决方法？
比如移动 /root/.acme.sh 文件夹位置？

**Comment by mack-a** [comment]
卸载重新安装
