### ISSUE TITLE
未检测到80端口开放，无法安装，后续会支持DNS API [TODO]

### ISSUE THREAD

**Issue by ouzc12358** [mack-a/v2ray-agent#647]
>不按照模版提交，一律关闭
- 使用21卸载后重新尝试
- 如果是旧版本升级到新版本的建议使用21卸载后重新安装

## 1.问题描述
安装后在域名填写完成后报警：

未检测到80端口开放，无法安装，后续会支持DNS API [TODO]

实际80端口已经在防火墙规则中放行，并且该规则已经使用很久了，之前并没有问题，

## 2.安装失败的log或者截图
![image](https://user-images.githubusercontent.com/7533211/236367452-04f74498-f32b-48a2-ba71-cd7b24a5ca9e.png)

## 3.系统版本
Debian 5.10.178-3

## 4.脚本版本
v2.8.13

**Comment by ouzc12358** [comment]
已经使用21卸载后重新安装，问题依旧

**Comment by ouzc12358** [comment]
在新的vps上使用依然报此错误

**Comment by mack-a** [comment]
可能是你的解析问题，可能解析的不对，ping域名试试
