### ISSUE TITLE
install.sh line 1812

### ISSUE THREAD

**Issue by Havard20009** [mack-a/v2ray-agent#651]
hello
what is this ?
进度  6/13 : 安装Xray 
/root/install.sh: line 1812: jq: command not found
 ---> Xray-core版本: 
 ---> 核心下载失败，请重新尝试安装

what should i do ?

**Comment by mack-a** [comment]
手动安装下jq

**Comment by Havard20009** [comment]
jq: error: Could not open file /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json: Permission denied
?!
