### ISSUE TITLE
检查证书的生成日期似乎有问题

### ISSUE THREAD

**Issue by zycboss** [mack-a/v2ray-agent#652]
## 1.问题描述
安装的是LE 90天的证书，但是每次使用 功能8 更新证书，检查时都显示剩余天数是90，检查日期在生成日期之后，生成日期似乎永远都是当天

找到脚本相关代码，发现读取的应该是 `$HOME/.acme.sh/${domain}_ecc/${domain}.cer` 这个路径的证书文件的修改时间，用WINSCP打开查看，证书文件的实际修改时间和脚本读取的不一致

这样会导致证书到期时脚本不进行自动更新

## 2.安装失败的log或者截图
![image](https://user-images.githubusercontent.com/29044143/236728973-8cd0347a-c9cd-440f-b285-0687d29c1cdc.png)
![image](https://user-images.githubusercontent.com/29044143/236729193-1a6477a2-1d00-410d-a573-002e7bcdddce.png)
![image](https://user-images.githubusercontent.com/29044143/236729618-4a38d735-77ba-4ebe-9613-06c52dc4b3d2.png)

## 3.系统版本
Ubuntu 22.04.2 LTS
Linux kernel 6.1.13

## 4.脚本版本
v2.8.15

**Comment by mack-a** [comment]
替换掉 stat "$HOME/.acme.sh/${domain}_ecc/${domain}.cer" 截图看一下

**Comment by zycboss** [comment]
似乎是系统语言造成的，我改成英文的就好了

中文环境下：
```
stat "/root/.acme.sh/www.***_ecc/www.***.cer" | sed -n '6,6p' | awk '{print $1" "$2" "$3" "$4" "$5}'
最近更改：2023-04-23 00:00:35.000000000 +0800
stat "/root/.acme.sh/www.***_ecc/www.***.cer" | sed -n '6,6p' | awk '{print $2" "$3" "$4" "$5}'
00:00:35.000000000 +0800
```
前面 “最近更改：2023-04-23 “ 这一段算成$1一体了

英文环境下：
```
stat "/root/.acme.sh/www.***_ecc/www.***.cer" | sed -n '6,6p' | awk '{print $1" "$2" "$3" "$4" "$5}'
Modify: 2023-04-23 00:00:35.000000000 +0800
stat "/root/.acme.sh/www.***_ecc/www.***.cer" | sed -n '6,6p' | awk '{print $2" "$3" "$4" "$5}'
2023-04-23 00:00:35.000000000 +0800
```
当然，脚本里的
`sed -n '7,6p'`
还是应该改成
`sed -n '6,6p'`
![image](https://user-images.githubusercontent.com/29044143/236751299-b548d45d-3fe3-4363-826d-adaa1fbd8753.png)

要不然读取的是最后修改（Change）时间，而不是文件创建（Modify）时间
```
stat "/root/.acme.sh/www.***_ecc/www.***.cer"
  File: /root/.acme.sh/www.***_ecc/www.***.cer
  Size: 1444            Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d    Inode: 655380      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-04-23 00:00:35.000000000 +0800
Modify: 2023-04-23 00:00:35.000000000 +0800
Change: 2023-05-08 13:52:30.813912932 +0800
```

修改后就正常了
![image](https://user-images.githubusercontent.com/29044143/236751104-6c9854f6-53de-40af-9747-0c7debe8600d.png)

**Comment by mack-a** [comment]
Access 这个不行 我以前试过

**Comment by mack-a** [comment]
Access 这个会出现一个问题 我以前试过

**Comment by zycboss** [comment]
> Access 这个会出现一个问题 我以前试过

那读modify呢？我改成
sed -n '6,6p'
和
sed -n '5,5p'
目前都是可以的

**Comment by zycboss** [comment]
另外，建议用
`stat -c%y`
读取修改日期，避免用print是遇到中文语言环境格式失效的问题
