### ISSUE TITLE
安装xray失败，在进度10重启xray失败

### ISSUE THREAD

**Issue by Einzelunterricht** [mack-a/v2ray-agent#659]
安装xray失败，报错日志为
ail: cannot open ‘/etc/v2ray-agent/xray/error.log’ for reading: No such file or
tail: no files remaining

**Comment by mack-a** [comment]
请说一下系统版本

**Comment by Einzelunterricht** [comment]
debian 10


mack-a ***@***.***> 于2023年5月16日周二 07:36写道：

**Comment by Einzelunterricht** [comment]
我这两天可能找到了原因，在反复安装下，bbr的自动安装脚本好像跟v2ray现在有冲突了

Songtao Chai ***@***.***> 于2023年5月20日周六 22:09写道：
