### ISSUE TITLE
关于修改UUID

### ISSUE THREAD

**Issue by lancehzzz1202** [mack-a/v2ray-agent#66]
大佬，能否增加在安装后修改UUID的功能，或者在允许在安装时指定UUID，vps较多的情况下，统一的UUID便于维护。

**Comment by mack-a** [comment]
> 大佬，能否增加在安装后修改UUID的功能，或者在允许在安装时指定UUID，vps较多的情况下，统一的UUID便于维护。

TODO功能

**Comment by mack-a** [comment]
> 大佬，能否增加在安装后修改UUID的功能，或者在允许在安装时指定UUID，vps较多的情况下，统一的UUID便于维护。

或者使用2.1.27 上一个稳定版本有这个功能

**Comment by lancehzzz1202** [comment]
> > 大佬，能否增加在安装后修改UUID的功能，或者在允许在安装时指定UUID，vps较多的情况下，统一的UUID便于维护。
> 
> 或者使用2.1.27 上一个稳定版本有这个功能

回复太快了。那我先自己手动修改脚本顶一阵。等TODO的部分更新就完美了。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.2.10 已添加
