### ISSUE TITLE
NAT机 申请证书 检测不到端口

### ISSUE THREAD

**Issue by zjjscwt** [mack-a/v2ray-agent#663]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
 NAT机 申请证书 检测不到端口 （已经重装全新系统 防火墙开放
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/18159420/ece73407-6fd2-4b69-9ef5-f8b1eb7701d0)
## 3.系统版本
lxc虚拟化 debian10
## 4.脚本版本
v 2.9.1

**Comment by mack-a** [comment]
目前手头没有测试机，以后有机会会尝试修复

**Comment by Billyas** [comment]
证书申请需要443端口，不支持其他端口的，nat机器如果没有就是443就是申请不了的

**Comment by ivangreat** [comment]
这个问题解决了吗，现在NAT机还有这个问题

**Comment by mack-a** [comment]
> 这个问题解决了吗，现在NAT机还有这个问题

NAT 内外端口都一致可以解决这个问题。
