### ISSUE TITLE
希望增加用户添加批量自选cloudflare ip或者域名，与现有链接进行组合

### ISSUE THREAD

**Issue by yzx1208** [mack-a/v2ray-agent#664]
**详细描述建议的内容**
希望增加用户添加 批量 自选cloudflare ip或者域名，与现有链接进行组合

**Comment by mack-a** [comment]
好像用处不是特别大

**Comment by yzx1208** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/72859262/5cdf964b-43af-4d37-b8fc-1fd25a0470bd)
功能9只能添加一个cdn,如果能批量添加优选ip更加好。

**Comment by yzx1208** [comment]
最好可以一直添加、读取文件列表、或者选择删除，机器不好的需要优选ip

**Comment by Shuang0606** [comment]
我觉得有必要，我用的就是rn

**Comment by yzx1208** [comment]
我只能说，作者牛逼爆了！

**Comment by yzx1208** [comment]
mack-a 添加cdn能不能像warp分流一样，能够实现累计添加，覆盖添加，删除指定，这样操作起来更加人性化。因为优选的本地ip有时候好，有时候坏。可以用户自己做出选择。

**Comment by mack-a** [comment]
有新需求单独开个issue，一般关掉的issue我就很少看了

**Comment by yzx1208** [comment]
好，后续提issue注意下。谢谢大佬！
