### ISSUE TITLE
希望增强对Hysteria的管理和yaml配置文件导出功能

### ISSUE THREAD

**Issue by garipan** [mack-a/v2ray-agent#665]
首先感谢Mack-a的付出，本脚本可以很好地让Hysteria和Xray共存，非常感谢！

原版Hysteria的本地文件.yaml可以连同分流方案一起一键导入Clash，非常好用，也是Hysteria最推荐的连接工具。
但通过本脚本配制好Hysteria之后，找不到本地文件.yaml，无法配置Clash等客户端。
希望本脚本后续可以支持，谢谢！

**Comment by mack-a** [comment]
ClashMeta支持 **订阅链接**不需要yaml，名字展示的不对，稍后我改一下。
