### ISSUE TITLE
脚本在gullo和webhorizo的nat机无法申请证书

### ISSUE THREAD

**Issue by gnz1123** [mack-a/v2ray-agent#666]
新系统、卸载重装均不能通过证书申请。同一个vps或其他nat机在2月前能的脚本版本安装没有问题。
系统debian10
脚本版本：v2.9.2

可提供gullo的nat小鸡做测试
![22023-05-21 113121](https://github.com/mack-a/v2ray-agent/assets/60494543/820bf300-b4af-448c-bd34-b0cc34ca1e54)

**Comment by mack-a** [comment]
现在脚本仅支持 对内对外一样端口的nat机器

**Comment by gnz1123** [comment]
> 现在脚本仅支持 对内对外一样端口的nat机器
ipv6f地址端口内外没有差异啊，而且近2月以前的八合一版本在任何nat only ipv6机上安装都是正常安装使用的，不知道脚本作了什么修改反而不兼容了。

**Comment by gnz1123** [comment]
feat(脚本): 移除80端口申请证书、添加代理端口申请证书以及renew-------是做了这个修改后就不支持nat机申请证书了吧

**Comment by idavailable** [comment]
我的gullo是connection refused 你的是timeout ，nat的小鸡还是用vasma2.7以下版本的

**Comment by mack-a** [comment]
@gnz1123 服务器可以私聊给群管理员

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.3

**Comment by gnz1123** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.3

大佬威武
