### ISSUE TITLE
脚本很棒，请问是否可以不安装Nginx来兼容已部署宝塔面板的环境？

### ISSUE THREAD

**Issue by jerrell851** [mack-a/v2ray-agent#67]
之前用v2ray已经部署好了vps环境，现在想用xray，脚本我下载来看了一下，会安装nginx并且设置一个伪装网站。

我想知道，脚本是否可以不安装nginx及设置伪装，这样应该就可以沿用原来v2ray时安装的宝塔面板啦吧？

**Comment by mack-a** [comment]
不可
