### ISSUE TITLE
Ngingx error in latest version 2.9.3

### ISSUE THREAD

**Issue by apktopsblog** [mack-a/v2ray-agent#670]
**详细描述建议的内容**

进度 11/13 : 添加伪装站点
 ---> 添加伪装站点成功
 ---> Xray关闭成功
 ---> Xray启动成功
 ---> Nginx启动失败
 ---> 请手动尝试安装nginx后，再次执行脚本

server is clean

**Comment by mack-a** [comment]
执行nginx 看看什么报错信息

**Comment by apktopsblog** [comment]
fixed

i just add `server_names_hash_bucket_size 64;` in /etc/nginx/nginx.conf   (http part)
