### ISSUE TITLE
xray routing功能失效了？

### ISSUE THREAD

**Issue by zyjisdog** [mack-a/v2ray-agent#671]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
更新geosite和geoip：vasma->17->7
屏蔽google.com：vasma->16->2->google

## 2.安装失败的log或者截图
1.查看已屏蔽域名
2.添加域名
3.屏蔽国内域名
4.删除黑名单
==-============================================================
请选择:1
[
  "geosite:google"
]

但是依然可以访问google.com

## 3.系统版本
Xray 1.8.1 + VLESS+Reality+Vision
Ubuntu 22.04.1

## 4.脚本版本
2.9.3

**Comment by mack-a** [comment]
看一下日志

**Comment by zyjisdog** [comment]
找到原因了，客户端自己把域名解析了，服务端只能得到IP地址😂谢谢！
