### ISSUE TITLE
未检测到端口开放，退出安装

### ISSUE THREAD

**Issue by cedar-c** [mack-a/v2ray-agent#673]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
不论怎么安装总是提示端口未开放，换端口，直接关防火墙都是提示未开放

## 2.安装失败的log或者截图
请选择:1

功能 1/1 : 选择核心安装 

============================================================== 
1.Xray-core 
2.v2ray-core 
============================================================== 
请选择:1
find: ‘/www/server/panel/vhost/cert/*/fullchain.pem’: No such file or directory

进度  2/13 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】 
 ---> 安装crontabs 
 ---> 安装binutils 
 ---> 安装lsb-release 

进度  3/13 : 初始化Nginx申请证书配置 

请输入要配置的域名 例: www.v2ray-agent.com ---> 
域名:*******

请输入端口[默认: 443]，可自定义端口[回车使用默认] 
端口:

 ---> 端口: 443 
touch: cannot touch ‘/etc/nginx/conf.d/checkPortOpen.conf’: No such file or directory
/usr/bin/vasma: line 990: /etc/nginx/conf.d/checkPortOpen.conf: No such file or directory
 ---> Nginx启动成功 
rm: cannot remove ‘/etc/nginx/conf.d/checkPortOpen.conf’: No such file or directory
 ---> Nginx关闭成功 
 ---> 未检测到443端口开放，退出安装 
 ---> 错误日志：，如果日志不为空可以提交issue反馈 

## 3.系统版本
CentOS 7.9.2009

## 4.脚本版本
v2.9.4

**Comment by mack-a** [comment]
吧机器反馈给 群管理员
