### ISSUE TITLE
reality+h2

### ISSUE THREAD

**Issue by yaser-k** [mack-a/v2ray-agent#675]
please add support for reality+h2. it have better performance than reality+gprc.

**Comment by yzx1208** [comment]
貌似实际测速和使用，我并未体验到有和差距。

**Comment by yaser-k** [comment]
We experience a heavy filtering. Upload speed is zero with gprc

**Comment by mack-a** [comment]
等ClashMeta支持 如果支持会考虑更改

**Comment by MrVb0** [comment]
up

**Comment by laaArmy** [comment]
> 等ClashMeta支持 如果支持会考虑更改

我去，都10月份了ClashMate还没支持吗
