### ISSUE TITLE
域名黑名单报错

### ISSUE THREAD

**Issue by yishao** [mack-a/v2ray-agent#676]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
用任意组合安装仅选择07时，添加域名黑名单会报错
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/1498568/ac5f17b0-f09b-49ed-8d05-c17cae740898)

## 3.系统版本
 Ubuntu 20.04.5 LTS 
## 4.脚本版本
2.9.4

**Comment by mack-a** [comment]
刚试了下没有复现，如果你是旧版本升级上来的建议21卸载后重新安装
