### ISSUE TITLE
希望能出一个修改订阅名称的功能

### ISSUE THREAD

**Issue by hdhdhdhd** [mack-a/v2ray-agent#679]
如题 目前的订阅都是默认名称 能否有一个修改订阅名称的功能 节点多的时候不太好分辨

**Comment by mack-a** [comment]
订阅名称就是你的节点名称的前缀，自己重新生成一个就行

**Comment by hdhdhdhd** [comment]
目前的名称是用户邮箱-协议 trojan会有别名 Vmess没有别名 主订阅跟副订阅邮箱要保持一样 就有点难区分

**Comment by mack-a** [comment]
没复现你说的这个问题 主vps是没有别名的 但是你添加的订阅会追加别名
