### ISSUE TITLE
检查ip时长建议改成1，pingIP=`ping -c 1 -W 1000 ${domain}|sed '1{s/[^(]*(//;s/).*//;q;}'`

### ISSUE THREAD

**Issue by domytest** [mack-a/v2ray-agent#68]
谢谢你的脚本，安装过程卡在 检查ipv4，等待时间过长
建议pingIP=`ping -c 1 -W 1000 ${domain}|sed '1{s/[^(]*(//;s/).*//;q;}'` 
改成 -W 1
谢谢

**Comment by mack-a** [comment]
> 谢谢你的脚本，安装过程卡在 检查ipv4，等待时间过长
> 建议pingIP=`ping -c 1 -W 1000 ${domain}|sed '1{s/[^(]*(//;s/).*//;q;}'`
> 改成 -W 1
> 谢谢

感谢反馈  写错了。

**Comment by mack-a** [comment]
> 谢谢你的脚本，安装过程卡在 检查ipv4，等待时间过长
> 建议pingIP=`ping -c 1 -W 1000 ${domain}|sed '1{s/[^(]*(//;s/).*//;q;}'`
> 改成 -W 1
> 谢谢
我刚才又看了下使用文档，-W 是超时时间。
卡在检查ipv4，可能只是单纯的ping不通，请详细反馈当时安装时遇到的问题。

**Comment by mack-a** [comment]
> 谢谢你的脚本，安装过程卡在 检查ipv4，等待时间过长
> 建议pingIP=`ping -c 1 -W 1000 ${domain}|sed '1{s/[^(]*(//;s/).*//;q;}'`
> 改成 -W 1
> 谢谢

而说根据描述我查看了不通的系统表现， MacOS的-W参数是等待时长，但是Linux的-W的是超时时长。
