### ISSUE TITLE
ssh命令获取v2ray-agent工具菜单

### ISSUE THREAD

**Issue by winicer** [mack-a/v2ray-agent#681]
能否添加ssh获取v2ray-agent工具菜单命令

root@vps:~# v2ray-agent
===============v2ray-agent八合一共存脚本==================

作者：mack-a 
当前版本：v2.9.4 
Github：https://github.com/mack-a/v2ray-agent 
描述：八合一共存脚本
核心: Xray-core[运行中] 
已安装协议: VLESS+TCP[TLS_Vision] VLESS+Reality+Vision VLESS+Reality+gRPC 

-------------------------工具管理----------------------------- 
6.账号管理 
7.更换伪装站 
8.更新证书 
9.更换CDN节点 
10.IPv6分流 
11.WARP分流 
12.流媒体工具 
13.添加新端口 
14.BT下载管理 
15.切换alpn 
16.域名黑名单 
-------------------------版本管理----------------------------- 
17.core管理 
18.更新脚本 
19.安装BBR、DD脚本 
-------------------------脚本管理----------------------------- 
20.查看日志 
21.卸载脚本 
============================================================== 
请选择:

**Comment by mack-a** [comment]
vasma这个命令
