### ISSUE TITLE
会影响现有WEB环境阿，直接一把梭把网站都搞挂了

### ISSUE THREAD

**Issue by sy3tem** [mack-a/v2ray-agent#682]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
LNMPA环境，直接更改了原有nginx启动配置信息。卸载了也没还原。手动修改配置才恢复。/
安装完不能用，所以卸载了。
## 4.脚本版本
2.9.5

**Comment by mack-a** [comment]
复杂的配置建议自己手动搞
