### ISSUE TITLE
一键搭建后的奇怪问题

### ISSUE THREAD

**Issue by snakeying** [mack-a/v2ray-agent#683]
大佬你好，首先非常感谢你无私的贡献了这个项目，对小白们特别友好。 我这几天折腾下来发现一个非常奇怪的问题，也不知道应该提供什么具体的logs给你，如果你需要具体的logs请告诉我。

是这样的，我的服务器是搬瓦工（DC6 CN2 GIA-E 机房），在使用xray一键搭建后，选择的是VLESS+Reality，搭建过程一切顺利，机子在搭建前也都是重置过的。将搭建完成后的配置直接copy到openwrt的passwall里也能正常运行。然后奇怪的问题来了，一开始一切正常，然后在不定的时间（慢则几小时快则半小时）后，google，youtube等依旧正常，chatgpt需要刷新好几次才能打开，最奇怪的是bing，网页总是显示多次重新定向，要么无法打开页面要么跳到cn网站，ios app则显示“目前区域无法提供该服务”，而passwall的设置我没有改动过，一切都是默认的，我确认了版本的一致性，还有bing.com的强制使用代理。我不知道是passwall设置出了问题还是reality出了问题。

还请你指教，谢谢

**Comment by mack-a** [comment]
大概率是客户端规则的问题，bing只要识别到是大陆访问就会重定向。建议本地用无痕模式 尝试一下

**Comment by snakeying** [comment]
嗯 我感觉也是，我再试试看，谢谢回复

**Comment by snakeying** [comment]
经过折腾及两天的测试后终于解决了问题，虽然issue已经close，还是给后面可能遇到相同问题的童鞋们提供一些经验。

首先大佬的一键搭建是没有问题的，但建议在搭建前先在VPS重装系统，我选择的是centos 7 bbr，安装完成后自带bbr，无需再安装一键脚本中的bbr，模式我查看了是bbr+FQ，没有问题。不建议选择bbr2，晚高峰期间有断流现象，油管（4K）表现也不及bbr稳定。

接下来是openwrt的问题，我建议如果你是基于lean编译的版本，不要使用ipv6，我上面遇到的所有问题在停止内置的ipv6服务后一切正常，虽然op的logs里面没有关于ipv6的error，但可能存在某些冲突（也有可能是我编译过程中出了问题）

bing的问题可以通过劫持DNS解决，通过google可以查找到13.107.21.200是bing美国服务器的ip地址，而204.79.197.200虽然显示是微软美国的ip，却是为香港地区服务的，有几率会跳转到cn.bing。在op网络--DHCP/DNS--自定义挟持域名添加 域名bing.com， ip地址为13.107.21.200，保存重启，刷新DNS缓存（WINDOWS--ipconfig /flushdns，浏览器清空缓存，op--service dnsmasq restart，手机平台--开关WIFI，AP设备--重起一次。值得注意的是，ios在打开bing app后，你需要稍等一下，等页面完全loading完成再点中间的bing chat按钮才不会出现 E010007等当前区域无法使用的提示。

希望可以帮到一些遇到差不多问题的朋友。
