### ISSUE TITLE
vless_reality_vision协议出现大量报错日志：inbound/tun[tun-in]: reality verification failed

### ISSUE THREAD

**Issue by WoChen5770** [mack-a/v2ray-agent#684]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
vless_reality_vision协议出现大量报错日志：inbound/tun[tun-in]: reality verification failed，
其他协议正常，客户端v2rayn和nekoray都有这个报错
## 3.系统版本
win11
## 4.脚本版本
最新版本

**Comment by mack-a** [comment]
检查uuid、privateKey是否正确。如果都正确建议更换域名再试一下
