### ISSUE TITLE
安装时nginx失败了

### ISSUE THREAD

**Issue by ahe-meow** [mack-a/v2ray-agent#685]
请输入端口[默认: 443]，可自定义端口[回车使用默认]
端口:

 ---> 端口: 443
 ---> Nginx启动成功
 ---> Nginx关闭成功
 ---> 未检测到443端口开放，退出安装
 ---> 错误日志：<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
<p>Additionally, a 400 Bad Request
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>，如果日志不为空可以提交issue反馈

**Comment by mack-a** [comment]
检查一下云朵是否关闭 ，如果没有用cloudflare，用了其他的CDN 检查一下CDN是否关闭

**Comment by ahe-meow** [comment]
破案了。是我傻逼了。域名那边被盗了然后ns被改了。
