### ISSUE TITLE
在德国EUSERV上安装成功，但无法上网

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#69]
>下方留下相关的描述即可

**1.描述出现的问题**
```
如题所述：
在德国EUSERV小鸡上安装成功，但无法上网。
安装成功后，伪装网站可以正常打开。ping主机延时170ms，测试下载速度为0MB/s。日志如下所示：

[Vmess] Euserv(***.***.***:443)
启动服务(2020/12/31 11:11:18)...
V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 windows/amd64)
A unified platform for anti-censorship.
2020/12/31 11:11:18 [Info] v2ray.com/core/main/jsonem: Reading config: stdin:
2020/12/31 11:11:18 [Warning] v2ray.com/core: V2Ray 4.33.0 started
2020/12/31 11:11:19 127.0.0.1:3243 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy2492] 
```
Cloudflare上的小云朵已经点亮（点灰与点亮均不可以上网）。

**2.是否直接安装失败**
- 成功

**3.直接安装失败的错误内容或者截图**
- 

**4.系统版本【例：Centos8】**
- Debian10.0-64bit-minimal 

**5.脚本版本**
- 

**6.安装类型**
- 个性化安装/全部安装

**7.安装的核心版本**
- V2ray-core【4.33.0】

**8.出现问题的协议类型**
- 均不能上网

**9.尝试重装后是否100%复现**
- 是

**10.是否仔细检查客户端与服务端的配置是否相同**
- 是

**Comment by mack-a** [comment]
> > 下方留下相关的描述即可
> 
> **1.描述出现的问题**
> 
> ```
> 如题所述：
> 在德国EUSERV小鸡上安装成功，但无法上网。
> 安装成功后，伪装网站可以正常打开。ping主机延时170ms，测试下载速度为0MB/s。日志如下所示：
> 
> [Vmess] Euserv(***.***.***:443)
> 启动服务(2020/12/31 11:11:18)...
> V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 windows/amd64)
> A unified platform for anti-censorship.
> 2020/12/31 11:11:18 [Info] v2ray.com/core/main/jsonem: Reading config: stdin:
> 2020/12/31 11:11:18 [Warning] v2ray.com/core: V2Ray 4.33.0 started
> 2020/12/31 11:11:19 127.0.0.1:3243 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy2492] 
> ```
> 
> Cloudflare上的小云朵已经点亮（点灰与点亮均不可以上网）。
> 
> **2.是否直接安装失败**
> 
> * 成功
> 
> ## **3.直接安装失败的错误内容或者截图**
> **4.系统版本【例：Centos8】**
> 
> * Debian10.0-64bit-minimal
> 
> ## **5.脚本版本**
> **6.安装类型**
> 
> * 个性化安装/全部安装
> 
> **7.安装的核心版本**
> 
> * V2ray-core【4.33.0】
> 
> **8.出现问题的协议类型**
> 
> * 均不能上网
> 
> **9.尝试重装后是否100%复现**
> 
> * 是
> 
> **10.是否仔细检查客户端与服务端的配置是否相同**
> 
> * 是

如果本地没有ipv6的环境只可以套cf来使用

**Comment by AndersonGhost** [comment]
服务器上的日志如下所示：
请选择：1
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/tcp: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core: V2Ray 4.33.0 started

客户端使用的是 Vemess ws 和 tcp 模式上网，均不能上网。套CF也不行。

**Comment by AndersonGhost** [comment]
套了CF也不行，测试下载速度也为0MB/s。

**Comment by mack-a** [comment]
> 服务器上的日志如下所示：
> 请选择：1
> 2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/tcp: accepting PROXY protocol
> 2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
> 2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
> 2020/12/31 04:02:03 [Warning] v2ray.com/core: V2Ray 4.33.0 started
> 
> 客户端使用的是 Vemess ws 和 tcp 模式上网，均不能上网。套CF也不行。

建议贴一下本地的报错信息和vps的访问日志【这个需要手动配置】

**Comment by mack-a** [comment]
> 套了CF也不行，测试下载速度也为0MB/s。

可以先看看能不能上网

**Comment by AndersonGhost** [comment]
本地日志：
配置成功
[Vmess] Euserv-8-德国-CF(104***52:443)
启动服务(2020/12/31 11:28:44)...
V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 windows/amd64)
A unified platform for anti-censorship.
2020/12/31 11:28:44 [Info] v2ray.com/core/main/jsonem: Reading config: D:\Program Files\v2ray\config.json
2020/12/31 11:28:44 [Warning] v2ray.com/core: V2Ray 4.33.0 started
2020/12/31 11:28:44 tcp:127.0.0.1:3408 accepted tcp:alive.github.com:443 [proxy] 
2020/12/31 11:28:44 tcp:127.0.0.1:3409 accepted tcp:www.google.com:443 [proxy] 
2020/12/31 11:28:44 tcp:127.0.0.1:3410 accepted tcp:clients4.google.com:443 [proxy] 
2020/12/31 11:28:44 tcp:127.0.0.1:3405 accepted tcp:clients4.google.com:443 [proxy] 
2020/12/31 11:28:44 tcp:127.0.0.1:3403 accepted tcp:alive.github.com:443 [proxy] 
2020/12/31 11:28:44 tcp:127.0.0.1:3404 accepted tcp:www.google.com:443 [proxy] 
2020/12/31 11:28:45 127.0.0.1:3412 accepted tcp:127.0.0.1:0 [api] 
2020/12/31 11:28:47 tcp:127.0.0.1:3415 accepted tcp:www.gstatic.com:80 [proxy] 
2020/12/31 11:29:03 tcp:127.0.0.1:3416 accepted tcp:lh3.googleusercontent.com:443 [proxy] 
2020/12/31 11:29:03 tcp:127.0.0.1:3417 accepted tcp:www.gstatic.com:443 [proxy] 
2020/12/31 11:29:03 tcp:127.0.0.1:3419 accepted tcp:apis.google.com:443 [proxy] 
2020/12/31 11:29:03 tcp:127.0.0.1:3421 accepted tcp:www.google.com:443 [proxy] 
2020/12/31 11:29:07 tcp:127.0.0.1:3422 accepted tcp:mtalk.google.com:443 [proxy] 

服务器日志：
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/tcp: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core/transport/internet/websocket: accepting PROXY protocol
2020/12/31 04:02:03 [Warning] v2ray.com/core: V2Ray 4.33.0 started

**Comment by AndersonGhost** [comment]
> > 套了CF也不行，测试下载速度也为0MB/s。
> 
> 可以先看看能不能上网

就是不能上网啊

**Comment by mack-a** [comment]
等会我试一下

**Comment by mack-a** [comment]
谢谢反馈 已修复

https://github.com/mack-a/v2ray-agent/releases/tag/v2.2.13

**Comment by AndersonGhost** [comment]
大佬厉害了୧(๑•̀◡•́๑)૭

**Comment by mack-a** [comment]
需更新脚本后，重新安装

**Comment by AndersonGhost** [comment]
谢谢大佬，已经成功！！

**Comment by sw586** [comment]
2021.10.2 安装VLESS+WS+TLS 问题依旧存在，安装顺利成功，但是无法上网
