### ISSUE TITLE
查看warp ipv4/ipv6分流 查看已分流域名 报错

### ISSUE THREAD

**Issue by davidtall** [mack-a/v2ray-agent#690]
1.WARP分流【第三方 IPv4】
2.WARP分流【第三方 IPv6】
3.IPv6分流
4.任意门分流
5.DNS分流
6.VMess+WS+TLS分流
7.SNI反向代理分流
请选择:1

进度  1/1 : WARP分流[第三方]
==============================================================

==============================================================
1.查看已分流域名
2.添加域名
3.设置WARP全局
4.卸载WARP分流
==============================================================
请选择:1
jq: error: syntax error, unexpected IDENT, expecting ';' or ')' (Unix shell quoting issues?) at <top-level>, line 1:
.routing.rules[]|select (.outboundTag=="wireguard-out-"IPv4""")|.domain
jq: 1 compile error

**Comment by SpeedPartner** [comment]
+1

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.9
