### ISSUE TITLE
aws云安装  TLS安装失败,请检查acme日志 错误提醒

### ISSUE THREAD

**Issue by gongyuan303** [mack-a/v2ray-agent#692]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
aws云安装  TLS安装失败,请检查acme日志 错误提醒

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/30801250/3c7dc6f6-e867-4c9c-a1d2-792a59be63d8)

## 3.系统版本
Debianwww
## 4.脚本版本
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by gongyuan303** [comment]
证书放在哪里位置 我自己上传证书得了

**Comment by gongyuan303** [comment]
提供一下证书位置吧

**Comment by gongyuan303** [comment]
卸载nginx 
问题还是没有解决

**Comment by mack-a** [comment]
dd纯净系统吧

**Comment by zhbotong** [comment]
再脚本执行到 

安装TLS证书，需要依赖80端口 时

切换另外一个窗口登陆服务器 nginx -s stop后 返回之前的命令行继续执行就行了
