### ISSUE TITLE
REALITY管理中更改端口号有误

### ISSUE THREAD

**Issue by hkfires** [mack-a/v2ray-agent#693]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
5.REALITY管理--3.更换配置--自定义端口修改后，在配置文件中的位置有误，修改到streamSettings里边了
## 2.安装失败的log或者截图
![snipaste20230607_214603](https://github.com/mack-a/v2ray-agent/assets/10558748/b82de94c-235c-4224-8a47-e1e975be0eb2)
## 3.系统版本
uBuntu20.04
## 4.脚本版本
v2.9.12

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.13
