### ISSUE TITLE
分流routing问题

### ISSUE THREAD

**Issue by zjjscwt** [mack-a/v2ray-agent#694]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
使用10-6 vmess+tls+ws 分流时  填入自定义域名 如 “baidu.com” 会在 09_routing.json中生成为“geosite:baidu.com” 导致xray 启动失败
似乎把所以填入的项 都识别为了 预定义域名

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.15
