### ISSUE TITLE
nginx1.25.1 报错，能否修复

### ISSUE THREAD

**Issue by xiechangan123** [mack-a/v2ray-agent#697]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
服务器用脚本重装了debian12，今天apt upgrade后nginx自动升级到1.25.1后，报错 nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/alone.conf:7
我看了下官网文档 https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2 启用了新的命令
![image](https://github.com/mack-a/v2ray-agent/assets/9552275/4e2642a5-a255-4ade-af8b-957ab0087997)
不影响科学上学，但是之前版本的nginx经常让grpc假死，不知道现在新命令是否有改善，大佬能否修复
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/9552275/f76b143a-9b91-4cd5-b070-202a129ffe9c)

## 3.系统版本
debian12 nginx1.25.1
## 4.脚本版本
2.19.14

**Comment by mack-a** [comment]
你试试对断流有改善吗 有改善就修复。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.17

**Comment by lexno** [comment]
ubuntu20自带的中apt安装的nginx版本为1.18.0
`
nginx version: nginx/1.18.0 (Ubuntu)
`
无法使用这种方式开启http2
脚本提示：
`
检测到安装伪装站点，是否需要重新安装[y/n]:n
 ---> Xray关闭成功 
 ---> Xray启动成功 
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本
`
nginx -t 提示：
`nginx: [emerg] unknown directive "http2" in /etc/nginx/conf.d/alone.conf:8
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by lexno** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.17

ubuntu使用apt安装的nginx版本为1.18.0
`
nginx version: nginx/1.18.0 (Ubuntu)
`
无法使用这种方式开启http2
脚本提示：
`
检测到安装伪装站点，是否需要重新安装[y/n]:n
 ---> Xray关闭成功 
 ---> Xray启动成功 
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本
`
nginx -t 提示：
`nginx: [emerg] unknown directive "http2" in /etc/nginx/conf.d/alone.conf:8
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by xiechangan123** [comment]
> 



> > https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.17
> 
> ubuntu使用apt安装的nginx版本为1.18.0 `nginx version: nginx/1.18.0 (Ubuntu)` 无法使用这种方式开启http2 脚本提示： `检测到安装伪装站点，是否需要重新安装[y/n]:n ---> Xray关闭成功 ---> Xray启动成功 ---> Nginx启动失败 ---> 请手动尝试安装nginx后，再次执行脚本` nginx -t 提示： `nginx: [emerg] unknown directive "http2" in /etc/nginx/conf.d/alone.conf:8 nginx: configuration file /etc/nginx/nginx.conf test failed`

nginx版本太老了，修改 /etc/nginx/conf.d/alone.conf 此文件，把 http2 on; 这行删掉，listen 127.0.0.1:31302 so_keepalive=on; 改为 listen 127.0.0.1:31302 http2 so_keepalive=on;
