### ISSUE TITLE
希望增加Tuic V5的支持

### ISSUE THREAD

**Issue by youngxlover** [mack-a/v2ray-agent#700]
目前来看，tuic速度表现属于优秀，尽管还无法接入xray分流。
对于对分流不敏感的节点来说，还是有用的。希望大佬单独增加一个tuic安装管理选项，并在meta的yaml中输出节点。

**Comment by gnz1123** [comment]
支持

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.17
