### ISSUE TITLE
 添加cn到warp ipv4分流后 无法测速

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#704]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
是不是需要添加规则，设定测速网址总是直连

## 3.系统版本
ubuntu
## 4.脚本版本
2.9.21

**Comment by mack-a** [comment]
speedtest吗 应该走cn了？

**Comment by fredericky123** [comment]
> speedtest吗 应该走cn了？

对，设置的www.speedtest.com
