### ISSUE TITLE
脚本生成hysteria客户端json后倒入到v2rayN里提示错误

### ISSUE THREAD

**Issue by finvv** [mack-a/v2ray-agent#706]
## 1.问题描述
最新脚本生成hysteria配置后倒入到v2rayN里提示错误
## 2.安装失败的log或者截图
![屏幕截图 2023-06-22 105436](https://github.com/mack-a/v2ray-agent/assets/103872493/13656ee2-a9c0-4e10-bd15-20ecdb9f6975)

## 3.系统版本
debian10
## 4.脚本版本
v2.9.21

**Comment by finvv** [comment]
用脚本生成Tuic，倒入也提示错误
Failed to parse the config file: unknown field `uuid`, expected one of `server`, `port`, `token`, `ip`, `certificates`, `udp_relay_mode`, `congestion_controller`, `heartbeat_interval`, `alpn`, `disable_sni`, `reduce_rtt`, `request_timeout`, `max_udp_relay_packet_size` at line 4 column 15
Cannot mix synchronous and asynchronous operation on process stream.

**Comment by finvv** [comment]
![捕获j](https://github.com/mack-a/v2ray-agent/assets/103872493/fac19b3a-e12b-4136-b446-5b1f4269c748)

**Comment by mack-a** [comment]
tuic :https://www.v2ray-agent.com/archives/1687167522196#heading-10

hysteria:https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.22
