### ISSUE TITLE
TLS安装失败，请检查acme日志

### ISSUE THREAD

**Issue by 7980963** [mack-a/v2ray-agent#71]
>下方留下相关的描述即可

**1.描述出现的问题**
```
TLS安装失败，请检查acme日志
```

**2.是否直接安装失败**
- 是/否
是
**3.直接安装失败的错误内容或者截图**
- 
进度  3/17 : 申请TLS证书
 ---> 安装TLS证书
sudo: unable to resolve host ecs-8agRa: Name or service not known
[Sun Jan  3 08:57:54 UTC 2021] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: mdl.cool: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Sun Jan  3 08:57:54 UTC 2021] Please add '--debug' or '--log' to check more details.
[Sun Jan  3 08:57:54 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/mdl.cool_ecc/fullchain.cer: No such file or directory
 ---> TLS安装失败，请检查acme日志
**4.系统版本【例：Centos8】**
- 
Debian10
**5.脚本版本**
- 
v2.2.16
**6.安装类型**
- 个性化安装/全部安装
v2.2.16
**7.安装的核心版本**
- Xray-core

**8.出现问题的协议类型**
- VLESS+TLS+WS[CDN]

**9.尝试重装后是否100%复现**
- 是/否
是
**10.是否仔细检查客户端与服务端的配置是否相同**
- 是/否

**Comment by mack-a** [comment]
ip或申请太多次证书了
too many certificates already issued for exact set of domains: mdl.cool: see https://letsencrypt.org/docs/rate-limits/",
