### ISSUE TITLE
默认安装Xray-core预览版

### ISSUE THREAD

**Issue by RunminYao** [mack-a/v2ray-agent#713]
## 1.问题描述
VLESS+TCP+TLS_Vision 协议全新安装，https访问正常，http访问返回503错误。
## 2.安装失败的log或者截图
http访问提示 malformed HTTP response "LH\xf0\x0f:lFy\xbd"
## 3.系统版本
Debian 11 x64 (bullseye)
## 4.脚本版本
v2.9.24
## 5.原因
脚本默认安装Xray-core预览版（v1.8.3），而非正式版（v1.7.5）。服务端版本高于客户端版本。

**Comment by mack-a** [comment]
新协议175不支持
