### ISSUE TITLE
脚本升级Xray-core\获取到错误版本

### ISSUE THREAD

**Issue by geekbb** [mack-a/v2ray-agent#714]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试
升级Xray-core\获取到错误版本

## 1.问题描述
16.core管理\升级Xray-core\获取到错误版本
## 2.安装失败的log或者截图
<img width="531" alt="CleanShot 2023-07-01 at 09 57 32@2x" src="https://github.com/mack-a/v2ray-agent/assets/46196358/c557165a-2913-467a-b8b8-d3071825cd83">

## 4.脚本版本
当前版本：v2.9.25

**Comment by mack-a** [comment]
正式版本就是175升级预览版本 才是183
