### ISSUE TITLE
证书无法更新

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#716]
证书过期后无法自动更新。
手动更新也不成功。

日志：
_进度  1/1 : 更新证书 
 ---> 证书检查日期:2023-07-03 23:06:25 
 ---> 证书生成日期:2023-04-03 23:17:08 
 ---> 证书生成天数:90 
 ---> 证书剩余天数:已过期 
 ---> 证书过期前最后一天自动更新，如更新失败请手动更新 
 ---> 重新生成证书 
 ---> Nginx关闭成功 
 ---> Xray关闭成功 
[Mon 03 Jul 2023 11:06:27 PM EDT] ===Starting cron===
[Mon 03 Jul 2023 11:06:27 PM EDT] Renew: '我的域名'
[Mon 03 Jul 2023 11:06:27 PM EDT] Renew to Le_API=
[Mon 03 Jul 2023 11:06:27 PM EDT] Skip invalid cert for: 我的域名
[Mon 03 Jul 2023 11:06:27 PM EDT] Skipped 我的域名_ecc
[Mon 03 Jul 2023 11:06:27 PM EDT] ===End cron===
[Mon 03 Jul 2023 11:06:27 PM EDT] Installing key to: /etc/v2ray-agent/tls/我的域名.key
[Mon 03 Jul 2023 11:06:27 PM EDT] Installing full chain to: /etc/v2ray-agent/tls/我的域名.crt_

**Comment by mack-a** [comment]
卸载后重新安装

**Comment by yoohooyoo** [comment]
刚才重新安装了，仍然报一样的错误。

**Comment by mack-a** [comment]
关键点不是重装是卸载后重装安装。把acme也删除了重新弄。如果不会用弄你就dd个纯净版的debian10或者debian11

**Comment by yoohooyoo** [comment]
成功了。
```
acme.sh --uninstall
rm -r ~/.acme.sh/ 
```
