### ISSUE TITLE
添加https证书自动续期那就更nice了

### ISSUE THREAD

**Issue by zonbar** [mack-a/v2ray-agent#72]
**详细描述建议的内容**

**Comment by mack-a** [comment]
> **详细描述建议的内容**

其实有这功能，但是好久没维护了，不知道还能不能用，改天我试一下。

**Comment by mack-a** [comment]
其实如果过期的话 可以直接重新执行脚本然后安装tls的时候直接重新生成就好

**Comment by zonbar** [comment]
可以参考trojan-go的一键脚本，里面有自动续期，其实就是添加一个自动执行的任务发自我的iPhone------------------ 原始邮件 ------------------发件人: mack-a  <notifications@github.com>发送时间: 2021年1月3日 23:52收件人: mack-a/v2ray-agent <v2ray-agent@noreply.github.com>抄送: zonbar <zonbar@163.com>, Author <author@noreply.github.com>主题: 回复：[mack-a/v2ray-agent] 添加https证书自动续期那就更nice了 (#72)
其实如果过期的话 可以直接重新执行脚本然后安装tls的时候直接重新生成就好

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mack-a/v2ray-agent/issues/72#issuecomment-753637160",
"url": "https://github.com/mack-a/v2ray-agent/issues/72#issuecomment-753637160",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zonbar** [comment]
好的 大佬发自我的iPhone------------------ 原始邮件 ------------------发件人: mack-a  <notifications@github.com>发送时间: 2021年1月3日 23:52收件人: mack-a/v2ray-agent <v2ray-agent@noreply.github.com>抄送: zonbar <zonbar@163.com>, Author <author@noreply.github.com>主题: 回复：[mack-a/v2ray-agent] 添加https证书自动续期那就更nice了 (#72)

详细描述建议的内容

其实有这功能，但是好久没维护了，不知道还能不能用，改天我试一下。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mack-a/v2ray-agent/issues/72#issuecomment-753637077",
"url": "https://github.com/mack-a/v2ray-agent/issues/72#issuecomment-753637077",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
