### ISSUE TITLE
进度  3/13 : 安装Xray  jq: error (at <stdin>:1): Cannot index string with string "prerelease"

### ISSUE THREAD

**Issue by WoChen5770** [mack-a/v2ray-agent#720]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
安装时，下载core失败

## 2.安装失败的log或者截图
进度  3/13 : 安装Xray 
jq: error (at <stdin>:1): Cannot index string with string "prerelease"

## 3.系统版本
debian11

## 4.脚本版本
最新

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.9.28
