### ISSUE TITLE
Warning! 该脚本部署的服务器存在严重的TLS指纹泄露问题，大部分用户出现相同的指纹

### ISSUE THREAD

**Issue by alreadysearched** [mack-a/v2ray-agent#722]
**详细描述建议的内容**
通过pyjarm工具可以获取某一域名的tls指纹hash信息。通过 [FOFA](https://fofa.info/) 查询相关的指纹hash值可以发现存在大量相同指纹的服务器，可以看到站点细节信息完全一致，可以判断是采用本脚本部署。

通过修改加密套件可以改变TLS指纹，但是我没有找到修改的位置，请告诉我如何个性化。

建议在今后版本更新中加入随机性。

<img width="1829" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/47503860/a7d1276a-9a9f-49e4-b817-ae45a7ea826c">

**Comment by mack-a** [comment]
和脚本无关 你手动写入配置也一样 官方不建议非专业人士 手动修改套件 建议去v2ray xray群进行咨询

**Comment by mack-a** [comment]
你还可以使用reality来避免指纹问题 

参考链接 https://www.v2ray-agent.com/archives/1680104902581
