### ISSUE TITLE
关于多节点订阅功能改进的建议

### ISSUE THREAD

**Issue by hkfires** [mack-a/v2ray-agent#724]
目前多节点订阅功能，初始需要在主节点这里加入各个分支节点的订阅，但是后续使用中，如果分支节点的订阅更新后，主节点这边更新订阅并不会拉取分支节点的最新订阅，而只能先删除外部订阅，然后再一个个添加，建议能够在主节点每次订阅更新时，同步分支节点的最新订阅。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.2
