### ISSUE TITLE
安装v2ray-core 无法下载v2ray-linux-64.zip

### ISSUE THREAD

**Issue by bebee4java** [mack-a/v2ray-agent#725]
## 1.问题描述
选择v2ray-core核心安装时发生下面错误：
进度  6/13 : 安装V2Ray
 ---> v2ray-core版本:
unzip:  cannot find or open /etc/v2ray-agent/v2ray/v2ray-linux-64.zip, /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.zip or /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.ZIP.

## 2.安装失败的log或者截图
<img width="1595" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/20768390/fa1e745b-6d04-4ac9-a70f-574387faa79c">

## 3.系统版本
Ubuntu 20.04 LTS

## 4.脚本版本
v2.9.28

**Comment by mack-a** [comment]
v2ray-core已经好久没维护了 建议使用xray-core
