### ISSUE TITLE
谷歌商店无法下载问题

### ISSUE THREAD

**Issue by chancat87** [mack-a/v2ray-agent#726]
**详细描述建议的内容**
群里经常看到有人问。谷歌商店能访问，无法下载。由于geo文件的问题，导致一些人谷歌商店无法下载更新应用。
群主可以自动添加规则省的小白到处问😂

**Comment by mack-a** [comment]
本地客户端需要设置下规则googleapis.cn

**Comment by chancat87** [comment]
> 本地客户端需要设置下规则googleapis.cn。和服务端关系不是特别大

这确实，服务端屏蔽cn之后，本地肯定没法浏览googleapis。
