### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by poptruck** [mack-a/v2ray-agent#728]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
安装最后一步，关闭v2ray之后，无法再次启动。安装V2RAY时找不到那个zip包。
## 2.安装失败的log或者截图

进度  6/13 : 安装V2Ray
 ---> v2ray-core版本:
unzip:  cannot find or open /etc/v2ray-agent/v2ray/v2ray-linux-64.zip, /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.zip or /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.ZIP.

进度  7/13 : 配置V2Ray开机自启
 ---> 配置V2Ray开机自启成功

进度 8/13 : 添加cloudflare自选CNAME

==============================================================
# 注意事项

教程地址:
https://www.v2ray-agent.com/archives/cloudflarezi-xuan-ip

如对Cloudflare优化不了解，请不要使用

 1.CNAME www.digitalocean.com
 2.CNAME who.int
 3.CNAME blog.hostmonit.com
----------------------------
请选择[回车不使用]:
unzip:  cannot find or open /etc/v2ray-agent/v2ray/v2ray-linux-64.zip, /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.zip or /etc/v2ray-agent/v2ray/v2ray-linux-64.zip.ZIP.

 ---> 不使用

进度 9/13 : 初始化V2Ray配置

是否自定义UUID ？[y/n]:
/usr/bin/vasma: line 2997: /etc/v2ray-agent/v2ray/v2ctl: No such file or directory

 ---> uuid读取错误，重新生成
/usr/bin/vasma: line 3003: /etc/v2ray-agent/v2ray/v2ctl: No such file or directory

进度 10/13 : 添加定时维护证书

 ---> 添加定时维护证书成功

进度 11/13 : 添加伪装站点

检测到安装伪装站点，是否需要重新安装[y/n]:n
 ---> V2Ray关闭成功
V2Ray启动失败
请手动执行【/etc/v2ray-agent/v2ray/v2ray -confdir /etc/v2ray-agent/v2ray/conf】，查看错误日志

## 3.系统版本
debian10
## 4.脚本版本
最新版

有卸载重试过，重装系统过，都是不可以

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.1

**Comment by poptruck** [comment]
实际上我装xray也是类似的问题，也是启动不起来。不确定。我是用racknerd vps。
之前的脚本好像没问题，只是昨天想修改一些配置，然后就不行了。

**Comment by mack-a** [comment]
> 

OK 如果复现了xray的 记得贴一下

**Comment by verson1** [comment]
我也是启动失败：
![image](https://github.com/mack-a/v2ray-agent/assets/24424328/7c9d9e35-0e8a-41b7-bc8e-69c112cd37de)
