### ISSUE TITLE
重启vps后伪装站失效，是否是Nginx的问题？

### ISSUE THREAD

**Issue by Bruceau** [mack-a/v2ray-agent#73]
centos7

**Comment by mack-a** [comment]
具体脚本版本是哪一个，以前得脚本版本安装了trojan-go重启后确实会。

**Comment by Bruceau** [comment]
当前版本：v2.2.16

**Comment by Bruceau** [comment]
热乎乎的版本额

**Comment by yanga9** [comment]
centos7，centos8我都试了，都有这个BUG，重装了N次都这样，搞得证书拉黑都无法申请了。

**Comment by yanga9** [comment]
但访问伪装目录有返回

**Comment by mack-a** [comment]
> centos7，centos8我都试了，都有这个BUG，重装了N次都这样，搞得证书拉黑都无法申请了。

![image](https://user-images.githubusercontent.com/57424792/103520879-d6cf7f00-4eb2-11eb-865a-8403bb33ef8a.png)
脚本加了注意事项，最好不要卸载脚本后再重装。

**Comment by mack-a** [comment]
> 当前版本：v2.2.16

尝试手动启动下nginx，试试可以不

**Comment by Bruceau** [comment]
那很有可能是trojan-go  试试不装trojan-go

> > 当前版本：v2.2.16
> 
> 尝试手动启动下nginx，试试可以不

**Comment by Bruceau** [comment]
> 那很有可能是trojan-go 试试不装trojan-go
> 
> > > 当前版本：v2.2.16
> > 
> > 
> > 尝试手动启动下nginx，试试可以不

好的，不要装trojan-go试试

**Comment by mack-a** [comment]
> > 那很有可能是trojan-go 试试不装trojan-go
> > > > 当前版本：v2.2.16
> > > 
> > > 
> > > 尝试手动启动下nginx，试试可以不
> 
> 好的，不要装trojan-go试试

不安装trojan-go也不应该出现你那个情况，我自己弄个centos7试试

**Comment by mack-a** [comment]
> centos7

请问安装的内核是啥

**Comment by yanga9** [comment]
VMess+WS+TLS和VLESS+TCP+TLS都这样，重新启动下nginx有时候可以，但再重启VPS还是伪装站失效

**Comment by yanga9** [comment]
Xray

**Comment by mack-a** [comment]
> VMess+WS+TLS和VLESS+TCP+TLS都这样，重新启动下nginx有时候可以，但再重启VPS还是伪装站失效

手动重启下nginx呐 执行nginx即可

**Comment by Bruceau** [comment]
> > centos7
> 
> 请问安装的内核是啥

xray

**Comment by mack-a** [comment]
我复现了  等会我看看

**Comment by mack-a** [comment]
感谢反馈

**Comment by Bruceau** [comment]
作者，还有一个问题，甲骨文的centos 和 ubuntu 死活装不上

当前域名的IP为 [168.138.210.164]，是否正确[y/n]？y

 ---> IP确认完成

检查Nginx是否正常访问
 ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确--->

**Comment by Bruceau** [comment]
我确定解析没错的 没有开启小云朵

**Comment by mack-a** [comment]
甲骨云有一个自己的防火墙，在面板里面

**Comment by Bruceau** [comment]
> 甲骨云有一个自己的防火墙，在面板里面

好的，谢谢作者

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.2.17

已修改，需重新安装
