### ISSUE TITLE
查看订阅时报错

### ISSUE THREAD

**Issue by w87777w** [mack-a/v2ray-agent#731]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
查看订阅时报错
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/49546405/bc50cc0a-bbef-4634-991a-b46b88e05969)
## 3.系统版本
Centos 7
## 4.脚本版本
v2.10.3

**Comment by mack-a** [comment]
卸载重新安装
