### ISSUE TITLE
纯IPV6 VPS无法通过域名解析检查

### ISSUE THREAD

**Issue by lengge86** [mack-a/v2ray-agent#732]
## 1.问题描述

纯IPV6 VPS无法通过域名解析检查，已使用DNS64。Cloudflare云朵未点亮。Xray-core + grpc/ws 都是如此。

## 2.安装失败的log或者截图

 ---> 端口: 443 
 ---> 域名解析IP与当前服务器IP不一致
 
 ---> 请检查域名解析是否生效以及正确 
 ---> 当前VPS IP： 
 ---> DNS解析 IP：;; UDP setup with 1.1.1.1#53(1.1.1.1) for 域名 failed: network unreachable.
;; UDP setup with 1.1.1.1#53(1.1.1.1) for 域名 failed: network unreachable.
;; UDP setup with 1.1.1.1#53(1.1.1.1) for 域名 failed: network unreachable. 

## 3.系统版本

Debian 12

## 4.脚本版本

2.10.3

**Comment by mack-a** [comment]
dd个系统试一下
