### ISSUE TITLE
443端口未开放，退出安装(nginx没有使用docker)

### ISSUE THREAD

**Issue by chenxuyuanchen** [mack-a/v2ray-agent#733]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
正常安装，我防火墙也没开，说我没开放443端口
## 2.安装失败的log或者截图
![图片](https://github.com/mack-a/v2ray-agent/assets/93701704/80391335-3709-4439-892a-9bc34996edd0)
## 3.系统版本
CentOS Linux release 7.9.2009 (Core)
## 4.脚本版本
当前版本：v2.10.3

**Comment by mack-a** [comment]
dd个纯净版本的debian11，再试一次
