### ISSUE TITLE
脚本中TUIC协议添加的iptables规则不正确

### ISSUE THREAD

**Issue by azraeljack** [mack-a/v2ray-agent#734]
## 1.问题描述

使用vasma开启tuic协议后，iptables会自动添加以下规则：

```
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:{port} /* allow {port}(mack-a) */
```

但是因为tuic实际为udp协议，所以其实应该添加的是一条udp规则而不是tcp，手动添加以下规则后tuic可以正常联通：

```
iptables -A INPUT -p udp --dport {port} -j ACCEPT
```

## 2.安装失败的log或者截图

暂无

## 3.系统版本

`ubuntu 22.04`

## 4.脚本版本
<img width="626" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/4611229/0a90a4af-37ca-4489-854a-62906a140269">

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.4
