### ISSUE TITLE
vasma 宝塔共存

### ISSUE THREAD

**Issue by hadis898** [mack-a/v2ray-agent#736]
**详细描述建议的内容**
vasma 可以宝塔共存 ，已经有nginx了，又要安装

**Comment by mack-a** [comment]
先安装宝塔 nginx和ssl再安装脚本

**Comment by wcmiracle** [comment]
> 先安装宝塔 nginx和ssl再安装脚本

为了防止意外发生，请问应该先备份宝塔的哪些配置，再继续安装vasma?
