### ISSUE TITLE
纯ipv6环境安装reality协议异常

### ISSUE THREAD

**Issue by qihang518887** [mack-a/v2ray-agent#737]
## 1.问题描述
纯ipv6环境安装reality时，如果开启warp会导致配置文件中的ip是warp的ip，关闭warp安装，安装完成后无法生成配置文件（卡死）
## 2.安装失败的log或者截图
无
## 3.系统版本
debian12
## 4.脚本版本
2.10.7

**Comment by mack-a** [comment]
warp不要全局
