### ISSUE TITLE
服务器出现大量目标8444端口的连接

### ISSUE THREAD

**Issue by CakeSystem** [mack-a/v2ray-agent#738]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
![image](https://github.com/mack-a/v2ray-agent/assets/130638116/b49e9117-6043-432d-8ee5-25e94cb51fa5)
服务器出现大量目标8444端口的连接，并且使用iptables封禁出口到8444端口的所有流量后依旧可以使用，时不时会占用大量带宽
查不到域名，封禁掉一批ip后，一会儿优惠出现新的一批。。。请问如何才能封禁掉这个

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/130638116/32d6bdd0-7306-4612-a7a0-ef14a42e7111)

## 3.系统版本
ubuntu18和ubuntu20

## 4.脚本版本
2.7.13和2.10.2

**Comment by CakeSystem** [comment]
加群进去一会儿就被禁，申请解封也没有回应，。。

**Comment by mack-a** [comment]
> 出现该问题的服务器都安装了一键脚本中的推荐bbr+fq

bbr+fq脚本采用的是第三方的，脚本有明确说明，建议联系那个作者。

**Comment by mack-a** [comment]
> 加群进去一会儿就被禁，申请解封也没有回应，。。

因为你是广告，群里不欢迎广告

**Comment by mack-a** [comment]
> 加群进去一会儿就被禁，申请解封也没有回应，。。

违反群规，不允许有广告

**Comment by CakeSystem** [comment]
没发过广告呀，刚进去就被封了，两次。。。

**Comment by CakeSystem** [comment]
求解封。。进群问这个问题怎么解决

**Comment by CakeSystem** [comment]
6



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月5日(周六) 凌晨0:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mack-a/v2ray-agent] 服务器出现大量目标8444端口的连接 (Issue #738)




  
加群进去一会儿就被禁，申请解封也没有回应，。。
  
因为你是广告，群里不欢迎广告

**Comment by mack-a** [comment]
> 6
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月5日(周六) 凌晨0:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [mack-a/v2ray-agent] 服务器出现大量目标8444端口的连接 (Issue #738) 加群进去一会儿就被禁，申请解封也没有回应，。。 因为你是广告，群里不欢迎广告 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你的bio就是广告

<img width="500" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/57424792/ff686146-b85c-4919-8603-0fe37bfd2996">
