### ISSUE TITLE
Errors with connections

### ISSUE THREAD

**Issue by bubulgum** [mack-a/v2ray-agent#740]
**详细描述建议的内容**
Hi, thx for script.
I have issue with Telecom (unicom ok) on vray2ng Android (core 1.8.3 server/client) "fail to detect internet connection: io: read/write on closed pipe". Win version can connect but also not so well.
Ports are availble in pingpe.
What can adjust to better work with telecom?

rejected  proxy/trojan: not trojan protocol

**Comment by mack-a** [comment]
你可以尝试tuic或者hy，如果这两个使用体验还是很差，可以尝试使用中转。建议电信使用gia，或者回程使用软银或者AS9929。
