### ISSUE TITLE
安装完无域名的Reality后发现没有ipv6

### ISSUE THREAD

**Issue by do02fw** [mack-a/v2ray-agent#741]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
安装完无域名的Reality后发现没有ipv6，访问ipv6检测检测不到，但是服务器是有ipv6的，是默认没开启吗还是不支持ipv6
## 3.系统版本
Debian12.1
## 4.脚本版本
最新版

**Comment by mack-a** [comment]
纯reality 脚本会先拿IPv4 拿到之后就不会去拿IPv6

**Comment by do02fw** [comment]
> 纯reality 脚本会先拿IPv4 拿到之后就不会去拿IPv6

我开启ipv6分流的全局后有了
