### ISSUE TITLE
动画疯在vps屏蔽国内域名的情况下会无限Loading

### ISSUE THREAD

**Issue by XDorz** [mack-a/v2ray-agent#742]
脚本版本：v2.10.2 
Xray 1.8.3
v2rayN 6.21
安装方式 reality
注：客户端和服务端中的geo file皆已进行过更新(非手动下载下来替换更新，都是使用软件/脚本自带的更新功能进行更新)
测试动画疯账号没有经过手机认证，年龄认证，没有开会员
v2rayN路由规则使用【绕过大陆】

描述：
在commit中没有见到相关描述斗胆在这里提出建议~
不知道将该建议提在这里是否合适，如果更适合提在geo file那边还请见谅。
当使用脚本 【15.添加域名黑名单】 中的【3.屏蔽国内域名】后
打开动画疯网页版（ani.gamer.com.tw）选择一个片子观看时会出现无限Loading加载，经过查看console发现是因为【Uncaught ReferenceError: google is not defined】 这个error导致的，而这个error的成因是因为网页载入时 【GET https://imasdk.googleapis.com/js/sdkloader/ima3.js net::ERR_CONNECTION_CLOSED】这个js脚本无法获取导致的
我换了不同浏览器，修改v2rayN中的路由规则来取消广告的block，关闭与广告相关的浏览器拓展程序后仍不见成效
最后使用脚本的【4.删除黑名单 】和v2rayN的路由设置中设置proxy【domain:imasdk.googleapis.com】后才能正常看到广告和动画
不知道大佬能否为【3.屏蔽国内域名】中设置一个排除【domain:imasdk.googleapis.com】的选项为动画疯用户行方便，客户端的block可以通过设置路由为全局或者取消block【geosite:category-ads-all】这条路由规则或是显示添加proxy【domain:imasdk.googleapis.com】来正常观看，但是linux中没有gui操作，只能用命令行，普通用户可能连哪里设置排除【domain:imasdk.googleapis.com】都不知道。

第一次提issue，不规范请见谅

**Comment by mack-a** [comment]
有空我改一下
