### ISSUE TITLE
重装reality后，warp第三方分流ipv6不更改端口的话无法启动分流

### ISSUE THREAD

**Issue by Miauson** [mack-a/v2ray-agent#744]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述 
vps为rn dc02机器，x64
原vps只搭建了reality，用脚本中带的第三方warp-ipv6分流Netflix和openai，使用正常。
想换个warp-ip，删除脚本后仍然选择了原来的端口和sni网址安装出现以下截图问题。重装脚本，重启vps几次都不行，
后来重启换了个reality端口就正常了。
ps，我不爱换端口。。。

## 2.安装失败的log或者截图![Screenshot_2023-08-08-20-21-47-339_com.server.auditor.ssh.client.jpg](https://github.com/mack-a/v2ray-agent/assets/87218810/b97a27b8-1034-493c-8c27-b81a53ec15b0)

![Screenshot_2023-08-08-20-03-20-486_com.server.auditor.ssh.client.jpg](https://github.com/mack-a/v2ray-agent/assets/87218810/45f76ee4-c395-4698-bdd9-5190ac6adad4)

## 3.系统版本 
Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-24-amd64

**Comment by Miauson** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/87218810/014bf827-99ea-4074-b05d-a9cb87575985)
新vps又出现了这种情况

**Comment by mack-a** [comment]
无法复现
