### ISSUE TITLE
计划加入 juicity 的支持吗

### ISSUE THREAD

**Issue by yqlbu** [mack-a/v2ray-agent#745]
**详细描述建议的内容**

项目地址： https://github.com/juicity/juicity

母项目： https://github.com/daeuniverse/dae

**Comment by mack-a** [comment]
等其他客户端完善一下

**Comment by Abdipour** [comment]
We want this too... Please add support for juicity.

**Comment by flyingbug2** [comment]
Tuic的项目已经彻底停止，可以安排 Juicity 了。
