### ISSUE TITLE
无法获取VPS IP

### ISSUE THREAD

**Issue by latifrons** [mack-a/v2ray-agent#746]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述

检查IP时VPS IP为空，无法通过检查

## 2.安装失败的log或者截图

![image](https://github.com/mack-a/v2ray-agent/assets/1080266/b2f1a603-4cba-4cc6-b832-cf4676329729)

## 3.系统版本

Ubuntu 22.04

## 4.脚本版本

v2.10.10 (Bug Since v2.10.8)

**Comment by davidtall** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/9320941/4e9db1fc-7f03-48bc-8244-79fb386302a9)
遇到同样的问题

**Comment by davidtall** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/9320941/261ca68b-0efd-48cc-a047-5568c70285a5)
原因是这里的 if [[ "${currentRealityServerNames}" == "${currentHost}" ]] 都为空了，加个非空判断就好了。选择2自定义安装，xray ,再选择7时出现的

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.11
