### ISSUE TITLE
纯IPv6 VPS核心下载失败

### ISSUE THREAD

**Issue by ReyReyy** [mack-a/v2ray-agent#747]
## 1.问题描述
纯IPv6 VPS核心下载失败
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/46741598/526ad6d8-5bde-457b-9733-8d4ddf2a3066)
![image](https://github.com/mack-a/v2ray-agent/assets/46741598/488dce82-48b4-47aa-803b-9e71a78b7e7d)
![image](https://github.com/mack-a/v2ray-agent/assets/46741598/ea3c5e91-d1ed-46e5-a7d2-26cefc30a50f)

## 3.系统版本
Debian 11
IPv6 vps 但是可以访问IPv4资源
## 4.脚本版本
v2.10.11

**Comment by mack-a** [comment]
换个nat64再试一下
