### ISSUE TITLE
tuic协议, warp分流不生效

### ISSUE THREAD

**Issue by Jadelog** [mack-a/v2ray-agent#748]
## 1.问题描述
使用tuic协议, warp分流不生效. 
其他协议可以生效.
测试网站为chat.openai.com
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/61723005/edbe8dd0-e49b-450f-9bd4-dc4c570dc598)

![image](https://github.com/mack-a/v2ray-agent/assets/61723005/cdfd6113-8b2e-4c4d-ad84-9926be46d6a4)

## 3.系统版本
Ubuntu22.04
## 4.脚本版本
2.10.11

**Comment by mack-a** [comment]
tuic不支持
