### ISSUE TITLE
oracle云提示“检查Nginx是否正常访问   ---> 无法正常访问服务器，请检测域名是否正确、域名的DNS解析以及防火墙设置是否正确---> ”

### ISSUE THREAD

**Issue by wolfing88** [mack-a/v2ray-agent#75]
**详细描述建议的内容**
无论是centos还是Ubuntu都提示这个，请问一下改怎么设置呢，ping域名已经是当前vps的IP了

**Comment by mack-a** [comment]
甲骨云面板有一个额外的防火墙，需要自己放行

**Comment by wolfing88** [comment]
请问您指的是安全列表里面的出站和入站规则吗，已经设置过了，并且按照网上的提示在vps设置防火墙了，可是还是提示那个问题，昨天试了一下午了还是搞不好，麻烦大佬帮忙看看，谢谢
![image](https://user-images.githubusercontent.com/22385050/103851129-f7325000-50e3-11eb-92e4-f550bd79b92e.png)
`#开放所有端口
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -F
#Oracle自带的Ubuntu镜像默认设置了Iptable规则，关闭它
apt-get purge netfilter-persistent
reboot`

**Comment by mack-a** [comment]
> 请问您指的是安全列表里面的出站和入站规则吗，已经设置过了，并且按照网上的提示在vps设置防火墙了，可是还是提示那个问题，昨天试了一下午了还是搞不好，麻烦大佬帮忙看看，谢谢
> ![image](https://user-images.githubusercontent.com/22385050/103851129-f7325000-50e3-11eb-92e4-f550bd79b92e.png)
> `#开放所有端口 sudo iptables -P INPUT ACCEPT sudo iptables -P FORWARD ACCEPT sudo iptables -P OUTPUT ACCEPT sudo iptables -F #Oracle自带的Ubuntu镜像默认设置了Iptable规则，关闭它 apt-get purge netfilter-persistent reboot`

自己Google一下，我手里没有甲骨文的云服务器，但是之前好几个人用脚本的时候 遇到过相同的问题，也是自己手动搞的，但是我不知道具体是怎么设置的，可以搜一下以前的issue 问一下他们

**Comment by blueveryday** [comment]
Oracle Cloud甲骨文免费VPS 防火墙设置

Oracle Cloud甲骨文免费VPS在创建vps后如果需要提供服务，需要对防火墙进行设置。

1、在子网中的安全列表中对入口规则和出口规则进行更改，对0.0.0.0/0的所有协议进行放行。
2、做完第一步是对网络的防火墙打开了，但是vps搭建的服务还是不能连接，需要对vpc机器的防火墙进行设置：

01 #开放所有端口
02 sudo iptables -P INPUT ACCEPT
03 sudo iptables -P FORWARD ACCEPT
04 sudo iptables -P OUTPUT ACCEPT
05 sudo iptables -F
06 #Oracle自带的Ubuntu镜像默认设置了Iptable规则，关闭它
07 apt-get purge netfilter-persistent
08 reboot
09 #强制删除
10 rm -rf /etc/iptables && reboot
