### ISSUE TITLE
TLS安装失败

### ISSUE THREAD

**Issue by minwoo0210** [mack-a/v2ray-agent#751]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
TLS安装失败，用了两个韩国供应商的vps都是同样报错
## 2.安装失败的log或者截图
============================================================== 
作者：mack-a 
当前版本：v2.10.12 
Github：https://github.com/mack-a/v2ray-agent 
描述：八合一共存脚本
=========================== 推广区============================ 
                                               
推广请联系TG：@mackaff
 
VPS选购攻略：https://www.v2ray-agent.com/archives/1679975663984 
年付10美金低价VPS AS4837：https://www.v2ray-agent.com/archives/racknerdtao-can-zheng-li-nian-fu-10mei-yuan 
============================================================== 
1.安装 
2.任意组合安装 
4.Hysteria管理 
5.REALITY管理 
6.Tuic管理 
-------------------------工具管理----------------------------- 
7.账号管理 
8.更换伪装站 
9.更新证书 
10.更换CDN节点 
11.分流工具 
12.添加新端口 
13.BT下载管理 
14.切换alpn 
15.域名黑名单 
-------------------------版本管理----------------------------- 
16.core管理 
17.更新脚本 
18.安装BBR、DD脚本 
-------------------------脚本管理----------------------------- 
19.查看日志 
20.卸载脚本 
============================================================== 
请选择:1

功能 1/1 : 选择核心安装 

============================================================== 
1.Xray-core 
2.v2ray-core 
============================================================== 
请选择:1

进度  2/13 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】 
 ---> 安装binutils 
 ---> 安装ping6 
 ---> 安装lsb-release 
 ---> 安装semanage 

进度  3/13 : 初始化Nginx申请证书配置 

请输入要配置的域名 例: www.v2ray-agent.com ---> 
域名:www.choi-min-woo.com

请输入端口[默认: 443]，可自定义端口[回车使用默认] 
端口:

 ---> 端口: 443 
 ---> 域名IP校验通过 
 ---> Nginx启动成功 
 ---> Nginx关闭成功 
 ---> 检测到443端口已开放 

 ---> 检查域名ip中 
 ---> 检查当前域名IP正确 
 ---> Xray关闭成功 

进度  4/13 : 申请TLS证书
 
 ---> 安装TLS证书，需要依赖80端口 

============================================================== 
1.letsencrypt[默认] 
2.zerossl 
3.buypass[不支持DNS申请] 
============================================================== 
请选择[回车]使用默认:

 ---> 生成证书中 
[Wed Aug 16 09:08:02 CST 2023] Getting webroot for domain='www.choi-min-woo.com'
[Wed Aug 16 09:08:02 CST 2023] Verifying: www.choi-min-woo.com
[Wed Aug 16 09:08:02 CST 2023] Standalone mode server
[Wed Aug 16 09:08:04 CST 2023] Pending, The CA is processing your order, please just wait. (1/30)
[Wed Aug 16 09:08:06 CST 2023] Pending, The CA is processing your order, please just wait. (2/30)
[Wed Aug 16 09:08:09 CST 2023] Pending, The CA is processing your order, please just wait. (3/30)
[Wed Aug 16 09:08:11 CST 2023] Pending, The CA is processing your order, please just wait. (4/30)
[Wed Aug 16 09:08:14 CST 2023] www.choi-min-woo.com:Verify error:121.0.122.73: Fetching http://www.choi-min-woo.com/.well-known/acme-challenge/o7jqClkDHZcIUg4wUJvcBZQB1BiyKNgGV3YULw_TMyU: Timeout during connect (likely firewall problem)
[Wed Aug 16 09:08:14 CST 2023] Please add '--debug' or '--log' to check more details.
[Wed Aug 16 09:08:14 CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

进度  4/13 : 申请TLS证书
 
 ---> 安装TLS证书，需要依赖80端口 

 ---> 生成证书中 
[Wed Aug 16 09:08:17 CST 2023] Getting webroot for domain='www.choi-min-woo.com'
[Wed Aug 16 09:08:17 CST 2023] Verifying: www.choi-min-woo.com
[Wed Aug 16 09:08:17 CST 2023] Standalone mode server
[Wed Aug 16 09:08:19 CST 2023] Pending, The CA is processing your order, please just wait. (1/30)
[Wed Aug 16 09:08:22 CST 2023] Pending, The CA is processing your order, please just wait. (2/30)
[Wed Aug 16 09:08:24 CST 2023] Pending, The CA is processing your order, please just wait. (3/30)
[Wed Aug 16 09:08:27 CST 2023] Pending, The CA is processing your order, please just wait. (4/30)
[Wed Aug 16 09:08:30 CST 2023] www.choi-min-woo.com:Verify error:121.0.122.73: Fetching http://www.choi-min-woo.com/.well-known/acme-challenge/zh8j_o7ZMFzBWs6dQxOtnPqQaqKS8hJrA1-rhan0Iso: Timeout during connect (likely firewall problem)
[Wed Aug 16 09:08:30 CST 2023] Please add '--debug' or '--log' to check more details.
[Wed Aug 16 09:08:30 CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
 ---> TLS安装失败，请检查acme日志 

## 3.系统版本
Debian 10
## 4.脚本版本
当前版本：v2.10.12

**Comment by mack-a** [comment]
检查一下防火墙，如果是甲骨文他有单独的防火墙 需要打开一下。
