### ISSUE TITLE
希望加入 AWS 的系统支持

### ISSUE THREAD

**Issue by hujiajun2022** [mack-a/v2ray-agent#752]
**详细描述建议的内容**
\S
 on an \m (\l)
Linux version 6.1.38-59.109.amzn2023.x86_64 (mockbuild@ip-10-0-38-43) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.39-6.amzn2023.0.7) #1 SMP PREEMPT_DYNAMIC Tue Jul 11 23:51:29 UTC 2023

希望加入 AWS 的系统支持

**Comment by tmnt2009** [comment]
我的AWS用了脚本后，走的流量反而要钱。。。

**Comment by AmaraFlowers** [comment]
本来就要钱呀，至少套了一个 IP
