### ISSUE TITLE
小白咨询443端口被封了，怎样续证书

### ISSUE THREAD

**Issue by pbclaodentm** [mack-a/v2ray-agent#753]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
443端口被封了，测了下，域名正常，80端口也正常，就是443端口国内被封，国外在正常，自动续证书是不是用的443，既然国内被封了，为啥vps在国外，国外没封，也续不了了，续证书跟443端口到底有无关系呢，不太明白，我试了手动更新的命令，也更新不了了，协议呢，除了要用证书的用不了，其他都没事

**Comment by mack-a** [comment]
不是用的443，国内封了也不影响申请证书

**Comment by mack-a** [comment]
如果脚本从低版本升级到高版本，建议卸载后重新安装

**Comment by pbclaodentm** [comment]
谢谢提醒，我已经解决，因为脚本生成的证书我看了，是5月份的时候生成的，那时也是因为版本不兼容删除了重新运行的脚本，所以这次就不想重装了，重装后的订阅地址、协议地址会变，于是我做了如下操作，一是acme.sh --uninstall
rm -r ~/.acme.sh/    只进行了证书及其证书程序的删除，第二步就是选择1重装，但都沿用，到生成完证书后就退出重启，然后再vasm出菜单，9进去看证书正常，如有其他同学有此问题，可参考
