### ISSUE TITLE
clashmeta订阅无法使用？

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#754]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
本地网络是电信，VPS是RackNerd的洛杉矶机房，客户端是 clash verge 。 使用clashMeta订阅链接导入后，发现没有任何可以用节点信息，更新会报错。本地网络是可以正常访问vps 22端口， telnet 代理端口也是可以通的
## 2.安装失败的log或者截图

![1](https://github.com/mack-a/v2ray-agent/assets/43665641/379c400e-ed06-4a36-a0b3-154d8d9b4ac3)

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v2.10.12

**Comment by bettswang** [comment]
换了联通和移动的网络，好像就可以。为啥电信不行，端口都能通，更新不到节点的信息下来

**Comment by mack-a** [comment]
rn不适合电信，比较慢。

**Comment by bettswang** [comment]
你好，这两天观察到，联通的as4387好像也用不了。不知道什么原因，还是服务器配置的问题。
线路检查如下，见过AS4387
```
 1  192.168.187.176 [*]  1.352 ms  1.269 ms  1.647 ms
 2  * * *
 3  * * *
 4  * * *
 5  218.104.128.161 [AS4837]  18.391 ms  18.520 ms  18.639 ms
 6  218.107.221.233 [AS4837]  36.377 ms  35.244 ms  35.188 ms
 7  * * *
 8  219.158.9.242 [AS4837]  54.304 ms  54.284 ms  54.491 ms
 9  219.158.9.213 [AS4837]  58.834 ms  58.806 ms  59.493 ms
10  219.158.100.22 [AS4837]  206.015 ms  205.990 ms  206.014 ms
11  219.158.33.78 [AS4837]  217.807 ms  218.238 ms  218.191 ms
12  * * *
13  182.54.129.91 [AS64050]  188.237 ms  184.044 ms  185.023 ms
14  208.64.231.5 [AS35916]  181.140 ms  177.830 ms  177.743 ms
```

clash verge客户端更新配置会报错
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/58bf3f52-8a36-4e98-96ec-6b1d718a5446)
