### ISSUE TITLE
tuic安装后，在客户端订阅中不显示？

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#755]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
tuic安装后，在Windows下的clash verge客户端中，拉取订阅后，却没有tuic的节点？
## 2.安装失败的log或者截图
<img width="953" alt="3" src="https://github.com/mack-a/v2ray-agent/assets/43665641/78445c9b-9ce7-4a49-9387-4abdacd4f150">

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v2.10.12

**Comment by bettswang** [comment]
![4](https://github.com/mack-a/v2ray-agent/assets/43665641/fb72e195-97ce-4447-b90f-23b14b230b47)

**Comment by mack-a** [comment]
重新查看下订阅 应该就有了

**Comment by bettswang** [comment]
账号里有信息，但是这个没法导入到calsh verge客户端。订阅没有呀，订阅只有两种，default和clashmeta。

**Comment by mack-a** [comment]
> 账号里有信息，但是这个没法导入到calsh verge客户端。订阅没有呀，订阅只有两种，default和clashmeta。

后安装的tuic，需要重新查看下订阅。脚本才会重新生成

**Comment by mack-a** [comment]
clashverga支持clashmeta内核，切换下

**Comment by bettswang** [comment]
内核时calsh meta的，重新生成了，也没看到呀

**Comment by bettswang** [comment]
不好意思，看到了哈，谢谢
