### ISSUE TITLE
开放了所有端口，然后安装提示端口未开放

### ISSUE THREAD

**Issue by hiseller** [mack-a/v2ray-agent#757]
请输入端口[默认: 443]，可自定义端口[回车使用默认]
端口:

 ---> 端口: 443
 ---> 域名IP校验通过
 ---> Nginx启动成功
 ---> Nginx关闭成功
 ---> 未检测到443端口开放，退出安装
 ---> 错误日志：，如果日志不为空可以提交issue反馈

**Comment by mack-a** [comment]
是否有网页版的防火墙 检查一下

**Comment by nicepass** [comment]
检查下域名解析是否成功，某天cf解析抽风了就出现这个问题

**Comment by blueveryday** [comment]
> 是否有网页版的防火墙 检查一下

确实有这个问题，第一次安装脚本顺利通过，卸载脚本，再重新安装，就会提示443端口未开放。
其实443端口开放了的。
原因不明，只能DD系统才能解决。
debian 10系统。

**Comment by iSteveyang** [comment]
> 是否有网页版的防火墙 检查一下

相同问题，使用正常，更新新版本后想尝试其他协议安装，删除以前的账号选择重新安装报错，iptables -L 无端口 sudo lsof -i :无占用，卸载并删除nginx 配置/usr/share/nginx/ /etc/nginx 依旧无法重新安装，显示
` ---> 请检查是否有网页防火墙，比如Oracle等云服务商 
 ---> 检查是否自己安装过nginx并且有配置冲突，可以尝试DD纯净系统后重新尝试 `

**Comment by iamjimmycheng** [comment]
同样的问题，只要点了卸载脚本，就无法再安装了，不但443端口用不了，是所有端口都用不了，换任何端口都会提示未开放，由于VPS上还安装了docker一堆应用，没法DD了，只能浪费一台VPS了。

**Comment by fengshgx** [comment]
同样点了删除脚本后就无法安装，443端口或者换端口安装都不行。不知道有没有docker版好用的。

**Comment by iSteveyang** [comment]
我使用以下指令完全删除nginx及其配置，就可以正常重装了
```
apt-get purge nginx nginx-common nginx-full nginx-core
rm -rf /etc/nginx
rm -rf /var/log/nginx
```

**Comment by fengshgx** [comment]
> 我使用以下指令完全删除nginx及其配置，就可以正常重装了
> 
> ```
> apt-get purge nginx nginx-common nginx-full nginx-core
> rm -rf /etc/nginx
> rm -rf /var/log/nginx
> ```

感谢，不过我使用的也是这个命令，并且删除后使用以下命令查找，也找不到nginx了。
`find  /  -name nginx`
但是仍然提示端口问题。
而且奇怪的是另一台就没有这种问题，用mack-a脚本上自带的删除即可。
两台部署的服务基本相同，没问题的那一台安装的东西更多，实在不知道为啥。
而且我也是换端口安装也不行，nginx初始占用的也只是443，应该和其他端口也没关系。

**Comment by CitrusFlavored** [comment]
我的机器上已经部署了nginx，也要使用，不想重新安装。
看了一下vasma脚本，我的解决方法是在原来的nginx配置文件**合适位置**加上 `include /etc/nginx/conf.d/*.conf;` 即可，实测不影响原网站配置（不要与原网站端口冲突），也能正常使用该脚本。

![Image](https://github.com/user-attachments/assets/efcb442c-7d65-4445-ae81-d44aca9d71cd)
