### ISSUE TITLE
合并订阅时添加订阅成功但是查看订阅没有从机节点

### ISSUE THREAD

**Issue by LoogCP** [mack-a/v2ray-agent#758]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
合并订阅时主机添加订阅成功，但是查看订阅没有从机节点
已确保主机和从机的用户名和salt完全一致

## 2.安装失败的log或者截图
> 添加订阅时log(域名是正常的，故意替换成星号的)：
```
请选择:7

功能 1/1 : 账号管理

==============================================================
# 添加单个用户时可自定义email和uuid
# 如安装了Hysteria或者Tuic，账号会同时添加到相应的类型下面

1.查看账号
2.查看订阅
3.添加订阅
4.添加用户
5.删除用户
==============================================================
请输入:3

===================== 添加其他机器订阅 =======================
1.添加
2.移除
==============================================================
请选择:1
#注意事项:
请仔细阅读以下文章： https://www.v2ray-agent.com/archives/1681804748677
录入示例：www.v2ray-agent.com:443:vps1

请输入域名 端口 机器别名:hk.******.***:443:hk
 ---> 通用订阅 loogcp 添加成功
 ---> clashMeta订阅 loogcp 添加成功
```

> 主机查看订阅时日志：
```
功能 1/1 : 账号管理

==============================================================
# 添加单个用户时可自定义email和uuid
# 如安装了Hysteria或者Tuic，账号会同时添加到相应的类型下面

1.查看账号
2.查看订阅
3.添加订阅
4.添加用户
5.删除用户
==============================================================
请输入:2
-------------------------备注---------------------------------
# 查看订阅会重新生成本地账号的订阅
# 添加账号或者修改账号需要重新查看订阅才会重新生成对外访问的订阅内容
# 需要手动输入md5加密的salt值，如果不了解使用随机即可
# 不影响已添加的远程订阅的内容

读取到上次安装设置的Salt，是否使用上次生成的Salt ？[y/n]:y

 ---> Salt: **tdazrj**
 ---> 通用订阅 hk.******_hk.***:loogcp 不存在
--------------------------------------------------------------
---> clashMeta订阅 hk.******_hk.***:loogcp不存在
```
**<font color=red>日志中前面一个hk是域名的，后面_hk是机器别名，我不知道是不是因为机器别名被组装到域名里面导致的错误</font>**

## 3.系统版本
> 主机：Debian 12，kernel：6.1
```
root@debian ~# uname -a
Linux debian 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
root@debian ~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

> 从机：Debian 11 ，kernel：5.10
```
root@ECS1872 ~# uname  -a
Linux ECS1872 5.10.0-25-cloud-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
root@ECS1872 ~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
## 4.脚本版本
> 主机：v2.10.12
```
==============================================================
作者：mack-a
当前版本：v2.10.12
Github：https://github.com/mack-a/v2ray-agent
描述：八合一共存脚本
核心: Xray-core[运行中]
已安装协议: VLESS+TCP[TLS_Vision] Trojan+TCP[TLS]
```

> 从机：v2.10.12
```
==============================================================
作者：mack-a
当前版本：v2.10.12
Github：https://github.com/mack-a/v2ray-agent
描述：八合一共存脚本
核心: Xray-core[运行中]
已安装协议: VLESS+TCP[TLS_Vision] Trojan+TCP[TLS] VLESS+Reality+Vision VLESS+Reality+gRPC
```

**Comment by mack-a** [comment]
可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了

**Comment by LoogCP** [comment]
> 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了

这个过程我重复了好几次都还是这个报错
我甚至把脚本（主机和从机）都重新安装了还是不行

**Comment by mack-a** [comment]
> > 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了
> 
> 这个过程我重复了好几次都还是这个报错 我甚至把脚本（主机和从机）都重新安装了还是不行

把订阅也卸载掉重新试一下 这个问题我刚刚复现了一次 重新卸载后又不会复现 目前没有定位问题在哪

试一下 主机和从机 安装一样的协议试一下

**Comment by LoogCP** [comment]
> > > 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了
> > 
> > 这个过程我重复了好几次都还是这个报错 我甚至把脚本（主机和从机）都重新安装了还是不行
> 
> 把订阅也卸载掉重新试一下 这个问题我刚刚复现了一次 重新卸载后又不会复现 目前没有定位问题在哪
> 
> 试一下 主机和从机 安装一样的协议试一下

我主机和从机都重新安装了，删除了之前的订阅，都还是不行，重新随机了一个salt也还是不行

**Comment by LoogCP** [comment]
> > > 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了
> > 
> > 这个过程我重复了好几次都还是这个报错 我甚至把脚本（主机和从机）都重新安装了还是不行
> 
> 把订阅也卸载掉重新试一下 这个问题我刚刚复现了一次 重新卸载后又不会复现 目前没有定位问题在哪
> 
> 试一下 主机和从机 安装一样的协议试一下


今天把脚本全部卸载了，拉取了最新的2.10.13从头开始，始终都是这个问题，我在想是不是我两台机子的ip绑定的是一个域名的不同子域名的问题
但是我也没有多的域名测试

**Comment by LoogCP** [comment]
> > > 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了
> > 
> > 这个过程我重复了好几次都还是这个报错 我甚至把脚本（主机和从机）都重新安装了还是不行
> 
> 把订阅也卸载掉重新试一下 这个问题我刚刚复现了一次 重新卸载后又不会复现 目前没有定位问题在哪
> 
> 试一下 主机和从机 安装一样的协议试一下

我想我找到原因了
主机添加从机订阅之后，可以在/etc/v2ray-agent/subscribe_remote里面找到从机的订阅信息已经从机的节点链接，这个链接本应该和从机etc/v2ray-agent/subscribe_local中的节点链接一致（除了最后的节点名称那儿）
我估计你是把【用户名】替换成【用户名_VPS别名】，而我正好域名里面包含了【用户名】字段，所以导致替换的时候把域名也给替换了
我重新添加了和域名区别的【用户名】验证一下

**Comment by mack-a** [comment]
> > > > 可以选择 **vasma->7->3->2** 卸载后重新添加订阅 应该就没有问题了
> > > 
> > > 
> > > 这个过程我重复了好几次都还是这个报错 我甚至把脚本（主机和从机）都重新安装了还是不行
> > 
> > 
> > 把订阅也卸载掉重新试一下 这个问题我刚刚复现了一次 重新卸载后又不会复现 目前没有定位问题在哪
> > 试一下 主机和从机 安装一样的协议试一下
> 
> 我想我找到原因了 主机添加从机订阅之后，可以在/etc/v2ray-agent/subscribe_remote里面找到从机的订阅信息已经从机的节点链接，这个链接本应该和从机etc/v2ray-agent/subscribe_local中的节点链接一致（除了最后的节点名称那儿） 我估计你是把【用户名】替换成【用户名_VPS别名】，而我正好域名里面包含了【用户名】字段，所以导致替换的时候把域名也给替换了 我重新添加了和域名区别的【用户名】验证一下

会存在这种情况，等我有空修复一下

**Comment by mack-a** [comment]
感谢反馈
