### ISSUE TITLE
域名解析IP与当前服务器IP不一致

### ISSUE THREAD

**Issue by onlyling** [mack-a/v2ray-agent#759]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述

重装系统（`Debian 12 x86_64`）通过[八合一一键脚本，快速搭建教程](https://www.v2ray-agent.com/archives/1682491479771)`一图教程`安装。

域名已在 `cloudflare` 开启 DNS 记录。

<img width="1284" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/9999765/84f573c4-4cd1-44b7-8546-8b3a4cea5dae">

## 2.安装失败的log或者截图

<img width="616" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/9999765/0be18a81-4f61-44b9-b459-0570a9cae551">

## 3.系统版本

Debian 12 x86_64

## 4.脚本版本

最新

**Comment by mack-a** [comment]
云朵关掉
