### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by mack-a** [mack-a/v2ray-agent#76]
- [ ] 任意门多出战 https://github.com/mack-a/v2ray-agent/issues/384
- [ ] 支持arch https://github.com/mack-a/v2ray-agent/issues/406
- [ ] https://github.com/mack-a/v2ray-agent/issues/702
- [ ] https://github.com/mack-a/v2ray-agent/issues/687
- [ ] https://github.com/mack-a/v2ray-agent/issues/675
- [ ] https://github.com/mack-a/v2ray-agent/issues/632
- [ ] https://github.com/mack-a/v2ray-agent/issues/653
- [x] SSL API申请
- [ ]  google play规则
- [ ] https://github.com/mack-a/v2ray-agent/issues/729
- [x] 优化查看节点时的IP展示（有域名则展示域名、没有则获取vps IP）
- [ ] https://github.com/mack-a/v2ray-agent/issues/795
- [ ] https://github.com/mack-a/v2ray-agent/issues/809
- [ ] https://github.com/mack-a/v2ray-agent/issues/774
- [ ] https://github.com/mack-a/v2ray-agent/issues/809
- [ ] https://github.com/mack-a/v2ray-agent/issues/745
- [ ] https://github.com/mack-a/v2ray-agent/issues/718
- [ ] https://github.com/mack-a/v2ray-agent/issues/808
- [x] reality scanner
- [ ] https://github.com/mack-a/v2ray-agent/issues/840

**Comment by Amos-Dan** [comment]
筛选条件：
1、配置个数(脚本内置判断)
2、二维码或者链接(两个选项)
3、用户email及对应的序号(删除时的那个列表)

**Comment by Amos-Dan** [comment]
### 关于脚本中第3个选项(用户管理)中二级菜单中“账号查看”功能的问题说明。

**一、问题**
如果账号(多用户配置)较多时，使用该功能进行账号查看的时候，无法准确定位与查询用户想要的特定用户的配置信息
**二、期望**
将账号查看的查询结果进行控制或筛选后进行返回，可以考虑的方式有以下几种：
1是脚本内置判断（判断账号的配置个数），返回email序号进行控制查询；
2是在1的基础上，增加direct与splice选择
3是在2的基础上，增加链接、明文、二维码选择
至于先选择direct/splice还是先选择链接/明文/二维码，有待探讨。
**三、具体建议**
**方案1**
1、脚本内置判断，对于自用的，没有多账号的（仅有1个配置），直接返回结果（链接、明文、二维码(direct和splice各一套)）
2、脚本内置判断，对于多账号的(大于等于2)，给出账号email列表，选择相应的序号，返回结果（链接、明文、二维码(direct和splice各一套)）
**方案2.1**
1、脚本内置判断，对于自用的，没有多账号的（仅有1个配置），提示选择direct与splice，之后返回相应结果（一套链接、明文、二维码）
2、脚本内置判断，对于多账号的(大于等于2)，给出账号email列表，选择相应的序号，提示选择direct/splice，之后返回相应结果（一套链接、明文、二维码）
**方案2.2**
1、脚本内置判断，对于自用的，没有多账号的（仅有1个配置），提示选择二维码、明文或链接，之后返回相应结果（direct与splice两类）
2、脚本内置判断，对于多账号的(大于等于2)，给出账号email列表，选择相应的序号，提示选择二维码、明文或链接，之后返回相应结果（direct与splice两类）
**方案3**
1、脚本内置判断，对于自用的，没有多账号的（仅有1个配置），提示选择二维码、明文或链接，之后再提示选择direct或splice，最终仅返回一个内容
2、脚本内置判断，对于多账号的(大于等于2)，给出账号email列表，选择相应的序号，提示选择二维码、明文或链接，之后再提示选择direct或splice，最终仅返回一个内容
