### ISSUE TITLE
能否考虑添加证书时加入“使用自定义证书”选项？

### ISSUE THREAD

**Issue by linconbb** [mack-a/v2ray-agent#760]
如题，在某些被墙的NAT VPS中，需要使用vmess+ws+tls(CDN)。使用8合1一键脚本进行ACME证书申请时，由于没有80端口，无法完成证书申请。能否考虑加入从VPS本地选取证书的选项，保证脚本可正常执行？

**Comment by mack-a** [comment]
现在就支持呀 https://github.com/mack-a/v2ray-agent/blob/master/documents/install_tls.md
