### ISSUE TITLE
TUIC启动失败

### ISSUE THREAD

**Issue by haomuch** [mack-a/v2ray-agent#761]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
使用脚本安装TUIC协议，所有选项都是默认，结果显示启动失败。

## 2.安装失败的log或者截图
-- Logs begin at Mon 2023-07-10 06:11:40 UTC. --
Aug 30 03:21:26 fox-vm systemd[1]: Stopped Tuic Service.
Aug 30 03:21:26 fox-vm systemd[1]: Started Tuic Service.
Aug 30 03:21:26 fox-vm tuic[809826]: UUID parsing failed: invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `o` at 2 at line 4 column 8
Aug 30 03:21:26 fox-vm systemd[1]: tuic.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 03:21:26 fox-vm systemd[1]: tuic.service: Failed with result 'exit-code'.
Aug 30 03:21:26 fox-vm systemd[1]: tuic.service: Scheduled restart job, restart counter is at 5.
Aug 30 03:21:26 fox-vm systemd[1]: Stopped Tuic Service.
Aug 30 03:21:26 fox-vm systemd[1]: tuic.service: Start request repeated too quickly.
Aug 30 03:21:26 fox-vm systemd[1]: tuic.service: Failed with result 'exit-code'.
Aug 30 03:21:26 fox-vm systemd[1]: Failed to start Tuic Service.

## 3.系统版本
Ubuntu 20.04.5 LTS 

## 4.脚本版本
v2.10.13

**Comment by mack-a** [comment]
完全卸载后重新安装
