### ISSUE TITLE
Xray failed to start 

### ISSUE THREAD

**Issue by Ros-ua** [mack-a/v2ray-agent#765]
## 1.问题描述
during install 
## 2.安装失败的log或者截图
Progress 11/13 : Add fake site 
 ---> Add fake site successfully 
---> Xray closed successfully 
Xray failed to start 
Please manually execute [/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf] to view the error log 

## 3.系统版本
debain 11 

root@GGC-24198-98948-gorovets:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)
A unified platform for anti-censorship.
2023/09/01 23:36:18 Using confdir from arg: /etc/v2ray-agent/xray/conf
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.

**Comment by mack-a** [comment]
this version https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.14

**Comment by predators46** [comment]
@mack-a 

I want to know how to fix this problem. It looks like the English version is no longer updated
