### ISSUE TITLE
Hysteria启动失败

### ISSUE THREAD

**Issue by drwangyd** [mack-a/v2ray-agent#766]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 2.安装失败的log或者截图

进度  3/5 : 配置Hysteria开机自启
 ---> 配置Hysteria开机自启成功
 ---> Xray关闭成功
 ---> Xray启动成功
 ---> Hysteria关闭成功
Hysteria启动失败
请手动执行【/etc/v2ray-agent/hysteria/hysteria --log-level debug -c /etc/v2ray-agent/hysteria/conf/config.json server】，查看错误日志

-- Logs begin at Sat 2023-09-02 16:46:38 CST. --
Sep 02 17:01:11 racknerd-247025 hysteria[7729]: 2023-09-02T17:01:11+08:00        INFO        server mode
Sep 02 17:01:11 racknerd-247025 hysteria[7729]: 2023-09-02T17:01:11+08:00        FATAL        failed to parse server config        {"error": "1 error(s) decoding:\n\n* 'resolver' expected a map, got 'string'"}

## 3.系统版本
debian10 64bit
## 4.脚本版本
2.10.14

**Comment by mack-a** [comment]
hy2 有空兼容下

**Comment by iceraintsx** [comment]
> hy2 有空兼容下

我也遇到这个问题，麻烦大佬尽快帮忙处理下，谢谢

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.15 2.0需要等客户端进行兼容 目前先限制了v1的最新版本

**Comment by ulifuqiang** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.15 2.0需要等客户端进行兼容 目前先限制了v1的最新版本

已经有不是客户端支持2.0了哦
