### ISSUE TITLE
Xray failed to start

### ISSUE THREAD

**Issue by firestarter7924** [mack-a/v2ray-agent#767]
![image_2023-09-02_22-21-00](https://github.com/mack-a/v2ray-agent/assets/47260646/b619904b-129f-4a96-91b0-079fce555fda)
![image_2023-09-02_22-21-43](https://github.com/mack-a/v2ray-agent/assets/47260646/5b7c3bfa-76ec-4059-a243-89174812cc62)
![image_2023-09-02_22-22-52](https://github.com/mack-a/v2ray-agent/assets/47260646/6f86d4e2-e5c9-4320-94ec-fbbf7bde0c80)
![image_2023-09-02_22-23-09](https://github.com/mack-a/v2ray-agent/assets/47260646/835f11bb-957f-44e0-bbba-2e7496a344ff)

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.20
