### ISSUE TITLE
脚本读到的VPS IP与运营商提供的公网IP不一致

### ISSUE THREAD

**Issue by msn1983aa** [mack-a/v2ray-agent#768]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
因为被墙问题，已多次更换了VPS（甲骨文免费VPS）的公网IP，但是脚本读到的始终是一个104开头的IP地址

## 2.安装失败的log或者截图
---> 域名解析IP与当前服务器IP不一致
  ---> 请检查域名解析是否生效以及正确 
 ---> 当前VPS IP：104.28.xxx.xxx
 ---> DNS解析 IP：152.70.xxx.xxx

## 3.系统版本
Ubuntu 20.04.2 LTS (GNU/Linux 5.12.13-bbrplus x86_64)

## 4.脚本版本
当前版本：v2.10.14

**Comment by mack-a** [comment]
卸载全局的warp

**Comment by msn1983aa** [comment]
请选择:11
功能 1/1 : 分流工具 
============================================================== 
1.WARP分流【第三方 IPv4】 
2.WARP分流【第三方 IPv6】 
3.IPv6分流 
4.任意门分流 
5.DNS分流 
6.VMess+WS+TLS分流 
7.SNI反向代理分流 

并没有安装，因为没有出现卸载选项，而且之前使用过“20.卸载脚本”几次，应该是卸载了所有东西了

劳烦大佬再帮忙看看原因

**Comment by msn1983aa** [comment]
尝试卸载了VPS上唯一名字里包含WARP的软件包cloudflare-warp（我也不确定是不是这个）
The following packages will be REMOVED:
  cloudflare-warp*
0 upgraded, 0 newly installed, 1 to remove and 77 not upgraded.
然后重启了VPS
再安装依旧提示IP不一致

**Comment by msn1983aa** [comment]
最后用DD脚本重装了系统就好了
