### ISSUE TITLE
2.10.14 安装reality后并没有账号回执

### ISSUE THREAD

**Issue by Etherealblade** [mack-a/v2ray-agent#769]
## 1.问题描述
更新xray core 到1.8.4, 其实我用脚本的更新core选项从来都没有升级成功. 每次都是重新安装reality. 但是更新脚本到2.10.14后, 接着更新xray core, 安装成功之后, 脚本却没有给出vless链接

## 2.安装失败的log或者截图
![2023-09-03_194355 xray更新失败](https://github.com/mack-a/v2ray-agent/assets/15205420/18cd3460-b6d8-41ce-9bfd-6ceb6ef203cd)

## 3.系统版本
Debian GNU/Linux 10 (buster) x86_64

## 4.脚本版本
2.10.14

**Comment by mack-a** [comment]
更新 https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.15 重新尝试
