### ISSUE TITLE
证书问题，一直提醒证书安装失败

### ISSUE THREAD

**Issue by gongyuan300** [mack-a/v2ray-agent#771]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
证书问题，一直提醒证书安装失败
## 2.安装失败的log或者截图
[Wed Sep  6 08:04:11 UTC 2023] Standalone mode.
[Wed Sep  6 08:04:11 UTC 2023] Single domain='www.XXXX.com'
[Wed Sep  6 08:04:11 UTC 2023] Getting domain auth token for each domain
[Wed Sep  6 08:04:11 UTC 2023] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
[Wed Sep  6 08:04:11 UTC 2023] Please add '--debug' or '--log' to check more details.
[Wed Sep  6 08:04:11 UTC 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
 ---> TLS安装失败，请检查acme日志 

## 3.系统版本
debian11
## 4.脚本版本
官网脚本

**Comment by gongyuan300** [comment]
v2ray的不能使用了吗  那客户端qv2ray还能使用吗

**Comment by gongyuan300** [comment]
如何手动配置证书 不用自动配置证书啊 ，我配置证书放到固定目录 但是/etc/v2ray-agent/tls/下面 但是不起作用

**Comment by mack-a** [comment]
换个子域名重新尝试

**Comment by gongyuan300** [comment]
问题解决了
