### ISSUE TITLE
任意门能否增加V6的分流？

### ISSUE THREAD

**Issue by nicepass** [mack-a/v2ray-agent#774]
对于有V6地址，但是V4解锁流媒体的落地小鸡应该挺有用的

**Comment by mack-a** [comment]
解锁机 有IPv6 而且仅IPv6解锁。现在的需求是要把被解锁机进行任意门 IPv6到解锁机？

**Comment by nicepass** [comment]
中转机只有V6，落地机有V4和V6，但只有V4解锁流媒体

**Comment by mack-a** [comment]
V6出 V4进？

**Comment by nicepass** [comment]
中转机V6出，落地机V6进，V4出
