### ISSUE TITLE
使用WARP脚本之后，REALITY被替换成全局代理的CF的IP

### ISSUE THREAD

**Issue by LReion** [mack-a/v2ray-agent#776]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
使用WARP脚本之后，在订阅链接中和实际显示的REALITY的地址是分配的CloudFlare的地址
## 3.系统版本
Debian GNU/Linux 10
## 4.脚本版本
2.10.18

**Comment by mack-a** [comment]
全局接管就是这样子 你可以选择用域名搭建 那样会展示域名
