### ISSUE TITLE
你好大神，有个问题想请教。

### ISSUE THREAD

**Issue by reds2lucas** [mack-a/v2ray-agent#778]
**详细描述建议的内容**
为啥我选择1的方式安装，然后到了输入域名和端口那个环节后，老是提示我域名没有解析成功。
但是我明明把域名解析了呀，换了好几个域名都说不行。。。。。

**Comment by mack-a** [comment]
排除下系统等问题

**Comment by mack-a** [comment]
可以尝试dd系统
