### ISSUE TITLE
请添加重启核心选项

### ISSUE THREAD

**Issue by DLGum** [mack-a/v2ray-agent#78]
**详细描述建议的内容**
如题。在手动修改用户id或者密码之后重启核心就能直接使用。
或者按自己需要修改配置的情况实验方便。
目前小白基本只能通过重启服务器达成。

**Comment by mack-a** [comment]
我的想法是如果自己手动改配置那就应该手动重启，README也写了常用的重启命令。所以目前还没有加这个的打算。
