### ISSUE TITLE
特殊端口自定义问题

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [mack-a/v2ray-agent#780]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
因特殊需求，需使用自定义端口53，但未能成功配置

## 2.安装失败的log或者截图
卡在输入端口后的Nginx上，如果使用443等常见端口则可以正常创建并使用
使用openvpn工具可正常用53端口，所以排除服务器问题
如果是bug，希望修复；如果是未适配，希望适配；如果是v2ray的硬伤，希望告知，我再找别的方案

## 3.系统版本
ubuntu 20.04

## 4.脚本版本
v2.10.18 Latest

**Comment by mack-a** [comment]
<img width="562" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/57424792/652dcf06-9802-424f-aefb-0a3e0c5e89d8">

53是可以的 正常访问

**Comment by YaeSakuraQvQ** [comment]
已经尝试过多次，尝试过卸载重装，均未解决，详细截图见下面
脚本自动装nginx或按提示尝试手动卸载手动装均未能解决
如果是我操作的问题，希望大佬指出，多谢指教~
![111](https://github.com/mack-a/v2ray-agent/assets/87939280/9111a99c-d3e8-4e2f-82ff-025f25fbb929)

**Comment by YaeSakuraQvQ** [comment]
> <img alt="image" width="562" src="https://user-images.githubusercontent.com/57424792/269353696-652dcf06-9802-424f-aefb-0a3e0c5e89d8.png">
> 53是可以的 正常访问

大佬，我的不行...详细截图见上一条(
