### ISSUE TITLE
怎样把伪网站换成一个真的网站?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [mack-a/v2ray-agent#781]
因为我想搭一个普通的blog，这样就可以同时使用blog和加密流量。

**Comment by mack-a** [comment]
需要nginx做一下反代即可

**Comment by piiiiiiiiiiiiiii** [comment]
> 需要nginx做一下反代即可

也就是说还需要再安装一个web服务器了?

**Comment by mack-a** [comment]
如果你的blog是一个动态的web服务，需要设置反向代理，如果静态文件修改一下配置的root路径即可

**Comment by piiiiiiiiiiiiiii** [comment]
> 如果你的blog是一个动态的web服务，需要设置反向代理，如果静态文件修改一下配置的root路径即可

明白了，谢谢

**Comment by piiiiiiiiiiiiiii** [comment]
> 如果你的blog是一个动态的web服务，需要设置反向代理，如果静态文件修改一下配置的root路径即可

你好，我现在已经在vps上面跑起一个apache，http端口是88，现在问题如下：

我在apache上面开了两个vhost，分别是www.aaa.com和www.bbb.com:
1. 怎么把伪网站反代到www.aaa.com，当然这个要使用ssl
2. 同样，怎样再建一个网站反代到www.bbb.com，这个只使用http

nginx不熟悉，麻烦您了

**Comment by mack-a** [comment]
你把alone.conf那个文件扔到ChatGPT或者其他AI 然后让他给你改

**Comment by piiiiiiiiiiiiiii** [comment]
> 你把alone.conf那个文件扔到ChatGPT或者其他AI 然后让他给你改

这样也行，我试下

**Comment by piiiiiiiiiiiiiii** [comment]
> 你把alone.conf那个文件扔到ChatGPT或者其他AI 然后让他给你改

我在alone.conf同目录添加了一个，配置如下：
server {
	listen 127.0.0.1:80;
	server_name www.784533.xyz;

	location / {
		proxy_pass  http://127.0.0.1:88
	}
}


结果重启后http和https都访问不到了。

**Comment by piiiiiiiiiiiiiii** [comment]
下面是alone.conf的默认配置：

----------------------
server {
    	listen 127.0.0.1:31300;
    	server_name _;
    	return 403;
}

server {
	listen 127.0.0.1:31302 so_keepalive=on;http2 on;
	server_name www.domain.xyz;
	root /usr/share/nginx/html/;

	client_header_timeout 1071906480m;
    keepalive_timeout 1071906480m;

	location ~ ^/s/(clashMeta|default|clashMetaProfiles)/(.*) {
        default_type 'text/plain; charset=utf-8';
        alias /etc/v2ray-agent/subscribe/$1/$2;
    }

    location /annagrpc {
    	if ($content_type !~ "application/grpc") {
    		return 404;
    	}
 		client_max_body_size 0;
		grpc_set_header X-Real-IP $proxy_add_x_forwarded_for;
		client_body_timeout 1071906480m;
		grpc_read_timeout 1071906480m;
		grpc_pass grpc://127.0.0.1:31301;
	}

	location /annatrojangrpc {
		if ($content_type !~ "application/grpc") {
            		return 404;
		}
 		client_max_body_size 0;
		grpc_set_header X-Real-IP $proxy_add_x_forwarded_for;
		client_body_timeout 1071906480m;
		grpc_read_timeout 1071906480m;
		grpc_pass grpc://127.0.0.1:31304;
	}
	location / {
        	add_header Strict-Transport-Security "max-age=15552000; preload" always;
    }
}
server {
	listen 127.0.0.1:31300;
	server_name www.domain.xyz;
	root /usr/share/nginx/html/;
	location ~ ^/s/(clashMeta|default|clashMetaProfiles)/(.*) {
            default_type 'text/plain; charset=utf-8';
            alias /etc/v2ray-agent/subscribe/$1/$2;
        }
	location / {
		add_header Strict-Transport-Security "max-age=15552000; preload" always;
	}
}

-------------------------------------
如上，有多个server{}，那么当我访问http://www.domain.xyz时，从80跳到443的动作又是哪里配置的呢，没有找到

**Comment by piiiiiiiiiiiiiii** [comment]
问题解决，由于不懂nginx配置，错误的参照了alone.conf，如下手工写了一个后问题解决：

server {
        listen 80;
        server_name www.aaa.com;
        location / {
                proxy_pass  http://127.0.0.1:88;
        }
}
