### ISSUE TITLE
更新证书问题

### ISSUE THREAD

**Issue by shijia7** [mack-a/v2ray-agent#787]
今天发现证书过期，选择脚本的功能9更新证书，显示--未安装，但使用acme的renew命令是可以更新的，请问如何在不重装的情况下自动更新证书。

以下是log好像8月份之后我更新了脚本证书就不会自动更新了：

[1;36m ---> 证书剩余天数:48 [0m
[1;36m ---> 证书过期前最后一天自动更新，如更新失败请手动更新 [0m
[32m ---> 证书有效 [0m
[1;36m ---> 证书检查日期:2023-08-07 01:30:01 [0m
[1;36m ---> 证书生成日期:2023-06-24 23:24:30 [0m
[1;36m ---> 证书生成天数:43 [0m
[1;36m ---> 证书剩余天数:47 [0m
[1;36m ---> 证书过期前最后一天自动更新，如更新失败请手动更新 [0m
[32m ---> 证书有效 [0m
[31m ---> 未安装 [0m
[31m ---> 未安装 [0m
[31m ---> 未安装 [0m
[31m ---> 未安装 [0m
[31m ---> 未安装 [0m

**Comment by mack-a** [comment]
重新安装，中间的版本有更新这块的逻辑 如果你的是旧逻辑并且是新脚本会出现无法更新的情况
