### ISSUE TITLE
Hysteria2.0 协议由于对垃圾线路提升效果很好，非常推荐大佬在百忙之中在脚本中升级到2.0

### ISSUE THREAD

**Issue by msn1983aa** [mack-a/v2ray-agent#788]
**详细描述建议的内容**
Hysteria2.0 协议是垃圾线路的救星，降低延迟、提升线路质量，求大佬在百忙之中集成到脚本里替换目前的1.0版本

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.10.22

**Comment by msn1983aa** [comment]
感谢感谢，速度太快了
