### ISSUE TITLE
关于使用脚本搭建xray后服务器产生异常流量的问题

### ISSUE THREAD

**Issue by Meteor2017** [mack-a/v2ray-agent#789]
## 1.问题描述
搬瓦工和DMIT服务器，通过开源地址的一键脚本进行xray的搭建后，突然某一天产生持续的异常流量，直至流量服务器耗尽为止。
并不是搭建开始就出现问题，而是好几天服务器统一在某个时间点出现该问题。节点是自己在使用，并未发送给任何人，且在异常消耗流量期间，本人并未连接节点使用。不知道是脚本问题还是配置泄露（但是我确实没分享给任何人，想不到任何泄露的可能），以下为自己排查的一些截图和日志，请大佬帮忙解答一下，万分感谢。

## 2.安装失败的log或者截图
以下为搬瓦工服务器面板流量监控图
![1](https://github.com/mack-a/v2ray-agent/assets/24621810/046d49db-b001-47e8-80b7-ad8282e300c9)
以下为finalshell流量监控面板监测到的跑流量的情况
![2](https://github.com/mack-a/v2ray-agent/assets/24621810/8b8977ad-d74c-4a65-8bd6-1b903c3e27db)
监听对应端口发现为xray在跑流量
![3](https://github.com/mack-a/v2ray-agent/assets/24621810/803a83ab-ce4f-48f2-bbe4-fb3c6d2b46b9)
异常跑流量服务器的nginx部分日志，发现大量持续的高并发get访问记录，访问伪装网站的js文件，该节点并没有分享给其他人使用，自己此时也并没有在连接
![4](https://github.com/mack-a/v2ray-agent/assets/24621810/a869be0d-cb24-4069-80d6-7e96fde7a8ea)
尝试对比另一台未出问题的搬瓦工，自己连接节点进行跑speedtest测速，对比两者的nginx日志，以下为正常服务器，自己使用节点的情况
![5](https://github.com/mack-a/v2ray-agent/assets/24621810/26484968-791b-4e52-990f-8d9e3f466944)
nginx日志
![6](https://github.com/mack-a/v2ray-agent/assets/24621810/dca2b507-9ffb-48cb-b44b-cce660e74dbd)

## 3.系统版本
Centos 7 x86_64
## 4.脚本版本
2023年9月19日复制的开源地址命令搭建的，应该是v2.10.19或者v2.10.20

**Comment by mack-a** [comment]
我猜 你这个应该是用了reality偷第三方的域名（这个域名被托管在cloudflare，并且脚本搭建的时候会提示风险） 或者偷自己的域名并且打开了云朵（脚本对打开云朵的域名无法成功搭建，但是如果自己搭建成功后打开，脚本无法检验）导致的被扫，被扫后会被当成转发进行转发cloudflare的流量。

**Comment by Meteor2017** [comment]
> 我猜 你这个应该是用了reality偷第三方的域名（这个域名被托管在cloudflare，并且脚本搭建的时候会提示风险） 或者偷自己的域名并且打开了云朵（脚本对打开云朵的域名无法成功搭建，但是如果自己搭建成功后打开，脚本无法检验）导致的被扫，被扫后会被当成转发进行转发cloudflare的流量。

用的是自己注册的域名。确实托管在cf，但是从解析至今并未打开小云朵cdn服务。一直用的vmess ws tls，没有用reality。这个确实很难定位到问题所在，苦恼，感谢作者的热心解答

**Comment by mack-a** [comment]
没有用reality是指的没有搭建reality还是搭建了没有用，如果没有搭建还在跑流量，通过你的nginx日志可以合理怀疑是被别人打了。

**Comment by mack-a** [comment]
默认安装的都是偷自己的 但是你说没有打开云朵，可以排除是被扫。可以观察下日志是不是被打了

**Comment by Meteor2017** [comment]
> 默认安装的都是偷自己的 但是你说没有打开云朵，可以排除是被扫。可以观察下日志是不是被打了

好的，感谢作者答复，我去研究一下
