### ISSUE TITLE
关于安装好脚本TLS_Vision、reality_vision、reality_grpc中，安装好脚本和CDN后，再开小黄云后上述三个连接不能用的问题

### ISSUE THREAD

**Issue by yzx1208** [mack-a/v2ray-agent#791]
**详细描述建议的内容**
关于安装好脚本TLS_Vision、reality_vision、reality_grpc中，安装好脚本和CDN后，再开小黄云后上述三个连接不能用的问题
1、地址为域名，sni也为域名时，同时CF开小黄云时，上述三个连接不能用
2、将地址为IP，SNI为域名时，同时开启小黄云，上述三个连接可用
个人建议，地址生成时，为IP即可，安装时小黄云关闭，安装好后，开启小黄云。原来的CDN的ip组合地址不变
![image](https://github.com/mack-a/v2ray-agent/assets/72859262/41ad9c1b-6564-4a44-8a3b-290b050fe91f)

**Comment by yzx1208** [comment]
VLESS_TCP/TLS_Vision这个开了小黄云还是不行，其他两个reality改成IP还是可以的。

**Comment by mack-a** [comment]
直连的协议不可以开云朵

**Comment by yzx1208** [comment]
make-a 大神，我的意思是，直连协议address完全可以更改为ip嘛，后期如果使用reality时，即使用户开启小黄云也是兼容的。尽管开启小黄云自认为安全点而已嘛。
