### ISSUE TITLE
大佬是否有计划支持sing-box 一键安装？

### ISSUE THREAD

**Issue by davidtall** [mack-a/v2ray-agent#792]
如题，最近sing-box 似乎很火，luci-app-passwall2 已经支持sing-box 内核。该项目有计划支持吗？

**Comment by mack-a** [comment]
已经在开始支持了呀

**Comment by davidtall** [comment]
> 已经在开始支持了呀

我看tuic 的确是支持了，由于sing-box 支持全协议，我的意思是有没有可能使用sing-box 内核完全替代xray 呢？
