### ISSUE TITLE
无法通过DNS获取域名IPv4 地址

### ISSUE THREAD

**Issue by NangenX** [mack-a/v2ray-agent#793]
## 1.问题描述
运行脚本获取报错提示“无法通过DNS获取域名 IPv4 地址”, DNS域名已正确解析，并且ping域名可以获取服务器IP信息。

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/18715023/89056b95-ae51-4ea1-92e6-82e552ef9417)

## 3.系统版本
20.04
## 4.脚本版本
v2.10.23

**Comment by NangenX** [comment]
查看脚本源码发现dig @1.1.1.1 +time=1 +short "${domain}" 无法获取报错，但是替换为dig @8.8.8.8 +time=1 +short "${domain}" 正常及txtAnswer=$(dig @8.8.8.8 +nocmd "_acme-challenge.${dnsTLSDomain}" txt +noall +answer | awk -F "[\"]" '{print $2}')后正常。

**Comment by ZhifaHan** [comment]
遇到了类似的问题

<img width="746" height="620" alt="Image" src="https://github.com/user-attachments/assets/294c8325-6a3a-4397-be4e-b56f3e5aae24" />
Ubuntu 22.04.5 LTS
