### ISSUE TITLE
/nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by 1207378404** [mack-a/v2ray-agent#8]

**Comment by mack-a** [comment]
请问你的系统是什么版本，脚本是一件安装CDN的脚本吗

**Comment by mack-a** [comment]
> _No description provided._

请问你的系统是什么版本，脚本是一件安装CDN的脚本吗

**Comment by 1207378404** [comment]
Debian 9.4。是的哦

**Comment by mack-a** [comment]
> Debian 9.4。是的哦

稍等 我试一下

**Comment by mack-a** [comment]
> Debian 9.4。是的哦
![image](https://user-images.githubusercontent.com/57424792/90011094-9426c380-dcd3-11ea-80ac-64053f021b6d.png)

![image](https://user-images.githubusercontent.com/57424792/90010993-6477bb80-dcd3-11ea-8ebe-b42b2c0ad3e2.png)
刚试了下GCP的Debian9 是可以安装成功的，如果方便的话可以tg私聊我，给个权限我上去瞧一下

**Comment by mack-a** [comment]
> Debian 9.4。是的哦

https://t.me/mack_a

**Comment by 1207378404** [comment]
我换Ubuntu可以了。谢啦

**Comment by mack-a** [comment]
> 我换Ubuntu可以了。谢啦
