### ISSUE TITLE
oracle DD debian 后使用自动配置, 所有CDN的协议无法使用. 

### ISSUE THREAD

**Issue by ialee9** [mack-a/v2ray-agent#800]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
使用自动安装所有配置.
除 TCP/TLS_vision 可以正常使用,
其他协议都无法使用 -1ms

## 2.安装失败的log或者截图

![01](https://github.com/mack-a/v2ray-agent/assets/91219603/3a76a41e-c174-496f-93cd-3fd48bfa61a3)

## 3.系统版本
Oracle cloud,  一键dd 全新  Debian 10

## 4.脚本版本
V2.11.5

大佬麻烦看一下, 谢谢

**Comment by ialee9** [comment]
补充:

2023/10/20 04:15:40 [Warning] [536852110] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"] > common/retry: all retry attempts failed

**Comment by ialee9** [comment]
自动生成 Vless gRPC,  配置文件

{
  "inbounds": [
    {
      "port": 31301,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "tag": "VLESSGRPC",
      "settings": {
        "clients": [
          {
            "id": "4c0e67e1-78f2-4085-9a1e-*******",
            "email": "4c0e67e1-vless_grpc"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "jiliguaguagrpc"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ]
}


好像没有域名设置, 是不是正确的?

**Comment by ialee9** [comment]
我蒙圈了, 在 
V2rayn  6.29  无法使用 gRPC 协议, 

在 4.34 竟然可以用,

真的不知道为何

**Comment by mack-a** [comment]
Fingerprint 修改成空白就可以用了 有空研究一下是哪的问题
