### ISSUE TITLE
无法通过DNS获取域名 IPv4 地址

### ISSUE THREAD

**Issue by Jiakuo0x** [mack-a/v2ray-agent#801]
## 1.问题描述
复现步骤：
1. 安装 
1. 选择 Xray-core
1. 输入域名
1. 输入端口（默认和任意）
1. 提示错误 **无法通过DNS获取域名 IPv4 地址**
注：已尝试不同域名，不同端口，均存在此问题。

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/88377252/3cb4f0c5-d156-46ea-b126-fd109cf21fcf)

## 3.系统版本
Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

## 4.脚本版本
v2.11.6 
![image](https://github.com/mack-a/v2ray-agent/assets/88377252/7e962bab-d26a-434b-b51a-1d42cb65a468)

**Comment by mack-a** [comment]
手动安装一下dig

**Comment by mack-a** [comment]
https://www.v2ray-agent.com/archives/1684115970026#heading-6
