### ISSUE TITLE
安装步骤3“初始化Nginx申请证书配置”时报错“域名解析IP与当前服务器IP不一致”，实际上是一致的

### ISSUE THREAD

**Issue by jinge1984** [mack-a/v2ray-agent#802]
## 1.问题描述
使用一键安装脚本安装时，到步骤3“初始化Nginx申请证书配置”时报错，“域名解析IP与当前服务器IP不一致”。但显示的域名解析IP和VPS IP是一致的。

我在截图里隐去了具体IP, 但我反复核对过，保证两个IP是一致的。

## 2.安装失败的log或者截图
![IP error](https://github.com/mack-a/v2ray-agent/assets/13271298/9b3ba264-6e58-45db-bb4c-dac448034cdc)

## 3.系统版本
CentOS 8

## 4.脚本版本
v2.11.6

**Comment by mack-a** [comment]
检查一下云朵是否关闭，检查一下dns解析的地方是否使用cname 如果用的是cname建议直接解析成IP

**Comment by jinge1984** [comment]
确实是dns解析使用了CNAME的原因。直接解析成IP后安装成功。谢谢
