### ISSUE TITLE
请求出一个docker版

### ISSUE THREAD

**Issue by stevejohnson7** [mack-a/v2ray-agent#803]
服务器上面用docker跑了不少服务，整体管理起来比较省心。希望作者可以考虑。

**Comment by yzx1208** [comment]
真的可以考虑下make-a 大神

**Comment by mack-a** [comment]
docker有别人做的核心镜像 自己写一个配置就可以用

**Comment by stevejohnson7** [comment]
> docker有别人做的核心镜像 自己写一个配置就可以用

方便说说在哪能找到吗，docker hub只搜到了这个 https://hub.docker.com/r/arthurm5089/v2ray-agent

**Comment by mxyhi** [comment]
> > docker有别人做的核心镜像 自己写一个配置就可以用
> 
> 方便说说在哪能找到吗，docker hub只搜到了这个 https://hub.docker.com/r/arthurm5089/v2ray-agent

找到了吗？ 同学
