### ISSUE TITLE
singbox核心加入关闭日志的功能

### ISSUE THREAD

**Issue by getMTbug** [mack-a/v2ray-agent#810]
**详细描述建议的内容**
RT，singbox核心目前只有开启日志的功能，脚本菜单列表里面没有关闭日志

**Comment by mack-a** [comment]
feat(脚本): 修复sing-box日志选项设置错误问题、修改tuic，hysteria2 server为IP展示、移除tuic，hysteria2选项中的sing-box核心管理并移动到16.core核心管理、修复v2rayN socks5端口设置问题

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.7
