### ISSUE TITLE
clashMeta订阅 导入clashx 报格式错误

### ISSUE THREAD

**Issue by CooljunS** [mack-a/v2ray-agent#812]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
yaml: unmarshal errors:
line 59: cannot unmarshal !!seq into string
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/4724304/b5a60cb7-38e0-4b36-aac8-43b70f5ac2f5)

## 4.脚本版本
v2.11.5

**Comment by mack-a** [comment]
ClashX不支持clashmeta吧 推荐使用 clashverge

**Comment by Gierry** [comment]
> ClashX不支持clashmeta吧 推荐使用 clashverge

关键是你这个一键脚本查看订阅也没有你说的那个clashverge类型的,默认的我试了也不行, 报一样的错误

**Comment by mack-a** [comment]
<img width="417" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/57424792/332fbd03-f40f-4146-b00e-110e03f6d1f4">

vasma->7查看订阅的时候有clashMeta订阅。支持clashMeta内核的都可以用。clashverge也支持原版clash

**Comment by mack-a** [comment]
https://www.v2ray-agent.com/archives/1695534611317

这里也有教程，建议多看看
