### ISSUE TITLE
希望hysteria2支持端口跳跃

### ISSUE THREAD

**Issue by x2287711259** [mack-a/v2ray-agent#816]
希望hysteria2支持端口跳跃，试用了一下脚本，hysteria2的搭建过程太简单了，而且也不支持端口跳跃，不知道是不是sing-box核心的问题，希望能够像一些hysteria2一键脚本那样提供更详细的设置，比如这两个
https://github.com/amcteams/hysteria-install
https://github.com/Misaka-blog/hysteria-install

**Comment by mack-a** [comment]
singbox不支持吧

**Comment by gungnirayu** [comment]
> Owner

我看好像是服务器端通过iptables做dnat来实现
