### ISSUE TITLE
大神 Hysteria 可自己修改流量嗎？

### ISSUE THREAD

**Issue by sammy0101** [mack-a/v2ray-agent#817]
流量太高我收到vps的警告了😶‍🌫️

**Comment by mack-a** [comment]
你本地改一下，后续会支持手动配置

**Comment by sammy0101** [comment]
bandwidth: 
  up: 300 mbps
  down: 500 mbps

我加了這段上去但好像沒效果..是語法不對嗎?
謝謝:)
