### ISSUE TITLE
sing-box 无法启动

### ISSUE THREAD

**Issue by cifei1** [mack-a/v2ray-agent#818]
## 1.问题描述
     安装Hysteria后调整warp分流会造成sing-box无法启动/重启
     看报错似乎是丢失了主配置文件
     尝试升级，也无法重启
     只能全部卸载重装
     可否提供重装sing-box选项 

## 2.安装失败的log或者截图
![QQ截图20231108191242](https://github.com/mack-a/v2ray-agent/assets/108108127/7a6fdaf0-32a2-453d-bc2b-bf75a54bd0fe)

## 3.系统版本

   Debian 11      5.10.0-8

## 4.脚本版本
v2.11.8

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.9

最新版试一下

**Comment by bigtree945** [comment]
小白报错就不会搞了啊，能不能修复纯ipv6先装warp，再一键hy2报错问题，拜托大佬了
sing-box启动失败 
请手动执行【/etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json】，查看错误日志
