### ISSUE TITLE
最新脚本在EUSERV上安装失败

### ISSUE THREAD

**Issue by AndersonGhost** [mack-a/v2ray-agent#82]
>下方留下相关的描述即可

**1.描述出现的问题**
```
#如题所述，最新脚本在EUSERV上安装失败。
```

**2.是否直接安装失败**
- 是

**3.直接安装失败的错误内容或者截图**
- 失败提示如下：
- 
当前域名的IP为 [XXX ，是否正确[y/n]？y

 ---> IP确认完成 

检查Nginx是否正常访问 

 ---> Nginx配置成功 

进度  4/17 : 申请TLS证书
 
 ---> 检测到证书 
 ---> 证书有效 
 ---> 如未过期请选择[n]
 
是否重新安装？[y/n]:y

进度  4/17 : 申请TLS证书
 
 ---> 未安装acme.sh 
root@xyz:~# 

**4.系统版本【例：Centos8】**
- Debian 9、Debian 10

**5.脚本版本**
- 

**6.安装类型**
- 个性化安装/全部安装

**7.安装的核心版本**
- V2ray-core

**8.出现问题的协议类型**
- 

**9.尝试重装后是否100%复现**
- 是

**10.是否仔细检查客户端与服务端的配置是否相同**
- 是

**Comment by AndersonGhost** [comment]
在Debian 9、Debian 10 上安装均失败，都是提示：未安装acme.sh，在这个地方失败。

**Comment by mack-a** [comment]
> > 下方留下相关的描述即可
> 
> **1.描述出现的问题**
> 
> ```
> #如题所述，最新脚本在EUSERV上安装失败。
> ```
> 
> **2.是否直接安装失败**
> 
> * 是
> 
> **3.直接安装失败的错误内容或者截图**
> 
> * 失败提示如下：
> 
> 当前域名的IP为 [XXX ，是否正确[y/n]？y
> 
> ---> IP确认完成
> 
> 检查Nginx是否正常访问
> 
> ---> Nginx配置成功
> 
> 进度 4/17 : 申请TLS证书
> 
> ---> 检测到证书
> ---> 证书有效
> ---> 如未过期请选择[n]
> 
> 是否重新安装？[y/n]:y
> 
> 进度 4/17 : 申请TLS证书
> 
> ---> 未安装acme.sh
> root@xyz:~#
> 
> **4.系统版本【例：Centos8】**
> 
> * Debian 9、Debian 10
> 
> ## **5.脚本版本**
> **6.安装类型**
> 
> * 个性化安装/全部安装
> 
> **7.安装的核心版本**
> 
> * V2ray-core
> 
> ## **8.出现问题的协议类型**
> **9.尝试重装后是否100%复现**
> 
> * 是
> 
> **10.是否仔细检查客户端与服务端的配置是否相同**
> 
> * 是

Debian9 Debian10 都不可以吗

**Comment by AndersonGhost** [comment]
是呀，我换了9和10都失败了

**Comment by mack-a** [comment]
> 在Debian 9、Debian 10 上安装均失败，都是提示：未安装acme.sh，在这个地方失败。

先用之前的稳定版本，这个问题稍后有空我改一下

**Comment by AndersonGhost** [comment]
怎样使用以前的版本啊？怎么操作？

**Comment by mack-a** [comment]
> 怎样使用以前的版本啊？怎么操作？

README里面有

**Comment by AndersonGhost** [comment]
好的，谢谢

**Comment by AndersonGhost** [comment]
经过测试，安装v2.2.13版本问题解决。

**Comment by mack-a** [comment]
这个问题是咋触发的，比如执行脚本的时候 提示安装acme了吗

**Comment by AndersonGhost** [comment]
没有提示啊

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.2 可以试一下这个

**Comment by ShangGuanLiXin** [comment]
CentOS-7也出现同样问题。
安装过程中

---------------------------------------------------------
Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.
 ---> 安装semanage 
 ---> 安装acme.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  202k  100  202k    0     0   149k      0  0:00:01  0:00:01 --:--:--  148k
no crontab for root
no crontab for root

进度  2/17 : 初始化Nginx申请证书配置 
-------------------------------------------------------
应该是出现【no crontab for root】，导致后续安装的东西失败了吧？

**Comment by ShangGuanLiXin** [comment]
补充：

 ---> 安装TLS证书 
[2021年 01月 19日 星期二 16:49:52 UTC] xxxx:Verify error:Fetching http://xxxx/.well-known/acme-challenge/zUA-5xl87l5JxAgxqlqEAExtGwCmf-5q9BSb-_zmWrY: Error getting validation data
[2021年 01月 19日 星期二 16:49:52 UTC] Please add '--debug' or '--log' to check more details.
[2021年 01月 19日 星期二 16:49:52 UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/xxxx_ecc/fullchain.cer: 没有那个文件或目录
 ---> TLS安装失败，请检查acme日志 

好像不是【no crontab for root】这个问题。重装系统后，解决了【no crontab for root】这个问题。再安装依然会出现这个问题。

而且只有第一次会出现这个问题。
再重新安装时，就会提示**---> 未安装acme.sh**

**Comment by mack-a** [comment]
应该是防火墙的问题，需要检查下防火墙，再就是看看面板是不是有额外的防火墙。
也可以更换系统再尝试下，建议不要用centos。找不到acme的那个问题最新脚本应该是修了。

**Comment by AndersonGhost** [comment]
在EUSERV上使用Debian 10，并升级最新补丁apt-get update && apt-get upgrade -y 后，安装还是失败。其提示如下：

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 ---> 安装curl 
 ---> 安装unzip 
 ---> 安装socat 
 ---> 安装jq 
 ---> 安装binutils 
 ---> 安装qrencode 
 ---> 安装nginx 
 ---> 安装semanage 
 ---> 安装sudo 
 ---> 安装acme.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  202k  100  202k    0     0  35109      0  0:00:05  0:00:05 --:--:-- 44611
no crontab for root
no crontab for root

进度  3/17 : 初始化Nginx申请证书配置 

请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:xxx

 ---> 配置Nginx 

检查IP是否设置为当前VPS 
 ---> 检查ipv4中 

当前域名的IP为 [xxx (2a02:180:]，是否正确[y/n]？y

 ---> IP确认完成 

检查Nginx是否正常访问 

 ---> Nginx配置成功 

进度  4/17 : 申请TLS证书
 
 ---> 安装TLS证书 
[Mi 20. Jan 09:12:08 CET 2021] all.baotong.cf:Verify error:Fetching http://xxx/.well-known/acme-challenge/oEw_hzx_YstyyrFbiM9QkxTADAe_v6VtaYrrIHe1YD8: Connection refused
[Mi 20. Jan 09:12:09 CET 2021] Please add '--debug' or '--log' to check more details.
[Mi 20. Jan 09:12:09 CET 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh/xxx_ecc/fullchain.cer: Datei oder Verzeichnis nicht gefunden
 ---> TLS安装失败，请检查acme日志 
root@all:~#

**Comment by mack-a** [comment]
> 在EUSERV上使用Debian 10全新系统，并升级最新补丁apt-get update && apt-get upgrade -y 后，安装还是失败。其提示如下：
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> ---> 安装curl
> ---> 安装unzip
> ---> 安装socat
> ---> 安装jq
> ---> 安装binutils
> ---> 安装qrencode
> ---> 安装nginx
> ---> 安装semanage
> ---> 安装sudo
> ---> 安装acme.sh
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 202k 100 202k 0 0 35109 0 0:00:05 0:00:05 --:--:-- 44611
> no crontab for root
> no crontab for root
> 
> 进度 3/17 : 初始化Nginx申请证书配置
> 
> 请输入要配置的域名 例：blog.v2ray-agent.com --->
> 域名:xxx
> 
> ---> 配置Nginx
> 
> 检查IP是否设置为当前VPS
> ---> 检查ipv4中
> 
> 当前域名的IP为 [xxx (2a02:180:]，是否正确[y/n]？y
> 
> ---> IP确认完成
> 
> 检查Nginx是否正常访问
> 
> ---> Nginx配置成功
> 
> 进度 4/17 : 申请TLS证书
> 
> ---> 安装TLS证书
> [Mi 20. Jan 09:12:08 CET 2021] xxx:Verify error:Fetching http://xxx/.well-known/acme-challenge/oEw_hzx_YstyyrFbiM9QkxTADAe_v6VtaYrrIHe1YD8: Connection refused
> [Mi 20. Jan 09:12:09 CET 2021] Please add '--debug' or '--log' to check more details.
> [Mi 20. Jan 09:12:09 CET 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
> cat: /root/.acme.sh/xxx_ecc/fullchain.cer: Datei oder Verzeichnis nicht gefunden
> ---> TLS安装失败，请检查acme日志
> root@all:~#

最新的脚本吗

**Comment by AndersonGhost** [comment]
是啊

**Comment by mack-a** [comment]
> 是啊

https://github.com/mack-a/v2ray-agent/releases/tag/v2.3.5 修了
