### ISSUE TITLE
acme安装失败

### ISSUE THREAD

**Issue by suifeng66** [mack-a/v2ray-agent#821]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
acme安装失败

## 2.安装失败的log或者
![image](https://github.com/mack-a/v2ray-agent/assets/18163368/e68c1378-fd35-4915-a3e4-343b46447061)
截图

## 3.系统版本
Linux coderbookclub.xyz 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
## 4.脚本版本
v2.11.9

**Comment by suifeng66** [comment]
老是提示 acme安装失败

**Comment by mack-a** [comment]
curl -s https://get.acme.sh | sh 手动执行一下此命令
