### ISSUE TITLE
ghproxy无法使用+sing-box无法更新

### ISSUE THREAD

**Issue by sound99** [mack-a/v2ray-agent#822]
1、 clash meta下载订阅，无法拉取provider rule。
install.sh代码中规则网址使用的是ghproxy。ghproxy已经挂了有段时间了，无法连接。
install.sh原文代码引用如下：
rule-providers:
lan:
type: http
behavior: classical
interval: 86400
url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
path: ./Rules/lan.yaml

2、无法更新sing-box至稳定版。

初始安装为1.5.3，但是始终无法检测到最新稳定版，选择17内核更新后只会检测到当前使用版本为最新版本，手动替换内核为1.6.0，1.6.1——1.6.3后，再选择更新singbox内核，检测到最新版本为当前使用版本。

![image](https://github.com/mack-a/v2ray-agent/assets/28331473/08eeb38f-a09e-437c-9bd6-e09fdbdc46c8)
第一次检测,此时最新版本为1.6.2,但是只能检测到当前版本1.6.1
![image](https://github.com/mack-a/v2ray-agent/assets/28331473/e360ddd5-3b65-40a0-b705-be757c5fa25e)
手动更新至1.6.2
![image](https://github.com/mack-a/v2ray-agent/assets/28331473/5f417a76-8747-45c3-9f17-1a00b4980e14)
此时提示最新版本为当前1.6.2

**Comment by mack-a** [comment]
tg联系 @mackaff
