### ISSUE TITLE
任意门分流，对Tuic协议无效

### ISSUE THREAD

**Issue by yt1988** [mack-a/v2ray-agent#823]
## 1.问题描述

两台VPS任意门分流，。用途是流媒体落地解锁

发现任意门分流对Tuic协议无效，Torjan、Vless正常

## 2.安装失败的log或者截图

无

## 3.系统版本

Debain 12

## 4.脚本版本

2.11.11

**Comment by mack-a** [comment]
目前不支持，请等待后续更新

**Comment by yt1988** [comment]
> 目前不支持，请等待后续更新

收到，后续实现了，需要重装么，还是说双边重新配置任意门即可
