### ISSUE TITLE
按照教程安装了这个脚本获取的节点都无法使用

### ISSUE THREAD

**Issue by Pd1021** [mack-a/v2ray-agent#824]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
2023/11/11 18:49:46 [Warning] [2573970633] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [read tcp 192.168.1.10:59504->142.171.220.3:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.10:59505->142.171.220.3:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.10:59506->142.171.220.3:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.10:59507->142.171.220.3:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.10:59508->142.171.220.3:443: wsarecv: An existing connection was forcibly closed by the remote host.] > common/retry: all retry attempts failed
按照教程安装了这个脚本获取的节点都无法使用
防火墙已关闭

## 2.安装失败的log或者截图
![QQ截图20231111185002](https://github.com/mack-a/v2ray-agent/assets/122723864/104f11f4-ed3f-4d42-aec5-b7865db97d05)
## 3.系统版本
centos 9
## 4.脚本版本
目前最新版本

**Comment by mack-a** [comment]
添加一个新端口试一下，并且参考这个教程，https://www.v2ray-agent.com/archives/1684115970026排查一下。
