### ISSUE TITLE
可以增加多域名管理

### ISSUE THREAD

**Issue by MaoMichael** [mack-a/v2ray-agent#828]
**详细描述建议的内容**
证书管理处可以加一个：添加域名，删除域名（默认域不能删除），强制更新TLS证书，TLS证书清单，删除TLS证书等功能。

用这个的老板本，手动增加若干个域，也有泛解析，挺好，以后不怕被和谐了。不行就换个域，SO EASY。

**Comment by mack-a** [comment]
使用场景有限
