### ISSUE TITLE
最新版本脚本安装BBR

### ISSUE THREAD

**Issue by FanXinShi233** [mack-a/v2ray-agent#831]
## 1.问题描述
多台VPS均出现此问题，应该为BUG或下载源头出现问题
## 2.安装失败的log或者截图
<img width="628" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/150363148/7b91de61-0af3-4935-ab44-18661bc3b075">

## 3.系统版本
centos7

## 4.脚本版本
最新版本

**Comment by mack-a** [comment]
再试试，现在应该是修复了
