### ISSUE TITLE
Reality偷自己报错

### ISSUE THREAD

**Issue by LReion** [mack-a/v2ray-agent#832]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
原来直接使用脚本偷自己报错
## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/78899198/ecf6dfb8-e066-41fa-a536-bef6150615e7)

## 3.系统版本
Debian10
## 4.脚本版本
当前版本：v2.11.14

## 可能的解决方法
最近更新了Reality Scan之后我发现我通过默认脚本搭建的ALPN是http1.1，这可能就是Reality偷自己报错的原因。但是我水平有限，不会改。
![image](https://github.com/mack-a/v2ray-agent/assets/78899198/287bef68-1568-4b77-866d-7a28bc011110)

**Comment by NoRRt** [comment]
Yes, I have this problem

**Comment by 7980963** [comment]
同样遇到这个问题，我补充一下，貌似在电信宽带网络下这种问题比较可能出现

**Comment by LReion** [comment]
我用的是移动，我感觉报错的原因应该是ALPN不是H2。

**Comment by LReion** [comment]
> 端口是正常的，因为TCP+Vision还有WS都能正常工作。 我用的是移动，我感觉报错的原因应该是ALPN不是H2。Reality的最低要求是TLS1.3和H2。 搭建的伪装网站自己扫出来ALPN是http1.1的，我感觉是因为这个报错。然后导致DialTLSContext。 也就是说我确实偷了自己的网站，但自己的网站搭建的伪装也不是http2的，所以会报这个错。

然后我发现如果用宝塔面板申请过证书的网站就是h2了，偷自己就不会报错DialTLS了
