### ISSUE TITLE
希望hysteria2支持伪装

### ISSUE THREAD

**Issue by gungnirayu** [mack-a/v2ray-agent#833]
**详细描述建议的内容**
hysteria2确实快，我看原文档支持伪装，而且是他的核心功能之一，但是看咱们生成的配置里并没有这一项，希望今后可以考虑支持：
<details><summary>Details</summary>
<p>

伪装 (Masquerade)
Hysteria 抵抗审查的关键之一就是它能伪装成标准的 HTTP/3 流量。这意味着数据包不仅对中间设备（middleboxes）看起来像是 HTTP/3，服务器还会像普通网站服务器一样真的响应 HTTP 请求。然而，这意味着你的服务器必须实际提供一些内容，以便看起来是真实的。

如果审查不是你需要担心的问题，可以从配置文件中完全删除 masquerade 部分。这种情况下，Hysteria 将对所有 HTTP 请求始终返回 404 Not Found 。

目前 Hysteria 提供以下几种伪装模式：

file：作为一个静态文件服务器，从一个目录提供内容。
proxy：作为一个反向代理，从另一个网站提供内容。
string：返回一个固定的字符串。

masquerade:
  type: proxy
  file:
    dir: /www/masq 
  proxy:
    url: https://some.site.net 
    rewriteHost: true 
  string:
    content: hello stupid world 
    headers: 
      content-type: text/plain
      custom-stuff: ice cream so good
    statusCode: 200 

</p>
</details>

**Comment by mack-a** [comment]
404就够用了
