### ISSUE TITLE
TUIC订阅格式不兼容NekoRay

### ISSUE THREAD

**Issue by iseku** [mack-a/v2ray-agent#834]
## 1.问题描述
NekoRay添加订阅获取的TUIC配置会丢失password，其它协议没有问题，查看 /etc/v2ray-agent/subscribe_local/default 下的原始配置信息与NekoRay导出的链接做比对，发现格式存在差异：
_v2ray-agent的格式：_
tuic://[uuid]@[host]:[port]?peer=[host]&congestion_control=bbr&password=[uuid]&insecure=0&sni=[sni]&alpn=h3#[name_tag]
_NekoRay导出的格式：_
tuic://[uuid]:[password]@[host]:[port]?congestion_control=bbr&alpn=h3&sni=[sni]&udp_relay_mode=quic&allow_insecure=0#[name_tag]

另外看账号管理的配置输出，TUIC的password是直接使用的uuid，并没有读取配置中真实的password，分析原因是脚本自动生成的配置两者是相同的，配置输出时就默认password=uuid了，试了下修改配置中的password也没用。

目前支持tuic配置直接导入的客户端不多，不知道默认格式是支持的哪个，希望能增加对NekoRay的支持，谢谢！

## 3.系统版本
Ubuntu 22.04.3 LTS
## 4.脚本版本
v2.11.14

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.15

**Comment by iseku** [comment]
新发布的v2.11.15没有修复tuic password的问题，我这边是因为要使用以前自己定义的密码，不能用uuid代替，所以尝试自己修改了脚本来满足需要，另外还增加了tuic的通用链接，经测试没有问题。请你们审核一下，合并到新版本中，谢谢。
[tuic_fix.zip](https://github.com/mack-a/v2ray-agent/files/13392741/tuic_fix.zip)
