### ISSUE TITLE
aws没用公网ipv4 只有ipv6 能平通 域名也配置好了 执行后 不能访问外网报错

### ISSUE THREAD

**Issue by gongyuan303** [mack-a/v2ray-agent#835]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
aws没用公网ipv4 只有ipv6 能平通 域名也配置好了 执行后 不能访问外网报错
## 2.安装失败的log或者截图
安装成功
运行使用软件翻墙,访问google.com 报错
2023/11/17 16:16:28 [Warning] core: Xray 1.6.4 started
2023/11/17 16:16:29 127.0.0.1:52691 accepted tcp:127.0.0.1:0 [QV2RAY_API_INBOUND -> QV2RAY_API]
2023/11/17 16:16:31 127.0.0.1:52700 accepted //docs.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:31 127.0.0.1:52701 accepted //res.wx.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:33 127.0.0.1:52713 accepted //api.github.com:443 [http_IN >> PROXY]
2023/11/17 16:16:34 127.0.0.1:52722 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:34 127.0.0.1:52723 accepted //github.com:443 [http_IN >> PROXY]
2023/11/17 16:16:34 127.0.0.1:52724 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:34 127.0.0.1:52725 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:34 127.0.0.1:52726 accepted http://get.sogou.com/q [http_IN -> DIRECT]
2023/11/17 16:16:34 127.0.0.1:52728 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:35 127.0.0.1:52729 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:35 127.0.0.1:52734 accepted //suggestion.baidu.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:37 127.0.0.1:52751 accepted //otheve.beacon.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:38 127.0.0.1:52759 accepted //www.google.com:443 [http_IN >> PROXY]
2023/11/17 16:16:40 127.0.0.1:52785 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:16:50 [Warning] [3861340308] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:16:50 127.0.0.1:52841 accepted //api.github.com:443 [http_IN >> PROXY]
2023/11/17 16:16:52 127.0.0.1:52856 accepted //doc.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:52 127.0.0.1:52857 accepted //doc.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:54 127.0.0.1:52869 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:54 127.0.0.1:52870 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:55 [Warning] [1155193178] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:16:55 [Warning] [3380163498] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:16:55 127.0.0.1:52880 accepted //github.com:443 [http_IN >> PROXY]
2023/11/17 16:16:55 127.0.0.1:52881 accepted //www.google.com:443 [http_IN >> PROXY]
2023/11/17 16:16:57 127.0.0.1:52895 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:57 127.0.0.1:52896 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:16:58 127.0.0.1:52901 accepted //cube.weixinbridge.com:443 [http_IN >> PROXY]
2023/11/17 16:16:58 127.0.0.1:52902 accepted //cube.weixinbridge.com:443 [http_IN >> PROXY]
2023/11/17 16:16:59 127.0.0.1:52912 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:17:00 [Warning] [527641426] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:00 127.0.0.1:52924 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:17:06 127.0.0.1:52960 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:17:08 127.0.0.1:52965 accepted http://www.gstatic.com/generate_204 [http_IN >> PROXY]
2023/11/17 16:17:08 127.0.0.1:52971 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:17:11 127.0.0.1:52997 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:17:11 127.0.0.1:52998 accepted //docrp.weixin.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:17:16 [Warning] [596776761] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:18 127.0.0.1:53039 accepted //vscode-sync.trafficmanager.net:443 [http_IN >> PROXY]
2023/11/17 16:17:18 127.0.0.1:53044 accepted //res.wx.qq.com:443 [http_IN -> DIRECT]
2023/11/17 16:17:20 127.0.0.1:53049 accepted //mobile.events.data.microsoft.com:443 [http_IN >> PROXY]
2023/11/17 16:17:21 [Warning] [127771145] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 [Warning] [553992160] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 [Warning] [259848541] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 [Warning] [3753593101] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 [Warning] [2854830320] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 [Warning] [2612749426] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:21 127.0.0.1:53069 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:17:21 127.0.0.1:53070 accepted //cube.weixinbridge.com:443 [http_IN >> PROXY]
2023/11/17 16:17:21 127.0.0.1:53071 accepted //cube.weixinbridge.com:443 [http_IN >> PROXY]
2023/11/17 16:17:22 127.0.0.1:53076 accepted //www.google.com:443 [http_IN >> PROXY]
2023/11/17 16:17:22 127.0.0.1:53077 accepted //www.google.com:443 [http_IN >> PROXY]
2023/11/17 16:17:26 [Warning] [4257320402] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:26 [Warning] [3727360807] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxx.xxx.com/wlodjdjdjvws):  > dial tcp [2600:1f18:3a3:4f00:e7f5:835b:5d2d:5871]:443: connect: no route to host] > common/retry: all retry attempts failed
2023/11/17 16:17:26 [Warning] [4257320402] proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe
2023/11/17 16:17:26 127.0.0.1:53105 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]
2023/11/17 16:17:31 127.0.0.1:53132 accepted //content-autofill.googleapis.com:443 [http_IN >> PROXY]

## 3.系统版本
 Debian 11
## 4.脚本版本
github.com脚本

**Comment by mack-a** [comment]
本地有IPv6吗

**Comment by gongyuan303** [comment]
现在家里有了电脑有ipv6 不能用啊 最好用账号的那个链接能链接上

**Comment by gongyuan303** [comment]
客户端用的是v2rayN.exe

**Comment by gongyuan303** [comment]
[transport/internet/grpc: failed to dial Grpc > transport/internet/grpc: Cannot dial grpc > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup vpn.osrpa.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."] > common/retry: all retry attempts failed

**Comment by rammiah** [comment]
你的vps域名地址解析失败了，直接换成ip试试？

**Comment by gongyuan303** [comment]
> 你的vps域名地址解析失败了，直接换成ip试试？

ipv4和ipv6 都设置了，没问题 能用。就是单独开通ipv6没通

**Comment by tmnt2009** [comment]
同样是AWS，怎么设置才能不消耗DataTransfer-Regional-Bytes流量，一消耗这个流量就是要钱。。。
