### ISSUE TITLE
给使用者一个提醒，关于卸载warp【第三方 IPv4】后，sing-box无法启动

### ISSUE THREAD

**Issue by kaishi961125** [mack-a/v2ray-agent#836]
在同步使用sing-box和 WARP分流【第三方 IPv4】 后一切正常

卸载WARP分流【第三方 IPv4】 后，singbox无法启动，

提示：read config at /etc/v2ray-agent/sing-box/conf/config.json: open /etc/v2ray-agent/sing-box/conf/config.json: no such file or directory

sing-box外其他协议无问题

![image](https://github.com/mack-a/v2ray-agent/assets/81787436/f33ce0ff-930d-4a0d-b1aa-aa71ef628349)

解决方案：卸载重新安装
![image](https://github.com/mack-a/v2ray-agent/assets/81787436/fcea29b9-b295-435f-b880-d4fbb38dcc0e)

VPS：甲骨文 ARM 4+24    ubuntu 20.4

脚本版本：v2.11.14

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.16
