### ISSUE TITLE
修复tuic password值不能导出的问题

### ISSUE THREAD

**Issue by iseku** [mack-a/v2ray-agent#837]
新发布的v2.11.15没有修复tuic password的问题，我这边是因为要使用以前自己定义的密码，不能用uuid代替，所以尝试自己修改了脚本来满足需要，另外还增加了tuic的通用链接，经测试可正常使用。请你们审核一下，如果没问题的可以合并到新版本中，谢谢。
[tuic_fix.zip](https://github.com/mack-a/v2ray-agent/files/13392741/tuic_fix.zip)

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.16
