### ISSUE TITLE
p2p怎样通过v2ray-agent穿透?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [mack-a/v2ray-agent#838]
## 1.问题描述
本机使用了btsync，由于连不上服务器，所以在btsync中设置了代理。代理是本机V2rayN客户端的端口。
目前的情况是使用代理上网正常，但是btsync还是连不上服务器。
![image](https://github.com/mack-a/v2ray-agent/assets/12248166/9a002db9-a2b0-422f-a292-48929e4386cb)

下面是btsync的代理设置。
![image](https://github.com/mack-a/v2ray-agent/assets/12248166/e25bd6f9-c7df-4092-9075-b6f0e8a02e6f)

## 2.安装失败的log或者截图
安装正常。

## 3.系统版本
win10

## 4.脚本版本
9月份安装的，不知道在哪看版本

**Comment by mack-a** [comment]
不了解
