### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by aaa2550** [mack-a/v2ray-agent#839]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
安装到生成key后报错
## 2.安装失败的log或者截图
请输入[回车]使用随机:

 ---> 回落域名: download-installer.cdn.mozilla.net:443

 ---> 客户端可用域名: "download-installer.cdn.mozilla.net"

========================== 生成key ==========================

 privateKey:qByZfotKuMMFwVll19oknf6_JT6FAzmNNc-bWWie_HU

 publicKey:xnJ9V7GOWl29XOIQrAKqC5eaRr7rsWYP-KcKjha61kM
 ---> Xray关闭成功
Xray启动失败
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈
root@541ac404d089:/# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)
A unified platform for anti-censorship.
2023/11/19 10:50:25 Using confdir from arg: /etc/v2ray-agent/xray/conf
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json] appended inbound with tag: VLESSReality
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/08_VLESS_reality_fallback_grpc_inbounds.json] appended inbound with tag: VLESSRealityGRPC
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/09_routing.json
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: IPv4_out
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: IPv6_out
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: direct
2023/11/19 10:50:25 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: blackhole_out
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
2023/11/19 10:50:25 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/12_policy.json
## 3.系统版本
mac里按的ubuntu的docker，在docker中运行的
## 4.脚本版本
v2.11.18

**Comment by mack-a** [comment]
看日志没有发现很明显的问题，建议手动启动一下。如果启动失败，建议重新安装。如果重新安装还不可以可能是不兼容
