### ISSUE TITLE
NAT VPS 无法检测端口，导致无法正常安装

### ISSUE THREAD

**Issue by yt1988** [mack-a/v2ray-agent#841]
## 1.问题描述

NAT VPS 无法检测端口，导致无法正常安装

端口已开放，连接正常

看到之前有同学反馈，应该是没有修复

https://github.com/mack-a/v2ray-agent/issues/663

## 2.安装失败的log或者截图

![WX20231122-125755@2x](https://github.com/mack-a/v2ray-agent/assets/4963078/cfbe8b70-0535-4da6-8f40-fc33865e2770)

## 3.系统版本

Debian 12

## 4.脚本版本

当前版本：v2.11.19

**Comment by mack-a** [comment]
目前不支持nat安装

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.11.20
