### ISSUE TITLE
Trojan ERR_SSL_PROTOCOL_ERROR 错误

### ISSUE THREAD

**Issue by LouisTay** [mack-a/v2ray-agent#842]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

之前一直用的Trojan，一直都正常。当时脚本是2.10.几。

今天更新了下脚本到2.11.19，重启 Xray，然后节点就一直 ERR_SSL_PROTOCOL_ERROR 了，尝试过重新安装、重启后重新安装、重装系统后重新安装、换不同的机器重新安装、换证书申请方式、切换Xray到1.8.4（我看最新版脚本用的是1.8.6），一直都是 ERR_SSL_PROTOCOL_ERROR 报错。

客户端是 Clash X Pro 以及 Clash for windows，都是这个报错。

## 2.安装失败的log或者截图

<img width="614" alt="截屏2023-11-22 16 56 46" src="https://github.com/mack-a/v2ray-agent/assets/89720279/76131179-1dc2-420f-a3a8-4a20201401db">

log 遇到过，但忘记截图了：

```
app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: no certificates configured
```

然后目前看到的 log ：

<img width="765" alt="截屏2023-11-22 17 00 10" src="https://github.com/mack-a/v2ray-agent/assets/89720279/39a4967d-1a1b-4d61-a5fe-2ea7b75ec058">

## 3.系统版本

Ubuntu 22.04

## 4.脚本版本

latest：2.11.19

**Comment by mack-a** [comment]
你本地的sni可能写的不对，检查一下。换手机客户端试一下

**Comment by LouisTay** [comment]
我看 手机 QX 确实可以，很奇怪。电脑上 Clash 还是不行。

检查了下 Clash 配置的 sni，和前面节点的域名是一样的。这些配置都是直接复制的脚本生成的，然后做了下订阅转换，应该不会有错吧。

刚拿了台新机器，换了个域名，重新装了下，然后 Clash 那边使用还是 ERR_SSL_PROTOCOL_ERROR。

接下来应该怎么排查呢😂

**Comment by mack-a** [comment]
你试试用clashverge的clashmeta内核是否正常使用 参考教程 https://www.v2ray-agent.com/archives/1695534611317#heading-1

**Comment by LouisTay** [comment]
我看了下代码，https://github.com/mack-a/v2ray-agent/commit/46b929a77bfa68092d5c2772f913342bf86e3383#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44f

我把配置文件改为这个 commit 前原来的 tlsSettings，就没问题了：

```
"tlsSettings": {
    "minVersion": "1.2",
    "alpn": [
      "http/1.1",
      "h2"
    ],
```

这个会有啥影响吗

**Comment by mack-a** [comment]
https://xtls.github.io/config/transport.html#tlsobject 大概率是客户端的锅 默认是h2，如果客户端没指定的话可能会报错，本地客户端手动指定一下alpn

**Comment by yuantanglong** [comment]
> https://xtls.github.io/config/transport.html#tlsobject 大概率是客户端的锅 默认是h2，如果客户端没指定的话可能会报错，本地客户端手动指定一下alpn

在哪知道 如何指定alpn小白不太懂 麻烦说明一下
