### ISSUE TITLE
添加一个自动更新到最新内核的功能（保持永远最新）

### ISSUE THREAD

**Issue by demonyins** [mack-a/v2ray-agent#843]
**详细描述建议的内容**

进度  1/1 : Xray版本管理 
============================================================== 
1.升级Xray-core 
2.升级Xray-core 预览版 
3.回退Xray-core 
4.关闭Xray-core 
5.打开Xray-core 
6.重启Xray-core 
7.更新geosite、geoip 
8.设置自动更新geo文件[每天凌晨更新] 
_9.在这里添加一个自动更新到最新内核的功能（保持永远最新）_
==============================================================

**Comment by mack-a** [comment]
这个也不会，还是那个理由。会导致无法使用

**Comment by laaArmy** [comment]
一键自动炸机是吧

**Comment by yzx1208** [comment]
慌什么！
