### ISSUE TITLE
Ubuntu 16.04.7 LTS  无法安装

### ISSUE THREAD

**Issue by ajf12f** [mack-a/v2ray-agent#845]
## 1.问题描述
无法安装

## 2.安装失败的log或者截图

Linux version 4.4.0-210-generic (buildd@lgw01-amd64-009) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 3.系统版本

Ubuntu 16.04.7 LTS 

## 4.脚本版本
 wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by mack-a** [comment]
用ubuntu20+或者debian10+
