### ISSUE TITLE
建议除了伪装网站，提供“个人网盘伪装选项”和“403报错选项”

### ISSUE THREAD

**Issue by waitandsoon** [mack-a/v2ray-agent#85]
引自：https://github.com/kirin10000/Xray-script

“自建VPS使用Xray进行代理的流量特征有 单点性 、 大流量性 和 出入相同性 。单点性 指使用的人少，一般只有自己，即使分享给朋友，一般也不会太多。出入相同性 指入VPS和出VPS的流量在时间和大小上几乎相同，比如使用Xray代理浏览BiliBili，从BiliBili到VPS(Xray服务端)的流量，和从VPS到Xray客户端的流量在时间上和大小上是几乎相同的。出入相同性 是所有代理的通病，目前还没有太好的伪装方法。
目前最符合这几个特征的伪装网站就是个人网盘。个人网盘可以理解为使用自己的VPS搭建起来的百度网盘，区别就是文件都存放在VPS中，并且自己是网盘的管理员。
网盘可以自己用，也可以分享给几个人用，甚至可以商用，无论用户多少都合理，符合 单点性 和 大流量性 。
许多脚本使用博客网站伪装，实际上博客网站往往提供给很多人浏览，并且流量不是很大，与 单点性 和 大流量性 相悖。”

**Comment by mack-a** [comment]
这需求别人以前提过，网盘这个东西确实很符合大流量场景，但是有一个问题，因为网盘是可以放一些资源，这些资源包含版权资源、敏感资源，如果多人分享是否有考虑过涉及到敏感资源，而导致涉及到审查的问题，当然这种小站点一般gfw也不会管。这种风险，你认为这种风险大，还是收益大一点。

**Comment by mack-a** [comment]
这需求别人以前提过，网盘这个东西确实很符合大流量场景，但是有一个问题，因为网盘是可以放一些资源，这些资源包含版权资源、敏感资源，如果多人分享是否有考虑过涉及到敏感资源，而导致涉及到审查的问题，当然这种小站点一般gfw也不会管。这种风险，你认为这种风险大，还是收益大一点。

**Comment by mack-a** [comment]
其实伪装也没啥用

**Comment by mack-a** [comment]
> 引自：https://github.com/kirin10000/Xray-script
> 
> “自建VPS使用Xray进行代理的流量特征有 单点性 、 大流量性 和 出入相同性 。单点性 指使用的人少，一般只有自己，即使分享给朋友，一般也不会太多。出入相同性 指入VPS和出VPS的流量在时间和大小上几乎相同，比如使用Xray代理浏览BiliBili，从BiliBili到VPS(Xray服务端)的流量，和从VPS到Xray客户端的流量在时间上和大小上是几乎相同的。出入相同性 是所有代理的通病，目前还没有太好的伪装方法。
> 目前最符合这几个特征的伪装网站就是个人网盘。个人网盘可以理解为使用自己的VPS搭建起来的百度网盘，区别就是文件都存放在VPS中，并且自己是网盘的管理员。
> 网盘可以自己用，也可以分享给几个人用，甚至可以商用，无论用户多少都合理，符合 单点性 和 大流量性 。
> 许多脚本使用博客网站伪装，实际上博客网站往往提供给很多人浏览，并且流量不是很大，与 单点性 和 大流量性 相悖。”

个人网盘的有些麻烦 以后实在是闲的没事干的时候 研究一下
