### ISSUE TITLE
启用cloudflare后，clashmeta订阅链接无法使用

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#850]
## 1.问题描述
#849 
大佬，我没明白。。。关闭云朵也是不行的呀。还有你说的这个使用直连模式进行更新，我试过了也不行呀

**Comment by bettswang** [comment]
关闭云朵的状态下，我卸载脚本后，重新安装测试，在没有启用cloudflare 自选IP的情况，只要安装了Hysteria2和Tuic，就会触发clashmeta订阅无法更新到节点信息。

**Comment by mack-a** [comment]
有空我看下

**Comment by mack-a** [comment]
有具体的复现步骤吗，clashverge的clashmeta内核版本是否是1.16版本

**Comment by bettswang** [comment]
环境：
服务器 ubuntu20.04 
脚本 v2.11.21

客户端 windows10
软件 clashverge v1.3.3 clashmeta内核 v1.15.0

cloudflare设置
未开启云朵 仅DNS
TLS/SSL 完全模式
未进行优选IP在服务器上或者软件终端上


复现步骤：
1. 在运行卸载脚本后，下载mack-a的脚步，选择2-1-047，输入域名，端口8443，其他全默认。完成后，查看订阅链接，此时clashmeta的订阅链接在clashverge上可以被更新，节点信息成功下载。
2. 然后安装Hysteria2，重新生成新的订阅链接后，此时clashmeta的订阅链接在clashverge软件终端，下载节点信息是空。
3. 最后卸载掉Hysteria2，重新生成新的订阅链接，此时clashmeta的订阅在clashverge软件终端，又可以成功拉取到节点信息。

**Comment by bettswang** [comment]
但是我之前域名没挂cloudflare进行dns解析时，Hysteria2和tuic安装后，重新生成新的clashmeta链接，在clashverge软件上是可以正常下载到节点信息的。

**Comment by mack-a** [comment]
你把clashmeta的内核更新到1.16就可以了 替换内核教程 https://www.v2ray-agent.com/archives/1697166382492
