### ISSUE TITLE
现在Hysteria2 的warp的分流无效了，即使设置了分流，所有流量也会直连

### ISSUE THREAD

**Issue by dogpem** [mack-a/v2ray-agent#853]
现在Hysteria2 的warp的分流无效了，即使设置了分流，所有流量也会直连
复现步骤：
1. 卸载重新安装`v2ray-agent`
2. 安装`Hyteria 2`
3. 选择 `11.分流工具` > `1.WARP分流` > `2.添加域名 `>`安装warp-reg - y` > `请按照上面示例录入域名:ip.sb`  > ` ---> 添加成功 
 ---> Xray关闭成功 
 ---> Xray启动成功 
 ---> sing-box关闭成功 
 ---> sing-box启动成功 `
4. 查看IP
![image](https://github.com/mack-a/v2ray-agent/assets/115675753/0fdca0f8-e92c-4e29-878d-85a3b63fa79a)

Sing-Box Config
```
 "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "direct",
      "tag": "wireguard_out_IPv4",
      "detour": "wireguard_out",
      "domain_strategy": "ipv4_only"
    },
    {
      "type": "wireguard",
      "tag": "wireguard_out",
      "local_address": [
        "172.16.0.2/32",
        "2606:4700:110:8535:788c:3bc4:6287:5063/128"
      ],
      "private_key": "xxx",
      "server": "162.159.192.1",
      "server_port": 2408,
      "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
      "reserved": "3woB",
      "mtu": 1280
    }
  ],
  "route": {
    "geosite": {
      "path": "/etc/v2ray-agent/sing-box/conf/geosite.db"
    },
    "rules": [
      {
        "domain": [
          "ip.gs",
          "ip.sb"
        ],
        "outbound": "wireguard_out_IPv4"
      }
    ]
  }
}
```

_Originally posted by @dogpem in https://github.com/mack-a/v2ray-agent/issues/851#issuecomment-1836629135_

**Comment by AiraNadih** [comment]
> 你设置 ipv4.ip.gs分流，他是正确的。你设置的ip.gs，分流就只会对当前域名有效

能否提供更详细的说明？我实际测试了 "scholar.google.com"，也没有生效：
```
...
"rules": [
      {
        "domain": ["scholar.google.com"],
        "outbound": "wireguard_out_IPv4"
      }
]
...
```

这里不能简单地用 `ipv4.scholar.google.com` 替换吧？

目前最新版对 Xray 的 wrap 分流是没问题的，而 sing-box 的 wrap 分流问题并没有修复。

**Comment by mack-a** [comment]
不修了，180这个功能废弃了

**Comment by mack-a** [comment]
他这个domain是精确匹配，你可以看日志到底是请求的什么域名，然后把那个域名加入到domain即可

**Comment by AiraNadih** [comment]
> 不修了，180这个功能废弃了

好像没废弃吧。

还是上面那个配置，我在 NekoBox for Android 上能生效，而 PC 上的 nekoray 不行。
我也是刚才想起来试了下，才发现的。

后来看了下服务器上的日志，发现 nekoray 发送请求直接是 IPv4 地址，而不是域名，所以服务器没匹配到域名规则。
不是很清楚 sing-box 的配置规则，我想大概是 DNS 相关的部分的配置原因？

**Comment by mack-a** [comment]
> > 不修了，180这个功能废弃了
> 
> 好像没废弃吧。
> 
> 还是上面那个配置，我在 NekoBox for Android 上能生效，而 PC 上的 nekoray 不行。 我也是刚才想起来试了下，才发现的。
> 
> 后来看了下服务器上的日志，发现 nekoray 发送请求直接是 IPv4 地址，而不是域名，所以服务器没匹配到域名规则。 不是很清楚 sing-box 的配置规则，我想大概是 DNS 相关的部分的配置原因？
> 
> UPDATE: 确定是 TUN 模式下的问题了。

https://sing-box.sagernet.org/configuration/route/geosite/

**Comment by AiraNadih** [comment]
> > > 不修了，180这个功能废弃了
> > 
> > 
> > 好像没废弃吧。
> > 还是上面那个配置，我在 NekoBox for Android 上能生效，而 PC 上的 nekoray 不行。 我也是刚才想起来试了下，才发现的。
> > 后来看了下服务器上的日志，发现 nekoray 发送请求直接是 IPv4 地址，而不是域名，所以服务器没匹配到域名规则。 不是很清楚 sing-box 的配置规则，我想大概是 DNS 相关的部分的配置原因？
> > UPDATE: 确定是 TUN 模式下的问题了。
> 
> https://sing-box.sagernet.org/configuration/route/geosite/

但是这个和当前的 issue 无关吧。根据 sing-box 文档中 [Route Rule](net.org/configuration/route/rule/) 这部分的信息来看，当 sing-box 升级到 1.8.0 或更高版本时，我们还是可以使用 `route > rules > domain` 这种配置方式。就像这样：

...
"rules": [
      {
        "domain": ["scholar.google.com"],
        "outbound": "wireguard_out_IPv4"
      }
]
...

实际上，上述配置是有效的。但在 nekoray 的 tun 模式下，DNS 请求被拦截并直接转换为 IP 地址，这才导致了配置未能发挥预期作用。不过，我不确定我所描述的情况是否和 @dogpem 的情况相同。

我只能确定的是，之前的 af082db 提交仍然可以继续进行修改。
