### ISSUE TITLE
I keep getting this error message 

### ISSUE THREAD

**Issue by mehradraissi** [mack-a/v2ray-agent#854]
hi, 
I keep getting this error message 

Xray启动失败 请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈

what should I do ? 
thank you

**Comment by mack-a** [comment]
run 
```
/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
```
