### ISSUE TITLE
直连模式失效

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#855]
## 1.问题描述
客户端上面测试直连模式失效，但是切换到另一个机场订阅，是正常的。
## 2.安装失败的log或者截图
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/cd27c466-1aeb-41ca-8372-b749f73c36ad)

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v2.11.22

**Comment by bettswang** [comment]
补充，直连模式下，还是可以访问谷歌

**Comment by mack-a** [comment]
clashmeta的核心版本是哪一个

**Comment by bettswang** [comment]
v1.16.0

**Comment by mack-a** [comment]
经过测试没有发现此问题，重启一下客户端试一下

**Comment by bettswang** [comment]
重启还是有呀

**Comment by bettswang** [comment]
顺便问下，脚本更新，我在现有的基础上更新完成后，需要重新安装吗？

**Comment by bettswang** [comment]
客户端是clashverge v1.3.8

**Comment by bettswang** [comment]
这个测试链接能不能自己修改？我怀疑是不是本地网络，访问不了。

**Comment by bettswang** [comment]
同一个客户端，在同一时刻，切换不同订阅，其他订阅是可以测试这个direct的延迟的。所以我在想是不是测试链接是不同的。
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/29d6e40a-f464-4735-967d-672c45872cc2)

**Comment by mack-a** [comment]
可以尝试修改一下试试，我自己测试没发现问题
