### ISSUE TITLE
v2.11.22 trojan 证书失败

### ISSUE THREAD

**Issue by yumaoss** [mack-a/v2ray-agent#856]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

2.11.22版本安装trojan，没有选择使用dns申请证书，使用默认的结果显示生成证书成功，实际节点不能连接，打开默认站点 提示没有证书

18版本正常

**Comment by bettswang** [comment]
那客户端没办法修改alpn兼容h2,http1.1吗？
