### ISSUE TITLE
脚本更新问题

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#857]
## 1.问题描述
请问下，脚本有更新版本的情况，是在现有的脚本上直接更新就行了？还是要重新部署？
vasma->17就可以了吗？还是还要重新生成订阅？

**Comment by mack-a** [comment]
中间的版本号变动则需要重新安装，第三位的版本号变动得需要看具体的变动日志。比如v2.11.24则需要重新生成订阅
