### ISSUE TITLE
经本人实测不开启云朵也能用CDN的方案！！

### ISSUE THREAD

**Issue by likefu40** [mack-a/v2ray-agent#86]
开启cloudflare.comDNSSEC
DNSSEC 可抵御伪造的 DNS 应答。受 DNSSEC 保护的区域将通过密码进行签名，以确保收到的 DNS 记录与域所有者发布的 DNS 记录相同。
在没有开启云朵时，也能用优选IP域名伪装

**Comment by mack-a** [comment]
README有写 不让开云朵

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/blob/master/documents/optimize_V2Ray.md
