### ISSUE TITLE
使用trojan_tcp进行代理时，发现YouTube(app/web)无法登录访问

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#861]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
如题，但是可以访问谷歌，facebook等其他被墙的网站
## 2.安装失败的log或者截图
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/79682c3b-e20d-4a81-a9db-a0ef5e0cfd3f)
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/19f00893-773f-4d5f-b3f2-b731e924e7ea)

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v2.11.24

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/856
