### ISSUE TITLE
vps订阅合成问题

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#862]
## 1.问题描述
有个疑惑想请教下大佬。
vps订阅，主vps已经如果有多个用户，次vps多个用户。其中有一个相同的用户名在二者上面。
我这边观察发现：
1.主vps的任意用户的vps订阅都包含添加进去的次vps的订阅(相同用户名的)
2.次vps的多个用户的订阅，为啥也包含了主vps的节点(相同用户名的)？
这不意味着，没办法做用户隔离了吗？

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v2.11.25

**Comment by mack-a** [comment]
用户名不一样，理论上是拉不到的。你现在是能拉到吗

**Comment by mack-a** [comment]
是这样的，主和次是你自己控制的

**Comment by bettswang** [comment]
我只在其中一个添加过订阅

**Comment by bettswang** [comment]
大佬我发现只有clashverge最新版有这个问题？你是否能帮忙看看，是不是内核不支持的原因？内核是nihomo

**Comment by bettswang** [comment]
最新的v3.1.19下，singbox也是订阅合并有问题呀？

**Comment by bettswang** [comment]
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/288ca8dd-c70a-48ae-b95b-94633dc95193)
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/1678493f-a03e-436e-9c18-92f99cff0876)

**Comment by bettswang** [comment]
主节点核心singbox可以添加分节点核心v2ray的订阅，添加不了分节点也是singbox的订阅，查看订阅时会报错

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.21
