### ISSUE TITLE
安装脚本时，卡在生成证书环节

### ISSUE THREAD

**Issue by jinge1984** [mack-a/v2ray-agent#866]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
安装最新脚本时，卡在第4步申请TLS证书环节，不报错，就是很长时间一直没反应。分别用两种生成证书的方式尝试，均是如此。

## 2.安装失败的log或者截图
![证书错误1](https://github.com/mack-a/v2ray-agent/assets/13271298/87e9f0f7-db98-44b2-9e42-9321387d454c)
![证书错误2](https://github.com/mack-a/v2ray-agent/assets/13271298/2de34b99-48c6-40b4-b025-438e4dd105a2)

## 3.系统版本
CentOS 7

## 4.脚本版本
v2.11.25

**Comment by bettswang** [comment]
vps的80，443端口无法被探测通过，估计是安全组还是防火墙挡住了

**Comment by mack-a** [comment]
等待即可，未复现
