### ISSUE TITLE
使用wireguard-go客户端配置双栈warp之后无法首选ipv6出站

### ISSUE THREAD

**Issue by DN3207** [mack-a/v2ray-agent#870]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
安装Xray后，以wireguard-go配置warp，在出站时设置ipv6优先，但没有作用
必须手动以ipv6地址形式访问
## 3.系统版本
AlmaLinux 8.9
## 4.脚本版本
v2.11.25

**Comment by mack-a** [comment]
脚本不支持你说的这个客户端，建议查看Xray文档
