### ISSUE TITLE
Hysteria2不会用，超时用不了！

### ISSUE THREAD

**Issue by e70123456** [mack-a/v2ray-agent#871]
脚本生成的 Hysteria2 TLS [推荐] 链接，在OWT/PassWall上通过链接添加节点，提示“请输入正确的链接”。手动添加有好多选项，按自己理解添加的一直超时，用不了。能否具体地说明一下怎么用？谢谢

**Comment by mack-a** [comment]
更换手机客户端试一下，或者保持你用的客户端的最新版本

**Comment by iamjimmycheng** [comment]
Passwall需要升级到4.7以上
