### ISSUE TITLE
在colocrossing VPS上安装，出现Last-modified header missing -- time-stamps turned off.

### ISSUE THREAD

**Issue by huzy0909** [mack-a/v2ray-agent#872]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
在colocrossing VPS上安装，出现 Last-modified header missing -- time-stamps turned off.提示，换了Debian，Ubuntu，CentOS几个系统后，均相同提示，不知道是什么意思，是否又影响？

## 2.安装失败的log或者截图
安装成功
## 3.系统版本
debian-11-x86_64，目前版本。
## 4.脚本版本
用的稳定版

**Comment by mack-a** [comment]
如果不影响使用，可以不用管。如果影响使用建议dd纯净版系统
