### ISSUE TITLE
任意门必须输入域名,可否不输入域名,完成全部流量中转的需求

### ISSUE THREAD

**Issue by wsnsnsns** [mack-a/v2ray-agent#874]
目前任意门必须输入域名;
如果允许不输入域名的话,就可以完成中转机的需求场景;
可否考虑提供一下这个能力;
或者有别的方法解决中转也是可以的;
谢谢~

当前效果:
`功能 1/1 : 任意门分流 

============================================================== 
# 注意事项 
# 使用教程：https://www.v2ray-agent.com/archives/ba-he-yi-jiao-ben-yu-ming-fen-liu-jiao-cheng 
 
1.添加出站 
2.添加入站 
3.卸载 
请选择:2

功能 1/1 : 任意门添加入站 

============================================================== 
ip录入示例:1.1.1.1,1.1.1.2 
下面的域名一定要和出站的vps一致 
域名录入示例:netflix,openai
 
请输入允许访问该vps的IP:1.1.1.1
请按照上面示例录入域名:
`

**Comment by mack-a** [comment]
任意门已取消，后续socks转发会增加此内容

**Comment by mack-a** [comment]
**v3.1.34** 此版本已支持

wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh

**Comment by wsnsnsns** [comment]
> **v3.1.34** 此版本已支持
> 
> wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh

十分感谢~!
