### ISSUE TITLE
vps订阅合并问题

### ISSUE THREAD

**Issue by snake4009** [mack-a/v2ray-agent#877]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.21
