### ISSUE TITLE
最新的脚本需要卸载重新安装，之前的配置及订阅是不是就要全部失效了？

### ISSUE THREAD

**Issue by Ericwln** [mack-a/v2ray-agent#878]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
最新的脚本需要卸载重新安装，之前的配置及订阅是不是就要全部失效了？

**Comment by mack-a** [comment]
大版本升级，建议卸载后重新安装
