### ISSUE TITLE
3.1.13版本sing-box报错

### ISSUE THREAD

**Issue by laaArmy** [mack-a/v2ray-agent#879]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

sing-box启动失败
请手动执行【/etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json】，查看错误日志

## 2.安装失败的log或者截图

sing-box启动失败
请手动执行【/etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json】，查看错误日志
root@jppro2-202311021034546820fb:~# /etc/v2ray-agent/sing-box/sing-box run -c /etc/v2ray-agent/sing-box/conf/config.json
INFO[0000] router: updated default interface eth0, index 2
TRACE[0000] initializing inbound/vless[VLESSTCP]
INFO[0000] inbound/vless[VLESSTCP]: tcp server started at [::]:443
TRACE[0000] initializing inbound/vless[VLESSReality]
INFO[0000] inbound/vless[VLESSReality]: tcp server started at [::]:18015
TRACE[0000] initializing inbound/vless[VLESSRealityGRPC]
TRACE[0000] closing inbound/vless[0]
TRACE[0000] closing inbound/vless[1]
TRACE[0000] closing inbound/vless[2]
TRACE[0000] closing outbound/direct[0]
TRACE[0000] closing router
TRACE[0000] router: closing transport[0]
TRACE[0000] router: closing interface monitor
TRACE[0000] router: closing network monitor
TRACE[0000] closing log factory
FATAL[0000] start service: initialize inbound/vless[VLESSRealityGRPC]: listen tcp 0.0.0.0:18015: bind: address already in use
root@jppro2-202311021034546820fb:~#

## 3.系统版本

Linux jppro2-202311021034546820fb 6.6.5-x64v3-xanmod1 #0~20231208.g202058e SMP PREEMPT_DYNAMIC Fri Dec  8 15:05:42 UTC x86_64

Debian12.2

## 4.脚本版本

3.1.13

**Comment by mack-a** [comment]
以singbox核心的协议，端口都不可以重复。看报错日志是端口被占用
