### ISSUE TITLE
Reality管理在脚本中被删除

### ISSUE THREAD

**Issue by eclipse9527** [mack-a/v2ray-agent#880]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
Reality管理在脚本中被删除

**Comment by mack-a** [comment]
使用sing-box的自定义安装选择不需要域名的协议即可
