### ISSUE TITLE
最新版本似乎无法保证tuic和h2协议共存

### ISSUE THREAD

**Issue by xj90512** [mack-a/v2ray-agent#881]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
最新版本似乎无法保证tuic和h2协议共存
## 3.系统版本
debian12
## 4.脚本版本
[v3.1.13](https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.13)

**Comment by cifei1** [comment]
同样情况，补个图，先安装的Hysteria2，再安装的tuic
![PixPin_2023-12-23_03-52-11](https://github.com/mack-a/v2ray-agent/assets/108108127/9fa2d7e2-c813-4084-a78b-13664d9fc6d7)

**Comment by mack-a** [comment]
> 同样情况，补个图，先安装的Hysteria2，再安装的tuic ![PixPin_2023-12-23_03-55-08](https://private-user-images.githubusercontent.com/108108127/292579044-4e0eaf92-6f96-4954-8e92-6198f614119b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mjc0MjcsIm5iZiI6MTcwMzQyNzEyNywicGF0aCI6Ii8xMDgxMDgxMjcvMjkyNTc5MDQ0LTRlMGVhZjkyLTZmOTYtNDk1NC04ZTkyLTYxOThmNjE0MTE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxNDEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzFlYWY4OTk0N2JmYjY1N2QwNWY5MGI4Yzk5YzQ5M2I4MjEwMTAyMzZhMzY3NGYzZTEyOTFjOTliN2RhYTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q-Kvr97q9nvC_IHfNf_mVX9xg7KFFkK8r7hCgQezsbA)
> 
> 但是似乎没影响Hysteria2的工作

详细说明一下具体的复现步骤

**Comment by xj90512** [comment]
尝试了下目前最新版本，3.1.15，目前逻辑是不让xray和sing共存了是吗？单独的sing进行自定义协议安装是可以保证h2和tuic共存，但自定义去安装xray，sing又被初始化了，2.x版本，2个核心的协议是可以共存的

**Comment by woodypeckerwho** [comment]
> 同样情况，补个图，先安装的Hysteria2，再安装的tuic ![PixPin_2023-12-23_03-55-08](https://private-user-images.githubusercontent.com/108108127/292579044-4e0eaf92-6f96-4954-8e92-6198f614119b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODM1NjksIm5iZiI6MTcwMzQ4MzI2OSwicGF0aCI6Ii8xMDgxMDgxMjcvMjkyNTc5MDQ0LTRlMGVhZjkyLTZmOTYtNDk1NC04ZTkyLTYxOThmNjE0MTE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwNTQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjhmZGFlZjE4OGJiOTAxOTUxNmRlZjM2N2M2MWY3OTk5MjIyMTVlZThhY2E5OGQ1NGQxMjFmNGRmMzFmZmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8H6yQ6kWhFEloRhMge620OApTWQLJCK_go0fnyvUtIc)
> 
> 但是似乎没影响Hysteria2的工作
遇到类似问题，用一下办法解决：卸载脚本——删除root下.acme.sh目录——重装——问题解决。

**Comment by mack-a** [comment]
> 尝试了下目前最新版本，3.1.15，目前逻辑是不让xray和sing共存了是吗？单独的sing进行自定义协议安装是可以保证h2和tuic共存，但自定义去安装xray，sing又被初始化了，2.x版本，2个核心的协议是可以共存的

可以在xray的基础上安装基于sing-box的hy2和tuic。反过来则不行

**Comment by xj90512** [comment]
尝试过的，无法同时出现h2和tuic，sing的端口信息也只看到一个协议的，所以才感到奇怪，所以目前临时办法在sing-box/config/下面先生成hy2协议的config，然后文件调整为bak，然后再去生成tuic的config，然后把刚才hy2的bak还原，然后重启sing-box服务，可以在排查下。

**Comment by mack-a** [comment]
你描述的情况是 使用xray进行安装后，使用hy2、tuic管理安装后不展示吗

**Comment by xj90512** [comment]
操作顺序：先安装xray后，然后选择01235协议，然后选择4，安装hy2，然后选择6安装tuic，这个时候，hy2就消失了
在已安装协议那里也只显示最新安装的tuic而不是hy2和tuic。
1.重新安装 
2.任意组合安装 
4.Hysteria2管理 
5.REALITY管理 
6.Tuic管理

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.17

**Comment by cifei1** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.17

辛苦大佬
