### ISSUE TITLE
Reality协议无需域名的怎么没了啊？

### ISSUE THREAD

**Issue by chancat87** [mack-a/v2ray-agent#882]
**详细描述建议的内容**
如题，更新了新脚本发现不需要域名的5.Reality管理没了，还有啥办法实现吗？谢谢。

**Comment by GuLuDaDuiZhang** [comment]
看代码提交记录是主动移除了这个选项，但更新日志里没有说明原因。要用的话去下载旧版本 2.xxx 目前还是可以的

**Comment by mack-a** [comment]
后续我会增加一个更加完善的reality管理

**Comment by mack-a** [comment]
[v3.1.16](https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.16)

**Comment by chancat87** [comment]
> [v3.1.16](https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.16)

谢群主😘

**Comment by chancat87** [comment]
> [v3.1.16](https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.16)

群主。。咱们群机器人把我给屏蔽了😂我之前用的小号在群里水，前几天小号被人偷了，注销了，然后用大号申请进群发现无此用户不存在啥的，明显被机器人拉黑了。。麻烦帮我解禁下id 是 chancat [泰森头像]😂谢谢
