### ISSUE TITLE
到添加伪装站点那步一直显示Nginx启动失败

### ISSUE THREAD

**Issue by sdshdv** [mack-a/v2ray-agent#886]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
到添加伪装站点那步一直显示Nginx启动失败，nginx已尝试多次卸载和重装，nginx版本：1.25.3

## 2.安装失败的log或者截图
请输入端口[默认: 443]，可自定义端口[回车使用默认] 
端口:

 ---> 端口: 443 
 ---> 域名IP校验通过 
 ---> Nginx启动成功 
 ---> Nginx关闭成功 
 ---> 检测到443端口已开放 

 ---> 检查域名ip中 
 ---> 检查当前域名IP正确 
 ---> Xray关闭成功 

进度  3/12 : 申请TLS证书
 
 ---> 检测到证书 
 ---> 证书检查日期:2023-12-26 02:11:51 
 ---> 证书生成日期:2023-12-26 00:51:29 
 ---> 证书生成天数:0 
 ---> 证书剩余天数:90 
 ---> 证书过期前最后一天自动更新，如更新失败请手动更新 
 ---> 证书有效 

进度 6/12 : 添加伪装站点 
 ---> 添加伪装站点成功 
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本 

## 3.系统版本
Linux VM31658A5D785CB04 6.1.0-16-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
debian12
## 4.脚本版本
v3.1.17

**Comment by mack-a** [comment]
手动启动下nginx 看看报错信息

**Comment by sdshdv** [comment]
root@VM31658A5D785CB04:~# systemctl start nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
root@VM31658A5D785CB04:~# ^C
root@VM31658A5D785CB04:~# systemctl status nginx.service
● nginx.service - nginx - high performance web server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-12-26 03:21:52 EST; 15s ago
       Docs: https://nginx.org/en/docs/
    Process: 6738 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
        CPU: 9ms

Dec 26 03:21:52 VM31658A5D785CB04 systemd[1]: Starting nginx - high performance web server...
Dec 26 03:21:52 VM31658A5D785CB04 nginx[6738]: nginx: [emerg] bind() to 127.0.0.1:31300 failed (99: Canno>
Dec 26 03:21:52 VM31658A5D785CB04 systemd[1]: nginx.service: Control process exited, code=exited, status=>
Dec 26 03:21:52 VM31658A5D785CB04 systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 26 03:21:52 VM31658A5D785CB04 systemd[1]: Failed to start nginx - high performance web server.

**Comment by mack-a** [comment]
如果以前没有安装成功过，建议dd一个纯净版系统重新安装
