### ISSUE TITLE
Debian 12系统下， Nginx启动失败

### ISSUE THREAD

**Issue by lixueshu** [mack-a/v2ray-agent#888]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
Debian 12系统下， Nginx启动失败.自行安装后还是启动失败

## 2.安装失败的log或者截图
-> 域名IP校验通过 
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本 

## 3.系统版本
系统版本: Debian GNU/Linux 12 (bookworm)
Linux版本: 6.1.0-13-cloud-amd64

## 4.脚本版本
当前版本：v3.1.19

**Comment by lixueshu** [comment]
#16270: bind() to 127.0.0.1:31300 failed (99: Cannot assign requested address)

**Comment by mack-a** [comment]
建议DD一下纯净版系统
