### ISSUE TITLE
访问伪装网站报错代码521

### ISSUE THREAD

**Issue by a308667911** [mack-a/v2ray-agent#889]
如果只安装 box 核心，伪装网站报错代码521 ..... （开了 cf代理

测试了一下，必须安装xy核心才能打开伪装网站 ..... 

希望下一个脚本能解决一下 只装 box 核心 也能 打开 伪装网站

centos7 、debian11，12

**Comment by mack-a** [comment]
sing-box 只有个别协议支持伪装站
