### ISSUE TITLE
cloudflare只用dns only，为什么也能自选IP啊？

### ISSUE THREAD

**Issue by lck1115** [mack-a/v2ray-agent#89]
虽然看到closed issue中有人提过，但是还是不明白。

我只用了dns only, 关了cloudflare的小云朵，也没有开DNSSEC，主机用cloudflare的自选IP地址，为什么也能起到CDN加速的作用？

**Comment by lck1115** [comment]
这种情况下，开小云朵和不开，有啥区别吗？

**Comment by mack-a** [comment]
> 这种情况下，开小云朵和不开，有啥区别吗？

开的时候不管谁访问也会经过CDN，不开的时候如果不自选ip，访问是直连，不走CDN

**Comment by mack-a** [comment]
> 虽然看到closed issue中有人提过，但是还是不明白。
> 
> 我只用了dns only, 关了cloudflare的小云朵，也没有开DNSSEC，主机用cloudflare的自选IP地址，为什么也能起到CDN加速的作用？

这和cloudflare 的判定有关系，首先自选ip后如果将自己的流量自选到某个cloudflare的anycast ip，这个时候他应该只检查了域名是否托管，没有检查是否开云朵。但是如果自选到某个Pro版本的anycast ip，这个时候大概率会被拒绝。

**Comment by lck1115** [comment]
> > 虽然看到closed issue中有人提过，但是还是不明白。
> > 我只用了dns only, 关了cloudflare的小云朵，也没有开DNSSEC，主机用cloudflare的自选IP地址，为什么也能起到CDN加速的作用？
> 
> 这和cloudflare 的判定有关系，首先自选ip后如果将自己的流量自选到某个cloudflare的anycast ip，这个时候他应该只检查了域名是否托管，没有检查是否开云朵。但是如果自选到某个Pro版本的anycast ip，这个时候大概率会被拒绝。
> 
> 以上都是猜测与推断，判定机制估计只有他们内部知道。

明白了，多谢~~
