### ISSUE TITLE
sing-box核心下的Reality无法使用且vision没有生成

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#891]
## 1.问题描述
全新节点下，最新脚本，操作如下：
vasma-2-2-089，输入域名，其他都是默认随机
## 2.安装失败的log或者截图
![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/45126c51-68e7-4cac-b5e2-3431f58cd751)

![图片](https://github.com/mack-a/v2ray-agent/assets/43665641/4f1ae031-2c2d-4c88-beff-1dbf40aa5ea9)

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v3.1.21

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.22
