### ISSUE TITLE
订阅更新失败，证书问题

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#893]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
reality 协议使用了第三方域名用于偷流量，导致使用sfm导入订阅链接时，提示证书不正确，而提示的证书域名正是自己设置的一个
如果用浏览器手动打开订阅链接，同样会提示非私密链接，需要刷新好几次，才能正确打开
可是使用reality+sni不是常见配置吗，难道这就无法通过订阅链接更新了吗
## 2.安装失败的log或者截图
<img width="260" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/13982749/8ae99ca7-f5d0-4c45-859f-c67f6440809c">

## 3.系统版本
Ubuntu
## 4.脚本版本
最新3.1.21

**Comment by mack-a** [comment]
请你你安装vision（xray）或者singbox（任意需要证书协议）作为https访问了吗

**Comment by fredericky123** [comment]
只安装了vision reality这一个协议

**Comment by mack-a** [comment]
只安装这个不会去申请证书，只能使用http订阅
