### ISSUE TITLE
sing-box下的reality无法使用

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#894]
## 1.问题描述
操作如下， vasma-2-2-0789，使用订阅，只有TLS_Vision，TUIC可用，reality_vision、reality_gRPC不可使用。单独使用reality的账号，报错为：net/http: TLS handshake timeout 

PS：排除机器问题，我已在3个卸载后的干净vps上反复测试过了（racknear\greencloud\oralce）。排除防火墙问题，reality的端口可通

## 3.系统版本
ubuntu20.04
## 4.脚本版本
v3.1.22

**Comment by mack-a** [comment]
用的什么客户端

**Comment by bettswang** [comment]
PC: clashverge v1.3.9
Android: clashmeta  v2rayNG

**Comment by davidtall** [comment]
我也遇到同样的问题，服务端用sing-box ，客户端用v2rayNG 无使用，换成sing-box 就正常了，就是服务端和客户端的内核都是sing-box 才可以

**Comment by mack-a** [comment]
经过多次测试，这个问题只能等内核相关大佬解决。目前sing-box内核安装可以使用nekobox。

**Comment by bettswang** [comment]
> 经过多次测试，这个问题只能等内核相关大佬解决。目前sing-box内核安装可以使用nekobox。

我试过了，nekobox导入reality_vision、reality_grpc都不可用。
![e961eb476c964be2db2a17a960fd30d](https://github.com/mack-a/v2ray-agent/assets/43665641/74aa9896-5f93-41d0-abed-fba37e0bb1c9)

**Comment by bettswang** [comment]
大佬有可虑支持下sing-box的客户端吗？

**Comment by iamjimmycheng** [comment]
我也遇到同样的问题，新搭建的reality协议无法使用，同时搭建的其他协议都正常。

**Comment by mack-a** [comment]
> > 经过多次测试，这个问题只能等内核相关大佬解决。目前sing-box内核安装可以使用nekobox。
> 
> 我试过了，nekobox导入reality_vision、reality_grpc都不可用。 ![e961eb476c964be2db2a17a960fd30d](https://private-user-images.githubusercontent.com/43665641/293872728-74aa9896-5f93-41d0-abed-fba37e0bb1c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTY4MTAsIm5iZiI6MTcwNDM1NjUxMCwicGF0aCI6Ii80MzY2NTY0MS8yOTM4NzI3MjgtNzRhYTk4OTYtNWY5My00MWQwLWFiZWQtZmJhMzdlMGJiMWM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNTQ5MjIwM2YxMDE3Nzc5YjZkZWNiYmYzYWNmYzRiNzkxMzEwMTlhZGM4YmFhZTNmM2E5M2RlMzBhNjcwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBuHaqPdSp51ZO908Q0MMQT1RRaMDdtAdzaIaC7IU2c)

更换域名试一下

**Comment by bettswang** [comment]
> > > 经过多次测试，这个问题只能等内核相关大佬解决。目前sing-box内核安装可以使用nekobox。
> > 
> > 
> > 我试过了，nekobox导入reality_vision、reality_grpc都不可用。 ![e961eb476c964be2db2a17a960fd30d](https://private-user-images.githubusercontent.com/43665641/293872728-74aa9896-5f93-41d0-abed-fba37e0bb1c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTY4MTAsIm5iZiI6MTcwNDM1NjUxMCwicGF0aCI6Ii80MzY2NTY0MS8yOTM4NzI3MjgtNzRhYTk4OTYtNWY5My00MWQwLWFiZWQtZmJhMzdlMGJiMWM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNTQ5MjIwM2YxMDE3Nzc5YjZkZWNiYmYzYWNmYzRiNzkxMzEwMTlhZGM4YmFhZTNmM2E5M2RlMzBhNjcwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBuHaqPdSp51ZO908Q0MMQT1RRaMDdtAdzaIaC7IU2c)
> 
> 更换域名试一下

在xray核心下是正常的。应该不是域名的问题。

**Comment by ChrisLiu0343** [comment]
为什么xray核心不能reality？singbox核心各种不兼容。

**Comment by bettswang** [comment]
更新下最新测试情况。操作菜单` vasma-2-2-6,7,8,9,10`。安装完成后，VLESS+Reality+Vision VLESS+Reality+gRPC不可用。查看过程中，发现没有对Reality的回落域名做设置。再次操作菜单`vasma-5`进行设置后，故障解除，VLESS+Reality+Vision VLESS+Reality+gRPC变成可用。

**Comment by mack-a** [comment]
> 更新下最新测试情况。操作菜单` vasma-2-2-6,7,8,9,10`。安装完成后，VLESS+Reality+Vision VLESS+Reality+gRPC不可用。查看过程中，发现没有对Reality的回落域名做设置。再次操作菜单`vasma-5`进行设置后，故障解除，VLESS+Reality+Vision VLESS+Reality+gRPC变成可用。

你这个用的是xray-core吗

**Comment by bettswang** [comment]
singbox

**Comment by caixiaomao** [comment]
> 更新下最新测试情况。操作菜单` vasma-2-2-6,7,8,9,10`。安装完成后，VLESS+Reality+Vision VLESS+Reality+gRPC不可用。查看过程中，发现没有对Reality的回落域名做设置。再次操作菜单`vasma-5`进行设置后，故障解除，VLESS+Reality+Vision VLESS+Reality+gRPC变成可用。

确实，这样在操作一次就没有问题了

**Comment by mack-a** [comment]
经过我的测试，vasma->5之前和5之后配置没有区别，你这样执行完毕后v2rayNG可以使用了吗 @bettswang

**Comment by bettswang** [comment]
> 经过我的测试，vasma->5之前和5之后配置没有区别，你这样执行完毕后v2rayNG可以使用了吗 @bettswang

我是这样操作的，完全卸载后，重新下载脚本。执行菜单：` vasma->2->2->6,7,8,9,10`   输入域名后，全部按回车选择默认。
完成后生成订阅，导入到clashmeta或者v2rayNG，Reality的相关节点都是不可用。其中v2rayNG测试，报错：`失败 net/http: TLS handshake timeout`。这个状态，执行任何操作好像都没解了。

第二次，完全卸载后，重新下载脚本。执行菜单：` vasma->2->2->6,7,8,9,10`   输入域名后，全部按回车选择默认。这个时候不要生成订阅，先在执行菜单：` vasma->5->y->回车->y->回车->y` ，再生成订阅，导入到clashmeta或者v2rayNG。Reality的相关节点正常。

**Comment by bettswang** [comment]
测试了几遍，发现，有时候，在第一次故障时候，直接执行菜单: vasma->5后完成操作，有时候也可以修复。我才是不是部分fallback域名失效了呀？

**Comment by bettswang** [comment]
顺便提下，为什么在windows下的ClashVerge客户端，订阅更新配置总是没办法覆盖。我观察了下，它是两层配置，其中1级入口在profiles目录下，2级入口在profiles同层目录下。然后由于salt值没变，导致这个文件不会被重新覆盖。

**Comment by shenyunet** [comment]
能否现在让xray内核也增加不用域名的reality  singbox兼容性有问题

**Comment by mack-a** [comment]
> 能否现在让xray内核也增加不用域名的reality singbox兼容性有问题

https://www.v2ray-agent.com/archives/1708584312877

**Comment by mack-a** [comment]
建议使用，此[方法](https://www.v2ray-agent.com/archives/1708584312877)搭建Xray-core的reality
