### ISSUE TITLE
vision+reality在客户端频繁报错

### ISSUE THREAD

**Issue by Delay7184** [mack-a/v2ray-agent#895]
## 1.问题描述
安装时选择了: 任意组合安装->7，端口都选择443。

安装过程中没有任何出错，客户端节点导入也没有问题。

vless+vision和grpc+reality在所有客户端使用完全正常；vision+reality可以使用，但频繁断流（几秒钟一次），客户端日志出现reality verification failed。

已经在两个不同商家且ip和端口均无封禁的vps上测试过了，客户端（均为最新版本）也尝试了：
Clash Nyanpasu（Clash Meta核心，系统代理和TUN代理均报错）
v2rayN（系统代理报错不一样，见下面的log，TUN代理报错）
Shadowrocket（没看日志，但断流最严重，几乎没法使用）

试着偷不同网站的证书，偷自己的也试过了，结果相同。

## 2.安装失败的log或者截图
Clash、v2rayN的TUN模式（即singbox）：reality verification failed

v2rayN的系统代理模式：app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [REALITY: processed invalid connection] > common/retry: all retry attempts failed
## 3.系统版本
Debian 11
## 4.脚本版本
3.1.22

**Comment by mack-a** [comment]
可能是你的线路太差劲了

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/894

可以看参考一下是不是这个问题或者是线路问题

**Comment by Delay7184** [comment]
> #894
> 
> 可以看参考一下是不是这个问题或者是线路问题

使用的是xray内核，抱歉忘记提了。与[#894](https://github.com/mack-a/v2ray-agent/issues/894)不是同一个问题。
VPS是dmit的三网cn2 gia，可以确定不是线路问题。

我晚点自己配置一遍xray，看看是不是脚本的问题

**Comment by Delay7184** [comment]
用本脚本单独搭建singbox内核的同端口Vision+Reality节点，没有任何问题；用xray单独搭建同端口Vision+Reality节点也没有任何问题。可以确定是用本脚本搭建xray内核节点的问题（或者是玄学emm）。猜测是xray配置中fallback的问题。

另外经过测试，PC端的v2rayN和clash nyanpasu只是频繁报错+连接网站缓慢，只有ios的Shadowrocket是频繁断流，可能是这个客户端的原因，所以改标题为[vision+reality在客户端频繁报错](https://github.com/mack-a/v2ray-agent/issues/895#top)。

希望能重新开放issue。

**Comment by mack-a** [comment]
频繁断流的时可否提供一下服务端的日志

**Comment by Delay7184** [comment]
> 频繁断流的时可否提供一下服务端的日志

warning级别日志只记录了内核的启动，反而在info级别日志下有一些信息。
这是使用PC客户端频繁报错时服务端的日志，example.com是我的域名：[pastebin](https://pastebin.com/X6hH5L5J)
iOS端的ShadowRocket断流时服务端的日志，就是以下内容的不断重复：
```
2024/01/03 08:50:13 [Info] [2808385700] proxy/vless/inbound: firstLen = 0
2024/01/03 08:50:13 [Info] [2808385700] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/01/03 08:50:13 [Info] [2808385700] proxy/vless/inbound: realName = example.com
2024/01/03 08:50:13 [Info] [2808385700] proxy/vless/inbound: realAlpn = 
2024/01/03 08:50:13 [Info] [2808385700] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > remote error: tls: unknown certificate
2024/01/03 08:50:14 [Info] [3730828639] proxy/vless/inbound: firstLen = 0
2024/01/03 08:50:14 [Info] [3730828639] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/01/03 08:50:14 [Info] [3730828639] proxy/vless/inbound: realName = example.com
2024/01/03 08:50:14 [Info] [3730828639] proxy/vless/inbound: realAlpn = 
2024/01/03 08:50:14 [Info] [3730828639] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp VPS的IP地址:443->VPS的IP地址:41844: i/o timeout
2024/01/03 08:50:14 [Info] transport/internet/tcp: REALITY: processed invalid connection
```

**Comment by mack-a** [comment]
你偷一下自己的域名试试会断流吗

**Comment by Delay7184** [comment]
> 你偷一下自己的域名试试会断流吗

现在偷的就是自己的，你的网站上的参考域名也试过几个了，都是一样的情况。

**Comment by mack-a** [comment]
> 用本脚本单独搭建singbox内核的同端口Vision+Reality节点，没有任何问题；用xray单独搭建同端口Vision+Reality节点也没有任何问题。可以确定是用本脚本搭建xray内核节点的问题（或者是玄学emm）。猜测是xray配置中fallback的问题。
> 
> 另外经过测试，PC端的v2rayN和clash nyanpasu只是频繁报错+连接网站缓慢，只有ios的Shadowrocket是频繁断流，可能是这个客户端的原因，所以改标题为[vision+reality在客户端频繁报错](https://github.com/mack-a/v2ray-agent/issues/895#top)。
> 
> 希望能重新开放issue。

用脚本sing-box单独安装reality没有问题，用xray个性化安装reality也没问题吗

**Comment by Delay7184** [comment]
> > 用本脚本单独搭建singbox内核的同端口Vision+Reality节点，没有任何问题；用xray单独搭建同端口Vision+Reality节点也没有任何问题。可以确定是用本脚本搭建xray内核节点的问题（或者是玄学emm）。猜测是xray配置中fallback的问题。
> > 另外经过测试，PC端的v2rayN和clash nyanpasu只是频繁报错+连接网站缓慢，只有ios的Shadowrocket是频繁断流，可能是这个客户端的原因，所以改标题为[vision+reality在客户端频繁报错](https://github.com/mack-a/v2ray-agent/issues/895#top)。
> > 希望能重新开放issue。
> 
> 用脚本sing-box单独安装reality没有问题，用xray个性化安装reality也没问题吗

是的。

**Comment by changmingcn** [comment]
遇到了类似的问题，Vision+Reality，使用任意组合安装->7，xray安装，端口都选择443，使用自己的域名，Cloudfare+DNS API解析，安装完毕后得到Vision+Reality和gRPC+Reality，选则Vision+Reality则出现connect error: REALITY authentication failed，选择gRPC+Reality可以正常联通。

**Comment by xueyunfeng0513** [comment]
遇到了类似的问题

**Comment by wtsai92** [comment]
环境: debian11
v2ray-agent版本: v3.3.3
安装协议: 0,7(vless+xtls,vless+reality)
复现步骤: 首次打开新网址有概率chrome提示ERR_CONNECTION_CLOSED/ERR_SSL_PROTOCOL_ERROR，打开成功后二次打开不会浮现，开了error日志如下
```
2024/06/17 16:06:38 [Info] [4137101228] proxy: XtlsFilterTls found tls 1.3! 4288 TLS_AES_128_GCM_SHA256
2024/06/17 16:06:38 [Info] [4137101228] proxy: XtlsPadding 4288 138 0
2024/06/17 16:06:38 [Info] [4137101228] proxy: Xtls Unpadding new block, content 64 padding 881 command 2
2024/06/17 16:06:38 [Info] [4137101228] proxy: CopyRawConn readv
2024/06/17 16:06:38 [Info] [4137101228] proxy: XtlsPadding 614 676 2
2024/06/17 16:06:38 [Info] [2967510813] proxy: CopyRawConn splice
2024/06/17 16:06:38 [Info] [4137101228] proxy: CopyRawConn splice
2024/06/17 16:06:39 [Info] [3400112683] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp xxxxxxx:443->xxxxx:7952: use of closed network connection
2024/06/17 16:06:39 [Info] [2117029287] proxy/vless/inbound: firstLen = 60
2024/06/17 16:06:39 [Info] [2117029287] proxy/vless/inbound: received request for tcp:maps.googleapis.com:443
2024/06/17 16:06:39 [Info] [2117029287] app/dispatcher: taking detour [z_direct_outbound] for [tcp:maps.googleapis.com:443]
2024/06/17 16:06:39 [Debug] app/dns: domain maps.googleapis.com will use DNS in order: [localhost]
2024/06/17 16:06:39 [Info] [2117029287] proxy: Xtls Unpadding new block, content 517 padding 846 command 0
2024/06/17 16:06:39 [Info] [2117029287] proxy: XtlsFilterTls found tls client hello! 517
2024/06/17 16:06:39 [Info] [2620772760] proxy/vless/inbound: firstLen = 0
2024/06/17 16:06:39 [Info] [2620772760] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/06/17 16:06:39 [Info] [2620772760] proxy/vless/inbound: realName = xxxxxx
2024/06/17 16:06:39 [Info] [2620772760] proxy/vless/inbound: realAlpn =
2024/06/17 16:06:39 [Info] [2620772760] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > remote error: tls: unknown certificate
```

**Comment by PikuZheng** [comment]
类似问题。。同城的两个同运营商同配置，一个正常，另一个报"REALITY authentication failed"

**Comment by EaveLuo** [comment]
同样的问题，两条都是cn2_gia，使用grpc_reality不会，vision_reality就会

**Comment by mack-a** [comment]
Reailty 更换域名试一下。

**Comment by EaveLuo** [comment]
不能偷自己的域名了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月10日(周五) 下午4:08
收件人: ***@***.***&gt;;
抄送: "Eave ***@***.******@***.***&gt;;
主题: Re: [mack-a/v2ray-agent] vision+reality在客户端频繁报错 (Issue #895)




 
Reailty 更换域名试一下。

**Comment by PikuZheng** [comment]
我的后来从xray换成box 就正常了

**Comment by EaveLuo** [comment]
@mack-a 换了域名vuejs.org后不报原来这个错了，虽然能连接成功，但报了新的错：192.168.50.150:34463 --> pool.ntp.org:123 error: new vless client error: remote error: tls: unrecognized name

**Comment by PikuZheng** [comment]
> @mack-a 换了域名vuejs.org后不报原来这个错了，虽然能连接成功，但报了新的错：192.168.50.150:34463 --> pool.ntp.org:123 error: new vless client error: remote error: tls: unrecognized name

这个应该是服务端改了域名客户端没改，两侧不匹配

**Comment by EaveLuo** [comment]
> > @mack-a 换了域名vuejs.org后不报原来这个错了，虽然能连接成功，但报了新的错：192.168.50.150:34463 --> pool.ntp.org:123 error: new vless client error: remote error: tls: unrecognized name
> 
> 这个应该是服务端改了域名客户端没改，两侧不匹配

订阅链接导入的，是地址那里还是sni那里没匹配呢，我把pool.ntp.org走国内了，国内反正也能走

**Comment by PikuZheng** [comment]
> 订阅链接导入的，是地址那里还是sni那里没匹配呢，我发现订阅链接导入的，那个节点的地址会变成ip，sni倒是我设置的那个,我把节点地址改成了域名，还是一样的会报tls错误

节点地址用ip是对的。sni应该是换之后的，还报错可能是服务器到sni对应的真实服务器有断续问题

**Comment by EaveLuo** [comment]
> > 订阅链接导入的，是地址那里还是sni那里没匹配呢，我发现订阅链接导入的，那个节点的地址会变成ip，sni倒是我设置的那个,我把节点地址改成了域名，还是一样的会报tls错误
> 
> 节点地址用ip是对的。sni应该是换之后的，还报错可能是服务器到sni对应的真实服务器有断续问题

好吧。。。
