### ISSUE TITLE
能否增加韩国墙分流

### ISSUE THREAD

**Issue by fredericky123** [mack-a/v2ray-agent#896]
**详细描述建议的内容**
https://hostloc.com/forum.php?mod=viewthread&tid=1249701&highlight=%E7%94%B2%E9%AA%A8%E6%96%87
韩国确实也有墙，如何实现分流用US ip访问呢

**Comment by mack-a** [comment]
任意门分流即可

**Comment by fredericky123** [comment]
任意门需要两个vps 可是只有一个 不知道能否通过warp实现
