### ISSUE TITLE
新加naive的节点

### ISSUE THREAD

**Issue by jackszb** [mack-a/v2ray-agent#897]
**详细描述建议的内容**
老大，导入小火箭不通啊，协议选择的http2,然后填入域名，端口，密码三项，是否还缺什么？

**Comment by mack-a** [comment]
小火煎需要手动填写，标准的naive uri不支持。
类型选择 HTTP2，依次填上地址、端口、用户、密码、SNI、填充打开

**Comment by jackszb** [comment]
谢谢老大

mack-a ***@***.***>于2024年1月3日 周三22:30写道：
