### ISSUE TITLE
3.1.23版本重新安装报Could not open file /etc/v2ray-agent/sing-box/conf/config/.json

### ISSUE THREAD

**Issue by davidtall** [mack-a/v2ray-agent#898]
升级脚本到3.1.23，安装sing-box 内核 679 安装 ，报 jq: error: Could not open file /etc/v2ray-agent/sing-box/conf/config/.json: No such file or directory
如图
![image](https://github.com/mack-a/v2ray-agent/assets/9320941/de152e2e-f5a3-4a19-bd97-e53ee6d42223)

**Comment by mack-a** [comment]
使用v3.1.24重新安装
