### ISSUE TITLE
申请tls证书的时候老是报错

### ISSUE THREAD

**Issue by ihuihui** [mack-a/v2ray-agent#899]
## 1.问题描述
2-2-6，严格按步骤执行，在申请tls证书的时候老是报错。

## 2.安装失败的log或者截图

是否使用DNS API申请证书[支持NAT]？[y/n]:y

============================================================== 
1.cloudflare[默认] 
============================================================== 
请选择[回车]使用默认:

 CF_Token参考配置教程：https://www.v2ray-agent.com/archives/1701160377972
 
请输入API Token: **

是否使用*.cn进行API申请通配符证书？[y/n]:y

============================================================== 
1.letsencrypt[默认] 
2.zerossl 
3.buypass[不支持DNS申请] 
============================================================== 
请选择[回车]使用默认:
 ---> 生成通配符证书中 
[Thu Jan  4 01:58:52 AM UTC 2024] The domain '**.cn' is not a cert name. You must use the cert name to specify the cert to install.
[Thu Jan  4 01:58:52 AM UTC 2024] Can not find path:'/root/.acme.sh/petsdoc.cn_ecc'
[Thu Jan  4 01:58:51 AM UTC 2024] The domain key is here: /root/.acme.sh/*.cn_ecc/*.cn.key
[Thu Jan  4 01:58:51 AM UTC 2024] Single domain='*.cn'
[Thu Jan  4 01:58:51 AM UTC 2024] Getting domain auth token for each domain
[Thu Jan  4 01:58:52 AM UTC 2024] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"*.cn\": Domain name is a wildcard for an ICANN TLD",
  "status": 400
}
[Thu Jan  4 01:58:52 AM UTC 2024] Please add '--debug' or '--log' to check more details.
[Thu Jan  4 01:58:52 AM UTC 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

进度  3/9 : 申请TLS证书
 
是否使用DNS API申请证书[支持NAT]？[y/n]:y

============================================================== 
1.cloudflare[默认] 
============================================================== 
请选择[回车]使用默认:

 CF_Token参考配置教程：https://www.v2ray-agent.com/archives/1701160377972
 
请输入API Token:**

是否使用*.cn进行API申请通配符证书？[y/n]:y
 ---> 生成通配符证书中 
[Thu Jan  4 01:59:07 AM UTC 2024] The domain '**.cn' is not a cert name. You must use the cert name to specify the cert to install.
[Thu Jan  4 01:59:07 AM UTC 2024] Can not find path:'/root/.acme.sh/petsdoc.cn_ecc'
[Thu Jan  4 01:59:06 AM UTC 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu Jan  4 01:59:06 AM UTC 2024] Single domain='*.cn'
[Thu Jan  4 01:59:06 AM UTC 2024] Getting domain auth token for each domain
[Thu Jan  4 01:59:07 AM UTC 2024] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"*.cn\": Domain name is a wildcard for an ICANN TLD",
  "status": 400
}
[Thu Jan  4 01:59:07 AM UTC 2024] Please add '--debug' or '--log' to check more details.
[Thu Jan  4 01:59:07 AM UTC 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
 ---> TLS安装失败，请检查acme日志 

## 3.系统版本
Ubuntu 22.04 64 Bit

## 4.脚本版本
v3.1.24

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.25
