### ISSUE TITLE
关于生成的的订阅链接 客户端无法正常识别

### ISSUE THREAD

**Issue by carlchina** [mack-a/v2ray-agent#900]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
使用最新脚本，安装Xray-core 与 sing-box后，使用生成的订阅链接，添加到客户端后无法正确的代理

ClashVerge 1.45

```
01-04 10:03:30ERROR
initial proxy provider drciguytkf_provider error: proxy 3 error: key 'port' missing 
```

## 2.安装失败的log或者截图
![WX20240104-101401@2x](https://github.com/mack-a/v2ray-agent/assets/5435458/01979fba-b81a-4782-866a-41a11e8600e4)

## 3.系统版本
macos  ClashVerge 1.45

## 4.脚本版本
当前版本：v3.1.24

**Comment by mack-a** [comment]
使用clashmeta内核

**Comment by carlchina** [comment]
Mihomo Meta v1.17.0 darwin arm64 with go1.21.4 Sun Dec  3 01:01:53 UTC 2023
Use tags: with_gvisor

确实是 Meta

**Comment by felixlu** [comment]
同遇到这个问题，是因为生成的 VMess 的端口号为空，导致解析失败。

**Comment by BigPig02** [comment]
> 同遇到这个问题，是因为生成的 VMess 的端口号为空，导致解析失败。

好像生成的vmess链接都不行

**Comment by mack-a** [comment]
暂时未复现，使用此版本试一下。https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.25

**Comment by BigPig02** [comment]
vmess用最新版本还是没法识别

**Comment by quango-web** [comment]
> vmess用最新版本还是没法识别

确实，vmess订阅在passwall里无法识别，手工填

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.26
