### ISSUE TITLE
xray 升级报错

### ISSUE THREAD

**Issue by myfalcom** [mack-a/v2ray-agent#901]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
最新脚本在xray-core预览版升级时会报没有找到xray文件的错误；
分析后发现应该是脚本执行时xray执行文件会被删除，然后侦测无法找到执行文件，步骤卡在是否继续升级，无法继续执行升级。

## 3.系统版本
debian 11 

## 4.脚本版本
latest

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.28
