### ISSUE TITLE
脚本对ipv6 only的vps不友好

### ISSUE THREAD

**Issue by deepdream** [mack-a/v2ray-agent#903]
## 1.问题描述
在iipv6 only的vps上运行，在检测地址这一步时，脚本得到的是ipv4的本机地址，会显示“ ---> 域名解析IP与当前服务器IP不一致 ---> 请检查域名解析是否生效以及正确“”
”

## 3.系统版本
debain 11
## 4.脚本版本
v3.1.29

**Comment by mack-a** [comment]
后续会持续更新

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.31

**Comment by mack-a** [comment]
纯IPv6机器为什么会获取到IPv4地址呢 ？是否使用WARP添加了IPv4地址

**Comment by offzen** [comment]
也遇到了一样的问题；v4地址不是cf的，而是同一个机房的，但也不是分配给我的nat 出口v4 IP
