### ISSUE TITLE
用dns api方式申请证书时总是失败

### ISSUE THREAD

**Issue by deepdream** [mack-a/v2ray-agent#904]
## 1.问题描
使用dns ap申请i证书，总是报错。

## 2.安装失败的log或者截图
是否使用*.deepdream.top进行API申请通配符证书？[y/n]:y

============================================================== 
1.letsencrypt[默认] 
2.zerossl 
3.buypass[不支持DNS申请] 
============================================================== 
请选择[回车]使用默认:1
 ---> 生成通配符证书中 
[Fri Jan 12 16:08:08 UTC 2024] The domain 'bv.deepdream.top' is not a cert name. You must use the cert name to specify the cert to install.
[Fri Jan 12 16:08:08 UTC 2024] Can not find path:'/root/.acme.sh/bv.deepdream.top_ecc'
[Fri Jan 12 16:01:57 UTC 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Jan 12 16:08:00 UTC 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Jan 12 16:08:00 UTC 2024] Single domain='*.deepdream.top'
[Fri Jan 12 16:08:00 UTC 2024] Getting domain auth token for each domain
[Fri Jan 12 16:08:04 UTC 2024] Getting webroot for domain='*.deepdream.top'
[Fri Jan 12 16:08:04 UTC 2024] Adding txt value: MHOfSdYJPQ8mXZ_LeMkkq7kpWHWFulm2tI-76hHPIdw for domain:  _acme-challenge.deepdream.top
[Fri Jan 12 16:08:07 UTC 2024] invalid domain
[Fri Jan 12 16:08:07 UTC 2024] Error add txt for domain:_acme-challenge.deepdream.top
[Fri Jan 12 16:08:07 UTC 2024] Please add '--debug' or '--log' to check more details.
[Fri Jan 12 16:08:07 UTC 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

## 3.系统版本
debain 12
## 4.脚本版本
当前版本：v3.1.30

**Comment by mack-a** [comment]
token是否配置正确，目前没有复现此问题

**Comment by johnayman0** [comment]
same, found any fix?
