### ISSUE TITLE
使用最新脚本安装，sing-box安装版本为1.7.8，当前最新sing-box为1.8.0，提交SHA为de908b1fed0784bc2c2f7f2321c6cfc19ef0781c

### ISSUE THREAD

**Issue by awhao** [mack-a/v2ray-agent#905]
**使用最新脚本安装，sing-box安装版本为1.7.8，当前最新sing-box为1.8.0，提交SHA为de908b1fed0784bc2c2f7f2321c6cfc19ef0781c**

**Comment by mack-a** [comment]
目前1.8.0提交的issues会影响某些协议的正常使用。现锁定1.7.8
