### ISSUE TITLE
安装过程中，Xray关闭后启动失败

### ISSUE THREAD

**Issue by dysdy** [mack-a/v2ray-agent#906]
## 1.问题描述
       安装过程中，Xray关闭后启动失败
## 2.安装失败的log或者截图
      ---> 添加定时维护证书成功 
      ---> Xray关闭成功 
     Xray启动失败 
     请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈 

## 3.系统版本
    Ubuntu 18.0.4，oracle cloud
## 4.脚本版本
    2024-1-12号下载的版本

**Comment by dysdy** [comment]
使用提示的命令抓的log如下
 ---> 添加定时维护证书成功 
 ---> Xray关闭成功 
Xray启动失败 
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈 
root@instance-20211110-1456:/home/ubuntu/reality# ^C
root@instance-20211110-1456:/home/ubuntu/reality# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)
A unified platform for anti-censorship.
2024/01/13 00:46:49 Using confdir from arg: /etc/v2ray-agent/xray/conf
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2024/01/13 00:46:49 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json] appended inbound with tag: VLESSTCP
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/09_routing.json
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2024/01/13 00:46:49 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: IPv4_out
2024/01/13 00:46:49 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: IPv6_out
2024/01/13 00:46:49 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: direct
2024/01/13 00:46:49 [Info] infra/conf: [/etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json] prepend outbound with tag: blackhole_out
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
2024/01/13 00:46:49 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/12_policy.json

**Comment by mack-a** [comment]
看日志没有发现明显错误，检查是否使用其他脚本安装过相应开机自启动程序

**Comment by dcosmic** [comment]
Failed to start: app/proxyman/inbound: failed to listen TCP on 31297 > transport/internet: failed to listen on address: 127.0.0.1:31297 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31297 > listen tcp 127.0.0.1:31297: bind: cannot assign requested address

**Comment by mack-a** [comment]
> Failed to start: app/proxyman/inbound: failed to listen TCP on 31297 > transport/internet: failed to listen on address: 127.0.0.1:31297 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31297 > listen tcp 127.0.0.1:31297: bind: cannot assign requested address

建议安装纯净版系统解决此问题

**Comment by dysdy** [comment]
***@***.*** 在清的时候没清掉，删了之后重装可以了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
