### ISSUE TITLE
使用xray-core进行socks分流，填写出站信息完成后，重启内核失败

### ISSUE THREAD

**Issue by ryan-web-dev** [mack-a/v2ray-agent#907]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
使用xray-core进行socks分流，填写出站信息完成后，重启内核失败

## 2.安装失败的log或者截图
错误信息：
```
failed to start: main: failed to create server > proxy/socks: 0 target server
```

## 3.系统版本
Debian12.4

## 4.脚本版本
v3.1.31

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.32
