### ISSUE TITLE
安装Xray核心时下载失败

### ISSUE THREAD

**Issue by Fhigr** [mack-a/v2ray-agent#911]
## 1.问题描述
使用DD后的全新系统安装协议时出现如下错误，尝试重新安装后问题依旧
## 2.安装失败的log或者截图
进度  7/12 : 安装Xray 
jq: error (at <stdin>:1): Cannot index string with string "prerelease"
 ---> Xray-core版本: 
 ---> 核心下载失败，请重新尝试安装 
## 3.系统版本
Debian 11 
## 4.脚本版本
v3.1.32

**Comment by mack-a** [comment]
尝试修改dns后重试

**Comment by Fhigr** [comment]
已解决，感谢
