### ISSUE TITLE
脚本 `core管理` - `升级` 存在严重bug

### ISSUE THREAD

**Issue by hawcgn** [mack-a/v2ray-agent#915]
## 1.问题描述
最近版本中的 `16.core管理` -> `升级xxx` 都有问题  
- singbox不能升级到最新release v1.8.1  反而降级到v1.7.8  
- xray核心直接升级报错  

详见下图 👇👇

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/150403800/9c43d8ef-cb1b-44a0-ab3a-26ae653f9d38)

![image](https://github.com/mack-a/v2ray-agent/assets/150403800/18806721-3668-47f8-9412-ac16622090b4)

## 3.系统版本
`Debian GNU/Linux 10 (buster)`
`Debian GNU/Linux 12 (bookworm)`

## 4.脚本版本
`v3.1.32`

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/910

**Comment by hawcgn** [comment]
> #910

ok  sing-box锁定了  我理解的
但是xray-core为什么也报错了

**Comment by mack-a** [comment]
> > #910
> 
> ok sing-box锁定了 我理解的 但是xray-core为什么也报错了

xray-core 重装后再尝试是否还会报错

**Comment by hawcgn** [comment]
重装后可以使用  谢谢
