### ISSUE TITLE
Singbox核心下，warp ipv4疑似没生效

### ISSUE THREAD

**Issue by TAXUEZJU** [mack-a/v2ray-agent#916]
## 1.问题描述
Singbox核心下，warp ipv4疑似没生效
通过脚本安装了Singbox 的 vless+reality+vision 和 Hysteria2，随后通过脚本中的分流工具，选择仅IPV4，添加了whatismyip.com域名后，脚本显示成功，但是访问这个测试网站，显示的还是我本机的IP

## 2.安装失败的log或者截图
```
进度  1/1 : WARP分流[第三方] 
============================================================== 
1.查看已分流域名 
2.添加域名 
3.设置WARP全局 
4.卸载WARP分流 
============================================================== 
请选择:1
sing-box 
{
  "domain": [
    "openai.com",
    "netflix.com",
    "android.chat.openai.com",
    "whatismyip.com"
  ],
  "geosite": [],
  "outbound": "wireguard_out_IPv4"
}
```

## 3.系统版本
Ubuntu 22.04.3

## 4.脚本版本
3.1.32

**Comment by mack-a** [comment]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh
