### ISSUE TITLE
分流工具-Socks5查看分流规则及卸载后仍然生效

### ISSUE THREAD

**Issue by Tkn-9** [mack-a/v2ray-agent#917]
## 1.问题描述
(1)出站端配置好Socks5分流后，查看分流规则提示“**未安装相应功能**”
(2)出站端将Socks5卸载后，访问配置分流的地址依然分流至落地鸡。重启VPS和将地址分流至IPv6都无法使卸载生效

## 2.问题截图
![2024-01-17 141822](https://github.com/mack-a/v2ray-agent/assets/122202865/97e80f8f-11e9-48f2-8a3c-f925ba33a983)
![2024-01-17 142410](https://github.com/mack-a/v2ray-agent/assets/122202865/66b6e301-6ce0-4250-9c75-83e172b0d0ff)

## 3.系统版本
出站端Debian11、入站端Debian12

## 4.脚本版本
出站端为[v3.1.32]更新至[v3.1.34]
入站端为首次安装[v3.1.34]

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.35
