### ISSUE TITLE
VPS升级Xray-core 1.8.6 升级到1.8.7出错

### ISSUE THREAD

**Issue by huzy0909** [mack-a/v2ray-agent#918]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
VPS升级Xray-core 1.8.6 升级到1.8.7出错，出现：
最新版本为:v1.8.7，是否更新？[y/n]:y
/usr/bin/vasma: line 2297: /etc/v2ray-agent/xray/xray: No such file or directory

## 2.安装失败的log或者截图
![Quicker_20240118_135625](https://github.com/mack-a/v2ray-agent/assets/33674729/0dfceede-befb-41f1-be4d-2c51746d35df)

## 3.系统版本
Ubuntu 22.04.3 LTS
5.15.0-87-generic
## 4.脚本版本
v3.1.35

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.1.36 用这个版本试一下
