### ISSUE TITLE
自定义字符串映射为一个 UUIDv5

### ISSUE THREAD

**Issue by lfxx** [mack-a/v2ray-agent#92]
**详细描述建议的内容**
希望可以使用自定义字符串代替随机生成的uuid,便于记忆,也方便填写,xray官方讨论贴:https://github.com/XTLS/Xray-core/issues/158

**Comment by lfxx** [comment]
> **详细描述建议的内容**
> 希望可以使用自定义字符串代替随机生成的uuid,便于记忆,也方便填写,xray官方讨论贴:[XTLS/Xray-core#158](https://github.com/XTLS/Xray-core/issues/158)

当然，这个同时也需要客户端支持也行

**Comment by mack-a** [comment]
目前这个功能不是非必须要添加，还没有要加的打算。可以关注后续更新。
