### ISSUE TITLE
请求sing-box加shadowsocks

### ISSUE THREAD

**Issue by gnz1123** [mack-a/v2ray-agent#921]
ss资源占用和速度稳定性比其他协议更有优势，新版2022-blake3-xxx加密稳定抗封，建议老板在sing-box加入shadowsocks。

**Comment by mack-a** [comment]
目前不会考虑加入可能会被封禁IP的协议，建议自己手动添加。
- 配置文件地址
```
/etc/v2ray-agent/sing-box/conf/config.json
```
