### ISSUE TITLE
[建议]更新脚本后需要一个一键重装的功能

### ISSUE THREAD

**Issue by wsnsnsns** [mack-a/v2ray-agent#925]
**详细描述建议的内容**
更新脚本后需要一个一键重装的功能;
有时还需要卸载后重装,目前比较麻烦;
可参考:
17.更新脚本 
17.1->更新v2ray-agent为最新版本
17.2->备份v2ray-agent配置(包括:核心类型,域名,端口,随机路径,xray配置,Reality key,伪装站点,Salt,等)
17.3->使用备份重新安装v2ray-agent最新版本
可以考虑增加一个配置信息记录文件:记个/etc/v2ray-agent/v2ray-agent-install-config.json
在安装的过程中,在文件中记录信息,便于日后快速卸载及重装;

**Comment by wsnsnsns** [comment]
17.4->查看当前的脚本安装参数;

**Comment by yzx1208** [comment]
这个很好

**Comment by MaleicAcid** [comment]
+1 希望增加配置导出的功能，并支持在安装时使用指定的配置文件，目前的安装过程对自动化流程不友好

**Comment by pbclaodentm** [comment]
这个真可以有，避免因为大版本改动后，影响已经配置好的客户端上网学习

**Comment by MFYDev** [comment]
完全支持，有几次需要重装还要一步一步重新点确实很繁琐，更新完之后要是能有一个一键重装那真的方便的很

**Comment by mack-a** [comment]
暂定记住选项功能

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/issues/1041
