### ISSUE TITLE
sing-box核心使用域名黑名单功能会联不通

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#927]
## 1.问题描述
大佬好，sing-box核心 VLESS reality_vision 使用域名黑名单功能选择屏蔽国内域名。添加完毕后客户端就连不上服务器了。再选删除黑名单就可以正常连接。

## 3.系统版本
Debian11

## 4.脚本版本
v3.1.38

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.4

**Comment by smdx** [comment]
> https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.4

大佬感谢更新，更新后添加国内黑名单正常了。反馈个问题，在查看黑名单时会提示No such file or directory。
![2024-01-30_161422](https://github.com/mack-a/v2ray-agent/assets/9279217/9459bca4-57f2-4cd2-b6db-66d1fb76f70c)
