### ISSUE TITLE
自用的流量仅限于油管及奈非等普通上网，却意外收到GCP警告

### ISSUE THREAD

**Issue by quango-web** [mack-a/v2ray-agent#94]
我们检测到您的Google Cloud Project我的项目（ID：）正在从事加密货币挖矿，导致显示此行为的所有项目资源被暂停。

此活动违反了Google Cloud Platform服务条款或您正在使用的Google API 服务条款。

我们建议您查看此活动以确定它是否有针对性。加密货币挖掘通常表明使用欺诈性帐户和支付工具，我们需要进行验证才能在我们的平台上挖掘加密货币

gcp安装的是VLESS_XTLS/TLS-direct_TCP

**Comment by mack-a** [comment]
脚本readme写了，不建议gcp用户使用。gcp去年就已经开始封禁代理服务。

**Comment by fengshengxie** [comment]
我用gcp 装v2ray ，一直没有收到警告呀，就是ip会别封，要常换
