### ISSUE TITLE
 安装nginx  出现报错

### ISSUE THREAD

**Issue by qq290598268** [mack-a/v2ray-agent#941]
进度  1/9 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，如长时间无反应，请手动停止后重新执行】 
 ---> 安装unzip 
 ---> 安装socat 
 ---> 安装jq 
 ---> 安装binutils 
 ---> 安装qrencode 
 ---> 安装lsb-release 
 ---> 安装nginx 
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
 ---> 安装semanage 
 ---> 安装acme.sh

**Comment by mack-a** [comment]
这个不是报错，是设置自启动信息
