### ISSUE TITLE
订阅链接在v2rayN中无法解析，在小火箭中可以

### ISSUE THREAD

**Issue by szhangcn** [mack-a/v2ray-agent#942]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
生成的订阅链接在v2rayN中无法解析，在小火箭中可以
## 2.安装失败的log或者截图
![无标题](https://github.com/mack-a/v2ray-agent/assets/4902402/def8be68-1d26-463c-b21d-fb989a790c2f)

## 4.脚本版本
V3.2.8

**Comment by shuishou4184** [comment]
我也遇到同样的问题

**Comment by szhangcn** [comment]
用浏览器能打开订阅链接，小火箭能解析，但是v2rayn里就是不行，麻烦作者看一下

**Comment by szhangcn** [comment]
解决了，所有Trojan的选项都不要安装就可以了。

建议在一键安装中不要默认安装Trojan协议

**Comment by mack-a** [comment]
https://t.me/v2rayAgentChannel/1598
