### ISSUE TITLE
服务端配置默认没有开启XRAY入站流量嗅探，会导致分流失败。

### ISSUE THREAD

**Issue by mumuou** [mack-a/v2ray-agent#943]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
如题
## 4.脚本版本
3.2.8

**Comment by mack-a** [comment]
最新版本看到嗅探正常添加
