### ISSUE TITLE
sing-box核心添加国内黑名单后谷歌pay无法下载

### ISSUE THREAD

**Issue by smdx** [mack-a/v2ray-agent#944]
## 1.问题描述
大佬新年好，sing-box核心 VLESS reality_vision 添加国内黑名单后谷歌pay无法下载了，怎么修改相关路由把指定域名强制走代理？谢谢

需要强走代理的域名列表：
gstatic.com
googleapis.cn
googleapis.com
ggpht.cn
1e100.net
connectivitycheck.gstatic.com
xn--ngstr-lra8j.com

## 3.系统版本
Debian 10
## 4.脚本版本
v3.2.8

**Comment by mack-a** [comment]
后续会增加默认规则

**Comment by smdx** [comment]
好的，谢谢。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.11 我加了googleapis.com,googleapis.cn,xn--ngstr-lra8j.com,gstatic.com，你试一下

**Comment by smdx** [comment]
测试添加黑名单后正常下载了，谢谢。
