### ISSUE TITLE
添加伪装站点 那一步老是卡着不动，是怎么回事？

### ISSUE THREAD

**Issue by CatalystLi** [mack-a/v2ray-agent#945]
## 2.安装失败的log或者截图：
<img width="499" alt="屏幕截图 2024-02-11 021443" src="https://github.com/mack-a/v2ray-agent/assets/86453819/b46228e6-35c6-4dde-92a2-a0b75f92c5e1">

**Comment by mack-a** [comment]
尝试修改dns，可能是因为无法下载github文件
