### ISSUE TITLE
xray的分流warp全局不生效

### ISSUE THREAD

**Issue by zanewayne78** [mack-a/v2ray-agent#946]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
最新脚本先安装xray，然后安装hy2和tuic，开启分流warp ipv4全局，但是只有hy2和tuic的sb核心可以用分流，xray不能用，还是本机ip

## 3.系统版本
Ubuntu 20.04
## 4.脚本版本
v3.2.8

**Comment by testRob-hash** [comment]
最新脚本遇到同样问题，中间有重装脚本，Xray内核可以在warp ipv4分流单独添加域名使用，测试过单独添加openai.com，安卓端的chatgpt可以解锁，singbox内核的无法解锁，但是开启ipv4全局之后，singbox内核的可以解锁chatgpt，xray内核的无法解锁。

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.11
