### ISSUE TITLE
ClashMeta订阅链接无法下载，收到GET EOF的错误

### ISSUE THREAD

**Issue by fxchby** [mack-a/v2ray-agent#947]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
无法下载ClashMeta订阅链接

## 2.安装失败的log或者截图
![Screenshot_20240213-174526_Clash Meta for Android](https://github.com/mack-a/v2ray-agent/assets/1815218/fbe7c5e9-535c-4a03-8e3a-7fa8807d2296)

## 3.系统版本
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
## 4.脚本版本
当前版本：v3.2.8

**Comment by hoshibara** [comment]
我也遇到了这个问题，以下是我的解决方案：
删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可
如：
```
proxy_protocol
real_ip_header proxy_protocol;
set_real_ip_from 0.0.0.0/0;
proxy_set_header X-Real-IP $proxy_protocol_addr;
```

**Comment by Zebartin** [comment]
遇到同样问题，v2rayNG也无法更新订阅。按楼上修改后mihomo和v2rayNG都能正常获取订阅。
未修改前浏览器可以正常访问订阅链接，但curl等方式不行，报错“The response ended prematurely”、“Remote end closed connection without response”、“server closed the connection”等

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.18

**Comment by QZQ-QSQ** [comment]
大佬，这个问题我也有，脚本版本v3.2.36。按楼上的方法删除代码也不行。

**Comment by Juanxcg** [comment]
可能要用魔法先翻出去正常下载

**Comment by mack-a** [comment]
> 大佬，这个问题我也有，脚本版本v3.2.36。按楼上的方法删除代码也不行。用浏览器直接打开链接，只有一些规则，但没有节点信息。另外的两个，默认链接和sing box链接是有节点信息的，能正常使用的。

提取节点订阅地址手动在浏览器访问下。

**Comment by QZQ-QSQ** [comment]
> > 大佬，这个问题我也有，脚本版本v3.2.36。按楼上的方法删除代码也不行。用浏览器直接打开链接，只有一些规则，但没有节点信息。另外的两个，默认链接和sing box链接是有节点信息的，能正常使用的。
> 
> 提取节点订阅地址手动在浏览器访问下。

我就是在浏览器里输入订阅地址的。浏览器得到的内容如下：
![捕获](https://github.com/user-attachments/assets/add7153b-729d-4212-9198-e889c687fd89)

**Comment by mack-a** [comment]
找到 proxy-providers: 这个。
下面的url有一个地址，浏览器访问这个地址，查看节点是否出现

**Comment by Ningruizhe** [comment]
> 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> 
> ```
> proxy_protocol
> real_ip_header proxy_protocol;
> set_real_ip_from 0.0.0.0/0;
> proxy_set_header X-Real-IP $proxy_protocol_addr;
> ```

求问这个代码在哪里打开呀

**Comment by hoshibara** [comment]
> > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > ```
> > proxy_protocol
> > real_ip_header proxy_protocol;
> > set_real_ip_from 0.0.0.0/0;
> > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > ```
> 
> 求问这个代码在哪里打开呀

这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件

**Comment by Ningruizhe** [comment]
没想到会有回复，非常感谢🙏过了一天他就自动好了，不知道咋回事，还是谢谢你的答复












Murphy
***@***.***






---原始邮件---
发件人: "Xingyuan ***@***.***&gt;
发送时间: 2025年1月3日(周五) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mack-a/v2ray-agent] ClashMeta订阅链接无法下载，收到GET EOF的错误 (Issue #947)




   
我也遇到了这个问题，以下是我的解决方案： 删除/etc/nginx/conf.d/alone.conf里proxy_protocol相关的内容即可 如：
 proxy_protocol real_ip_header proxy_protocol; set_real_ip_from 0.0.0.0/0; proxy_set_header X-Real-IP $proxy_protocol_addr;   
求问这个代码在哪里打开呀
  
这是很早之前的解决方案，你可以找找/etc/nginx/conf.d/下面的文件

**Comment by hhfll** [comment]
> > > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > > ```
> > > proxy_protocol
> > > real_ip_header proxy_protocol;
> > > set_real_ip_from 0.0.0.0/0;
> > > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > > ```
> > 
> > 
> > 求问这个代码在哪里打开呀
> 
> 这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件

請問這個文件在哪，是在手機的系統文件管理器嗎？我搜索不到

**Comment by eaiu** [comment]
> > > > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > > > ```
> > > > proxy_protocol
> > > > real_ip_header proxy_protocol;
> > > > set_real_ip_from 0.0.0.0/0;
> > > > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > > > ```
> > > 
> > > 
> > > 求问这个代码在哪里打开呀
> > 
> > 
> > 这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件
> 
> 請問這個文件在哪，是在手機的系統文件管理器嗎？我搜索不到

这种情况是获取节点的链接被墙了，手动添加一个节点，使用代理获取

**Comment by hoshibara** [comment]
> > > > > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > > > > ```
> > > > > proxy_protocol
> > > > > real_ip_header proxy_protocol;
> > > > > set_real_ip_from 0.0.0.0/0;
> > > > > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > > > > ```
> > > > 
> > > > 
> > > > 求问这个代码在哪里打开呀
> > > 
> > > 
> > > 这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件
> > 
> > 
> > 請問這個文件在哪，是在手機的系統文件管理器嗎？我搜索不到
> 
> 这种情况是获取节点的链接被墙了，手动添加一个节点，使用代理获取

不是的，当时的场景是：服务器上的其他文件可以正常访问，但subscribe文件无法被clash正确获取。

这个文件是服务器nginx的配置文件，如果你只有客户端，我的解决方案对你是无效的。

**Comment by hhfll** [comment]
> > > > > > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > > > > > ```
> > > > > > proxy_protocol
> > > > > > real_ip_header proxy_protocol;
> > > > > > set_real_ip_from 0.0.0.0/0;
> > > > > > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 求问这个代码在哪里打开呀
> > > > 
> > > > 
> > > > 这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件
> > > 
> > > 
> > > 請問這個文件在哪，是在手機的系統文件管理器嗎？我搜索不到
> > 
> > 
> > 这种情况是获取节点的链接被墙了，手动添加一个节点，使用代理获取
> 
> 不是的，当时的场景是：服务器上的其他文件可以正常访问，但subscribe文件无法被clash正确获取。
> 
> 这个文件是服务器nginx的配置文件，如果你只有客户端，我的解决方案对你是无效的。

那請問只有客戶端可以怎麽解決這個問題呢

**Comment by hoshibara** [comment]
> 那請問只有客戶端可以怎麽解決這個問題呢

@hhfll 我的建议是：
1. 联系你的服务提供商
2. 用chrome/edge直接访问订阅地址，得到订阅文件的文本版本，用编辑器处理后通过clash的本地配置功能导入

**Comment by hhfll** [comment]
> > 那請問只有客戶端可以怎麽解決這個問題呢
> 
> [@hhfll](https://github.com/hhfll) 我的建议是：
> 
> 1. 联系你的服务提供商
> 2. 用chrome/edge直接访问订阅地址，得到订阅文件的文本版本，用编辑器处理后通过clash的本地配置功能导入

訪問了地址，出來的是一行字母和數字，我看不太懂，請問該怎麽編輯呢

**Comment by hoshibara** [comment]
> 訪問了地址，出來的是一行字母和數字，我看不太懂，請問該怎麽編輯呢

share一下前几个字符吧，我看看是什么类型的

**Comment by hhfll** [comment]
> > 訪問了地址，出來的是一行字母和數字，我看不太懂，請問該怎麽編輯呢
> 
> share一下前几个字符吧，我看看是什么类型的

c3M6Ly9ZMmhoWTJoaE1qQXRh
這樣的，有點像某種序列號或者密鑰的形式，我看不懂

**Comment by saltFishCode** [comment]
大概率是该订阅的服务器被墙了，
我使用的**clash meta for Android**也出现_部分订阅_eof，
电脑的clash very倒是没问题，
想办法让自己的手机开启代理（搞一些免费的垃圾vpn）然后再去导入订阅，值得一提的是我这边的规则模式还是无法有效，开全局才可以

**Comment by mack-a** [comment]
大概率此问题是因为订阅地址无法通过直连访问所导致。

**Comment by CandleM6** [comment]
> > > > > 我也遇到了这个问题，以下是我的解决方案： 删除`/etc/nginx/conf.d/alone.conf`里`proxy_protocol`相关的内容即可 如：
> > > > > ```
> > > > > proxy_protocol
> > > > > real_ip_header proxy_protocol;
> > > > > set_real_ip_from 0.0.0.0/0;
> > > > > proxy_set_header X-Real-IP $proxy_protocol_addr;
> > > > > ```
> > > > 
> > > > 
> > > > 求问这个代码在哪里打开呀
> > > 
> > > 
> > > 这是很早之前的解决方案，你可以找找`/etc/nginx/conf.d/`下面的文件
> > 
> > 請問這個文件在哪，是在手機的系統文件管理器嗎？我搜索不到
> 
> 这种情况是获取节点的链接被墙了，手动添加一个节点，使用代理获取

我是直接买的机场，不会弄，怎么办呀，我电脑上可以正常访问，但是手机上连接后urltest超时，链接就显示“get http：....EOF ”

**Comment by 1910324276-pixel** [comment]
连个Wi-Fi就能用了

**Comment by liyuan66666** [comment]
我的解决方案：如果只是在手机上的应用，可以用UU加速器加速steam商店，在vpn开启的同时再试一次就可以了
