### ISSUE TITLE
连接电信宽带或者数据流量，可以正常使用，但连接移动的宽带或流量，就无法使用。

### ISSUE THREAD

**Issue by zgpnuaa** [mack-a/v2ray-agent#948]
## 1.问题描述
连接电信宽带或者数据流量，可以正常使用，但连接移动的宽带或流量，就无法使用。

## 2.安装失败的log或者截图
移动网络下显示延迟是-1，电信网络下正常。

## 3.系统版本
Debian 11 x64

## 4.脚本版本
v3.1.21

**Comment by mack-a** [comment]
和脚本无关，建议排查本地运营商

**Comment by Seaburg97** [comment]
你解决了嘛

> ## 1.问题描述
> 连接电信宽带或者数据流量，可以正常使用，但连接移动的宽带或流量，就无法使用。
> 
> ## 2.安装失败的log或者截图
> 移动网络下显示延迟是-1，电信网络下正常。
> 
> ## 3.系统版本
> Debian 11 x64
> 
> ## 4.脚本版本
> v3.1.21
