### ISSUE TITLE
用二级域名(a.com)+dnsAPI，输入cfAPIToken 后，脚本的判断条件应该有误，导致无法继续了

### ISSUE THREAD

**Issue by Se7enMuting** [mack-a/v2ray-agent#949]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

用二级域名：a.com + dnsAPI，输入cfAPIToken 后，直接跳出:
 `是否使用*.com进行API申请通配符证书？[y/n]:`
选y：后续 acme.sh 申请证书错误
选n：直接跳出脚本

目前脚本的意思应该是用 dnsAPI 的话，只支持三级域名：a.b.com 吧（而且必须用通配符申请证书），所以用二级域名这里应该是要跳到：
`不支持此域名申请通配符证书，建议使用此格式[xx.xx.xx]`

应该是这行判断条件不对
https://github.com/mack-a/v2ray-agent/blob/5b7e1585bc43b015117d0e1910423465c4cd2ad3/install.sh#L1539

表达式不太懂，GPT给的修改意见，哈哈，仅供参考：
`            if ! echo "${dnsTLSDomain}" | grep -qE "^[^.]+\.[^.]+$"; then`

_另外的建议_：dnsAPI模式下，不管输入的是几级域名，都转成二级域名给 dnsTLSDomain ，直接申请通配符+二级域名的组合证书即可：
`--issue -d "*.${dnsTLSDomain}" -d "${dnsTLSDomain}" --dns dns_cf`
这样也不用拘泥于只能用三级域名

## 2.安装失败的log或者截图

![image](https://github.com/mack-a/v2ray-agent/assets/889925/a6a7bc3a-8544-4ed1-98c9-17b4a6df2e95)

## 3.系统版本

Debian 12

## 4.脚本版本

v3.2.8

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.10

**Comment by Travel2Here** [comment]
怎么说？这个问题最新版的脚本还是存在哦。咋关闭了~这个3.2.10的tag打不开了~
