### ISSUE TITLE
您好，它可以和我现有的网站兼容运行吗？

### ISSUE THREAD

**Issue by zed767** [mack-a/v2ray-agent#95]
我可以在搭建我网站的服务器上边，直接使用这个脚本部署吗？谢谢

**Comment by mack-a** [comment]
会冲突

**Comment by zed767** [comment]
有什么方法，可以让他们不冲突吗？

**Comment by mack-a** [comment]
你可以选择先用脚本安装，然后在安装你的服务。需要nginx知识。

**Comment by musaart** [comment]
大佬，能出个宝塔/wordpress共存教程教程么。想在已有网站上搭建。

**Comment by mack-a** [comment]
> 大佬，能出个宝塔/wordpress共存教程教程么。想在已有网站上搭建。

开个单独的issue，说下宝塔 博客的具体搭建教程。

**Comment by sjjjmax** [comment]
> 有什么方法，可以让他们不冲突吗？
"/etc/nginx/conf.d/alone.conf"
root /usr/share/nginx/html  改一下就行了，

**Comment by mack-a** [comment]
> > 有什么方法，可以让他们不冲突吗？
> > "/etc/nginx/conf.d/alone.conf"
> > root /usr/share/nginx/html  改一下就行了，

后续应该会兼容 宝塔之类的，如果想要脚本兼容。需要开一个新issue描述一下你的宝塔以及博客的搭建步骤。我没玩过宝塔。
