### ISSUE TITLE
未检测到端口开放

### ISSUE THREAD

**Issue by FireFoxzzzz** [mack-a/v2ray-agent#950]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
执行脚本到第二步失败，使用搬瓦工vps，ping 自有域名，二级域名均为为vps 的ip地址
当前vps有若干个docker 容器在运行，包含nginx process，nginx日志显示“nginx: [warn] conflicting server name "二级域名" on 0.0.0.0:443, ignored”

## 2.安装失败的log或者截图

请输入端口[默认: 443]，可自定义端口[回车使用默认]
端口:443

 ---> 端口: 443
 ---> 域名IP校验通过
 ---> Nginx启动成功
 ---> Nginx关闭成功
 ---> 未检测到443端口开放，退出安装
 ---> 错误日志：<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
，请将此错误日志通过issues提交反馈

## 3.系统版本
ubuntu 22.04.3
## 4.脚本版本
3.2.8

**Comment by mack-a** [comment]
检测冲突，建议关闭docker后重新执行
