### ISSUE TITLE
Xray启动失败

### ISSUE THREAD

**Issue by Aether-Zh** [mack-a/v2ray-agent#952]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

进度 10/12 : 添加定时维护证书 

 ---> 添加定时维护证书成功 
 ---> Xray关闭成功 
Xray启动失败 
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈

## 2.安装失败的log或者截图

![image](https://github.com/mack-a/v2ray-agent/assets/40912858/173b3928-3765-48aa-9b67-b7b318c85949)

**Comment by mack-a** [comment]
卸载后重新安装一下
