### ISSUE TITLE
3.2.8版本安装sing-box时的一些错误

### ISSUE THREAD

**Issue by 123Diego** [mack-a/v2ray-agent#953]
## 脚本版本:
![IMG_20240219_155520](https://github.com/mack-a/v2ray-agent/assets/49546009/e5fff4dd-0e7a-43ee-b281-fe9080630b4f)
3.2.8

**Comment by mack-a** [comment]
好的，我看一下

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.9
