### ISSUE TITLE
使用域名黑名单功能屏蔽国内域名，再卸载黑名单，然后再屏蔽国内域名后，Xray启动报错

### ISSUE THREAD

**Issue by lilin151** [mack-a/v2ray-agent#954]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
1、使用【15.域名黑名单】功能，选3屏蔽国内域名
2、再选4卸载黑名单
3、然后再选3屏蔽国内域名后，Xray启动报错
备注：还启用了菜单13内的禁用BT下载
操作记录
![image](https://github.com/mack-a/v2ray-agent/assets/33724029/56e0dfed-77c1-494d-a221-65c4f8dabcad)

## 2.安装失败的log或者截图
Xray 1.8.7 (Xray, Penetrates Everything.) 3f0bc13 (go1.21.5 linux/amd64)
A unified platform for anti-censorship.
2024/02/19 21:38:37 Using confdir from arg: /etc/v2ray-agent/xray/conf
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_vision_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json /etc/v2ray-agent/xray/conf/blackhole_out.json /etc/v2ray-agent/xray/conf/z_direct_outbound.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/09_routing.json > infra/conf/serial: failed to read config file > EOF
## 3.系统版本
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-28-amd64
Architecture: x86-64
## 4.脚本版本
v3.2.9

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.10
