### ISSUE TITLE
ipv6 全局分流后GitHub提示无法建立安全连接

### ISSUE THREAD

**Issue by Claire9518** [mack-a/v2ray-agent#955]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

设置 ipv6 全局分流后无法访问 GitHub，提示无法建立安全链接。检查过服务器证书未过期，时间同步情况正常。

## 3.系统版本

ubuntu 22.04.4

## 4.脚本版本

v3.2.11

**Comment by mack-a** [comment]
用的什么核心

**Comment by mack-a** [comment]
github个别域名支持IPv6，全局分流后会导致github无法使用
