### ISSUE TITLE
Debian 11 升级预览版时描述xray文件不存在

### ISSUE THREAD

**Issue by myfalcom** [mack-a/v2ray-agent#958]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
升级最新预览版1.8.8时描述/etc/v2ray-agent/xray/xray不存在，并无法继续执行升级
## 3.系统版本
Debian 11
## 4.脚本版本
3.2.11

**Comment by mack-a** [comment]
重新安装后再升级pre版本
