### ISSUE TITLE
Xray 核心无法升级

### ISSUE THREAD

**Issue by Claire9518** [mack-a/v2ray-agent#959]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

最新版本存在 xray 核心无法升级的情况。选择升级 xray-core 后出现 xray 关闭成功，之后报错提示 no such file or directory

## 2.安装失败的log或者截图

![image](https://github.com/mack-a/v2ray-agent/assets/26239983/3ab6f5f4-1dd4-48d7-986f-73e83c60d1d6)

## 3.系统版本

Ubuntu 22.04.3 LTS

## 4.脚本版本

v3.2.11

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.12
