### ISSUE TITLE
请教大佬，最新脚本默认选项搭建好之后，手机电脑都通，openwrt/梅林的路由不通是什么原因

### ISSUE THREAD

**Issue by dalianjeff** [mack-a/v2ray-agent#96]
找了两天也没找到什么原因，openwrt路由里面用的《passwall/hello world》， 梅林路由用的《科学上网》，结果都是国内通，国外不通，不知道差在哪里了

**Comment by mack-a** [comment]
> 找了两天也没找到什么原因，openwrt路由里面用的《passwall/hello world》， 梅林路由用的《科学上网》，结果都是国内通，国外不通，不知道差在哪里了

可以来tg群问问，我没玩过这个。

**Comment by mack-a** [comment]
> 找了两天也没找到什么原因，openwrt路由里面用的《passwall/hello world》， 梅林路由用的《科学上网》，结果都是国内通，国外不通，不知道差在哪里了

一般都是SNI HOST什么的填写不对
