### ISSUE TITLE
升级xray-core内核正式版与预览版选项错误

### ISSUE THREAD

**Issue by Array-Cats** [mack-a/v2ray-agent#960]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
选择正式版（1选项）检测的是预览版，选择预览版（2选项检测的是正式版）
## 2.安装失败的log或者截图
![Snipaste_2024-02-27_10-43-56](https://github.com/mack-a/v2ray-agent/assets/33084797/459a5445-adb4-40d9-b82a-4c2e6dd2c724)
![Snipaste_2024-02-27_10-44-28](https://github.com/mack-a/v2ray-agent/assets/33084797/4cab8471-d942-4a2c-8ace-6f5c903a445d)
## 3.系统版本
脚本侧bug
## 4.脚本版本
3.2.11

**Comment by mack-a** [comment]
现在是正式版，不是预览版

**Comment by Array-Cats** [comment]
> 现在是正式版，不是预览版

ORZ，才几个小时就从预览变正式了，没注意
