### ISSUE TITLE
Clash-verge配置无法使用日志如下

### ISSUE THREAD

**Issue by zhaolsy** [mack-a/v2ray-agent#962]
1.按照客户端使用Clash-verge配置完成无法访问谷歌浏览器

2.Clash-verge 日志信息

![微信截图_20240229174153](https://github.com/mack-a/v2ray-agent/assets/115966060/c0d0472f-658a-4efd-b51b-bdd63a059cb7)

3.系统版本：Ubuntu-20.04.1-x64

4.脚本版本: 脚本参照连接【https://www.v2ray-agent.com/archives/1682491479771】，使用的是一快速开始

**Comment by mack-a** [comment]
规则下载成功了吗

**Comment by zhaolsy** [comment]
我配置的订阅链接是http://域名/s/clashMetaProfile/12345  但是日志报错 initial proxy provider qfeycfqphg_provider error: Get "https://域名/s/clashMeta/12345": EOF
这个是什么原因呢

**Comment by mack-a** [comment]
内核有没有切换成clashmeta

**Comment by zhaolsy** [comment]
内核已经切换到clashmeta

![image](https://github.com/mack-a/v2ray-agent/assets/115966060/4ca4b292-5892-4818-81c5-2a257a99da46)

日志现在报错这个

![Uploading image.png…]()

**Comment by zhaolsy** [comment]
日志还是同上面的

**Comment by mack-a** [comment]
建议把配置删掉重新添加一下

**Comment by zhaolsy** [comment]
配置删除掉重新添加也还是不行
![001](https://github.com/mack-a/v2ray-agent/assets/115966060/a03e89ee-a917-4665-ba8e-10b24456d8d5)
![002](https://github.com/mack-a/v2ray-agent/assets/115966060/e8b59931-2ddf-441c-bdcc-8547cbe3b004)
