### ISSUE TITLE
安装证书的时候异常

### ISSUE THREAD

**Issue by Klosw** [mack-a/v2ray-agent#966]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
安装证书的时候提示是否用通配符 进行匹配 选择 n 直接退出脚本  

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/13143959/41710639-84ea-4cfe-845d-fec3406ce111)

![image](https://github.com/mack-a/v2ray-agent/assets/13143959/cf0f2a8f-894f-43ea-ab42-62761b0f94a2)

**Comment by mack-a** [comment]
提供截图

**Comment by mack-a** [comment]
这里选择n，流程就结束了。如有需要请重新执行
