### ISSUE TITLE
parse error: Expected value before ',' at line 4, column 19

### ISSUE THREAD

**Issue by Aether-Zh** [mack-a/v2ray-agent#967]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述

![image](https://github.com/mack-a/v2ray-agent/assets/40912858/9d0ca7c3-4771-4729-a9da-98cb4e8e77e7)

## 2.安装失败的log或者截图

![image](https://github.com/mack-a/v2ray-agent/assets/40912858/96170ea0-7b2c-45da-8e87-bfcacd2a4d07)

## 3.系统版本

CentOS Linux release 7.9.2009 (Core)

Linux ideal-nodes-1.localdomain 4.10.4-1.el7.elrepo.x86_64 #1 SMP Sat Mar 18 12:50:10 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

## 4.脚本版本

![image](https://github.com/mack-a/v2ray-agent/assets/40912858/2366c3d6-d871-4c89-ac68-c38e4a805858)

**Comment by mack-a** [comment]
尝试卸载重装
