### ISSUE TITLE
更新xray版本时，报错。

### ISSUE THREAD

**Issue by yoohooyoo** [mack-a/v2ray-agent#968]
更新xray版本，报错。并且本来可以运行的xray bin文件被删掉了。
脚本为当前最新版3.2.14.
尝试过卸载重装。重装后只要更新，仍然出现同样问题。

报错信息如下：

进度  1/1 : Xray版本管理 
1.升级Xray-core 
2.升级Xray-core 预览版 
3.回退Xray-core 
4.关闭Xray-core 
5.打开Xray-core 
6.重启Xray-core 
7.更新geosite、geoip 
8.设置自动更新geo文件[每天凌晨更新] 
9.查看日志 

请选择:1
 ---> 当前Xray-core版本:1.8.8 
当前版本与最新版相同，是否重新安装？[y/n]:y
 ---> Xray关闭成功 
/usr/bin/vasma: line 2318: /etc/v2ray-agent/xray/xray: No such file or directory
 ---> 当前Xray-core版本: 
/usr/bin/vasma: line 2337: /etc/v2ray-agent/xray/xray: No such file or directory
最新版本为:v1.8.8，是否更新？[y/n]:y
rm: cannot remove '/etc/v2ray-agent/xray/xray': No such file or directory
/usr/bin/vasma: line 2318: /etc/v2ray-agent/xray/xray: No such file or directory
 ---> 当前Xray-core版本: 
/usr/bin/vasma: line 2337: /etc/v2ray-agent/xray/xray: No such file or directory
最新版本为:v1.8.8，是否更新？[y/n]:n
 ---> 放弃更新

**Comment by mack-a** [comment]
<img width="470" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/57424792/61d47a2e-402f-433a-8dae-f27a8d0c540b">
<img width="404" alt="image" src="https://github.com/mack-a/v2ray-agent/assets/57424792/7924fc3b-94ce-41d1-b74a-1adb194e4eff">
升级正式版和预览版均未复现

**Comment by yoohooyoo** [comment]
使用新版3.2.18，再次出现。

 ---> 当前Xray-core版本:1.8.8 
最新版本为:v1.8.9，是否更新？[y/n]:y
/usr/bin/vasma: line 2334: /etc/v2ray-agent/xray/xray: No such file or directory
 ---> 当前Xray-core版本: 
/usr/bin/vasma: line 2353: /etc/v2ray-agent/xray/xray: No such file or directory
最新版本为:v1.8.9，是否更新？[y/n]:
