### ISSUE TITLE
使用LESS reality_vision和VLESS reality_gRPC时提示infra/conf: empty "publicKey"，无法连接网络

### ISSUE THREAD

**Issue by Journey17** [mack-a/v2ray-agent#969]
## 1.问题描述：在v2rayN上使用脚本创建的VLESS reality_vision和VLESS reality_gRPC时无法连接网络，日志中提示：infra/conf: Failed to build REALITY config. > infra/conf: empty "publicKey"
Cannot mix synchronous and asynchronous operation on process stream.

## 2.安装失败的log或者截图：
![PixPin_2024-03-07_17-00-53](https://github.com/mack-a/v2ray-agent/assets/25453731/a2a8d4a0-6fb2-4483-b5df-b3c3fdbbd58b)

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.16
