### ISSUE TITLE
甲骨文云安卓无法使用

### ISSUE THREAD

**Issue by sw586** [mack-a/v2ray-agent#97]
**详细描述建议的内容**
作者：mack-a 
当前版本：v2.3.15 
Github：https://github.com/mack-a/v2ray-agent 
描述：七合一共存脚本 
============================================================== 
1.安装 
2.任意组合安装 
-------------------------工具管理----------------------------- 
3.账号管理 
4.更换伪装站 
5.更新证书 
6.更换CDN节点 
7.ipv6人机验证 
-------------------------版本管理----------------------------- 
8.core版本管理 
9.更新Trojan-Go 
10.更新脚本 
11.安装BBR、DD脚本 
-------------------------脚本管理----------------------------- 
12.查看日志 
13.卸载脚本 
============================================================== 
快捷方式创建成功，可执行[vasma]重新打开脚本 
请选择:1

功能 1/1 : 选择核心安装 

============================================================== 
1.Xray-core 
2.v2ray-core 
3.v2ray-core[XTLS] 
============================================================== 
请选择：1

进度  2/17 : 安装工具 
 ---> 检查、安装更新【新机器会很慢，耐心等待】 

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 ---> 安装binutils 
 ---> 安装semanage 

进度  3/17 : 初始化Nginx申请证书配置 

请输入要配置的域名 例：blog.v2ray-agent.com ---> 
域名:j6.XXXX.ml

 ---> 配置Nginx 

检查IP是否设置为当前VPS 
 ---> 检查ipv4中 

当前域名的IP为 [152.xxxXXX]，是否正确[y/n]？y

 ---> IP确认完成 

检查Nginx是否正常访问 

 ---> Nginx配置成功 

进度  4/17 : 申请TLS证书
 
 ---> 安装TLS证书 
 ---> TLS生成成功 

进度  5/17 : 配置Nginx 

进度  6/17 : 生成随机路径 
请输入自定义路径[例: alone]，不需要斜杠，[回车]随机路径 
路径:
path：mnwc 

---------------------------- 
 ---> V2Ray关闭成功 

进度  7/17 : 安装Xray 
 ---> Xray-core版本:v1.2.4 
Xray-linux-64.zip                   100%[=================================================================>]   8.37M  5.33MB/s    in 1.6s    

进度  8/17 : 配置Xray开机自启 
Created symlink /etc/systemd/system/multi-user.target.wants/xray.service → /etc/systemd/system/xray.service.
 ---> 配置Xray开机自启成功 

进度  9/17 : 安装Trojan-Go 
 ---> Trojan-Go版本:v0.8.2 
trojan-go-linux-amd64.zip           100%[=================================================================>]   6.41M  7.86MB/s    in 0.8s    

进度  10/17 : 配置Trojan开机自启 
Created symlink /etc/systemd/system/multi-user.target.wants/trojan-go.service → /etc/systemd/system/trojan-go.service.
 ---> 配置Trojan开机自启成功 

进度 11/17 : 添加DNS智能解析 

 移动:XXXX
 联通:amp.cloudflare.com 
 电信:www.digitalocean.com 
---------------------------- 
是否使用？[y/n]:n

进度 12/17 : 初始化Xray配置 

 ---> 使用成功 

进度 13/17 : 初始化Trojan配置 

进度 15/17 : 添加伪装站点 
 ---> 添加伪装站点成功 
 ---> Xray关闭成功 
 ---> Xray启动成功 
 ---> Trojan-Go关闭成功 
 ---> Trojan-Go启动成功 

进度 16/17 : 验证服务启动状态 
 ---> 服务启动成功 

进度 17/17 : 账号 
===================== VLESS TCP TLS/XTLS-direct/XTLS-splice ======================
 
 ---> 通用格式(VLESS+TCP+TLS/xtls-rprx-direct) 
    vless://XXX
 XXXXXX

电脑端：v2rayN正常
安卓端：v2rayNG 无法使用（打不开谷、油）

**Comment by mack-a** [comment]
仔细检查下参数 多尝试下 或者截图客户端 配置

**Comment by sw586** [comment]
> 仔细检查下参数多尝试下或截图客户端配置

![image](https://user-images.githubusercontent.com/24788222/107233474-9c32a680-6a5d-11eb-956e-ac81791ab997.png)
![image](https://user-images.githubusercontent.com/24788222/107234170-562a1280-6a5e-11eb-9c5e-e4dcc2f4d36b.png)
![image](https://user-images.githubusercontent.com/24788222/107234232-68a44c00-6a5e-11eb-9c64-91649ad1380a.png)

经过测试在vultr.com服务商测试不存在此故障，在甲骨文云oraclecloud.com下安卓端：v2rayNG始终无法上网

**Comment by sjjjmax** [comment]
> > 仔细检查下参数多尝试下或截图客户端配置
> 
> ![image](https://user-images.githubusercontent.com/24788222/107233474-9c32a680-6a5d-11eb-956e-ac81791ab997.png)
> ![image](https://user-images.githubusercontent.com/24788222/107234170-562a1280-6a5e-11eb-9c5e-e4dcc2f4d36b.png)
> ![image](https://user-images.githubusercontent.com/24788222/107234232-68a44c00-6a5e-11eb-9c64-91649ad1380a.png)
> 
> 经过测试在vultr.com服务商测试不存在此故障，在甲骨文云oraclecloud.com下安卓端：v2rayNG始终无法上网

v2rayN 底层传输安全   "TLS"

**Comment by qq280579056** [comment]
哥们我也遇到了 安卓甲骨文 v2rayng xray vless 其它vps相同的配置都正常

**Comment by superabbite1** [comment]
安卓甲骨文 v2rayng xray vless 我是正常的
