### ISSUE TITLE
管理其他订阅，附加订阅中的naive用户名被添加了机器别名，naive无法连接

### ISSUE THREAD

**Issue by yd2005** [mack-a/v2ray-agent#971]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
管理其他订阅，附加订阅的naive用户名被添加了机器别名，naive无法连接。
## 3.系统版本
Debian 12
## 4.脚本版本
v3.2.18

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.35
