### ISSUE TITLE
新增的Sing-box订阅功能发现几处BUG

### ISSUE THREAD

**Issue by iseku** [mack-a/v2ray-agent#973]
## 1.问题描述
BUG1: 
hysteria2协议的up_mbps和down_mbps参数需要写成数值，目前是字符串，客户端解析时会出错
<img width="325" alt="截屏2024-03-13 15 22 45" src="https://github.com/mack-a/v2ray-agent/assets/46520618/bdba8826-c181-4d6b-a37d-5e08ce77cbfe">
<img width="260" alt="截屏2024-03-13 15 21 52" src="https://github.com/mack-a/v2ray-agent/assets/46520618/2c76d66a-36d8-4b10-8c8b-2dc2e55fa400">
需要写成:       "up_mbps": 50, "down_mbps": 1000,

BUG2:
tuic协议的uuid和password在生成订阅时做了错误连接，应该是 "uuid": "${uuid}" , "password": "${password}", 但是却成了
"uuid": "${uuid}下划线${password}" , "password": "${uuid}下划线${password}", 客户端解析时也会因为"_"而出错。
![截屏2024-03-13 15 31 32](https://github.com/mack-a/v2ray-agent/assets/46520618/f0e057f3-c38f-44ed-9cbf-79af6a42eb1b)
<img width="259" alt="截屏2024-03-13 15 28 01" src="https://github.com/mack-a/v2ray-agent/assets/46520618/83d51071-b33e-4d05-9901-cc5d0c6bf5ec">

BUG3:
这个应该是功能上未实现也算不上是bug：脚本未自动修改nginx配置，远程无法打开sing-box订阅，需要在nginx配置里手工添加sing-box关键字。

另外一个问题：最新版本还不支持sing-box订阅的合并吧？试了下似乎不行

## 3.系统版本
Ubuntu 20.04.6 LTS
## 4.脚本版本
3.2.20

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.21
