### ISSUE TITLE
无法关闭端口

### ISSUE THREAD

**Issue by testRob-hash** [mack-a/v2ray-agent#974]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
使用脚本添加端口，再次使用脚本删除端口无法删除规则，输入ufw命令看端口还在列表显示Allow in

## 3.系统版本
Debian 11

## 4.脚本版本
v3.2.20

**Comment by mack-a** [comment]
脚本只会主动添加，不会主动删除规则，需要手动删除
