### ISSUE TITLE
在v3.2.24版本中only ipv6的vps安装sing-box内核+hysterai2后生成的json配置文件会无法获取主机ip信息

### ISSUE THREAD

**Issue by cukewu** [mack-a/v2ray-agent#978]
1.问题描述
在v3.2.24版本中only ipv6的vps安装sing-box内核+hysterai2后生成的json配置文件会无法获取主机ip信息
2.安装失败的log或者截图
生成的json配置文件中， "server":字段只有端口无主机ip信息
3.系统版本
ubuntu2204
4.脚本版本
3.2.24

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.25
