### ISSUE TITLE
脚本如何对接已有网站

### ISSUE THREAD

**Issue by musaart** [mack-a/v2ray-agent#98]
**详细描述建议的内容**
1.已有网站比如wordprdss 等如何作为伪装站点使用，而非内置的纯html静态网页
2.是否可以出一个与宝塔面板对接的教程方便使用，很多站长使用宝塔面板管理网站，是否可以使用此脚本对接。

**Comment by mack-a** [comment]
请详细描述相关博客、宝塔内容是怎样搭建的 你说的那两个我没玩过需要详细的描述怎么搭建的

**Comment by musaart** [comment]
大佬，我以为你的博客也是wordpress搭建的，wordpress是全球目前使用人数最多的开源博客程序。是php环境的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mack-a"<notifications@github.com&gt;; 
发送时间: 2021年2月12日(星期五) 晚上6:54
收件人: "mack-a/v2ray-agent"<v2ray-agent@noreply.github.com&gt;; 
抄送: "上善若水"<2584623954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mack-a/v2ray-agent] 脚本如何对接已有网站 (#98)





 
请详细描述相关博客、宝塔内容是怎样搭建的 你说的那两个我没玩过需要详细的描述怎么搭建的

**Comment by Be90nia** [comment]
我试过在宝塔面板下安装xray.是无法正常启动xray..
具体哪里出问题了..暂时也不清楚

**Comment by mack-a** [comment]
你们如果需要兼容宝塔、wordpress，请把宝塔、wordpress搭建的过程详细描述下或者给相应的教程，本人没有玩过宝塔。

**Comment by musaart** [comment]
https://raw.githubusercontent.com/atrandys/xray/main/install_wp.sh 大佬参考一下这个脚本

**Comment by Lasx** [comment]
能对接宝塔就好了。

**Comment by twcoin** [comment]
可否分离一个脚本出来，不需要那些什么软件，只是安装，能方面后期更新内核，配置文件之类完全可以自己编写。

**Comment by mack-a** [comment]
> 可否分离一个脚本出来，不需要那些什么软件，只是安装，能方面后期更新内核，配置文件之类完全可以自己编写。

安装什么   只安装核心吗 只安装核心xray官方有这样的脚本

**Comment by musaart** [comment]
https://www.youtube.com/watch?v=gOOJSLICiK4  宝塔+wordpress+xray可以观看此视频解决

**Comment by twcoin** [comment]
> > 可否分离一个脚本出来，不需要那些什么软件，只是安装，能方面后续更新内核，配置文件之类完全可以自己编写。
> 
> 安装什么只安装核心吗只安装核心xray官方有这样的脚本

或者在原脚本上加一个只安装核心的脚本的选项，给需要自己配置相关软件的多一个选择，这只是我的想法。毕竟只用于FQ的用户只是一部分。

**Comment by mack-a** [comment]
> > > 可否分离一个脚本出来，不需要那些什么软件，只是安装，能方面后续更新内核，配置文件之类完全可以自己编写。
> > 
> > 
> > 安装什么只安装核心吗只安装核心xray官方有这样的脚本
> 
> 或者在原脚本上加一个只安装核心的脚本的选项，给需要自己配置相关软件的多一个选择，这只是我的想法。毕竟只用于FQ的用户只是一部分。

我觉得分离出来就和官方的冲突了，即使分离出来还要兼容很多东西得不偿失。
面向小白的一键脚本不搞那么复杂，如果可以自己写配置文件就直接用官方的就可以，他们写的都已经非常全面了。

**Comment by liwenjie119** [comment]
也有需求对接宝塔，可以脚本需要nginx的部分跳过，设置好xray部分，然后手动设置nginx，脚本给出nginx网站conf需要修改的部分就行

**Comment by liwenjie119** [comment]
也有需求对接宝塔，可以脚本需要nginx的部分跳过，设置好xray部分，然后手动设置nginx，脚本给出nginx网站conf需要修改的部分就行

**Comment by hiyuxiang** [comment]
centos 8(4.18.0-240.22.1.el8_3.x86_64)装完后，伪装站点无法访问，提示“未发送任何数据。
ERR_EMPTY_RESPONSE”要怎么破。

**Comment by mack-a** [comment]
已移动到 https://github.com/mack-a/v2ray-agent/issues/76

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v2.5.39 已更新beta1版本
