### ISSUE TITLE
v2ray-agent全新安装后warp分流功能不起效果

### ISSUE THREAD

**Issue by Xunflash** [mack-a/v2ray-agent#985]
## 1.问题描述
脚本全新安装后warp分流功能不起效果

## 2.安装失败的log或者截图

```
install.log:
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.net
 * elrepo-kernel: ftp.yz.yamagata-u.ac.jp
 * epel: ftp.riken.jp
 * extras: mirrors.cat.net
 * updates: mirrors.cat.net
Resolving Dependencies
--> Running transaction check
---> Package docker-buildx-plugin.x86_64 0:0.13.0-1.el7 will be updated
---> Package docker-buildx-plugin.x86_64 0:0.13.1-1.el7 will be an update
---> Package docker-ce.x86_64 3:25.0.4-1.el7 will be updated
---> Package docker-ce.x86_64 3:25.0.5-1.el7 will be an update
---> Package docker-ce-cli.x86_64 1:25.0.4-1.el7 will be updated
---> Package docker-ce-cli.x86_64 1:25.0.5-1.el7 will be an update
---> Package docker-ce-rootless-extras.x86_64 0:25.0.4-1.el7 will be updated
---> Package docker-ce-rootless-extras.x86_64 0:25.0.5-1.el7 will be an update
---> Package docker-compose-plugin.x86_64 0:2.24.7-1.el7 will be updated
---> Package docker-compose-plugin.x86_64 0:2.25.0-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                     Arch     Version          Repository          Size
================================================================================
Updating:
 docker-buildx-plugin        x86_64   0.13.1-1.el7     docker-ce-stable    14 M
 docker-ce                   x86_64   3:25.0.5-1.el7   docker-ce-stable    26 M
 docker-ce-cli               x86_64   1:25.0.5-1.el7   docker-ce-stable    14 M
 docker-ce-rootless-extras   x86_64   25.0.5-1.el7     docker-ce-stable   9.4 M
 docker-compose-plugin       x86_64   2.25.0-1.el7     docker-ce-stable    13 M

Transaction Summary
================================================================================
Upgrade  5 Packages

Total download size: 76 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
--------------------------------------------------------------------------------
Total                                               41 MB/s |  76 MB  00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : docker-compose-plugin-2.25.0-1.el7.x86_64                   1/10 
  Updating   : docker-buildx-plugin-0.13.1-1.el7.x86_64                    2/10 
  Updating   : 1:docker-ce-cli-25.0.5-1.el7.x86_64                         3/10 
  Updating   : docker-ce-rootless-extras-25.0.5-1.el7.x86_64               4/10 
  Updating   : 3:docker-ce-25.0.5-1.el7.x86_64                             5/10 
  Cleanup    : 3:docker-ce-25.0.4-1.el7.x86_64                             6/10 
  Cleanup    : docker-ce-rootless-extras-25.0.4-1.el7.x86_64               7/10 
  Cleanup    : 1:docker-ce-cli-25.0.4-1.el7.x86_64                         8/10 
  Cleanup    : docker-buildx-plugin-0.13.0-1.el7.x86_64                    9/10 
  Cleanup    : docker-compose-plugin-2.24.7-1.el7.x86_64                  10/10 
  Verifying  : 1:docker-ce-cli-25.0.5-1.el7.x86_64                         1/10 
  Verifying  : docker-ce-rootless-extras-25.0.5-1.el7.x86_64               2/10 
  Verifying  : 3:docker-ce-25.0.5-1.el7.x86_64                             3/10 
  Verifying  : docker-buildx-plugin-0.13.1-1.el7.x86_64                    4/10 
  Verifying  : docker-compose-plugin-2.25.0-1.el7.x86_64                   5/10 
  Verifying  : docker-compose-plugin-2.24.7-1.el7.x86_64                   6/10 
  Verifying  : docker-buildx-plugin-0.13.0-1.el7.x86_64                    7/10 
  Verifying  : docker-ce-rootless-extras-25.0.4-1.el7.x86_64               8/10 
  Verifying  : 1:docker-ce-cli-25.0.4-1.el7.x86_64                         9/10 
  Verifying  : 3:docker-ce-25.0.4-1.el7.x86_64                            10/10 

Updated:
  docker-buildx-plugin.x86_64 0:0.13.1-1.el7                                    
  docker-ce.x86_64 3:25.0.5-1.el7                                               
  docker-ce-cli.x86_64 1:25.0.5-1.el7                                           
  docker-ce-rootless-extras.x86_64 0:25.0.5-1.el7                               
  docker-compose-plugin.x86_64 0:2.25.0-1.el7                                   

Complete!

```

安装步骤：
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/eb6833e3-d577-4af0-ac2d-7bda2a2e4d50)
conf文件夹内容：
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/bec54c3c-b3f4-4de0-b39a-c7a524c3d416)

![image](https://github.com/mack-a/v2ray-agent/assets/71567536/62a8e037-5a21-4406-8caa-e458eca09355)

访问一次 https://chat.openai.com/cdn-cgi/trace 后打开access.log发现并没有正常分流到wireguard_out_IPv6这里：
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/b4edbb13-0f5e-46f4-970d-be6b125636b8)

_Originally posted by @Xunflash in https://github.com/mack-a/v2ray-agent/issues/981#issuecomment-2008761474_
            
## 3.系统版本
```
root@glowing-echo-1:~# uname -a
Linux glowing-echo-1.localdomain 6.8.1 #1 SMP PREEMPT_DYNAMIC Sat Mar 16 08:28:33 CST 2024 x86_64 GNU/Linux
```
## 4.脚本版本
v3.2.32 
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```  
- 协议(VLESS+TLS_Vision+TCP)
```
VLESS+Reality+Vision VLESS+Reality+gRPC
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```

**Comment by BallM8964** [comment]
你这算好的，我的现在warp一输入域名就自动boom

请按照上面示例录入域名:alibaba
---> 添加完毕
---> Xray关闭成功
Xray启动失败
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈
root@vmhk-intl-001:/etc/v2ray-agent/xray# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.9 (Xray, Penetrates Everything.) 37f8654 (go1.22.1 linux/amd64)
A unified platform for anti-censorship.
2024/03/20 10:39:01 Using confdir from arg: /etc/v2ray-agent/xray/conf
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_vision_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json /etc/v2ray-agent/xray/conf/IPv6_out.json /etc/v2ray-agent/xray/conf/blackhole_out.json /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json /etc/v2ray-agent/xray/conf/z_direct_outbound.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json > infra/conf/serial: failed to read config file at line 20 char 21 > invalid character ',' looking for beginning of value

**Comment by mack-a** [comment]
> 你这算好的，我的现在warp一输入域名就自动boom
> 
> 请按照上面示例录入域名:alibaba ---> 添加完毕 ---> Xray关闭成功 Xray启动失败 请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈 root@vmhk-intl-001:/etc/v2ray-agent/xray# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf Xray 1.8.9 (Xray, Penetrates Everything.) 37f8654 (go1.22.1 linux/amd64) A unified platform for anti-censorship. 2024/03/20 10:39:01 Using confdir from arg: /etc/v2ray-agent/xray/conf Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_vision_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json /etc/v2ray-agent/xray/conf/IPv6_out.json /etc/v2ray-agent/xray/conf/blackhole_out.json /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json /etc/v2ray-agent/xray/conf/z_direct_outbound.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json > infra/conf/serial: failed to read config file at line 20 char 21 > invalid character ',' looking for beginning of value

脚本卸载后重新下载，应该是下载文件导致乱码所致。如还有问题请单独开issue。

**Comment by mack-a** [comment]
你的最后一张log图没有出现 chat.openai.com 这个域名，可以根据 执行 **vasma->16->1->9->2** 监听日志后，使用本地浏览器访问，等待日志出现后反馈。

**Comment by Xunflash** [comment]
> 你的最后一张log图没有出现 chat.openai.com 这个域名，可以根据 执行 **vasma->16->1->9->2** 监听日志后，使用本地浏览器访问，等待日志出现后反馈。 @Xunflash

![image](https://github.com/mack-a/v2ray-agent/assets/71567536/4c5b09ee-c7f4-4a62-9684-01a547e561c8)

我的访问全是显示的ip地址，这是啥问题啊，是我用的代理软件的问题吗，我测了pc的v2rayN和安卓上的Nekobox，都是只有IP地址没有域名

**Comment by Xunflash** [comment]
> 本地的嗅探

感谢大佬，已解决，安卓端NekoBox需要在设置中把流量探测模式改为探测结果用于目标地址，V2rayN我测了下发下是因为我开了TUN模式导致于发送到服务端都是ip地址，把TUN模式关闭就可以了
