### ISSUE TITLE
多VPS合并后，订阅可以正常拉取，但除了主VPS之外其他的VPS节点测速连接都超时。

### ISSUE THREAD

**Issue by oraoraoraaa** [mack-a/v2ray-agent#987]
## 1.问题描述
在按照要求（email名一致、salt一致、端口一致）配置完成所有的VPS后，所有的VPS单独都能正常使用，设置主VPS后，可以正常拉取其他VPS的订阅，但是在测速时，除了主VPS节点正常使用之外，其他的VPS节点均超时。

## 2.安装失败的log或者截图
![Screenshot 2024-03-23 132616](https://github.com/mack-a/v2ray-agent/assets/50160604/f22deca1-b3fe-4153-aeec-4941fc1ab853)
图中，能够正常测速的是主VPS节点，超时的为其他被合并的VPS。

## 3.系统版本
[ubuntu-2204-jammy-v20240319]

## 4.脚本版本
v3.2.33

## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
xray-core
```  
- 协议(VLESS+TLS_Vision+TCP)
```
VLESS+TCP[TLS_Vision], VLESS+Reality+Vision, VLESS+Reality+gRPC
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.35
