### ISSUE TITLE
使用hysteria2协议，反而更慢了

### ISSUE THREAD

**Issue by finvv** [mack-a/v2ray-agent#989]
## 1.问题描述
都说使用hysteria2会让垃圾vps起飞，但是用搭建后反而更慢了，我是和grpc协议做对比，延时和下载都更高了，不知是我的racknerd机子太差的缘故吗？

## 3.系统版本
debian10
## 4.脚本版本
3.2.33
## 5.安装的内核、协议、安装方式
任意组合安装，xray-core和sing-box核心都单独试过，grpc套cdn就快，用hysteria2就很慢

**Comment by mack-a** [comment]
UDP取决于你本地的宽带是否进行QoS

**Comment by finvv** [comment]
> UDP取决于你本地的宽带是否进行QoS

我是小白，看不懂啥意思，请指教。。。
是指我的hy2走的是udp，本地运营商对我限速了是吗？那如何让hy2走tcp呢？
