### ISSUE TITLE
Xray安装错误

### ISSUE THREAD

**Issue by waxy955** [mack-a/v2ray-agent#99]
进度  7/17 : 安装Xray 
 ---> Xray-core版本: 
unzip:  cannot find or open /etc/v2ray-agent/xray/Xray-linux-64.zip, /etc/v2ray-agent/xray/Xray-linux-64.zip.zip or /etc/v2ray-agent/xray/Xray-linux-64.zip.ZIP.
chmod: cannot access '/etc/v2ray-agent/xray/xray': No such file or directory

**Comment by mack-a** [comment]
> 进度 7/17 : 安装Xray
> ---> Xray-core版本:
> unzip: cannot find or open /etc/v2ray-agent/xray/Xray-linux-64.zip, /etc/v2ray-agent/xray/Xray-linux-64.zip.zip or /etc/v2ray-agent/xray/Xray-linux-64.zip.ZIP.
> chmod: cannot access '/etc/v2ray-agent/xray/xray': No such file or directory

先用v2ray、等xray发布release就可以用了

**Comment by AaronWing** [comment]
遇到同样的问题：
![image](https://user-images.githubusercontent.com/22290329/107872896-c74b4900-6ee8-11eb-9b10-57cdaf579267.png)

**Comment by mack-a** [comment]
> 遇到同样的问题：
> ![image](https://user-images.githubusercontent.com/22290329/107872896-c74b4900-6ee8-11eb-9b10-57cdaf579267.png)

稍后会修复

**Comment by mack-a** [comment]
v2.3.16 已修复
