### ISSUE TITLE
singbox订阅不支持全局代理

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#990]
## 1.问题描述
客户端拉取最新版的v2ray-agent的singbox订阅后，开启global代理，无法使用
## 2.安装失败的log或者截图
无
## 3.系统版本
ubuntu22.04
## 4.脚本版本
v3.2.24
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
sing-box
```  
- 协议(VLESS+TLS_Vision+TCP)
```
VLESS+TCP[TLS_Vision] Hysteria2 VLESS+Reality+Vision VLESS+Reality+gRPC Tuic
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2
```

**Comment by pbclaodentm** [comment]
我咨询下楼主，本身我一直用八合一的脚本，但安装的方式是选的xray核心的，现在已经有8个协议了，我如果任意组合再安装一个sing-box的，我以前的八个协议还能正常服务不呢，我主要是想试用下sing box这个新东东，请教。

**Comment by bettswang** [comment]
> 我咨询下楼主，本身我一直用八合一的脚本，但安装的方式是选的xray核心的，现在已经有8个协议了，我如果任意组合再安装一个sing-box的，我以前的八个协议还能正常服务不呢，我主要是想试用下sing box这个新东东，请教。

那肯定不行了呀，任意组合安装就是重新部署了。

**Comment by bettswang** [comment]
在版本v3.2.40, 增加了http_proxy后已经解决。开启global代理后，选择手动设置节点进行代理。
