### ISSUE TITLE
warp分流域名singbox不能分次添加，保存

### ISSUE THREAD

**Issue by zanewayne78** [mack-a/v2ray-agent#995]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述
分流添新域名是sing box只有最后的域名分流，比如我最后要添加的是ehentai,singbox只有ehentai_wireguard_out_IPv4_route，最后只能一次性添加，才能正常

 
```
Xray-core
[
  "geosite:netflix",
  "geosite:openai",
  "geosite:ehentai"
]
sing-box
{
  "rule_set": [
    "ehentai_wireguard_out_IPv4_route"
  ],
  "domain_regex": [],
  "outbound": "wireguard_out_IPv4"


```

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.3.4
