### ISSUE TITLE
同时使用cloudreve的webdav协议405问题

### ISSUE THREAD

**Issue by tidehc** [mack-a/v2ray-agent#996]
vps开了一个网盘
cloudreve正常配置以后
在ngixn配置中xray相应server下注释了 root 同时增加如下

       location / {
               proxy_set_header X-Forwarded-For 127.0.0.1;
               proxy_set_header     Host    $http_host;
               proxy_redirect       off;
               proxy_pass http://127.0.0.1:5212;
               client_max_body_size 4G;
       }
通过web443访问cloudreve的服务以及上传下载文件都不成问题
但当使用raidrive或者winscp通过webdav协议访问cloudreve时出现 405 not allowed
关了xray，直接使用nginx则可以

**Comment by mack-a** [comment]
没有用过你提到的东西，可以去xray问一下。
