### ISSUE TITLE
singbox订阅的QR code无法被singbox客户端识别

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#997]
## 1.问题描述
singbox订阅的QR code无法被singbox客户端识别
## 2.安装失败的log或者截图
无
## 3.系统版本
ubuntu20.04
## 5.安装的内核、协议、安装方式
- 核心（xray-core、sing-box）
```
sing-box
```  
- 协议(VLESS+TLS_Vision+TCP)
```
Hysteria2 VLESS+Reality+Vision VLESS+Reality+gRPC Tuic
```  
- 安装方式（1.全部安装、2.任意组合安装）
```
2.任意组合安装
```

**Comment by mack-a** [comment]
singbox客户端指的是哪一个客户端。

**Comment by bettswang** [comment]
官方的客户端，singbox for android ， v1.8.10

**Comment by mack-a** [comment]
建议使用remote来拉取订阅，扫码问题可以问一下客户端。
