### ISSUE TITLE
无法UDP转发（ VLESS+TLS_Vision+TCP 、VLESS+TLS+WS ）

### ISSUE THREAD

**Issue by Accademia** [mack-a/v2ray-agent#998]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、[八合一脚本从入门到精通](https://www.v2ray-agent.com/archives/1710141233)。

如果低版本升级高版本出现问题，建议使用**20.卸载脚本**卸载后重新安装

## 1.问题描述

0.VLESS+TLS_Vision+TCP[推荐]
1.VLESS+TLS+WS[仅CDN推荐]

这两个配置，配置后，无法转发UDP转发（不支持Fullcone）

 - NatTypeTester：测试NAT类型，显示为UnsupportedServer类型。

 - Stash for iOS：同样也显示 UDP = bad udp address

.
## 2.安装失败的log或者截图
安装成功，未出现异常LOG

.
## 3.系统版本
搬瓦工Ubuntu 20、22默认版本，都安装过，均显示UnsupportedServer

.
## 4.脚本版本
最新版 （v1.18.2）

.
## 5.安装的内核、协议、安装方式
- 核心
```
Xray-Code
```  
- 协议
```
- 0.VLESS+TLS_Vision+TCP[推荐]
- 1.VLESS+TLS+WS[仅CDN推荐]
```  
- 安装方式
```
任意组合安装
```  

.
## 6.客户端
Clash Verge Rev 1.5.11（2024-04-03最新版）
V2rayN 6.42（2024-04-03最新版）

.
## 7. 希望修复的BUG
目前[mack-a](https://github.com/mack-a)
不支持FullCone，希望能够支持Full Cone，能够让 NatTypeTester的NAT类型测试，不 不 不 显示为UnsupportedServer类型。从而实现游戏代理。

**Comment by mack-a** [comment]
https://github.com/XTLS/Xray-core/discussions/252 参考

**Comment by Accademia** [comment]
> [XTLS/Xray-core#252](https://github.com/XTLS/Xray-core/discussions/252) 参考

大佬，没搞懂，要怎么使用配置脚本，才能支持UDP和FullCone？是说下面这两个配置，因为没有使用XTLS，所以不支持FullCone？

0.VLESS+TLS_Vision+TCP[推荐]
1.VLESS+TLS+WS[仅CDN推荐]

比较想知道，用哪个配置，可以默认支持FullCone
