### ISSUE TITLE
添加alpine系统支持

### ISSUE THREAD

**Issue by QAQ5555** [mack-a/v2ray-agent#999]
**详细描述建议的内容**
本脚本不支持此系统，请将下方日志反馈给开发者
Welcome to Alpine Linux 3.18 on an \m (\l) Linux version 6.5.11-8-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-8 (2024-01-30T12:27Z)

**Comment by AgathonLi** [comment]
附议，Alpine系统真的干净好用，能添加支持就太好了

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.42

**Comment by WoChen5770** [comment]
最新脚本还是不行哦
```
本脚本不支持此系统，请将下方日志反馈给开发者
 
Welcome to Alpine Linux 3.16
 on an \m (\l) 
Linux version 5.15.131-2-pve (build@proxmox) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PVE 5.15.131-3 (2023-12-01T13:42Z) 
```
